Text_SwordsDanceTeach::
    .string "Ikke mange kommer herud.\p"
    .string "Hvis jeg traener her, er jeg overbevist om at\n"
    .string "jeg bliver staerkere og staerkere.\p"
    .string "Ja, staerkere og staerkere…\p"
    .string "Vil du laere et traek som det?\n"
    .string "Det er SWORDS DANCE.$"

Text_SwordsDanceDeclined::
    .string "Ja, det er ogsaa fint.$"

Text_SwordsDanceWhichMon::
    .string "Okay, vaelg hvilken POKeMON\n"
    .string "jeg skal laere det.$"

Text_SwordsDanceTaught::
    .string "Hvis bare vi kunne blive ved med at blive\n"
    .string "staerkere og staerkere, hva?$"

SevenIsland_Text_IslandSign::
    .string "SEVEN ISLAND\n"
    .string "Opgaveoeen med uendelighed$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "Disse oeer kaldes SEVII ISLANDS\n"
    .string "fordi der er syv.\p"
    .string "…Eller det er i hvert fald hvad de unge\n"
    .string "tror.\p"
    .string "Sandheden er at disse oeer er opkaldt\n"
    .string "saa fordi de siges at vaere lavet\l"
    .string "paa syv dage.$"

SevenIsland_Text_IslandVirtuallyUntouched::
    .string "Denne oe er blevet naesten uberoert\n"
    .string "i sin naturlige tilstand.\p"
    .string "Det kan vaere lidt vanskeligt at\n"
    .string "vandre rundt paa grund af det.$"

