Text_SwordsDanceTeach::
    .string "Ikke mange kommer herud.\p"
    .string "Hvis jeg träner her, er jeg overbevist om at\n"
    .string "jeg bliver stärkere og stärkere.\p"
    .string "Ja, stärkere og stärkere…\p"
    .string "Vil du läre et träk som det?\n"
    .string "Det er SWORDS DANCE.$"

Text_SwordsDanceDeclined::
    .string "Ja, det er ogsâ fint.$"

Text_SwordsDanceWhichMon::
    .string "Okay, välg hvilken POKéMON\n"
    .string "jeg skal läre det.$"

Text_SwordsDanceTaught::
    .string "Hvis bare vi kunne blive ved med at blive\n"
    .string "stärkere og stärkere, hva?$"

SevenIsland_Text_IslandSign::
    .string "SEVEN ISLAND\n"
    .string "Opgaveöen med uendelighed$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "Disse öer kaldes SEVII ISLANDS\n"
    .string "fordi der er syv.\p"
    .string "…Eller det er i hvert fald hvad de unge\n"
    .string "tror.\p"
    .string "Sandheden er at disse öer er opkaldt\n"
    .string "sâ fordi de siges at väre lavet\l"
    .string "pâ syv dage.$"

SevenIsland_Text_IslandVirtuallyUntouched::
    .string "Denne ö er blevet nästen uberört\n"
    .string "i sin naturlige tilstand.\p"
    .string "Det kan väre lidt vanskeligt at\n"
    .string "vandre rundt pâ grund af det.$"

