Text_SwordsDanceTeach::
    .string "Ikke mange kommer herud.\p"
    .string "Hvis jeg træner her, er jeg overbevist om at\n"
    .string "jeg bliver stærkere og stærkere.\p"
    .string "Ja, stærkere og stærkere…\p"
    .string "Vil du lære et træk som det?\n"
    .string "Det er SWORDS DANCE.$"

Text_SwordsDanceDeclined::
    .string "Ja, det er ogsâ fint.$"

Text_SwordsDanceWhichMon::
    .string "Okay, vælg hvilken POKéMON\n"
    .string "jeg skal lære det.$"

Text_SwordsDanceTaught::
    .string "Hvis bare vi kunne blive ved med at blive\n"
    .string "stærkere og stærkere, hva?$"

SevenIsland_Text_IslandSign::
    .string "SEVEN ISLAND\n"
    .string "Opgaveøen med uendelighed$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "Disse øer kaldes SEVII ISLANDS\n"
    .string "fordi der er syv.\p"
    .string "…Eller det er i hvert fald hvad de unge\n"
    .string "tror.\p"
    .string "Sandheden er at disse øer er opkaldt\n"
    .string "sâ fordi de siges at være lavet\l"
    .string "pâ syv dage.$"

SevenIsland_Text_IslandVirtuallyUntouched::
    .string "Denne ø er blevet næsten uberørt\n"
    .string "i sin naturlige tilstand.\p"
    .string "Det kan være lidt vanskeligt at\n"
    .string "vandre rundt pâ grund af det.$"

