OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
    .string "BILL: Hej der!\n"
    .string "CELIO!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
    .string "CELIO: BILL!\n"
    .string "Jeg kan ikke tro du kom herud.$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
    .string "BILL: Ja, helt sikkert!\n"
    .string "Hvordan gâr din forskning?\p"
    .string "…Oh, vent lige.$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
    .string "{PLAYER}, dette er min ven CELIO.\n"
    .string "Han er en dedikeret PC-MANIAC!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
    .string "CELIO, dette er {PLAYER}, en stigende\n"
    .string "udfordrer som POKéMON-mester!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
    .string "CELIO, dette er {PLAYER}, den\n"
    .string "regerende POKéMON-mester!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
    .string "CELIO: Det er virkelig imponerende.\p"
    .string "Jeg hader at sige det, men jeg har\n"
    .string "nul anlæg for kamp.\p"
    .string "Men jeg er glad for at møde dig.$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
    .string "BILL: Sa opdater mig.\n"
    .string "Hvordan kører din maskine?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
    .string "CELIO: Den kører fint, men vi er\n"
    .string "for afsides herude.\p"
    .string "PC'erne pâ denne ø kan bare ikke\n"
    .string "forbinde til din PC, BILL.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
    .string "BILL: Oh ja?\n"
    .string "Okay, lad mig tage et kig.\p"
    .string "…Vent lige…\n"
    .string "Jeg tror vi kan fâ det til at virke.\l"
    .string "Lad mig hjælpe dig, okay?$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
    .string "{PLAYER}, kan du vente pâ mig\n"
    .string "bare lidt?\p"
    .string "…Faktisk, kan du gøre mig en\n"
    .string "tjeneste?\p"
    .string "Øen ved siden af hedder\n"
    .string "TWO ISLAND.\p"
    .string "Der er en fyr der kører et\n"
    .string "GAME CORNER.\p"
    .string "Han er vild med sjældne sten\n"
    .string "og ædelstene.\p"
    .string "Vi holder kontakten som\n"
    .string "med-maniacs.\p"
    .string "Sâ kan du levere denne\n"
    .string "METEORITE til ham?$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
    .string "{PLAYER} modtog METEORITEN\n"
    .string "fra BILL.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
    .string "CELIO: {PLAYER}, hvis du tager til\n"
    .string "TWO ISLAND, tag dette med.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
    .string "Det er et PASS til færgeen der\n"
    .string "betjener de lokale øer.\p"
    .string "Det lader dig rejse mellem\n"
    .string "ISLAND ONE, TWO og THREE.\p"
    .string "Oh, du skal ogsâ have dette.$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
    .string "{PLAYER} modtog en ekstra side\n"
    .string "til BYKORTET!$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
    .string "{PLAYER} modtog\n"
    .string "et BYKORT!$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
    .string "BILL: Vi ses!\n"
    .string "Hils ham fra mig!$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
    .string "Hmm…\p"
    .string "Hvad med at vi prøver sâdan…$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
    .string "Oh, hej {PLAYER}!\p"
    .string "Sâ du det?\n"
    .string "Vi fik PC'en til at virke!\p"
    .string "Jeg har noget at vise CELIO her.\p"
    .string "Kan du gâ en tur eller noget\n"
    .string "endnu en tid?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .string "Undskyld at jeg tog sâ meget af\n"
    .string "BILLs tid.\p"
    .string "Undskyld ogsâ at jeg var sâdan en\n"
    .string "dârlig vært pâ dit besøg her.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
    .string "De sædvanlige PC-tjenester er\n"
    .string "ikke tilgængelige…$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
    .string "BILL: Oh, hej!\n"
    .string "{PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
    .string "BILL: Hvad tog sâ længe?\n"
    .string "Havde du det hyggeligt?\p"
    .string "Vi fik det færdigt.\n"
    .string "PC'erne kører!$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
    .string "CELIO: Opgaven gik utroligt\n"
    .string "hurtigt.\p"
    .string "BILL er fantastisk…$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
    .string "BILL: Nej, nej! Der var næsten\n"
    .string "intet tilbage til mig.\p"
    .string "CELIO, jeg mâ give dig ros.\n"
    .string "Du har lært meget.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
    .string "CELIO: Oh virkelig?\n"
    .string "Ehehe…$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
    .string "BILL: Nâ, sa er vi der.\n"
    .string "Jeg er færdig med opgaven.\l"
    .string "Vi bør tage tilbage til KANTO.\p"
    .string "CELIO, vi ses igen.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
    .string "CELIO: {PLAYER}, jeg er virkelig\n"
    .string "ked af vi sendte dig afsted alene i dag.\p"
    .string "Jeg lover at vise dig rundt pâ\n"
    .string "disse øer en gang.$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
    .string "CELIO: Hej!\n"
    .string "Du ser frygtelig travl ud som altid.\p"
    .string "Hvordan gâr det for mig?\p"
    .string "Jeg modificerer min Netværks-\n"
    .string "maskine.\p"
    .string "Nâr jeg er færdig med maskinen,\n"
    .string "hâber jeg du vil bruge den først,\l"
    .string "{PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
    .string "CELIO: {PLAYER}, hvordan har det\n"
    .string "været for dig?\p"
    .string "Oh, virkelig?\n"
    .string "Du har fanget flere POKéMON.\p"
    .string "Ved du hvad?\n"
    .string "Mâske jeg kan være nyttig for dig.$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
    .string "Jeg modificerer Netværksmaskinen\n"
    .string "lige nu.\p"
    .string "Jeg ændrer den sâ den kan hândtere\n"
    .string "bytter over lange afstande.\p"
    .string "Nâr jeg er færdig, kan du\n"
    .string "bytte exotiske POKéMON med\l"
    .string "TRAINERE langt væk.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
    .string "Men der er en lille ulempe.\p"
    .string "For at forbindelsen virker, skal\n"
    .string "maskinen bruge en særlig ædelsten.\p"
    .string "Den skulle være pâ ONE ISLAND,\n"
    .string "men jeg har ikke fundet en endnu.\p"
    .string "Hvem ved hvor den kunne være.$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
    .string "Jeg forsøgte at finde ædelstenen\n"
    .string "mens jeg studerede.\p"
    .string "Som resultat er jeg ikke kommet\n"
    .string "videre i søgning eller studier…\p"
    .string "Hvis jeg stolede pâ BILL, ville\n"
    .string "min forskning sikkert fremskride.\p"
    .string "Men denne gang vil jeg prøve at\n"
    .string "gøre tingene selv.$"

OneIsland_PokemonCenter_1F_Text_OhThats::
    .string "Oh!\n"
    .string "D-det er…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
    .string "{PLAYER} gav RUBINEN\n"
    .string "til CELIO.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
    .string "Tak!\n"
    .string "{PLAYER}, du er simpelthen fantastisk.\p"
    .string "… … …  … … …\p"
    .string "Øh… Mâ jeg bede om endnu en kæmpe\n"
    .string "tjeneste?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
    .string "Det… Det er ikke noget mærkeligt.\n"
    .string "Jeg har brug for din hjælp!$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
    .string "Mens jeg studerede ædelstene,\n"
    .string "opdagede jeg noget vigtigt.\p"
    .string "Der er en anden ædelsten der danner\n"
    .string "et par med denne RUBIN.\p"
    .string "Den anden ædelsten skulle være\n"
    .string "i SEVII ISLANDS.\p"
    .string "{PLAYER}, ga venligst og find\n"
    .string "den anden ædelsten.\p"
    .string "{PLAYER}, mâ jeg fâ din færge-\n"
    .string "PASS og BYKORTET?$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
    .string "{PLAYER} afleverede TRI-PASS og\n"
    .string "modtog RAINBOW PASS.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
    .string "Fik en ekstra side til BYKORTET!$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
    .string "Dette er min egen færge-PASS.\p"
    .string "Den lader dig komme til alle\n"
    .string "SEVII ISLANDS.\p"
    .string "{PLAYER}, jeg kan ikke gøre det\n"
    .string "uden din hjælp.$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
    .string "{PLAYER} gav SAPFIREN\n"
    .string "til CELIO.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
    .string "CELIO: Sâ dette er ædelstenen der\n"
    .string "danner par med RUBINEN…\p"
    .string "{PLAYER}, du har været igennem meget\n"
    .string "for at fa dette, ikke?\p"
    .string "Du behøver ikke fortælle mig. Jeg ved\n"
    .string "det var ikke nemt.\p"
    .string "Mange tak!\p"
    .string "Nu er det min tur at arbejde for dig!\n"
    .string "Giv mig venligst lidt tid.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .string "Okay, det er godt…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .string "Jeg gjorde det!\n"
    .string "Jeg er forbundet med LANETTE!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .string "{PLAYER}…\n"
    .string "{PLAYER}, jeg gjorde det!\p"
    .string "Jeg fik forbundet med TRAINERE\n"
    .string "i HØNN-regionen!\p"
    .string "Endelig er Netværksmaskinen\n"
    .string "fuldt operationel!\p"
    .string "{PLAYER}, jeg skylder det alt til dig!\p"
    .string "Takket være dig blev min drøm\n"
    .string "til virkelighed…$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .string "Jeg…\n"
    .string "Jeg græder ikke.\p"
    .string "Nok om mig!\p"
    .string "{PLAYER}, du bliver ved med at\n"
    .string "lede efter exotiske POKéMON, ikke?\p"
    .string "Jeg ønsker dig al mulig held!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .string "CELIO: Hej!\p"
    .string "{PLAYER}, jeg har hørt rygter\n"
    .string "om dig.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .string "{PLAYER}, hvad er din yndlings-\n"
    .string "POKéMON?\p"
    .string "BILL er en POKeMANIAC, sâ han\n"
    .string "elsker alle slags.\p"
    .string "Åbenbart var den første han\n"
    .string "fangede en ABRA.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .string "For resten, {PLAYER}, du er fra\n"
    .string "PALLET TOWN, ikke?\p"
    .string "Jeg har hørt at det er et stille og\n"
    .string "behageligt sted.\p"
    .string "BILLs hjemby er GOLDENROD CITY,\n"
    .string "hvor hans forældre stadig bor.\p"
    .string "Jeg har hørt at det er en festlig,\n"
    .string "livlig by.\p"
    .string "Jeg vil gerne derhen en dag.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .string "{PLAYER}, er der noget du\n"
    .string "slet ikke kan li?\p"
    .string "Åbenbart kan BILL slet ikke\n"
    .string "tâle mælk.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .string "Oh, du er fremmed her!\n"
    .string "Hej! Hvor kom du fra?\p"
    .string "…PALLET TOWN?\n"
    .string "Jeg kender den ikke!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .string "Pâ denne ø er der en kæmpe\n"
    .string "vulkan.\p"
    .string "Den har ikke udbrudt for nylig,\n"
    .string "sâ hvorfor ikke nyde en vandring?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .string "Jeg ville ønske jeg kunne bytte\n"
    .string "POKéMON med min kæreste langt væk…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .string "Jeg byttede POKéMON med min kæreste\n"
    .string "langt væk!\p"
    .string "Alle siger at vi kan takke dig\n"
    .string "og CELIO.\p"
    .string "Sâ tak!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .string "Netværksmaskine\n"
    .string "Link Niveau 0\p"
    .string "…POKéMON-opbevaring under\n"
    .string "justering…$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .string "Netværksmaskine\n"
    .string "Link Niveau 1\p"
    .string "Forbindelse etableret med KANTO-\n"
    .string "regionen.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .string "Netværksmaskine\n"
    .string "Link Niveau 2\p"
    .string "Forbindelse etableret med KANTO-\n"
    .string "og HØNN-regionerne.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
    .string "Fik TRI-PASS!$"

