SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Sssh!\n"
    .string "Kan du ikke se jeg gemmer mig?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "Hva?\n"
    .string "TEAM ROCKET er väk?$"

SilphCo_4F_Text_Grunt1Intro::
    .string "TEAM ROCKET har taget kontrol\n"
    .string "over SILPH CO.!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "Fwahahaha!\n"
    .string "Min BOSS har jaget dette sted!$"

SilphCo_4F_Text_RodneyIntro::
    .string "Mit POKéMON er min loyale tjener.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "Pokkers!\n"
    .string "I svâge POKéMON!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "Dörene er elektronisk\n"
    .string "lâst.\p"
    .string "Det kräver en CARD KEY for at âbne\n"
    .string "dörene her.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "Indtränger spottet!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "Hvem er du?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "Jeg bör fortälle BOSS pâ 11. sal!$"

SilphCo_4F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "4. SAL$"

