SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Sssh!\n"
    .string "Kan du ikke se jeg gemmer mig?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "Hva?\n"
    .string "TEAM ROCKET er vaek?$"

SilphCo_4F_Text_Grunt1Intro::
    .string "TEAM ROCKET har taget kontrol\n"
    .string "over SILPH CO.!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "Fwahahaha!\n"
    .string "Min BOSS har jaget dette sted!$"

SilphCo_4F_Text_RodneyIntro::
    .string "Mit POKeMON er min loyale tjener.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "Pokkers!\n"
    .string "I svaage POKeMON!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "Doerene er elektronisk\n"
    .string "laast.\p"
    .string "Det kraever en CARD KEY for at aabne\n"
    .string "doerene her.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "Indtraenger spottet!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "Hvem er du?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "Jeg boer fortaelle BOSS paa 11. sal!$"

SilphCo_4F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "4. SAL$"

