PokemonMansion_1F_Text_TedIntro::
    .string "Hvem er du?\n"
    .string "Der burde ikke vaere nogen her.$"

PokemonMansion_1F_Text_TedDefeat::
    .string "Av!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "En noegle? Jeg ved ikke hvad du\n"
    .string "taler om.$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "V-v-vah! Du skraemte mig!\n"
    .string "Jeg troede du var et spoegelse.$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "Tch!\n"
    .string "Jeg kan ikke faa nogle sejre.$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "Jeg udforskede her alene,\n"
    .string "men jeg foeler mig skraemt.\p"
    .string "Jeg boer ga snart.$"
