PokemonMansion_1F_Text_TedIntro::
    .string "Hvem er du?\n"
    .string "Der burde ikke være nogen her.$"

PokemonMansion_1F_Text_TedDefeat::
    .string "Av!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "En nøgle? Jeg ved ikke hvad du\n"
    .string "taler om.$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "V-v-vah! Du skræmte mig!\n"
    .string "Jeg trøde du var et spøgelse.$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "Tch!\n"
    .string "Jeg kan ikke fâ nogle sejre.$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "Jeg udforskede her alene,\n"
    .string "men jeg føler mig skræmt.\p"
    .string "Jeg bør ga snart.$"
