PokemonMansion_1F_Text_TedIntro::
    .string "Hvem er du?\n"
    .string "Der burde ikke väre nogen her.$"

PokemonMansion_1F_Text_TedDefeat::
    .string "Av!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "En nögle? Jeg ved ikke hvad du\n"
    .string "taler om.$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "V-v-vah! Du skrämte mig!\n"
    .string "Jeg tröde du var et spögelse.$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "Tch!\n"
    .string "Jeg kan ikke fâ nogle sejre.$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "Jeg udforskede her alene,\n"
    .string "men jeg föler mig skrämt.\p"
    .string "Jeg bör ga snart.$"
