SixIsland_GreenPath_Text_JaclynIntro::
    .string "…Hva?\p"
    .string "Jeg forestillede mig mit hus, men\n"
    .string "det er her jeg TELEPORTERER?$"

SixIsland_GreenPath_Text_JaclynDefeat::
    .string "Stor bølle!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
    .string "Jeg er sâ forstrøt!\p"
    .string "Jeg skal fokusere sâ jeg kan\n"
    .string "TELEPORTERE ordentligt til mit hus!$"

SixIsland_GreenPath_Text_LeftRouteSign::
    .string "GREEN PATH\n"
    .string "PATTERN BUSH FORUDE$"

SixIsland_GreenPath_Text_RightRouteSign::
    .string "GREEN PATH\n"
    .string "Tænk grønt, hold naturen ren!$"

