SixIsland_GreenPath_Text_JaclynIntro::
    .string "…Hva?\p"
    .string "Jeg forestillede mig mit hus, men\n"
    .string "det er her jeg TELEPORTERER?$"

SixIsland_GreenPath_Text_JaclynDefeat::
    .string "Stor boelle!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
    .string "Jeg er saa forstroet!\p"
    .string "Jeg skal fokusere saa jeg kan\n"
    .string "TELEPORTERE ordentligt til mit hus!$"

SixIsland_GreenPath_Text_LeftRouteSign::
    .string "GREEN PATH\n"
    .string "PATTERN BUSH FORUDE$"

SixIsland_GreenPath_Text_RightRouteSign::
    .string "GREEN PATH\n"
    .string "Taenk groent, hold naturen ren!$"

