FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "VOGTER: Hif fuff hefifoo!\p"
    .string "Ha lof ha feef ee hafahi ho.\n"
    .string "Heff hee fwee!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "Ah howhee ho hoo!\n"
    .string "Eef ee hafahi ho!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "Ha?\n"
    .string "He ohay heh ha hoo ee haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER} gav GULDTÆNDERNE\n"
    .string "til VOGTEREN.$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "VOGTEREN satte tænderne i!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "VOGTER: Tak, søn!\n"
    .string "Du er en rigtig livredder!\p"
    .string "Ingen kunne forstâ et ord af hvad\n"
    .string "jeg sagde!\p"
    .string "Jeg skammede mig over at vise mig\n"
    .string "i KONTORET.\p"
    .string "Lad mig give dig noget for besværet.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "VOGTER: Tak, tøs!\n"
    .string "Du er en rigtig livredder!\p"
    .string "Ingen kunne forstâ et ord af hvad\n"
    .string "jeg sagde!\p"
    .string "Jeg skammede mig over at vise mig\n"
    .string "i KONTORET.\p"
    .string "Lad mig give dig noget for besværet.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER} modtog HM04\n"
    .string "fra VOGTEREN.$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "VOGTER: I HM04 findes STRENGTH.\p"
    .string "Det lader POKéMON flytte kampesten\n"
    .string "uden for kamp.\p"
    .string "Aa ja, fandt du det hemmelige\n"
    .string "HUS i SAFARI ZONE?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "POKéMON-fotos og fossiler er\n"
    .string "udstillet.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "Gammel POKéMON-merchandise er\n"
    .string "udstillet.$"

