SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "…Vent! Sig ikke et ord!\p"
    .string "Du ville have dette!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} modtog TM29\n"
    .string "fra MR. PSYCHIC.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "Du ved det allerede, ikke?\n"
    .string "TM29 er PSYCHIC.\p"
    .string "Det er et angreb der ogsâ kan\n"
    .string "sænke mâlets specialstats.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Hvor vil du putte dette?\n"
    .string "Du har ikke plads.$"

