RockTunnel_B1F_Text_SofiaIntro::
    .string "Ved du hvordan du undgâr at fare vild\n"
    .string "i bjergene?\p"
    .string "Du kan bøje kviste som\n"
    .string "stimmærkninger.$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "Aahh!\n"
    .string "Jeg gjorde mit bedste!$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "Jeg vil hjem!$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "Hahaha!\n"
    .string "Kan du slâ min styrke?$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "Ups!\n"
    .string "Overmandet!$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "Jeg gâr efter styrke fordi jeg hader\n"
    .string "at tænke.$"

RockTunnel_B1F_Text_CooperIntro::
    .string "Du har en POKéDEX?\n"
    .string "Jeg vil ogsâ have een.$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "Shoot!\n"
    .string "Jeg er sâ misundelig!$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "Nâr du er færdig med din POKéDEX,\n"
    .string "kan jeg fâ den?$"

RockTunnel_B1F_Text_SteveIntro::
    .string "Øh… Ved du noget om POKéMON\n"
    .string "cosplay?$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "Nâ, det var det.$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "POKéMON cosplay er at klæde sig ud som\n"
    .string "POKéMON for sjov.\p"
    .string "CLEFAIRY er en favorit.$"

RockTunnel_B1F_Text_AllenIntro::
    .string "Mine POKéMON teknikker vil fâ\n"
    .string "dig til at græde!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "Jeg giver op!\n"
    .string "Du er en bedre tekniker!$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "I bjerge finder du ofte\n"
    .string "ROCK-type POKéMON.$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "Jeg kommer ikke ofte her, men jeg\n"
    .string "vil kæmpe mod dig.$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "Aah!\n"
    .string "Jeg tabte!$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "Jeg kan lide smâ POKéMON.\n"
    .string "Store er for skræmmende!$"

RockTunnel_B1F_Text_EricIntro::
    .string "Ram mig med dit bedste skud!$"

RockTunnel_B1F_Text_EricDefeat::
    .string "Afskaffet!$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "Jeg opdrager mine POKéMON til at slâ\n"
    .string "dine, unge.$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "Jeg tegner illustrationer af POKéMON\n"
    .string "nâr jeg er hjemme.$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "Puha…\n"
    .string "Jeg er udmattet…$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "Jeg er kunstner, ikke kæmper.\n"
    .string "Jeg gâr hjem for at tegne.$"
