RockTunnel_B1F_Text_SofiaIntro::
    .string "Ved du hvordan du undgaar at fare vild\n"
    .string "i bjergene?\p"
    .string "Du kan boeje kviste som\n"
    .string "stimmaerkninger.$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "Aahh!\n"
    .string "Jeg gjorde mit bedste!$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "Jeg vil hjem!$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "Hahaha!\n"
    .string "Kan du slaa min styrke?$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "Ups!\n"
    .string "Overmandet!$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "Jeg gaar efter styrke fordi jeg hader\n"
    .string "at taenke.$"

RockTunnel_B1F_Text_CooperIntro::
    .string "Du har en POKeDEX?\n"
    .string "Jeg vil ogsaa have een.$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "Shoot!\n"
    .string "Jeg er saa misundelig!$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "Naar du er faerdig med din POKeDEX,\n"
    .string "kan jeg faa den?$"

RockTunnel_B1F_Text_SteveIntro::
    .string "Oeh… Ved du noget om POKeMON\n"
    .string "cosplay?$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "Naa, det var det.$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "POKeMON cosplay er at klaede sig ud som\n"
    .string "POKeMON for sjov.\p"
    .string "CLEFAIRY er en favorit.$"

RockTunnel_B1F_Text_AllenIntro::
    .string "Mine POKeMON teknikker vil faa\n"
    .string "dig til at graede!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "Jeg giver op!\n"
    .string "Du er en bedre tekniker!$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "I bjerge finder du ofte\n"
    .string "ROCK-type POKeMON.$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "Jeg kommer ikke ofte her, men jeg\n"
    .string "vil kaempe mod dig.$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "Aah!\n"
    .string "Jeg tabte!$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "Jeg kan lide smaa POKeMON.\n"
    .string "Store er for skraemmende!$"

RockTunnel_B1F_Text_EricIntro::
    .string "Ram mig med dit bedste skud!$"

RockTunnel_B1F_Text_EricDefeat::
    .string "Afskaffet!$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "Jeg opdrager mine POKeMON til at slaa\n"
    .string "dine, unge.$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "Jeg tegner illustrationer af POKeMON\n"
    .string "naar jeg er hjemme.$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "Puha…\n"
    .string "Jeg er udmattet…$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "Jeg er kunstner, ikke kaemper.\n"
    .string "Jeg gaar hjem for at tegne.$"
