CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MEOWTH: Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "Du bör ikke bruge alle dine penge\n"
    .string "pâ drikkevarer.\p"
    .string "Pröv dette i stedet.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Intet slâer törst som varm\n"
    .string "TEA.\p"
    .string "Det er virkelig det bedste.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "Mine kere POKéMON holder mig selskab.\n"
    .string "MEOWTH bräger endda penge hjem!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Aah, hej, kere.\n"
    .string "Nöd du min TEA?\p"
    .string "For resten, kere. Er du tilfäldigvis\n"
    .string "fra PALLET TOWN?\p"
    .string "En pige fra PALLET TOWN, DAISY,\n"
    .string "hun nyder TEA hver dag.\p"
    .string "Hun besöger CELADON DEPT. STORE\n"
    .string "for at köbe TEA.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "CLEFAIRY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDORAN♀: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "CELADON MANSION\n"
    .string "Manager's Suite$"
