CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "En POKe FLUTE vaekker sovende\n"
    .string "POKeMON. Det ved du.\p"
    .string "Den goer det med en lyd som kun\n"
    .string "de kan hoere.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "Jeg cyklede her fra FUCHSIA.\p"
    .string "Det er opadbakke paa CYCLING\n"
    .string "ROAD, saa jeg er udmattet.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "Hvis jeg havde en BIKE, ville jeg tage\n"
    .string "til CYCLING ROAD!$"
