CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "En POKe FLUTE väkker sovende\n"
    .string "POKeMON. Det ved du.\p"
    .string "Den gör det med en lyd som kun\n"
    .string "de kan höre.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "Jeg cyklede her fra FUCHSIA.\p"
    .string "Det er opadbakke pâ CYCLING\n"
    .string "ROAD, sâ jeg er udmattet.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "Hvis jeg havde en BIKE, ville jeg tage\n"
    .string "til CYCLING ROAD!$"
