CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "En POKe FLUTE vækker sovende\n"
    .string "POKéMON. Det ved du.\p"
    .string "Den gør det med en lyd som kun\n"
    .string "de kan høre.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "Jeg cyklede her fra FUCHSIA.\p"
    .string "Det er opadbakke pâ CYCLING\n"
    .string "ROAD, sâ jeg er udmattet.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "Hvis jeg havde en BIKE, ville jeg tage\n"
    .string "til CYCLING ROAD!$"
