Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "Jeg er pâ en afslappet tur pâ min\n"
    .string "nye cykel med min käreste.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "Vi körer sammen pâ vores\n"
    .string "nye cykler.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "Lad os se hvad kikkerten viser...\p"
    .string "Det er CELADON DEPT. STORE!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "Lad os se hvad kikkerten viser...\p"
    .string "Der er en lang sti over vand\n"
    .string "langt väk.$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "Hej! Husker du mig?\n"
    .string "Jeg er en af PROF. OAKs assistenter.\p"
    .string "Hvis din POKéDEX har fulde data\n"
    .string "om 40 arter, skal jeg\l"
    .string "give dig en belönning.\p"
    .string "PROF. OAK betröde mig et\n"
    .string "AMULET COIN til dig.\p"
    .string "Sâ, {PLAYER}, lad mig spörge dig.\p"
    .string "Har du indsamlet data om mindst\n"
    .string "40 slags POKéMON?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "Super! Du har fanget eller ejet\n"
    .string "{STR_VAR_3} slags POKéMON!\p"
    .string "Tillykke!\n"
    .string "Her har du den!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "{PLAYER} modtog AMULET COIN\n"
    .string "fra assistenten.$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "Et AMULET COIN er en genstand en\n"
    .string "POKéMON kan bäre.\p"
    .string "Hvis POKéMON deltager i en vindende\n"
    .string "kamp, tjener du flere penge.$"
