FuchsiaCity_Text_DidYouTrySafariGame::
    .string "Prøvede du SAFARI GAME?\p"
    .string "Der er nogle sjælde POKéMON der\n"
    .string "kun kan fanges der.$"

FuchsiaCity_Text_SafariZoneZooInFront::
    .string "SAFARI ZONE har en zoo foran\n"
    .string "indgangen.\p"
    .string "Bagved er SAFARI GAME til at\n"
    .string "fange POKéMON.$"

FuchsiaCity_Text_WheresSara::
    .string "ERIK: Hvor er SARA?\n"
    .string "Jeg sagde jeg mødtes med hende her.$"

FuchsiaCity_Text_ItemBallInThere::
    .string "Den genstandskugle derinde…\n"
    .string "Ville du have den?\p"
    .string "Mig ogsâ!\n"
    .string "…Hvad? Det er en POKéMON?$"

FuchsiaCity_Text_CitySign::
    .string "FUCHSIA CITY\n"
    .string "Se! Det er passioneret pink!$"

FuchsiaCity_Text_SafariZoneSign::
    .string "POKéMON PARADIS\n"
    .string "SAFARI ZONE$"

FuchsiaCity_Text_SafariGameSign::
    .string "SAFARI GAME\n"
    .string "POKéMON-U-CATCH!$"

FuchsiaCity_Text_WardensHomeSign::
    .string "SAFARI ZONE\n"
    .string "WARDENS Hjem$"

FuchsiaCity_Text_SafariZoneOfficeSign::
    .string "POKéMON PARADIS!\n"
    .string "Velkommen til SAFARI ZONE!\l"
    .string "SAFARI ZONE KONTOR$"

FuchsiaCity_Text_GymSign::
    .string "FUCHSIA CITY POKéMON GYM\n"
    .string "LEDER: KOGA\l"
    .string "Den giftige ninjamester$"

FuchsiaCity_Text_ChanseySign::
    .string "Navn: CHANSEY\n"
    .string "At fange en er ren tilfældighed.$"

FuchsiaCity_Text_VoltorbSign::
    .string "Navn: VOLTORB\n"
    .string "Billedet af en POKe BALL.$"

FuchsiaCity_Text_KangaskhanSign::
    .string "Navn: KANGASKHAN\p"
    .string "En moderlig POKéMON der opdrager\n"
    .string "sine unger i en pung pâ maven.$"

FuchsiaCity_Text_SlowpokeSign::
    .string "Navn: SLOWPOKE\n"
    .string "Venlig og meget langsom.$"

FuchsiaCity_Text_LaprasSign::
    .string "Navn: LAPRAS\n"
    .string "AKA havets konge.$"

FuchsiaCity_Text_OmanyteSign::
    .string "Navn: OMANYTE\n"
    .string "En yderst sjælden POKéMON gen-\l"
    .string "regenereret fra et fossil.$"

FuchsiaCity_Text_KabutoSign::
    .string "Navn: KABUTO\n"
    .string "En yderst sjælden POKéMON gen-\l"
    .string "regenereret fra et fossil.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .string "Av, jeg ville ønske jeg var en\n"
    .string "KANGASKHAN-baby.\p"
    .string "Jeg ville elske at være erstatning\n"
    .string "for babyen…\p"
    .string "Og kæle i moder KANGASKHANs\n"
    .string "mavepung.\p"
    .string "Men kun POKéMON kan bruge\n"
    .string "teknikken SUBSTITUTE…\p"
    .string "Skal jeg lære SUBSTITUTE til\n"
    .string "en af dine POKéMON?$"

Text_SubstituteDeclined::
    .string "Øh, virkelig?\n"
    .string "SUBSTITUTE lyder sâ sjov…$"

Text_SubstituteWhichMon::
    .string "Hvilken POKéMON vil lære\n"
    .string "SUBSTITUTE?$"

Text_SubstituteTaught::
    .string "Mand, hvad jeg ikke ville give for\n"
    .string "at kravle ind i en KANGASKHAN-\n"
    .string "mavepung...$"

FuchsiaCity_Text_MyFatherIsGymLeader::
    .string "Min far er GYM LEDER i\n"
    .string "denne by.\p"
    .string "Jeg træner i at bruge GIFT-\n"
    .string "POKéMON ligesom min far.$"

