FuchsiaCity_Text_DidYouTrySafariGame::
    .string "Proevede du SAFARI GAME?\p"
    .string "Der er nogle sjaelde POKeMON der\n"
    .string "kun kan fanges der.$"

FuchsiaCity_Text_SafariZoneZooInFront::
    .string "SAFARI ZONE har en zoo foran\n"
    .string "indgangen.\p"
    .string "Bagved er SAFARI GAME til at\n"
    .string "fange POKeMON.$"

FuchsiaCity_Text_WheresSara::
    .string "ERIK: Hvor er SARA?\n"
    .string "Jeg sagde jeg moedtes med hende her.$"

FuchsiaCity_Text_ItemBallInThere::
    .string "Den genstandskugle derinde…\n"
    .string "Ville du have den?\p"
    .string "Mig ogsaa!\n"
    .string "…Hvad? Det er en POKeMON?$"

FuchsiaCity_Text_CitySign::
    .string "FUCHSIA CITY\n"
    .string "Se! Det er passioneret pink!$"

FuchsiaCity_Text_SafariZoneSign::
    .string "POKeMON PARADIS\n"
    .string "SAFARI ZONE$"

FuchsiaCity_Text_SafariGameSign::
    .string "SAFARI GAME\n"
    .string "POKeMON-U-CATCH!$"

FuchsiaCity_Text_WardensHomeSign::
    .string "SAFARI ZONE\n"
    .string "WARDENS Hjem$"

FuchsiaCity_Text_SafariZoneOfficeSign::
    .string "POKeMON PARADIS!\n"
    .string "Velkommen til SAFARI ZONE!\l"
    .string "SAFARI ZONE KONTOR$"

FuchsiaCity_Text_GymSign::
    .string "FUCHSIA CITY POKeMON GYM\n"
    .string "LEDER: KOGA\l"
    .string "Den giftige ninjamester$"

FuchsiaCity_Text_ChanseySign::
    .string "Navn: CHANSEY\n"
    .string "At fange en er ren tilfaeldighed.$"

FuchsiaCity_Text_VoltorbSign::
    .string "Navn: VOLTORB\n"
    .string "Billedet af en POKe BALL.$"

FuchsiaCity_Text_KangaskhanSign::
    .string "Navn: KANGASKHAN\p"
    .string "En moderlig POKeMON der opdrager\n"
    .string "sine unger i en pung paa maven.$"

FuchsiaCity_Text_SlowpokeSign::
    .string "Navn: SLOWPOKE\n"
    .string "Venlig og meget langsom.$"

FuchsiaCity_Text_LaprasSign::
    .string "Navn: LAPRAS\n"
    .string "AKA havets konge.$"

FuchsiaCity_Text_OmanyteSign::
    .string "Navn: OMANYTE\n"
    .string "En yderst sjaelden POKeMON gen-\l"
    .string "regenereret fra et fossil.$"

FuchsiaCity_Text_KabutoSign::
    .string "Navn: KABUTO\n"
    .string "En yderst sjaelden POKeMON gen-\l"
    .string "regenereret fra et fossil.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .string "Av, jeg ville oenske jeg var en\n"
    .string "KANGASKHAN-baby.\p"
    .string "Jeg ville elske at vaere erstatning\n"
    .string "for babyen…\p"
    .string "Og kaele i moder KANGASKHANs\n"
    .string "mavepung.\p"
    .string "Men kun POKeMON kan bruge\n"
    .string "teknikken SUBSTITUTE…\p"
    .string "Skal jeg laere SUBSTITUTE til\n"
    .string "en af dine POKeMON?$"

Text_SubstituteDeclined::
    .string "Oeh, virkelig?\n"
    .string "SUBSTITUTE lyder saa sjov…$"

Text_SubstituteWhichMon::
    .string "Hvilken POKeMON vil laere\n"
    .string "SUBSTITUTE?$"

Text_SubstituteTaught::
    .string "Mand, hvad jeg ikke ville give for\n"
    .string "at kravle ind i en KANGASKHAN-\n"
    .string "mavepung...$"

FuchsiaCity_Text_MyFatherIsGymLeader::
    .string "Min far er GYM LEDER i\n"
    .string "denne by.\p"
    .string "Jeg traener i at bruge GIFT-\n"
    .string "POKeMON ligesom min far.$"

