ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "Hej, der!\n"
    .string "Hvordan gâr det?\p"
    .string "Hvad laver jeg her, spørger du?\n"
    .string "Jeg leder efter guld!\p"
    .string "Nâr jeg finder rigdom, købe jeg\n"
    .string "et hus i KANTO.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "Hej, der! Hvordan gâr det?\n"
    .string "Hørte du? Jeg har fundet guld!\p"
    .string "Du huskede at jeg ledte efter det,\n"
    .string "ikke?\p"
    .string "Du kan ikke forestille dig hvor\n"
    .string "glad jeg er.\p"
    .string "Sâ viser jeg dig!\n"
    .string "Dette er til dig!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "Det er en NUGGET!\p"
    .string "Jeg kan ikke give dig nogen visdoms-\n"
    .string "nuggets, sâ det mâ gøre det!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "Ups, din TASKE er proppet fuld!\n"
    .string "Jeg giver dig den senere.$"

