ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "Hej, der!\n"
    .string "Hvordan gaar det?\p"
    .string "Hvad laver jeg her, spoerger du?\n"
    .string "Jeg leder efter guld!\p"
    .string "Naar jeg finder rigdom, koebe jeg\n"
    .string "et hus i KANTO.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "Hej, der! Hvordan gaar det?\n"
    .string "Hoerte du? Jeg har fundet guld!\p"
    .string "Du huskede at jeg ledte efter det,\n"
    .string "ikke?\p"
    .string "Du kan ikke forestille dig hvor\n"
    .string "glad jeg er.\p"
    .string "Saa viser jeg dig!\n"
    .string "Dette er til dig!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "Det er en NUGGET!\p"
    .string "Jeg kan ikke give dig nogen visdoms-\n"
    .string "nuggets, saa det maa goere det!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "Ups, din TASKE er proppet fuld!\n"
    .string "Jeg giver dig den senere.$"

