ThreeIsland_Text_IslandSign::
    .string "THREE ISLAND\n"
    .string "Slägtsöen med familiebând$"

ThreeIsland_Text_IslandBelongsToUs::
    .string "Hyahoo!\p"
    .string "Fra i dag tilhörer denne ö\n"
    .string "os!$"

ThreeIsland_Text_GoBackToKanto::
    .string "Vi har ikke brug for jer der bringer\n"
    .string "stöj og ballade her!\p"
    .string "Vi beder jer tage tilbage til\n"
    .string "KANTO!$"

ThreeIsland_Text_BossIsOnHisWay::
    .string "Hey, gâ og gräd et andet sted.\n"
    .string "Vores chef er pâ vej.\p"
    .string "Nâr han kommer, giver vi jer et\n"
    .string "k-rad motorcykelshow I ikke\l"
    .string "snart glemmer!$"

ThreeIsland_Text_GetOffIslandNow::
    .string "W-hvad!? Aldrig i livet!\n"
    .string "Forlad ön nu!$"

ThreeIsland_Text_WhosGonnaMakeMe::
    .string "Hvem skal tvinge mig?$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
    .string "Er du chefen?\n"
    .string "Tag tilbage til KANTO med det samme!$"

ThreeIsland_Text_JustGotHerePal::
    .string "Hah?\p"
    .string "Jeg er lige kommet, makker.\p"
    .string "Hvad er det for en fjendtlig holdning?\n"
    .string "Det er virkelig koldt af jer!$"

ThreeIsland_Text_FollowersRaisingHavoc::
    .string "Din flok tilhängere har lavet\n"
    .string "ballade pâ deres cykler.\p"
    .string "Har du nogen anelse om hvor meget\n"
    .string "besvär de har voldt os pâ\l"
    .string "ön?$"

ThreeIsland_Text_OughtToBeThankingUs::
    .string "Nej mand, jeg forstâr slet ikke.\p"
    .string "Se det her sted.\n"
    .string "Hvad gör I for underholdning?\p"
    .string "I burde takke os for at\n"
    .string "väkke denne sövnige landsby.\p"
    .string "Men hey, hvis I insisterer, kan I\n"
    .string "pröve at fâ os til at tage af sted.$"

ThreeIsland_Text_YouCowardsToughInPack::
    .string "Grr… I kujoner…\n"
    .string "Sâ hârde i flok…$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
    .string "Du, hvad glor du pâ?\n"
    .string "Ved du ikke det er uforskammet?\p"
    .string "Vil du göre noget ved det\n"
    .string "eller hvad?$"

ThreeIsland_Text_ThatsSmart::
    .string "Det er klogt.\n"
    .string "Hold din näse ude af det.$"

ThreeIsland_Text_Biker1Intro::
    .string "Heh, jeg kan lide din mod.\n"
    .string "Du taber penge til mig, men…$"

ThreeIsland_Text_Biker1Defeat::
    .string "Hva…\n"
    .string "Hvad er dette barn?!$"

ThreeIsland_Text_Biker1PostBattle::
    .string "Aah, mand…\n"
    .string "Vov ikke at grine!$"

ThreeIsland_Text_Biker2Intro::
    .string "Er du ikke fra KANTO?\n"
    .string "Du burde väre pâ vores side!$"

ThreeIsland_Text_Biker2Defeat::
    .string "Stop med at fjolle rundt!$"

ThreeIsland_Text_Biker2PostBattle::
    .string "Hvad er der galt med dig,\n"
    .string "blive sâ varm sâdan?\p"
    .string "Totalt uncool, mand!$"

ThreeIsland_Text_Biker3Intro::
    .string "Vi inviterede chefen herud,\n"
    .string "men du mâtte ödelägge det!\p"
    .string "Du gjorde os skamfulde, mand!$"

ThreeIsland_Text_Biker3Defeat::
    .string "… … …   … … …$"

ThreeIsland_Text_Biker3PostBattle::
    .string "Chef, jeg siger dig, du mâ\n"
    .string "göre noget ved dette barn!$"

ThreeIsland_Text_PaxtonIntro::
    .string "Jeg har set dig, og jeg vil sige\n"
    .string "du har gjort nok.\p"
    .string "Hvad er du, deres ven eller\n"
    .string "noget?\p"
    .string "Sâ gätter jeg pâ at du kämper\n"
    .string "mod mig i deres sted.$"

ThreeIsland_Text_PaxtonDefeat::
    .string "Okay, nok!\n"
    .string "Vi tager af sted som I ville!\p"
    .string "Vi er glade for at se det sidste\n"
    .string "af denne kedelige ö!$"

ThreeIsland_Text_PaxtonPostBattle::
    .string "Humph! Ja, bliv endelig hängende\n"
    .string "med disse bonderöve!$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
    .string "Tak! De banditter var ikke\n"
    .string "andet end ballade.\p"
    .string "Aah, se, din POKeMON blev skadet\n"
    .string "pâ min konto.$"

ThreeIsland_Text_GivenFullRestore::
    .string "{PLAYER} fik\n"
    .string "en FULL RESTORE.$"

ThreeIsland_Text_OhYourBagIsFull::
    .string "Aah?\n"
    .string "Din TASKE er fuld.$"

ThreeIsland_Text_YouveGotImpressiveMons::
    .string "Du har virkelig imponerende\n"
    .string "POKeMON med dig.$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
    .string "Det ville väre fantastisk hvis nogen\n"
    .string "sâ stärk som dig böde her.\p"
    .string "Jeg hâber du i det mindste bliver\n"
    .string "her et stykke tid.\p"
    .string "…Undskyld mig?\n"
    .string "Du leder efter LOSTELLE?\p"
    .string "LOSTELLE gik mod BOND\n"
    .string "BRIDGE for et stykke tid siden.$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
    .string "THREE ISLAND er faktisk den mest\n"
    .string "befolkede af öerne her.\p"
    .string "Stadig kunne den väre mindre sövnig.\p"
    .string "Men jeg vil ikke se banditter\n"
    .string "som de BIKERS her igen.$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
    .string "Jeg träner min DODUO i\n"
    .string "BERRY FOREST.\p"
    .string "Nâr den udvikler sig, spiller jeg\n"
    .string "et spil pâ TWO ISLAND.$"

ThreeIsland_Text_Doduo::
    .string "DODUO: Gigiih!$"

