CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "Det er et foto af BLAINE og\n"
    .string "MR. FUJI.\p"
    .string "De stâr skulder ved skulder\n"
    .string "med store grine.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "Vi studerer POKéMON grundigt\n"
    .string "hver dag.\p"
    .string "Folk bringer os ofte själdne POKéMON\n"
    .string "til undersögelse.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "Et foto af LABs grundläger…\n"
    .string "DR. FUJI?!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "POKéMON LAB\n"
    .string "Mödelokale$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "POKéMON LAB\n"
    .string "R & D Lokale$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "POKéMON LAB\n"
    .string "Testlokale$"
