CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "Det er et foto af BLAINE og\n"
    .string "MR. FUJI.\p"
    .string "De staar skulder ved skulder\n"
    .string "med store grine.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "Vi studerer POKeMON grundigt\n"
    .string "hver dag.\p"
    .string "Folk bringer os ofte sjaeldne POKeMON\n"
    .string "til undersoegelse.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "Et foto af LABs grundlaeger…\n"
    .string "DR. FUJI?!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "POKeMON LAB\n"
    .string "Moedelokale$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "POKeMON LAB\n"
    .string "R & D Lokale$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "POKeMON LAB\n"
    .string "Testlokale$"
