MtMoon_1F_Text_MarcosIntro::
    .string "WHOA!\n"
    .string "Du chokerede mig!\l"
    .string "…Oeh, du er bare et barn!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Wow!\n"
    .string "Chokeret igen!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "Börn som dig bör ikke vandre\n"
    .string "rundt her i mörket.$"

MtMoon_1F_Text_JoshIntro::
    .string "Kom du for at udforske hulen,\n"
    .string "ogsâ?$"

MtMoon_1F_Text_JoshDefeat::
    .string "At tabe stinker!\n"
    .string "Sâ uncool.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "Jeg kom hele vejen herned for at\n"
    .string "vise mig frem over for piger.$"

MtMoon_1F_Text_MiriamIntro::
    .string "Wow! Det er meget större herinde\n"
    .string "end jeg tröde!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Oeh!\n"
    .string "Jeg tabte!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "Hvordan kommer man ud herfra?\n"
    .string "Det er sâ stort, jeg kan fare vild.$"

MtMoon_1F_Text_JovanIntro::
    .string "Hvad!\n"
    .string "Sneg dig ikke op pâ mig!$"

MtMoon_1F_Text_JovanDefeat::
    .string "Mine POKeMON duer ikke!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "Jeg mâ finde stärkere POKeMON.\n"
    .string "Hvor mon de er?$"

MtMoon_1F_Text_IrisIntro::
    .string "Hvad?\n"
    .string "Jeg venter pâ mine venner finder\l"
    .string "mig her.$"

MtMoon_1F_Text_IrisDefeat::
    .string "Jeg tabte?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "Jeg kom fordi jeg hörte der er\n"
    .string "nogle meget själde fossiler her.$"

MtMoon_1F_Text_KentIntro::
    .string "Mistänkelige mänd er i hulen.\n"
    .string "Hvad med dig?$"

MtMoon_1F_Text_KentDefeat::
    .string "Du fik mig!$"

MtMoon_1F_Text_KentPostBattle::
    .string "Jeg sâ dem!\n"
    .string "Jeg er sikker pâ de er fra TEAM ROCKET!$"

MtMoon_1F_Text_RobbyIntro::
    .string "Du skal gennem denne hule for at\n"
    .string "nâ CERULEAN CITY.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "Jeg tabte.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "ZUBAT er hârd!\n"
    .string "Men fanger du en, kan du regne\l"
    .string "med den.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "Pas pâ!\n"
    .string "ZUBAT er en blodsuger!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Hej, jeg udgraver fossiler her\n"
    .string "under MT. MOON.\p"
    .string "Nogle gange hjälper BROCK fra\n"
    .string "PEWTER GYM mig.$"

