PokemonMansion_B1F_Text_LewisIntro::
    .string "Uh-oh…\n"
    .string "Hvor er jeg nu?$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "Awooh!$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "Du kan finde ting der ligger.\n"
    .string "Beboerne maa have efterladt dem.$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "Dette sted er ideelt til et lab.\n"
    .string "Se al denne plads.$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "Hvad var det for?$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "Jeg kan lide det her.\n"
    .string "Det er godt for mine studier.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "Dagbog: 1. sept\n"
    .string "MEWTWO er langt for kraeftig.\p"
    .string "Vi har ikke formaaet at daempe dens\n"
    .string "ondskabsfulde tendenser…$"
