SevenIsland_TrainerTower_Text_DarioIntro::
    .string "Jeg mærkede din tilnærmelse.$"

SevenIsland_TrainerTower_Text_DarioDefeat::
    .string "Giv op…$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .string "I din fremtid fornemmer jeg at du\n"
    .string "vil møde mange andre.\p"
    .string "Jeg tror I vil være forbundet med\n"
    .string "hinanden ved en underlig kraft.$"

SevenIsland_TrainerTower_Text_RodetteIntro::
    .string "Et sted pâ denne ø sover\n"
    .string "særlige POKéMON.$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .string "Hvilken fantastisk TRAINER!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .string "Et sted pâ denne ø sover\n"
    .string "særlige POKéMON.\p"
    .string "Kunne det være at de venter\n"
    .string "pâ dig?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .string "TRAINER TOWER INDGANG\n"
    .string "Tag udfordringen, TRAINERS!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .string "TRAINER TOWER FORUDE$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"

