SevenIsland_TrainerTower_Text_DarioIntro::
    .string "Jeg märkede din tilnärmelse.$"

SevenIsland_TrainerTower_Text_DarioDefeat::
    .string "Giv op…$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .string "I din fremtid fornemmer jeg at du\n"
    .string "vil möde mange andre.\p"
    .string "Jeg tror I vil väre forbundet med\n"
    .string "hinanden ved en underlig kraft.$"

SevenIsland_TrainerTower_Text_RodetteIntro::
    .string "Et sted pâ denne ö sover\n"
    .string "särlige POKeMON.$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .string "Hvilken fantastisk TRAINER!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .string "Et sted pâ denne ö sover\n"
    .string "särlige POKeMON.\p"
    .string "Kunne det väre at de venter\n"
    .string "pâ dig?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .string "TRAINER TOWER INDGANG\n"
    .string "Tag udfordringen, TRAINERS!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .string "TRAINER TOWER FORUDE$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"

