VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "Vil du ikke beundre min PIKACHUs\n"
    .string "yndige hale?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "Hmph!\p"
    .string "Min PIKACHU er dobbelt så nuttet som\n"
    .string "den der!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "Jeg tilbeder bare min SEEL!\n"
    .string "Den er så elskværdig!\p"
    .string "Den hyler Kyuuuh når jeg\n"
    .string "krammer den!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Aah, kære!\p"
    .string "Min SEEL er langt mere tillokkende.\n"
    .string "Dobbelt så meget, vil jeg sige.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "PIKACHU: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "SEEL: Kyuoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "Jeg er formand for POKéMON Fan Klubben!\p"
    .string "Jeg opfostrer mere end hundrede\n"
    .string "POKéMON!\p"
    .string "Jeg er meget kræsen når det gælder\n"
    .string "POKéMON! Det er jeg virkelig!\p"
    .string "Så…\p"
    .string "Kom du for at høre om\n"
    .string "mine POKéMON?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Godt!\n"
    .string "Så lyt med!\p"
    .string "Min yndlings RAPIDASH…\p"
    .string "Den er…nuttede…dejlig…klog…\n"
    .string "plus…fantastisk…synes du ikke?…\l"
    .string "åh ja…den er…blændende…\l"
    .string "venlig…elsker den!\p"
    .string "Kram den…når…den sover…varm\n"
    .string "og putte…spektakulær…\l"
    .string "betagende…\l"
    .string "…Ups! Se tiden!\l"
    .string "Jeg holdt dig for længe!\p"
    .string "Tak fordi du hørte på mig!\n"
    .string "Jeg vil gerne give dig dette!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} modtog en CYKEL-KUPON\n"
    .string "fra FORMANDEN.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Tag den CYKEL-KUPON til\n"
    .string "CYKELFORRETNINGEN i CERULEAN CITY.\p"
    .string "Byt den til en CYKEL\n"
    .string "gratis!\p"
    .string "Bare rolig, min yndlings FEAROW\n"
    .string "vil FLYVE mig hvor jeg skal hen.\p"
    .string "Så jeg har ikke brug for en CYKEL.\p"
    .string "Jeg håber du kan lide at cykle!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Aah. Kom tilbage når du vil\n"
    .string "høre min historie!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Hej, {PLAYER}!\p"
    .string "Kom du for at høre om mine\n"
    .string "POKéMON igen?\p"
    .string "Nej?\n"
    .string "Så ærgerligt!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Gør plads til dette!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "Vores FORMAND er meget vokal omkring\n"
    .string "POKéMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Lad os alle lytte høfligt til andre\n"
    .string "TRÆNERE!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "Hvis nogen praler, pral lige tilbage!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "Vores FORMAND elsker virkelig sine\n"
    .string "POKéMON.\p"
    .string "Men personen der er mest elsket af\n"
    .string "POKéMON er DAISY, tror jeg.$"
