VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "Vil du ikke beundre min PIKACHUs\n"
    .string "yndige hale?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "Hmph!\p"
    .string "Min PIKACHU er dobbelt saa nuttet som\n"
    .string "den der!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "Jeg tilbeder bare min SEEL!\n"
    .string "Den er saa elskvaerdig!\p"
    .string "Den hyler Kyuuuh naar jeg\n"
    .string "krammer den!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Aah, kaere!\p"
    .string "Min SEEL er langt mere tillokkende.\n"
    .string "Dobbelt saa meget, vil jeg sige.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "PIKACHU: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "SEEL: Kyuoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "Jeg er formand for POKeMON Fan Klubben!\p"
    .string "Jeg opfostrer mere end hundrede\n"
    .string "POKeMON!\p"
    .string "Jeg er meget kraesen naar det gaelder\n"
    .string "POKeMON! Det er jeg virkelig!\p"
    .string "Saa…\p"
    .string "Kom du for at hoere om\n"
    .string "mine POKeMON?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Godt!\n"
    .string "Saa lyt med!\p"
    .string "Min yndlings RAPIDASH…\p"
    .string "Den er…nuttede…dejlig…klog…\n"
    .string "plus…fantastisk…synes du ikke?…\l"
    .string "aah ja…den er…blaendende…\l"
    .string "venlig…elsker den!\p"
    .string "Kram den…naar…den sover…varm\n"
    .string "og putte…spektakulaer…\l"
    .string "betagende…\l"
    .string "…Ups! Se tiden!\l"
    .string "Jeg holdt dig for laenge!\p"
    .string "Tak fordi du hoerte paa mig!\n"
    .string "Jeg vil gerne give dig dette!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} modtog en CYKEL-KUPON\n"
    .string "fra FORMANDEN.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Tag den CYKEL-KUPON til\n"
    .string "CYKELFORRETNINGEN i CERULEAN CITY.\p"
    .string "Byt den til en CYKEL\n"
    .string "gratis!\p"
    .string "Bare rolig, min yndlings FEAROW\n"
    .string "vil FLYVE mig hvor jeg skal hen.\p"
    .string "Saa jeg har ikke brug for en CYKEL.\p"
    .string "Jeg haaber du kan lide at cykle!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Aah. Kom tilbage naar du vil\n"
    .string "hoere min historie!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Hej, {PLAYER}!\p"
    .string "Kom du for at hoere om mine\n"
    .string "POKeMON igen?\p"
    .string "Nej?\n"
    .string "Saa aergerligt!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Goer plads til dette!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "Vores FORMAND er meget vokal omkring\n"
    .string "POKeMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Lad os alle lytte hoefligt til andre\n"
    .string "TRAeNERE!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "Hvis nogen praler, pral lige tilbage!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "Vores FORMAND elsker virkelig sine\n"
    .string "POKeMON.\p"
    .string "Men personen der er mest elsket af\n"
    .string "POKeMON er DAISY, tror jeg.$"
