FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
    .string "SAFARI ZONEs VOGTER er gammel,\n"
    .string "men han er stadig meget aktiv.\p"
    .string "Alle hans tänder er kunstige.$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
    .string "Hmm?\n"
    .string "Du har mödt BILL?\p"
    .string "Han er mit barnebarn!\p"
    .string "Han har altid kunnet lide at samle\n"
    .string "ting, selv som barn!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
    .string "BILL gemmer sine egne POKéMON-\n"
    .string "data pâ sin PC.\p"
    .string "Viste han dig det?$"

