SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
    .string "Min datter er saa selvoptaget.\n"
    .string "Hun har kun faa venner.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
    .string "Min datter kan lide at efterligne folk.\n"
    .string "Det er ret irriterende.\p"
    .string "Hendes efterligning har givet hende\n"
    .string "tilnavnet COPYCAT her omkring.$"

SaffronCity_CopycatsHouse_1F_Text_Chansey::
    .string "CHANSEY: Chaan! Sii!$"

