PokemonTower_7F_Text_Grunt1Intro::
    .string "Hvad vil du?\n"
    .string "Hvorfor er du her?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "Jeg giver op!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "Jeg glemmer ikke dette!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "Den gamle mand marcherede lige ind i\n"
    .string "vores HIDEOUT.\p"
    .string "Sâ begynder han at rante om at\n"
    .string "TEAM ROCKET misbruger POKéMON.\p"
    .string "Sâ vi taler bare om det som\n"
    .string "voksne.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "Vær sâ venlig!\n"
    .string "Ikke mere!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "POKéMON er kun gode til at tjene\n"
    .string "penge. Hvorfor ikke bruge dem?\p"
    .string "Bliv ude af vores forretning!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "Du redder ingen, unge!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "Kæmp ikke mod os ROCKETS!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "Du slipper ikke godt fra dette!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "MR. FUJI: Hva?\n"
    .string "Du kom for at redde mig?\p"
    .string "Tak. Men jeg kom her af min\n"
    .string "egen frie vilje.\p"
    .string "Jeg kom for at berolige ânden af\n"
    .string "CUBONEs mor.\p"
    .string "Jeg tror MAROWAKs ând endelig\n"
    .string "har forladt os.\p"
    .string "Jeg mâ takke dig for din venlige\n"
    .string "omtanke.\p"
    .string "Følg mig til mit hjem, POKéMON\n"
    .string "HOUSE, ved foden af dette târn.$"
