PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "Ja, ja.\n"
    .string "Det er ¥50 for en boernebillet.\p"
    .string "Vil du ind?$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "Kom igen!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "Rigtigt, ¥50!\n"
    .string "Tak!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "Du har ikke nok penge.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "Nyd dig selv.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "Du kan ikke snige dig ind bagvejen!\n"
    .string "Godt forsoegt, unge, men nej.\p"
    .string "Aah, whatever!\n"
    .string "Ved du hvad AMBER er?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "AMBER indeholder genetisk materiale\n"
    .string "fra gamle POKeMON.\p"
    .string "Der er et LAB et sted der proever at\n"
    .string "genoplive POKeMON fra AMBER.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "AMBER er faktisk saft, den klaebede\n"
    .string "ting der siver fra traeer.\p"
    .string "Den gamle saft blev til fossil\n"
    .string "over tid og blev stenhaard AMBER.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "Jeg burde vaere taknemmelig for mit lange\n"
    .string "liv.\p"
    .string "Jeg troede aldrig jeg ville faa\n"
    .string "at se benene af en drage!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "Ssst! Hoer, jeg skal dele en\n"
    .string "hemmelighed med nogen.\p"
    .string "Jeg tror at dette stykke AMBER\n"
    .string "indeholder POKeMON DNA!\p"
    .string "Det ville vaere et rystende videnskabeligt\n"
    .string "gennembrud hvis POKeMON kunne\l"
    .string "genoplives fra det.\p"
    .string "Men mine kollegaer ignorerer bare\n"
    .string "hvad jeg har at sige.\p"
    .string "Saa jeg har en tjeneste at bede om!\p"
    .string "Jeg vil have dig til at faa dette undersoegt\n"
    .string "ved et POKeMON LAB et sted.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "{PLAYER} modtog OLD AMBER\n"
    .string "fra manden.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "Ssst!\n"
    .string "Fa OLD AMBER tjekket!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "Du har ikke plads til dette.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "Vi har to fossiler af sjaeldne,\n"
    .string "forhistoriske POKeMON udstillet.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "Der er et smukt stykke\n"
    .string "AMBER i klar guld farve.$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "AERODACTYL Fossil\n"
    .string "En primitiv og sjaelden POKeMON.$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "KABUTOPS Fossil\n"
    .string "En primitiv og sjaelden POKeMON.$"
