SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .string "Dans, dans!\n"
    .string "CHANSEY Dans!\p"
    .string "Du danser med!\n"
    .string "Dans, dans!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .string "Vil du gerne danse?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .string "Kom nu, dans!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
    .string "{PLAYER} dansede CHANSEY-dansen!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .string "Ahahahaha!\p"
    .string "Sâdan, nu er du helt oppe at køre!\n"
    .string "Heldige!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
    .string "CHANSEY: Chansi! Chansi!$"
