VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "Jeg fâr min PIDGEY til at flyve et\n"
    .string "brev til SAFFRON i nord.$"

VermilionCity_House3_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Käre PIPPI,\n"
    .string "Jeg hâber at se dig snart.\p"
    .string "Jeg hörte at SAFFRON har problemer med\n"
    .string "TEAM ROCKET.\p"
    .string "VERMILION ser ud til at väre trygt.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "Jeg vil gerne udveksle MAIL med alle\n"
    .string "mulige mennesker.\p"
    .string "Jeg sender min PIDGEY til et UNION ROOM\n"
    .string "for at udveksle MAIL for mig.$"

