Route18_Text_WiltonIntro::
    .string "Jeg tjekker altid hvert graesomraade\n"
    .string "for nye POKeMON.$"

Route18_Text_WiltonDefeat::
    .string "Tch!$"

Route18_Text_WiltonPostBattle::
    .string "Jeg ville oenske jeg havde en CYKEL!$"

Route18_Text_RamiroIntro::
    .string "Kurukkoo!\n"
    .string "Hvordan kan du lide mit fuglekald?$"

Route18_Text_RamiroDefeat::
    .string "Jeg maatte irritere dig!$"

Route18_Text_RamiroPostBattle::
    .string "Jeg samler hav-POKeMON i weekenden\n"
    .string "fordi havet er saa taet paa.$"

Route18_Text_JacobIntro::
    .string "Dette er mit territorium!\n"
    .string "Forsvind herfra!$"

Route18_Text_JacobDefeat::
    .string "Pokker!$"

Route18_Text_JacobPostBattle::
    .string "Dette er mit yndlingssted til at\n"
    .string "fange POKeMON.$"

Route18_Text_RouteSign::
    .string "ROUTE 18\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route18_Text_CyclingRoadSign::
    .string "CYKELVEJ\n"
    .string "Fodgaengere forbudt!$"
