Route18_Text_WiltonIntro::
    .string "Jeg tjekker altid hvert græsomrâde\n"
    .string "for nye POKéMON.$"

Route18_Text_WiltonDefeat::
    .string "Tch!$"

Route18_Text_WiltonPostBattle::
    .string "Jeg ville ønske jeg havde en CYKEL!$"

Route18_Text_RamiroIntro::
    .string "Kurukkoo!\n"
    .string "Hvordan kan du lide mit fuglekald?$"

Route18_Text_RamiroDefeat::
    .string "Jeg mâtte irritere dig!$"

Route18_Text_RamiroPostBattle::
    .string "Jeg samler hav-POKéMON i weekenden\n"
    .string "fordi havet er sâ tæt pâ.$"

Route18_Text_JacobIntro::
    .string "Dette er mit territorium!\n"
    .string "Forsvind herfra!$"

Route18_Text_JacobDefeat::
    .string "Pokker!$"

Route18_Text_JacobPostBattle::
    .string "Dette er mit yndlingssted til at\n"
    .string "fange POKéMON.$"

Route18_Text_RouteSign::
    .string "ROUTE 18\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route18_Text_CyclingRoadSign::
    .string "CYKELVEJ\n"
    .string "Fodgængere forbudt!$"
