Text_SeismicTossTeach::
    .string "Rummet hemmeligheder…\n"
    .string "Jordens mysterier…\p"
    .string "Der er sâ mange ting vi ved\n"
    .string "sâ lidt om.\p"
    .string "Men det burde tilskynde os til at\n"
    .string "studere hardere, ikke give op.\p"
    .string "Det eneste du burde kaste…\p"
    .string "Nâ, hvad med SEISMIC TOSS?\n"
    .string "Skal jeg läre det til en POKeMON?$"

Text_SeismicTossDeclined::
    .string "Er det sâ?\n"
    .string "Jeg er sikker pâ du kommer tilbage.$"

Text_SeismicTossWhichMon::
    .string "Hvilken POKeMON vil läre\n"
    .string "SEISMIC TOSS?$"

Text_SeismicTossTaught::
    .string "Jeg hâber du ikke giver op.\n"
    .string "Fortsät.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "MOON STONE, hva?\p"
    .string "Hvad er sâ specielt ved den?\n"
    .string "Ser ud som en almindelig sten.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "20. juli 1969!\p"
    .string "Menneskeheden satte först foden pâ\n"
    .string "mânen den dag.\p"
    .string "Jeg köbte et farvefjernsyn bare for at\n"
    .string "se den nyhed.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "Denne mâned har vi en rumudstilling.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "Jeg vil have en PIKACHU!\n"
    .string "Den er sâ nuttet!\p"
    .string "Jeg bad min far om at fange een!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Ja, en PIKACHU snart, jeg lover!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "Rumfärge$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "En meteorit der faldt pâ MT. MOON.\n"
    .string "Den antages at väre en MOON STONE.$"
