Text_SeismicTossTeach::
    .string "Rummet hemmeligheder…\n"
    .string "Jordens mysterier…\p"
    .string "Der er saa mange ting vi ved\n"
    .string "saa lidt om.\p"
    .string "Men det burde tilskynde os til at\n"
    .string "studere hardere, ikke give op.\p"
    .string "Det eneste du burde kaste…\p"
    .string "Naa, hvad med SEISMIC TOSS?\n"
    .string "Skal jeg laere det til en POKeMON?$"

Text_SeismicTossDeclined::
    .string "Er det saa?\n"
    .string "Jeg er sikker paa du kommer tilbage.$"

Text_SeismicTossWhichMon::
    .string "Hvilken POKeMON vil laere\n"
    .string "SEISMIC TOSS?$"

Text_SeismicTossTaught::
    .string "Jeg haaber du ikke giver op.\n"
    .string "Fortsaet.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "MOON STONE, hva?\p"
    .string "Hvad er saa specielt ved den?\n"
    .string "Ser ud som en almindelig sten.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "20. juli 1969!\p"
    .string "Menneskeheden satte foerst foden paa\n"
    .string "maanen den dag.\p"
    .string "Jeg koebte et farvefjernsyn bare for at\n"
    .string "se den nyhed.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "Denne maaned har vi en rumudstilling.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "Jeg vil have en PIKACHU!\n"
    .string "Den er saa nuttet!\p"
    .string "Jeg bad min far om at fange een!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Ja, en PIKACHU snart, jeg lover!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "Rumfaerge$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "En meteorit der faldt paa MT. MOON.\n"
    .string "Den antages at vaere en MOON STONE.$"
