SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "Ah! Endelig!\p"
    .string "Du er den foerste der naaede\n"
    .string "DET HEMMELIGE HUS!\p"
    .string "Selv om jeg lavede en kampagne\n"
    .string "til vor store aabning,\p"
    .string "begyndte jeg at bekymre mig for at\n"
    .string "ingen ville vinde vores kampagnepraemie.\p"
    .string "Tillykke!\n"
    .string "Du har vundet!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
    .string "{PLAYER} modtog HM03\n"
    .string "fra betjenten!$"

SafariZone_SecretHouse_Text_ExplainSurf::
    .string "HM03 er SURF.\p"
    .string "POKeMON kan faerge dig over vand\n"
    .string "med den.\p"
    .string "Og denne HM er ikke engangsbrug,\n"
    .string "saa du kan bruge den igen og igen.\p"
    .string "Du er super heldig at vinde denne\n"
    .string "fantastiske praemie!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "Du har ikke plads til denne\n"
    .string "fantastiske praemie!$"
