Route19_Text_RichardIntro::
    .string "Jeg skal motionere og varme op\n"
    .string "foer jeg svoemmer ud.$"

Route19_Text_RichardDefeat::
    .string "Varmet ordentligt op!$"

Route19_Text_RichardPostBattle::
    .string "Tak, unge!\n"
    .string "Jeg er klar til at svoemme.$"

Route19_Text_ReeceIntro::
    .string "Vent! Langsomt!\n"
    .string "Du faar et hjerteanfald!$"

Route19_Text_ReeceDefeat::
    .string "Ooh!\n"
    .string "Det er koldt!$"

Route19_Text_ReecePostBattle::
    .string "Pas paa TENTACOOL.\n"
    .string "De stikker saa smertefuldt.$"

Route19_Text_MatthewIntro::
    .string "Jeg elsker at svoemme!\n"
    .string "Hvad med dig?$"

Route19_Text_MatthewDefeat::
    .string "Maveplasker!$"

Route19_Text_MatthewPostBattle::
    .string "Jeg kan slaa selv hav-POKeMON\n"
    .string "i svoemning.$"

Route19_Text_DouglasIntro::
    .string "Hvad er der bag horisonten?$"

Route19_Text_DouglasDefeat::
    .string "Glub!$"

Route19_Text_DouglasPostBattle::
    .string "Jeg kan se et par oer derude!$"

Route19_Text_DavidIntro::
    .string "Jeg proevede at dykke efter\n"
    .string "POKeMON, men det lykkedes ikke.$"

Route19_Text_DavidDefeat::
    .string "Hjaelp!$"

Route19_Text_DavidPostBattle::
    .string "Jeg gaetter paa man skal fiske efter\n"
    .string "hav-POKeMON.$"

Route19_Text_TonyIntro::
    .string "Jeg kigger paa havet for at glemme\n"
    .string "alt det daarlige der skete.$"

Route19_Text_TonyDefeat::
    .string "Ooh!\n"
    .string "Traumatisk!$"

Route19_Text_TonyPostBattle::
    .string "Jeg kigger paa havet for at glemme\n"
    .string "det daarlige der skete!$"

Route19_Text_AnyaIntro::
    .string "Aa, jeg elsker bare dit koeretoej!\n"
    .string "Ma jeg faa den hvis jeg vinder?$"

Route19_Text_AnyaDefeat::
    .string "Aa! Jeg tabte!$"

Route19_Text_AnyaPostBattle::
    .string "Det er stadig langt til\n"
    .string "SEAFOAM ISLANDS...\p"
    .string "Jeg vil tilbage til FUCHSIA...$"

Route19_Text_AliceIntro::
    .string "Svoemning er fantastisk!\n"
    .string "Solbraend er ikke!$"

Route19_Text_AliceDefeat::
    .string "Chokerende!$"

Route19_Text_AlicePostBattle::
    .string "Min kaereste ville svoemme til\n"
    .string "SEAFOAM ISLANDS.$"

Route19_Text_AxleIntro::
    .string "Ahoy der!\n"
    .string "Disse farvande er farlige!$"

Route19_Text_AxleDefeat::
    .string "Ooh!\n"
    .string "Farligt!$"

Route19_Text_AxlePostBattle::
    .string "M-mine ben! De krampede!\n"
    .string "Glub, glub...$"

Route19_Text_ConnieIntro::
    .string "Jeg svoemmede hertil med mine\n"
    .string "venner... Jeg er traet...$"

Route19_Text_ConnieDefeat::
    .string "Jeg er udmattet...$"

Route19_Text_ConniePostBattle::
    .string "Hvis jeg skulle ride paa en POKeMON\n"
    .string "paa havet, ville jeg vaelge LAPRAS.\p"
    .string "LAPRAS er saa stor, den holder\n"
    .string "mig sikkert toer paa vandet.$"

Route19_Text_RouteSign::
    .string "HAVROUTE 19\n"
    .string "FUCHSIA CITY - SEAFOAM ISLANDS$"

Route19_Text_LiaIntro::
    .string "LIA: Jeg passer min bror.\n"
    .string "Han er lige blevet TRAINER.$"

Route19_Text_LiaDefeat::
    .string "LIA: Saadan behandler man ikke min\n"
    .string "lillebror!$"

Route19_Text_LiaPostBattle::
    .string "LIA: Har du en yngre bror?\p"
    .string "Jeg haaber du laerer ham alt\n"
    .string "muligt.$"

Route19_Text_LiaNotEnoughMons::
    .string "LIA: Jeg vil kaempe sammen\n"
    .string "med min lillebror.\p"
    .string "Har du ikke to POKeMON?$"

Route19_Text_LucIntro::
    .string "LUC: Min storesoester laerte mig at\n"
    .string "svoemme og traene POKeMON.$"

Route19_Text_LucDefeat::
    .string "LUC: Aa, wow!\n"
    .string "En der er staerkere end min storesoester!$"

Route19_Text_LucPostBattle::
    .string "LUC: Min storesoester er staerk og\n"
    .string "rar. Hun er fantastisk!$"

Route19_Text_LucNotEnoughMons::
    .string "LUC: Jeg vil ikke hvis jeg ikke kan\n"
    .string "kaempe dig med min storesoester.\p"
    .string "Har du ikke to POKeMON?$"
