Route19_Text_RichardIntro::
    .string "Jeg skal motionere og varme op\n"
    .string "för jeg svömmer ud.$"

Route19_Text_RichardDefeat::
    .string "Varmet ordentligt op!$"

Route19_Text_RichardPostBattle::
    .string "Tak, unge!\n"
    .string "Jeg er klar til at svömme.$"

Route19_Text_ReeceIntro::
    .string "Vent! Langsomt!\n"
    .string "Du fâr et hjerteanfald!$"

Route19_Text_ReeceDefeat::
    .string "Ooh!\n"
    .string "Det er koldt!$"

Route19_Text_ReecePostBattle::
    .string "Pas pâ TENTACOOL.\n"
    .string "De stikker sâ smertefuldt.$"

Route19_Text_MatthewIntro::
    .string "Jeg elsker at svömme!\n"
    .string "Hvad med dig?$"

Route19_Text_MatthewDefeat::
    .string "Maveplasker!$"

Route19_Text_MatthewPostBattle::
    .string "Jeg kan slâ selv hav-POKeMON\n"
    .string "i svömning.$"

Route19_Text_DouglasIntro::
    .string "Hvad er der bag horisonten?$"

Route19_Text_DouglasDefeat::
    .string "Glub!$"

Route19_Text_DouglasPostBattle::
    .string "Jeg kan se et par ör derude!$"

Route19_Text_DavidIntro::
    .string "Jeg prövede at dykke efter\n"
    .string "POKeMON, men det lykkedes ikke.$"

Route19_Text_DavidDefeat::
    .string "Hjälp!$"

Route19_Text_DavidPostBattle::
    .string "Jeg gätter pâ man skal fiske efter\n"
    .string "hav-POKeMON.$"

Route19_Text_TonyIntro::
    .string "Jeg kigger pâ havet for at glemme\n"
    .string "alt det dârlige der skete.$"

Route19_Text_TonyDefeat::
    .string "Ooh!\n"
    .string "Traumatisk!$"

Route19_Text_TonyPostBattle::
    .string "Jeg kigger pâ havet for at glemme\n"
    .string "det dârlige der skete!$"

Route19_Text_AnyaIntro::
    .string "Aa, jeg elsker bare dit köretöj!\n"
    .string "Ma jeg fâ den hvis jeg vinder?$"

Route19_Text_AnyaDefeat::
    .string "Aa! Jeg tabte!$"

Route19_Text_AnyaPostBattle::
    .string "Det er stadig langt til\n"
    .string "SEAFOAM ISLANDS...\p"
    .string "Jeg vil tilbage til FUCHSIA...$"

Route19_Text_AliceIntro::
    .string "Svömning er fantastisk!\n"
    .string "Solbränd er ikke!$"

Route19_Text_AliceDefeat::
    .string "Chokerende!$"

Route19_Text_AlicePostBattle::
    .string "Min käreste ville svömme til\n"
    .string "SEAFOAM ISLANDS.$"

Route19_Text_AxleIntro::
    .string "Ahoy der!\n"
    .string "Disse farvande er farlige!$"

Route19_Text_AxleDefeat::
    .string "Ooh!\n"
    .string "Farligt!$"

Route19_Text_AxlePostBattle::
    .string "M-mine ben! De krampede!\n"
    .string "Glub, glub...$"

Route19_Text_ConnieIntro::
    .string "Jeg svömmede hertil med mine\n"
    .string "venner... Jeg er trät...$"

Route19_Text_ConnieDefeat::
    .string "Jeg er udmattet...$"

Route19_Text_ConniePostBattle::
    .string "Hvis jeg skulle ride pâ en POKeMON\n"
    .string "pâ havet, ville jeg välge LAPRAS.\p"
    .string "LAPRAS er sâ stor, den holder\n"
    .string "mig sikkert tör pâ vandet.$"

Route19_Text_RouteSign::
    .string "HAVROUTE 19\n"
    .string "FUCHSIA CITY - SEAFOAM ISLANDS$"

Route19_Text_LiaIntro::
    .string "LIA: Jeg passer min bror.\n"
    .string "Han er lige blevet TRAINER.$"

Route19_Text_LiaDefeat::
    .string "LIA: Sâdan behandler man ikke min\n"
    .string "lillebror!$"

Route19_Text_LiaPostBattle::
    .string "LIA: Har du en yngre bror?\p"
    .string "Jeg hâber du lärer ham alt\n"
    .string "muligt.$"

Route19_Text_LiaNotEnoughMons::
    .string "LIA: Jeg vil kämpe sammen\n"
    .string "med min lillebror.\p"
    .string "Har du ikke to POKeMON?$"

Route19_Text_LucIntro::
    .string "LUC: Min storesöster lärte mig at\n"
    .string "svömme og träne POKeMON.$"

Route19_Text_LucDefeat::
    .string "LUC: Aa, wow!\n"
    .string "En der er stärkere end min storesöster!$"

Route19_Text_LucPostBattle::
    .string "LUC: Min storesöster er stärk og\n"
    .string "rar. Hun er fantastisk!$"

Route19_Text_LucNotEnoughMons::
    .string "LUC: Jeg vil ikke hvis jeg ikke kan\n"
    .string "kämpe dig med min storesöster.\p"
    .string "Har du ikke to POKeMON?$"
