VictoryRoad_1F_Text_NaomiIntro::
    .string "Jeg spekulerer pâ om du er god nok\n"
    .string "for mig?$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "Jeg tabte…$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "Jeg ville aldrig tabe til nogen,\n"
    .string "isär ikke til et yngre barn…$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "Jeg kan se du er god.\n"
    .string "Lad mig se präcis hvor god!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "Jeg havde en chance…$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "Tch!\n"
    .string "Jeg indrömmer, du er bedre end mig!$"

