VictoryRoad_1F_Text_NaomiIntro::
    .string "Jeg spekulerer paa om du er god nok\n"
    .string "for mig?$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "Jeg tabte…$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "Jeg ville aldrig tabe til nogen,\n"
    .string "isaer ikke til et yngre barn…$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "Jeg kan se du er god.\n"
    .string "Lad mig se praecis hvor god!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "Jeg havde en chance…$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "Tch!\n"
    .string "Jeg indroemmer, du er bedre end mig!$"

