SevenIsland_TanobyRuins_Text_BrandonIntro::
    .string "Ved du noget om denne\n"
    .string "stenskammer?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
    .string "Det var unoedvendigt.\n"
    .string "Du behoevede ikke vaere saa haard.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
    .string "TANOBY RUINS er mindst\n"
    .string "1.500 aar gamle.\p"
    .string "Men det er et gaadefuldt mysterium\n"
    .string "hvorfor det overhovedet blev bygget.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
    .string "En mystisk POKeMON siges at sove\n"
    .string "inde her.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
    .string "Jeg er ikke saerlig god til kamp.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
    .string "Jeg hoerer at der er andre ruiner\n"
    .string "som den her.\p"
    .string "Kunne de vaere hvilesteder for\n"
    .string "andre mystiske POKeMON?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
    .string "CLIFFORD laerer mig at male.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
    .string "Vi kan faa problemer for at vaere\n"
    .string "lystige her.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
    .string "Jeg sagde at jeg ville male en\n"
    .string "gammel bygning.\p"
    .string "Saa CLIFFORD bragte mig her.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
    .string "I dag kom vi for at se kammeret\n"
    .string "ud over vores lektion.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
    .string "Min, hvor usaedvanligt.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
    .string "Aah, saa du studerer POKeMON\n"
    .string "paa egen haand…\p"
    .string "Ja, du er virkelig en ganske\n"
    .string "usaedvanlig person.$"

