SevenIsland_TanobyRuins_Text_BrandonIntro::
    .string "Ved du noget om denne\n"
    .string "stenskammer?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
    .string "Det var unødvendigt.\n"
    .string "Du behøvede ikke være sâ hârd.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
    .string "TANOBY RUINS er mindst\n"
    .string "1.500 âr gamle.\p"
    .string "Men det er et gâdefuldt mysterium\n"
    .string "hvorfor det overhovedet blev bygget.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
    .string "En mystisk POKéMON siges at sove\n"
    .string "inde her.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
    .string "Jeg er ikke særlig god til kamp.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
    .string "Jeg hører at der er andre ruiner\n"
    .string "som den her.\p"
    .string "Kunne de være hvilesteder for\n"
    .string "andre mystiske POKéMON?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
    .string "CLIFFORD lærer mig at male.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
    .string "Vi kan fâ problemer for at være\n"
    .string "lystige her.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
    .string "Jeg sagde at jeg ville male en\n"
    .string "gammel bygning.\p"
    .string "Sâ CLIFFORD bragte mig her.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
    .string "I dag kom vi for at se kammeret\n"
    .string "ud over vores lektion.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
    .string "Min, hvor usædvanligt.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
    .string "Aah, sâ du studerer POKéMON\n"
    .string "pâ egen hând…\p"
    .string "Ja, du er virkelig en ganske\n"
    .string "usædvanlig person.$"

