CeruleanCity_House1_Text_AnyInterestInBerries::
    .string "Jeg blander en variation af medicin\n"
    .string "af BERRY POWDER.\p"
    .string "Med god BERRY POWDER kan jeg\n"
    .string "lave enhver slags medicin.\p"
    .string "Sig mig nu, har du interesse\n"
    .string "i BERRIES?$"

CeruleanCity_House1_Text_HaveJustTheThing::
    .string "Ah, godt! For dig har jeg sâ\n"
    .string "lige det rigtige.$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
    .string "Der er noget nyt pâ anden sal\n"
    .string "i POKeMON CENTERS, ved\l"
    .string "DIRECT CORNER.\p"
    .string "De installerede en Wireless Adapter-\n"
    .string "maskine til at knuse BERRIES.\p"
    .string "Det er her du kommer ind.\p"
    .string "Jeg har en tjeneste at bede om, een\n"
    .string "jeg kun kan betro dig.\p"
    .string "Kunne du lave BERRY POWDER til\n"
    .string "mig med den maskine?\p"
    .string "Glem ikke, maskinen er ved\n"
    .string "DIRECT CORNER i POKeMON CENTERS.\p"
    .string "Jeg laver medicin til dig hvis\n"
    .string "du bringer mig noget BERRY POWDER.\p"
    .string "Glem ikke, knus BERRIES til\n"
    .string "BERRY POWDER og bring det til mig.$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
    .string "Hvorfor mâ du lyve for mig?\p"
    .string "Hvor mange BERRIES har du?\n"
    .string "Ikke een!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
    .string "Du har ingen interesse i BERRIES?\p"
    .string "Ungdom, det er vigtigt at vise\n"
    .string "interesse for alle slags ting.$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
    .string "Er-hem! Har du bragt mig noget\n"
    .string "BERRY POWDER?$"

CeruleanCity_House5_Text_ExchangeWithWhat::
    .string "Med hvad vil du\n"
    .string "bytte det?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
    .string "Fint, du bytter din BERRY\n"
    .string "POWDER for een {STR_VAR_1}?$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
    .string "Hm? Du har ikke nok\n"
    .string "BERRY POWDER.$"

CeruleanCity_House1_Text_TradeMoreBerryPowder::
    .string "Dette er virkelig fint BERRY POWDER.\n"
    .string "Det bliver fremragende medicin.\p"
    .string "Vil du bytte mere BERRY\n"
    .string "POWDER for noget andet?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain::
    .string "Det er fint, sâ.\n"
    .string "Jeg hâber at se dig igen.$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
    .string "Kom til mig hvis du vil bytte\n"
    .string "din BERRY POWDER.$"
