Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Mange POKeMON lever kun i skove\n"
    .string "og huler.\p"
    .string "Du skal väre vedholdende og kigge\n"
    .string "overalt for at fâ forskellige slags.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Har du lagt märke til de tynde träer\n"
    .string "ved vejsiden?\p"
    .string "De kan fäldes med et specielt\n"
    .string "POKeMON-träk, har jeg hört.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Kender du evolution-annullerings-\n"
    .string "teknikken?\p"
    .string "Nâr en POKeMON udvikler sig, kan\n"
    .string "du stoppe processen.\p"
    .string "Det er en teknik til at opdrage\n"
    .string "POKeMON som de er.$"
