Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Mange POKeMON lever kun i skove\n"
    .string "og huler.\p"
    .string "Du skal vaere vedholdende og kigge\n"
    .string "overalt for at faa forskellige slags.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Har du lagt maerke til de tynde traeer\n"
    .string "ved vejsiden?\p"
    .string "De kan faeldes med et specielt\n"
    .string "POKeMON-traek, har jeg hoert.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Kender du evolution-annullerings-\n"
    .string "teknikken?\p"
    .string "Naar en POKeMON udvikler sig, kan\n"
    .string "du stoppe processen.\p"
    .string "Det er en teknik til at opdrage\n"
    .string "POKeMON som de er.$"
