Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Mange POKéMON lever kun i skove\n"
    .string "og huler.\p"
    .string "Du skal være vedholdende og kigge\n"
    .string "overalt for at fâ forskellige slags.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Har du lagt mærke til de tynde træer\n"
    .string "ved vejsiden?\p"
    .string "De kan fældes med et specielt\n"
    .string "POKéMON-træk, har jeg hørt.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Kender du evolution-annullerings-\n"
    .string "teknikken?\p"
    .string "Nâr en POKéMON udvikler sig, kan\n"
    .string "du stoppe processen.\p"
    .string "Det er en teknik til at opdrage\n"
    .string "POKéMON som de er.$"
