Route20_Text_BarryIntro::
    .string "Vandet er lavt her.\n"
    .string "Der er mange der svoemmer.$"

Route20_Text_BarryDefeat::
    .string "Plask!$"

Route20_Text_BarryPostBattle::
    .string "Jeg ville oenske jeg kunne ride\n"
    .string "mine POKeMON. Du er sikkert ikke traet.$"

Route20_Text_ShirleyIntro::
    .string "SEAFOAM er et roligt tilflugtssted.\n"
    .string "Jeg holder ferie her.$"

Route20_Text_ShirleyDefeat::
    .string "Stop det!$"

Route20_Text_ShirleyPostBattle::
    .string "Der er en kaempe grotte under\n"
    .string "denne oe.$"

Route20_Text_TiffanyIntro::
    .string "Jeg elsker at flyde med fiskene\n"
    .string "her mellem boelgerne.$"

Route20_Text_TiffanyDefeat::
    .string "Av!$"

Route20_Text_TiffanyPostBattle::
    .string "Vil du flyde med mig?$"

Route20_Text_IreneIntro::
    .string "Er du ogsaa paa ferie?$"

Route20_Text_IreneDefeat::
    .string "Ingen naade overhovedet!$"

Route20_Text_IrenePostBattle::
    .string "SEAFOAM var engang en enkelt oe\n"
    .string "i fjerne fortid.$"

Route20_Text_DeanIntro::
    .string "Se min muskuloese krop!$"

Route20_Text_DeanDefeat::
    .string "Svag!$"

Route20_Text_DeanPostBattle::
    .string "Jeg burde have styrket mine\n"
    .string "POKeMON i stedet for mig!$"

Route20_Text_DarrinIntro::
    .string "Hvorfor rider du paa en POKeMON?\n"
    .string "Kan du ikke svoemme?$"

Route20_Text_DarrinDefeat::
    .string "Av!\n"
    .string "Torpedoeret!$"

Route20_Text_DarrinPostBattle::
    .string "At ride paa en POKeMON ser sjovt ud!$"

Route20_Text_RogerIntro::
    .string "Jeg floej hertil paa mine fugle-POKeMON.$"

Route20_Text_RogerDefeat::
    .string "Aa, nej!\n"
    .string "Hvad skal jeg goere nu?$"

Route20_Text_RogerPostBattle::
    .string "Mine fugle er udmattede.\n"
    .string "De kan ikke FLY mig tilbage!$"

Route20_Text_NoraIntro::
    .string "Min kaereste gav mig store perler.$"

Route20_Text_NoraDefeat::
    .string "Aa, nej!\n"
    .string "Mine perler var i dem!$"

Route20_Text_NoraPostBattle::
    .string "Bliver mine perler stoerre inde i\n"
    .string "CLOYSTER?$"

Route20_Text_MissyIntro::
    .string "Jeg svoemmede herfra CINNABAR ISLAND.\n"
    .string "Det var ikke nemt!$"

Route20_Text_MissyDefeat::
    .string "Jeg er saa skuffet!$"

Route20_Text_MissyPostBattle::
    .string "POKeMON har overtaget et forladt\n"
    .string "palae paa CINNABAR.\p"
    .string "De kalder det POKeMON MANSION nu.$"

Route20_Text_MelissaIntro::
    .string "CINNABAR mod vest har et LAB\n"
    .string "til POKeMON.\p"
    .string "Min far arbejder der.$"

Route20_Text_MelissaDefeat::
    .string "Vent!\n"
    .string "Du skulle vente!$"

Route20_Text_MelissaPostBattle::
    .string "CINNABAR er en vulkanoe.\p"
    .string "Jeg horte den rejste sig fra havet\n"
    .string "da en vulkan udbroed.$"

Route20_Text_SeafoamIslands::
    .string "SEAFOAM ISLANDS$"

Route20_Text_MistyTrainsHere::
    .string "Staerke TRAINERS og vand-POKeMON\n"
    .string "er almindelige her.\p"
    .string "De siger at MISTY fra\n"
    .string "CERULEAN GYM traener her.$"
