Route20_Text_BarryIntro::
    .string "Vandet er lavt her.\n"
    .string "Der er mange der svømmer.$"

Route20_Text_BarryDefeat::
    .string "Plask!$"

Route20_Text_BarryPostBattle::
    .string "Jeg ville ønske jeg kunne ride\n"
    .string "mine POKéMON. Du er sikkert ikke træt.$"

Route20_Text_ShirleyIntro::
    .string "SEAFOAM er et roligt tilflugtssted.\n"
    .string "Jeg holder ferie her.$"

Route20_Text_ShirleyDefeat::
    .string "Stop det!$"

Route20_Text_ShirleyPostBattle::
    .string "Der er en kæmpe grotte under\n"
    .string "denne ø.$"

Route20_Text_TiffanyIntro::
    .string "Jeg elsker at flyde med fiskene\n"
    .string "her mellem bølgerne.$"

Route20_Text_TiffanyDefeat::
    .string "Av!$"

Route20_Text_TiffanyPostBattle::
    .string "Vil du flyde med mig?$"

Route20_Text_IreneIntro::
    .string "Er du ogsâ pâ ferie?$"

Route20_Text_IreneDefeat::
    .string "Ingen nâde overhovedet!$"

Route20_Text_IrenePostBattle::
    .string "SEAFOAM var engang en enkelt ø\n"
    .string "i fjerne fortid.$"

Route20_Text_DeanIntro::
    .string "Se min muskuløse krop!$"

Route20_Text_DeanDefeat::
    .string "Svag!$"

Route20_Text_DeanPostBattle::
    .string "Jeg burde have styrket mine\n"
    .string "POKéMON i stedet for mig!$"

Route20_Text_DarrinIntro::
    .string "Hvorfor rider du pâ en POKéMON?\n"
    .string "Kan du ikke svømme?$"

Route20_Text_DarrinDefeat::
    .string "Av!\n"
    .string "Torpedøret!$"

Route20_Text_DarrinPostBattle::
    .string "At ride pâ en POKéMON ser sjovt ud!$"

Route20_Text_RogerIntro::
    .string "Jeg fløj hertil pâ mine fugle-POKéMON.$"

Route20_Text_RogerDefeat::
    .string "Aa, nej!\n"
    .string "Hvad skal jeg gøre nu?$"

Route20_Text_RogerPostBattle::
    .string "Mine fugle er udmattede.\n"
    .string "De kan ikke FLY mig tilbage!$"

Route20_Text_NoraIntro::
    .string "Min kæreste gav mig store perler.$"

Route20_Text_NoraDefeat::
    .string "Aa, nej!\n"
    .string "Mine perler var i dem!$"

Route20_Text_NoraPostBattle::
    .string "Bliver mine perler større inde i\n"
    .string "CLOYSTER?$"

Route20_Text_MissyIntro::
    .string "Jeg svømmede herfra CINNABAR ISLAND.\n"
    .string "Det var ikke nemt!$"

Route20_Text_MissyDefeat::
    .string "Jeg er sâ skuffet!$"

Route20_Text_MissyPostBattle::
    .string "POKéMON har overtaget et forladt\n"
    .string "palæ pâ CINNABAR.\p"
    .string "De kalder det POKéMON MANSION nu.$"

Route20_Text_MelissaIntro::
    .string "CINNABAR mod vest har et LAB\n"
    .string "til POKéMON.\p"
    .string "Min far arbejder der.$"

Route20_Text_MelissaDefeat::
    .string "Vent!\n"
    .string "Du skulle vente!$"

Route20_Text_MelissaPostBattle::
    .string "CINNABAR er en vulkanø.\p"
    .string "Jeg horte den rejste sig fra havet\n"
    .string "da en vulkan udbrød.$"

Route20_Text_SeafoamIslands::
    .string "SEAFOAM ISLANDS$"

Route20_Text_MistyTrainsHere::
    .string "Stærke TRAINERS og vand-POKéMON\n"
    .string "er almindelige her.\p"
    .string "De siger at MISTY fra\n"
    .string "CERULEAN GYM træner her.$"
