SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .string "Du, mon petit!\n"
    .string "Vi har travlt her!\l"
    .string "Af vejen!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
    .string "Jeg sâ et underligt BÆR i skraldet.\n"
    .string "Jeg spekulerer pâ hvad det var?$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .string "Jeg har sâ travlt at jeg bliver svimmel!\n"
    .string "Du mâ give mig plads her!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .string "Hum-de-hum-de-ho…\p"
    .string "Jeg skræller kartofler hver dag!\n"
    .string "Hum-hum…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
    .string "Hørte du om SNORLAX?\n"
    .string "Det er en frâdser.\p"
    .string "Ingen anden POKéMON spiser og sover\n"
    .string "som SNORLAX kan og gør!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .string "Snøft… Snus…\p"
    .string "Jeg mâ kun skrælle løg…\n"
    .string "Snøft…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .string "Er-hem!\n"
    .string "Jeg er virkelig CHEF!\p"
    .string "Hovedretten er$"

SSAnne_Kitchen_Text_SalmonDuSalad::
    .string "Salmon du Salad!\p"
    .string "Gæsterne brokker sig mâske over at det\n"
    .string "igen er fisk!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .string "Eels au Barbecue!\p"
    .string "Gæsterne vil mytteri, frygter jeg.$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .string "Prime Beefsteak!\p"
    .string "Men har jeg nok fileter du\n"
    .string "beef?$"

