SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .string "Du, mon petit!\n"
    .string "Vi har travlt her!\l"
    .string "Af vejen!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
    .string "Jeg saa et underligt BAeR i skraldet.\n"
    .string "Jeg spekulerer paa hvad det var?$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .string "Jeg har saa travlt at jeg bliver svimmel!\n"
    .string "Du maa give mig plads her!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .string "Hum-de-hum-de-ho…\p"
    .string "Jeg skraeller kartofler hver dag!\n"
    .string "Hum-hum…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
    .string "Hoerte du om SNORLAX?\n"
    .string "Det er en fraadser.\p"
    .string "Ingen anden POKeMON spiser og sover\n"
    .string "som SNORLAX kan og goer!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .string "Snoeft… Snus…\p"
    .string "Jeg maa kun skraelle loeg…\n"
    .string "Snoeft…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .string "Er-hem!\n"
    .string "Jeg er virkelig CHEF!\p"
    .string "Hovedretten er$"

SSAnne_Kitchen_Text_SalmonDuSalad::
    .string "Salmon du Salad!\p"
    .string "Gaesterne brokker sig maaske over at det\n"
    .string "igen er fisk!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .string "Eels au Barbecue!\p"
    .string "Gaesterne vil mytteri, frygter jeg.$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .string "Prime Beefsteak!\p"
    .string "Men har jeg nok fileter du\n"
    .string "beef?$"

