SilphCo_2F_Text_ConnorIntro::
    .string "Hjälp!\n"
    .string "Jeg er SILPH-ansat.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "Hvordan vidste du\n"
    .string "at jeg var ROCKET?$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "Jeg arbejder for bâde SILPH og TEAM\n"
    .string "ROCKET.$"

SilphCo_2F_Text_JerryIntro::
    .string "Det er forbudt omrâde her!\n"
    .string "Ga hjem!$"

SilphCo_2F_Text_JerryDefeat::
    .string "Du er god.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "Kan du löse labyrinten her?\n"
    .string "Det er ikke nemt, siger jeg dig!$"

SilphCo_2F_Text_Grunt1Intro::
    .string "Börn har ikke adgang her!$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "Hârdt!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "Diamantformede fliser er teleport-\n"
    .string "blokke.\p"
    .string "De er transportörer i denne\n"
    .string "höjteknologiske bygning.$"

SilphCo_2F_Text_Grunt2Intro::
    .string "Hey, unge!\n"
    .string "Hvad vandrer du her for?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "Jeg lavede en fejl!$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "SILPH CO. vil blive forbundet med\n"
    .string "TEAM ROCKET!$"

Text_ThunderWaveTeach::
    .string "Eeek!\n"
    .string "Nej! Stop! Hjälp!\p"
    .string "Oh, du er ikke med TEAM ROCKET.\n"
    .string "Undskyld, jeg tröde…\p"
    .string "Tilgiver du mig hvis jeg lärer dig\n"
    .string "THUNDER WAVE-teknikken?$"

Text_ThunderWaveDeclined::
    .string "Oh…\n"
    .string "Men THUNDER WAVE er bekvem…$"

Text_ThunderWaveWhichMon::
    .string "Hvilket POKéMON skal jeg läre\n"
    .string "THUNDER WAVE?$"

Text_ThunderWaveTaught::
    .string "THUNDER WAVE forârsager lamhed hos\n"
    .string "mâl-POKéMON.\p"
    .string "Et lamt POKéMON kan väre ude af stand\n"
    .string "til at beväge sig i kamp.\p"
    .string "Det er et ELECTRIC-type angreb, sâ det\n"
    .string "virker ikke pâ nogle POKéMON.$"

SilphCo_2F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "2. SAL$"

