SilphCo_2F_Text_ConnorIntro::
    .string "Hjaelp!\n"
    .string "Jeg er SILPH-ansat.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "Hvordan vidste du\n"
    .string "at jeg var ROCKET?$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "Jeg arbejder for baade SILPH og TEAM\n"
    .string "ROCKET.$"

SilphCo_2F_Text_JerryIntro::
    .string "Det er forbudt omraade her!\n"
    .string "Ga hjem!$"

SilphCo_2F_Text_JerryDefeat::
    .string "Du er god.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "Kan du loese labyrinten her?\n"
    .string "Det er ikke nemt, siger jeg dig!$"

SilphCo_2F_Text_Grunt1Intro::
    .string "Boern har ikke adgang her!$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "Haardt!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "Diamantformede fliser er teleport-\n"
    .string "blokke.\p"
    .string "De er transportoerer i denne\n"
    .string "hoejteknologiske bygning.$"

SilphCo_2F_Text_Grunt2Intro::
    .string "Hey, unge!\n"
    .string "Hvad vandrer du her for?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "Jeg lavede en fejl!$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "SILPH CO. vil blive forbundet med\n"
    .string "TEAM ROCKET!$"

Text_ThunderWaveTeach::
    .string "Eeek!\n"
    .string "Nej! Stop! Hjaelp!\p"
    .string "Oh, du er ikke med TEAM ROCKET.\n"
    .string "Undskyld, jeg troede…\p"
    .string "Tilgiver du mig hvis jeg laerer dig\n"
    .string "THUNDER WAVE-teknikken?$"

Text_ThunderWaveDeclined::
    .string "Oh…\n"
    .string "Men THUNDER WAVE er bekvem…$"

Text_ThunderWaveWhichMon::
    .string "Hvilket POKeMON skal jeg laere\n"
    .string "THUNDER WAVE?$"

Text_ThunderWaveTaught::
    .string "THUNDER WAVE foraarsager lamhed hos\n"
    .string "maal-POKeMON.\p"
    .string "Et lamt POKeMON kan vaere ude af stand\n"
    .string "til at bevaege sig i kamp.\p"
    .string "Det er et ELECTRIC-type angreb, saa det\n"
    .string "virker ikke paa nogle POKeMON.$"

SilphCo_2F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "2. SAL$"

