Route21_South_Text_JackIntro::
	.string "Jeg fangede mine POKéMON til havs.$"

Route21_South_Text_JackDefeat::
	.string "Dykker!!\n"
	.string "Ned!!$"

Route21_South_Text_JackPostBattle::
	.string "Hvor fangede du dine POKéMON?$"

Route21_South_Text_JeromeIntro::
	.string "Lige nu er jeg i en triathlon.$"

Route21_South_Text_JeromeDefeat::
	.string "Gisper...\n"
	.string "Gisper... Gisper...$"

Route21_South_Text_JeromePostBattle::
	.string "Jeg er udmattet! Men jeg har stadig\n"
	.string "cykelløb og maraton tilbage!$"

Route21_South_Text_RolandIntro::
	.string "Aah!\n"
	.string "Mærk solen og vinden!$"

Route21_South_Text_RolandDefeat::
	.string "Av!\n"
	.string "Jeg tabte!$"

Route21_South_Text_RolandPostBattle::
	.string "Jeg er brændt til et skorpe!$"

Route21_South_Text_ClaudeIntro::
	.string "Hey, skræm ikke fiskene væk!$"

Route21_South_Text_ClaudeDefeat::
	.string "Undskyld! Jeg er bare sâ frustreret\n"
	.string "over ikke at fange noget.$"

Route21_South_Text_ClaudePostBattle::
	.string "Puha, jeg har ikke fanget noget.\n"
	.string "Kunne dette sted faktisk være et\l"
	.string "kæmpe swimmingpool eller noget?$"

Route21_South_Text_NolanIntro::
	.string "Hold mig selskab til jeg fâr et bid.$"

Route21_South_Text_NolanDefeat::
	.string "Det brændte noget tid.$"

Route21_South_Text_NolanPostBattle::
	.string "Aa vent!\n"
	.string "Jeg fik et bid! Ja!$"

Route21_North_Text_LilIntro::
	.string "LIL: Hvad? En kamp?\n"
	.string "IAN, kan du ikke gøre det alene?$"

Route21_North_Text_LilDefeat::
	.string "LIL: Aa, se?\n"
	.string "Vi tabte. Tilfreds nu?$"

Route21_North_Text_LilPostBattle::
	.string "LIL: Jeg er træt.\n"
	.string "Kan vi ikke gâ hjem snart?$"

Route21_North_Text_LilNotEnoughMons::
	.string "LIL: Hvad? En kamp?\n"
	.string "Jeg gider ikke gøre det alene.\l"
	.string "Medbring to POKéMON, vil du?$"

Route21_North_Text_IanIntro::
	.string "IAN: Min søster motionerer ikke nok,\n"
	.string "sâ jeg fik hende med.$"

Route21_North_Text_IanDefeat::
	.string "IAN: Aâ, Søs!\n"
	.string "Tag dig sammen!$"

Route21_North_Text_IanPostBattle::
	.string "IAN: Kom nu, Søs!\p"
	.string "Du taber ikke vægt sâdan!$"

Route21_North_Text_IanNotEnoughMons::
	.string "IAN: Vi vil have en to-mod-to kamp.\n"
	.string "Sâ kan du medbringe to POKéMON?$"
