FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
    .string "Du rejser overalt,\n"
    .string "gør du ikke?\p"
    .string "Du kører ikke dine POKéMON for\n"
    .string "hârdt, vel?\p"
    .string "Lad mig se.\n"
    .string "… … …   … … …$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
    .string "Ah, hmm…\n"
    .string "Jeg ser, jeg ser…$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
    .string "Øh, imponerende.\n"
    .string "Du behandler dine POKéMON rigtigt.\p"
    .string "Jeg tror du kan betros med dette.\p"
    .string "Værsgo, jeg vil gerne give dig dette.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
    .string "{PLAYER} modtog et ÆG\n"
    .string "fra manden!$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
    .string "…Desværre har du ikke plads til\n"
    .string "dette i dit hold.\p"
    .string "Du bør komme tilbage efter det\n"
    .string "en anden gang.$"

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
    .string "やあ\n"
    .string "タマゴを　もらいに\l"
    .string "きて　くれたんだね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
    .string "Jeg modtog det ÆG mens jeg\n"
    .string "rejste.\p"
    .string "Jeg er glad for at jeg mødte en\n"
    .string "som dig.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
    .string "Øh, hej.\n"
    .string "Det er en sød {STR_VAR_2}.\p"
    .string "At se den minder mig om en sod\n"
    .string "lille pige jeg mødte pâ rejse.\p"
    .string "Hun plejede POKéMON blidt...\n"
    .string "Hun var en lille engel.\p"
    .string "Den lille piges navn…\n"
    .string "Jeg tror det var DAISY.$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
    .string "Dette er et fremragende miljø\n"
    .string "til at opdrage POKéMON.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
    .string "Dine POKéMON vokser beundringsværdigt!$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
    .string "Du ved, jeg tror du har talent\n"
    .string "til at være en god AVLER.$"

