FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
    .string "Du rejser overalt,\n"
    .string "goer du ikke?\p"
    .string "Du koerer ikke dine POKeMON for\n"
    .string "haardt, vel?\p"
    .string "Lad mig se.\n"
    .string "… … …   … … …$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
    .string "Ah, hmm…\n"
    .string "Jeg ser, jeg ser…$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
    .string "Oeh, imponerende.\n"
    .string "Du behandler dine POKeMON rigtigt.\p"
    .string "Jeg tror du kan betros med dette.\p"
    .string "Vaersgo, jeg vil gerne give dig dette.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
    .string "{PLAYER} modtog et AeG\n"
    .string "fra manden!$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
    .string "…Desvaerre har du ikke plads til\n"
    .string "dette i dit hold.\p"
    .string "Du boer komme tilbage efter det\n"
    .string "en anden gang.$"

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
    .string "やあ\n"
    .string "タマゴを　もらいに\l"
    .string "きて　くれたんだね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
    .string "Jeg modtog det AeG mens jeg\n"
    .string "rejste.\p"
    .string "Jeg er glad for at jeg moedte en\n"
    .string "som dig.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
    .string "Oeh, hej.\n"
    .string "Det er en soed {STR_VAR_2}.\p"
    .string "At se den minder mig om en sod\n"
    .string "lille pige jeg moedte paa rejse.\p"
    .string "Hun plejede POKeMON blidt...\n"
    .string "Hun var en lille engel.\p"
    .string "Den lille piges navn…\n"
    .string "Jeg tror det var DAISY.$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
    .string "Dette er et fremragende miljoe\n"
    .string "til at opdrage POKeMON.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
    .string "Dine POKeMON vokser beundringsvaerdigt!$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
    .string "Du ved, jeg tror du har talent\n"
    .string "til at vaere en god AVLER.$"

