FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Fwahahaha!\p"
    .string "Et barn som dig tør udfordre mig?\p"
    .string "Bare tanken fâr mig til at ryste\n"
    .string "af latter!\p"
    .string "Godt, jeg viser dig sand skræk\n"
    .string "som ninjamester.\p"
    .string "Gift bringer sikker undergang.\n"
    .string "Søvn gør fjender hjelpeløse.\p"
    .string "Fortvivl over den kravlende skræk\n"
    .string "fra GIFT-type POKéMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Humph!\n"
    .string "Du har bevist din værdi!\p"
    .string "Her!\n"
    .string "Tag SOULBADGE!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "Nâr TOXIC rammer, lider en\n"
    .string "POKéMON mere og mere.\p"
    .string "Skaden forværres efterhânden som\n"
    .string "kampen skrider frem!\p"
    .string "Det vil skræmme fjender!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Nu hvor du har SOULBADGE,\n"
    .string "stiger dine POKéMONs FORSVAR.\p"
    .string "Det lader dig ogsâ SURFE uden for\n"
    .string "kamp.\p"
    .string "Ah!\n"
    .string "Tag ogsâ dette!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} modtog TM06\n"
    .string "fra KOGA.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "Inde i TM06 findes TOXIC!\p"
    .string "Det er en hemmelig teknik der\n"
    .string "daterer cirka 400 âr tilbage.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Gør plads til dette, barn!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "Styrke er ikke nøglen til POKéMON.\n"
    .string "Forstâr du?\p"
    .string "POKéMON handler om strategi!\p"
    .string "Jeg viser hvordan strategi slâr\n"
    .string "râ styrke.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "Hvad?\n"
    .string "Ekstraordinært!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "Sâ du blander styrke med forstand?\n"
    .string "God strategi!\p"
    .string "Det er bemærkelsesværdigt for en\n"
    .string "barn-TRAINER.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "Jeg var engang tryllekunstner.\p"
    .string "Men jeg drømte om at blive ninja,\n"
    .string "sâ jeg meldte mig i dette GYM.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "Jeg er færdig!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Selv om jeg tabte, bliver jeg ved med\n"
    .string "at træne efter læren fra min\l"
    .string "ninjamester KOGA.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Lad os se dig slâ mine specielle\n"
    .string "teknikker!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "Du narrede mig!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "Jeg kan lide gift- og søvnteknikker,\n"
    .string "de holder ved efter kampen!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Stop der!\p"
    .string "De berømte usynlige vægge i\n"
    .string "FUCHSIA GYM driver dig til vanvid?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Whoa!\n"
    .string "Du har det!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "Du imponerede mig!\n"
    .string "Her er et tip!\p"
    .string "Kig grundigt efter huller i de\n"
    .string "usynlige vægge!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "Jeg studerer ogsâ ninjæns vej\n"
    .string "hos mester KOGA!\p"
    .string "Ninjær har lang historie med at\n"
    .string "bruge dyr!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Awoo!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "Jeg har stadig meget at lære.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Mester KOGA kommer fra en lang\n"
    .string "ninja-slægt.\p"
    .string "Hvad stammer du fra?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "Du er dygtigere end jeg trøde!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Hvor der er lys, er der skygge!\p"
    .string "Lys og skygge!\n"
    .string "Hvad vælger du?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i blomst!\p"
    .string "FUCHSIA GYM er et tricket sted.\n"
    .string "Det er fuld af usynlige vægge!\p"
    .string "KOGA kan se nær ud, men han er\n"
    .string "spærret af.\p"
    .string "Du skal finde huller i væggene\n"
    .string "for at nâ ham.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "Det er forbløffende hvordan ninjær\n"
    .string "kan skræmme, selv nu!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "FUCHSIA POKéMON GYM\n"
    .string "LEDER: KOGA\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "FUCHSIA POKéMON GYM\n"
    .string "LEDER: KOGA\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

