FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Fwahahaha!\p"
    .string "Et barn som dig tör udfordre mig?\p"
    .string "Bare tanken fâr mig til at ryste\n"
    .string "af latter!\p"
    .string "Godt, jeg viser dig sand skräk\n"
    .string "som ninjamester.\p"
    .string "Gift bringer sikker undergang.\n"
    .string "Sövn gör fjender hjelpelöse.\p"
    .string "Fortvivl over den kravlende skräk\n"
    .string "fra GIFT-type POKeMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Humph!\n"
    .string "Du har bevist din värdi!\p"
    .string "Her!\n"
    .string "Tag SOULBADGE!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "Nâr TOXIC rammer, lider en\n"
    .string "POKeMON mere og mere.\p"
    .string "Skaden forvärres efterhânden som\n"
    .string "kampen skrider frem!\p"
    .string "Det vil skrämme fjender!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Nu hvor du har SOULBADGE,\n"
    .string "stiger dine POKeMONs FORSVAR.\p"
    .string "Det lader dig ogsâ SURFE uden for\n"
    .string "kamp.\p"
    .string "Ah!\n"
    .string "Tag ogsâ dette!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} modtog TM06\n"
    .string "fra KOGA.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "Inde i TM06 findes TOXIC!\p"
    .string "Det er en hemmelig teknik der\n"
    .string "daterer cirka 400 âr tilbage.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Gör plads til dette, barn!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "Styrke er ikke nöglen til POKeMON.\n"
    .string "Forstâr du?\p"
    .string "POKeMON handler om strategi!\p"
    .string "Jeg viser hvordan strategi slâr\n"
    .string "râ styrke.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "Hvad?\n"
    .string "Ekstraordinärt!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "Sâ du blander styrke med forstand?\n"
    .string "God strategi!\p"
    .string "Det er bemärkelsesvärdigt for en\n"
    .string "barn-TRAINER.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "Jeg var engang tryllekunstner.\p"
    .string "Men jeg drömte om at blive ninja,\n"
    .string "sâ jeg meldte mig i dette GYM.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "Jeg er färdig!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Selv om jeg tabte, bliver jeg ved med\n"
    .string "at träne efter lären fra min\l"
    .string "ninjamester KOGA.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Lad os se dig slâ mine specielle\n"
    .string "teknikker!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "Du narrede mig!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "Jeg kan lide gift- og sövnteknikker,\n"
    .string "de holder ved efter kampen!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Stop der!\p"
    .string "De berömte usynlige vägge i\n"
    .string "FUCHSIA GYM driver dig til vanvid?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Whoa!\n"
    .string "Du har det!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "Du imponerede mig!\n"
    .string "Her er et tip!\p"
    .string "Kig grundigt efter huller i de\n"
    .string "usynlige vägge!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "Jeg studerer ogsâ ninjäns vej\n"
    .string "hos mester KOGA!\p"
    .string "Ninjär har lang historie med at\n"
    .string "bruge dyr!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Awoo!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "Jeg har stadig meget at läre.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Mester KOGA kommer fra en lang\n"
    .string "ninja-slägt.\p"
    .string "Hvad stammer du fra?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "Du er dygtigere end jeg tröde!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Hvor der er lys, er der skygge!\p"
    .string "Lys og skygge!\n"
    .string "Hvad välger du?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i blomst!\p"
    .string "FUCHSIA GYM er et tricket sted.\n"
    .string "Det er fuld af usynlige vägge!\p"
    .string "KOGA kan se när ud, men han er\n"
    .string "spärret af.\p"
    .string "Du skal finde huller i väggene\n"
    .string "for at nâ ham.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "Det er forblöffende hvordan ninjär\n"
    .string "kan skrämme, selv nu!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "FUCHSIA POKeMON GYM\n"
    .string "LEDER: KOGA\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "FUCHSIA POKeMON GYM\n"
    .string "LEDER: KOGA\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

