FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Fwahahaha!\p"
    .string "Et barn som dig toer udfordre mig?\p"
    .string "Bare tanken faar mig til at ryste\n"
    .string "af latter!\p"
    .string "Godt, jeg viser dig sand skraek\n"
    .string "som ninjamester.\p"
    .string "Gift bringer sikker undergang.\n"
    .string "Soevn goer fjender hjelpeloese.\p"
    .string "Fortvivl over den kravlende skraek\n"
    .string "fra GIFT-type POKeMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Humph!\n"
    .string "Du har bevist din vaerdi!\p"
    .string "Her!\n"
    .string "Tag SOULBADGE!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "Naar TOXIC rammer, lider en\n"
    .string "POKeMON mere og mere.\p"
    .string "Skaden forvaerres efterhaanden som\n"
    .string "kampen skrider frem!\p"
    .string "Det vil skraemme fjender!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Nu hvor du har SOULBADGE,\n"
    .string "stiger dine POKeMONs FORSVAR.\p"
    .string "Det lader dig ogsaa SURFE uden for\n"
    .string "kamp.\p"
    .string "Ah!\n"
    .string "Tag ogsaa dette!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} modtog TM06\n"
    .string "fra KOGA.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "Inde i TM06 findes TOXIC!\p"
    .string "Det er en hemmelig teknik der\n"
    .string "daterer cirka 400 aar tilbage.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Goer plads til dette, barn!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "Styrke er ikke noeglen til POKeMON.\n"
    .string "Forstaar du?\p"
    .string "POKeMON handler om strategi!\p"
    .string "Jeg viser hvordan strategi slaar\n"
    .string "raa styrke.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "Hvad?\n"
    .string "Ekstraordinaert!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "Saa du blander styrke med forstand?\n"
    .string "God strategi!\p"
    .string "Det er bemaerkelsesvaerdigt for en\n"
    .string "barn-TRAINER.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "Jeg var engang tryllekunstner.\p"
    .string "Men jeg droemte om at blive ninja,\n"
    .string "saa jeg meldte mig i dette GYM.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "Jeg er faerdig!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Selv om jeg tabte, bliver jeg ved med\n"
    .string "at traene efter laeren fra min\l"
    .string "ninjamester KOGA.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Lad os se dig slaa mine specielle\n"
    .string "teknikker!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "Du narrede mig!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "Jeg kan lide gift- og soevnteknikker,\n"
    .string "de holder ved efter kampen!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Stop der!\p"
    .string "De beroemte usynlige vaegge i\n"
    .string "FUCHSIA GYM driver dig til vanvid?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Whoa!\n"
    .string "Du har det!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "Du imponerede mig!\n"
    .string "Her er et tip!\p"
    .string "Kig grundigt efter huller i de\n"
    .string "usynlige vaegge!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "Jeg studerer ogsaa ninjaens vej\n"
    .string "hos mester KOGA!\p"
    .string "Ninjaer har lang historie med at\n"
    .string "bruge dyr!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Awoo!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "Jeg har stadig meget at laere.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Mester KOGA kommer fra en lang\n"
    .string "ninja-slaegt.\p"
    .string "Hvad stammer du fra?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "Du er dygtigere end jeg troede!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Hvor der er lys, er der skygge!\p"
    .string "Lys og skygge!\n"
    .string "Hvad vaelger du?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i blomst!\p"
    .string "FUCHSIA GYM er et tricket sted.\n"
    .string "Det er fuld af usynlige vaegge!\p"
    .string "KOGA kan se naer ud, men han er\n"
    .string "spaerret af.\p"
    .string "Du skal finde huller i vaeggene\n"
    .string "for at naa ham.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "Det er forbloeffende hvordan ninjaer\n"
    .string "kan skraemme, selv nu!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "FUCHSIA POKeMON GYM\n"
    .string "LEDER: KOGA\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "FUCHSIA POKeMON GYM\n"
    .string "LEDER: KOGA\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

