SafariZone_West_Text_RestHouse::
    .string "HVILESTED$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .string "ANMODNING\p"
    .string "Find venligst SAFARI VOGTERENS\n"
    .string "tabte GULDTÆNDER.\l"
    .string "De er et sted her omkring.\p"
    .string "Belønning tilbudes!\n"
    .string "Kontakt: VOGTER$"

SafariZone_West_Text_SearchForSecretHouse::
    .string "TRAINER TIPS\p"
    .string "Zone-udforskningskampagne!\n"
    .string "Søgningen efter DET HEMMELIGE HUS!$"

SafariZone_West_Text_AreaSign::
    .string "OMRÂDE 3\n"
    .string "OST: CENTER OMRÂDE$"
