VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .string "Jeg er FISKE-GURUEN!\p"
    .string "Jeg elsker simpelthen at fiske!\n"
    .string "Jeg kan ikke undväre det.\p"
    .string "Sig mig, kan du lide at fiske?$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "Fremragende! Jeg kan lide din stil.\n"
    .string "Jeg tror vi kan blive venner.\p"
    .string "Tag dette og fisk, unge ven!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} modtog en GAMMEL ROD fra\n"
    .string "FISKE-GURUEN.$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .string "Fiskeri er en livsstil!\n"
    .string "Det er som den fineste pösi.\p"
    .string "Fra havet til floder, gâ ud\n"
    .string "og fang den store, min ven.$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "Aah…\n"
    .string "Det er sâ skuffende…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "Hej med dig, {PLAYER}!\p"
    .string "Hvordan bider fiskene?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
    .string "Aah nej!\p"
    .string "Jeg havde en fin gave til dig, men du\n"
    .string "har ikke plads til den!$"

