SSAnne_1F_Room6_Text_TakeAShortRest::
    .string "Du ser trät ud. Vil du tage en\n"
    .string "kort hvile?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
    .string "Jeg er glad for at se at alle\n"
    .string "ser forfriskede og livlige ud.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .string "Aah, undskyld at jeg maser.\n"
    .string "Du ligner min lillebror…$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .string "Aah, undskyld at jeg maser.\n"
    .string "Du ligner min lillesöster…$"

