CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "EEVEE kan udvikle sig til een af tre\n"
    .string "slags POKéMON.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "Der er en e-mail besked.\p"
    .string "… … …\p"
    .string "Der er tre legendariske fugle-\n"
    .string "POKéMON.\p"
    .string "De er ARTICUNO, ZAPDOS og\n"
    .string "MOLTRES.\p"
    .string "Deres opholdssted er ukendt.\p"
    .string "Vi planläger at udforske hulen\n"
    .string "när CERULEAN.\p"
    .string "Fra: POKéMON RESEARCH TEAM…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "Et ravpibe!$"
