Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
    .string "Okay, sæt seks POKe BALLS i mit\n"
    .string "bælte…\p"
    .string "Ja, det gør det. Du kan højest have\n"
    .string "seks POKéMON med dig.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
    .string "TEAM ROCKET angriber CERULEAN-\n"
    .string "borgere…\p"
    .string "Der gâr ikke en dag uden TEAM\n"
    .string "ROCKET er i nyhederne.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
    .string "MAND: Hej der, unge mand!\n"
    .string "Har jeg et tilbud til dig!\p"
    .string "Jeg giver dig en hemmelig POKéMON\n"
    .string "- en MAGIKARP - for kun ¥500!\p"
    .string "Sâ du køber den, ikke?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
    .string "MAND: Hej der, skat!\n"
    .string "Har jeg et tilbud til dig!\p"
    .string "Jeg giver dig en hemmelig POKéMON\n"
    .string "- en MAGIKARP - for kun ¥500!\p"
    .string "Sâ du køber den, ikke?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .string "{PLAYER} betalte ublu ¥500\n"
    .string "og købte MAGIKARP…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .string "Nej? Du siger nej? Jeg gør det kun\n"
    .string "som en tjeneste for dig!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .string "Der er ikke plads til flere\n"
    .string "POKéMON, ser det ud til.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .string "Du har brug for flere penge end det!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
    .string "MAND: Jeg giver ikke refusion.\n"
    .string "Du vidste hvad du fik!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .string "Nogle gange har du for mange\n"
    .string "POKéMON med dig til at tilføje flere.\p"
    .string "I sâ fald bør du bare gemme nogle\n"
    .string "pâ en PC.$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .string "Det er en avis.$"
