PokemonLeague_BrunosRoom_Text_Intro::
    .string "Jeg er BRUNO fra ELITE FOUR!\p"
    .string "Gennem streng träning kan mennesker\n"
    .string "og POKéMON blive stärkere\l"
    .string "uden gränse.\p"
    .string "Jeg har levet og tränet med mine\n"
    .string "kämpende POKéMON!\l"
    .string "Og det ändrer sig aldrig!\p"
    .string "{PLAYER}!\p"
    .string "Vi vil slide dig ned med vores\n"
    .string "overlegne styrke!\p"
    .string "Hoo hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .string "Jeg er BRUNO fra ELITE FOUR!\p"
    .string "Gennem streng träning kan mennesker\n"
    .string "og POKéMON blive stärkere\l"
    .string "uden gränse.\p"
    .string "Jeg har levet og tränet med mine\n"
    .string "kämpende POKéMON!\l"
    .string "Og det ändrer sig aldrig!\p"
    .string "{PLAYER}!\p"
    .string "Vi vil slide dig ned med vores\n"
    .string "overlegne styrke!\p"
    .string "Hoo hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat::
    .string "Hvorfor?\n"
    .string "Hvordan kunne jeg tabe?$"

PokemonLeague_BrunosRoom_Text_PostBattle::
    .string "Mit job er gjort.\n"
    .string "Ga möd din näste udfordring.$"
