SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "KAPTEJN: Ooargh…\n"
    .string "Jeg har det forfaerdeligt…\l"
    .string "Urrp! Soesyg…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER} gned KAPTEJNens\n"
    .string "ryg!\p"
    .string "Gnid-gnid…\n"
    .string "Gnid-gnid…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "KAPTEJN: Puh! Tak!\n"
    .string "Jeg har det meget bedre nu.\p"
    .string "Vil du se min skjulte CUT-\n"
    .string "teknik?\p"
    .string "Jeg kunne vise dig min elskede CUT-\n"
    .string "teknik hvis jeg ikke var saa syg…\p"
    .string "Jeg ved det! Du maa faa dette!\n"
    .string "Denne HIDDEN MACHINE!\p"
    .string "Laer CUT til din POKeMON, og\n"
    .string "du kan se den CUTTE naar som helst!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} modtog HM01\n"
    .string "fra KAPTEJNen!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Med CUT kan du faelde\n"
    .string "smaa traeer.\p"
    .string "Hvorfor ikke proeve det med traeerne\n"
    .string "omkring VERMILION CITY?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "KAPTEJN: …Puh!\p"
    .string "Nu hvor jeg ikke er syg laengere,\n"
    .string "gaetter jeg paa det er tid.\p"
    .string "S.S. ANNE vil afsejle snart!\p"
    .string "Farvel, indtil vi vender tilbage til\n"
    .string "VERMILION CITY!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "Aah, nej!\n"
    .string "Du har ikke plads til dette!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "Ad!\n"
    .string "Burde ikke have kigget!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "Saadan overvinder man soesyge…\n"
    .string "KAPTEJNen laeser denne!$"

