PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "DAISY: Hej, {PLAYER}!\p"
    .string "Min bror, {RIVAL}, er ude ved\n"
    .string "Bedstefars LAB.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "DAISY: {PLAYER}, jeg hörte du kämpede\n"
    .string "mod {RIVAL}.\p"
    .string "Jeg ville önske jeg havde set det!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "Bedstefar bad dig om et ärinde?\p"
    .string "Av, det er dovent af ham.\n"
    .string "Her, dette vil hjälpe dig.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} modtog et BYKORT\n"
    .string "fra DAISY.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "Du har ikke plads til dette i\n"
    .string "din TASKE.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "Du kan bruge BYKORTET til at finde\n"
    .string "ud af hvor du er, eller tjekke\l"
    .string "stedsnavne.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "DAISY: Lige som mennesker er POKeMON\n"
    .string "levende väsener.\p"
    .string "Nâr de bliver trätte, giv dem\n"
    .string "venligst hvile.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "Det er et stort kort over KANTO-regionen.\n"
    .string "Det vil väre nyttigt!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "Hylderne er proppet med böger\n"
    .string "om POKeMON.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "DAISY: Hej, {PLAYER}!\n"
    .string "God timing.\p"
    .string "Jeg skal lige til at drikke te.\n"
    .string "Vil du väre med?\p"
    .string "Oh, men se.\n"
    .string "Dine POKeMON er lidt snavsede.\p"
    .string "Skal jeg pudse en?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "Du har ikke brug for pudning?\n"
    .string "Okay, vi tager bare te.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "Hvilken skal jeg pudse?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "DAISY: Okay, jeg fâr den til at se\n"
    .string "pän ud med det samme.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
    .string "{COLOR DARK_GRAY}{STR_VAR_1} ser dösigt tilfreds ud…\p"
    .string "{COLOR RED}DAISY: Sâdan! Färdig.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "{FONT_NORMAL}{STR_VAR_1} ser dösigt tilfreds ud…\p"
    .string "{FONT_FEMALE}DAISY: Sâdan! Färdig.\n"
#endif
    .string "Se? Ser den ikke pän ud?\p"
    .string "Fnise…\n"
    .string "Det er sâdan en söd POKeMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "Oh, undskyld. Jeg kan ärligt ikke\n"
    .string "pudse et ÄG.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "DAISY: Dine POKeMON lärer at elske\n"
    .string "dig hvis du opdrager dem med kärlighed.\p"
    .string "For eksempel, {PLAYER}, mâ jeg se\n"
    .string "din förste POKeMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "Den kan umuligt elske dig mere\n"
    .string "end den gör nu.\p"
    .string "Din POKeMON er lykkelig uden\n"
    .string "ord.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "Den ser meget lykkelig ud.\p"
    .string "Jeg ville önske {RIVAL} kunne se dette\n"
    .string "og läre noget af det.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "Den er ret venlig mod dig.\n"
    .string "Bliv ved med at väre god ved den!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "Den varmes op til dig.\n"
    .string "Tillid mâ vokse mellem jer.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "Den er ikke helt vant til dig\n"
    .string "endnu.\p"
    .string "POKeMON er alle ret forsigtige\n"
    .string "nâr du först fâr dem.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, jeg kan ikke lide mâden\n"
    .string "den stirrer pâ dig.\p"
    .string "Kunne du pröve at väre lidt\n"
    .string "venligere mod den?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "…Oeh, det er ikke nemt for mig at\n"
    .string "sige dette, men…\p"
    .string "Er der en grund til at din POKeMON\n"
    .string "ville hade dig sâ meget?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "Den dejlige og södme\n"
    .string "CLEFAIRY$"

