PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "DAISY: Hej, {PLAYER}!\p"
    .string "Min bror, {RIVAL}, er ude ved\n"
    .string "Bedstefars LAB.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "DAISY: {PLAYER}, jeg hoerte du kaempede\n"
    .string "mod {RIVAL}.\p"
    .string "Jeg ville oenske jeg havde set det!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "Bedstefar bad dig om et aerinde?\p"
    .string "Av, det er dovent af ham.\n"
    .string "Her, dette vil hjaelpe dig.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} modtog et BYKORT\n"
    .string "fra DAISY.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "Du har ikke plads til dette i\n"
    .string "din TASKE.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "Du kan bruge BYKORTET til at finde\n"
    .string "ud af hvor du er, eller tjekke\l"
    .string "stedsnavne.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "DAISY: Lige som mennesker er POKeMON\n"
    .string "levende vaesener.\p"
    .string "Naar de bliver traette, giv dem\n"
    .string "venligst hvile.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "Det er et stort kort over KANTO-regionen.\n"
    .string "Det vil vaere nyttigt!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "Hylderne er proppet med boeger\n"
    .string "om POKeMON.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "DAISY: Hej, {PLAYER}!\n"
    .string "God timing.\p"
    .string "Jeg skal lige til at drikke te.\n"
    .string "Vil du vaere med?\p"
    .string "Oh, men se.\n"
    .string "Dine POKeMON er lidt snavsede.\p"
    .string "Skal jeg pudse en?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "Du har ikke brug for pudning?\n"
    .string "Okay, vi tager bare te.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "Hvilken skal jeg pudse?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "DAISY: Okay, jeg faar den til at se\n"
    .string "paen ud med det samme.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
    .string "{COLOR DARK_GRAY}{STR_VAR_1} ser doesigt tilfreds ud…\p"
    .string "{COLOR RED}DAISY: Saadan! Faerdig.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "{FONT_NORMAL}{STR_VAR_1} ser doesigt tilfreds ud…\p"
    .string "{FONT_FEMALE}DAISY: Saadan! Faerdig.\n"
#endif
    .string "Se? Ser den ikke paen ud?\p"
    .string "Fnise…\n"
    .string "Det er saadan en soed POKeMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "Oh, undskyld. Jeg kan aerligt ikke\n"
    .string "pudse et AEG.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "DAISY: Dine POKeMON laerer at elske\n"
    .string "dig hvis du opdrager dem med kaerlighed.\p"
    .string "For eksempel, {PLAYER}, maa jeg se\n"
    .string "din foerste POKeMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "Den kan umuligt elske dig mere\n"
    .string "end den goer nu.\p"
    .string "Din POKeMON er lykkelig uden\n"
    .string "ord.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "Den ser meget lykkelig ud.\p"
    .string "Jeg ville oenske {RIVAL} kunne se dette\n"
    .string "og laere noget af det.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "Den er ret venlig mod dig.\n"
    .string "Bliv ved med at vaere god ved den!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "Den varmes op til dig.\n"
    .string "Tillid maa vokse mellem jer.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "Den er ikke helt vant til dig\n"
    .string "endnu.\p"
    .string "POKeMON er alle ret forsigtige\n"
    .string "naar du foerst faar dem.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, jeg kan ikke lide maaden\n"
    .string "den stirrer paa dig.\p"
    .string "Kunne du proeve at vaere lidt\n"
    .string "venligere mod den?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "…Oeh, det er ikke nemt for mig at\n"
    .string "sige dette, men…\p"
    .string "Er der en grund til at din POKeMON\n"
    .string "ville hade dig saa meget?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "Den dejlige og soedme\n"
    .string "CLEFAIRY$"

