SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "Jeg spekulerer pâ om SILPH er färdig…$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "Tak for at redde os!$"

SilphCo_8F_Text_Grunt1Intro::
    .string "Sâ langt kommer du ikke!$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "Ikke nok kampâand!$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "Hvis du ikke vender om…\n"
    .string "Sâ ringer jeg efter forstärkning!$"

SilphCo_8F_Text_ParkerIntro::
    .string "Du skaber os problemer!$"

SilphCo_8F_Text_ParkerDefeat::
    .string "Hva?\n"
    .string "Jeg tabte?$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "Sâ hvad synes du om SILPH\n"
    .string "BYGNINGs labyrint?$"

SilphCo_8F_Text_Grunt2Intro::
    .string "Jeg er en af de fire ROCKET\n"
    .string "BRÖDRE!$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "Whoo!\n"
    .string "Oh, Brödre!$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "Jeg overlader dig til mine brödre.$"

SilphCo_8F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "8. SAL$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .string "TEAM ROCKETs BOSS er frygtelig\n"
    .string "grausom!\p"
    .string "For ham er POKéMON bare värktöjer\n"
    .string "der skal bruges.\p"
    .string "Hvad sker der hvis den tyran\n"
    .string "overtar vores virksomhed…$"

