SSAnne_2F_Room4_Text_LamarIntro::
    .string "Hvad finder du mere värdifuldt,\n"
    .string "en stärk eller en själden POKéMON?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "Jeg mâ hilse dig!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "Personligt foreträkker jeg stärke og\n"
    .string "själdne POKéMON.$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "Jeg tror ikke jeg sâ dig til\n"
    .string "festen?$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "Tag det roligt!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "Aah, jeg tilbeder dine stärke POKéMON!\n"
    .string "Aah, hvor misundelig jeg er pâ dem!$"

