SSAnne_2F_Room4_Text_LamarIntro::
    .string "Hvad finder du mere vaerdifuldt,\n"
    .string "en staerk eller en sjaelden POKeMON?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "Jeg maa hilse dig!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "Personligt foretraekker jeg staerke og\n"
    .string "sjaeldne POKeMON.$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "Jeg tror ikke jeg saa dig til\n"
    .string "festen?$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "Tag det roligt!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "Aah, jeg tilbeder dine staerke POKeMON!\n"
    .string "Aah, hvor misundelig jeg er paa dem!$"

