SSAnne_2F_Room4_Text_LamarIntro::
    .string "Hvad finder du mere værdifuldt,\n"
    .string "en stærk eller en sjælden POKéMON?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "Jeg mâ hilse dig!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "Personligt foretrækker jeg stærke og\n"
    .string "sjældne POKéMON.$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "Jeg tror ikke jeg sâ dig til\n"
    .string "festen?$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "Tag det roligt!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "Aah, jeg tilbeder dine stærke POKéMON!\n"
    .string "Aah, hvor misundelig jeg er pâ dem!$"

