SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .string "Du må beholde enhver genstand du\n"
    .string "finder i SAFARI ZONE.\p"
    .string "Men tiden løb ud hvis du prøver\n"
    .string "at få dem alle på en gang.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .string "Ga til den dybeste del af\n"
    .string "SAFARI ZONE. Du vinder en præmie!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .string "Min EEVEE udviklede sig til FLAREON.\p"
    .string "Men en venns EEVEE blev til\n"
    .string "VAPOREON. Hvorfor mon?$"
