SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .string "Du maa beholde enhver genstand du\n"
    .string "finder i SAFARI ZONE.\p"
    .string "Men tiden loeb ud hvis du proever\n"
    .string "at faa dem alle paa en gang.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .string "Ga til den dybeste del af\n"
    .string "SAFARI ZONE. Du vinder en praemie!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .string "Min EEVEE udviklede sig til FLAREON.\p"
    .string "Men en venns EEVEE blev til\n"
    .string "VAPOREON. Hvorfor mon?$"
