ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
    .string "Hey, hoerte du nyheden?\p"
    .string "PC-netvaerket her kan nu forbinde\n"
    .string "med PC'er i KANTO.\p"
    .string "Jeg ved ikke hvordan det skete,\n"
    .string "men det er fantastisk!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
    .string "Det er umuligt at SURFE mellem\n"
    .string "oeerne heromkring.\p"
    .string "Stroemmene er for hurtige og\n"
    .string "farlige.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
    .string "Lad os mase BAeR!\n"
    .string "…Det ville vaere at spilde BAeR?\p"
    .string "Man kan altid finde BAeR paa\n"
    .string "jorden i BERRY FOREST.$"

