ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
    .string "Hey, hörte du nyheden?\p"
    .string "PC-netvärket her kan nu forbinde\n"
    .string "med PC'er i KANTO.\p"
    .string "Jeg ved ikke hvordan det skete,\n"
    .string "men det er fantastisk!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
    .string "Det er umuligt at SURFE mellem\n"
    .string "öerne heromkring.\p"
    .string "Strömmene er for hurtige og\n"
    .string "farlige.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
    .string "Lad os mase BAeR!\n"
    .string "…Det ville väre at spilde BAeR?\p"
    .string "Man kan altid finde BAeR pâ\n"
    .string "jorden i BERRY FOREST.$"

