OneIsland_KindleRoad_Text_MariaIntro::
    .string "Veiret er herligt!\n"
    .string "Perfekt til en kamp!$"

OneIsland_KindleRoad_Text_MariaDefeat::
    .string "Aijâa!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
    .string "Plask ikke vand i ansigtet pâ mig!\n"
    .string "Du ödelägger makeupen.$"

OneIsland_KindleRoad_Text_AbigailIntro::
    .string "Jeg fâr solbrändning…$"

OneIsland_KindleRoad_Text_AbigailDefeat::
    .string "Ah, du er sâdan en led.$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
    .string "Jeg kan lide den kasket du har.\n"
    .string "Mâske jeg ogsâ skulle tage en pâ…$"

OneIsland_KindleRoad_Text_FinnIntro::
    .string "Set herfra räger MT. EMBER\n"
    .string "op i himlen.$"

OneIsland_KindleRoad_Text_FinnDefeat::
    .string "Ja, er du ikke hârd?$"

OneIsland_KindleRoad_Text_FinnPostBattle::
    .string "Himlen er uendelig her omkring.$"

OneIsland_KindleRoad_Text_GarrettIntro::
    .string "Jeg tog en pause fra at svömme,\n"
    .string "sâ udfordrer du mig?$"

OneIsland_KindleRoad_Text_GarrettDefeat::
    .string "Hey, hvad…\n"
    .string "Du er god, du!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
    .string "I stedet for altid at bruge SURF,\n"
    .string "burde du ogsâ svömme lidt.$"

OneIsland_KindleRoad_Text_TommyIntro::
    .string "Vent! Vent et sekund!\n"
    .string "Jeg tror jeg har fâet en stor en!$"

OneIsland_KindleRoad_Text_TommyDefeat::
    .string "Jeg har tabt det hele igen…$"

OneIsland_KindleRoad_Text_TommyPostBattle::
    .string "Ikke nok med at jeg tabte, slap den\n"
    .string "store ogsâ väk!$"

OneIsland_KindleRoad_Text_SharonIntro::
    .string "Vil du hjälpe mig med min\n"
    .string "träning?$"

OneIsland_KindleRoad_Text_SharonDefeat::
    .string "Du var bedre end mig.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
    .string "Det er tydeligt at du er dygtig.\n"
    .string "Jeg kan lide dig!$"

OneIsland_KindleRoad_Text_TanyaIntro::
    .string "Der er ikke en dag vi ikke\n"
    .string "träner!$"

OneIsland_KindleRoad_Text_TanyaDefeat::
    .string "Jeg er sâdan en tosse!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
    .string "Jeg träner endnu hardere fra nu af!$"

OneIsland_KindleRoad_Text_SheaIntro::
    .string "Hver morgen, för frokost,\n"
    .string "svömmer jeg rundt om denne ö.$"

OneIsland_KindleRoad_Text_SheaDefeat::
    .string "Gisp…\n"
    .string "Gisp…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
    .string "Jeg tabte fordi jeg er slät ud af\n"
    .string "alt det lob jeg har lavet…$"

OneIsland_KindleRoad_Text_HughIntro::
    .string "Kläd dig passende til kamp!\n"
    .string "Skaf dig af med det fjollede outfit!$"

OneIsland_KindleRoad_Text_HughDefeat::
    .string "Hvorfor mig?!$"

OneIsland_KindleRoad_Text_HughPostBattle::
    .string "Selv kampsportsudövere bliver\n"
    .string "modebevidste nu om stunder…$"

OneIsland_KindleRoad_Text_BryceIntro::
    .string "Alt smager godt nâr du er\n"
    .string "ude i naturen.$"

OneIsland_KindleRoad_Text_BryceDefeat::
    .string "Av, fordärvet!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
    .string "Vandet i vulkanomrâder er\n"
    .string "delikt.$"

OneIsland_KindleRoad_Text_ClaireIntro::
    .string "Min frokost mättede os, sâ vil du\n"
    .string "kämpe mod os til motion?$"

OneIsland_KindleRoad_Text_ClaireDefeat::
    .string "Det fik mig til at svede.$"

OneIsland_KindleRoad_Text_ClairePostBattle::
    .string "Hvad skal jeg göre?\n"
    .string "Jeg er sulten igen.$"

OneIsland_KindleRoad_Text_KiaIntro::
    .string "KIA: Min storebror og jeg er et\n"
    .string "fantastisk team!$"

OneIsland_KindleRoad_Text_KiaDefeat::
    .string "KIA: Hva?!\n"
    .string "Det kan jeg ikke tro!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
    .string "KIA: Hvordan kan der väre nogen\n"
    .string "bedre end min storebror?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
    .string "KIA: Hvis du vil kämpe med os,\n"
    .string "skal du have mindst to POKeMON\l"
    .string "med.$"

OneIsland_KindleRoad_Text_MikIntro::
    .string "MIK: Sammen med KIA er jeg ikke\n"
    .string "bange for noget!$"

OneIsland_KindleRoad_Text_MikDefeat::
    .string "MIK: Whoa!\n"
    .string "Det er for meget!$"

OneIsland_KindleRoad_Text_MikPostBattle::
    .string "MIK: Hvordan kunne mit team med\n"
    .string "KIA fejle?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
    .string "MIK: Hey, vil du kämpe med os to?\p"
    .string "Tag to eller flere POKeMON med,\n"
    .string "sâ.$"

OneIsland_KindleRoad_Text_RouteSign::
    .string "Dette er KINDLE ROAD.\p"
    .string "Gâ lige ud til MT. EMBER.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
    .string "Tänd ilden i dit hjerte!\n"
    .string "EMBER SPA$"

