PokemonTower_4F_Text_PaulaIntro::
    .string "Spoegelse! Nej!\n"
    .string "Kwaaah!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "Hvor er spoegelsen?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "Jeg maa have droemt…$"

PokemonTower_4F_Text_LaurelIntro::
    .string "Vaer forbandet med mig!\n"
    .string "Kwaaah!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "Hvad!$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "Vi kan ikke bestemme identiteten af\n"
    .string "spoegelserne…$"

PokemonTower_4F_Text_JodyIntro::
    .string "Huhuhu…\n"
    .string "Slaa mig ikke!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "Hva?\n"
    .string "Hvem? Hvad?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "Maa de afdoede POKeMON hvile i\n"
    .string "fred…$"
