PokemonTower_4F_Text_PaulaIntro::
    .string "Spøgelse! Nej!\n"
    .string "Kwâah!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "Hvor er spøgelsen?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "Jeg mâ have drømt…$"

PokemonTower_4F_Text_LaurelIntro::
    .string "Vær forbandet med mig!\n"
    .string "Kwâah!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "Hvad!$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "Vi kan ikke bestemme identiteten af\n"
    .string "spøgelserne…$"

PokemonTower_4F_Text_JodyIntro::
    .string "Huhuhu…\n"
    .string "Slâ mig ikke!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "Hva?\n"
    .string "Hvem? Hvad?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "Mâ de afdøde POKéMON hvile i\n"
    .string "fred…$"
