PokemonTower_4F_Text_PaulaIntro::
    .string "Spögelse! Nej!\n"
    .string "Kwâah!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "Hvor er spögelsen?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "Jeg mâ have drömt…$"

PokemonTower_4F_Text_LaurelIntro::
    .string "Vär forbandet med mig!\n"
    .string "Kwâah!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "Hvad!$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "Vi kan ikke bestemme identiteten af\n"
    .string "spögelserne…$"

PokemonTower_4F_Text_JodyIntro::
    .string "Huhuhu…\n"
    .string "Slâ mig ikke!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "Hva?\n"
    .string "Hvem? Hvad?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "Mâ de afdöde POKéMON hvile i\n"
    .string "fred…$"
