CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "SUPER REPEL holder sväkke POKéMON\n"
    .string "pâ afstand…\p"
    .string "Hmm, det er en stärkere REPEL.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "Til lange ture bör du köbe\n"
    .string "REVIVE.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "Top-ting til TRAINERS!\p"
    .string "2F: TRAINER'S MARKET$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "Vi har en kunde, LANCE, som\n"
    .string "kommer lejlighedsvis.\p"
    .string "Han köber altid kapper.\p"
    .string "Jeg undrer mig… Har han mange\n"
    .string "identiske kapper derhjemme?$"
