SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "TEAM ROCKET er i oprör over\n"
    .string "en indtränger.\p"
    .string "Det er dig, ikke?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "TEAM ROCKET er stukket af!\n"
    .string "Du er vores helt! Tak!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "Jeg hörte et barn vandre\n"
    .string "omkring.$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "Boom!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "Det er ikke klogt at söge kamp med\n"
    .string "TEAM ROCKET!$"

SilphCo_5F_Text_BeauIntro::
    .string "Vi studerer POKe BALL-teknologi pâ\n"
    .string "denne sal.$"

SilphCo_5F_Text_BeauDefeat::
    .string "Pokkers!\n"
    .string "Forbandet!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "Vi arbejdede pâ den ultimative POKe\n"
    .string "BALL der kunne fange hvad som helst.$"

SilphCo_5F_Text_DaltonIntro::
    .string "Hvââd?\p"
    .string "Der bör ikke väre börn her!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "Oh, gud!$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "Du er kun pâ 5. sal.\n"
    .string "Det er langt til min BOSS!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "Vis TEAM ROCKET lidt respekt!$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "Host…\n"
    .string "Host…$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "Hvad det angâr.\p"
    .string "KOFFING udvikler sig til WEEZING!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "Det er en POKeMON RAPPORT!\p"
    .string "POKeMON LAB skabte PORYGON,\n"
    .string "det förste virtual-reality POKeMON.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "Det er en POKeMON RAPPORT!\p"
    .string "Over 350 POKeMON-teknikker er\n"
    .string "blevet bekräftet.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "Det er en POKeMON RAPPORT!\p"
    .string "Nogle POKeMON er bekräftet at\n"
    .string "udvikle sig nâr de byttes.$"

SilphCo_5F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "5. SAL$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "De böller der overtog vores\n"
    .string "bygning…\p"
    .string "Deres BOSS sagde han ledte efter\n"
    .string "stärke POKeMON.\p"
    .string "Jeg hâber vores PRESIDENT undgik\n"
    .string "problemer…$"
