SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "TEAM ROCKET er i oproer over\n"
    .string "en indtraenger.\p"
    .string "Det er dig, ikke?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "TEAM ROCKET er stukket af!\n"
    .string "Du er vores helt! Tak!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "Jeg hoerte et barn vandre\n"
    .string "omkring.$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "Boom!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "Det er ikke klogt at soege kamp med\n"
    .string "TEAM ROCKET!$"

SilphCo_5F_Text_BeauIntro::
    .string "Vi studerer POKe BALL-teknologi paa\n"
    .string "denne sal.$"

SilphCo_5F_Text_BeauDefeat::
    .string "Pokkers!\n"
    .string "Forbandet!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "Vi arbejdede paa den ultimative POKe\n"
    .string "BALL der kunne fange hvad som helst.$"

SilphCo_5F_Text_DaltonIntro::
    .string "Hvaaaad?\p"
    .string "Der boer ikke vaere boern her!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "Oh, gud!$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "Du er kun paa 5. sal.\n"
    .string "Det er langt til min BOSS!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "Vis TEAM ROCKET lidt respekt!$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "Host…\n"
    .string "Host…$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "Hvad det angaar.\p"
    .string "KOFFING udvikler sig til WEEZING!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "Det er en POKeMON RAPPORT!\p"
    .string "POKeMON LAB skabte PORYGON,\n"
    .string "det foerste virtual-reality POKeMON.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "Det er en POKeMON RAPPORT!\p"
    .string "Over 350 POKeMON-teknikker er\n"
    .string "blevet bekraeftet.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "Det er en POKeMON RAPPORT!\p"
    .string "Nogle POKeMON er bekraeftet at\n"
    .string "udvikle sig naar de byttes.$"

SilphCo_5F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "5. SAL$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "De boeller der overtog vores\n"
    .string "bygning…\p"
    .string "Deres BOSS sagde han ledte efter\n"
    .string "staerke POKeMON.\p"
    .string "Jeg haaber vores PRESIDENT undgik\n"
    .string "problemer…$"
