LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "Jeg leder efter genstande der oeger\n"
    .string "POKeMONs statistikker.\p"
    .string "De virker i loebet af en enkelt kamp.\p"
    .string "X ATTACK, X DEFEND, X SPEED og\n"
    .string "X SPECIAL er hvad jeg soeger.\p"
    .string "Ved du hvor jeg kan faa dem?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "Koebte du REVIVES?\n"
    .string "De genopliver besvimet POKeMON!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "Nogle gange udfordrer et TRAINER-\n"
    .string "par dig med to POKeMON paa én gang.\p"
    .string "Sker det, skal du sende to POKeMON\n"
    .string "ud i kamp ogsaa.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　5000¥でした$"

