SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "Grunt!\p"
    .string "Jeg er KARATE MESTEREN!\n"
    .string "Jeg er LEADEREN her!\p"
    .string "Vil du udfordre os?\n"
    .string "Forvent ingen nâde!\p"
    .string "Fwâa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "Hwa!\n"
    .string "Arrgh! Besejret!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "Sandelig, jeg har tabt!\p"
    .string "Men jeg beder dig, tag ikke\n"
    .string "vârt emblem som din trofä!\p"
    .string "Til gengäld giver jeg dig et värdifuldt\n"
    .string "FIGHTING POKéMON!\p"
    .string "Välig hvilken som helst du vil!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "Grunt!\n"
    .string "Bliv og trän karate med os!$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "Hoargh!\n"
    .string "Tag dine sko af!$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "Jeg giver op!$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "Vent bare til du ser vores MESTER!\n"
    .string "Jeg er en lille fisk sammenlignet med ham!$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "Jeg hörer du er god!\n"
    .string "Vis mig det!$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "Dommer!\n"
    .string "Et point!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
    .string "Vores MESTER er en pro-fighter.\n"
    .string "Vär forberedt pâ at tabe!$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "Hiyah!\n"
    .string "Jeg frygter intet hârdt!\p"
    .string "Jeg splintrer kampesten under träning\n"
    .string "hver dag!$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "Yow!\n"
    .string "Stubbede fingre!$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "Det eneste der skrämmer os er\n"
    .string "psykisk kraft!$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "Hwâh!\p"
    .string "Du träder ind i vores\n"
    .string "FIGHTING DOJO!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "Oof!\n"
    .string "Jeg giver op!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "De bedste fightere i landet\n"
    .string "träner her.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "Vil du have den hârd-sparkende\n"
    .string "HITMONLEE?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "{PLAYER} modtog {STR_VAR_1}\n"
    .string "fra KARATE MESTEREN.$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "Vil du have den stempel-slagende\n"
    .string "HITMONCHAN?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "Du bör ikke blive grâdig…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "Fjender pâ alle sider!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "Hvad man sär, det höster man.$"

SaffronCity_Dojo_Text_FightingDojo::
    .string "FIGHTING DOJO$"

