Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Lad mig se…\n"
	.string "Uha! Du har kun fanget\l"
	.string "{STR_VAR_3} slags POKéMON!\p"
	.string "Du har brug for {STR_VAR_1} slags\n"
	.string "for at fâ {STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "…Oh. Jeg forstâr.\p"
	.string "Nâr du har {STR_VAR_1} slags POKéMON,\n"
	.string "kom tilbage efter {STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Oh! Du har ikke plads til\n"
	.string "{STR_VAR_2}.$"
