@ The text here is a copy/paste from Hoenn's various berry NPCs, all unused and untranslated

PetalburgCity_Gym_Text_GiveEnigmaBerry::
	.string "Far: “Hej, {PLAYER}!\p"
	.string "Jeg har fået en sjælden BÆR,\n"
	.string "så den får du!”$"

Route104_Text_PlantBerriesInSoilTakeThis::
	.string "BÆR der vokser i den bløde jord,\n"
	.string "må du gerne plukke frit…\p"
	.string "men det er god stil at plante ét\n"
	.string "nyt BÆR samme sted bagefter.\p"
	.string "Her, du får en af mig.$"

Route104_Text_TrainersOftenMakeMonHoldBerries::
	.string "Du ligner en TRÆNER, ikke?\p"
	.string "TRÆNERE lader ofte deres POKéMON\n"
	.string "holde BÆR.\p"
	.string "Om du vil dyrke dem eller bruge dem,\n"
	.string "det er op til dig.$"

Route111_Text_WateredPlantsEveryDayTakeBerry::
	.string "Jeg vandede planterne hver dag,\n"
	.string "og så blomstrede de helt vildt.\p"
	.string "Nu har jeg også masser af BÆR!\p"
	.string "Her!\n"
	.string "Tag det her.$"

Route111_Text_TryToMakeRedPokeblock::
	.string "Prøv at lave en rød POKEBLOCK!\n"
	.string "Held og lykke, {STR_VAR_1}!$"

Route111_Text_WhatColorBerriesToLookForToday::
	.string "Hvilken farve BÆR\n"
	.string "skal jeg mon lede efter i dag?$"

Route114_Text_GatheringBerriesForContest::
	.string "Jeg samler BÆR for at vinde\n"
	.string "POKéMON-konkurrencer.\p"
	.string "Du må gerne få nogle af mig!$"

Route114_Text_GoodLuckToYouToo::
	.string "Held og lykke til dig også!$"

Route114_Text_WhatBerriesShouldIPlantToday::
	.string "Hvilke BÆR skal jeg plante i dag…\n"
	.string "og hvilken farve POKEBLOCK skal jeg lave…\p"
	.string "Det er faktisk sjovt at tænke over.$"

Route120_Text_PokeblocksExpressionOfLove::
	.string "POKEBLOCKS der kommer ud af casen…\p"
	.string "Og en POKéMON som griber den\n"
	.string "og spiser den…\p"
	.string "Det er kærlighed, ikke?$"

Route120_Text_YouUnderstandTakeThis::
	.string "Ja, ja!\n"
	.string "Du forstår det virkelig.\p"
	.string "Her, tag den her.$"

Route120_Text_OwnImpressionsImportantTakeThis::
	.string "Okay…\n"
	.string "Men det er også vigtigt at føle anderledes.\p"
	.string "Her, tag den her.$"

Route120_Text_BerryIsRareRaiseItWithCare::
	.string "Det BÆR skulle være ret sjældent,\n"
	.string "så pas godt på det, når du dyrker det!$"

Route120_Text_IllGetMoreBerriesFromBerryMaster::
	.string "Jeg må hente flere BÆR hos BÆR-MESTEREN.$"

LilycoveCity_Text_BerrySuitsYou::
	.string "Ja…\p"
	.string "Ligesom et jakkesæt passer til mig,\n"
	.string "og saltvind passer til havet,\l"
	.string "så passer BÆR vist til dig…\p"
	.string "Hvorfor mon?$"

LilycoveCity_Text_BecauseYoureTrainer::
	.string "Det er selvfølgelig fordi…\p"
	.string "du er TRÆNER!$"

LilycoveCity_Text_PokeblocksSuitPokemon::
	.string "Ja…\p"
	.string "Ligesom enkelhed passer til mig,\n"
	.string "så passer POKEBLOCKS til POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry::
	.string "De kalder mig BÆR-MESTEREN.\p"
	.string "Jeg dyrker og deler BÆR,\n"
	.string "så verden kan blive fyldt med\l"
	.string "smukke blomster.\p"
	.string "Du skal også have et BÆR!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother::
	.string "Kom nu, vær ikke genert - tag et mere!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop::
	.string "Husk også blomsterbutikken PRETTY PETAL\n"
	.string "i nærheden af RUSTBORO.\p"
	.string "Lad os få verden til at blomstre!$"

Route123_BerryMastersHouse_Text_DoneForToday::
	.string "Det var alt for i dag.\n"
	.string "Kom igen en anden dag.\p"
	.string "Lad os få verden til at blomstre!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately::
	.string "Gamlingens måde at dyrke BÆR på\n"
	.string "er verdens bedste.\p"
	.string "Det er jeg stolt af.\p"
	.string "For resten,\n"
	.string "har du hørt et godt ordsprog for nylig?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis::
	.string "Åh! Det var et virkelig godt ordsprog!\n"
	.string "Det rørte mig.\p"
	.string "Her, tag det her.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis::
	.string "Åh! Det var et ret godt ordsprog.\n"
	.string "Du er også noget særligt.\p"
	.string "Her, tag det her.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife::
	.string "Mine fire børnebørn bliver sikkert\n"
	.string "endnu større end den gamle.\p"
	.string "Livet løber aldrig tør for glæde!$"

Route123_BerryMastersHouse_Text_Ah::
	.string "Nå…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop::
	.string "Hej!\p"
	.string "Vi er PRETTY PETAL BLOMSTERBUTIK,\n"
	.string "og vi spreder blomster i verden!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries::
	.string "{PLAYER}{KUN}, vil du høre om BÆR?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries::
	.string "Dit navn er…\p"
	.string "{PLAYER}{KUN}, ikke?\n"
	.string "Det er et rigtig fint navn!\l"
	.string "{PLAYER}{KUN}, vil du høre om BÆR?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation::
	.string "BÆR kan nogle gange findes i\n"
	.string "mørk, blød jord.\l"
	.string "Og så…\p"
	.string "når du plukker et, skal du plante ét nyt!\p"
	.string "Så spirer det,\n"
	.string "vokser op, blomstrer,\l"
	.string "og laver nye BÆR.\p"
	.string "På den måde spreder vi blomster\n"
	.string "i hele verden -\l"
	.string "det er min drøm!\p"
	.string "Så plant også BÆR, {PLAYER}{KUN},\n"
	.string "og hjælp verden med at blomstre!$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness::
	.string "Blomster får én til at føle sig\n"
	.string "virkelig glad, ikke?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis::
	.string "Hej!\p"
	.string "Jo mere man passer blomster,\n"
	.string "jo flottere blomstrer de.\p"
	.string "Du fik også lyst til at passe dem,\n"
	.string "ikke? Her, den er til dig.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation::
	.string "Hver gang BÆR vokser,\n"
	.string "så vand dem med en vandkande!\p"
	.string "Og en ting mere:\p"
	.string "Hvis BÆR får lov at sidde for længe,\n"
	.string "falder de ned på jorden,\l"
	.string "men så kan de spire igen!\p"
	.string "Vildt, ikke?\n"
	.string "Man mærker virkelig livets kraft.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers::
	.string "Jeg lærer af mine storesøstre,\n"
	.string "og gør mig umage med at dyrke blomster.\p"
	.string "Her! Den får du!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries::
	.string "Man kan plante BÆR så de vokser,\n"
	.string "eller lade POKéMON holde dem.\p"
	.string "Men jeg hørte, at der findes en maskine\n"
	.string "som kan blande flere BÆR\l"
	.string "til POKéMON-slik.\p"
	.string "Jeg vil også have noget slik!$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese::
	.string "Hvad hedder du, {STR_VAR_1}?\p"
	.string "… … …\n"
	.string "Nåh, fint navn!\p"
	.string "Jeg hedder KIRI.\p"
	.string "Mor og far gav mig navnet,\n"
	.string "fordi de ønskede jeg voksede op\l"
	.string "til at blive et varmt menneske!\p"
	.string "Her, du får også den her.$"

SootopolisCity_Text_GiveYouThisBerryToo::
	.string "Og {STR_VAR_1}, du får også\n"
	.string "det her BÆR - det er KIRIs yndlings!$"

SootopolisCity_Text_WhatKindOfWishInYourName::
	.string "Hvilket ønske mon gemmer sig\n"
	.string "i dit navn, {STR_VAR_1}?$"

SootopolisCity_Text_LikeSeasonBornIn::
	.string "Forår, sommer, efterår, vinter…\n"
	.string "Mon man elsker forår hvis man er født der,\l"
	.string "og sommer hvis man er født om sommeren?$"

SootopolisCity_Text_ThenILoveAutumn::
	.string "Så fordi KIRI er født i efteråret,\n"
	.string "elsker jeg efterår!\p"
	.string "Hvad kan du bedst lide, {STR_VAR_1}?$"

SootopolisCity_Text_OhDoesntMatter::
	.string "Okay…\n"
	.string "Måske hænger det ikke sammen…\p"
	.string "Der er så meget jeg gerne vil vide.$"
