@ The text here is a copy/paste from Hoenn's competitive brothers, the NPCs in Sootopolis who request to see big Barboach/Shroomish (Seedot/Lotad in Emerald). It's all unused and untranslated

SootopolisCity_Text_PleaseShowMeBigMon::
    .string "Jeg er meget interesseret i store\n"
    .string "{STR_VAR_1}!\p"
    .string "Hvad? Har du en {STR_VAR_1}?\n"
    .string "V-v-vent lige…\l"
    .string "Vis den til mig!$"

SootopolisCity_Text_GrandMonThanksForShowingMe::
    .string "Wow! Den er stor!\n"
    .string "Sikke en fantastisk {STR_VAR_1}!\p"
    .string "Tak fordi du viste mig den.\n"
    .string "Tag det her som tak.$"

SootopolisCity_Text_ReceivedOneItem::
    .string "{PLAYER} modtog\n"
    .string "{STR_VAR_2}!$"

SootopolisCity_Text_HuhBagIsCrammedFull::
    .string "Hov?\n"
    .string "Din taske er helt fuld.$"

SootopolisCity_Text_IveSeenBiggerMonThanThisOne::
    .string "Hmm… Jeg har set en\n"
    .string "større {STR_VAR_1} end den her…$"

SootopolisCity_Text_QuiteSomethingButNotMon::
    .string "Nå, den er da ellers ret… vent,\n"
    .string "det er jo ikke en {STR_VAR_1}!$"

SootopolisCity_Text_TooBadDontHaveBigMon::
    .string "Har du ikke en stor {STR_VAR_1}?\l"
    .string "Det var ærgerligt…\n"
    .string "Vis mig en stor {STR_VAR_1} næste gang.$"

SootopolisCity_Text_BiggestMonPlayersXCmColossus::
    .string "Den største {STR_VAR_1} nogensinde!\n"
    .string "{STR_VAR_2}s på {STR_VAR_3} cm!$"
