@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "Jeg er DAGPLEJEMANDEN.\p"
	.string "Jeg hjaelper med at passe TRAINERs\n"
	.string "kaere POKeMON.\p"
	.string "Hvis du vil have mig til at opdrage\n"
	.string "dine POKeMON, tal med min kone.$"

DayCare_Text_DoYouWantEgg::
	.string "Ah, det er dig!\p"
	.string "Vi passede dine POKeMON, og\n"
	.string "gode gud, blev vi overraskede!\p"
	.string "Din POKeMON fik et AEG!\p"
	.string "Vi ved ikke hvordan det skete,\n"
	.string "men din POKeMON havde det.\p"
	.string "Du vil gerne have det, ikke?$"

DayCare_Text_YourMonIsDoingFine::
	.string "Ah, det er dig! Godt at se dig.\n"
	.string "Din {STR_VAR_1} har det fint.$"

DayCare_Text_IllKeepIt::
	.string "Na, saa beholder jeg det.\n"
	.string "Tak!$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "Du har ikke plads til det…\n"
	.string "Kom tilbage naar du har lavet plads.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER} modtog AEGGET fra\n"
	.string "DAGPLEJEMANDEN.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "Pas godt paa det.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine::
	.string "Ah, det er dig! Din {STR_VAR_1} og\n"
	.string "{STR_VAR_2} har det fint.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "Jeg beholder det virkelig.\n"
	.string "Du vil gerne have det, ikke?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "Jeg er DAGPLEJEKONEN.\p"
	.string "Vi kan opdrage POKeMON for dig.\p"
	.string "Vil du have os til at opdrage en?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "Hvilken POKeMON skal vi opdrage\n"
	.string "for dig?$"

DayCare_Text_WellRaiseYourMon::
	.string "Fint, vi opdrager din {STR_VAR_1}\n"
	.string "et stykke tid.\p"
	.string "Kom tilbage efter den senere.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "Vi kan opdrage to af dine POKeMON.\p"
	.string "Vil du have os til at opdrage\n"
	.string "en POKeMON mere for dig?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "Min mand ledte efter dig.$"

DayCare_Text_FineThenComeAgain::
	.string "Oh, fint da.\n"
	.string "Kom igen.$"

DayCare_Text_NotEnoughMoney::
	.string "Du har ikke nok penge…$"

DayCare_Text_TakeOtherOneBackToo::
	.string "Vil du ogsaa hente den anden?$"

DayCare_Text_ComeAgain::
	.string "Fint.\n"
	.string "Kom igen.$"

DayCare_Text_GoodToSeeYou::
	.string "Ah, det er dig!\n"
	.string "Godt at se dig.\p"
	.string "Dine POKeMON maa have det\n"
	.string "godt!$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "Din {STR_VAR_1} er steget\n"
	.string "{STR_VAR_2} niveau.$"

DayCare_Text_YourPartyIsFull::
	.string "Din POKeMON-hold er fuldt.\n"
	.string "Lav plads, og kom saa til mig.$"

DayCare_Text_TakeBackWhichMon::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX::
	.string "Hvis du vil have din {STR_VAR_1} tilbage,\n"
	.string "koster det ¥{STR_VAR_2}.$"

DayCare_Text_HeresYourMon::
	.string "Perfekt!\n"
	.string "Her er din POKeMON.$"

DayCare_Text_TookBackMon::
	.string "{PLAYER} hentede {STR_VAR_1} hos\n"
	.string "DAGPLEJEKONEN.$"

DayCare_Text_YouHaveJustOneMon::
	.string "Oh? Men du har kun en\n"
	.string "POKeMON.\p"
	.string "Kom tilbage en anden gang.$"

DayCare_Text_TakeYourMonBack::
	.string "Vil du hente din POKeMON tilbage?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "Hvis du efterlader den POKeMON,\n"
	.string "hvad vil du saa kaempe med?\p"
	.string "Kom tilbage en anden gang.$"

DayCare_Text_Huh::
	.string "Hva?$"
