@ The text here is a copy/paste from Hoenn's Eon Ticket event, all unused and untranslated

Text_DadLetterArrivedForYouPlayer::
	.string "Far: “{PLAYER}! Godt du kom!\n"
	.string "Der er kommet et brev til dig.”$"

Text_DadPassForShipNeverSeenBefore::
	.string "Far: “Det er en bådbillet,\n"
	.string "jeg aldrig har set før…\l"
	.string "Du burde prøve at tage til havnen.”$"

Text_FerryToSlateportOhThatPass::
	.string "Færge til havnen…\p"
	.string "Hov?\n"
	.string "Den billet der…!$"

Text_YoureOneWhoBroughtOddPass::
	.string "Er det dig med den mærkelige\n"
	.string "billet?\p"
	.string "Stedet du vil til er en lille ø\n"
	.string "langt mod syd…\p"
	.string "Ingen ved, hvad der sker derude…\l"
	.string "Det vækker eventyrlysten i mig!\p"
	.string "Kom så, hop om bord!$"

Text_NothingHereSailBackToLilycove::
	.string "Der er ikke meget på den lille ø…\n"
	.string "Skal vi sejle tilbage?$"

Text_SailHomeWeWill::
	.string "Fint! Så sejler vi hjemad!$"

Text_AsYouLikeThen::
	.string "Okay.\n"
	.string "Gør som du vil.$"

SouthernIsland_Interior_Text_Sign::
	.string "Alle drømme er en anden form for virkelighed.\n"
	.string "Glem det aldrig…$"

SouthernIsland_Exterior_Text_Sign::
	.string "Det, som minderne slører,\n"
	.string "ønsker hjertet at indprente for evigt…$"
