gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}OAK POKéMON-FORSKNINGSLAB$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}At lave en komplet guide over alle\n"
	.string "POKéMON i verden…\p"
	.string "Det var min drøm!$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK ser måske ikke ud af meget,\n"
	.string "men han er autoriteten på POKéMON.\p"
	.string "Mange POKéMON-TRÆNERE holder ham i\n"
	.string "høj agtelse.$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK siges at bo sammen med\n"
	.string "sine børnebørn, DAISY og {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg har hørt at OAK interesserer\n"
	.string "sig meget for dig, barn.\p"
	.string "Den gamle knark var engang stærk og\n"
	.string "flot.\p"
	.string "Men det er årtier siden.\n"
	.string "Nu er han en skygge af sig selv.$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK får snart sit eget\n"
	.string "radioprogram.\p"
	.string "Programmet hedder PROF.\n"
	.string "OAKS POKéMON-SEMINAR.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Viser du DAISY din POKéMON,\n"
	.string "kan hun sige hvor meget den kan lide dig.\p"
	.string "Af og til vil hun endda soignere\n"
	.string "en POKéMON for dig.$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Den som POKéMON kan lide allerbedst,\n"
	.string "er vist DAISY.$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hun stod og plejede POKéMON blidt…\n"
	.string "hun var som en lille engel.\p"
	.string "Den lille piges navn…\n"
	.string "jeg mener det var DAISY.$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK siges at bo sammen med\n"
	.string "sine børnebørn, DAISY og {RIVAL}.$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En pige fra PALLET TOWN, DAISY,\n"
	.string "nyder sin TE hver dag.\p"
	.string "Hun besøger CELADON STORCENTER\n"
	.string "for at købe TE.$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Forårskonkurrencens POKéMON CONTEST-\n"
	.string "Stormester er DAISY OAK fra\l"
	.string "PALLET TOWN!$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PEWTER CITY POKéMON GYM\n"
	.string "LEDER: BROCK\l"
	.string "Den klippefaste POKéMON-TRÆNER!$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Min klippehårde viljestyrke kan ses\n"
	.string "selv i mine POKéMON.\p"
	.string "Mine POKéMON er alle hårde som sten\n"
	.string "og fulde af viljestyrke.\p"
	.string "Ja, mine POKéMON er alle af\n"
	.string "typen ROCK!$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Der er ikke mange seriøse POKéMON-\n"
	.string "TRÆNERE her.\p"
	.string "De er som INSEKTSAMLERE,\n"
	.string "bare hobbyfolk.\p"
	.string "Men BROCK fra PEWTER GYM er slet\n"
	.string "ikke sådan.$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK er sej. Han er ikke kun stærk.\n"
	.string "Folk kan lide og respekterer ham.\p"
	.string "Jeg vil være GYM-LEDER\n"
	.string "ligesom ham.$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hej, jeg graver fossiler frem her\n"
	.string "under MT. MOON.\p"
	.string "Nogle gange giver BROCK fra\n"
	.string "PEWTER GYM en hånd med.$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK griner sjældent, men siges\n"
	.string "ikke at kunne stoppe når han først gør.$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CERULEAN CITY POKéMON GYM\n"
	.string "LEDER: MISTY\l"
	.string "Den drengetøjsagtige havfrue!$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Min politik er fuldt angreb\n"
	.string "med WATER-POKéMON!$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY er en TRÆNER som vil blive\n"
	.string "ved med at udvikle sig.\p"
	.string "Hun taber ikke til en som dig!$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Stærke TRÆNERE og WATER-POKéMON\n"
	.string "er et almindeligt syn her.\p"
	.string "De siger, at MISTY fra\n"
	.string "CERULEAN GYM træner her.$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Denne pynt er et berømt sted at\n"
	.string "gå på date.\p"
	.string "MISTY, GYM-LEDEREN, har store\n"
	.string "forhåbninger til stedet.$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY siges at beundre LORELEI\n"
	.string "fra ELITE FOUR.$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}VERMILION CITY POKéMON GYM\n"
	.string "LEDER: LT. SURGE\l"
	.string "Den Lynhurtige Amerikaner!$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hør her, knægt, elektriske POKéMON\n"
	.string "reddede mig under krigen!$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Da jeg var i hæren, var\n"
	.string "LT. SURGE min strenge chef.\p"
	.string "Han var en hård opdrager.$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE var altid kendt for sin\n"
	.string "forsigtige natur i hæren.$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE satte selv fælderne op\n"
	.string "i GYM'en.\p"
	.string "Han satte dobbelte låse overalt.$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE siges at have været\n"
	.string "pilot hjemme i Amerika.\p"
	.string "Han brugte strøm fra POKéMON til\n"
	.string "at drive sit fly.$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CELADON CITY POKéMON GYM\n"
	.string "LEDER: ERIKA\l"
	.string "Den naturglade prinsesse!$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg studerer kunsten at lave\n"
	.string "blomsterarrangementer.\p"
	.string "Mine POKéMON er udelukkende af\n"
	.string "typen GRASS.$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Vores LEDER ERIKA er måske stille,\n"
	.string "men hun er berømt her omkring.$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Vi bruger kun POKéMON af typen GRASS\n"
	.string "i vores GYM.\p"
	.string "Hvorfor? Vi bruger dem også til\n"
	.string "blomsterarrangementer!$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg ville aldrig samle POKéMON,\n"
	.string "hvis de var grimme.$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Rygterne siger at hvis du kigger ind i\n"
	.string "CELADON GYM, kan du tit\l"
	.string "se ERIKA tage en lur.$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}FUCHSIA CITY POKéMON GYM\n"
	.string "LEDER: KOGA\l"
	.string "Den giftige ninjamester$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Fortvivl over den snigende rædsel fra\n"
	.string "POKéMON af typen POISON!$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Selv om jeg tabte, fortsætter jeg\n"
	.string "med at træne efter læren\l"
	.string "fra KOGA, min ninjamester.$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Min far er GYM-LEDER i\n"
	.string "denne by.\p"
	.string "Jeg træner også i at bruge\n"
	.string "POISON-POKéMON, ligesom min far.$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}KOGA siges at have indgående\n"
	.string "kendskab til medicin.\p"
	.string "Han fremstiller endda medicin for at\n"
	.string "pleje sine POKéMON raske.$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SAFARI ZONE er enorm, ikke\n"
	.string "sandt?\p"
	.string "FUCHSIAs GYM-LEDER, KOGA, \n"
	.string "patruljerer området af og til.\p"
	.string "Takket være ham kan vi lege her\n"
	.string "i sikkerhed.$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SAFFRON CITY POKéMON GYM\n"
	.string "LEDER: SABRINA\l"
	.string "Mesteren af PSYCHIC-POKéMON!$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Du kender vel den kvindelige\n"
	.string "GYM-LEDER i SAFFRON CITY?\p"
	.string "Hun bruger POKéMON af typen\n"
	.string "PSYCHIC, ikke?$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg har haft psykiske kræfter siden\n"
	.string "jeg var barn.\p"
	.string "Det begyndte da en ske, jeg\n"
	.string "tankeløst kastede, bøjede.$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg bryder mig ikke om at kæmpe, men\n"
	.string "hvis du vil, viser jeg dig mine kræfter!$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Folk siger at SABRINA kan\n"
	.string "kommunikere med sine POKéMON\l"
	.string "under kamp uden at tale.$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SABRINA knuste lige KARATE-\n"
	.string "MASTEREN ved siden af.$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CINNABAR ISLAND POKéMON GYM\n"
	.string "LEDER: BLAINE\l"
	.string "Den hidsige quizmester!$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mine ildfulde POKéMON er alle barske\n"
	.string "og klar med intens varme!\p"
	.string "De brænder alle udfordrere ned!$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Vores LEDER, BLAINE, for vild\n"
	.string "i bjergene.\p"
	.string "Da natten faldt på, dukkede en\n"
	.string "ildfugl-POKéMON op.\p"
	.string "Dens lys lod BLAINE finde\n"
	.string "vejen ned i sikkerhed.$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE fra CINNABAR GYM er en\n"
	.string "ret sær fyr.\p"
	.string "Han har boet på øen længe før\n"
	.string "LAB'et blev bygget.$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Det er et foto af BLAINE og\n"
	.string "MR. FUJI.\p"
	.string "De står skulder ved\n"
	.string "skulder med store grin.$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE siges kun at tage sine mørke\n"
	.string "solbriller af når han finder på\l"
	.string "nye quizspørgsmål.$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg er LORELEI fra ELITE FOUR.$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ingen kan slå mig når det gælder\n"
	.string "iskolde POKéMON.$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvor er denne person født?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En stor og magtfuld TRÆNER er\n"
	.string "vokset op på denne ø.\p"
	.string "Jeg gætter på at selv du kender hende.\n"
	.string "Det er LORELEI fra ELITE FOUR!$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LORELEI er kendt for sin logiske,\n"
	.string "beregnende og kølige kampstil,\l"
	.string "men hun har en overraskende hemmelighed!$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Vidste du at LORELEI har masser\n"
	.string "af bamser?\p"
	.string "Hver gang hun vender tilbage til\n"
	.string "FOUR ISLAND, vokser samlingen!$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Den LAPRAS hun har, er nok den\n"
	.string "hun mødte som barn.\p"
	.string "Jeg tror det var i ICEFALL CAVE\n"
	.string "hun fangede den.\p"
	.string "Måske har den POKéMON været med\n"
	.string "hende lige siden.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg er BRUNO fra ELITE FOUR!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg har levet og trænet med mine\n"
	.string "FIGHTING-POKéMON!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO kom tilsyneladende med i ELITE\n"
	.string "FOUR pga. sin brændende ambition om\l"
	.string "at kæmpe mod de bedste TRÆNERE.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO, som er ældre end mig,\n"
	.string "besøger SPA af og til.\p"
	.string "Han kommer for at genoptræne skader,\n"
	.string "både sine egne og sine POKéMONs.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Han er en af ELITE FOUR.\n"
	.string "Han hedder BRUNO.\p"
	.string "Han gik skuffet væk da han\n"
	.string "fandt ud af at de var udsolgt\l"
	.string "af Rage Candybars.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Selv BRUNO…\n"
	.string "Han trænede tidligere med en fyr\l"
	.string "ved navn BRAWLY.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg er AGATHA fra ELITE FOUR.$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AGATHAs POKéMON af typen GHOST er\n"
	.string "skrækindjagende stærke.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Den gamle dame har også et meget\n"
	.string "hidsigt temperament.\p"
	.string "Der skal ikke meget til før\n"
	.string "den skræmmende dame råber op.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I sin ungdom var AGATHA og PROF.\n"
	.string "OAK rivaler der kæmpede om\l"
	.string "overherredømme som TRÆNERE.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg har hørt at OAK interesserer\n"
	.string "sig meget for dig, barn.\p"
	.string "Den gamle knark var engang stærk og\n"
	.string "flot.\p"
	.string "Men det er årtier siden.\n"
	.string "Nu er han en skygge af sig selv.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tag AGATHA for eksempel.\p"
	.string "Hun satte rekord som det\n"
	.string "ældste ELITE FOUR-medlem nogensinde.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg leder ELITE FOUR.\p"
	.string "Du kan kalde mig LANCE,\n"
	.string "drage-TRÆNEREN.$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Du ved at drager er\n"
	.string "mytiske POKéMON.\p"
	.string "De er svære at fange og opdrage,\n"
	.string "men deres kræfter er overlegne.\p"
	.string "De er næsten uforgængelige.\n"
	.string "Der er ingen smarte tricks mod dem.$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Han står for retfærdighed!\n"
	.string "Han er kølig og alligevel passioneret!\l"
	.string "Han er den bedste, LANCE!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Vi har en kunde, LANCE,\n"
	.string "som kommer af og til.\p"
	.string "Han køber altid kapper.\p"
	.string "Mon… har han mange\n"
	.string "identiske kapper derhjemme?$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCEs bedstefar menes at være\n"
	.string "ældste i en berømt klan af\l"
	.string "dragemestre.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Så vidt jeg har hørt, har LANCE\n"
	.string "en fætter som er GYM-LEDER\l"
	.string "langt væk et sted.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL er jo verdensberømt som\n"
	.string "POKeMANIAC.\p"
	.string "Han opfandt også PC'ens\n"
	.string "POKéMON-opbevaringssystem.$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL har masser af POKéMON!\n"
	.string "Han samler også på sjældne!$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Han er mit barnebarn!\p"
	.string "Han har altid kunnet lide at samle,\n"
	.string "selv da han var barn!$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL er en POKeMANIAC, så han elsker\n"
	.string "dem alle.\p"
	.string "Tilsyneladende var den første han\n"
	.string "fangede en ABRA.$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILLs hjemby er GOLDENROD CITY,\n"
	.string "hvor hans familie stadig bor.\p"
	.string "Jeg har hørt at det er en livlig,\n"
	.string "festlig by.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tilsyneladende kan BILL slet ikke\n"
	.string "fordrage mælk.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Han er virkelig venlig.\p"
	.string "Han tager sig af forladte og\n"
	.string "forældreløse POKéMON.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Den gamle fyr kom marcherende lige\n"
	.string "ind i vores HIDEOUT.\p"
	.string "Så begyndte han at skælde ud om\n"
	.string "at TEAM ROCKET mishandler POKéMON.\p"
	.string "Så nu snakker vi det bare igennem\n"
	.string "som voksne.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}POKéMON FAN MAGAZINE\n"
	.string "Månedlig hovedpræmieudtrækning!\p"
	.string "Ansøgningsblanketten er…\p"
	.string "Væk! Den er klippet ud.\n"
	.string "Nogen må allerede have ansøgt.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Der går et rygte…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg har hørt at MR. FUJI heller ikke\n"
	.string "oprindeligt er herfra.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Det er et foto af BLAINE og\n"
	.string "MR. FUJI.\p"
	.string "De står skulder ved\n"
	.string "skulder med store grin.$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Redaktør: Den generte MR. FUJI afslog\n"
	.string "vores interviewønsker.\p"
	.string "Han er en venlig mand som er elsket\n"
	.string "og respekteret i LAVENDER TOWN.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET fanger POKéMON fra\n"
	.string "hele verden.\p"
	.string "De er vigtige redskaber for at holde\n"
	.string "vores kriminelle foretagende i gang.\p"
	.string "Jeg er lederen, GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Yndlingstype POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}De bøller der overtog vores\n"
	.string "bygning…\p"
	.string "Deres BOSS sagde at han søgte\n"
	.string "stærke POKéMON.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvordan er denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKETs BOSS er frygtelig\n"
	.string "grusom!\p"
	.string "For ham er POKéMON bare redskaber\n"
	.string "der skal bruges.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Velkommen til mit skjulested!\p"
	.string "Sådan forbliver det indtil jeg kan\n"
	.string "genoprette TEAM ROCKETs storhed.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hvad laver denne person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hold da op! Var GIOVANNI\n"
	.string "GYM-LEDEREN i VIRIDIAN?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Familie og venner?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Du… Du er vel ikke GIOVANNIs barn,\n"
	.string "vel?\p"
	.string "Nej, det kan ikke passe.\n"
	.string "GIOVANNIs barn har rødt hår.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. OAK$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: PROF. OAK\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hvorfor konkurrerer og kæmper\n"
	.string "POKéMON så hårdt for dig?\p"
	.string "Det gør de fordi de kan se\n"
	.string "den kærlighed og tillid du har\l"
	.string "til POKéMON.\p"
	.string "Glem aldrig det.$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}DAISY$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: DAISY\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mens jeg roligt nød mine\n"
	.string "tepauser, er du blevet meget\l"
	.string "dygtig og stærk.\p"
	.string "Jeg håber du forbliver en god rival\n"
	.string "for min lillebror.$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BROCK$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: BROCK\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I vores store verden må der være\n"
	.string "mange hårde TRÆNERE.\p"
	.string "Lad os begge blive ved med at træne\n"
	.string "og gøre os stærkere!$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: MISTY\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg bliver ved med at træne her i\n"
	.string "denne GYM.\p"
	.string "Når jeg bliver bedre, vil jeg gerne\n"
	.string "ud på vejen og rejse.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LT. SURGE$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: LT. SURGE\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, knægt!\n"
	.string "Du elektrificerede mig i vores kamp!\p"
	.string "Jeg vidste ikke at der fandtes\n"
	.string "modige TRÆNERE som dig.\p"
	.string "Det fik mig til at ændre mening\n"
	.string "om dig!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: ERIKA\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg er så glad for at der findes stærke\n"
	.string "TRÆNERE som dig.\p"
	.string "Bare den bevidsthed inspirerer og\n"
	.string "motiverer mig til at prøve hårdere.\p"
	.string "Kom meget gerne forbi igen.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: KOGA\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Du og jeg må begge sætte vores\n"
	.string "mål højere og arbejde mod\l"
	.string "at møde vores udfordringer.\p"
	.string "Nu må jeg gå og træne min datter.$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: SABRINA\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Den kærlighed du har til dine\n"
	.string "POKéMON…\p"
	.string "Det var en kraft som min psykiske\n"
	.string "kraft aldrig kunne besejre.$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BLAINE$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: BLAINE\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mine FIRE-POKéMON!\n"
	.string "De bliver endnu stærkere!\p"
	.string "Og nu, en quiz. Hvor mange slags\n"
	.string "POKéMON af typen FIRE findes der?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: LORELEI\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg måtte takke dig for din\n"
	.string "hjælp.\p"
	.string "Men det har intet at gøre med vores\n"
	.string "kampe.\p"
	.string "Du må hellere passe på næste gang!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: BRUNO\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Den store styrke i dine POKéMON\n"
	.string "og dig har jeg selv mærket.\p"
	.string "Næste gang burde jeg måske vise dig\n"
	.string "hvordan du træner dig selv.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: AGATHA\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Når du bliver ældre, så vover du\n"
	.string "ikke at blive blød som den gamle OAK!\p"
	.string "Vær som mig og bliv ved med at kæmpe!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: LANCE\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Jeg overvejer at tage tilbage til\n"
	.string "min hjemby.\p"
	.string "Jeg vil genoptræne mine POKéMON af\n"
	.string "typen DRAGON og styrke dem.\p"
	.string "Jeg vil gerne invitere dig til min\n"
	.string "hjemby en dag.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: BILL\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hej! CELIO havde kun\n"
	.string "ros til dig.\p"
	.string "Det gør mig glad at høre.\p"
	.string "Når du fanger sjældne POKéMON,\n"
	.string "så kom og vis mig dem, okay? Lov mig det!$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: MR. FUJI\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I stedet for kun at ønske lykke\n"
	.string "for dine egne POKéMON…\p"
	.string "…kan du så ikke ønske lykke\n"
	.string "for alle POKéMON?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Fra: GIOVANNI\n"
	.string "Til: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Der er intet jeg ønsker at sige\n"
	.string "til dig.\p"
	.string "Jeg vil udelukkende koncentrere mig om\n"
	.string "at forbedre mig selv, og ingen andre.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "PALLET TOWN$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "FORSKNINGSLAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "FORSKNINGSLAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "VIRIDIAN CITY$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "POKéMON-LIGA$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "FORSKNINGSLAB$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "FORSKNINGSLAB$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "VANDLABYRINT$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "VIRIDIAN CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "CELADON PALÆ$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "PEWTER CITY$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "PEWTER GYM$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "PEWTER CITY$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "ROUTE 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "MT. MOON$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "PEWTER MUSEUM$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "CERULEAN GYM$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "CERULEAN GYM$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "SEAFOAM ISLANDS$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "CERULEAN CAPE$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "CELADON CITY$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "CELADON PALÆ$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "FUCHSIA GYM$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "FUCHSIA GYM$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "SAFARI ZONE$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "THREE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "RESORT GORGEOUS$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "POKéMON-LIGA$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "POKéMON-LIGA$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "FIVE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "POKéMON-LIGA$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "POKéMON-LIGA$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "EMBER SPA$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "TWO ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "SEVAULT CANYON$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "POKéMON-LIGA$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "SEVEN ISLAND$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "POKéMON-LIGA$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "SIX ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "POKéMON-LIGA$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "POKéMON-LIGA$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "CELADON STORCENTER$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "POKéMON TOWER$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "ROCKET-SKJULESTED$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "SILPH CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "SILPH CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "VIRIDIAN GYM$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "VIRIDIAN GYM$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "ROCKET-LAGER$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "SKILT$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "PROF. OAK$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "ASSISTENT$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "ASSISTENT$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "ASSISTENT$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "KVINDE$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "MAND$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "GAMMEL DAME$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "SKILT$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "BROCK$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "UNG MAND$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "BOY$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "MAND$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "SKILT$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "MISTY$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "UNG MAND$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "DAME$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "SKILT$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "LT. SURGE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "DWAYNE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "SKILT$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "SKILT$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "MAND$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "SKILT$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "UNG MAND$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "SKILT$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "BLAINE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "KVINDE$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "FOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "LILLE PIGE$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "GAMMEL DAME$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "KVINDE$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "GAMMEL DAME$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "KVINDE$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "LILLE PIGE$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "UNG MAND$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "LILLE DRENG$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "LILLE PIGE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "MAGASIN$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "MAND$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "FOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "FORSKER$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "FORSKER$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "MAND$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "POKéMON JOURNAL\p"
	.string "Særtema: PEWTER GYM\n"
	.string "LEDER BROCK!\p"
	.string "BROCK griner sjældent, men siges ikke\n"
	.string "at kunne stoppe hvis han begynder.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "POKéMON JOURNAL\p"
	.string "Særtema: CERULEAN GYM\n"
	.string "LEDER MISTY!\p"
	.string "MISTY siges at beundre LORELEI\n"
	.string "fra ELITE FOUR.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "POKéMON JOURNAL\p"
	.string "Særtema: VERMILION GYM\n"
	.string "LEDER LT. SURGE!\p"
	.string "LT. SURGE siges at have været\n"
	.string "pilot hjemme i Amerika.\p"
	.string "Han brugte strøm skabt af\n"
	.string "POKéMON til at drive sit fly.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "POKéMON JOURNAL\p"
	.string "Særtema: CELADON GYM\n"
	.string "LEDER ERIKA!\p"
	.string "Rygterne siger at hvis du kigger ind i\n"
	.string "CELADON GYM, kan du ofte\l"
	.string "se ERIKA tage en lur.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "POKéMON JOURNAL\p"
	.string "Særtema: FUCHSIA GYM\n"
	.string "LEDER KOGA!\p"
	.string "KOGA siges at have indgående\n"
	.string "viden om medicin.\p"
	.string "Han fremstiller endda medicin til at\n"
	.string "pleje sine POKéMON raske.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "POKéMON JOURNAL\p"
	.string "Særtema: SAFFRON GYM\n"
	.string "LEDER SABRINA!\p"
	.string "Folk siger at SABRINA kan\n"
	.string "kommunikere med sine POKéMON\l"
	.string "under kamp uden at tale.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "POKéMON JOURNAL\p"
	.string "Særtema: CINNABAR GYM\n"
	.string "LEDER BLAINE!\p"
	.string "BLAINE siges kun at tage sine mørke\n"
	.string "solbriller af når han finder på\l"
	.string "nye quizspørgsmål.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "POKéMON JOURNAL\p"
	.string "Særtema:\n"
	.string "ELITE FOURs LORELEI!\p"
	.string "LORELEI er kendt for sin logiske,\n"
	.string "beregnende og kølige kampstil,\l"
	.string "men har en overraskende hemmelighed!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "POKéMON JOURNAL\p"
	.string "Særtema:\n"
	.string "ELITE FOURs BRUNO!\p"
	.string "BRUNO kom tilsyneladende med i ELITE\n"
	.string "FOUR pga. sin brændende ambition om\l"
	.string "at kæmpe mod de bedste TRÆNERE.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "POKéMON JOURNAL\p"
	.string "Særtema:\n"
	.string "ELITE FOURs AGATHA!\p"
	.string "I sin ungdom var AGATHA og PROF.\n"
	.string "OAK rivaler der kæmpede om\l"
	.string "overherredømme som TRÆNERE.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "POKéMON JOURNAL\p"
	.string "Særtema:\n"
	.string "ELITE FOURs LANCE!\p"
	.string "LANCEs bedstefar menes at være\n"
	.string "ældste i en berømt klan af\l"
	.string "dragemestre.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "POKéMON JOURNAL\p"
	.string "Særtema: PROF. OAK,\n"
	.string "POKéMON-forskeren!\p"
	.string "PROF. OAK siges at bo med sine\n"
	.string "børnebørn DAISY og {RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "Dette er et POKéMON JOURNAL fra\n"
	.string "for mange år siden…\p"
	.string "POKéMON JOURNAL\n"
	.string "CONTEST-særtema!\p"
	.string "Forårets POKéMON CONTESTs\n"
	.string "Stormester er DAISY OAK fra\l"
	.string "PALLET TOWN!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "POKéMON JOURNAL\p"
	.string "Særtema:\n"
	.string "MR. FUJI fra POKéMON HOUSE!\p"
	.string "Redaktør: Den generte MR. FUJI afslog\n"
	.string "vores interviewønsker.\p"
	.string "Han er en venlig mand som er elsket\n"
	.string "og respekteret i LAVENDER TOWN.$"
