@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Den er proppet med POKéMON-\n"
	.string "bøger.$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "Et BYKORT.$"

Text_PokeMartShelf::
	.string "Wow!\n"
	.string "Masser af POKéMON-ting!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Tallerkener og fade stâr pænt\n"
	.string "opstillet.$"

Text_Kitchen::
	.string "Det lugter lækkert!\n"
	.string "Nogen har lavet mad her.$"

Text_Dresser::
	.string "Det er et pænt lavet kommode.\n"
	.string "Der er plads til en masse ting.$"

Text_Snacks::
	.string "Der er en stak snacks her.$"

Text_PokemartSign::
	.string "Alt hvad du behøver!\n"
	.string "POKéMON MART$"

Text_PokecenterSign::
	.string "Helbred dine POKéMON!\n"
	.string "POKéMON CENTER$"

Text_Indigo_UltimateGoal::
	.string "INDIGO PLATEAU\p"
	.string "TRÆNERNES ultimative mâl!\n"
	.string "POKéMON LEAGUE HQ$"

Text_Indigo_HighestAuthority::
	.string "INDIGO PLATEAU\p"
	.string "Den højeste POKéMON-myndighed!\n"
	.string "POKéMON LEAGUE HQ$"

Text_Food::
	.string "Den burde være fuld af alle slags\n"
	.string "lækre ting at spise.$"

Text_Blueprints::
	.string "Det er en slags tegning.\n"
	.string "Den er fuld af diagrammer og tekst.$"

Text_Painting::
	.string "Det er et smukt billede af en POKéMON.\n"
	.string "Den ser ud til at have det godt.$"

Text_PowerPlantMachine::
	.string "Hvad kan denne maskine være?\n"
	.string "Lad være med at rode med den!$"

Text_Telephone::
	.string "Det er en telefon.\n"
	.string "Brug den hellere ikke.$"

Text_Computer::
	.string "Det er alle mulige indviklede ord og\n"
	.string "tal der ikke giver mening…$"

Text_AdvertisingPoster::
	.string "Det er en reklameplakat om\n"
	.string "alle mulige produkter.$"

Text_TastyFood::
	.string "Aah, det lugter lækkert!\n"
	.string "Maven kunne godt begynde at knurre!$"

Text_TrashBin::
	.string "Indeni…\n"
	.string "……\p"
	.string "Der er ingenting her!$"

Text_Cup::
	.string "Det er en kop med et POKéMON-\n"
	.string "mærke pâ.$"

Text_PolishedWindow::
	.string "Vinduet er meget velpoleret.$"

Text_BeautifulSkyWindow::
	.string "Uden for vinduet…\p"
	.string "Himlen ser fantastisk\n"
	.string "smøk ud.$"

Text_BlinkingLights::
	.string "Lys i forskellige farver\n"
	.string "blinker til og fra.$"

Text_NeatlyLinedUpTools::
	.string "Alle mulige værktøjer stâr\n"
	.string "pænt opstillet.$"

Text_ImpressiveMachine::
	.string "Det er en slags maskine.\n"
	.string "Den er da imponerende.$"

Text_VideoGame::
	.string "Det er det seneste videospil!\n"
	.string "Det ser sjovert ud!$"

Text_Burglary::
	.string "Der er tydelige tegn pâ indbrud\n"
	.string "her…$"

Text_PlayerFacingTVScreen::
	.string "Der er en POKéMON i TV!\n"
	.string "Den ser ud til at more sig.$"
