@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Den er proppet med POKeMON-\n"
	.string "boeger.$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "Et BYKORT.$"

Text_PokeMartShelf::
	.string "Wow!\n"
	.string "Masser af POKeMON-ting!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Tallerkener og fade staar paent\n"
	.string "opstillet.$"

Text_Kitchen::
	.string "Det lugter laekkert!\n"
	.string "Nogen har lavet mad her.$"

Text_Dresser::
	.string "Det er et paent lavet kommode.\n"
	.string "Der er plads til en masse ting.$"

Text_Snacks::
	.string "Der er en stak snacks her.$"

Text_PokemartSign::
	.string "Alt hvad du behoever!\n"
	.string "POKeMON MART$"

Text_PokecenterSign::
	.string "Helbred dine POKeMON!\n"
	.string "POKeMON CENTER$"

Text_Indigo_UltimateGoal::
	.string "INDIGO PLATEAU\p"
	.string "TRAENERNES ultimative maal!\n"
	.string "POKeMON LEAGUE HQ$"

Text_Indigo_HighestAuthority::
	.string "INDIGO PLATEAU\p"
	.string "Den hoejeste POKeMON-myndighed!\n"
	.string "POKeMON LEAGUE HQ$"

Text_Food::
	.string "Den burde vaere fuld af alle slags\n"
	.string "laekre ting at spise.$"

Text_Blueprints::
	.string "Det er en slags tegning.\n"
	.string "Den er fuld af diagrammer og tekst.$"

Text_Painting::
	.string "Det er et smukt billede af en POKeMON.\n"
	.string "Den ser ud til at have det godt.$"

Text_PowerPlantMachine::
	.string "Hvad kan denne maskine vaere?\n"
	.string "Lad vaere med at rode med den!$"

Text_Telephone::
	.string "Det er en telefon.\n"
	.string "Brug den hellere ikke.$"

Text_Computer::
	.string "Det er alle mulige indviklede ord og\n"
	.string "tal der ikke giver mening…$"

Text_AdvertisingPoster::
	.string "Det er en reklameplakat om\n"
	.string "alle mulige produkter.$"

Text_TastyFood::
	.string "Aah, det lugter laekkert!\n"
	.string "Maven kunne godt begynde at knurre!$"

Text_TrashBin::
	.string "Indeni…\n"
	.string "……\p"
	.string "Der er ingenting her!$"

Text_Cup::
	.string "Det er en kop med et POKeMON-\n"
	.string "maerke paa.$"

Text_PolishedWindow::
	.string "Vinduet er meget velpoleret.$"

Text_BeautifulSkyWindow::
	.string "Uden for vinduet…\p"
	.string "Himlen ser fantastisk\n"
	.string "smoek ud.$"

Text_BlinkingLights::
	.string "Lys i forskellige farver\n"
	.string "blinker til og fra.$"

Text_NeatlyLinedUpTools::
	.string "Alle mulige vaerktoejer staar\n"
	.string "paent opstillet.$"

Text_ImpressiveMachine::
	.string "Det er en slags maskine.\n"
	.string "Den er da imponerende.$"

Text_VideoGame::
	.string "Det er det seneste videospil!\n"
	.string "Det ser sjovert ud!$"

Text_Burglary::
	.string "Der er tydelige tegn paa indbrud\n"
	.string "her…$"

Text_PlayerFacingTVScreen::
	.string "Der er en POKeMON i TV!\n"
	.string "Den ser ud til at more sig.$"
