Trade_Text_LookingForMonWannaTradeForMon::
	.string "Jeg leder efter POKeMON\n"
	.string "{STR_VAR_1}!\p"
	.string "Vil du bytte en mod min\n"
	.string "{STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "Av!\n"
	.string "Naa ja…$"

Trade_Text_WhatThatsNoMon::
	.string "Hvad?\n"
	.string "Det er da ikke en {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Hey, tak!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Er min gamle {STR_VAR_2} ikke fed?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Hej! Har du tilfaeldigvis\n"
	.string "en {STR_VAR_1}?\p"
	.string "Vil du bytte mod min\n"
	.string "{STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Naar du ikke vil…$"

Trade_Text_ThisIsntMon::
	.string "Hmmm?\n"
	.string "Det er ikke en {STR_VAR_1}.\p"
	.string "Taenk paa mig hvis du faar en.$"

Trade_Text_Thanks::
	.string "Tak!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "Er {STR_VAR_2}, som jeg byttede til dig,\n"
	.string "blevet staerkere?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Hej!\n"
	.string "Har du en {STR_VAR_1}?\p"
	.string "Vil du bytte den mod min\n"
	.string "{STR_VAR_2}?$"

Trade_Text_ThatsTooBad::
	.string "Det var aergerligt.$"

Trade_Text_ThisIsNoMon::
	.string "…Det er ikke en {STR_VAR_1}.\p"
	.string "Hvis du faar en, saa byt med mig.$"

Trade_Text_ThanksYoureAPal::
	.string "Tak, du er en ven!$"

Trade_Text_HowIsMyOldMon::
	.string "Hvordan har min gamle {STR_VAR_2} det?\n"
	.string "Min {STR_VAR_1} har det fint!$"
