gOtherText_NewName::
    .string "NYT NAVN$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "De forskellige knapper forklares i\n"
    .string "rækkefølge efter deres vigtighed.$"

gControlsGuide_Text_DPad::
    .string "Bevæger hovedpersonen.\n"
    .string "Bruges ogsâ til at vælge data\n"
    .string "og overskrifter.$"

gControlsGuide_Text_AButton::
    .string "Bruges til at bekræfte valg, tjekke\n"
    .string "ting, snakke og scrolle i teksten.$"

gControlsGuide_Text_BButton::
    .string "Bruges til at lukke, annullere et\n"
    .string "valg eller afbryde en tilstand.$"

gControlsGuide_Text_StartButton::
    .string "Tryk for at âbne\n"
    .string "MENUEN.$"

gControlsGuide_Text_SelectButton::
    .string "Bruges til at flytte genstande og\n"
    .string "bruge en registreret genstand.$"

gControlsGuide_Text_LRButtons::
    .string "Hvis du har brug for hjælp til\n"
    .string "spillet eller hvad du skal gøre,\n"
    .string "tryk pâ L- eller R-knappen.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Sig mig. Er du en dreng?\n"
    .string "Eller er du en pige?$"

gPikachuIntro_Text_Page1::
    .string "I den verden du snart træder ind i,\n"
    .string "venter et stort eventyr med dig\n"
    .string "som helten.\n"
    .string "\n"
    .string "Snak med folk og tjek ting overalt,\n"
    .string "i byer, pâ veje eller i huler.\n"
    .string "Saml oplysninger og spor fra\n"
    .string "alle kilder.$"

gPikachuIntro_Text_Page2::
    .string "Nye veje âbner sig ved at hjælpe\n"
    .string "folk i nød, overvinde udfordringer\n"
    .string "og løse mysterier.\n"
    .string "\n"
    .string "Til tider bliver du udfordret af\n"
    .string "andre og angrebet af vilde væsner.\n"
    .string "Vær modig og bliv ved.$"

gPikachuIntro_Text_Page3::
    .string "Gennem dit eventyr hâber vi at du\n"
    .string "møder alle slags mennesker og\n"
    .string "vokser personligt. Det er vigtigste mâl.\n"
    .string "\n"
    .string "Tryk pâ A-knappen og lad dit\n"
    .string "eventyr begynde!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Hej med dig!\n"
    .string "Dejligt at møde dig!\p"
    .string "Velkommen til POKéMONs verden!\p"
    .string "Jeg hedder OAK.\p"
    .string "Folk kalder mig kærligt\n"
    .string "for POKéMON-professoren.\p$"

gOakSpeech_Text_ThisWorld::
    .string "Denne verden…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…er befolket overalt af\n"
    .string "væsner kaldet POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "For nogle er POKéMON kæledyr.\n"
    .string "Andre bruger dem til kamp.\p"
    .string "Hvad mig angâr…\p"
    .string "Jeg studerer POKéMON til profession.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "Men fortæl mig først lidt om\n"
    .string "dig selv.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Lad os starte med dit navn.\n"
    .string "Hvad hedder du?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Ja…\n"
    .string "Sâ du hedder {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "Dette er min barnebarn.\p"
    .string "Han har været din rival siden I\n"
    .string "begge var smâ.\p"
    .string "…Hmm, hvad hed han nu?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Din rivals navn, hvad var det nu?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Var det {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "Præcis! Nu husker jeg det!\n"
    .string "Han hedder {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Din egen POKéMON-legende er\n"
    .string "ved at begynde!\p"
    .string "En verden af dromme og eventyr\n"
    .string "med POKéMON venter! Lad os gøre det!$"
