Text_ObtainedTheX::
	.string "Fik {STR_VAR_2}!$"

Text_BagIsFull::
	.string "Tasken er fuld…$"

Text_PutItemAway::
	.string "{PLAYER} lagde {STR_VAR_2}\n"
	.string "i {STR_VAR_3}.$"

Text_FoundOneItem::
	.string "{PLAYER} fandt en {STR_VAR_2}!$"

Text_TooBadBagFull::
	.string "Så sørgeligt!\n"
	.string "Tasken er fuld…$"

Text_FoundXCoins::
	.string "{PLAYER} fandt\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} lagde MØNTERNE i\n"
	.string "MØNTBOKSEN.$"

Text_CoinCaseIsFull::
	.string "Så sørgeligt!\n"
	.string "MØNTBOKSEN er fuld…$"

Text_NothingToPutThemIn::
	.string "Så sørgeligt!\n"
	.string "Der er intet at putte dem i…$"

Text_FoundXItems::
	.string "{PLAYER} fandt\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_ObtainedTheDecor::
	.string "Fik {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "Så sørgeligt! Der er ikke plads\n"
	.string "til endnu en {STR_VAR_2}…$"

Text_DecorTransferredToPC::
	.string "{STR_VAR_2} blev overført\n"
	.string "til PC'en.$"
