Text_MonSentToBoxInSomeonesPC::
    .string "{STR_VAR_2} blev overført til\n"
    .string "Nogens PC.\p"
    .string "Den blev placeret i\n"
    .string "BOX “{STR_VAR_1}.”$"

Text_MonSentToBoxInBillsPC::
    .string "{STR_VAR_2} blev overført til\n"
    .string "BILLs PC.\p"
    .string "Den blev placeret i\n"
    .string "BOX “{STR_VAR_1}.”$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "BOX “{STR_VAR_3}” pâ\n"
    .string "Nogens PC var fuld.\p"
    .string "{STR_VAR_2} blev overført til\n"
    .string "BOX “{STR_VAR_1}.”$"

Text_MonSentToBoxBillsBoxFull::
    .string "BOX “{STR_VAR_3}” pâ\n"
    .string "BILLs PC var fuld.\p"
    .string "{STR_VAR_2} blev overført til\n"
    .string "BOX “{STR_VAR_1}.”$"

Text_PlayerObtainedTheMon::
    .string "{PLAYER} modtog\n"
    .string "{STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "Der er ikke mere plads til POKéMON!\p"
    .string "POKéMON-boksene er fulde og\n"
    .string "kan ikke tage flere!$"
