PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Godt at se dig!\n"
	.string "Hvordan gâr det med din POKéDEX?\p"
	.string "Lad mig tage et kig.$"

PokedexRating_Text_SeenXOwnedY::
	.string "Din fremgang i POKéDEX er:\p"
	.string "{STR_VAR_1} POKéMON set og\n"
	.string "{STR_VAR_2} POKéMON ejet.\p"
	.string "{FONT_NORMAL}PROF. OAKs vurdering:$"

PokedexRating_Text_LessThan10::
	.string "Du har stadig meget at gore.\p"
	.string "Ga ind i hver græsplet du ser\n"
	.string "og led efter POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "Det ser ud til at du er pâ rette\n"
	.string "vej!\p"
	.string "Jeg har givet en af mine assistenter\n"
	.string "en FLASH-HM. Hænt den!$"

PokedexRating_Text_LessThan30::
	.string "Din POKéDEX kunne bruge lidt mere\n"
	.string "indhold!\p"
	.string "Forsøg at fange andre POKéMON-\n"
	.string "arter!$"

PokedexRating_Text_LessThan40::
	.string "Godt, det er tydeligt at du\n"
	.string "gør dig umage!\p"
	.string "Jeg har givet en af mine assistenter\n"
	.string "en GENSTANDSFINDER. Hænt den!$"

PokedexRating_Text_LessThan50::
	.string "Din POKéDEX kommer godt fra sted!\p"
	.string "Jeg har givet en af mine assistenter\n"
	.string "et AMULET-MØNT. Hænt det!$"

PokedexRating_Text_LessThan60::
	.string "Ah, du har endelig over 50 arter!\p"
	.string "Jeg har givet en af mine assistenter\n"
	.string "et EXP.-DELER. Hænt det!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! Det her bliver en rigtig\n"
	.string "respektabel POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Meget godt!\p"
	.string "Jeg tror du fanger endnu flere\n"
	.string "POKéMON ved at fiske!$"

PokedexRating_Text_LessThan90::
	.string "Vidunderligt! Lad mig gætte… Du\n"
	.string "kan godt lide at samle, ikke?$"

PokedexRating_Text_LessThan100::
	.string "Jeg er imponeret!\n"
	.string "Det mâ have været svært!$"

PokedexRating_Text_LessThan110::
	.string "Du har endelig nâet 100 arter!\n"
	.string "Utroligt hvor dygtig du er!$"

PokedexRating_Text_LessThan120::
	.string "Du har endda udviklede former\n"
	.string "af POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Fremragende! Bytt med venner for\n"
	.string "at fâ flere!$"

PokedexRating_Text_LessThan140::
	.string "Enestænde!\n"
	.string "Du er blevet en rigtig ekspert!$"

PokedexRating_Text_LessThan150::
	.string "Jeg har intet mere at sige!\n"
	.string "Du er POKéMON-professoren nu!$"

PokedexRating_Text_Complete::
	.string "Din POKéDEX er helt færdig!\n"
	.string "Tillykke!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "Og din NATIONAL POKéDEX er:\p"
	.string "{STR_VAR_1} POKéMON set og\n"
	.string "{STR_VAR_2} POKéMON ejet.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Jeg glæder mig til at se dig\n"
	.string "udfylde NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Endelig…\p"
	.string "Du har endelig færdiggjort\n"
	.string "POKéDEX!\p"
	.string "Det er storslâet!\n"
	.string "Virkelig en fantastisk bedrift!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooââârrrr!$"

PokedexRating_Text_HaHa::
	.string "Ha ha...$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Tak, {PLAYER}!\n"
	.string "Oprigtig tak!\l"
	.string "Du har virkeliggjort min drom!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, velkommen!\p"
	.string "Sig mig, hvordan gâr det med\n"
	.string "din POKéDEX?\p"
	.string "Wahaha!\p"
	.string "Faktisk ved jeg hvordan det er,\n"
	.string "men jeg elsker at se den alligevel!\p"
	.string "Lad os se…$"
