Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "POKé DUDE: Den hurtigste af de\n"
	.string "to kæmpere angriber først.$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "Det ser ud til at min RATTATA var\n"
	.string "hurtigere end PIDGEY.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "Kæmperne skifter til at angribe\n"
	.string "og reducere hinandens HP.$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "Min RATTATA bragte modstanderens HP\n"
	.string "ned på nul, så den vandt!\p"
	.string "POKéMON'en der deltog i kampen\n"
	.string "får EXP. point.\p"
	.string "Når en POKéMON har samlet nok\n"
	.string "EXP. point, stiger den i niveau.\p"
	.string "Niveaustigning gør din POKéMON\n"
	.string "stærkere end før.$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "POKé DUDE: Uha…\n"
	.string "Min RATTATA er blevet forgiftet…\p"
	.string "Hvis en POKéMON er forgiftet, mister\n"
	.string "den HP jævnligt.$"

Pokedude_Text_HealStatusRightAway::
	.string "Hvis en POKéMON får et status-\n"
	.string "problem, helbred det med det samme.$"

Pokedude_Text_UsingItemTakesTurn::
	.string "At bruge et objekt på en POKéMON\n"
	.string "bruger en tur, dog.\p"
	.string "Nu er det modstanderens tur!$"

Pokedude_Text_YayWeManagedToWin::
	.string "Juhuu!\n"
	.string "Vi formåede at vinde!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "POKé DUDE: Truslen BUBBLE er\n"
	.string "et VAND-type angreb.\p"
	.string "ODDISH er en\n"
	.string "GRÆS/GIFT-type POKéMON.\p"
	.string "VAND-type angrebet bliver optaget\n"
	.string "af GRÆS-type POKéMON…\p"
	.string "Resultatet er at truslen bliver ikke\n"
	.string "særlig effektiv og gør kun halvt\l"
	.string "skade.$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "Uha, det er ikke godt!\p"
	.string "ABSORB-angrebet du lige så\n"
	.string "er en GRÆS-type trusel.\p"
	.string "POLIWAG er en VAND-type POKéMON.\p"
	.string "Så ABSORB bliver super effektiv\n"
	.string "og fordobler skaden.$"

Pokedude_Text_LetsTryShiftingMons::
	.string "Det bliver ikke nemt at vinde\n"
	.string "med dette matchup…\p"
	.string "Lad os skifte POKéMON!$"

Pokedude_Text_ShiftingUsesTurn::
	.string "At skifte POKéMON ind og ud bruger\n"
	.string "en tur.\p"
	.string "Nu er det modstanderens tur.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "BUTTERFREE er en BUG/FLYING-type\n"
	.string "POKéMON.\p"
	.string "Mod denne POKéMON gør et GRÆS-\n"
	.string "type angreb…\p"
	.string "…kun halvt skade på BUG-type\n"
	.string "POKéMON…\p"
	.string "…Og det gør også kun halvt\n"
	.string "skade på FLYING-type POKéMON.\p"
	.string "Derfor tager BUTTERFREE, som er\n"
	.string "BUG/FLYING POKéMON, kun en fjerdedel\l"
	.string "af den sædvanlige skade.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "ODDISH er en GRÆS/GIFT-type\n"
	.string "POKéMON.\p"
	.string "Et FLYING- eller PSYCHIC-type\n"
	.string "angreb er super effektivt mod den.\p"
	.string "Et af disse angreb vil gøre\n"
	.string "dobbelt sædvanlig skade.\p"
	.string "Okay, så går vi!$"

Pokedude_Text_YeahWeWon::
	.string "Ja!\n"
	.string "Vi vandt!$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "POKé DUDE: Når du prøver at\n"
	.string "fange en POKéMON, kast ikke\l"
	.string "POKé BALLS med det samme.\p"
	.string "Først skal du svække den ved\n"
	.string "at reducere dens HP.$"

Pokedude_Text_BestIfTargetStatused::
	.string "Okay, det burde være nok.\p"
	.string "Men hvis det er muligt, er det\n"
	.string "bedst hvis målet har et status-\l"
	.string "problem.\p"
	.string "For eksempel ville det være\n"
	.string "nemmere at fange hvis den var\l"
	.string "søvende eller lam.$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "Det gør POKéMON'en meget\n"
	.string "nemmere at fange!\p"
	.string "Åh ja. Hvis du lammer en\n"
	.string "POKéMON kan du ikke få den til at\l"
	.string "sove oven på lamhed.\p"
	.string "Med andre ord kan du ikke lægge\n"
	.string "to statusproblemer oven på hinanden.$"

Pokedude_Text_LetMeThrowBall::
	.string "Okay!\n"
	.string "Lad mig kaste min POKé BALL!$"

Pokedude_Text_PickBestKindOfBall::
	.string "Før du kaster en POKé BALL,\n"
	.string "overvej tilstanden og typen af\l"
	.string "POKéMON og vælg den BALL der\l"
	.string "ville virke bedst.$"
