Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "POKe DUDE: Den hurtigste af de\n"
	.string "to kämpere angriber först.$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "Det ser ud til at min RATTATA var\n"
	.string "hurtigere end PIDGEY.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "Kämperne skifter til at angribe\n"
	.string "og reducere hinandens HP.$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "Min RATTATA bragte modstanderens HP\n"
	.string "ned pâ nul, sâ den vandt!\p"
	.string "POKéMON'en der deltog i kampen\n"
	.string "fâr EXP.-point.\p"
	.string "Nâr en POKéMON har samlet nok\n"
	.string "EXP.-point, stiger den i niveau.\p"
	.string "Niveaustigning gör din POKéMON\n"
	.string "stärkere end för.$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "POKe DUDE: Uha…\n"
	.string "Min RATTATA er blevet forgiftet…\p"
	.string "Hvis en POKéMON er forgiftet, mister\n"
	.string "den HP jävnligt.$"

Pokedude_Text_HealStatusRightAway::
	.string "Hvis en POKéMON fâr et status-\n"
	.string "problem, helbred det med det samme.$"

Pokedude_Text_UsingItemTakesTurn::
	.string "At bruge et objekt pâ en POKéMON\n"
	.string "bruger en tur, dog.\p"
	.string "Nu er det modstanderens tur!$"

Pokedude_Text_YayWeManagedToWin::
	.string "Juhuu!\n"
	.string "Vi formâede at vinde!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "POKe DUDE: Truslen BUBBLE er\n"
	.string "et VAND-type angreb.\p"
	.string "ODDISH er en\n"
	.string "GRÄS/GIFT-type POKéMON.\p"
	.string "VAND-type angrebet bliver optaget\n"
	.string "af GRÄS-type POKéMON…\p"
	.string "Resultatet er at truslen bliver ikke\n"
	.string "särlig effektiv og gör kun halvt\l"
	.string "skade.$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "Uha, det er ikke godt!\p"
	.string "ABSORB-angrebet du lige sâ\n"
	.string "er en GRÄS-type trusel.\p"
	.string "POLIWAG er en VAND-type POKéMON.\p"
	.string "Sâ ABSORB bliver super effektiv\n"
	.string "og fordobler skaden.$"

Pokedude_Text_LetsTryShiftingMons::
	.string "Det bliver ikke nemt at vinde\n"
	.string "med dette matchup…\p"
	.string "Lad os skifte POKéMON!$"

Pokedude_Text_ShiftingUsesTurn::
	.string "At skifte POKéMON ind og ud bruger\n"
	.string "en tur.\p"
	.string "Nu er det modstanderens tur.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "BUTTERFREE er en BUG/FLYING-type\n"
	.string "POKéMON.\p"
	.string "Mod denne POKéMON gör et GRÄS-\n"
	.string "type angreb…\p"
	.string "…kun halvt skade pâ BUG-type\n"
	.string "POKéMON…\p"
	.string "…Og det gör ogsâ kun halvt\n"
	.string "skade pâ FLYING-type POKéMON.\p"
	.string "Derfor tager BUTTERFREE, som er\n"
	.string "BUG/FLYING POKéMON, kun en fjerdedel\l"
	.string "af den sädvanlige skade.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "ODDISH er en GRÄS/GIFT-type\n"
	.string "POKéMON.\p"
	.string "Et FLYING- eller PSYCHIC-type\n"
	.string "angreb er super effektivt mod den.\p"
	.string "Et af disse angreb vil göre\n"
	.string "dobbelt sädvanlig skade.\p"
	.string "Okay, sâ gâr vi!$"

Pokedude_Text_YeahWeWon::
	.string "Ja!\n"
	.string "Vi vandt!$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "POKe DUDE: Nâr du pröver at\n"
	.string "fange en POKéMON, kast ikke\l"
	.string "POKe BALLS med det samme.\p"
	.string "Först skal du sväkke den ved\n"
	.string "at reducere dens HP.$"

Pokedude_Text_BestIfTargetStatused::
	.string "Okay, det burde väre nok.\p"
	.string "Men hvis det er muligt, er det\n"
	.string "bedst hvis mâlet har et status-\l"
	.string "problem.\p"
	.string "For eksempel ville det väre\n"
	.string "nemmere at fange hvis den var\l"
	.string "sövende eller lam.$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "Det gör POKéMON'en meget\n"
	.string "nemmere at fange!\p"
	.string "Oh ja. Hvis du lammer en\n"
	.string "POKéMON kan du ikke fâ den til at\l"
	.string "sove oven pâ lamhed.\p"
	.string "Med andre ord kan du ikke lägge\n"
	.string "to statusproblemer oven pâ hinanden.$"

Pokedude_Text_LetMeThrowBall::
	.string "Okay!\n"
	.string "Lad mig kaste min POKe BALL!$"

Pokedude_Text_PickBestKindOfBall::
	.string "För du kaster en POKe BALL,\n"
	.string "overvej tilstanden og typen af\l"
	.string "POKéMON og välg den BALL der\l"
	.string "ville virke bedst.$"
