Text_MayIHelpYou::
	.string "Hej!\n"
	.string "Kan jeg hjaelpe dig?$"

Text_FillOutQuestionnaire::
	.string "Der er en spoergeundersoegelse.\n"
	.string "Vil du udfylde den?$"

Text_QuestionnaireThankYou::
	.string "Tak fordi du tog dig tid til at\n"
	.string "udfylde vores spoergeundersøgelse.\p"
	.string "Din feedback bruges som\n"
	.string "reference fremover.$"

Text_YouKnowThoseWords::
	.string "Oh, hej!\n"
	.string "Kender du de ord?\p"
	.string "Det betyder at du maa kende\n"
	.string "MYSTERY GIFT.\p"
	.string "Fra nu af bør du modtage\n"
	.string "MYSTERY GIFTS!$"

Text_YouCanAccessMysteryGift::
	.string "Naar du har gemt spillet, kan du\n"
	.string "tilgaa MYSTERY GIFT.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Tak fordi du tilgaaede\n"
	.string "MYSTERY GIFT-systemet.$"
