PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Godt at se dig!\n"
	.string "Hvordan gaar det med din POKeDEX?\p"
	.string "Lad mig tage et kig.$"

PokedexRating_Text_SeenXOwnedY::
	.string "Din fremgang i POKeDEX er:\p"
	.string "{STR_VAR_1} POKeMON set og\n"
	.string "{STR_VAR_2} POKeMON ejet.\p"
	.string "{FONT_NORMAL}PROF. OAKs vurdering:$"

PokedexRating_Text_LessThan10::
	.string "Du har stadig meget at gore.\p"
	.string "Ga ind i hver graesplet du ser\n"
	.string "og led efter POKeMON!$"

PokedexRating_Text_LessThan20::
	.string "Det ser ud til at du er paa rette\n"
	.string "vej!\p"
	.string "Jeg har givet en af mine assistenter\n"
	.string "en FLASH-HM. Haent den!$"

PokedexRating_Text_LessThan30::
	.string "Din POKeDEX kunne bruge lidt mere\n"
	.string "indhold!\p"
	.string "Forsoeg at fange andre POKeMON-\n"
	.string "arter!$"

PokedexRating_Text_LessThan40::
	.string "Godt, det er tydeligt at du\n"
	.string "goer dig umage!\p"
	.string "Jeg har givet en af mine assistenter\n"
	.string "en GENSTANDSFINDER. Haent den!$"

PokedexRating_Text_LessThan50::
	.string "Din POKeDEX kommer godt fra sted!\p"
	.string "Jeg har givet en af mine assistenter\n"
	.string "et AMULET-MOENT. Haent det!$"

PokedexRating_Text_LessThan60::
	.string "Ah, du har endelig over 50 arter!\p"
	.string "Jeg har givet en af mine assistenter\n"
	.string "et EXP.-DELER. Haent det!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! Det her bliver en rigtig\n"
	.string "respektabel POKeDEX!$"

PokedexRating_Text_LessThan80::
	.string "Meget godt!\p"
	.string "Jeg tror du fanger endnu flere\n"
	.string "POKeMON ved at fiske!$"

PokedexRating_Text_LessThan90::
	.string "Vidunderligt! Lad mig gaette… Du\n"
	.string "kan godt lide at samle, ikke?$"

PokedexRating_Text_LessThan100::
	.string "Jeg er imponeret!\n"
	.string "Det maa have vaeret svaert!$"

PokedexRating_Text_LessThan110::
	.string "Du har endelig naaet 100 arter!\n"
	.string "Utroligt hvor dygtig du er!$"

PokedexRating_Text_LessThan120::
	.string "Du har endda udviklede former\n"
	.string "af POKeMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Fremragende! Bytt med venner for\n"
	.string "at faa flere!$"

PokedexRating_Text_LessThan140::
	.string "Enestaende!\n"
	.string "Du er blevet en rigtig ekspert!$"

PokedexRating_Text_LessThan150::
	.string "Jeg har intet mere at sige!\n"
	.string "Du er POKeMON-professoren nu!$"

PokedexRating_Text_Complete::
	.string "Din POKeDEX er helt faerdig!\n"
	.string "Tillykke!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "Og din NATIONAL POKeDEX er:\p"
	.string "{STR_VAR_1} POKeMON set og\n"
	.string "{STR_VAR_2} POKeMON ejet.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Jeg glaeder mig til at se dig\n"
	.string "udfylde NATIONAL POKeDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Endelig…\p"
	.string "Du har endelig faerdiggjort\n"
	.string "POKeDEX!\p"
	.string "Det er storslaaet!\n"
	.string "Virkelig en fantastisk bedrift!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_HaHa::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Tak, {PLAYER}!\n"
	.string "Oprigtig tak!\l"
	.string "Du har virkeliggjort min drom!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, velkommen!\p"
	.string "Sig mig, hvordan gaar det med\n"
	.string "din POKeDEX?\p"
	.string "Wahaha!\p"
	.string "Faktisk ved jeg hvordan det er,\n"
	.string "men jeg elsker at se den alligevel!\p"
	.string "Lad os se…$"
