Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "POKe DUDE: Den hurtigste af de\n"
	.string "to kaempere angriber foerst.$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "Det ser ud til at min RATTATA var\n"
	.string "hurtigere end PIDGEY.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "Kaemperne skifter til at angribe\n"
	.string "og reducere hinandens HP.$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "Min RATTATA bragte modstanderens HP\n"
	.string "ned paa nul, saa den vandt!\p"
	.string "POKeMON'en der deltog i kampen\n"
	.string "faar EXP.-point.\p"
	.string "Naar en POKeMON har samlet nok\n"
	.string "EXP.-point, stiger den i niveau.\p"
	.string "Niveaustigning goer din POKeMON\n"
	.string "staerkere end foer.$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "POKe DUDE: Uha…\n"
	.string "Min RATTATA er blevet forgiftet…\p"
	.string "Hvis en POKeMON er forgiftet, mister\n"
	.string "den HP jaevnligt.$"

Pokedude_Text_HealStatusRightAway::
	.string "Hvis en POKeMON faar et status-\n"
	.string "problem, helbred det med det samme.$"

Pokedude_Text_UsingItemTakesTurn::
	.string "At bruge et objekt paa en POKeMON\n"
	.string "bruger en tur, dog.\p"
	.string "Nu er det modstanderens tur!$"

Pokedude_Text_YayWeManagedToWin::
	.string "Juhuu!\n"
	.string "Vi formaaede at vinde!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "POKe DUDE: Truslen BUBBLE er\n"
	.string "et VAND-type angreb.\p"
	.string "ODDISH er en\n"
	.string "GRAES/GIFT-type POKeMON.\p"
	.string "VAND-type angrebet bliver optaget\n"
	.string "af GRAES-type POKeMON…\p"
	.string "Resultatet er at truslen bliver ikke\n"
	.string "saerlig effektiv og goer kun halvt\l"
	.string "skade.$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "Uha, det er ikke godt!\p"
	.string "ABSORB-angrebet du lige saa\n"
	.string "er en GRAES-type trusel.\p"
	.string "POLIWAG er en VAND-type POKeMON.\p"
	.string "Saa ABSORB bliver super effektiv\n"
	.string "og fordobler skaden.$"

Pokedude_Text_LetsTryShiftingMons::
	.string "Det bliver ikke nemt at vinde\n"
	.string "med dette matchup…\p"
	.string "Lad os skifte POKeMON!$"

Pokedude_Text_ShiftingUsesTurn::
	.string "At skifte POKeMON ind og ud bruger\n"
	.string "en tur.\p"
	.string "Nu er det modstanderens tur.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "BUTTERFREE er en BUG/FLYING-type\n"
	.string "POKeMON.\p"
	.string "Mod denne POKeMON goer et GRAES-\n"
	.string "type angreb…\p"
	.string "…kun halvt skade paa BUG-type\n"
	.string "POKeMON…\p"
	.string "…Og det goer ogsaa kun halvt\n"
	.string "skade paa FLYING-type POKeMON.\p"
	.string "Derfor tager BUTTERFREE, som er\n"
	.string "BUG/FLYING POKeMON, kun en fjerdedel\l"
	.string "af den saedvanlige skade.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "ODDISH er en GRAES/GIFT-type\n"
	.string "POKeMON.\p"
	.string "Et FLYING- eller PSYCHIC-type\n"
	.string "angreb er super effektivt mod den.\p"
	.string "Et af disse angreb vil goere\n"
	.string "dobbelt saedvanlig skade.\p"
	.string "Okay, saa gaar vi!$"

Pokedude_Text_YeahWeWon::
	.string "Ja!\n"
	.string "Vi vandt!$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "POKe DUDE: Naar du proever at\n"
	.string "fange en POKeMON, kast ikke\l"
	.string "POKe BALLS med det samme.\p"
	.string "Foerst skal du svaekke den ved\n"
	.string "at reducere dens HP.$"

Pokedude_Text_BestIfTargetStatused::
	.string "Okay, det burde vaere nok.\p"
	.string "Men hvis det er muligt, er det\n"
	.string "bedst hvis maalet har et status-\l"
	.string "problem.\p"
	.string "For eksempel ville det vaere\n"
	.string "nemmere at fange hvis den var\l"
	.string "soevende eller lam.$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "Det goer POKeMON'en meget\n"
	.string "nemmere at fange!\p"
	.string "Oh ja. Hvis du lammer en\n"
	.string "POKeMON kan du ikke faa den til at\l"
	.string "sove oven paa lamhed.\p"
	.string "Med andre ord kan du ikke laegge\n"
	.string "to statusproblemer oven paa hinanden.$"

Pokedude_Text_LetMeThrowBall::
	.string "Okay!\n"
	.string "Lad mig kaste min POKe BALL!$"

Pokedude_Text_PickBestKindOfBall::
	.string "Foer du kaster en POKe BALL,\n"
	.string "overvej tilstanden og typen af\l"
	.string "POKeMON og vaelg den BALL der\l"
	.string "ville virke bedst.$"
