Text_OnlySkilledTrainersAllowedThrough::
	.string "Kun virkelig dygtige TRÆNERE\n"
	.string "må komme forbi.\p"
	.string "Du har ikke {STR_VAR_1}\n"
	.string "endnu!$"

Text_CantLetYouPass::
	.string "Regler er regler.\n"
	.string "Jeg kan ikke lade dig komme forbi.$"

Text_OhThatsBadgeGoRightAhead::
	.string "Åh! Det er {STR_VAR_1}!\n"
	.string "Gå bare videre.$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "Du kan kun komme forbi her med\n"
	.string "{STR_VAR_1}.\p"
	.string "Du har ikke {STR_VAR_1}\n"
	.string "endnu.\p"
	.string "Du skal have den for at nå\n"
	.string "POKéMON LEAGUE.$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "Du kan kun komme forbi her med\n"
	.string "{STR_VAR_1}.\p"
	.string "Åh! Det er {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Okay da.\n"
	.string "Gå endelig videre.$"
