Text_OnlySkilledTrainersAllowedThrough::
	.string "Kun virkelig dygtige TRAINERs\n"
	.string "maa komme forbi.\p"
	.string "Du har ikke {STR_VAR_1}\n"
	.string "endnu!$"

Text_CantLetYouPass::
	.string "Regler er regler.\n"
	.string "Jeg kan ikke lade dig komme forbi.$"

Text_OhThatsBadgeGoRightAhead::
	.string "Oh! Det er {STR_VAR_1}!\n"
	.string "Ga bare videre.$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "Du kan kun komme forbi her med\n"
	.string "{STR_VAR_1}.\p"
	.string "Du har ikke {STR_VAR_1}\n"
	.string "endnu.\p"
	.string "Du skal have den for at naa\n"
	.string "POKeMON LEAGUE.$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "Du kan kun komme forbi her med\n"
	.string "{STR_VAR_1}.\p"
	.string "Oh! Det er {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Okay da.\n"
	.string "Ga endelig videre.$"
