@ The text here is a copy/paste from Hoenn's Safari Zone, and any unused text was left untranslated

SafariZone_Text_WouldYouLikeToExit::
	.string "Vil du forlade SAFARI-\n"
	.string "ZONEN nu?$"

SafariZone_Text_TimesUp::
	.string "PA: Ding-dong!\p"
	.string "Tiden er ude!\p"
	.string "PA: Dit SAFARI-SPIL er slut!$"

SafariZone_Text_OutOfBalls::
	.string "PA: Ding-dong!\p"
	.string "Du har ikke flere SAFARI-BOLLER!\p"
	.string "PA: Dit SAFARI-SPIL er slut!$"

SafariZone_Text_WelcomeToSafariZone::
	.string "Velkommen til SAFARI-ZONEN!\p"
	.string "Her kan du se POKéMON,\n"
	.string "som ellers er svære at finde,\p"
	.string "i deres naturlige omgivelser.\p"
	.string "Og hvis du vil,\n"
	.string "kan du også fange dem!\p"
	.string "God fornøjelse i SAFARI-ZONEN!$"

SafariZone_Text_WelcomeFirstTime::
	.string "Velkommen til SAFARI-ZONEN!\n"
	.string "Er det din første gang her?$"

SafariZone_Text_ComeInAndEnjoy::
	.string "God fornøjelse i SAFARI-ZONEN!$"

SafariZone_Text_FirstTimeInfo::
	.string "I SAFARI-ZONEN kan du bruge\n"
	.string "30 SAFARI-BALLS til at\l"
	.string "fange POKéMON.\p"
	.string "Spillet slutter, når du\n"
	.string "har brugt alle boldene\p"
	.string "eller gået 500 skridt.\p"
	.string "God fornøjelse i SAFARI-ZONEN!$"

SafariZone_Text_WouldYouLikeToPlay::
	.string "Velkommen til SAFARI-ZONEN!\p"
	.string "For ¥500 kan du fange POKéMON!\n"
	.string "Vil du deltage i SAFARI-SPILLET?$"

SafariZone_Text_PlayAnotherTime::
	.string "Okay.\n"
	.string "Kom gerne tilbage og prøv en anden gang!$"

SafariZone_Text_NotEnoughMoney::
	.string "Du har ikke penge nok!$"

SafariZone_Text_ThatWillBe500Please::
	.string "Så bliver det ¥500.$"

SafariZone_Text_HereAreYourSafariBalls::
	.string "Her er dine SAFARI-BALLS!$"

SafariZone_Text_Received30SafariBalls::
	.string "{PLAYER} modtog\n"
	.string "30 SAFARI-BALLS!$"

SafariZone_Text_PleaseEnjoyYourself::
	.string "Når tiden er gået,\n"
	.string "giver vi besked herfra.\p"
	.string "Nyd turen!\n"
	.string "God jagt!$"

SafariZone_Text_ExcuseMeYourPCBoxIsFull::
	.string "Undskyld!\n"
	.string "Din PC-BOKS er fuld.$"

SafariZone_Text_YouNeedPokeblockCase::
	.string "Hov, undskyld!\n"
	.string "Du har ikke en POKEBLOCK-CASE, vel?\p"
	.string "SAFARI-ZONEN bliver sjovere,\n"
	.string "hvis du kan bruge POKEBLOCKS.\p"
	.string "Kom gerne igen,\n"
	.string "når du har en CASE med dig!$"

SafariZone_South_Text_StillHaveTimeExit::
	.string "Du har stadig tid tilbage.\n"
	.string "Vil du stoppe SAFARI-SPILLET?$"

SafariZone_South_Text_EnjoyTheRestOfYourAdventure::
	.string "Så fortsæt og god fornøjelse!$"

SafariZone_South_Text_ExitEarlyThankYouForPlaying::
	.string "Forstået.\p"
	.string "Så tager vi de resterende\n"
	.string "SAFARI-BALLS tilbage.\p"
	.string "Tak for i dag,\n"
	.string "og kom igen.$"

SafariZone_South_Text_GoodLuck::
	.string "Så er du klar! God tur!\l"
	.string "Hvis der er noget,\n"
	.string "så sig bare til.$"

SafariZone_South_Text_Boy::
	.string "Vidste du det?\p"
	.string "Hvis du lægger POKEBLOCKS i den\n"
	.string "firkantede beholder, samles POKéMON!$"

SafariZone_South_Text_Man::
	.string "Jeg vil gerne længere ind,\n"
	.string "men jeg glemte min cykel…\p"
	.string "Det føles som om der er\n"
	.string "sjældne POKéMON derinde!$"

SafariZone_Southwest_Text_Woman::
	.string "Nogle gange ignorerer POKéMON helt,\n"
	.string "selv når jeg kaster en POKEBLOCK.\p"
	.string "Måske har de også præferencer?$"

SafariZone_Northwest_Text_Man::
	.string "Hah… Hah…\n"
	.string "Jeg kom helt herop, men…\p"
	.string "jeg er for træt til overhovedet\n"
	.string "at fange flere POKéMON…$"

SafariZone_North_Text_Fisherman::
	.string "Jeg kom for at finde VAND-POKéMON,\n"
	.string "som ikke findes andre steder…\p"
	.string "Ved du hvor søen\n"
	.string "ligger?$"

SafariZone_North_Text_Man::
	.string "Jeg fanger en masse sjældne POKéMON\n"
	.string "herinde,\l"
	.string "og bytter dem med venner!$"

SafariZone_South_Text_Youngster::
	.string "POKEBLOCKS'en jeg lagde i beholderen\n"
	.string "forsvandt pludselig…\p"
	.string "Mon en POKéMON\n"
	.string "spiste dem?$"

Route121_SafariZoneEntrance_Text_TrainerTip::
	.string "Nyttigt tip til SAFARI-ZONEN!\p"
	.string "Hvis du kaster en POKEBLOCK efter\n"
	.string "en POKéMON, løber den sjældnere væk!$"

SafariZone_Southwest_Text_RestHouseSign::
	.string "Træt af at gå? Tag en pause!\n"
	.string "“Alles hvilested”$"

SafariZone_RestHouse_Text_Youngster::
	.string "Jeg har ingen POKEBLOCKS,\n"
	.string "men jeg fangede alligevel mange POKéMON.\p"
	.string "Man kan komme langt ved bare at\n"
	.string "komme tæt på og kaste en BALL!$"

SafariZone_RestHouse_Text_PsychicM::
	.string "Når man bruger POKEBLOCKS,\n"
	.string "løber de lidt sjældnere væk.\p"
	.string "Så på POKéMON der i forvejen\n"
	.string "sjældent flygter, hjælper det nok ikke meget.$"

SafariZone_RestHouse_Text_FatMan::
	.string "Hvis man lægger POKEBLOCKS i beholderen\n"
	.string "og fanger POKéMON,\p"
	.string "så føles det som om POKéMON med\n"
	.string "lignende natur samler sig.$"
