gText_WouldYouLikeToSaveTheGame::
	.string "Vil du gemme spillet?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Der findes allerede en gemt fil.\n"
	.string "Er det okay at overskrive den?$"

gText_SavingDontTurnOffThePower::
	.string "GEMmer…\n"
	.string "SLUK IKKE FOR STRÖMMEN.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} gemte spillet.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "ADVARSEL!\p"
	.string "Der er en anden spilfil der allerede\n"
	.string "er gemt.\p"
	.string "Hvis du gemmer nu, vil den anden\n"
	.string "fils eventyr, inkl. genstande og\l"
	.string "POKeMON, ga tabt.\p"
	.string "Er du sikker pâ at du vil gemme nu\n"
	.string "og overskrive den anden gemte fil?$"
