@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "Hmm…\n"
	.string "Er det rigtigt…$"

PalletTown_Text_OhLookLook::
	.string "Aah!\n"
	.string "Se, se!$"

PalletTown_Text_ReadItReadIt::
	.string "Laes det, laes det!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "TRAENER TIPS\p"
	.string "Tryk paa START for at aabne MENUEN!$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Skilte er nyttige, er de ikke?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "Se, se!\p"
	.string "Jeg kopierede hvad der stod paa et af\n"
	.string "de TRAENER TIPS-skilte!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "TRAENER TIPS!\p"
	.string "Tryk paa START for at aabne MENUEN!$"
