@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "Hmm…\n"
	.string "Er det rigtigt…$"

PalletTown_Text_OhLookLook::
	.string "Aah!\n"
	.string "Se, se!$"

PalletTown_Text_ReadItReadIt::
	.string "Läs det, läs det!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "TRÄNER TIPS\p"
	.string "Tryk pâ START for at âbne MENUEN!$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Skilte er nyttige, er de ikke?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "Se, se!\p"
	.string "Jeg kopierede hvad der stod pâ et af\n"
	.string "de TRÄNER TIPS-skilte!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "TRÄNER TIPS!\p"
	.string "Tryk pâ START for at âbne MENUEN!$"
