VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "Batteriet er ikke opladet nok.\p"
	.string "Antal skridt krævet for fuld\n"
	.string "opladning af batteriet: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "Der er ingen TRÆNERE inden for rækkevidde\n"
	.string "som kan kæmpe…\p"
	.string "VS SEEKER blev slukket.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "De andre TRÆNERE ser ikke ud til\n"
	.string "at være klar til kamp.\p"
	.string "Lad os vente til senere.{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro::
	.string "Hey!\n"
	.string "Jeg så dig i VIRIDIAN FOREST!$"

Route3_Text_BenRematchIntro::
	.string "Hej! Jeg kan lide shorts!\n"
	.string "De er behagelige og nemme at have på!\p"
	.string "Du burde også gå i shorts!$"

Route3_Text_JaniceRematchIntro::
	.string "Undskyld!\n"
	.string "Du bliver ved med at kigge på mig, ikke?$"

Route3_Text_GregRematchIntro::
	.string "Du er en TRÆNER, ikke?\n"
	.string "Lad os komme i gang med det samme!$"

Route3_Text_SallyRematchIntro::
	.string "Det blik du giver mig…\n"
	.string "Det fascinerer mig så meget!$"

Route3_Text_CalvinRematchIntro::
	.string "Hey! Hvad er der galt med dig?\n"
	.string "Du har stadig ikke shorts på!$"

Route3_Text_JamesRematchIntro::
	.string "Jeg kæmper mod dig med den POKéMON\n"
	.string "jeg begyndte at opdrætte.$"

Route3_Text_RobinRematchIntro::
	.string "Eek!\n"
	.string "Skubbede du mig?$"

Route4_Text_CrissyRematchIntro::
	.string "Jeg fanger altid svampe-POKéMON\n"
	.string "på MT. MOON.$"

Route6_Text_RickyRematchIntro::
	.string "Åh! Du er den nysgerrige unge som\n"
	.string "lyttede med på os!$"

Route6_Text_NancyRematchIntro::
	.string "Undskyld! Sagde jeg ikke at\n"
	.string "det her er en privat samtale?\p"
	.string "Du burde ikke lytte med,\n"
	.string "din uforskammede person!$"

Route6_Text_KeigoRematchIntro::
	.string "Jeg prøver at finde noget godt\n"
	.string "som ikke er en BUG-POKéMON, men…$"

Route6_Text_JeffRematchIntro::
	.string "Huh?\n"
	.string "Vil du prøve med mig igen?$"

Route6_Text_IsabelleRematchIntro::
	.string "Mig?\n"
	.string "Tja, okay. Jeg prøver én gang.$"

Route6_Text_ElijahRematchIntro::
	.string "Hey, længe siden!\n"
	.string "Er du blevet bedre?$"

Route8_Text_AidanRematchIntro::
	.string "Du er god til POKéMON, men hvordan\n"
	.string "står det til med din kemikarakter?$"

Route8_Text_StanRematchIntro::
	.string "Fint!\n"
	.string "Lad os tage en omgang mere!$"

Route8_Text_GlennRematchIntro::
	.string "Du skal have strategi for at vinde\n"
	.string "kampe.\p"
	.string "Følger du mit råd?$"

Route8_Text_PaigeRematchIntro::
	.string "Jeg har samlet mange NIDORAN.\n"
	.string "Jeg vil ikke have dem til at udvikle sig, men…$"

Route8_Text_LeslieRematchIntro::
	.string "Skole er sjovt, men jeg synes stadig\n"
	.string "POKéMON også er sjove.$"

Route8_Text_AndreaRematchIntro::
	.string "MEOWTH og PERSIAN er så søde,\n"
	.string "meow, meow, meow!$"

Route8_Text_MeganRematchIntro::
	.string "Vi ser måske fjollede ud her,\n"
	.string "men jeg kan stadig kæmpe.$"

Route8_Text_RichRematchIntro::
	.string "Jeg er en omvandrende spillefyr!\n"
	.string "Jeg er i en sejrsstime!$"

Route8_Text_JuliaRematchIntro::
	.string "Hvad er en sød, rund og fluffy\n"
	.string "POKéMON?\p"
	.string "Det ved du allerede, ikke?$"

Route8_Text_RicardoRematchIntro::
	.string "Min cykel driller stadig, mand.$"

Route8_Text_JarenRematchIntro::
	.string "Okay, knægt!\n"
	.string "Forvent ingen nåde denne gang!$"

Route8_Text_EliRematchIntro::
	.string "ELI: Vores tvillingekraft er blevet\n"
	.string "endnu bedre!$"

Route8_Text_AnneRematchIntro::
	.string "ANNE: Vores tvillingekraft er steget!$"

Route9_Text_AliciaRematchIntro::
	.string "Skal vi kæmpe igen?\n"
	.string "Denne gang er du min!$"

Route9_Text_ChrisRematchIntro::
	.string "Jeg har ikke glemt at du var med\n"
	.string "de flotte POKéMON.$"

Route9_Text_DrewRematchIntro::
	.string "Jeg tager ROCK TUNNEL for at komme til\n"
	.string "LAVENDER…\p"
	.string "Men jeg bliver ved med at blive stoppet\n"
	.string "af alle undervejs…$"

Route9_Text_CaitlinRematchIntro::
	.string "Du skal ikke tale ned til mig i dag!\n"
	.string "Nu gælder det for alvor!$"

Route9_Text_JeremyRematchIntro::
	.string "Bwahaha!\n"
	.string "Fedt! Jeg kedede mig igen, hva'!$"

Route9_Text_BriceRematchIntro::
	.string "Hahaha!\n"
	.string "En lille hård en, som altid!$"

Route9_Text_BrentRematchIntro::
	.string "Jeg stod tidligt op hver dag for at\n"
	.string "træne mine POKéMON fra kokoner!$"

Route9_Text_AlanRematchIntro::
	.string "Hahahaha!\n"
	.string "Jeg vinder denne gang!$"

Route9_Text_ConnerRematchIntro::
	.string "Gå ud og vind, mine super BUG-POKéMON!$"

Route10_Text_MarkRematchIntro::
	.string "Wow, kom du her igen?\n"
	.string "Måske er du også en POKeMANIAC?\l"
	.string "Vil du se min samling?$"

Route10_Text_ClarkRematchIntro::
	.string "Ha-hahah-ah-ha!\n"
	.string "Jeg kan ikke stoppe med at nyse!$"

Route10_Text_HermanRematchIntro::
	.string "Hej, knægt!\n"
	.string "Viste jeg dig mine POKéMON?$"

Route10_Text_HeidiRematchIntro::
	.string "Jeg tog ud til en POKéMON GYM igen.\p"
	.string "…Men jeg tabte som sædvanligt.$"

Route10_Text_TrentRematchIntro::
	.string "Ah!\n"
	.string "Bjergluften er fantastisk!\l"
	.string "Den er så god, jeg kan ikke gå!$"

Route10_Text_CarolRematchIntro::
	.string "Mit hoved begynder at snurre.\n"
	.string "Jeg har vandret alt for længe…$"

Route11_Text_HugoRematchIntro::
	.string "Vind, tab eller uafgjort!\n"
	.string "Nu tager vi omkampen!$"

Route11_Text_JasperRematchIntro::
	.string "At konkurrere er det ultimative sus.\n"
	.string "Jeg kan stadig ikke få nok!$"

Route11_Text_EddieRematchIntro::
	.string "Du ved det godt, ikke?\n"
	.string "Lad os gå i gang, men snyd ikke!$"

Route11_Text_BraxtonRematchIntro::
	.string "Hej med dig!\p"
	.string "Men pas på!\n"
	.string "Jeg lægger stadig kabler!$"

Route11_Text_DillonRematchIntro::
	.string "Jeg blev TRÆNER for et stykke tid siden.\n"
	.string "Men jeg tror, jeg kan vinde.$"

Route11_Text_DirkRematchIntro::
	.string "Fwahaha!\n"
	.string "Jeg har aldrig tabt!\p"
	.string "…Og hvis jeg gjorde, har jeg glemt det\n"
	.string "helt!$"

Route11_Text_DarianRematchIntro::
	.string "Jeg har aldrig vundet før…\p"
	.string "Måske er jeg dømt til at forblive\n"
	.string "sådan…$"

Route11_Text_YasuRematchIntro::
	.string "Jeg er den bedste i min klasse.\n"
	.string "Jeg træner hver morgen og aften!$"

Route11_Text_BernieRematchIntro::
	.string "Hold øje med strømførende kabler!$"

Route11_Text_DaveRematchIntro::
	.string "Jeg har opdrættet mine POKéMON nøje.\n"
	.string "De burde være klar nu.\l"
	.string "Denne gang burde de også vinde.$"

Route12_Text_NedRematchIntro::
	.string "Ja!\n"
	.string "Der er bid her!\l"
	.string "D-det kan være den ægte vare!$"

Route12_Text_ChipRematchIntro::
	.string "Du er endelig her.\n"
	.string "Fiskeri er et ventespil.$"

Route12_Text_JustinRematchIntro::
	.string "Jeg kan stadig ikke finde en MOON STONE…\n"
	.string "Har du fundet en?$"

Route12_Text_LucaRematchIntro::
	.string "Elektricitet har altid været min\n"
	.string "specialitet.\p"
	.string "Jeg ved dog intet om POKéMON\n"
	.string "fra havet.$"

Route12_Text_HankRematchIntro::
	.string "FISKETOSSEN mod POKéMON-UNGE!\n"
	.string "Endnu en runde, kæmp!$"

Route12_Text_ElliotRematchIntro::
	.string "Jeg elsker at fiske, forstå mig ret.\n"
	.string "Men jeg ville ønske jeg havde mere arbejde…\l"
	.string "…Det er svært at opgive fiskeriet!$"

Route12_Text_AndrewRematchIntro::
	.string "Hvad fanger vi?\p"
	.string "Det finder du aldrig ud af medmindre\n"
	.string "du slår mig!$"

Route12_Text_JesRematchIntro::
	.string "JES: Jeg vinder her i dag og\n"
	.string "frier til min GIA.$"

Route12_Text_GiaRematchIntro::
	.string "GIA: Hej, JES…\n"
	.string "Jeg har ventet længe nu.\p"
	.string "Hvis vi vinder i dag, gifter jeg mig med dig!$"

Route13_Text_SebastianRematchIntro::
	.string "Mine fugle-POKéMON husker dig!$"

Route13_Text_SusieRematchIntro::
	.string "Jeg vil være den bedste TRÆNER\n"
	.string "mens jeg stadig er ung!$"

Route13_Text_ValerieRematchIntro::
	.string "Wow!\n"
	.string "Du har fået flere seje MÆRKER!$"

Route13_Text_GwenRematchIntro::
	.string "Mine sødt opdrættede POKéMON vil\n"
	.string "gerne blive genbekendt med dig.$"

Route13_Text_AlmaRematchIntro::
	.string "Jeg tømte min opsparing og\n"
	.string "købte mere CARBOS.$"

Route13_Text_PerryRematchIntro::
	.string "Jeg kommer ikke til at tabe denne gang.\n"
	.string "Vinden blæser min vej!$"

Route13_Text_LolaRematchIntro::
	.string "Åh, er du tilbage?\p"
	.string "Ja da, jeg leger gerne igen med dig,\n"
	.string "søde.$"

Route13_Text_SheilaRematchIntro::
	.string "Kan du ikke glemme at du kæmpede\n"
	.string "mod mig?$"

Route13_Text_JaredRematchIntro::
	.string "Hvad glor du på?$"

Route13_Text_RobertRematchIntro::
	.string "Jeg går altid med fugle-POKéMON.\n"
	.string "Jeg har viet mig til dem.$"

Route14_Text_CarterRematchIntro::
	.string "Jeg brugte TMs til at lære gode angreb\n"
	.string "til mine POKéMON.$"

Route14_Text_MitchRematchIntro::
	.string "Mine fugle-POKéMON burde være klar\n"
	.string "til kamp denne gang.$"

Route14_Text_BeckRematchIntro::
	.string "Bruger du TMs på POKéMON?\n"
	.string "Bare at holde på dem er nytteløst.$"

Route14_Text_MarlonRematchIntro::
	.string "Har du lært dine fugle-POKéMON\n"
	.string "at FLY?\p"
	.string "Så kan du svæve med dem op i\n"
	.string "himlen! Prøv det.$"

Route14_Text_DonaldRematchIntro::
	.string "Legenden om de vingede luftspejlinger…\n"
	.string "Den har du hørt, ikke?$"

Route14_Text_BennyRematchIntro::
	.string "Jeg er egentlig ikke til det, men okay.\n"
	.string "Lad os gå i gang!$"

Route14_Text_LukasRematchIntro::
	.string "Hey!\n"
	.string "Jeg husker dig!\p"
	.string "Kom nu, kom nu.\n"
	.string "Lad os gå, lad os gå, lad os gå!$"

Route14_Text_IsaacRematchIntro::
	.string "Du er her igen, hva'?\n"
	.string "Hold kæft og kæmp.$"

Route14_Text_GeraldRematchIntro::
	.string "Vi har kørt rundt her på grund af\n"
	.string "de store åbne områder.$"

Route14_Text_MalikRematchIntro::
	.string "POKéMON-kamp, ikke?\n"
	.string "Fedt! Rumble!$"

Route14_Text_KiriRematchIntro::
	.string "KIRI: JAN, jeg håber vi vinder i dag.$"

Route14_Text_JanRematchIntro::
	.string "JAN: KIRI, nu kører vi!\n"
	.string "Lad os vinde sikkert denne gang!$"

Route15_Text_KindraRematchIntro::
	.string "Jeg bliver ved med at kæmpe med de\n"
	.string "POKéMON jeg fik i bytter.$"

Route15_Text_BeckyRematchIntro::
	.string "Du ser blid ud, så jeg tror jeg kan\n"
	.string "slå dig.\p"
	.string "Jeg giver det én omgang mere!$"

Route15_Text_EdwinRematchIntro::
	.string "Når jeg fløjter, samler fugle-POKéMON\n"
	.string "sig omkring mig.\p"
	.string "De er utrolig søde!$"

Route15_Text_ChesterRematchIntro::
	.string "Hmm? Mine fugle ryster!\n"
	.string "Vent, er du ikke den TRÆNER…$"

Route15_Text_GraceRematchIntro::
	.string "Åh, du er en lille sød en!\n"
	.string "Ligesom en kær POKéMON!\l"
	.string "Nu husker jeg dig!$"

Route15_Text_OliviaRematchIntro::
	.string "Jeg opdrætter POKéMON til beskyttelse\n"
	.string "fordi jeg bor alene.\p"
	.string "Det har ikke ændret sig.$"

Route15_Text_ErnestRematchIntro::
	.string "Hey, knægt! Kom nu!\n"
	.string "Jeg tog dem fra en taber!$"

Route15_Text_AlexRematchIntro::
	.string "Aflever alle dine penge når du\n"
	.string "taber til mig, knægt!$"

Route15_Text_CeliaRematchIntro::
	.string "Hvad er sejt og happening?\n"
	.string "At bytte POKéMON, selvfølgelig.$"

Route15_Text_YazminRematchIntro::
	.string "Vil du lege med mine POKéMON\n"
	.string "igen?$"

Route15_Text_MyaRematchIntro::
	.string "MYA: Hej, vi mødes igen og igen,\n"
	.string "ikke?\p"
	.string "Vil du hjælpe mig med at træne min lillebror\n"
	.string "igen?$"

Route15_Text_RonRematchIntro::
	.string "RON: Min søster er blevet\n"
	.string "stærkere…$"

Route16_Text_LaoRematchIntro::
	.string "Hvad vil du?$"

Route16_Text_KojiRematchIntro::
	.string "Fed BIKE!\n"
	.string "Ræk den over med det samme!$"

Route16_Text_LukeRematchIntro::
	.string "Kom frem og leg, lille mus.\n"
	.string "Jeg skal nok behandle dig ordentligt!$"

Route16_Text_HideoRematchIntro::
	.string "Hey, vent lige!\n"
	.string "Lad være med at kalde på mig og så løbe væk!$"

Route16_Text_CamronRematchIntro::
	.string "Jeg føler mig sulten og ond!\n"
	.string "Jeg har virkelig brug for en boksepude!$"

Route16_Text_RubenRematchIntro::
	.string "Hej du!\n"
	.string "Vi skal nok få det sjovt!$"

Route16_Text_JedRematchIntro::
	.string "JED: Er du her for at se vores\n"
	.string "grænseløse kærlighed?$"

Route16_Text_LeaRematchIntro::
	.string "LEA: Nogle gange skræmmer styrken\n"
	.string "i vores kærlighed mig.$"

Route17_Text_RaulRematchIntro::
	.string "Jeg sagde det, man bliver ikke rig\n"
	.string "hurtigt på at kæmpe mod børn.$"

Route17_Text_IsaiahRematchIntro::
	.string "Jeg er mægtigt stolt af min krop, knægt.\n"
	.string "Kom an!$"

Route17_Text_VirgilRematchIntro::
	.string "Er du ude at gå en tur?$"

Route17_Text_BillyRematchIntro::
	.string "Vi er BIKERS!\n"
	.string "Vi styrer vejene, mand!$"

Route17_Text_NikolasRematchIntro::
	.string "VOLTORB kommer til at give dig\n"
	.string "et seriøst stød i dag!$"

Route17_Text_ZeekRematchIntro::
	.string "Jeg hævede min POKéMONs niveau, men den\n"
	.string "vil overhovedet ikke udvikle sig. Hvorfor?$"

Route17_Text_JamalRematchIntro::
	.string "Gåh! Jeg har virkelig brug for motion\n"
	.string "og for alvor at trimme noget fedt!$"

Route17_Text_CoreyRematchIntro::
	.string "Vær en rebel!$"

Route17_Text_JaxonRematchIntro::
	.string "Yep, det er en fed BIKE!\n"
	.string "Hvordan kører den?$"

Route17_Text_WilliamRematchIntro::
	.string "Smut, knægt!\n"
	.string "Jeg er helt færdig!$"

Route18_Text_WiltonRematchIntro::
	.string "Jeg har tjekket hvert græsområde\n"
	.string "for nye POKéMON.\p"
	.string "Men det er ikke altid nemt…$"

Route18_Text_RamiroRematchIntro::
	.string "Koorukukukoo!\n"
	.string "Bliver mit fuglekald bedre?$"

Route18_Text_JacobRematchIntro::
	.string "Jeg advarede dig før, det her er mit\n"
	.string "område!\p"
	.string "Jeg vil ikke have dig rendende her.$"

Route19_Text_RichardRematchIntro::
	.string "Jeg er næsten varmet op til\n"
	.string "at tage en svømmetur.$"

Route19_Text_ReeceRematchIntro::
	.string "Vent! Sæt farten ned!\n"
	.string "Hvad nu hvis du får et hjerteanfald?$"

Route19_Text_MatthewRematchIntro::
	.string "Jeg elsker at svømme!\n"
	.string "Du er vist surf-typen.$"

Route19_Text_DouglasRematchIntro::
	.string "Hvad er der bag horisonten?\n"
	.string "Har du set det?$"

Route19_Text_DavidRematchIntro::
	.string "Jeg prøvede at dykke efter POKéMON igen,\n"
	.string "men det gik ikke, ligesom før.$"

Route19_Text_TonyRematchIntro::
	.string "Jeg ser ud over havet for at glemme\n"
	.string "alle de dårlige ting der skete.\p"
	.string "…Som at tabe til dig sidst!$"

Route19_Text_AnyaRematchIntro::
	.string "Du får altid lov til at ride på din\n"
	.string "POKéMON…\p"
	.string "Det ser så afslappende ud.\n"
	.string "Må jeg få den, hvis jeg vinder?$"

Route19_Text_AliceRematchIntro::
	.string "Svømning er fantastisk!\n"
	.string "Solskoldninger er ikke!$"

Route19_Text_AxleRematchIntro::
	.string "Disse farvande er farlige!\n"
	.string "Du burde ikke komme tilbage hertil!$"

Route19_Text_ConnieRematchIntro::
	.string "Jeg svømmede herhen med mine venner…\n"
	.string "Jeg er træt…\l"
	.string "Skal vi virkelig kæmpe igen?$"

Route19_Text_LiaRematchIntro::
	.string "LIA: Du ved godt min bror lige er\n"
	.string "blevet TRÆNER, ikke?\p"
	.string "Jeg vil gøre ham bedre, så jeg\n"
	.string "har brug for din hjælp igen.$"

Route19_Text_LucRematchIntro::
	.string "LUC: Min storesøster lærte mig alt\n"
	.string "om POKéMON.\p"
	.string "Mon jeg er blevet bedre?$"

Route20_Text_BarryRematchIntro::
	.string "Vandet er lavt her.\n"
	.string "Der er mange mennesker der svømmer.$"

Route20_Text_ShirleyRematchIntro::
	.string "Er du misundelig over at jeg\n"
	.string "holder ferie på SEAFOAM?$"

Route20_Text_TiffanyRematchIntro::
	.string "Jeg elsker at flyde med fiskene\n"
	.string "her ude mellem bølgerne.$"

Route20_Text_IreneRematchIntro::
	.string "Var du også på ferie?$"

Route20_Text_DeanRematchIntro::
	.string "Se min fysik!\p"
	.string "Den er endnu mere muskuløs end\n"
	.string "nogensinde før!$"

Route20_Text_DarrinRematchIntro::
	.string "Hvorfor rider du på en POKéMON?\n"
	.string "Har du ikke lært at svømme endnu?$"

Route20_Text_RogerRematchIntro::
	.string "Jeg red hertil på min fugle-POKéMON.$"

Route20_Text_NoraRematchIntro::
	.string "Min kæreste gav mig store perler.\n"
	.string "Og de er blevet endnu større!$"

Route20_Text_MissyRematchIntro::
	.string "Jeg svømmede hertil fra CINNABAR ISLAND.\n"
	.string "Det var ikke nemt, som jeg sagde.$"

Route20_Text_MelissaRematchIntro::
	.string "CINNABAR i vest har et LAB\n"
	.string "for POKéMON.\p"
	.string "Min far arbejder der.$"

Route21_North_Text_RonaldRematchIntro::
	.string "Vil du vide om fiskene\n"
	.string "bider?$"

Route21_North_Text_WadeRematchIntro::
	.string "Jeg fik en stor fangst igen!\n"
	.string "Vil du tage en omgang mere?$"

Route21_North_Text_SpencerRematchIntro::
	.string "Havet renser min krop og sjæl!$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro::
	.string "Jeg fangede mine POKéMON til havs.\n"
	.string "Og det er der jeg træner dem.$"

Route21_South_Text_JeromeRematchIntro::
	.string "Lige nu er jeg med i endnu et\n"
	.string "triatlonstævne!$"

Route21_South_Text_RolandRematchIntro::
	.string "Ahh!\n"
	.string "Mærk solen og vinden!$"

Route21_South_Text_ClaudeRematchIntro::
	.string "Hey, stop så.\n"
	.string "Du skræmmer altid fiskene væk!$"

Route21_South_Text_NolanRematchIntro::
	.string "Hold mig med selskab til jeg får bid.$"

Route21_North_Text_LilRematchIntro::
	.string "LIL: Hva'? En kamp igen?\n"
	.string "IAN, kan du ikke klare det alene?$"

Route21_North_Text_IanRematchIntro::
	.string "IAN: Min søster er stadig doven.\n"
	.string "Hjælp mig med at få hende i form!$"

Route25_Text_JoeyRematchIntro::
	.string "Jeg taber ikke mens jeg er her!$"

Route25_Text_DanRematchIntro::
	.string "Far tog mig med til en fed fest på\n"
	.string "S.S. ANNE i VERMILION CITY.$"

Route25_Text_FlintRematchIntro::
	.string "Jeg er en sej fyr.\n"
	.string "Jeg har en kæreste!\p"
	.string "Denne gang skal jeg helt sikkert vise\n"
	.string "hvor sej jeg er!$"

Route25_Text_KelseyRematchIntro::
	.string "Hej!\n"
	.string "Min kæreste er sej!\l"
	.string "Min form er god i dag!$"

Route25_Text_ChadRematchIntro::
	.string "Jeg havde en fornemmelse…\n"
	.string "Jeg vidste jeg måtte kæmpe mod dig igen!$"

Route25_Text_HaleyRematchIntro::
	.string "Min ven har mange søde POKéMON.\n"
	.string "Jeg er så misundelig!$"

Route25_Text_FranklinRematchIntro::
	.string "Jeg trænede lige oppe på MT. MOON,\n"
	.string "men jeg har stadig energi i tanken!$"

Route25_Text_NobRematchIntro::
	.string "En POKeMANIAC bor på næsset.\n"
	.string "Har du set hans samling?$"

Route25_Text_WayneRematchIntro::
	.string "Skal du besøge BILL igen?\n"
	.string "Først kæmper vi!$"

Route24_Text_ShaneRematchIntro::
	.string "Jeg så din bedrift fra græsset!$"

Route24_Text_EthanRematchIntro::
	.string "Okay!\n"
	.string "Jeg knuser dig!$"

Route24_Text_ReliRematchIntro::
	.string "Du ser altid så travl ud…\n"
	.string "Bliver du ikke træt?$"

Route24_Text_TimmyRematchIntro::
	.string "Du må virkelig elske at komme til\n"
	.string "NUGGET BRIDGE.$"

Route24_Text_AliRematchIntro::
	.string "Dengang vi kæmpede…\p"
	.string "Selvom jeg var nummer to i\n"
	.string "rækken, var jeg den bedste, ikke?$"

Route24_Text_CaleRematchIntro::
	.string "Folk kalder dette NUGGET\n"
	.string "BRIDGE!\p"
	.string "Du har allerede slået os, så du\n"
	.string "må ikke tage udfordringen…\p"
	.string "…Men du er velkommen til at kæmpe\n"
	.string "mod os igen.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Liggende tilbage, vugget af bølgerne…\n"
	.string "Jeg mærker ikke tiden flyve afsted…$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "Vejret er fantastisk!\n"
	.string "Jeg skal prøve ikke at ødelægge det.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "Min solskoldning begynder at gøre ondt…$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "Ildfuglens bjerg kaster\n"
	.string "en kæmpe skygge…$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "Jeg har en stærk fornemmelse af at\n"
	.string "jeg kan vinde denne gang!$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "Vent! Vent lige!\n"
	.string "Jeg er sikker på jeg har kroget en stor en!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "Vil du hjælpe mig med min\n"
	.string "træning igen?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "Vi har endnu ikke misset en eneste\n"
	.string "træningsdag!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Hver morgen, før morgenmad,\n"
	.string "svømmer jeg rundt om denne ø…\l"
	.string "Tre gange!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "Klæd dig passende til kamp!\n"
	.string "Skift det pjattede outfit ud, siger jeg!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "Du ved, alt smager fantastisk\n"
	.string "når man er ude i naturen.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "Jeg spiste for meget igen, så vil du\n"
	.string "kæmpe mod os for lidt motion?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "KIA: Min storebror og jeg er\n"
	.string "en fantastisk kombination!\p"
	.string "Vi taber ikke denne gang!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "MIK: Sammen med KIA er vi\n"
	.string "ikke bange for noget!\p"
	.string "Det beviser vi for dig denne gang!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "Skal vi kæmpe igen?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "Hvor kommer du fra, og\n"
	.string "hvor er du på vej hen?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "Jeg vil snart svømme uden min\n"
	.string "badering.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "Hurra, hurra!\n"
	.string "POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "Åh nej, sagde jeg det ikke allerede?\n"
	.string "Hold dig venligst væk fra mig!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "JOY: Vi er blevet stærkere!\n"
	.string "Meget, meget stærkere!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "MEG: Du kan ikke slå os i dag!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Åh, hej!\p"
	.string "Opdrætter du dine POKéMON i et\n"
	.string "godt miljø?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "Med disse hænder vil jeg skabe\n"
	.string "min sejr i dag.$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "Skal jeg gentage mig selv?\n"
	.string "Jeg prøver at male.\l"
	.string "Hold dig venligst uden for mit synsfelt!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "Jeg har ikke gjort fremskridt…\n"
	.string "Jeg kan stadig ikke få den rigtige vinkel…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "Åh, vil du give mig endnu en\n"
	.string "mulighed for at måle mig med dig?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "De er næsten færdige med at lave\n"
	.string "poolen til mine POKéMON.\p"
	.string "Du må kigge forbi på besøg.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "Jeg er en god løber.\n"
	.string "Jeg er blevet endnu hurtigere!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "Hør her, ven!\n"
	.string "Lad os nyde tiden sammen!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "Jeg er den ældste af BIRD\n"
	.string "BROTHERS. Husker du mig?\p"
	.string "Det er rigtigt, jeg er ham der elsker\n"
	.string "fugle for deres næb!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "Jeg er mellembarnet i BIRD\n"
	.string "BROTHERS.\p"
	.string "Jeg er ham der elsker vinger.\n"
	.string "Lad os kæmpe igen!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "Jeg er den yngste af BIRD\n"
	.string "BROTHERS.\p"
	.string "Jeg elsker fugle for deres dun.\n"
	.string "Jeg troede ikke jeg ville se dig igen!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "Jeg har stadig slet ingen held.\n"
	.string "En kamp ville være et afbræk!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Hah… Hah…\p"
	.string "Jeg svømmede hertil fra SIX ISLANDs havn\n"
	.string "i ét stræk igen.$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "Du dukker altid op mens jeg\n"
	.string "svømmer.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "AVA: Lad os tage endnu en\n"
	.string "to-mod-to havkamp i dag!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "GEB: Min storesøster og jeg er\n"
	.string "meget hårdere end før!$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "…Hva'?\p"
	.string "Jeg forestiller mig mit hus, men TELEPORT\n"
	.string "bringer mig altid hertil!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "Åh, hej.\n"
	.string "En behagelig brise blæser igen.$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Hehehe, jeg træner i hemmelighed\n"
	.string "igen.$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "Hvad, er du træt af at se\n"
	.string "SWIMMERS som mig?\p"
	.string "Aww, lad være med at hade!\n"
	.string "Kæmp mod mig igen.$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Suk…\n"
	.string "Min kæreste har travlt igen…$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Kom nu, sig mig, hvor er bjergene\n"
	.string "her omkring?$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "MIU: Hej, POKéMON!\n"
	.string "Det er tid til at lege igen!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MIA: Hej, POKéMON!\n"
	.string "Det er tid til at kæmpe igen!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "Der ser ud til at være mange hemmeligheder\n"
	.string "i denne verden som stadig er uløste.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Hej, mødtes vi ikke før?\n"
	.string "Hvad fik dig til at komme tilbage?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "Det siges at der er\n"
	.string "mystiske sten på denne ø.\p"
	.string "Har du opdaget noget siden\n"
	.string "vi sidst mødtes?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "En omkamp med dig, helt heroppe!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "Jeg kender området her\n"
	.string "ret godt.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "Jeg mærkede at du nærmede dig.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "Et sted på denne ø sover særlige\n"
	.string "POKéMON.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "Kyahaha!\p"
	.string "At komme tilbage ændrer ingenting.\n"
	.string "Jeg fejer dig væk uden besvær!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "Hej du! Du er medlem af min\n"
	.string "fanklub, ikke sandt?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "Denne ø er alt for udstrakt…\n"
	.string "Det er surt at patruljere stedet…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "Jeg tilgiver ikke folk der misbruger\n"
	.string "POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "EVE: Jeg slår mig sammen med JON og\n"
	.string "vi kæmper sammen igen.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "JON: Når jeg er med EVE, føles det\n"
	.string "som om vi aldrig kan tabe, aldrig.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Lad os tage endnu en kamp.\n"
	.string "Min form er i top!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "Det betyder ikke noget om du tilfældigvis\n"
	.string "har de stærkeste POKéMON…\p"
	.string "Det betyder intet hvis du ikke\n"
	.string "ved hvordan du bruger dem ordentligt!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "Jeg arbejder for at beskytte miljøet.\n"
	.string "Til gengæld beskytter naturen mig!$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "Hver gang vi mødes, har du de\n"
	.string "smarte sko på.$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "Du må være blevet hårdere.\n"
	.string "Lad mig kæmpe mod dig, tak!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "Jeg har fået den bedst mulige\n"
	.string "uddannelse for at blive så stærk.\p"
	.string "Jeg taber ikke denne gang.\n"
	.string "Helt sikkert ikke!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "LEX: Min elskede NYA, sammen\n"
	.string "vinder vi helt sikkert!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "NYA: Jeg vil ikke holde min mentor\n"
	.string "LEX tilbage! Vi kommer til at vinde!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "Har du opdaget noget om\n"
	.string "dette stenkammer?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "Det siges at en mystisk POKéMON sover\n"
	.string "herinde.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "Min lærer viser mig hvordan man\n"
	.string "maler mere.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "I dag, ud over vores lektion,\n"
	.string "kom vi for at se kammeret igen.$"
