VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "Batteriet er ikke opladet nok.\p"
	.string "Antal skridt krævet for fuld\n"
	.string "opladning af batteriet: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "Der er ingen TRÆNERE inden for rækkevidde\n"
	.string "som kan kæmpe…\p"
	.string "VS SEEKER blev slukket.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "De andre TRÆNERE ser ikke ud til\n"
	.string "at være klar til kamp.\p"
	.string "Lad os vente til senere.{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro::
	.string "Hey!\n"
	.string "Jeg så dig i VIRIDIAN FOREST!$"

Route3_Text_BenRematchIntro::
	.string "Hej! Jeg kan lide shorts!\n"
	.string "De er behagelige og nemme at have på!\p"
	.string "Du burde også gå i shorts!$"

Route3_Text_JaniceRematchIntro::
	.string "Undskyld!\n"
	.string "Du bliver ved med at kigge på mig, ikke?$"

Route3_Text_GregRematchIntro::
	.string "Du er en TRÆNER, ikke?\n"
	.string "Lad os komme i gang med det samme!$"

Route3_Text_SallyRematchIntro::
	.string "Det blik du giver mig…\n"
	.string "Det fascinerer mig så meget!$"

Route3_Text_CalvinRematchIntro::
	.string "Hey! Hvad er der galt med dig?\n"
	.string "Du har stadig ikke shorts på!$"

Route3_Text_JamesRematchIntro::
	.string "Jeg kæmper mod dig med den POKéMON\n"
	.string "jeg begyndte at opdrætte.$"

Route3_Text_RobinRematchIntro::
	.string "Eek!\n"
	.string "Skubbede du mig?$"

Route4_Text_CrissyRematchIntro::
	.string "Jeg fanger altid svampe-POKéMON\n"
	.string "på MT. MOON.$"

Route6_Text_RickyRematchIntro::
	.string "Åh! Du er den nysgerrige unge som\n"
	.string "lyttede med på os!$"

Route6_Text_NancyRematchIntro::
	.string "Undskyld! Sagde jeg ikke at\n"
	.string "det her er en privat samtale?\p"
	.string "Du burde ikke lytte med,\n"
	.string "din uforskammede person!$"

Route6_Text_KeigoRematchIntro::
	.string "Jeg prøver at finde noget godt\n"
	.string "som ikke er en BUG-POKéMON, men…$"

Route6_Text_JeffRematchIntro::
	.string "Huh?\n"
	.string "Vil du prøve med mig igen?$"

Route6_Text_IsabelleRematchIntro::
	.string "Mig?\n"
	.string "Tja, okay. Jeg prøver én gang.$"

Route6_Text_ElijahRematchIntro::
	.string "Hey, længe siden!\n"
	.string "Er du blevet bedre?$"

Route8_Text_AidanRematchIntro::
	.string "Du er god til POKéMON, men hvordan\n"
	.string "står det til med din kemikarakter?$"

Route8_Text_StanRematchIntro::
	.string "Fint!\n"
	.string "Lad os tage en omgang mere!$"

Route8_Text_GlennRematchIntro::
	.string "Du skal have strategi for at vinde\n"
	.string "kampe.\p"
	.string "Følger du mit råd?$"

Route8_Text_PaigeRematchIntro::
	.string "Jeg har samlet mange NIDORAN.\n"
	.string "Jeg vil ikke have dem til at udvikle sig, men…$"

Route8_Text_LeslieRematchIntro::
	.string "Skole er sjovt, men jeg synes stadig\n"
	.string "POKéMON også er sjove.$"

Route8_Text_AndreaRematchIntro::
	.string "MEOWTH og PERSIAN er så søde,\n"
	.string "meow, meow, meow!$"

Route8_Text_MeganRematchIntro::
	.string "Vi ser måske fjollede ud her,\n"
	.string "men jeg kan stadig kæmpe.$"

Route8_Text_RichRematchIntro::
	.string "Jeg er en omvandrende spillefyr!\n"
	.string "Jeg er i en sejrsstime!$"

Route8_Text_JuliaRematchIntro::
	.string "Hvad er en sød, rund og fluffy\n"
	.string "POKéMON?\p"
	.string "Det ved du allerede, ikke?$"

Route8_Text_RicardoRematchIntro::
	.string "Min cykel driller stadig, mand.$"

Route8_Text_JarenRematchIntro::
	.string "Okay, knægt!\n"
	.string "Forvent ingen nåde denne gang!$"

Route8_Text_EliRematchIntro::
	.string "ELI: Vores tvillingekraft er blevet\n"
	.string "endnu bedre!$"

Route8_Text_AnneRematchIntro::
	.string "ANNE: Vores tvillingekraft er steget!$"

Route9_Text_AliciaRematchIntro::
	.string "Skal vi kæmpe igen?\n"
	.string "Denne gang er du min!$"

Route9_Text_ChrisRematchIntro::
	.string "Jeg har ikke glemt at du var med\n"
	.string "de flotte POKéMON.$"

Route9_Text_DrewRematchIntro::
	.string "Jeg tager ROCK TUNNEL for at komme til\n"
	.string "LAVENDER…\p"
	.string "Men jeg bliver ved med at blive stoppet\n"
	.string "af alle undervejs…$"

Route9_Text_CaitlinRematchIntro::
	.string "Du skal ikke tale ned til mig i dag!\n"
	.string "Nu gælder det for alvor!$"

Route9_Text_JeremyRematchIntro::
	.string "Bwahaha!\n"
	.string "Fedt! Jeg kedede mig igen, hva'!$"

Route9_Text_BriceRematchIntro::
	.string "Hahaha!\n"
	.string "En lille hård en, som altid!$"

Route9_Text_BrentRematchIntro::
	.string "Jeg stod tidligt op hver dag for at\n"
	.string "træne mine POKéMON fra kokoner!$"

Route9_Text_AlanRematchIntro::
	.string "Hahahaha!\n"
	.string "Jeg vinder denne gang!$"

Route9_Text_ConnerRematchIntro::
	.string "Gå ud og vind, mine super BUG-POKéMON!$"

Route10_Text_MarkRematchIntro::
	.string "Wow, kom du her igen?\n"
	.string "Måske er du også en POKeMANIAC?\l"
	.string "Vil du se min samling?$"

Route10_Text_ClarkRematchIntro::
	.string "Ha-hahah-ah-ha!\n"
	.string "Jeg kan ikke stoppe med at nyse!$"

Route10_Text_HermanRematchIntro::
	.string "Hej, knægt!\n"
	.string "Viste jeg dig mine POKéMON?$"

Route10_Text_HeidiRematchIntro::
	.string "Jeg tog ud til en POKéMON GYM igen.\p"
	.string "…Men jeg tabte som sædvanligt.$"

Route10_Text_TrentRematchIntro::
	.string "Ah!\n"
	.string "Bjergluften er fantastisk!\l"
	.string "Den er så god, jeg kan ikke gå!$"

Route10_Text_CarolRematchIntro::
	.string "Mit hoved begynder at snurre.\n"
	.string "Jeg har vandret alt for længe…$"

Route11_Text_HugoRematchIntro::
	.string "Vind, tab eller uafgjort!\n"
	.string "Nu tager vi omkampen!$"

Route11_Text_JasperRematchIntro::
	.string "At konkurrere er det ultimative sus.\n"
	.string "Jeg kan stadig ikke få nok!$"

Route11_Text_EddieRematchIntro::
	.string "Du ved det godt, ikke?\n"
	.string "Lad os gå i gang, men snyd ikke!$"

Route11_Text_BraxtonRematchIntro::
	.string "Hej med dig!\p"
	.string "Men pas på!\n"
	.string "Jeg lægger stadig kabler!$"

Route11_Text_DillonRematchIntro::
	.string "Jeg blev TRÆNER for et stykke tid siden.\n"
	.string "Men jeg tror, jeg kan vinde.$"

Route11_Text_DirkRematchIntro::
	.string "Fwahaha!\n"
	.string "Jeg har aldrig tabt!\p"
	.string "…Og hvis jeg gjorde, har jeg glemt det\n"
	.string "helt!$"

Route11_Text_DarianRematchIntro::
	.string "Jeg har aldrig vundet før…\p"
	.string "Måske er jeg dømt til at forblive\n"
	.string "sådan…$"

Route11_Text_YasuRematchIntro::
	.string "Jeg er den bedste i min klasse.\n"
	.string "Jeg træner hver morgen og aften!$"

Route11_Text_BernieRematchIntro::
	.string "Hold øje med strømførende kabler!$"

Route11_Text_DaveRematchIntro::
	.string "Jeg har opdrættet mine POKéMON nøje.\n"
	.string "De burde være klar nu.\l"
	.string "Denne gang burde de også vinde.$"

Route12_Text_NedRematchIntro::
	.string "Ja!\n"
	.string "Der er bid her!\l"
	.string "D-det kan være den ægte vare!$"

Route12_Text_ChipRematchIntro::
	.string "Du er endelig her.\n"
	.string "Fiskeri er et ventespil.$"

Route12_Text_JustinRematchIntro::
	.string "Jeg kan stadig ikke finde en MOON STONE…\n"
	.string "Har du fundet en?$"

Route12_Text_LucaRematchIntro::
	.string "Elektricitet har altid været min\n"
	.string "specialitet.\p"
	.string "Jeg ved dog intet om POKéMON\n"
	.string "fra havet.$"

Route12_Text_HankRematchIntro::
	.string "FISKETOSSEN mod POKéMON-UNGE!\n"
	.string "Endnu en runde, kæmp!$"

Route12_Text_ElliotRematchIntro::
	.string "Jeg elsker at fiske, forstå mig ret.\n"
	.string "Men jeg ville ønske jeg havde mere arbejde…\l"
	.string "…Det er svært at opgive fiskeriet!$"

Route12_Text_AndrewRematchIntro::
	.string "Hvad fanger vi?\p"
	.string "Det finder du aldrig ud af medmindre\n"
	.string "du slår mig!$"

Route12_Text_JesRematchIntro::
	.string "JES: Jeg vinder her i dag og\n"
	.string "frier til min GIA.$"

Route12_Text_GiaRematchIntro::
	.string "GIA: Hey, JES…\n"
	.string "Jeg har ventet længe nu.\p"
	.string "Hvis vi vinder i dag, gifter jeg mig med dig!$"

Route13_Text_SebastianRematchIntro::
	.string "Mine fugle-POKéMON husker dig!$"

Route13_Text_SusieRematchIntro::
	.string "Jeg vil være den bedste TRÆNER\n"
	.string "mens jeg stadig er ung!$"

Route13_Text_ValerieRematchIntro::
	.string "Wow!\n"
	.string "Du har fået flere seje MÆRKER!$"

Route13_Text_GwenRematchIntro::
	.string "Mine sødt opdrættede POKéMON vil\n"
	.string "gerne blive genbekendt med dig.$"

Route13_Text_AlmaRematchIntro::
	.string "Jeg tømte min opsparing og\n"
	.string "købte mere CARBOS.$"

Route13_Text_PerryRematchIntro::
	.string "Jeg kommer ikke til at tabe denne gang.\n"
	.string "Vinden blæser min vej!$"

Route13_Text_LolaRematchIntro::
	.string "Åh, er du tilbage?\p"
	.string "Ja da, jeg leger gerne igen med dig,\n"
	.string "søde.$"

Route13_Text_SheilaRematchIntro::
	.string "Kan du ikke glemme at du kæmpede\n"
	.string "mod mig?$"

Route13_Text_JaredRematchIntro::
	.string "Hvad glor du på?$"

Route13_Text_RobertRematchIntro::
	.string "Jeg går altid med fugle-POKéMON.\n"
	.string "Jeg har viet mig til dem.$"

Route14_Text_CarterRematchIntro::
	.string "Jeg brugte TMs til at lære gode angreb\n"
	.string "til mine POKéMON.$"

Route14_Text_MitchRematchIntro::
	.string "Mine fugle-POKéMON burde være klar\n"
	.string "til kamp denne gang.$"

Route14_Text_BeckRematchIntro::
	.string "Bruger du TMs på POKéMON?\n"
	.string "Bare at holde på dem er nytteløst.$"

Route14_Text_MarlonRematchIntro::
	.string "Har du lært dine fugle-POKéMON\n"
	.string "at FLY?\p"
	.string "Så kan du svæve med dem op i\n"
	.string "himlen! Prøv det.$"

Route14_Text_DonaldRematchIntro::
	.string "Legenden om de vingede luftspejlinger…\n"
	.string "Den har du hørt, ikke?$"

Route14_Text_BennyRematchIntro::
	.string "Jeg er egentlig ikke til det, men okay.\n"
	.string "Lad os gå i gang!$"

Route14_Text_LukasRematchIntro::
	.string "Hey!\n"
	.string "Jeg husker dig!\p"
	.string "Kom nu, kom nu.\n"
	.string "Lad os gå, lad os gå, lad os gå!$"

Route14_Text_IsaacRematchIntro::
	.string "Du er her igen, hva'?\n"
	.string "Hold kæft og kæmp.$"

Route14_Text_GeraldRematchIntro::
	.string "Vi har kørt rundt her på grund af\n"
	.string "de store åbne områder.$"

Route14_Text_MalikRematchIntro::
	.string "POKéMON-kamp, ikke?\n"
	.string "Fedt! Rumble!$"

Route14_Text_KiriRematchIntro::
	.string "KIRI: JAN, jeg håber vi vinder i dag.$"

Route14_Text_JanRematchIntro::
	.string "JAN: KIRI, nu kører vi!\n"
	.string "Lad os vinde sikkert denne gang!$"

Route15_Text_KindraRematchIntro::
	.string "Jeg bliver ved med at kæmpe med de\n"
	.string "POKéMON jeg fik i bytter.$"

Route15_Text_BeckyRematchIntro::
	.string "Du ser blid ud, så jeg tror jeg kan\n"
	.string "slå dig.\p"
	.string "Jeg giver det én omgang mere!$"

Route15_Text_EdwinRematchIntro::
	.string "Når jeg fløjter, samler fugle-POKéMON\n"
	.string "sig omkring mig.\p"
	.string "De er utrolig søde!$"

Route15_Text_ChesterRematchIntro::
	.string "Hmm? Mine fugle ryster!\n"
	.string "Vent, er du ikke den TRÆNER…$"

Route15_Text_GraceRematchIntro::
	.string "Åh, du er en lille sød en!\n"
	.string "Ligesom en kær POKéMON!\l"
	.string "Nu husker jeg dig!$"

Route15_Text_OliviaRematchIntro::
	.string "Jeg opdrætter POKéMON til beskyttelse\n"
	.string "fordi jeg bor alene.\p"
	.string "Det har ikke ændret sig.$"

Route15_Text_ErnestRematchIntro::
	.string "Hey, knægt! Kom nu!\n"
	.string "Jeg tog dem fra en taber!$"

Route15_Text_AlexRematchIntro::
	.string "Aflever alle dine penge når du\n"
	.string "taber til mig, knægt!$"

Route15_Text_CeliaRematchIntro::
	.string "Hvad er sejt og happening?\n"
	.string "At bytte POKéMON, selvfølgelig.$"

Route15_Text_YazminRematchIntro::
	.string "Vil du lege med mine POKéMON\n"
	.string "igen?$"

Route15_Text_MyaRematchIntro::
	.string "MYA: Hej, vi mødes igen og igen,\n"
	.string "ikke?\p"
	.string "Vil du hjælpe mig med at træne min lillebror\n"
	.string "igen?$"

Route15_Text_RonRematchIntro::
	.string "RON: Min søster er blevet\n"
	.string "stærkere…$"

Route16_Text_LaoRematchIntro::
	.string "Hvad vil du?$"

Route16_Text_KojiRematchIntro::
	.string "Nice BIKE!\n"
	.string "Ræk den over med det samme!$"

Route16_Text_LukeRematchIntro::
	.string "Kom frem og leg, lille mus.\n"
	.string "Jeg skal nok behandle dig ordentligt!$"

Route16_Text_HideoRematchIntro::
	.string "Hey, vent lige!\n"
	.string "Lad være med at kalde på mig og så løbe væk!$"

Route16_Text_CamronRematchIntro::
	.string "Jeg føler mig sulten og ond!\n"
	.string "Jeg har virkelig brug for en boksepude!$"

Route16_Text_RubenRematchIntro::
	.string "Hey, there!\n"
	.string "Vi skal nok få det sjovt!$"

Route16_Text_JedRematchIntro::
	.string "JED: Er du her for at se vores\n"
	.string "grænseløse kærlighed?$"

Route16_Text_LeaRematchIntro::
	.string "LEA: Nogle gange skræmmer styrken\n"
	.string "i vores kærlighed mig.$"

Route17_Text_RaulRematchIntro::
	.string "Jeg sagde det, man bliver ikke rig\n"
	.string "hurtigt på at kæmpe mod børn.$"

Route17_Text_IsaiahRematchIntro::
	.string "Jeg er mægtigt stolt af min krop, knægt.\n"
	.string "Kom an!$"

Route17_Text_VirgilRematchIntro::
	.string "Er du ude at gå en tur?$"

Route17_Text_BillyRematchIntro::
	.string "Vi er BIKERS!\n"
	.string "Vi styrer vejene, mand!$"

Route17_Text_NikolasRematchIntro::
	.string "VOLTORB kommer til at give dig\n"
	.string "et seriøst stød i dag!$"

Route17_Text_ZeekRematchIntro::
	.string "Jeg hævede min POKéMONs niveau, men den\n"
	.string "vil overhovedet ikke udvikle sig. Hvorfor?$"

Route17_Text_JamalRematchIntro::
	.string "Gåh! Jeg har virkelig brug for motion\n"
	.string "og for alvor at trimme noget fedt!$"

Route17_Text_CoreyRematchIntro::
	.string "Vær en rebel!$"

Route17_Text_JaxonRematchIntro::
	.string "Yep, det er en fed BIKE!\n"
	.string "Hvordan kører den?$"

Route17_Text_WilliamRematchIntro::
	.string "Smut, knægt!\n"
	.string "Jeg er helt færdig!$"

Route18_Text_WiltonRematchIntro::
	.string "Jeg har tjekket hvert græsområde\n"
	.string "for nye POKéMON.\p"
	.string "Men det er ikke altid nemt…$"

Route18_Text_RamiroRematchIntro::
	.string "Koorukukukoo!\n"
	.string "Bliver mit fuglekald bedre?$"

Route18_Text_JacobRematchIntro::
	.string "Jeg advarede dig før, det her er mit\n"
	.string "turf!\p"
	.string "Jeg vil ikke have dig rendende her.$"

Route19_Text_RichardRematchIntro::
	.string "Jeg er næsten varmet op til\n"
	.string "at tage en svømmetur.$"

Route19_Text_ReeceRematchIntro::
	.string "Vent! Sæt farten ned!\n"
	.string "Hvad nu hvis du får et hjerteanfald?$"

Route19_Text_MatthewRematchIntro::
	.string "Jeg elsker at svømme!\n"
	.string "Du er vist surf-typen.$"

Route19_Text_DouglasRematchIntro::
	.string "Hvad er der bag horisonten?\n"
	.string "Har du set det?$"

Route19_Text_DavidRematchIntro::
	.string "Jeg prøvede at dykke efter POKéMON igen,\n"
	.string "men det gik ikke, ligesom før.$"

Route19_Text_TonyRematchIntro::
	.string "Jeg ser ud over havet for at glemme\n"
	.string "alle de dårlige ting der skete.\p"
	.string "…Som at tabe til dig sidst!$"

Route19_Text_AnyaRematchIntro::
	.string "Du får altid lov til at ride på din\n"
	.string "POKéMON…\p"
	.string "Det ser så afslappende ud.\n"
	.string "Må jeg få den, hvis jeg vinder?$"

Route19_Text_AliceRematchIntro::
	.string "Svømning er fantastisk!\n"
	.string "Solskoldninger er ikke!$"

Route19_Text_AxleRematchIntro::
	.string "Disse farvande er farlige!\n"
	.string "Du burde ikke komme tilbage hertil!$"

Route19_Text_ConnieRematchIntro::
	.string "Jeg svømmede herhen med mine venner…\n"
	.string "Jeg er træt…\l"
	.string "Skal vi virkelig kæmpe igen?$"

Route19_Text_LiaRematchIntro::
	.string "LIA: Du ved godt min bror lige er\n"
	.string "blevet TRÆNER, ikke?\p"
	.string "Jeg vil gøre ham bedre, så jeg\n"
	.string "har brug for din hjælp igen.$"

Route19_Text_LucRematchIntro::
	.string "LUC: Min storesøster lærte mig alt\n"
	.string "om POKéMON.\p"
	.string "Mon jeg er blevet bedre?$"

Route20_Text_BarryRematchIntro::
	.string "The water is shallow here.\n"
	.string "There are many people swimming.$"

Route20_Text_ShirleyRematchIntro::
	.string "Are you jealous that I'm\n"
	.string "vacationing on SEAFOAM?$"

Route20_Text_TiffanyRematchIntro::
	.string "I love floating with the fishes\n"
	.string "here among the waves.$"

Route20_Text_IreneRematchIntro::
	.string "Were you on vacation, too?$"

Route20_Text_DeanRematchIntro::
	.string "Check out my physique!\p"
	.string "It's even more buff than ever\n"
	.string "before!$"

Route20_Text_DarrinRematchIntro::
	.string "Why are you riding a POKéMON?\n"
	.string "Haven't you learned to swim yet?$"

Route20_Text_RogerRematchIntro::
	.string "I rode my bird POKéMON here.$"

Route20_Text_NoraRematchIntro::
	.string "My boyfriend gave me big pearls.\n"
	.string "And, they've grown bigger!$"

Route20_Text_MissyRematchIntro::
	.string "I swam here from CINNABAR ISLAND.\n"
	.string "It wasn't easy, like I said.$"

Route20_Text_MelissaRematchIntro::
	.string "CINNABAR, in the west, has a LAB\n"
	.string "for POKéMON.\p"
	.string "My daddy works there.$"

Route21_North_Text_RonaldRematchIntro::
	.string "You want to know if the fish are\n"
	.string "biting?$"

Route21_North_Text_WadeRematchIntro::
	.string "I got a big haul again!\n"
	.string "Wanna go for it once more?$"

Route21_North_Text_SpencerRematchIntro::
	.string "The sea cleanses my body and soul!$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro::
	.string "I caught my POKéMON at sea.\n"
	.string "And that's where I train them.$"

Route21_South_Text_JeromeRematchIntro::
	.string "Right now, I'm in another triathlon\n"
	.string "meet!$"

Route21_South_Text_RolandRematchIntro::
	.string "Ahh!\n"
	.string "Feel the sun and the wind!$"

Route21_South_Text_ClaudeRematchIntro::
	.string "Hey, cut it out already.\n"
	.string "You always scare away the fish!$"

Route21_South_Text_NolanRematchIntro::
	.string "Keep me company till I get a hit.$"

Route21_North_Text_LilRematchIntro::
	.string "LIL: Huh? A battle again?\n"
	.string "IAN, can't you do it alone?$"

Route21_North_Text_IanRematchIntro::
	.string "IAN: My sis is still a slob.\n"
	.string "Help me get her into shape!$"

Route25_Text_JoeyRematchIntro::
	.string "I won't lose while I'm here!$"

Route25_Text_DanRematchIntro::
	.string "Dad took me to a great party on\n"
	.string "the S.S. ANNE at VERMILION CITY.$"

Route25_Text_FlintRematchIntro::
	.string "I'm a cool guy.\n"
	.string "I've got a girlfriend!\p"
	.string "I'll show her how cool I am for\n"
	.string "sure this time!$"

Route25_Text_KelseyRematchIntro::
	.string "Hi!\n"
	.string "My boyfriend is cool!\l"
	.string "My conditioning's good today!$"

Route25_Text_ChadRematchIntro::
	.string "I had this feeling…\n"
	.string "I knew I had to battle you again!$"

Route25_Text_HaleyRematchIntro::
	.string "My friend has many cute POKéMON.\n"
	.string "I'm so jealous!$"

Route25_Text_FranklinRematchIntro::
	.string "I just trained up on MT. MOON,\n"
	.string "but I've still got gas in the tank!$"

Route25_Text_NobRematchIntro::
	.string "A POKeMANIAC lives on the cape.\n"
	.string "Have you seen his collection?$"

Route25_Text_WayneRematchIntro::
	.string "You're going to see BILL again?\n"
	.string "First, we battle!$"

Route24_Text_ShaneRematchIntro::
	.string "I saw your feat from the grass!$"

Route24_Text_EthanRematchIntro::
	.string "Okay!\n"
	.string "I'll stomp you!$"

Route24_Text_ReliRematchIntro::
	.string "You always look so busy…\n"
	.string "Aren't you getting tired?$"

Route24_Text_TimmyRematchIntro::
	.string "You really must love coming to\n"
	.string "NUGGET BRIDGE.$"

Route24_Text_AliRematchIntro::
	.string "The time we battled…\p"
	.string "Even though I was the second in\n"
	.string "line, I was the best, wasn't I?$"

Route24_Text_CaleRematchIntro::
	.string "People call this the NUGGET\n"
	.string "BRIDGE!\p"
	.string "You've already beaten us, so you're\n"
	.string "not allowed to take the challenge…\p"
	.string "…But, you're welcome to battle with\n"
	.string "us again.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Lying back, rocked by the waves…\n"
	.string "I don't notice time slipping by…$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "The weather's gorgeous!\n"
	.string "I'll try not to spoil it.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "My sunburn is starting to hurt…$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "The fire bird's mountain casts\n"
	.string "a huge shadow…$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "I have this strong feeling that\n"
	.string "I can win this time!$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "Wait! Wait a second!\n"
	.string "I'm sure I've hooked a big one!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "You'll help me out with my\n"
	.string "training again?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "We haven't missed a single day of\n"
	.string "training yet!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Every morning, before breakfast,\n"
	.string "I swim around this island…\l"
	.string "Three times!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "Dress appropriately for battle!\n"
	.string "Lose that frivolous outfit, I said!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "You know, everything tastes great\n"
	.string "when you're out in the wild.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "I ate too much again, so will you\n"
	.string "battle us for some exercise?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "KIA: My big brother and I make\n"
	.string "an awesome combination!\p"
	.string "We won't lose this time!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "MIK: Together with KIA, we're\n"
	.string "afraid of nothing!\p"
	.string "We'll prove it to you this time!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "Are we to battle again?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "From where have you come, and\n"
	.string "where are you bound?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "I want to swim without my float\n"
	.string "ring soon.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "Yay, yay!\n"
	.string "POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "Oh, no, didn't I tell you already?\n"
	.string "Please, stay away from me!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "JOY: We've gotten stronger!\n"
	.string "Lots and lots!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "MEG: You can't beat us today!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Oh, hello!\p"
	.string "Are you raising your POKéMON in a\n"
	.string "good environment?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "With these hands, I will create\n"
	.string "my victory today.$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "Must I repeat myself?\n"
	.string "I'm trying to paint.\l"
	.string "Please keep out of my sight!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "I haven't made any progress…\n"
	.string "I still can't get the right angle…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "Oh, you will give me another\n"
	.string "opportunity to match wits with you?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "They're almost finished making the\n"
	.string "pool for my POKéMON.\p"
	.string "You must drop in for a visit.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "I'm a good runner.\n"
	.string "I've gotten even faster!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "I say, friend!\n"
	.string "Let us enjoy our time together!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "I'm the eldest of the BIRD\n"
	.string "BROTHERS. Remember me?\p"
	.string "That's right, I'm the one who loves\n"
	.string "birds for their beaks!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "I'm the middle kid of the BIRD\n"
	.string "BROTHERS.\p"
	.string "I'm the one that loves wings.\n"
	.string "Let's battle again!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "I'm the youngest of the BIRD\n"
	.string "BROTHERS.\p"
	.string "I love birds for their down.\n"
	.string "I didn't think I'd see you again!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "I'm still having no luck at all.\n"
	.string "A battle'd be a change of pace!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Gasp… Gasp…\p"
	.string "I swam here from SIX ISLAND's port\n"
	.string "in one go again.$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "You always come along while I'm\n"
	.string "swimming.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "AVA: Let's have another\n"
	.string "two-on-two marine battle today!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "GEB: My big sister and I are way\n"
	.string "tougher than before!$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "…Huh?\p"
	.string "I envision my house, but TELEPORT\n"
	.string "always brings me here!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "Oh, hello.\n"
	.string "A pleasant breeze is blowing again.$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Hehehe, I'm practicing in secret\n"
	.string "again.$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "What, you're sick of seeing\n"
	.string "SWIMMERS like me?\p"
	.string "Aww, don't be hatin'!\n"
	.string "Battle with me again.$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Sigh…\n"
	.string "My boyfriend's busy again…$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Come on, tell me, where are the\n"
	.string "mountains around these parts?$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "MIU: Hello, POKéMON!\n"
	.string "It's time to play again!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MIA: Hello, POKéMON!\n"
	.string "It's time to battle again!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "There appear to be many secrets\n"
	.string "still unsolved in this world.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Hi, didn't we meet before?\n"
	.string "What compelled you to come back?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "It's been said that there are\n"
	.string "mysterious stones on this island.\p"
	.string "Have you discovered anything since\n"
	.string "we last met?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "A rematch with you, so high up!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "I'm pretty familiar with the land\n"
	.string "around these parts.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "I sensed your approach.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "Somewhere on this island, peculiar\n"
	.string "POKéMON are sleeping.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "Kyahaha!\p"
	.string "Coming back won't change a thing.\n"
	.string "I'll flick you away effortlessly!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "Howdy! You're a member of my\n"
	.string "fan club, isn't that right?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "This island is too spread out…\n"
	.string "Patrolling the place is a drag…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "I don't forgive people who abuse\n"
	.string "POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "EVE: I'll team up with JON and\n"
	.string "battle together again.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "JON: When I'm with EVE, it feels\n"
	.string "like we could never lose, not ever.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Let's have another battle.\n"
	.string "My conditioning's in top form!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "It døsn't matter if you happen to\n"
	.string "have the strongest POKéMON…\p"
	.string "It døsn't mean a thing if you don't\n"
	.string "know how to use them properly!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "I work to protect the environment.\n"
	.string "In turn, nature protects me!$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "Every time we meet, you have those\n"
	.string "snazzy shøs on.$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "You must have gotten tougher.\n"
	.string "Let me battle you, please!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "I was given the best possible\n"
	.string "education to become this strong.\p"
	.string "I won't lose this time.\n"
	.string "Absolutely not!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "LEX: My darling NYA, together\n"
	.string "we will win for certain!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "NYA: I won't drag down my mentor\n"
	.string "LEX! We're going to win!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "Have you discovered anything about\n"
	.string "this stone chamber?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "A mystic POKéMON is said to sleep\n"
	.string "inside here.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "My teacher is showing me how to\n"
	.string "paint some more.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "Today, in addition to our lesson,\n"
	.string "we came to see the chamber again.$"
