CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "Det er en POKeMON PRINTER!\p"
	.string "Den kan putte et print af din POKeMON\n"
	.string "paa bagsiden af din TRAINER CARD.\p"
	.string "Det koster kun ¥50.\n"
	.string "Vil du proeve den?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "Du har ikke penge nok.$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "Vaelg venligst printtypen.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "Et stort smil til billedet!\n"
	.string "Tre… To… En…\p"
	.string "Blitz!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "Dit POKeMON-print er klar!\n"
	.string "Tjek din TRAINER CARD.$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "Fnise…\n"
	.string "Jeg har samlet en masse STICKERS.\l"
	.string "Jeg ville oenske jeg kunne vise dem frem…$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "Oh, glimrende!\n"
	.string "Du er kommet til det rette sted!\p"
	.string "Se, se! Se? Se?\n"
	.string "Det her er mine STICKERS!\l"
	.string "Se hvor mange jeg har!\p"
	.string "Jeg ved du vil have nogle.\n"
	.string "Det ved jeg!\p"
	.string "Jeg giver en STICKER hvis du kan fortaelle\n"
	.string "mig noget fantastisk om\l"
	.string "dig selv.\p"
	.string "Hvad vil du prale af?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "Prael af noget for mig.\n"
	.string "Saa giver jeg dig en STICKER.$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "Oh, hej!\n"
	.string "Her kommer praleren.\p"
	.string "Hvad vil du prale af\n"
	.string "i dag?$"

FourIsland_House2_Text_WowHoFLowest::
	.string "Oh, wow, du kom med i\n"
	.string "AEREGALLERIET.\p"
	.string "Det er ret godt, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowHoFLow::
	.string "Oh, wow, du har vaeret i\n"
	.string "AEREGALLERIET mange gange!\p"
	.string "Det er imponerende, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowHoFHigh::
	.string "Wow! Du har vaeret i\n"
	.string "AEREGALLERIET saa mange gange?\l"
	.string "Det er virkelig utroligt, ja!\p"
	.string "Du ejer POKeMON LEAGUE!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowHoFHighest::
	.string "Utroligt! Du har vaeret i\n"
	.string "AEREGALLERIET saa mange gange?\p"
	.string "Du er mere end utrolig, ja!\n"
	.string "Saa maa jeg give dig denne.$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "AEREGALLERIE-STICKEREN blev\n"
	.string "anbragt paa TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "Hmm…\p"
	.string "Kom tilbage med en bedre historie\n"
	.string "naeste gang, okay?$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "Oh, nej, det kan jeg ikke.\p"
	.string "Du er naesten en levende legende.\n"
	.string "Jeg har ingen STICKERS tilbage at give.$"

FourIsland_House2_Text_WowEggsLowest::
	.string "Oh, wow, der findes POKeMON AEG?\n"
	.string "Det vidste jeg ikke!\p"
	.string "Det er ret godt, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowEggsLow::
	.string "Du har klaekket saa mange AEG?\n"
	.string "Du maa virkelig kunne lide dem!\p"
	.string "Det er imponerende, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowEggsHigh::
	.string "Wow! Du har klaekket en hel\n"
	.string "masse AEG!\p"
	.string "Du er en AEG-klaekningsmaskine!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowEggsHighest::
	.string "Wh… Du har klaekket saa mange AEG?\p"
	.string "Hvad er bag din kaerlighed til AEG?\n"
	.string "Det er mere end utroligt, ja!\p"
	.string "Du er for sej, siger jeg.\n"
	.string "Saa maa jeg give dig denne.$"

FourIsland_House2_Text_EggStickerApplied::
	.string "AEG-STICKEREN blev anbragt\n"
	.string "paa TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "Hmm…\p"
	.string "Kom tilbage med en bedre historie\n"
	.string "naeste gang, okay?$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "Oh, nej, det kan jeg ikke.\p"
	.string "Du er naesten en levende legende.\n"
	.string "Jeg har ingen STICKERS tilbage at give.$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "Oh, wow, du har haft succes\n"
	.string "med link-kampe?\p"
	.string "Du er ret staerk, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "Du har slaaet dine venner mange\n"
	.string "gange i link-kampe, hva?\p"
	.string "Du er imponerende staerk, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "Wow! Du har slaaet dine venner\n"
	.string "et skraemmende antal gange.\p"
	.string "Har du mistet venner paa grund af det?\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "Wh… For vildt!\n"
	.string "Du har vundet utroligt mange gange!\p"
	.string "Jeg bliver helt paavirket af at taenke\n"
	.string "paa hvor haard du er.\p"
	.string "Du er mareriddets mand!\n"
	.string "Saa maa jeg give dig denne.$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "SEJR-STICKEREN blev anbragt\n"
	.string "paa TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "Hmm…\p"
	.string "Kom tilbage med en bedre historie\n"
	.string "naeste gang, okay?$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "Oh, nej, det kan jeg ikke.\p"
	.string "Du er naesten en levende legende.\n"
	.string "Jeg har ingen STICKERS tilbage at give.$"
