CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "Det er en POKéMON PRINTER!\p"
	.string "Den kan putte et print af din POKéMON\n"
	.string "pâ bagsiden af din TRAINER CARD.\p"
	.string "Det koster kun ¥50.\n"
	.string "Vil du prøve den?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "Du har ikke penge nok.$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "Vælg venligst printtypen.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "Et stort smil til billedet!\n"
	.string "Tre… To… En…\p"
	.string "Blitz!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "Dit POKéMON-print er klar!\n"
	.string "Tjek din TRAINER CARD.$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "Fnise…\n"
	.string "Jeg har samlet en masse STICKERS.\l"
	.string "Jeg ville ønske jeg kunne vise dem frem…$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "Oh, glimrende!\n"
	.string "Du er kommet til det rette sted!\p"
	.string "Se, se! Se? Se?\n"
	.string "Det her er mine STICKERS!\l"
	.string "Se hvor mange jeg har!\p"
	.string "Jeg ved du vil have nogle.\n"
	.string "Det ved jeg!\p"
	.string "Jeg giver en STICKER hvis du kan fortælle\n"
	.string "mig noget fantastisk om\l"
	.string "dig selv.\p"
	.string "Hvad vil du prale af?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "Præl af noget for mig.\n"
	.string "Sâ giver jeg dig en STICKER.$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "Oh, hej!\n"
	.string "Her kommer praleren.\p"
	.string "Hvad vil du prale af\n"
	.string "i dag?$"

FourIsland_House2_Text_WowHoFLowest::
	.string "Oh, wow, du kom med i\n"
	.string "ÆREGALLERIET.\p"
	.string "Det er ret godt, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowHoFLow::
	.string "Oh, wow, du har været i\n"
	.string "ÆREGALLERIET mange gange!\p"
	.string "Det er imponerende, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowHoFHigh::
	.string "Wow! Du har været i\n"
	.string "ÆREGALLERIET sâ mange gange?\l"
	.string "Det er virkelig utroligt, ja!\p"
	.string "Du ejer POKéMON LEAGUE!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowHoFHighest::
	.string "Utroligt! Du har været i\n"
	.string "ÆREGALLERIET sâ mange gange?\p"
	.string "Du er mere end utrolig, ja!\n"
	.string "Sâ mâ jeg give dig denne.$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "ÆREGALLERIE-STICKEREN blev\n"
	.string "anbragt pâ TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "Hmm…\p"
	.string "Kom tilbage med en bedre historie\n"
	.string "næste gang, okay?$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "Oh, nej, det kan jeg ikke.\p"
	.string "Du er næsten en levende legende.\n"
	.string "Jeg har ingen STICKERS tilbage at give.$"

FourIsland_House2_Text_WowEggsLowest::
	.string "Oh, wow, der findes POKéMON ÆG?\n"
	.string "Det vidste jeg ikke!\p"
	.string "Det er ret godt, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowEggsLow::
	.string "Du har klækket sâ mange ÆG?\n"
	.string "Du mâ virkelig kunne lide dem!\p"
	.string "Det er imponerende, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowEggsHigh::
	.string "Wow! Du har klækket en hel\n"
	.string "masse ÆG!\p"
	.string "Du er en ÆG-klækningsmaskine!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowEggsHighest::
	.string "Wh… Du har klækket sâ mange ÆG?\p"
	.string "Hvad er bag din kærlighed til ÆG?\n"
	.string "Det er mere end utroligt, ja!\p"
	.string "Du er for sej, siger jeg.\n"
	.string "Sâ mâ jeg give dig denne.$"

FourIsland_House2_Text_EggStickerApplied::
	.string "ÆG-STICKEREN blev anbragt\n"
	.string "pâ TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "Hmm…\p"
	.string "Kom tilbage med en bedre historie\n"
	.string "næste gang, okay?$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "Oh, nej, det kan jeg ikke.\p"
	.string "Du er næsten en levende legende.\n"
	.string "Jeg har ingen STICKERS tilbage at give.$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "Oh, wow, du har haft succes\n"
	.string "med link-kampe?\p"
	.string "Du er ret stærk, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "Du har slâet dine venner mange\n"
	.string "gange i link-kampe, hva?\p"
	.string "Du er imponerende stærk, ja!\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "Wow! Du har slâet dine venner\n"
	.string "et skræmmende antal gange.\p"
	.string "Har du mistet venner pâ grund af det?\n"
	.string "Jeg giver dig en af disse.$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "Wh… For vildt!\n"
	.string "Du har vundet utroligt mange gange!\p"
	.string "Jeg bliver helt pâvirket af at tænke\n"
	.string "pâ hvor hârd du er.\p"
	.string "Du er mareriddets mand!\n"
	.string "Sâ mâ jeg give dig denne.$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "SEJR-STICKEREN blev anbragt\n"
	.string "pâ TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "Hmm…\p"
	.string "Kom tilbage med en bedre historie\n"
	.string "næste gang, okay?$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "Oh, nej, det kan jeg ikke.\p"
	.string "Du er næsten en levende legende.\n"
	.string "Jeg har ingen STICKERS tilbage at give.$"
