Text_FirstShouldRestoreMonsHealth::
	.string "Foerst boer du genoprette dine\n"
	.string "POKeMON til fuld helbred.$"

Text_MonsHealedShouldBuyPotions::
	.string "Dine POKeMON er blevet helbredt\n"
	.string "til fuld helbred.\p"
	.string "Hvis dine POKeMONs energi, HP,\n"
	.string "er lav, kom og besoeg os.\p"
	.string "Hvis du planlaegger at rejse langt,\n"
	.string "boer du koebe HELBREDELSES-\l"
	.string "MIDLER i POKeMON-MARTEN.\p"
	.string "Vi haaber du klarer dig godt!$"

Text_MonsHealed::
	.string "Dine POKeMON er blevet helbredt\n"
	.string "til fuld helbred.\p"
	.string "Vi haaber du klarer dig godt!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "MOR: {PLAYER}!\n"
	.string "Velkommen hjem.\p"
	.string "Det lyder som om du har haft\n"
	.string "en oplevelse.\p"
	.string "Maaske boer du tage en kort\n"
	.string "hvile.$"

Text_MomExplainHPGetPotions::
	.string "MOR: Oh, godt! Du og dine\n"
	.string "POKeMON ser gode ud.\p"
	.string "Jeg har lige hoert fra PROF. OAK.\p"
	.string "Han sagde at POKeMONs energi\n"
	.string "maales i HP.\p"
	.string "Hvis dine POKeMON mister HP,\n"
	.string "kan du genoprette dem paa et\l"
	.string "POKeMON-CENTER.\p"
	.string "Hvis du rejser langt vaek, koeber\n"
	.string "den kloge TRAINER HELBREDELSES-\l"
	.string "MIDLER i POKeMON-MARTEN.\p"
	.string "Goer mig stolt, skat!\p"
	.string "Pas paa dig selv!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} har ingen brugbare\n"
	.string "POKeMON!\p"
	.string "{PLAYER} fik panik og mistede ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} besvimede!$"

Text_WhitedOut::
	.string "{PLAYER} har ingen brugbare\n"
	.string "POKeMON!\p"
	.string "{PLAYER} besvimede!$"
