Text_FirstShouldRestoreMonsHealth::
	.string "Först bör du genoprette dine\n"
	.string "POKéMON til fuld helbred.$"

Text_MonsHealedShouldBuyPotions::
	.string "Dine POKéMON er blevet helbredt\n"
	.string "til fuld helbred.\p"
	.string "Hvis dine POKéMONs energi, HP,\n"
	.string "er lav, kom og besög os.\p"
	.string "Hvis du planlägger at rejse langt,\n"
	.string "bör du köbe HELBREDELSES-\l"
	.string "MIDLER i POKéMON-MARTEN.\p"
	.string "Vi hâber du klarer dig godt!$"

Text_MonsHealed::
	.string "Dine POKéMON er blevet helbredt\n"
	.string "til fuld helbred.\p"
	.string "Vi hâber du klarer dig godt!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "MOR: {PLAYER}!\n"
	.string "Velkommen hjem.\p"
	.string "Det lyder som om du har haft\n"
	.string "en oplevelse.\p"
	.string "Mâske bör du tage en kort\n"
	.string "hvile.$"

Text_MomExplainHPGetPotions::
	.string "MOR: Oh, godt! Du og dine\n"
	.string "POKéMON ser gode ud.\p"
	.string "Jeg har lige hört fra PROF. OAK.\p"
	.string "Han sagde at POKéMONs energi\n"
	.string "mâles i HP.\p"
	.string "Hvis dine POKéMON mister HP,\n"
	.string "kan du genoprette dem pâ et\l"
	.string "POKéMON-CENTER.\p"
	.string "Hvis du rejser langt väk, köber\n"
	.string "den kloge TRAINER HELBREDELSES-\l"
	.string "MIDLER i POKéMON-MARTEN.\p"
	.string "Gör mig stolt, skat!\p"
	.string "Pas pâ dig selv!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} har ingen brugbare\n"
	.string "POKéMON!\p"
	.string "{PLAYER} fik panik og mistede ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} besvimede!$"

Text_WhitedOut::
	.string "{PLAYER} har ingen brugbare\n"
	.string "POKéMON!\p"
	.string "{PLAYER} besvimede!$"
