SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections::
    .string "Paa denne oe sker forskellige ting\n"
    .string "afhaengigt af forbindelser.\p"
    .string "Hvad er disse forbindelser?\p"
    .string "Det er for dig at opdage\n"
    .string "paa egen haand.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere::
    .string "Kom du med en SEAGALLOP-faerge\n"
    .string "for at komme her?\p"
    .string "Der er mindst ti af disse\n"
    .string "hoejhastighedsskibe.\p"
    .string "Jeg ved ikke hvor de alle\n"
    .string "sejler hen, dog.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower::
    .string "Hvis du er selvsikker, boer du\n"
    .string "tjekke TRAINER TOWER.$"

