SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections::
    .string "Pâ denne ø sker forskellige ting\n"
    .string "afhængigt af forbindelser.\p"
    .string "Hvad er disse forbindelser?\p"
    .string "Det er for dig at opdage\n"
    .string "pâ egen hând.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere::
    .string "Kom du med en SEAGALLOP-færge\n"
    .string "for at komme her?\p"
    .string "Der er mindst ti af disse\n"
    .string "højhastighedsskibe.\p"
    .string "Jeg ved ikke hvor de alle\n"
    .string "sejler hen, dog.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower::
    .string "Hvis du er selvsikker, bør du\n"
    .string "tjekke TRAINER TOWER.$"

