SevenIsland_SevaultCanyon_Text_CyndyIntro::
    .string "Min form er i topform!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
    .string "Hva?\n"
    .string "Noget er galt…$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
    .string "Som jeg er nu, mâ jeg mâske\n"
    .string "vente med TRAINER TOWER…$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
    .string "Det gör ikke noget hvis du tilfäldigvis\n"
    .string "har de stärkeste POKeMON…\p"
    .string "Det betyder intet hvis du ikke\n"
    .string "ved hvordan man bruger dem ordentligt!$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
    .string "Du er mester i dette.$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
    .string "Man ser dem ind imellem,\n"
    .string "TRAINERS med fantastiske POKeMON\l"
    .string "der ikke aner hvad de skal göre.\p"
    .string "För man träner POKeMON, skal\n"
    .string "TRAINERS selv vokse.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
    .string "Jeg arbejder for at beskytte miljöet.\n"
    .string "Til gengäld beskytter naturen mig!$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
    .string "Whoa! Du er hârd!\n"
    .string "Hvad med at beskytte mig?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
    .string "Langt ude blandt stjernerne er vores\n"
    .string "planet bare en vanddrâbe.\p"
    .string "Men vi vil beskytte den drâbe\n"
    .string "vand for alle.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
    .string "De sko du har er ret flotte.$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
    .string "Du er fed trods dit söde udseende.$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
    .string "Köbte din mor de flotte\n"
    .string "RUNNING SHÖS til dig?\p"
    .string "Hun mâ elske dig.$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
    .string "Du ser stärk ud.\n"
    .string "Lad mig kämpe mod dig!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
    .string "Jeg vidste det!\n"
    .string "Du er sâ hârd som jeg tröde!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
    .string "Mâden du kämper pâ har givet mig\n"
    .string "en masse brugbare data.\p"
    .string "Mange tak!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
    .string "Jeg fik den bedste mulige\n"
    .string "uddannelse for at blive sâ stärk.\p"
    .string "Jeg vil ikke tabe over for nogen!$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
    .string "Tak. Jeg föler mig befriet\n"
    .string "ved at tabe til dig.$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
    .string "Af en eller anden grund bliver jeg\n"
    .string "rasende over den mindste ting.\p"
    .string "Jeg beroliger mig ved at\n"
    .string "träkke vejret dybt.$"

SevenIsland_SevaultCanyon_Text_LexIntro::
    .string "LEX: Min käre NYA, sammen\n"
    .string "kunne vi vinde!$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
    .string "LEX: Jeg synes jeg var for\n"
    .string "sködeslös…$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
    .string "LEX: Jeg tror det var en god\n"
    .string "erfaring for NYA.\p"
    .string "Du har min taknemmelighed.$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
    .string "LEX: Ma jeg bede dig kämpe mod\n"
    .string "os begge pâ samme tid?$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
    .string "NYA: Jeg gör mit bedste sâ jeg ikke\n"
    .string "träkker min mentor LEX ned!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
    .string "NYA: Aah, nej…\n"
    .string "Jeg er sâ ked af det, jeg…$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
    .string "NYA: Jeg tror jeg har brug for\n"
    .string "meget mere erfaring og vejledning\l"
    .string "under LEX…\p"
    .string "…Sâ LEX, ma jeg blive hos\n"
    .string "dig sâdan her?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
    .string "NYA: Undskyld, men ma vi kämpe\n"
    .string "i to-mod-to stil?$"

SevenIsland_SevaultCanyon_Text_RouteSign::
    .string "SEVAULT CANYON\n"
    .string "TANOBY RUINS FORUDE$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
    .string "At träne alene er bestemt\n"
    .string "ikke en dârlig ting.\p"
    .string "Men det er heller ikke dârligt at\n"
    .string "sigte mod toppen med en partner.\p"
    .string "Selv BRUNO…\n"
    .string "Han tränede med en fyr ved navn\l"
    .string "BRAWLY för.$"
