SevenIsland_SevaultCanyon_Text_CyndyIntro::
    .string "Min form er i topform!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
    .string "Hva?\n"
    .string "Noget er galt…$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
    .string "Som jeg er nu, maa jeg maaske\n"
    .string "vente med TRAINER TOWER…$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
    .string "Det goer ikke noget hvis du tilfaeldigvis\n"
    .string "har de staerkeste POKeMON…\p"
    .string "Det betyder intet hvis du ikke\n"
    .string "ved hvordan man bruger dem ordentligt!$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
    .string "Du er mester i dette.$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
    .string "Man ser dem ind imellem,\n"
    .string "TRAINERS med fantastiske POKeMON\l"
    .string "der ikke aner hvad de skal goere.\p"
    .string "Foer man traener POKeMON, skal\n"
    .string "TRAINERS selv vokse.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
    .string "Jeg arbejder for at beskytte miljoeet.\n"
    .string "Til gengaeld beskytter naturen mig!$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
    .string "Whoa! Du er haard!\n"
    .string "Hvad med at beskytte mig?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
    .string "Langt ude blandt stjernerne er vores\n"
    .string "planet bare en vanddraabe.\p"
    .string "Men vi vil beskytte den draabe\n"
    .string "vand for alle.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
    .string "De sko du har er ret flotte.$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
    .string "Du er fed trods dit soede udseende.$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
    .string "Koebte din mor de flotte\n"
    .string "RUNNING SHOES til dig?\p"
    .string "Hun maa elske dig.$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
    .string "Du ser staerk ud.\n"
    .string "Lad mig kaempe mod dig!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
    .string "Jeg vidste det!\n"
    .string "Du er saa haard som jeg troede!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
    .string "Maaden du kaemper paa har givet mig\n"
    .string "en masse brugbare data.\p"
    .string "Mange tak!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
    .string "Jeg fik den bedste mulige\n"
    .string "uddannelse for at blive saa staerk.\p"
    .string "Jeg vil ikke tabe over for nogen!$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
    .string "Tak. Jeg foeler mig befriet\n"
    .string "ved at tabe til dig.$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
    .string "Af en eller anden grund bliver jeg\n"
    .string "rasende over den mindste ting.\p"
    .string "Jeg beroliger mig ved at\n"
    .string "traekke vejret dybt.$"

SevenIsland_SevaultCanyon_Text_LexIntro::
    .string "LEX: Min kaere NYA, sammen\n"
    .string "kunne vi vinde!$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
    .string "LEX: Jeg synes jeg var for\n"
    .string "skoedesloes…$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
    .string "LEX: Jeg tror det var en god\n"
    .string "erfaring for NYA.\p"
    .string "Du har min taknemmelighed.$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
    .string "LEX: Ma jeg bede dig kaempe mod\n"
    .string "os begge paa samme tid?$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
    .string "NYA: Jeg goer mit bedste saa jeg ikke\n"
    .string "traekker min mentor LEX ned!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
    .string "NYA: Aah, nej…\n"
    .string "Jeg er saa ked af det, jeg…$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
    .string "NYA: Jeg tror jeg har brug for\n"
    .string "meget mere erfaring og vejledning\l"
    .string "under LEX…\p"
    .string "…Saa LEX, ma jeg blive hos\n"
    .string "dig saadan her?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
    .string "NYA: Undskyld, men ma vi kaempe\n"
    .string "i to-mod-to stil?$"

SevenIsland_SevaultCanyon_Text_RouteSign::
    .string "SEVAULT CANYON\n"
    .string "TANOBY RUINS FORUDE$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
    .string "At traene alene er bestemt\n"
    .string "ikke en daarlig ting.\p"
    .string "Men det er heller ikke daarligt at\n"
    .string "sigte mod toppen med en partner.\p"
    .string "Selv BRUNO…\n"
    .string "Han traenede med en fyr ved navn\l"
    .string "BRAWLY foer.$"
