OneIsland_Text_BillLetsGoSeeCelio::
    .string "BILL: Her er vi!\n"
    .string "Dette er ONE ISLAND.\p"
    .string "Der er flere oeer omkring her,\n"
    .string "og dette er en af dem.\p"
    .string "Min ven CELIO sendte baaden for at\n"
    .string "hente mig her.\p"
    .string "Han staar alene for oens PC-\n"
    .string "netvaerk.\p"
    .string "…Hvorfor fortaeller jeg dig det nu?\n"
    .string "Lad os bare gaa til CELIO!$"

Text_WhereDoYouWantToSail::
    .string "Ahoj der!\n"
    .string "Hvor vil du sejle hen?$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "Her er vi paa en oe midt i\n"
    .string "ingenting.\p"
    .string "Vi er heldige at have en saadan\n"
    .string "bra ung mand som CELIO her.\p"
    .string "Min barnebarn var helt oppe at koere\n"
    .string "over CELIOs ven.\p"
    .string "Noget om en beroemt\n"
    .string "POKeMANIAC?\p"
    .string "Jeg ved ikke hvad det betyder, men\n"
    .string "CELIO er virkelig manden!$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "Min barnebarn var helt oppe at koere\n"
    .string "over et nyt gennembrud.\p"
    .string "Hun sagde at vi nu har PC-forbindelse\n"
    .string "med folk i KANTO.\p"
    .string "Jeg ved ikke hvad det betyder, men\n"
    .string "CELIO er virkelig manden!$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "Min barnebarn var helt oppe at koere\n"
    .string "over et nyt gennembrud.\p"
    .string "Hun sagde at vi endelig har PC-\n"
    .string "forbindelse med folk i HOENN.\p"
    .string "Jeg ved ikke hvad det betyder, men\n"
    .string "CELIO er virkelig manden.\p"
    .string "Han ville vaere en fin aegtefaelle\n"
    .string "for min barnebarn!$"

OneIsland_Text_IslandSign::
    .string "ONE ISLAND\n"
    .string "Venner moedes paa Knot Island$"

OneIsland_Text_PokemonNetCenterSign::
    .string "Udvider POKeMON-verdenen!\n"
    .string "POKeMON NET CENTER$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "Hej, er du ude og se landet?\n"
    .string "Er det varme klima her ikke herligt?$"

