OneIsland_Text_BillLetsGoSeeCelio::
    .string "BILL: Her er vi!\n"
    .string "Dette er ONE ISLAND.\p"
    .string "Der er flere øer omkring her,\n"
    .string "og dette er en af dem.\p"
    .string "Min ven CELIO sendte bâden for at\n"
    .string "hente mig her.\p"
    .string "Han stâr alene for øns PC-\n"
    .string "netværk.\p"
    .string "…Hvorfor fortæller jeg dig det nu?\n"
    .string "Lad os bare gâ til CELIO!$"

Text_WhereDoYouWantToSail::
    .string "Ahoj der!\n"
    .string "Hvor vil du sejle hen?$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "Her er vi pâ en ø midt i\n"
    .string "ingenting.\p"
    .string "Vi er heldige at have en sâdan\n"
    .string "bra ung mand som CELIO her.\p"
    .string "Min barnebarn var helt oppe at køre\n"
    .string "over CELIOs ven.\p"
    .string "Noget om en berømt\n"
    .string "POKeMANIAC?\p"
    .string "Jeg ved ikke hvad det betyder, men\n"
    .string "CELIO er virkelig manden!$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "Min barnebarn var helt oppe at køre\n"
    .string "over et nyt gennembrud.\p"
    .string "Hun sagde at vi nu har PC-forbindelse\n"
    .string "med folk i KANTO.\p"
    .string "Jeg ved ikke hvad det betyder, men\n"
    .string "CELIO er virkelig manden!$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "Min barnebarn var helt oppe at køre\n"
    .string "over et nyt gennembrud.\p"
    .string "Hun sagde at vi endelig har PC-\n"
    .string "forbindelse med folk i HØNN.\p"
    .string "Jeg ved ikke hvad det betyder, men\n"
    .string "CELIO er virkelig manden.\p"
    .string "Han ville være en fin ægtefælle\n"
    .string "for min barnebarn!$"

OneIsland_Text_IslandSign::
    .string "ONE ISLAND\n"
    .string "Venner mødes pâ Knot Island$"

OneIsland_Text_PokemonNetCenterSign::
    .string "Udvider POKéMON-verdenen!\n"
    .string "POKéMON NET CENTER$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "Hej, er du ude og se landet?\n"
    .string "Er det varme klima her ikke herligt?$"

