LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Tror du pâ spøgelser?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Virkelig?\n"
    .string "Sâ der er trønde…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, vel ikke.\p"
    .string "Den hvide hând pâ din skulder…\n"
    .string "Jeg forestiller mig bare det.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "Denne by er kendt som gravstedet\n"
    .string "for POKéMON.\p"
    .string "Mindehøjtideligheder afholdes i\n"
    .string "POKéMON TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Spøgelser dukkede op i POKéMON\n"
    .string "TOWER.\p"
    .string "Jeg tror de er ânderne af POKéMON\n"
    .string "som ROCKET dræbte.$"

LavenderTown_Text_TownSign::
    .string "LAVENDER TOWN\n"
    .string "Den noble lilla by$"

LavenderTown_Text_SilphScopeNotice::
    .string "Nyt SILPH SCOPE!\n"
    .string "Gør det usynlige synligt!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER FRIVILLIG\n"
    .string "POKéMON HUS$"

LavenderTown_Text_PokemonTowerSign::
    .string "POKéMON TOWER\n"
    .string "Berolig POKéMONs ânder$"

