LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Tror du pâ spögelser?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Virkelig?\n"
    .string "Sâ der er trönde…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, vel ikke.\p"
    .string "Den hvide hând pâ din skulder…\n"
    .string "Jeg forestiller mig bare det.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "Denne by er kendt som gravstedet\n"
    .string "for POKeMON.\p"
    .string "Mindehöjtideligheder afholdes i\n"
    .string "POKeMON TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Spögelser dukkede op i POKeMON\n"
    .string "TOWER.\p"
    .string "Jeg tror de er ânderne af POKeMON\n"
    .string "som ROCKET dräbte.$"

LavenderTown_Text_TownSign::
    .string "LAVENDER TOWN\n"
    .string "Den noble lilla by$"

LavenderTown_Text_SilphScopeNotice::
    .string "Nyt SILPH SCOPE!\n"
    .string "Gör det usynlige synligt!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER FRIVILLIG\n"
    .string "POKeMON HUS$"

LavenderTown_Text_PokemonTowerSign::
    .string "POKeMON TOWER\n"
    .string "Berolig POKeMONs ânder$"

