PokemonMansion_Text_PressSecretSwitchJP::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
    .string "Det her sted er, ligesom, kämpe!$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "Ayah!$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "Jeg spekulerer pâ hvor min partner blev af.$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "Min mentor böde engang her.$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "Puha!\n"
    .string "Overväldende!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "Sâ du er fast?\n"
    .string "Pröv at hoppe ned derovre!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "Dagbog: 6. feb\n"
    .string "MEW födte.\p"
    .string "Vi navngav den nyfödte MEWTWO.$"
