LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "TEAM ROCKET gör alt for\n"
    .string "pengenes skyld!\p"
    .string "Intet job er for beskidt, ingen\n"
    .string "gerning for grusom, intet forbrydelse\l"
    .string "for ond!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "Jeg sâ CUBONEs mor forsöge at\n"
    .string "flygte fra TEAM ROCKET.\p"
    .string "Hun blev dräbt under flugten…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "Du ved hvordan CUBONE-arten\n"
    .string "bärer kranier, ikke?\p"
    .string "Folk betaler meget for et.$"

