Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "Hej! Husker du mig?\n"
    .string "Jeg er en af PROF. OAKs ASSISTENTER.\p"
    .string "Hvis din POKeDEX har fulde data\n"
    .string "pâ ti arter, skal jeg give dig\l"
    .string "en belönning.\p"
    .string "PROF. OAK betröde mig\n"
    .string "HM05 til dig.\p"
    .string "Sâ, {PLAYER}, lad mig spörge.\p"
    .string "Har du samlet data pâ mindst\n"
    .string "ti slags POKeMON?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "Stort! Du har fanget eller ejet\n"
    .string "{STR_VAR_3} slags POKeMON!\p"
    .string "Tillykke!\n"
    .string "Värsgo!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER} modtog HM05\n"
    .string "fra ASSISTENTEN.$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "HM05 indeholder det skjulte träk\n"
    .string "FLASH.\p"
    .string "FLASH lyser selv de mörkeste\n"
    .string "huler og fangehuller op.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "Nâr en POKeMON lärer FLASH, kan\n"
    .string "du komme igennem ROCK TUNNEL.$"
