Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "Hej! Husker du mig?\n"
    .string "Jeg er en af PROF. OAKs ASSISTENTER.\p"
    .string "Hvis din POKéDEX har fulde data\n"
    .string "pâ ti arter, skal jeg give dig\l"
    .string "en belønning.\p"
    .string "PROF. OAK betrøde mig\n"
    .string "HM05 til dig.\p"
    .string "Sâ, {PLAYER}, lad mig spørge.\p"
    .string "Har du samlet data pâ mindst\n"
    .string "ti slags POKéMON?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "Stort! Du har fanget eller ejet\n"
    .string "{STR_VAR_3} slags POKéMON!\p"
    .string "Tillykke!\n"
    .string "Værsgo!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER} modtog HM05\n"
    .string "fra ASSISTENTEN.$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "HM05 indeholder det skjulte træk\n"
    .string "FLASH.\p"
    .string "FLASH lyser selv de mørkeste\n"
    .string "huler og fangehuller op.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "Nâr en POKéMON lærer FLASH, kan\n"
    .string "du komme igennem ROCK TUNNEL.$"
