Route17_Text_RaulIntro::
    .string "Man bliver ikke hurtig rig af\n"
    .string "at kæmpe med børn.$"

Route17_Text_RaulDefeat::
    .string "Brændt ud!$"

Route17_Text_RaulPostBattle::
    .string "Du kan finde gode ting der ligger\n"
    .string "og flyder pâ CYKELVEJ.\p"
    .string "Der er gode penge i at samle dem\n"
    .string "op og sælge dem.$"

Route17_Text_IsaiahIntro::
    .string "Jeg er stolt af min krop, unge.\n"
    .string "Kom an!$"

Route17_Text_IsaiahDefeat::
    .string "Whoo!$"

Route17_Text_IsaiahPostBattle::
    .string "Jeg kunne mave-bumpe dig væk\n"
    .string "herfra!$"

Route17_Text_VirgilIntro::
    .string "Er du pâ vej til FUCHSIA?$"

Route17_Text_VirgilDefeat::
    .string "Crash og brænd!$"

Route17_Text_VirgilPostBattle::
    .string "Jeg elsker at køre ned ad bakke!$"

Route17_Text_BillyIntro::
    .string "Vi er BIKERS!\n"
    .string "Vi hersker over vejene!$"

Route17_Text_BillyDefeat::
    .string "Røgt!$"

Route17_Text_BillyPostBattle::
    .string "Led du efter eventyr?$"

Route17_Text_NikolasIntro::
    .string "Lad VOLTORB give dig stød!$"

Route17_Text_NikolasDefeat::
    .string "Jordet!$"

Route17_Text_NikolasPostBattle::
    .string "Jeg fik min VOLTORB ved den\n"
    .string "forladte KRAFTVÆRK.$"

Route17_Text_ZeekIntro::
    .string "Jeg har level'et mine POKéMON op,\n"
    .string "men de udvikler sig ikke. Hvorfor?$"

Route17_Text_ZeekDefeat::
    .string "Hvor du!$"

Route17_Text_ZeekPostBattle::
    .string "Mâske har nogle POKéMON brug for\n"
    .string "element STONES for at udvikle sig.$"

Route17_Text_JamalIntro::
    .string "Jeg har brug for lidt motion!$"

Route17_Text_JamalDefeat::
    .string "Puha!\n"
    .string "God træning!$"

Route17_Text_JamalPostBattle::
    .string "Jeg er sikker pâ jeg tabte vægt!$"

Route17_Text_CoreyIntro::
    .string "Vær en rebel!$"

Route17_Text_CoreyDefeat::
    .string "Aâargh!$"

Route17_Text_CoreyPostBattle::
    .string "Vær parat til at kæmpe for det\n"
    .string "du tror pâ!$"

Route17_Text_JaxonIntro::
    .string "Fin CYKEL!\n"
    .string "Hvordan kører den?$"

Route17_Text_JaxonDefeat::
    .string "Skyd!$"

Route17_Text_JaxonPostBattle::
    .string "Skrâningen gør det svært at styre.$"

Route17_Text_WilliamIntro::
    .string "Forsvind, unge!\n"
    .string "Jeg er udmattet!$"

Route17_Text_WilliamDefeat::
    .string "Er du tilfreds?$"

Route17_Text_WilliamPostBattle::
    .string "Jeg skal sove lidt!$"

Route17_Text_WatchOutForDiscardedItems::
    .string "Det er en besked.\p"
    .string "Pas pâ kasserede genstande.$"

Route17_Text_SameSpeciesGrowDifferentRates::
    .string "TRAINER TIPS\p"
    .string "Alle POKéMON er unikke.\p"
    .string "Selv POKéMON af samme art og\n"
    .string "niveau vokser med forskellig hastighed.$"

Route17_Text_PressBToStayInPlace::
    .string "TRAINER TIPS\p"
    .string "Tryk B-knappen for at blive pâ\n"
    .string "stedet pâ en skrâning.$"

Route17_Text_RouteSign::
    .string "ROUTE 17\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route17_Text_DontThrowGameThrowBalls::
    .string "Det er en besked!\p"
    .string "Kast ikke spillet, kast POKe-\n"
    .string "BALLS i stedet!$"

Route17_Text_CyclingRoadSign::
    .string "CYKELVEJ\n"
    .string "Skrâning slutter her!$"
