Route17_Text_RaulIntro::
    .string "Man bliver ikke hurtig rig af\n"
    .string "at kaempe med boern.$"

Route17_Text_RaulDefeat::
    .string "Braendt ud!$"

Route17_Text_RaulPostBattle::
    .string "Du kan finde gode ting der ligger\n"
    .string "og flyder paa CYKELVEJ.\p"
    .string "Der er gode penge i at samle dem\n"
    .string "op og saelge dem.$"

Route17_Text_IsaiahIntro::
    .string "Jeg er stolt af min krop, unge.\n"
    .string "Kom an!$"

Route17_Text_IsaiahDefeat::
    .string "Whoo!$"

Route17_Text_IsaiahPostBattle::
    .string "Jeg kunne mave-bumpe dig vaek\n"
    .string "herfra!$"

Route17_Text_VirgilIntro::
    .string "Er du paa vej til FUCHSIA?$"

Route17_Text_VirgilDefeat::
    .string "Crash og braend!$"

Route17_Text_VirgilPostBattle::
    .string "Jeg elsker at koere ned ad bakke!$"

Route17_Text_BillyIntro::
    .string "Vi er BIKERS!\n"
    .string "Vi hersker over vejene!$"

Route17_Text_BillyDefeat::
    .string "Roegt!$"

Route17_Text_BillyPostBattle::
    .string "Led du efter eventyr?$"

Route17_Text_NikolasIntro::
    .string "Lad VOLTORB give dig stoed!$"

Route17_Text_NikolasDefeat::
    .string "Jordet!$"

Route17_Text_NikolasPostBattle::
    .string "Jeg fik min VOLTORB ved den\n"
    .string "forladte KRAFTVAERK.$"

Route17_Text_ZeekIntro::
    .string "Jeg har level'et mine POKeMON op,\n"
    .string "men de udvikler sig ikke. Hvorfor?$"

Route17_Text_ZeekDefeat::
    .string "Hvor du!$"

Route17_Text_ZeekPostBattle::
    .string "Maaske har nogle POKeMON brug for\n"
    .string "element STONES for at udvikle sig.$"

Route17_Text_JamalIntro::
    .string "Jeg har brug for lidt motion!$"

Route17_Text_JamalDefeat::
    .string "Puha!\n"
    .string "God traening!$"

Route17_Text_JamalPostBattle::
    .string "Jeg er sikker paa jeg tabte vaegt!$"

Route17_Text_CoreyIntro::
    .string "Vaer en rebel!$"

Route17_Text_CoreyDefeat::
    .string "Aaaargh!$"

Route17_Text_CoreyPostBattle::
    .string "Vaer parat til at kaempe for det\n"
    .string "du tror paa!$"

Route17_Text_JaxonIntro::
    .string "Fin CYKEL!\n"
    .string "Hvordan koerer den?$"

Route17_Text_JaxonDefeat::
    .string "Skyd!$"

Route17_Text_JaxonPostBattle::
    .string "Skraaningen goer det svaert at styre.$"

Route17_Text_WilliamIntro::
    .string "Forsvind, unge!\n"
    .string "Jeg er udmattet!$"

Route17_Text_WilliamDefeat::
    .string "Er du tilfreds?$"

Route17_Text_WilliamPostBattle::
    .string "Jeg skal sove lidt!$"

Route17_Text_WatchOutForDiscardedItems::
    .string "Det er en besked.\p"
    .string "Pas paa kasserede genstande.$"

Route17_Text_SameSpeciesGrowDifferentRates::
    .string "TRAINER TIPS\p"
    .string "Alle POKeMON er unikke.\p"
    .string "Selv POKeMON af samme art og\n"
    .string "niveau vokser med forskellig hastighed.$"

Route17_Text_PressBToStayInPlace::
    .string "TRAINER TIPS\p"
    .string "Tryk B-knappen for at blive paa\n"
    .string "stedet paa en skraaning.$"

Route17_Text_RouteSign::
    .string "ROUTE 17\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route17_Text_DontThrowGameThrowBalls::
    .string "Det er en besked!\p"
    .string "Kast ikke spillet, kast POKe-\n"
    .string "BALLS i stedet!$"

Route17_Text_CyclingRoadSign::
    .string "CYKELVEJ\n"
    .string "Skraaning slutter her!$"
