Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Jeg driver DAGPLEJE-tjenesten.\p"
	.string "Vil du have mig til at opdrage en\n"
	.string "af dine POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Kom igen.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "Hvilken POKéMON skal jeg opdrage?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Fint.\n"
	.string "Kom nâr du vil.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Fint, jeg passer din\n"
	.string "{STR_VAR_1} et stykke tid.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Kom til mig om en stund.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "Du er tilbage allerede?\p"
	.string "Din {STR_VAR_1} har brug for at\n"
	.string "bruge mere tid hos mig.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "Du skylder mig ¥{STR_VAR_2} for at fâ\n"
	.string "denne POKéMON tilbage.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "Tak!\n"
	.string "Her er din POKéMON.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} fik {STR_VAR_1} tilbage\n"
	.string "fra DAGPLEJE-manden.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Oh? Du har kun en POKéMON\n"
	.string "med dig.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "Hvis du efterlader den POKéMON hos\n"
	.string "mig, hvad vil du sâ kæmpe med?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "Din {STR_VAR_1} er vokset meget.\n"
	.string "Ja, ret meget, vil jeg sige.\p"
	.string "Lad mig se…\n"
	.string "Niveau-mæssigt er den vokset {STR_VAR_2}.\p"
	.string "Er jeg ikke fantastisk?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "Du kan ikke fâ denne POKéMON\n"
	.string "tilbage hvis du ikke har plads.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "Du har ikke nok penge.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
    .string "Skal jeg tage et kig pâ dine?$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
    .string "Beklager, jeg kan ikke tage imod\n"
    .string "POKéMON med skjulte træk.$"
