SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
    .string "Kyahaha!\n"
    .string "Jeg fejer dig väk uden besvär!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
    .string "Tch!\n"
    .string "For stärk for mig!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
    .string "Hvad er det?\n"
    .string "Jeg opförer mig ikke som jeg ser ud?\p"
    .string "Heh, det er en del af min strategi!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
    .string "Hej!\n"
    .string "Er du medlem af min fanclub?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
    .string "Aah, sâ du er ikke en fan…\p"
    .string "Ja, jeg kan ändre det.\n"
    .string "Lad mig synge for dig!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
    .string "Lalalah…\n"
    .string "Min POKeMON, jeg sender dem ud,\l"
    .string "alle pigerne skriger og râber!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
    .string "Denne ö er for spredt…\n"
    .string "Det er ikke nemt at patruljere.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
    .string "Uh-huh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
    .string "TRAINERS som dig fra byer,\n"
    .string "de er virkelig hârde.\p"
    .string "Du tager til TOWER,\n"
    .string "gör du ikke?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
    .string "Jeg straffer folk der misbruger\n"
    .string "POKeMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
    .string "Du virker ikke som et problem-\n"
    .string "TRAINER.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
    .string "Hvis du behandler dine POKeMON med\n"
    .string "venlighed, forstâr de.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
    .string "EVE: Jeg slâr mig sammen med JON og\n"
    .string "kämper sammen.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
    .string "EVE: Mig og JON tabte vi.\n"
    .string "Ehehe.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
    .string "EVE: Jeg vil arbejde hârdere med\n"
    .string "JON.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
    .string "EVE: Jeg vil gerne slâ mig sammen med JON\n"
    .string "nâr jeg kämper mod dig.\p"
    .string "Kom tilbage med to POKeMON, okay?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
    .string "JON: Nâr jeg er med EVE, föles det\n"
    .string "som om vi aldrig kunne tabe.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
    .string "JON: Nâr jeg er med EVE,\n"
    .string "föles det ikke som om jeg har tabt!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
    .string "JON: Nâr jeg er med EVE, föler jeg mig\n"
    .string "svimmel om jeg vinder eller taber.\p"
    .string "Det er magisk!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
    .string "JON: Hvis det er med EVE, kämper jeg\n"
    .string "gerne mod dig.\p"
    .string "Sâ jeg vil gerne göre det til en\n"
    .string "to-mod-to kamp, om jeg mâ.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
    .string "SEVAULT CANYON ENTRANCE\p"
    .string "TRAINERS bedes undlade at\n"
    .string "skâde planter i CANYON.$"

