SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
    .string "Kyahaha!\n"
    .string "Jeg fejer dig vaek uden besvaer!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
    .string "Tch!\n"
    .string "For staerk for mig!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
    .string "Hvad er det?\n"
    .string "Jeg opfoerer mig ikke som jeg ser ud?\p"
    .string "Heh, det er en del af min strategi!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
    .string "Hej!\n"
    .string "Er du medlem af min fanclub?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
    .string "Aah, saa du er ikke en fan…\p"
    .string "Ja, jeg kan aendre det.\n"
    .string "Lad mig synge for dig!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
    .string "Lalalah…\n"
    .string "Min POKeMON, jeg sender dem ud,\l"
    .string "alle pigerne skriger og raaber!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
    .string "Denne oe er for spredt…\n"
    .string "Det er ikke nemt at patruljere.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
    .string "Uh-huh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
    .string "TRAINERS som dig fra byer,\n"
    .string "de er virkelig haarde.\p"
    .string "Du tager til TOWER,\n"
    .string "goer du ikke?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
    .string "Jeg straffer folk der misbruger\n"
    .string "POKeMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
    .string "Du virker ikke som et problem-\n"
    .string "TRAINER.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
    .string "Hvis du behandler dine POKeMON med\n"
    .string "venlighed, forstaar de.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
    .string "EVE: Jeg slaar mig sammen med JON og\n"
    .string "kaemper sammen.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
    .string "EVE: Mig og JON tabte vi.\n"
    .string "Ehehe.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
    .string "EVE: Jeg vil arbejde haardere med\n"
    .string "JON.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
    .string "EVE: Jeg vil gerne slaa mig sammen med JON\n"
    .string "naar jeg kaemper mod dig.\p"
    .string "Kom tilbage med to POKeMON, okay?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
    .string "JON: Naar jeg er med EVE, foeles det\n"
    .string "som om vi aldrig kunne tabe.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
    .string "JON: Naar jeg er med EVE,\n"
    .string "foeles det ikke som om jeg har tabt!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
    .string "JON: Naar jeg er med EVE, foeler jeg mig\n"
    .string "svimmel om jeg vinder eller taber.\p"
    .string "Det er magisk!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
    .string "JON: Hvis det er med EVE, kaemper jeg\n"
    .string "gerne mod dig.\p"
    .string "Saa jeg vil gerne goere det til en\n"
    .string "to-mod-to kamp, om jeg maa.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
    .string "SEVAULT CANYON ENTRANCE\p"
    .string "TRAINERS bedes undlade at\n"
    .string "skaade planter i CANYON.$"

