Route12_Text_MonSprawledOutInSlumber::
    .string "Et POKéMON ligger og sover dybt\n"
    .string "og behageligt.$"

Text_SnorlaxWokeUp::
    .string "SNORLAX vâgnede!\p"
    .string "Den angreb i arrig vrede!$"

Text_SnorlaxReturnedToMountains::
    .string "SNORLAX blev rolig.\n"
    .string "Den gav et kämpe gaben…\l"
    .string "Og vendte tilbage til bjergene.$"

Text_WantToUsePokeFlute::
    .string "Vil du bruge POKe FLUTE?$"

Text_PlayedPokeFlute::
    .string "{PLAYER} spillede POKe FLUTE.$"

Route12_Text_NedIntro::
    .string "Ja!\n"
    .string "Jeg fik et bid her!$"

Route12_Text_NedDefeat::
    .string "Tch!\n"
    .string "Bare en lille fisk…$"

Route12_Text_NedPostBattle::
    .string "Vent!\n"
    .string "Min line er sat fast!$"

Route12_Text_ChipIntro::
    .string "Hav tâlmodighed.\n"
    .string "Fiskeri er et ventespil.$"

Route12_Text_ChipDefeat::
    .string "Den slap väk!$"

Route12_Text_ChipPostBattle::
    .string "Med et bedre ROD kunne jeg fange\n"
    .string "bedre POKéMON…$"

Route12_Text_JustinIntro::
    .string "Jeg leder efter en MOON STONE.\n"
    .string "Har du fundet en?$"

Route12_Text_JustinDefeat::
    .string "Av!$"

Route12_Text_JustinPostBattle::
    .string "Jeg kunne have ladet mine POKéMON\n"
    .string "udvikle sig med en MOON STONE.\p"
    .string "Sâ havde jeg vundet, vädder jeg.$"

Route12_Text_LucaIntro::
    .string "Elektricitet er min speciale.\p"
    .string "Jeg ved ikke noget om havets\n"
    .string "POKéMON.$"

Route12_Text_LucaDefeat::
    .string "Afpluget!$"

Route12_Text_LucaPostBattle::
    .string "Vand leder elektricitet, sâ du\n"
    .string "bör give hav-POKéMON stöd.$"

Route12_Text_HankIntro::
    .string "FISHING FOOL mod POKéMON KID!$"

Route12_Text_HankDefeat::
    .string "For meget!$"

Route12_Text_HankPostBattle::
    .string "Jeg gätter man bliver god til det\n"
    .string "man kan lide.\p"
    .string "Du slog mig i POKéMON, men du\n"
    .string "kan ikke slâ mig til fiskeri.$"

Route12_Text_ElliotIntro::
    .string "Jeg elsker fiskeri, misforstâ ikke.\p"
    .string "Men det ville väre bedst hvis jeg\n"
    .string "ogsâ havde mere arbejde.$"

Route12_Text_ElliotDefeat::
    .string "Det er ikke nemt…$"

Route12_Text_ElliotPostBattle::
    .string "Det er okay.\n"
    .string "At tabe gener mig ikke längere.$"

Route12_Text_AndrewIntro::
    .string "Hvad fanges?\p"
    .string "Man ved aldrig hvad man kan\n"
    .string "fange!$"

Route12_Text_AndrewDefeat::
    .string "Mistede den!$"

Route12_Text_AndrewPostBattle::
    .string "Hvad, MAGIKARP?\p"
    .string "Jeg fanger dem hele tiden, ja.\n"
    .string "Men de er virkelig svage.$"

Route12_Text_RouteSign::
    .string "ROUTE 12 \n"
    .string "Nord til LAVENDER$"

Route12_Text_SportfishingArea::
    .string "SPORTFISHING AREA$"

Route12_Text_JesIntro::
    .string "JES: Hvis jeg vinder, frier jeg\n"
    .string "til GIA.$"

Route12_Text_JesDefeat::
    .string "JES: Oh, hvorfor kunne du ikke\n"
    .string "lade os vinde?$"

Route12_Text_JesPostBattle::
    .string "JES: Oh, GIA, tilgiv mig,\n"
    .string "min kärlighed!$"

Route12_Text_JesNotEnoughMons::
    .string "JES: GIA og jeg, vi bliver\n"
    .string "sammen for evigt.\p"
    .string "Vi kämper ikke medmindre du har\n"
    .string "to POKéMON selv.$"

Route12_Text_GiaIntro::
    .string "GIA: Hey, JES…\p"
    .string "Hvis vi vinder, gifter jeg mig\n"
    .string "med dig!$"

Route12_Text_GiaDefeat::
    .string "GIA: Oh, men hvorfor?$"

Route12_Text_GiaPostBattle::
    .string "GIA: JES, din tosser!\n"
    .string "Du ödelagde det!$"

Route12_Text_GiaNotEnoughMons::
    .string "GIA: Jeg kan ikke kämpe uden\n"
    .string "min JES!\p"
    .string "Har du ikke en POKéMON mere?$"
