SaffronCity_Gym_Text_SabrinaIntro::
    .string "Jeg havde en vision om din ankomst.\p"
    .string "Jeg har haft psykiske kraefter siden\n"
    .string "jeg var barn.\p"
    .string "Det startede da en ske jeg\n"
    .string "uagtsomt kastede, bojede.\p"
    .string "Jeg kan ikke lide at kaempe, men hvis du vil,\n"
    .string "viser jeg dig mine kraefter!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "Dette nederlag chokerer mig!\n"
    .string "Men et nederlag er et nederlag.\p"
    .string "Jeg indroemmer, jeg arbejdede ikke\n"
    .string "haardt nok for at vinde.\p"
    .string "Din sejr har fortjent dig\n"
    .string "MARSHBADGE.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Psykisk kraft er ikke noget kun\n"
    .string "fa mennesker har.\p"
    .string "Alle har psykisk kraft.\n"
    .string "Folk er bare ikke klar over det.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "MARSHBADGE faar POKeMON op til\n"
    .string "Lv. 70 til at adlyde dig.\p"
    .string "Staerkere POKeMON bliver vilde og\n"
    .string "ignorerer dine ordre i kamp.\p"
    .string "Opdrag bare ikke dine POKeMON for\n"
    .string "meget for at undgaa det problem.\p"
    .string "Vent, tag venligst denne TM med.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} modtog TM04 fra\n"
    .string "SABRINA.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "TM04 er CALM MIND.\p"
    .string "Den faar POKeMON til at koncentrere sig\n"
    .string "for at oge baade SP. ATK og SP. DEF.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Din TASKE er fuld af andre ting.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "SABRINA er langt yngre end mig,\n"
    .string "men hun har fortjent min respekt.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "Ikke godt nok!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "I en kamp mellem lige staerke vinder\n"
    .string "den med staerkeste vilje.\p"
    .string "Hvis du vil besejre SABRINA, fokuser\n"
    .string "og vil dig til sejr.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Skraemmer vores usynlige kraft dig?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "Det forudsa jeg aldrig!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "PSYCHIC POKeMON frygter kun spoegelser\n"
    .string "og insekter!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "POKeMON antager udseendet af\n"
    .string "deres TRAINERE.\p"
    .string "Dine POKeMON maa vaere haarde, da!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "Jeg vidste det!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "Jeg har meget at laere endnu…\p"
    .string "Jeg maa mestre PSYCHIC og laere det\n"
    .string "til mine POKeMON…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "Du forstaar, ikke?\p"
    .string "At kraft alene ikke er nok til at\n"
    .string "vinde i POKeMON-verdenen?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "Det tror jeg ikke paa!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "SABRINA udslettede lige KARATE\n"
    .string "MESTEREN ved siden af.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "Du og jeg, vores POKeMON skal\n"
    .string "kaempe!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "Jeg tabte alligevel!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "Jeg vidste at dette ville ske.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA er ung, men hun er ogsaa\n"
    .string "vores meget dygtige LEADER.\p"
    .string "Du naar ikke let til hende!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Av!\n"
    .string "Ned og ude!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "Der var engang to POKeMON GYMS\n"
    .string "i SAFFRON.\p"
    .string "FIGHTING DOJO ved siden af mistede\n"
    .string "sin GYM-status, dog.\p"
    .string "Vi tromlede dem bare ned da vi\n"
    .string "besluttede at have kun eet GYM.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "SAFFRON POKeMON GYM er kendt for\n"
    .string "at traene psykikere.\p"
    .string "Du vil se SABRINA, ikke?\n"
    .string "Jeg kan maerke det!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "Praecis! Jeg brugte telepati til at\n"
    .string "laese dine tanker!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion under opsejling!\p"
    .string "SABRINAs POKeMON bruger psykisk\n"
    .string "kraft i stedet for magt.\p"
    .string "FIGHTING POKeMON er saerligt\n"
    .string "svaage over for PSYCHIC POKeMON.\p"
    .string "De bliver odelagt foer de overhovedet\n"
    .string "kan sigte et stoed!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "Psykisk kraft, hva?\p"
    .string "Hvis jeg havde det, ville jeg tjene\n"
    .string "en formue paa spilleautomaterne!$"

SaffronCity_Gym_Text_GymStatue::
    .string "SAFFRON POKeMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "VINDENDE TRAINERE:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "SAFFRON POKeMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "VINDENDE TRAINERE:\n"
    .string "{RIVAL}, {PLAYER}$"

