SaffronCity_Gym_Text_SabrinaIntro::
    .string "Jeg havde en vision om din ankomst.\p"
    .string "Jeg har haft psykiske kräfter siden\n"
    .string "jeg var barn.\p"
    .string "Det startede da en ske jeg\n"
    .string "uagtsomt kastede, bojede.\p"
    .string "Jeg kan ikke lide at kämpe, men hvis du vil,\n"
    .string "viser jeg dig mine kräfter!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "Dette nederlag chokerer mig!\n"
    .string "Men et nederlag er et nederlag.\p"
    .string "Jeg indrömmer, jeg arbejdede ikke\n"
    .string "hârdt nok for at vinde.\p"
    .string "Din sejr har fortjent dig\n"
    .string "MARSHBADGE.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Psykisk kraft er ikke noget kun\n"
    .string "fa mennesker har.\p"
    .string "Alle har psykisk kraft.\n"
    .string "Folk er bare ikke klar over det.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "MARSHBADGE fâr POKéMON op til\n"
    .string "Lv. 70 til at adlyde dig.\p"
    .string "Stärkere POKéMON bliver vilde og\n"
    .string "ignorerer dine ordre i kamp.\p"
    .string "Opdrag bare ikke dine POKéMON for\n"
    .string "meget for at undgâ det problem.\p"
    .string "Vent, tag venligst denne TM med.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} modtog TM04 fra\n"
    .string "SABRINA.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "TM04 er CALM MIND.\p"
    .string "Den fâr POKéMON til at koncentrere sig\n"
    .string "for at oge bâde SP. ATK og SP. DEF.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Din TASKE er fuld af andre ting.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "SABRINA er langt yngre end mig,\n"
    .string "men hun har fortjent min respekt.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "Ikke godt nok!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "I en kamp mellem lige stärke vinder\n"
    .string "den med stärkeste vilje.\p"
    .string "Hvis du vil besejre SABRINA, fokuser\n"
    .string "og vil dig til sejr.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Skrämmer vores usynlige kraft dig?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "Det forudsa jeg aldrig!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "PSYCHIC POKéMON frygter kun spögelser\n"
    .string "og insekter!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "POKéMON antager udseendet af\n"
    .string "deres TRAINERE.\p"
    .string "Dine POKéMON mâ väre hârde, da!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "Jeg vidste det!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "Jeg har meget at läre endnu…\p"
    .string "Jeg mâ mestre PSYCHIC og läre det\n"
    .string "til mine POKéMON…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "Du forstâr, ikke?\p"
    .string "At kraft alene ikke er nok til at\n"
    .string "vinde i POKéMON-verdenen?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "Det tror jeg ikke pâ!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "SABRINA udslettede lige KARATE\n"
    .string "MESTEREN ved siden af.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "Du og jeg, vores POKéMON skal\n"
    .string "kämpe!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "Jeg tabte alligevel!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "Jeg vidste at dette ville ske.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA er ung, men hun er ogsâ\n"
    .string "vores meget dygtige LEADER.\p"
    .string "Du nâr ikke let til hende!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Av!\n"
    .string "Ned og ude!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "Der var engang to POKéMON GYMS\n"
    .string "i SAFFRON.\p"
    .string "FIGHTING DOJO ved siden af mistede\n"
    .string "sin GYM-status, dog.\p"
    .string "Vi tromlede dem bare ned da vi\n"
    .string "besluttede at have kun eet GYM.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "SAFFRON POKéMON GYM er kendt for\n"
    .string "at träne psykikere.\p"
    .string "Du vil se SABRINA, ikke?\n"
    .string "Jeg kan märke det!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "Präcis! Jeg brugte telepati til at\n"
    .string "läse dine tanker!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion under opsejling!\p"
    .string "SABRINAs POKéMON bruger psykisk\n"
    .string "kraft i stedet for magt.\p"
    .string "FIGHTING POKéMON er särligt\n"
    .string "svâge over for PSYCHIC POKéMON.\p"
    .string "De bliver odelagt för de overhovedet\n"
    .string "kan sigte et stöd!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "Psykisk kraft, hva?\p"
    .string "Hvis jeg havde det, ville jeg tjene\n"
    .string "en formue pâ spilleautomaterne!$"

SaffronCity_Gym_Text_GymStatue::
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "VINDENDE TRAINERE:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "VINDENDE TRAINERE:\n"
    .string "{RIVAL}, {PLAYER}$"

