PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "En mistænkelig gammel fyr fik mig til at\n"
    .string "købe denne underlige fisk-POKéMON!\p"
    .string "Den er totalt svag og kostede ¥500!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "Gode ting kan ske hvis du opdrager\n"
    .string "POKéMON flittigt.\p"
    .string "Selv de svage kan overraske\n"
    .string "dig hvis du ikke giver op.$"
