PokemonTower_6F_Text_AngelicaIntro::
    .string "Giv…mig…\n"
    .string "blod…$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "Stoen!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "Jeg foeler mig anaemisk og svag…$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Urff…\n"
    .string "Kwaah!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "Noget faldt ud!$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "Mit haar faldt ikke ud!\n"
    .string "Det var en ondskabsfuld aand!$"

PokemonTower_6F_Text_JenniferIntro::
    .string "Ke…ke…ke…\n"
    .string "ke…ke…ke!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "Keee!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "Hvad sker der her?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "Forsvind…\n"
    .string "Indtraengende…$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "Spoegelsen var den rastloese aand\n"
    .string "af CUBONEs mor!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "Morens aand blev beroliget.\p"
    .string "Den rejste til det hinsidige…$"
