VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "Der er ondskabsfulde mennesker der vil\n"
    .string "bruge POKeMON til kriminelle handlinger.\p"
    .string "TEAM ROCKET handler med själdne\n"
    .string "POKeMON, for eksempel.\p"
    .string "De forlader ogsâ POKeMON som\n"
    .string "de anser for upopuläre eller ubrugelige.\p"
    .string "Det er den slags forfärdelige mennesker\n"
    .string "de er, TEAM ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "Jeg tror POKeMON kan väre gode eller\n"
    .string "dârlige. Det afhänger af TRAeNEREN.$"

