VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "Der er ondskabsfulde mennesker der vil\n"
    .string "bruge POKéMON til kriminelle handlinger.\p"
    .string "TEAM ROCKET handler med sjældne\n"
    .string "POKéMON, for eksempel.\p"
    .string "De forlader ogsâ POKéMON som\n"
    .string "de anser for upopulære eller ubrugelige.\p"
    .string "Det er den slags forfærdelige mennesker\n"
    .string "de er, TEAM ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "Jeg tror POKéMON kan være gode eller\n"
    .string "dârlige. Det afhænger af TRÆNEREN.$"

