VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "Der er ondskabsfulde mennesker der vil\n"
    .string "bruge POKeMON til kriminelle handlinger.\p"
    .string "TEAM ROCKET handler med sjaeldne\n"
    .string "POKeMON, for eksempel.\p"
    .string "De forlader ogsaa POKeMON som\n"
    .string "de anser for upopulaere eller ubrugelige.\p"
    .string "Det er den slags forfaerdelige mennesker\n"
    .string "de er, TEAM ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "Jeg tror POKeMON kan vaere gode eller\n"
    .string "daarlige. Det afhaenger af TRAeNEREN.$"

