Text_ExplosionTeach::
    .string "Kan du forestille dig?\n"
    .string "Hvis denne vulkan udbrød?\p"
    .string "Eksplosionen ville være vores ende.\n"
    .string "Hvor skræmmende er det ikke?\p"
    .string "Mens vi er bange, vil du have mig\n"
    .string "til at lære EXPLOSION?$"

Text_ExplosionDeclined::
    .string "Ja, du har ret.\n"
    .string "Det er for skræmmende.$"

Text_ExplosionWhichMon::
    .string "Du er forfærdeligt modig!\p"
    .string "Hvilken POKéMON skal jeg lære\n"
    .string "EXPLOSION?$"

Text_ExplosionTaught::
    .string "At bruge EXPLOSION her pâ denne\n"
    .string "vulkan…\p"
    .string "Hvilken skræmmende thrill!$"

@ Below 4 are unused JP versions of the above texts
Text_ExplosionTeachJP::
    .string "こ　この　かざんが\n"
    .string "もし　だいばくはつ　したら\l"
    .string "お　おれら　ひとたまりも\l"
    .string "ないなあ　‥ブルブル！\p"
    .string "こ　こわい　ついでに\n"
    .string "だいばくはつ　でも　おぼえてみる？$"

Text_ExplosionDeclinedJP::
    .string "や　やっぱ　こわいもんな\n"
    .string "ブルブル$"

Text_ExplosionWhichMonJP::
    .string "つ　つよきだね！\n"
    .string "じゃあ　どの　ポケモンに　する？$"

Text_ExplosionTaughtJP::
    .string "かざんで　だいばくはつを‥\n"
    .string "す　すごい　スリル！$"

MtEmber_Exterior_Text_WellTryDiggingHere::
    .string "Herovre.\n"
    .string "Vi prøver at grave her.\p"
    .string "Skatten ADMIN'erne har talt om\n"
    .string "skal være her.$"

MtEmber_Exterior_Text_YoureInTheWayGetLost::
    .string "Hvad…?\n"
    .string "Du er i vejen. Forsvind.$"

MtEmber_Exterior_Text_PunchedThroughAtLast::
    .string "Puha, endelig gennembrudt.\n"
    .string "Lad os skattejage!$"

MtEmber_Exterior_Text_WhatsPasswordAgain::
    .string "Al skat vi finder bringer vi tilbage\n"
    .string "til LAGERET, forstâet?\p"
    .string "…Øh, og hvad er adgangskoderne?\n"
    .string "Ved ROCKET LAGERET, mener jeg.$"

MtEmber_Exterior_Text_FirstPasswordGoldeen::
    .string "Hvad, du glemte adgangskoden?\n"
    .string "Der er faktisk to.\p"
    .string "Den første er GOLDEEN need\n"
    .string "log.\p"
    .string "Og den anden er…$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn::
    .string "Hey!\n"
    .string "Denne snus har lyttet med!$"

MtEmber_Exterior_Text_Grunt1Intro::
    .string "Du har lyttet med pâ os,\n"
    .string "har du ikke?$"

MtEmber_Exterior_Text_Grunt1Defeat::
    .string "Hvad, hvad?$"

MtEmber_Exterior_Text_Grunt1PostBattle::
    .string "Hvorfor skulle du vinde?$"

MtEmber_Exterior_Text_Grunt2Intro::
    .string "Prover du at komme ind pâ vores\n"
    .string "skat? Glem det!$"

MtEmber_Exterior_Text_Grunt2Defeat::
    .string "Vent!\n"
    .string "Men hvordan?$"

MtEmber_Exterior_Text_Grunt2PostBattle::
    .string "Fâ beqvem hukommelsestab og\n"
    .string "glem alt hvad du hørte!$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere::
    .string "Sikke et tilbageslag…\n"
    .string "Vi mâ samle os igen.\p"
    .string "Du! Tænk ikke engang pâ at\n"
    .string "træde ind der!\p"
    .string "Hvis du ved hvad der er godt for\n"
    .string "dig, glem det helt!$"

MtEmber_Exterior_Text_LoganIntro::
    .string "En aktiv vulkan er een der\n"
    .string "udbruder eller er ved at.$"

MtEmber_Exterior_Text_LoganDefeat::
    .string "Puha… Det var varmt!\n"
    .string "Sveden udbruder fra mig!$"

MtEmber_Exterior_Text_LoganPostBattle::
    .string "De siger der er over 1500 aktive\n"
    .string "vulkaner i verden.\p"
    .string "Bare tanken gør mig helt varm\n"
    .string "inderst inde!$"

MtEmber_Exterior_Text_BethIntro::
    .string "Ved du hvordan huler dannes inde i\n"
    .string "vulkaner?$"

MtEmber_Exterior_Text_BethDefeat::
    .string "Atchah!\n"
    .string "Du er chokerende dygtig!$"

MtEmber_Exterior_Text_BethPostBattle::
    .string "Nâr lava pâ overfladen af magma\n"
    .string "hærder, og magmæn inde flyder ud,\l"
    .string "bliver der huler tilbage.$"

MtEmber_Exterior_Text_JocelynIntro::
    .string "Jeg har trænet for at læger mit\n"
    .string "knuste hjerte…\p"
    .string "Det hærdede mig i det mindste\n"
    .string "fysisk! Hi-yah!$"

MtEmber_Exterior_Text_JocelynDefeat::
    .string "Jeg tror jeg overdrev…$"

MtEmber_Exterior_Text_JocelynPostBattle::
    .string "Mâden du kæmper pâ minder mig\n"
    .string "om fyren der dumpede mig…$"

