SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "Du ved hvad de siger om\n"
    .string "sømænd og kamp!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "Lige!\n"
    .string "God kamp, kammerat!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "Hahaha!\n"
    .string "Vil du være sømand, kammerat?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "Kom så!\n"
    .string "Min sømandsstolthed står på spil!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "Din ånd sænkede mig!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "Så du FISHING GURU i\n"
    .string "VERMILION CITY?$"

