SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "Du ved hvad de siger om\n"
    .string "soemaend og kamp!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "Lige!\n"
    .string "God kamp, kammerat!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "Hahaha!\n"
    .string "Vil du vaere soemand, kammerat?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "Kom saa!\n"
    .string "Min soemandsstolthed staar paa spil!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "Din aand saenkede mig!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "Saa du FISHING GURU i\n"
    .string "VERMILION CITY?$"

