SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "Du ved hvad de siger om\n"
    .string "sömänd og kamp!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "Lige!\n"
    .string "God kamp, kammerat!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "Hahaha!\n"
    .string "Vil du väre sömand, kammerat?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "Kom sâ!\n"
    .string "Min sömandsstolthed stâr pâ spil!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "Din ând sänkede mig!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "Sâ du FISHING GURU i\n"
    .string "VERMILION CITY?$"

