SixIsland_Text_IslandSign::
    .string "SIX ISLAND\n"
    .string "Lykkeön med gammel visdom$"

SixIsland_Text_ThatWayToWaterPathRuinValley::
    .string "Fortsät denne vej og du nâr\n"
    .string "WATER PATH.\p"
    .string "Hold dig til den og du nâr\n"
    .string "RUIN VALLEY.$"

SixIsland_Text_SkyAtNightIsFantastic::
    .string "Nâr du er sâ langt fra byen,\n"
    .string "er nattehimlen fantastisk.$"

