Text_RockSlideTeach::
    .string "Nâr du er oppe pâ et bjerg med sten\n"
    .string "som her, er stenskred en trussel.\p"
    .string "Kan du forestille dig?\n"
    .string "Kampesten der välter ned over dig?\p"
    .string "Det ville väre, ligesom, wâââââah!\n"
    .string "Total skräk!\p"
    .string "Du ser ikke bange ud.\n"
    .string "Vil du präve at bruge ROCK SLIDE?$"

Text_RockSlideDeclined::
    .string "Ah, sâ du er bange alligevel.$"

Text_RockSlideWhichMon::
    .string "Hvilket POKéMON skal jeg läre\n"
    .string "ROCK SLIDE?$"

Text_RockSlideTaught::
    .string "Det kan väre skrämmende at bruge det\n"
    .string "i denne tunnel…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "Hint: Kampesten kan ändre\n"
    .string "vandströmmen.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "FARE\n"
    .string "Hurtig ström!$"

