Text_RockSlideTeach::
    .string "Naar du er oppe paa et bjerg med sten\n"
    .string "som her, er stenskred en trussel.\p"
    .string "Kan du forestille dig?\n"
    .string "Kampesten der vaelter ned over dig?\p"
    .string "Det ville vaere, ligesom, waaaaaaaaaaah!\n"
    .string "Total skraek!\p"
    .string "Du ser ikke bange ud.\n"
    .string "Vil du praeve at bruge ROCK SLIDE?$"

Text_RockSlideDeclined::
    .string "Ah, saa du er bange alligevel.$"

Text_RockSlideWhichMon::
    .string "Hvilket POKeMON skal jeg laere\n"
    .string "ROCK SLIDE?$"

Text_RockSlideTaught::
    .string "Det kan vaere skraemmende at bruge det\n"
    .string "i denne tunnel…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "Hint: Kampesten kan aendre\n"
    .string "vandstroemmen.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "FARE\n"
    .string "Hurtig stroem!$"

