CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "Mig?\n"
    .string "Jeg er programmören!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "Jeg er grafikeren!\n"
    .string "Jeg tegnede dig!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "Jeg skrev historien!\n"
    .string "Er ERIKA ikke söd?\p"
    .string "Jeg kan ogsâ godt lide MISTY!\n"
    .string "Aah, og SABRINA, jeg kan lide hende!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "Er det rigtigt?\p"
    .string "Jeg er spildesigneren!\p"
    .string "At udfylde din POKeDEX er svärt,\n"
    .string "men giv ikke op!\p"
    .string "Nâr du er färdig, kom og sig det til mig!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "Wow! Fremragende!\n"
    .string "Du fuldförte din POKeDEX!\l"
    .string "Tillykke!\l"
    .string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "Det er spilprogrammet! At pille ved det\n"
    .string "kunne give fejl i spillet!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "Nogen spiller et spil i stedet for\n"
    .string "at arbejde!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "Det er manuskriptet!\n"
    .string "Se hellere ikke pâ slutningen!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "GAME FREAK Udviklingslokale$"
