CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "POKeMON stat-forbedringer kan kun\n"
    .string "köbes her.\p"
    .string "HP UP öger basis HP af en\n"
    .string "POKeMON.\p"
    .string "CALCIUM öger basis SP. ATK\n"
    .string "stat af en POKeMON.\p"
    .string "ZINC öger basis SP. DEF stat\n"
    .string "af en POKeMON.\p"
    .string "CARBOS forbedrer basis SPEED\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "Jeg er her efter POKeMON stat-\n"
    .string "forbedringer.\p"
    .string "PROTEIN öger basis ATTACK\n"
    .string "kraft.\p"
    .string "IRON öger basis DEFENSE\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: DRUGSTORE$"
