CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "POKéMON stat-forbedringer kan kun\n"
    .string "købes her.\p"
    .string "HP UP øger basis HP af en\n"
    .string "POKéMON.\p"
    .string "CALCIUM øger basis SP. ATK\n"
    .string "stat af en POKéMON.\p"
    .string "ZINC øger basis SP. DEF stat\n"
    .string "af en POKéMON.\p"
    .string "CARBOS forbedrer basis SPEED\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "Jeg er her efter POKéMON stat-\n"
    .string "forbedringer.\p"
    .string "PROTEIN øger basis ATTACK\n"
    .string "kraft.\p"
    .string "IRON øger basis DEFENSE\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: DRUGSTORE$"
