CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "POKeMON stat-forbedringer kan kun\n"
    .string "koebes her.\p"
    .string "HP UP oeger basis HP af en\n"
    .string "POKeMON.\p"
    .string "CALCIUM oeger basis SP. ATK\n"
    .string "stat af en POKeMON.\p"
    .string "ZINC oeger basis SP. DEF stat\n"
    .string "af en POKeMON.\p"
    .string "CARBOS forbedrer basis SPEED\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "Jeg er her efter POKeMON stat-\n"
    .string "forbedringer.\p"
    .string "PROTEIN oeger basis ATTACK\n"
    .string "kraft.\p"
    .string "IRON oeger basis DEFENSE\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: DRUGSTORE$"
