SilphCo_7F_Text_HaveMonForSavingUs::
    .string "Oh! Hej! Du er ikke en ROCKET!\n"
    .string "Du kom for at redde os?\l"
    .string "Hvor tak, tak!\p"
    .string "Jeg vil give dig dette POKeMON\n"
    .string "for at redde os.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "{PLAYER} fik en LAPRAS fra\n"
    .string "SILPH-ansatten!$"

SilphCo_7F_Text_ExplainLapras::
    .string "Det er en LAPRAS.\n"
    .string "Det er et meget intelligent POKeMON.\p"
    .string "Vi holdt det i vores lab, men det\n"
    .string "vil have det meget bedre hos dig.\p"
    .string "Jeg tror du vil vaere en god TRAINER\n"
    .string "for LAPRAS!\p"
    .string "Den er en god svoemmer.\n"
    .string "Den giver dig lift over vand!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "TEAM ROCKETs BOSS gik til\n"
    .string "modesalen!\p"
    .string "Er vores PRESIDENT okay?\n"
    .string "Jeg er bekymret.$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "TEAM ROCKET jagede MASTER\n"
    .string "BALL'en, der fanger ethvert POKeMON.$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "Vi annullerede MASTER BALL-\n"
    .string "projektet pga. TEAM ROCKET.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "Det ville vaere slemt hvis TEAM ROCKET\n"
    .string "overtog SILPH eller vores POKeMON.$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "Wow!\p"
    .string "Du jagede TEAM ROCKET vaek\n"
    .string "helt alene?$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "Du!\n"
    .string "Det er virkelig farligt her!\p"
    .string "Du kom for at redde mig?\n"
    .string "Du kan ikke!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "Tusind tak!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "Uh-oh!\n"
    .string "Jeg lugter en lille mus!$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "Lys ud!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "Du finder ikke min BOSS ved bare\n"
    .string "at lobe rundt!$"

SilphCo_7F_Text_JoshuaIntro::
    .string "Heheh!\p"
    .string "Du forvekslede mig med en SILPH-ansat?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "Jeg er faerdig!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "Paa trods af din alder er du en\n"
    .string "dygtig TRAINER!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "Jeg er en af de fire ROCKET\n"
    .string "BROEDRE!$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "Aack!\n"
    .string "Broedre, jeg tabte!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "Ligemeget.\n"
    .string "Mine broedre vil gengaelde tjenesten!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "Et barn som indtraenger?\n"
    .string "Det maa vaere dig!$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "Fint!\n"
    .string "Jeg tabte!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "Ga hjem foer min BOSS bliver\n"
    .string "sur!$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{RIVAL}: Hvad tog saa laenge, {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
    .string "{RIVAL}: Hahaha! Jeg troede du ville\n"
    .string "dukke op hvis jeg ventede her!\p"
    .string "Jeg gaetter paa at TEAM ROCKET\n"
    .string "langsommede dig! Det er mig ligegyldigt!\p"
    .string "Jeg sa dig i SAFFRON, saa jeg besluttede\n"
    .string "at se om du var blevet bedre!$"

SilphCo_7F_Text_RivalDefeat::
    .string "Oh man!\n"
    .string "Saa du er klar til BOSS\l"
    .string "ROCKET!$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
    .string "Naa, {PLAYER}!\n"
    .string "Jeg rykker fremad og op!\p"
    .string "Ved at tjekke min POKeDEX kan jeg\n"
    .string "begynde at se hvad der er staerkt og\l"
    .string "hvordan de udvikler sig!\p"
    .string "Er jeg et geni eller hvad?\p"
    .string "Jeg tager til POKeMON LEAGUE for at\n"
    .string "smide ELITE FOUR ud.\p"
    .string "Jeg bliver verdens mest\n"
    .string "kraftfulde TRAINER!\p"
    .string "{PLAYER}, naa, held og lykke!\n"
    .string "Bare rolig!\l"
    .string "Snus til dig!$"

SilphCo_7F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "7. SAL$"

