Route8_WestEntrance_Text_ThirstyOnGuardDuty::
    .string "Jeg er pâ vagt.\n"
    .string "Av, jeg er tørstig!\p"
    .string "Oh vent, vejen er lukket.$"

Route8_WestEntrance_Text_ThatTeaLooksTasty::
    .string "Oh, den TEA…\n"
    .string "Den ser rigtig lækker ud…$"

Route8_WestEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Hvad? Mâ jeg fâ den drink?\n"
    .string "Av, tak!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "Hvis du vil til SAFFRON\l"
    .string "CITY…\l"
    .string "… …\l"
    .string "Ma du gâe igennem.\p"
    .string "Jeg deler denne TEA med de andre\n"
    .string "vagter!$"

Route8_WestEntrance_Text_HiHowsItGoing::
    .string "Hej, hvordan gâr det?$"
