SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross::
    .string "Hera, hera, HERACROSS!\n"
    .string "Stor og skinnende, det er insekt-chefen!\l"
    .string "Elsk det, bruger det, HERACROSS!$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross::
    .string "Eeeeek!\n"
    .string "Det er en HERACROSS!\p"
    .string "Ma jeg venligst mâle hvor stor\n"
    .string "den er?$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward::
    .string "Eeeek, den er {STR_VAR_2} tommer!\n"
    .string "Jeg har aldrig set noget lignende!\l"
    .string "Du fortjener en belönning!$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne::
    .string "Jeg vil gerne se en meget, meget större\n"
    .string "HERACROSS end den der.\p"
    .string "Aah, hvor jeg tilbeder dem, store\n"
    .string "HERACROSS!$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore::
    .string "Hva? Denne {STR_VAR_2}-tommers mâling…\n"
    .string "Aah, böv! Det er det samme som för.$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest::
    .string "Aah, den er kun {STR_VAR_2} tommer.\n"
    .string "HERACROSS för var större.\p"
    .string "Den var {STR_VAR_3} tommer, den störste\n"
    .string "HERACROSS du har vist mig.$"

SixIsland_WaterPath_House1_Text_ThisWontDo::
    .string "Aah, nej! Det her duer ikke!\p"
    .string "HERACROSS ser meget mere maskulin\n"
    .string "og cool ud og har et dejligt horn!$"

SixIsland_WaterPath_House1_Text_YourBagIsFull::
    .string "Din TASKE er fuld.\n"
    .string "Min belönning kan ikke väre med.$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches::
    .string "Den störste HERACROSS jeg nogensinde\n"
    .string "har set mâlt indtil nu er:\p"
    .string "{STR_VAR_3} tommer!$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort::
    .string "Det er en blank tabel af en slags.\p"
    .string "Den har plads til at skrive\n"
    .string "rekorder af en art.$"

