ViridianCity_Gym_Text_GiovanniIntro::
    .string "Fwahahaha!\n"
    .string "Velkommen til mit skjul!\p"
    .string "Saadan forbliver det indtil jeg kan genskabe\n"
    .string "TEAM ROCKET til sin tidligere storhed.\p"
    .string "Men du har fundet mig igen.\n"
    .string "Saa vaer det.\l"
    .string "Denne gang holder jeg ikke tilbage!\p"
    .string "Endnu en gang skal du moede\n"
    .string "GIOVANNI, den stoerste TRAeNER!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "Ha!\n"
    .string "Det var en virkelig intens kamp.\l"
    .string "Du har vundet!\p"
    .string "Som bevis, her er EARTHBADGE!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Efter at have tabt paa denne maade,\n"
    .string "kan jeg ikke moede mine foelgere.\l"
    .string "Jeg har forraadt deres tillid.\p"
    .string "Fra i dag er TEAM ROCKET\n"
    .string "sluttet for evigt!\p"
    .string "Hvad mig selv angaar, vil jeg vie\n"
    .string "mit liv til traening igen.\p"
    .string "Lad os moedes igen en dag!\n"
    .string "Farvel!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "EARTHBADGE faar POKeMON paa ethvert\n"
    .string "niveau til at adlyde uden spoergsmaal.\p"
    .string "Det er bevis paa din mesterskab som\n"
    .string "POKeMON TRAeNER.\p"
    .string "Med den kan du udfordre\n"
    .string "POKeMON LEAGUE.\p"
    .string "Tag ogsaa denne TM.\p"
    .string "Betragt den som en gave til din POKeMON\n"
    .string "LEAGUE udfordring.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} modtog TM26\n"
    .string "fra GIOVANNI.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "TM26 indeholder EARTHQUAKE.\p"
    .string "Det er et kraftfuldt angreb der foraarsager\n"
    .string "et massivt jordskaelv.\p"
    .string "Jeg lavede den da jeg drev GYM her,\n"
    .string "for alt for laenge siden… $"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "Du har ikke plads til dette!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh!\n"
    .string "Du maa snart vaere ved at loebe toer for damp!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "Jeg loeb toer for benzin!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "Du faar brug for styrke for at foelge med\n"
    .string "vores GYM LEDER.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrroar!\n"
    .string "Jeg arbejder mig op i et raseri!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Wargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "Jeg er stadig ikke vaerdig!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "POKeMON og jeg, vi laver vidunderlig\n"
    .string "musik sammen!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "Du er i perfekt harmoni!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Ved du hvem vores\n"
    .string "GYM LEDER er?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Karate er den ultimative form for\n"
    .string "kampsport!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "Hvis mine POKeMON var lige saa gode til\n"
    .string "karate som jeg…$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "De virkelig talentfulde vinder med stil.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "Jeg mistede grebet!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "LEDEREN vil skaelde mig ud for\n"
    .string "at tabe paa denne maade…$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "Jeg er KARATE KONGEN!\n"
    .string "Din skaebne hviler hos mig!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "POKeMON LEAGUE?\n"
    .string "Dig? Bliv ikke overmodig!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "Dine POKeMON vil krybe sammen ved\n"
    .string "smaeldet af min pisk!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "Yowch!\n"
    .string "Piskesmaeld!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "Vent!\n"
    .string "Jeg var bare uforsigtig!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "VIRIDIAN GYM var lukket i\n"
    .string "lang tid.\p"
    .string "Men nu er vores LEDER tilbage!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "Jeg blev slaaet?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "Du kan kun komme videre til POKeMON\n"
    .string "LEAGUE ved at besejre vores GYM\l"
    .string "LEDER!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i gaere!\p"
    .string "Selv jeg kender ikke VIRIDIAN\n"
    .string "LEDERs identitet.\p"
    .string "Men en ting er sikker.\n"
    .string "Dette bliver den haardeste af alle\l"
    .string "GYM LEDERE.\p"
    .string "Jeg hoerte ogsaa at TRAeNERNE\n"
    .string "her kan lide JORD-type POKeMON.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Blaes mig vaek! GIOVANNI var\n"
    .string "GYM LEDEREN af VIRIDIAN?$"

ViridianCity_Gym_Text_GymStatue::
    .string "VIRIDIAN POKeMON GYM\n"
    .string "LEDER: ?\p"
    .string "VINDENDE TRAeNERE:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRIDIAN POKeMON GYM\n"
    .string "LEDER: GIOVANNI\p"
    .string "VINDENDE TRAeNERE:\n"
    .string "{RIVAL}, {PLAYER}$"

