ViridianCity_Gym_Text_GiovanniIntro::
    .string "Fwahahaha!\n"
    .string "Velkommen til mit skjul!\p"
    .string "Sâdan forbliver det indtil jeg kan genskabe\n"
    .string "TEAM ROCKET til sin tidligere storhed.\p"
    .string "Men du har fundet mig igen.\n"
    .string "Sâ vær det.\l"
    .string "Denne gang holder jeg ikke tilbage!\p"
    .string "Endnu en gang skal du møde\n"
    .string "GIOVANNI, den største TRÆNER!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "Ha!\n"
    .string "Det var en virkelig intens kamp.\l"
    .string "Du har vundet!\p"
    .string "Som bevis, her er EARTHBADGE!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Efter at have tabt pâ denne mâde,\n"
    .string "kan jeg ikke møde mine følgere.\l"
    .string "Jeg har forrâdt deres tillid.\p"
    .string "Fra i dag er TEAM ROCKET\n"
    .string "sluttet for evigt!\p"
    .string "Hvad mig selv angâr, vil jeg vie\n"
    .string "mit liv til træning igen.\p"
    .string "Lad os mødes igen en dag!\n"
    .string "Farvel!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "EARTHBADGE fâr POKéMON pâ ethvert\n"
    .string "niveau til at adlyde uden spørgsmâl.\p"
    .string "Det er bevis pâ din mesterskab som\n"
    .string "POKéMON TRÆNER.\p"
    .string "Med den kan du udfordre\n"
    .string "POKéMON LEAGUE.\p"
    .string "Tag ogsâ denne TM.\p"
    .string "Betragt den som en gave til din POKéMON\n"
    .string "LEAGUE udfordring.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} modtog TM26\n"
    .string "fra GIOVANNI.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "TM26 indeholder EARTHQUAKE.\p"
    .string "Det er et kraftfuldt angreb der forârsager\n"
    .string "et massivt jordskælv.\p"
    .string "Jeg lavede den da jeg drev GYM her,\n"
    .string "for alt for længe siden… $"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "Du har ikke plads til dette!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh!\n"
    .string "Du mâ snart være ved at løbe tør for damp!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "Jeg løb tør for benzin!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "Du fâr brug for styrke for at følge med\n"
    .string "vores GYM LEDER.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrroar!\n"
    .string "Jeg arbejder mig op i et raseri!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Wargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "Jeg er stadig ikke værdig!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "POKéMON og jeg, vi laver vidunderlig\n"
    .string "musik sammen!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "Du er i perfekt harmoni!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Ved du hvem vores\n"
    .string "GYM LEDER er?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Karate er den ultimative form for\n"
    .string "kampsport!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "Hvis mine POKéMON var lige sâ gode til\n"
    .string "karate som jeg…$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "De virkelig talentfulde vinder med stil.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "Jeg mistede grebet!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "LEDEREN vil skælde mig ud for\n"
    .string "at tabe pâ denne mâde…$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "Jeg er KARATE KONGEN!\n"
    .string "Din skæbne hviler hos mig!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "POKéMON LEAGUE?\n"
    .string "Dig? Bliv ikke overmodig!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "Dine POKéMON vil krybe sammen ved\n"
    .string "smældet af min pisk!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "Yowch!\n"
    .string "Piskesmæld!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "Vent!\n"
    .string "Jeg var bare uforsigtig!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "VIRIDIAN GYM var lukket i\n"
    .string "lang tid.\p"
    .string "Men nu er vores LEDER tilbage!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "Jeg blev slâet?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "Du kan kun komme videre til POKéMON\n"
    .string "LEAGUE ved at besejre vores GYM\l"
    .string "LEDER!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i gære!\p"
    .string "Selv jeg kender ikke VIRIDIAN\n"
    .string "LEDERs identitet.\p"
    .string "Men en ting er sikker.\n"
    .string "Dette bliver den hârdeste af alle\l"
    .string "GYM LEDERE.\p"
    .string "Jeg hørte ogsâ at TRÆNERNE\n"
    .string "her kan lide JORD-type POKéMON.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Blæs mig væk! GIOVANNI var\n"
    .string "GYM LEDEREN af VIRIDIAN?$"

ViridianCity_Gym_Text_GymStatue::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEDER: ?\p"
    .string "VINDENDE TRÆNERE:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEDER: GIOVANNI\p"
    .string "VINDENDE TRÆNERE:\n"
    .string "{RIVAL}, {PLAYER}$"

