RocketHideout_B1F_Text_Grunt1Intro::
    .string "Hvem er du?\n"
    .string "Hvordan kom du her?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "Av!\n"
    .string "Besejret!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "Forbandede… Du disser TEAM\n"
    .string "ROCKET, ikke?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "Du broed ind i TEAM ROCKETs\n"
    .string "operation? Hvilken fraekhed!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "Boom!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "Du slipper ikke godt fra dette,\n"
    .string "moegunge!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "Indtraenger alarm!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "Jeg kan ikke!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "SILPH SCOPE? Humph!\n"
    .string "Jeg ved ikke hvor den er.$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "Hvorfor kom du her?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "Det duer ikke!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "Okay, jeg snakker…\n"
    .string "Tag elevatoren for at se min BOSS.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "Er du faret vild, din lille mus?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "Hvorfor…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "Uh-oh, den larm aabnede paa en eller\n"
    .string "anden maade doeren!$"
