RocketHideout_B4F_Text_GiovanniIntro::
    .string "Sâ! Jeg mâ sige, jeg er imponeret over\n"
    .string "at du kom her.\p"
    .string "TEAM ROCKET fanger POKéMON fra\n"
    .string "hele verden.\p"
    .string "De er vigtige værktøjer til at holde\n"
    .string "vores kriminelle foretagenhed i gang.\p"
    .string "Jeg er lederen, GIOVANNI!\p"
    .string "For din frækhed vil du mærke en\n"
    .string "verden af smerte!$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "HVAD!\n"
    .string "Det kan ikke være!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "Jeg ser at du opdrager POKéMON med\n"
    .string "største omhu.\p"
    .string "Et barn som dig ville aldrig\n"
    .string "forstâ hvad jeg hâber at opnâ.\p"
    .string "Jeg træder til side denne gang!\p"
    .string "Jeg hâber vi mødes igen…$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "Jeg kender dig!\n"
    .string "Du ødelagde vores planer ved MT. MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "Brændt igen!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "Har du noget imod TEAM\n"
    .string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "Hvordan kan du ikke se skønheden i\n"
    .string "vores ondskab?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "Ayaya!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "BOSS!\n"
    .string "Undskyld at jeg svigtede dig!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "Elevatoren virker ikke?\n"
    .string "Hvem har LIFT KEY?$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "Nej!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "Aah nej!\n"
    .string "Jeg tabte LIFT KEY!$"
