SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
    .string "Jeg kan ikke finde ud af hvordan jeg\n"
    .string "skal komme ind.$"

SixIsland_RuinValley_Text_IFoundThisPlace::
    .string "Lad mig fortälle dig, jeg fandt dette\n"
    .string "sted.\p"
    .string "Se ikke sâ misundelig ud, vil du?$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
    .string "Dören giver sig slet ikke.\n"
    .string "Tjek den grundigere?$"

SixIsland_RuinValley_Text_LeftDoorAlone::
    .string "{PLAYER} lod dören väre i fred.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
    .string "Ved närmere eftersyn er der\n"
    .string "flere prikker pâ dören…$"

SixIsland_RuinValley_Text_DoorIsOpen::
    .string "Dören er âben.$"

SixIsland_RuinValley_Text_StanlyIntro::
    .string "Der synes at väre mange hemmeligheder\n"
    .string "stadig ulöst i denne verden.$"

SixIsland_RuinValley_Text_StanlyDefeat::
    .string "Hmm…$"

SixIsland_RuinValley_Text_StanlyPostBattle::
    .string "Jeg foreslâr at du ogsâ tänker\n"
    .string "pâ hemmelighederne og mysterierne\l"
    .string "i vores verden én gang om dagen.$"

SixIsland_RuinValley_Text_FosterIntro::
    .string "Jeg er nysgerrig, hvad drev dig til\n"
    .string "at komme her?$"

SixIsland_RuinValley_Text_FosterDefeat::
    .string "Det er sâ länge siden jeg kämpede,\n"
    .string "mine instinkter er slöbe.$"

SixIsland_RuinValley_Text_FosterPostBattle::
    .string "Der er flere ruiner pâ\n"
    .string "SEVII ISLANDS.\p"
    .string "Störstedelen af dem er meget\n"
    .string "gamle.$"

SixIsland_RuinValley_Text_LarryIntro::
    .string "Det siges at der er mystiske\n"
    .string "sten pâ denne ö.\p"
    .string "Jeg mistänker at det har noget at\n"
    .string "göre med ruinerne her.$"

SixIsland_RuinValley_Text_LarryDefeat::
    .string "Aah, interessant.$"

SixIsland_RuinValley_Text_LarryPostBattle::
    .string "De ruiner derovre…\p"
    .string "Jeg har ikke haft held til at finde\n"
    .string "ud af hvordan jeg kommer ind.$"

SixIsland_RuinValley_Text_DarylIntro::
    .string "En kamp med dig, sâ höjt oppe!$"

SixIsland_RuinValley_Text_DarylDefeat::
    .string "Aah, hjertesorg at tabe sâ\n"
    .string "nemt til dig!$"

SixIsland_RuinValley_Text_DarylPostBattle::
    .string "Oplev gläden ved at klatre!$"

SixIsland_RuinValley_Text_HectorIntro::
    .string "Jeg kender landet omkring disse\n"
    .string "egne ret godt.$"

SixIsland_RuinValley_Text_HectorDefeat::
    .string "Du behöver ikke at väre sâ pâträngende.\n"
    .string "Jeg fortäller dig gerne.$"

SixIsland_RuinValley_Text_HectorPostBattle::
    .string "Dören til ruinerne…\n"
    .string "Den har disse underlige mönstre\l"
    .string "graveret pâ udsiden.\p"
    .string "Jeg ved ikke hvad de betyder.$"

