SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
    .string "Jeg kan ikke finde ud af hvordan jeg\n"
    .string "skal komme ind.$"

SixIsland_RuinValley_Text_IFoundThisPlace::
    .string "Lad mig fortaelle dig, jeg fandt dette\n"
    .string "sted.\p"
    .string "Se ikke saa misundelig ud, vil du?$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
    .string "Doeren giver sig slet ikke.\n"
    .string "Tjek den grundigere?$"

SixIsland_RuinValley_Text_LeftDoorAlone::
    .string "{PLAYER} lod doeren vaere i fred.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
    .string "Ved naermere eftersyn er der\n"
    .string "flere prikker paa doeren…$"

SixIsland_RuinValley_Text_DoorIsOpen::
    .string "Doeren er aaben.$"

SixIsland_RuinValley_Text_StanlyIntro::
    .string "Der synes at vaere mange hemmeligheder\n"
    .string "stadig uloest i denne verden.$"

SixIsland_RuinValley_Text_StanlyDefeat::
    .string "Hmm…$"

SixIsland_RuinValley_Text_StanlyPostBattle::
    .string "Jeg foreslaar at du ogsaa taenker\n"
    .string "paa hemmelighederne og mysterierne\l"
    .string "i vores verden én gang om dagen.$"

SixIsland_RuinValley_Text_FosterIntro::
    .string "Jeg er nysgerrig, hvad drev dig til\n"
    .string "at komme her?$"

SixIsland_RuinValley_Text_FosterDefeat::
    .string "Det er saa laenge siden jeg kaempede,\n"
    .string "mine instinkter er sloebe.$"

SixIsland_RuinValley_Text_FosterPostBattle::
    .string "Der er flere ruiner paa\n"
    .string "SEVII ISLANDS.\p"
    .string "Stoerstedelen af dem er meget\n"
    .string "gamle.$"

SixIsland_RuinValley_Text_LarryIntro::
    .string "Det siges at der er mystiske\n"
    .string "sten paa denne oe.\p"
    .string "Jeg mistaenker at det har noget at\n"
    .string "goere med ruinerne her.$"

SixIsland_RuinValley_Text_LarryDefeat::
    .string "Aah, interessant.$"

SixIsland_RuinValley_Text_LarryPostBattle::
    .string "De ruiner derovre…\p"
    .string "Jeg har ikke haft held til at finde\n"
    .string "ud af hvordan jeg kommer ind.$"

SixIsland_RuinValley_Text_DarylIntro::
    .string "En kamp med dig, saa hoejt oppe!$"

SixIsland_RuinValley_Text_DarylDefeat::
    .string "Aah, hjertesorg at tabe saa\n"
    .string "nemt til dig!$"

SixIsland_RuinValley_Text_DarylPostBattle::
    .string "Oplev glaeden ved at klatre!$"

SixIsland_RuinValley_Text_HectorIntro::
    .string "Jeg kender landet omkring disse\n"
    .string "egne ret godt.$"

SixIsland_RuinValley_Text_HectorDefeat::
    .string "Du behoever ikke at vaere saa paatraengende.\n"
    .string "Jeg fortaeller dig gerne.$"

SixIsland_RuinValley_Text_HectorPostBattle::
    .string "Doeren til ruinerne…\n"
    .string "Den har disse underlige moenstre\l"
    .string "graveret paa udsiden.\p"
    .string "Jeg ved ikke hvad de betyder.$"

