SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
    .string "Jeg kan ikke finde ud af hvordan jeg\n"
    .string "skal komme ind.$"

SixIsland_RuinValley_Text_IFoundThisPlace::
    .string "Lad mig fortælle dig, jeg fandt dette\n"
    .string "sted.\p"
    .string "Se ikke sâ misundelig ud, vil du?$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
    .string "Døren giver sig slet ikke.\n"
    .string "Tjek den grundigere?$"

SixIsland_RuinValley_Text_LeftDoorAlone::
    .string "{PLAYER} lod døren være i fred.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
    .string "Ved nærmere eftersyn er der\n"
    .string "flere prikker pâ døren…$"

SixIsland_RuinValley_Text_DoorIsOpen::
    .string "Døren er âben.$"

SixIsland_RuinValley_Text_StanlyIntro::
    .string "Der synes at være mange hemmeligheder\n"
    .string "stadig uløst i denne verden.$"

SixIsland_RuinValley_Text_StanlyDefeat::
    .string "Hmm…$"

SixIsland_RuinValley_Text_StanlyPostBattle::
    .string "Jeg foreslâr at du ogsâ tænker\n"
    .string "pâ hemmelighederne og mysterierne\l"
    .string "i vores verden én gang om dagen.$"

SixIsland_RuinValley_Text_FosterIntro::
    .string "Jeg er nysgerrig, hvad drev dig til\n"
    .string "at komme her?$"

SixIsland_RuinValley_Text_FosterDefeat::
    .string "Det er sâ længe siden jeg kæmpede,\n"
    .string "mine instinkter er sløbe.$"

SixIsland_RuinValley_Text_FosterPostBattle::
    .string "Der er flere ruiner pâ\n"
    .string "SEVII ISLANDS.\p"
    .string "Størstedelen af dem er meget\n"
    .string "gamle.$"

SixIsland_RuinValley_Text_LarryIntro::
    .string "Det siges at der er mystiske\n"
    .string "sten pâ denne ø.\p"
    .string "Jeg mistænker at det har noget at\n"
    .string "gøre med ruinerne her.$"

SixIsland_RuinValley_Text_LarryDefeat::
    .string "Aah, interessant.$"

SixIsland_RuinValley_Text_LarryPostBattle::
    .string "De ruiner derovre…\p"
    .string "Jeg har ikke haft held til at finde\n"
    .string "ud af hvordan jeg kommer ind.$"

SixIsland_RuinValley_Text_DarylIntro::
    .string "En kamp med dig, sâ højt oppe!$"

SixIsland_RuinValley_Text_DarylDefeat::
    .string "Aah, hjertesorg at tabe sâ\n"
    .string "nemt til dig!$"

SixIsland_RuinValley_Text_DarylPostBattle::
    .string "Oplev glæden ved at klatre!$"

SixIsland_RuinValley_Text_HectorIntro::
    .string "Jeg kender landet omkring disse\n"
    .string "egne ret godt.$"

SixIsland_RuinValley_Text_HectorDefeat::
    .string "Du behøver ikke at være sâ pâtrængende.\n"
    .string "Jeg fortæller dig gerne.$"

SixIsland_RuinValley_Text_HectorPostBattle::
    .string "Døren til ruinerne…\n"
    .string "Den har disse underlige mønstre\l"
    .string "graveret pâ udsiden.\p"
    .string "Jeg ved ikke hvad de betyder.$"

