SafariZone_North_Text_RestHouse::
    .string "HVILESTED$"

SafariZone_North_Text_SecretHouseStillAhead::
    .string "TRAINER TIPS\p"
    .string "DET HEMMELIGE HUS er stadig foran.$"

SafariZone_North_Text_Area2::
    .string "OMRAADE 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "TRAINER TIPS\p"
    .string "POKeMON gemmer sig i hoejt graes.\p"
    .string "Snoev gennem graesomraader for at\n"
    .string "jage dem frem.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .string "TRAINER TIPS\p"
    .string "Vind en gratis HM for at finde\n"
    .string "DET HEMMELIGE HUS.$"
