VictoryRoad_2F_Text_DawsonIntro::
    .string "Hvis du kan komme igennem her,\n"
    .string "kan du moede ELITE FOUR.$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "Nej!\n"
    .string "Utroligt!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "Jeg kan slaa dig naar det gaelder\n"
    .string "viden om POKeMON!$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "Dette er VICTORY ROAD.\n"
    .string "Det er den endelige proeve for TRAeNERE!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "Atcho!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "Hvis du staar fast, proev at flytte nogle\n"
    .string "kampesten.$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "Ah, saa du vil udfordre\n"
    .string "ELITE FOUR?$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "Du fik mig!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "{RIVAL} kom ogsaa igennem her.$"

VictoryRoad_2F_Text_VincentIntro::
    .string "Kom an!\n"
    .string "Jeg banker dig!$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "Jeg blev banket!$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "Du har fortjent retten til at vaere paa\n"
    .string "VICTORY ROAD…$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "Er VICTORY ROAD for haard?$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "Godt gaaet!$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "Mange TRAeNERE opgiver deres\n"
    .string "udfordring her og tager hjem.$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "Gyaoo!$"

