SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
    .string "SAFARI ZONE er kaempestor, vil du\n"
    .string "ikke sige?\p"
    .string "FUCHSIAs GYM LEADER, KOGA,\n"
    .string "patruljerer omraadet lejlighedsvis.\p"
    .string "Takket vaere ham kan vi lege her\n"
    .string "i vidende at vi er i sikkerhed.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .string "At kaste STEN efter POKeMON kan\n"
    .string "goere at de loeb vaek, men de er\l"
    .string "lettere at fange.$"

SafariZone_West_Text_BaitMakesMonStickAround::
    .string "At bruge MAD goer POKeMON mere\n"
    .string "tilbojelige til at blive hvis de\l"
    .string "bliver optaget af at spise.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "Jeg vandrede meget, men jeg saa ikke\n"
    .string "nogen POKeMON jeg ville have.$"
