SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
    .string "SAFARI ZONE er kæmpestor, vil du\n"
    .string "ikke sige?\p"
    .string "FUCHSIAs GYM LEADER, KOGA,\n"
    .string "patruljerer omrâdet lejlighedsvis.\p"
    .string "Takket være ham kan vi lege her\n"
    .string "i vidende at vi er i sikkerhed.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .string "At kaste STEN efter POKéMON kan\n"
    .string "gøre at de løb væk, men de er\l"
    .string "lettere at fange.$"

SafariZone_West_Text_BaitMakesMonStickAround::
    .string "At bruge MAD gør POKéMON mere\n"
    .string "tilbojelige til at blive hvis de\l"
    .string "bliver optaget af at spise.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "Jeg vandrede meget, men jeg sâ ikke\n"
    .string "nogen POKéMON jeg ville have.$"
