SSAnne_Deck_Text_ShipDepartingSoon::
    .string "Festen er forbi.\n"
    .string "Skibet afsejler snart.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .string "Puh!\n"
    .string "At skrubbe daek er haardt arbejde!$"

SSAnne_Deck_Text_FeelSeasick::
    .string "Urf… Jeg har det daarligt…\p"
    .string "Jeg blev soesyg, saa jeg gik ud for at\n"
    .string "faa lidt luft…$"

SSAnne_Deck_Text_EdmondIntro::
    .string "Hey, kammerat!\p"
    .string "Lad os lave en lille dans!$"

SSAnne_Deck_Text_EdmondDefeat::
    .string "Du er imponerende!$"

SSAnne_Deck_Text_EdmondPostBattle::
    .string "Hvor mange slags POKeMON tror du\n"
    .string "der er i denne store verden?$"

SSAnne_Deck_Text_TrevorIntro::
    .string "Ahoy!\n"
    .string "Er du soesyg?$"

SSAnne_Deck_Text_TrevorDefeat::
    .string "Jeg var bare uforsigtig!$"

SSAnne_Deck_Text_TrevorPostBattle::
    .string "Min far sagde der er 100 slags\n"
    .string "POKeMON. Jeg tror der er flere.$"

