SSAnne_Deck_Text_ShipDepartingSoon::
    .string "Festen er forbi.\n"
    .string "Skibet afsejler snart.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .string "Puh!\n"
    .string "At skrubbe däk er hârdt arbejde!$"

SSAnne_Deck_Text_FeelSeasick::
    .string "Urf… Jeg har det dârligt…\p"
    .string "Jeg blev sösyg, sâ jeg gik ud for at\n"
    .string "fâ lidt luft…$"

SSAnne_Deck_Text_EdmondIntro::
    .string "Hey, kammerat!\p"
    .string "Lad os lave en lille dans!$"

SSAnne_Deck_Text_EdmondDefeat::
    .string "Du er imponerende!$"

SSAnne_Deck_Text_EdmondPostBattle::
    .string "Hvor mange slags POKéMON tror du\n"
    .string "der er i denne store verden?$"

SSAnne_Deck_Text_TrevorIntro::
    .string "Ahoy!\n"
    .string "Er du sösyg?$"

SSAnne_Deck_Text_TrevorDefeat::
    .string "Jeg var bare uforsigtig!$"

SSAnne_Deck_Text_TrevorPostBattle::
    .string "Min far sagde der er 100 slags\n"
    .string "POKéMON. Jeg tror der er flere.$"

