FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "LORELEI: Hold dine beskidte hænder\n"
    .string "væk fra POKéMON i hulen!\p"
    .string "Gør som jeg siger, eller du får mig\n"
    .string "at gøre regnskab med!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Hold op, frue, og lad os være.\p"
    .string "Lad ikke dine briller dugge til!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "LORELEI: {PLAYER}?!\n"
    .string "Hvad laver du her?\p"
    .string "Nej, vi kan snakke senere.\n"
    .string "Lige nu har jeg brug for din hjælp.\p"
    .string "Hjælp mig med at smide de her\n"
    .string "dyrtyve ud før de gør mere.\p"
    .string "De har fanget POKéMON her og\n"
    .string "solgt dem!\p"
    .string "Er du klar?\n"
    .string "Du tager den der!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "H-hvad?!\p"
    .string "Hvem siger vi ikke må gøre hvad\n"
    .string "vi vil med de POKéMON vi fanger?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "Det havde vi ikke planlagt!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "LORELEI: Hmph.\n"
    .string "Sådan afskyeligt svage.\p"
    .string "Du!\n"
    .string "Sig mig!\p"
    .string "Hvor har I taget de fangede\n"
    .string "POKéMON hen?\p"
    .string "Jeg tilintetgør jeres netværk\n"
    .string "en gang for alle!$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "A-aldrig!\n"
    .string "Det siger jeg ikke!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "LORELEI: Hvis du ikke tilstår,\n"
    .string "fryser vi dig ned.\p"
    .string "Min LAPRAS er rasende over hvad\n"
    .string "I har gjort ved dens venner.\p"
    .string "Kør, LAPRAS!\n"
    .string "ICE BEAM…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "Wawåh! Okay!\n"
    .string "Jeg snakker!\p"
    .string "POKéMON er i ROCKET LAGERET\n"
    .string "på FIVE ISLAND.\p"
    .string "Der! Jeg sagde det!\n"
    .string "Vi går nu!\p"
    .string "…Men jeg tvivler på du nogensinde\n"
    .string "kommer ind i ROCKET LAGERET!\p"
    .string "Heheheheh!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, tak.\n"
    .string "Men det her er forfærdeligt…\p"
    .string "Jeg er født og opvokset her på\n"
    .string "disse øer.\p"
    .string "Jeg anede ikke at de forfærdelige\n"
    .string "kriminelle var løse her…$"

