FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "LORELEI: Hold dine beskidte haender\n"
    .string "vaek fra POKeMON i hulen!\p"
    .string "Goer som jeg siger, eller du faar mig\n"
    .string "at goere regnskab med!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Hold op, frue, og lad os vaere.\p"
    .string "Lad ikke dine briller dugge til!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "LORELEI: {PLAYER}?!\n"
    .string "Hvad laver du her?\p"
    .string "Nej, vi kan snakke senere.\n"
    .string "Lige nu har jeg brug for din hjaelp.\p"
    .string "Hjaelp mig med at smide de her\n"
    .string "dyrtyve ud foer de goer mere.\p"
    .string "De har fanget POKeMON her og\n"
    .string "solgt dem!\p"
    .string "Er du klar?\n"
    .string "Du tager den der!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "H-hvad?!\p"
    .string "Hvem siger vi ikke maa goere hvad\n"
    .string "vi vil med de POKeMON vi fanger?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "Det havde vi ikke planlagt!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "LORELEI: Hmph.\n"
    .string "Saadan afskyeligt svage.\p"
    .string "Du!\n"
    .string "Sig mig!\p"
    .string "Hvor har I taget de fangede\n"
    .string "POKeMON hen?\p"
    .string "Jeg tilintetgoer jeres netvaerk\n"
    .string "en gang for alle!$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "A-aldrig!\n"
    .string "Det siger jeg ikke!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "LORELEI: Hvis du ikke tilstaar,\n"
    .string "fryser vi dig ned.\p"
    .string "Min LAPRAS er rasende over hvad\n"
    .string "I har gjort ved dens venner.\p"
    .string "Koer, LAPRAS!\n"
    .string "ICE BEAM…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "Wawaah! Okay!\n"
    .string "Jeg snakker!\p"
    .string "POKeMON er i ROCKET LAGERET\n"
    .string "paa FIVE ISLAND.\p"
    .string "Der! Jeg sagde det!\n"
    .string "Vi gaar nu!\p"
    .string "…Men jeg tvivler paa du nogensinde\n"
    .string "kommer ind i ROCKET LAGERET!\p"
    .string "Heheheheh!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, tak.\n"
    .string "Men det her er forfaerdeligt…\p"
    .string "Jeg er foedt og opvokset her paa\n"
    .string "disse oeer.\p"
    .string "Jeg anede ikke at de forfaerdelige\n"
    .string "kriminelle var loese her…$"

