FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "LORELEI: Hold dine beskidte händer\n"
    .string "väk fra POKéMON i hulen!\p"
    .string "Gör som jeg siger, eller du fâr mig\n"
    .string "at göre regnskab med!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Hold op, frue, og lad os väre.\p"
    .string "Lad ikke dine briller dugge til!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "LORELEI: {PLAYER}?!\n"
    .string "Hvad laver du her?\p"
    .string "Nej, vi kan snakke senere.\n"
    .string "Lige nu har jeg brug for din hjälp.\p"
    .string "Hjälp mig med at smide de her\n"
    .string "dyrtyve ud för de gör mere.\p"
    .string "De har fanget POKéMON her og\n"
    .string "solgt dem!\p"
    .string "Er du klar?\n"
    .string "Du tager den der!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "H-hvad?!\p"
    .string "Hvem siger vi ikke mâ göre hvad\n"
    .string "vi vil med de POKéMON vi fanger?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "Det havde vi ikke planlagt!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "LORELEI: Hmph.\n"
    .string "Sâdan afskyeligt svage.\p"
    .string "Du!\n"
    .string "Sig mig!\p"
    .string "Hvor har I taget de fangede\n"
    .string "POKéMON hen?\p"
    .string "Jeg tilintetgör jeres netvärk\n"
    .string "en gang for alle!$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "A-aldrig!\n"
    .string "Det siger jeg ikke!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "LORELEI: Hvis du ikke tilstâr,\n"
    .string "fryser vi dig ned.\p"
    .string "Min LAPRAS er rasende over hvad\n"
    .string "I har gjort ved dens venner.\p"
    .string "Kör, LAPRAS!\n"
    .string "ICE BEAM…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "Wawâh! Okay!\n"
    .string "Jeg snakker!\p"
    .string "POKéMON er i ROCKET LAGERET\n"
    .string "pâ FIVE ISLAND.\p"
    .string "Der! Jeg sagde det!\n"
    .string "Vi gâr nu!\p"
    .string "…Men jeg tvivler pâ du nogensinde\n"
    .string "kommer ind i ROCKET LAGERET!\p"
    .string "Heheheheh!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, tak.\n"
    .string "Men det her er forfärdeligt…\p"
    .string "Jeg er födt og opvokset her pâ\n"
    .string "disse öer.\p"
    .string "Jeg anede ikke at de forfärdelige\n"
    .string "kriminelle var löse her…$"

