CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "De elendige ROCKETs!\p"
    .string "Se hvad de har gjort ved mit\n"
    .string "hus!\p"
    .string "De stjal en TM til at laere\n"
    .string "POKeMON at DIGge huller!\p"
    .string "Jeg ville bruge den paa en\n"
    .string "MANKEY eller en SANDSHREW…\p"
    .string "Det kostede mig en formue!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "Jeg taenker hvad der er tabt er tabt.\p"
    .string "Jeg besluttede at laere DIGLETT at\n"
    .string "DIGge uden en TM.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "TEAM ROCKET maa forsoege at DIGge\n"
    .string "sig til noget slemt!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "TEAM ROCKET efterlod en udvej!$"
