LavenderTown_House1_Text_Cubone::
    .string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "De forfærdelige ROCKET!\n"
    .string "De fortjener ingen nâde!\p"
    .string "Den stakkels CUBONEs mor…\p"
    .string "Den blev dræbt under flugt fra\n"
    .string "TEAM ROCKET.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "Spøgelsen fra POKéMON TOWER er\n"
    .string "væk!\p"
    .string "Nogen mâ have beroliget dens\n"
    .string "rastløse ând!$"

