LavenderTown_House1_Text_Cubone::
    .string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "De forfaerdelige ROCKET!\n"
    .string "De fortjener ingen naade!\p"
    .string "Den stakkels CUBONEs mor…\p"
    .string "Den blev draebt under flugt fra\n"
    .string "TEAM ROCKET.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "Spoegelsen fra POKeMON TOWER er\n"
    .string "vaek!\p"
    .string "Nogen maa have beroliget dens\n"
    .string "rastloese aand!$"

