LavenderTown_House1_Text_Cubone::
    .string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "De forfärdelige ROCKET!\n"
    .string "De fortjener ingen nâde!\p"
    .string "Den stakkels CUBONEs mor…\p"
    .string "Den blev dräbt under flugt fra\n"
    .string "TEAM ROCKET.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "Spögelsen fra POKéMON TOWER er\n"
    .string "väk!\p"
    .string "Nogen mâ have beroliget dens\n"
    .string "rastlöse ând!$"

