SaffronCity_House_Text_DontLookAtMyLetter::
    .string "…Tak for at du skrev.\n"
    .string "Jeg håber at se dig snart!\p"
    .string "…Hey!\n"
    .string "Kig ikke på mit brev!$"

SaffronCity_House_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "COPYCAT er sød!\n"
    .string "Jeg skaffer hende en POKé DOLL.$"

SaffronCity_House_Text_ExplainPPUp::
    .string "Jeg fik en PP UP i gave.\p"
    .string "Den bruges til at oge PP for\n"
    .string "et POKéMONs angreb.\p"
    .string "Jeg bør bruge den på et kræftigt\n"
    .string "angreb med kun få PP.$"

