SaffronCity_House_Text_DontLookAtMyLetter::
    .string "…Tak for at du skrev.\n"
    .string "Jeg haaber at se dig snart!\p"
    .string "…Hey!\n"
    .string "Kig ikke paa mit brev!$"

SaffronCity_House_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "COPYCAT er soed!\n"
    .string "Jeg skaffer hende en POKe DOLL.$"

SaffronCity_House_Text_ExplainPPUp::
    .string "Jeg fik en PP UP i gave.\p"
    .string "Den bruges til at oge PP for\n"
    .string "et POKeMONs angreb.\p"
    .string "Jeg boer bruge den paa et kraeftigt\n"
    .string "angreb med kun faa PP.$"

