SaffronCity_House_Text_DontLookAtMyLetter::
    .string "…Tak for at du skrev.\n"
    .string "Jeg hâber at se dig snart!\p"
    .string "…Hey!\n"
    .string "Kig ikke pâ mit brev!$"

SaffronCity_House_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "COPYCAT er söd!\n"
    .string "Jeg skaffer hende en POKe DOLL.$"

SaffronCity_House_Text_ExplainPPUp::
    .string "Jeg fik en PP UP i gave.\p"
    .string "Den bruges til at oge PP for\n"
    .string "et POKéMONs angreb.\p"
    .string "Jeg bör bruge den pâ et kräftigt\n"
    .string "angreb med kun fâ PP.$"

