SSAnne_2F_Room2_Text_BrooksIntro::
    .string "At konkurrere mod de unge holder\n"
    .string "mig ung.$"

SSAnne_2F_Room2_Text_BrooksDefeat::
    .string "God kamp!\n"
    .string "Aah, jeg föler mig ung igen!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .string "For femten âr siden ville\n"
    .string "jeg have vundet!$"

SSAnne_2F_Room2_Text_DaleIntro::
    .string "Se hvad jeg fiskede op!$"

SSAnne_2F_Room2_Text_DaleDefeat::
    .string "Jeg er tom!$"

SSAnne_2F_Room2_Text_DalePostBattle::
    .string "Fest?\p"
    .string "Krydstogtskibets fest burde väre\n"
    .string "forbi nu.$"

