FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .string "LORELEI: Der er noget der tynger\n"
    .string "meget paa mit sind.\p"
    .string "Hvis der skete noget paa oeen hvor\n"
    .string "jeg er foedt…\p"
    .string "Ville jeg ikke vide det hvis jeg var\n"
    .string "i POKeMON LEAGUE.\p"
    .string "Jeg spekulerer paa om det ville\n"
    .string "goere mig uansvarlig over for mit hjem…$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
    .string "LORELEI: Saa du loeste alle\n"
    .string "problemerne her?\p"
    .string "Det er vidunderligt.\p"
    .string "Det betyder der ikke er nogen grund\n"
    .string "til at jeg er her hele tiden.\p"
    .string "Tak…\p"
    .string "Jeg vender tilbage til POKeMON\n"
    .string "LEAGUE om kort tid.$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .string "Jeg ved ikke hvad der sker i\n"
    .string "fremtiden, men…\p"
    .string "Jeg goer hvad jeg kan her og nu.\n"
    .string "Det er alt jeg kan.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "POKeMON-stuffedukker i massevis!$"

