FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .string "LORELEI: Der er noget der tynger\n"
    .string "meget pâ mit sind.\p"
    .string "Hvis der skete noget pâ öen hvor\n"
    .string "jeg er födt…\p"
    .string "Ville jeg ikke vide det hvis jeg var\n"
    .string "i POKéMON LEAGUE.\p"
    .string "Jeg spekulerer pâ om det ville\n"
    .string "göre mig uansvarlig over for mit hjem…$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
    .string "LORELEI: Sâ du löste alle\n"
    .string "problemerne her?\p"
    .string "Det er vidunderligt.\p"
    .string "Det betyder der ikke er nogen grund\n"
    .string "til at jeg er her hele tiden.\p"
    .string "Tak…\p"
    .string "Jeg vender tilbage til POKéMON\n"
    .string "LEAGUE om kort tid.$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .string "Jeg ved ikke hvad der sker i\n"
    .string "fremtiden, men…\p"
    .string "Jeg gör hvad jeg kan her og nu.\n"
    .string "Det er alt jeg kan.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "POKéMON-stuffedukker i massevis!$"

