Route4_Text_TrippedOverGeodude::
    .string "Av! Jeg snublede over et stenede\n"
    .string "POKeMON, GEODUDE!$"

Route4_Text_CrissyIntro::
    .string "Jeg kom til MT. MOON for at lede\n"
    .string "efter svampe-POKeMON.$"

Route4_Text_CrissyDefeat::
    .string "Efter alt hvad jeg gjorde for at\n"
    .string "fange dem!$"

Route4_Text_CrissyPostBattle::
    .string "Der er maaske ikke flere svampe\n"
    .string "her.\p"
    .string "Jeg tror jeg fik dem alle.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON\n"
    .string "Tunnelindgang$"

Route4_Text_RouteSign::
    .string "ROUTE 4\n"
    .string "MT. MOON - CERULEAN CITY$"

Text_MegaPunchTeach::
    .string "Et slag af buldrende vildskab!\p"
    .string "Proppet med oedelaeggende kraft!\p"
    .string "Naar chipsene er nede, er\n"
    .string "MEGA PUNCH det ultimative angreb!\l"
    .string "Det er du enig i, ikke?\p"
    .string "Nu!\n"
    .string "Lad mig laere det til din POKeMON!$"

Text_MegaPunchDeclined::
    .string "Du kommer tilbage naar du forstaar\n"
    .string "vaerdien af MEGA PUNCH.$"

Text_MegaPunchWhichMon::
    .string "Fint!\n"
    .string "Hvilken POKeMON skal laere det?$"

Text_MegaPunchTaught::
    .string "Nu er vi kammerater i slagets kunst!\p"
    .string "Du boer gaa foer du bliver set af den\n"
    .string "vildledte fjols der kun traener\l"
    .string "sine dumme spark derovre.$"

Text_MegaKickTeach::
    .string "Et spark af brutal vildskab!\p"
    .string "Proppet med oedelaeggende kraft!\p"
    .string "Naar du kommer til sagen, er\n"
    .string "MEGA KICK det ultimative angreb!\l"
    .string "Er du ikke enig?\p"
    .string "Okay!\n"
    .string "Jeg laerer det til din POKeMON!$"

Text_MegaKickDeclined::
    .string "Du kommer kravlende tilbage naar du\n"
    .string "indser vaerdien af MEGA KICK.$"

Text_MegaKickWhichMon::
    .string "Okay!\n"
    .string "Hvilken POKeMON vil laere det?$"

Text_MegaKickTaught::
    .string "Nu er vi sjaelefaeller i sparkets kunst!\p"
    .string "Du boer lobe foer du bliver set af den\n"
    .string "vildledte torsk der kun traener\l"
    .string "simpelt slag derovre.$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Oh wow, det er BOULDERBADGE!\n"
    .string "Du fik den fra BROCK, ikke?\p"
    .string "BROCK er sej. Han er ikke bare haard.\n"
    .string "Folk kan lide og respekterer ham.\p"
    .string "Jeg vil blive en GYM LEADER\n"
    .string "som ham.$"
