Route4_Text_TrippedOverGeodude::
    .string "Av! Jeg snublede over et stenede\n"
    .string "POKéMON, GEODUDE!$"

Route4_Text_CrissyIntro::
    .string "Jeg kom til MT. MOON for at lede\n"
    .string "efter svampe-POKéMON.$"

Route4_Text_CrissyDefeat::
    .string "Efter alt hvad jeg gjorde for at\n"
    .string "fange dem!$"

Route4_Text_CrissyPostBattle::
    .string "Der er mâske ikke flere svampe\n"
    .string "her.\p"
    .string "Jeg tror jeg fik dem alle.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON\n"
    .string "Tunnelindgang$"

Route4_Text_RouteSign::
    .string "ROUTE 4\n"
    .string "MT. MOON - CERULEAN CITY$"

Text_MegaPunchTeach::
    .string "Et slag af buldrende vildskab!\p"
    .string "Proppet med ödeläggende kraft!\p"
    .string "Nâr chipsene er nede, er\n"
    .string "MEGA PUNCH det ultimative angreb!\l"
    .string "Det er du enig i, ikke?\p"
    .string "Nu!\n"
    .string "Lad mig läre det til din POKéMON!$"

Text_MegaPunchDeclined::
    .string "Du kommer tilbage nâr du forstâr\n"
    .string "värdien af MEGA PUNCH.$"

Text_MegaPunchWhichMon::
    .string "Fint!\n"
    .string "Hvilken POKéMON skal läre det?$"

Text_MegaPunchTaught::
    .string "Nu er vi kammerater i slagets kunst!\p"
    .string "Du bör gâ för du bliver set af den\n"
    .string "vildledte fjols der kun träner\l"
    .string "sine dumme spark derovre.$"

Text_MegaKickTeach::
    .string "Et spark af brutal vildskab!\p"
    .string "Proppet med ödeläggende kraft!\p"
    .string "Nâr du kommer til sagen, er\n"
    .string "MEGA KICK det ultimative angreb!\l"
    .string "Er du ikke enig?\p"
    .string "Okay!\n"
    .string "Jeg lärer det til din POKéMON!$"

Text_MegaKickDeclined::
    .string "Du kommer kravlende tilbage nâr du\n"
    .string "indser värdien af MEGA KICK.$"

Text_MegaKickWhichMon::
    .string "Okay!\n"
    .string "Hvilken POKéMON vil läre det?$"

Text_MegaKickTaught::
    .string "Nu er vi själefäller i sparkets kunst!\p"
    .string "Du bör lobe för du bliver set af den\n"
    .string "vildledte torsk der kun träner\l"
    .string "simpelt slag derovre.$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Oh wow, det er BOULDERBADGE!\n"
    .string "Du fik den fra BROCK, ikke?\p"
    .string "BROCK er sej. Han er ikke bare hârd.\n"
    .string "Folk kan lide og respekterer ham.\p"
    .string "Jeg vil blive en GYM LEADER\n"
    .string "som ham.$"
