VermilionCity_Text_GrimerMultipliesInSludge::
    .string "Vi er omhyggelige med forurening her.\p"
    .string "Vi har hört at GRIMER formerer sig i\n"
    .string "giftigt slam.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "Sâ du S.S. ANNE fortöjet\n"
    .string "i havnen?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "Sâ S.S. ANNE er afsejlet?\p"
    .string "Den kommer tilbage til VERMILION omkring\n"
    .string "samme tid näste âr.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "Jeg bygger et hus pâ denne\n"
    .string "grund. Jeg ejer det hele.\p"
    .string "Min POKeMON stampede jorden\n"
    .string "for at lägge fundamentet.$"

VermilionCity_Text_Machop::
    .string "MACHOP: Guoh! Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "En MACHOP stampede jorden flad.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "S.S. ANNE er et berömt luksus-\n"
    .string "krydstogtskib.\p"
    .string "Det besöger VERMILION en gang om âret.$"

VermilionCity_Text_CitySign::
    .string "VERMILION CITY\n"
    .string "Havnen med de udsögte solnedgange$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "OPSLAG!\p"
    .string "ROUTE 12 kan väre blokeret af en\n"
    .string "sovende POKeMON.\p"
    .string "Kör omvej gennem ROCK TUNNEL til\n"
    .string "LAVENDER TOWN.\p"
    .string "VERMILION POLITI$"

VermilionCity_Text_PokemonFanClubSign::
    .string "POKeMON FAN KLUB\n"
    .string "Alle POKeMON-fans velkomne!$"

VermilionCity_Text_GymSign::
    .string "VERMILION CITY POKeMON GYM\n"
    .string "LEDER: LT. SURGE\l"
    .string "Den amerikanske lynkaster!$"

VermilionCity_Text_VermilionHarbor::
    .string "VERMILION HAVN$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "Velkommen om bord pâ S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "Velkommen til S.S. ANNE!\p"
    .string "Undskyld, har du en billet?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER} viste S.S. BILLETTEN!\p"
    .string "{FONT_MALE}Perfekt!\n"
    .string "Velkommen om bord pâ S.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_NORMAL}{PLAYER} har ikke den nödvendige\n"
    .string "S.S. BILLET.\p"
    .string "{FONT_MALE}Beklager!\p"
    .string "Du skal bruge en billet for at komme om bord.$"

VermilionCity_Text_TheShipSetSail::
    .string "Skibet sejlede.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "Ah, du har et TRI-PASS.\p"
    .string "Vil du gâ om bord pâ\n"
    .string "en SEAGALLOP färge?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Okay, alt er i orden.\p"
    .string "SEAGALLOP HI-SPEED 7 afsejler\n"
    .string "straks.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "Ah, du har et RAINBOW PASS.\p"
    .string "Vil du gâ om bord pâ\n"
    .string "en SEAGALLOP färge?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Aah! Det er en MYSTICTICKET!\n"
    .string "Det er virkelig själdent.\p"
    .string "Vi tager dig gerne til\n"
    .string "NAVEL ROCK nâr som helst.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Aah! Det er en AURORATICKET!\n"
    .string "Det er virkelig själdent.\p"
    .string "Vi tager dig gerne til\n"
    .string "BIRTH ISLAND nâr som helst.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Vil du gâ om bord pâ\n"
    .string "en SEAGALLOP färge?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Okay, alt er i orden for at du kan\n"
    .string "gâ om bord pâ en speciel färge.\p"
    .string "SEAGALLOP HI-SPEED 10 afsejler\n"
    .string "straks.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Okay, alt er i orden for at du kan\n"
    .string "gâ om bord pâ en speciel färge.\p"
    .string "SEAGALLOP HI-SPEED 12 afsejler\n"
    .string "straks.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Aah, hej {PLAYER}!\n"
    .string "Hvordan har du det?\p"
    .string "Det er mig, en af PROF. OAKs assistenter.\p"
    .string "Mödte du den anden assistent?\p"
    .string "Han havde en pakke fra PROF. OAK\n"
    .string "til dig, {PLAYER}.\p"
    .string "Han sagde han ville lede efter dig omkring\n"
    .string "ROUTE 2, {PLAYER}.\p"
    .string "Hvis du er i ROUTE 2-omrâdet,\n"
    .string "sâ led venligst efter ham.$"

