@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
    .string "Hej!\p"
    .string "Velkommen til TRAINER TOWER hvor\n"
    .string "TRAINERS samles fra hele verden!$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
    .string "TRAINERS fra hele verden\n"
    .string "samles her for at kaempe.\p"
    .string "Lad mig se…\p"
    .string "Lige nu er der kun TRAINERS\n"
    .string "op til etage {STR_VAR_1}.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
    .string "TRAINERS venter paa din\n"
    .string "udfordring op til ottende etage.$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
    .string "Vil du udfordre de\n"
    .string "ventende TRAINERS?$"

TrainerTower_Lobby_Text_StartClockGetSetGo::
    .string "Okay, jeg starter uret,\n"
    .string "saa giv den gas.\p"
    .string "Paa plads…\p"
    .string "Klar…\p"
    .string "Go!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
    .string "Besoeg os gerne igen!$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
    .string "Det var aergerligt.\p"
    .string "Jeg synes du lagde en enorm\n"
    .string "indsats i din kamp.\p"
    .string "Kom tilbage og proev igen!$"

TrainerTower_Lobby_Text_GiveItYourBest::
    .string "Jeg haaber du giver den bedste.$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
    .string "Naar TRAINERS skifter plads,\n"
    .string "kan det blive hektisk.\p"
    .string "For at undgaa stampede flyttede vi\n"
    .string "receptionsbordet herhen.\p"
    .string "Undskyld ulejligheden.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
    .string "Hej…\p"
    .string "Jeg er ejeren af dette TOWER…\p"
    .string "Hvor himlen svejfer over dette\n"
    .string "tag…\p"
    .string "Beroeringen af vinden heroppe…\p"
    .string "Alt er saa perfekt…\p"
    .string "Maaden du kaempede paa…\n"
    .string "Ogsaa det var perfektion…$"

TrainerTower_Roof_Text_ThisIsForYou::
    .string "Dette er til dig…$"

TrainerTower_Roof_Text_DoneItInRecordTime::
    .string "Aah!\n"
    .string "Fantastisk!\p"
    .string "Det er vidunderligt at du er\n"
    .string "kommet herop saa hurtigt.\p"
    .string "Faktum er at du har gjort det paa\n"
    .string "rekordtid…\p"
    .string "Jeg lader din rekord blive vist ved\n"
    .string "receptionsbordet.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
    .string "Du har taget dig god tid\n"
    .string "med at komme her…$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
    .string "Hvad jeg gerne vil se er en\n"
    .string "bedre tid fra dig…\p"
    .string "Jeg regner med dig.\p"
    .string "Indtil da, farvel…$"

TrainerTower_Text_XMinYZSec::
    .string "{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} sek.$"

TrainerTower_Lobby_Text_HereAreTheResults::
    .string "せいせきひょうです$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
    .string "Dette er en to-mod-to kamp.\p"
    .string "Du maa ikke kaempe medmindre du har\n"
    .string "mindst to POKeMON.$"

TrainerTower_Lobby_Text_ExplainTrainerTower::
    .string "Her i TRAINER TOWER er der en\n"
    .string "begivenhed kaldet TIME ATTACK.\p"
    .string "Du bliver tidsmaalt paa hvor hurtigt\n"
    .string "du kan komme fra receptionsbordet\l"
    .string "til EJEREN paa taget.\p"
    .string "De bedste tider bliver noteret paa\n"
    .string "Tidstavlen.\p"
    .string "Proev at konkurrere med venner om\n"
    .string "hvem der kan slaa den hurtigst.\p"
    .string "Du faar ikke nogen EXP. Point eller\n"
    .string "penge ved at besejre TRAINERS her.$"

TrainerTower_Lobby_Text_ThanksForCompeting::
    .string "Tak fordi du deltog!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
    .string "Jeg er her for at se hvor god jeg er.\p"
    .string "Jeg spekulerer paa hvilke slags\n"
    .string "TRAINERS der venter paa mig?\p"
    .string "Det er nervepirrende!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
    .string "Gisp, gisp…\n"
    .string "Gisp…\p"
    .string "Glem kamp! Disse trapper…\n"
    .string "De er haardere end nogen kamp…$"

