PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "POKeMON lärer nye teknikker\n"
    .string "nâr de vokser.\p"
    .string "Men nogle träk skal läres dem\n"
    .string "af mennesker.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "En POKeMON bliver nemmere at\n"
    .string "fange hvis den har et statusproblem.\p"
    .string "Sövn, gift, bränd eller lamhed…\n"
    .string "De er alle effektive.\p"
    .string "Men at fange POKeMON er aldrig\n"
    .string "en sikker sag!$"
