PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "POKéMON lærer nye teknikker\n"
    .string "nâr de vokser.\p"
    .string "Men nogle træk skal læres dem\n"
    .string "af mennesker.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "En POKéMON bliver nemmere at\n"
    .string "fange hvis den har et statusproblem.\p"
    .string "Søvn, gift, brænd eller lamhed…\n"
    .string "De er alle effektive.\p"
    .string "Men at fange POKéMON er aldrig\n"
    .string "en sikker sag!$"
