PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Velkommen til POKeMON LEAGUE.\p"
    .string "Jeg er LORELEI fra ELITE FOUR.\p"
    .string "Ingen kan slâ mig nâr det gälder\n"
    .string "isse POKeMON.\p"
    .string "Frysende träk er kräftige.\p"
    .string "Dine POKeMON vil väre i min magt\n"
    .string "nâr de er frosset helt inde.\p"
    .string "Hahaha!\n"
    .string "Er du klar?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Velkommen til POKeMON LEAGUE.\p"
    .string "Jeg, LORELEI fra ELITE FOUR,\n"
    .string "er tilbage!\p"
    .string "Du ved hvordan det er.\n"
    .string "Ingen kan slâ mig nâr det gälder\l"
    .string "isse POKeMON.\p"
    .string "Frysende träk er kräftige.\p"
    .string "Dine POKeMON vil väre i min magt\n"
    .string "nâr de er frosset helt inde.\p"
    .string "Hahaha!\n"
    .string "Er du klar?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Sâdan burde det ikke väre!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "Du er bedre end jeg tröde.\n"
    .string "Fortsät.\p"
    .string "Du fik kun en smagspröve af\n"
    .string "POKeMON LEAGUEs styrke.$"
