PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Velkommen til POKéMON LEAGUE.\p"
    .string "Jeg er LORELEI fra ELITE FOUR.\p"
    .string "Ingen kan slâ mig nâr det gælder\n"
    .string "isse POKéMON.\p"
    .string "Frysende træk er kræftige.\p"
    .string "Dine POKéMON vil være i min magt\n"
    .string "nâr de er frosset helt inde.\p"
    .string "Hahaha!\n"
    .string "Er du klar?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Velkommen til POKéMON LEAGUE.\p"
    .string "Jeg, LORELEI fra ELITE FOUR,\n"
    .string "er tilbage!\p"
    .string "Du ved hvordan det er.\n"
    .string "Ingen kan slâ mig nâr det gælder\l"
    .string "isse POKéMON.\p"
    .string "Frysende træk er kræftige.\p"
    .string "Dine POKéMON vil være i min magt\n"
    .string "nâr de er frosset helt inde.\p"
    .string "Hahaha!\n"
    .string "Er du klar?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Sâdan burde det ikke være!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "Du er bedre end jeg trøde.\n"
    .string "Fortsæt.\p"
    .string "Du fik kun en smagsprøve af\n"
    .string "POKéMON LEAGUEs styrke.$"
