CeladonCity_Gym_Text_ErikaIntro::
    .string "Hej…\n"
    .string "Dejligt vejr, er det ikke?\l"
    .string "Det er saa behageligt…\p"
    .string "…Aah, kere…\n"
    .string "Jeg maa have doset. Velkommen.\p"
    .string "Mit navn er ERIKA.\n"
    .string "Jeg er LEADER af CELADON GYM.\p"
    .string "Jeg er elev i blomsterarrangement.\p"
    .string "Mine POKeMON er udelukkende af\n"
    .string "GRASS typen.\p"
    .string "…Aah, undskyld, jeg vidste ikke at\n"
    .string "du onskede at udfordre mig.\p"
    .string "Okay, men jeg taber ikke.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Aah!\n"
    .string "Jeg indroemmer nederlag.\l"
    .string "Du er bemaerkelsesvaerdigt staerk.\p"
    .string "Jeg maa overraekke dig\n"
    .string "RAINBOWBADGE.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "Du katalogiserer POKeMON?\n"
    .string "Jeg maa sige jeg er imponeret.\p"
    .string "Jeg ville aldrig samle POKeMON hvis\n"
    .string "de var uattraktive.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "RAINBOWBADGE faar POKeMON op til Lv. 50\n"
    .string "til at adlyde.\p"
    .string "Den tillader ogsaa POKeMON at bruge\n"
    .string "STRENGTH i og uden kamp.\p"
    .string "Tag venligst ogsaa dette med dig.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER} modtog TM19\n"
    .string "fra ERIKA.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "TM19 indeholder GIGA DRAIN.\p"
    .string "Halvdelen af skaden den goer\n"
    .string "draines for at helbrede din POKeMON.\p"
    .string "Vil du ikke give mig ret i at det er\n"
    .string "et vidunderligt trick?$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "Du boer lave plads til dette.$"

CeladonCity_Gym_Text_KayIntro::
    .string "Jeg boer fortaelle dig om denne GYM.\p"
    .string "Kun rigtige damer maa komme ind\n"
    .string "her!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "Du er for grov!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "Bleaah!\n"
    .string "Jeg haaber ERIKA udsletter dig!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Aah, velkommen.\n"
    .string "Jeg kede mig.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "Mit makeup!$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "GRASS-type POKeMON er haarde\n"
    .string "mod WATER typen.\p"
    .string "De har ogsaa fordel mod ROCK-\n"
    .string "og GROUND-type POKeMON.$"

CeladonCity_Gym_Text_TinaIntro::
    .string "…Kiggede du ikke ind her\n"
    .string "tidligere?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "Du er en ojenabner!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "Aah, du kiggede paa ERIKA…\n"
    .string "Du kiggede ikke paa mig…$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "Se, se!\n"
    .string "Se mine POKeMON!\p"
    .string "Jeg kan lide GRASS typen.\n"
    .string "Jeg kan lide at de er nemme at opdrage.$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "Nej!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "Vi bruger kun GRASS-type POKeMON i\n"
    .string "vores GYM.\p"
    .string "Hvorfor? Vi bruger dem ogsaa til\n"
    .string "blomsterarrangementer!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "Aah, hej!\p"
    .string "Vi kan ikke lide BUG- eller FIRE-type\n"
    .string "POKeMON herinde!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "Aah!\n"
    .string "Dig!$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "Vores LEADER ERIKA er maaske tavs,\n"
    .string "men hun er beroemt heroppe.$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Dejligt at moede dig.\n"
    .string "Min hobby er POKeMON traening.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "Aah!\n"
    .string "Splendidt!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "Jeg har en blind date paa vej.\n"
    .string "Jeg maa laere at vaere hoeflig,\l"
    .string "isaer hvis jeg skal kaempe.$"

CeladonCity_Gym_Text_MaryIntro::
    .string "Velkommen til CELADON GYM!\p"
    .string "Du boer ikke undervurdere\n"
    .string "de rare damer her.$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "Aah!\n"
    .string "Slaaet!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "Jeg tog ikke mine bedste POKeMON med.\n"
    .string "Vent til naeste gang!$"

CeladonCity_Gym_Text_GymStatue::
    .string "CELADON POKeMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "CELADON POKeMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
