CeladonCity_Gym_Text_ErikaIntro::
    .string "Hej…\n"
    .string "Dejligt vejr, er det ikke?\l"
    .string "Det er sâ behageligt…\p"
    .string "…Aah, kere…\n"
    .string "Jeg mâ have doset. Velkommen.\p"
    .string "Mit navn er ERIKA.\n"
    .string "Jeg er LEADER af CELADON GYM.\p"
    .string "Jeg er elev i blomsterarrangement.\p"
    .string "Mine POKeMON er udelukkende af\n"
    .string "GRASS typen.\p"
    .string "…Aah, undskyld, jeg vidste ikke at\n"
    .string "du onskede at udfordre mig.\p"
    .string "Okay, men jeg taber ikke.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Aah!\n"
    .string "Jeg indrömmer nederlag.\l"
    .string "Du er bemärkelsesvärdigt stärk.\p"
    .string "Jeg mâ overräkke dig\n"
    .string "RAINBOWBADGE.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "Du katalogiserer POKeMON?\n"
    .string "Jeg mâ sige jeg er imponeret.\p"
    .string "Jeg ville aldrig samle POKeMON hvis\n"
    .string "de var uattraktive.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "RAINBOWBADGE fâr POKeMON op til Lv. 50\n"
    .string "til at adlyde.\p"
    .string "Den tillader ogsâ POKeMON at bruge\n"
    .string "STRENGTH i og uden kamp.\p"
    .string "Tag venligst ogsâ dette med dig.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER} modtog TM19\n"
    .string "fra ERIKA.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "TM19 indeholder GIGA DRAIN.\p"
    .string "Halvdelen af skaden den gör\n"
    .string "draines for at helbrede din POKeMON.\p"
    .string "Vil du ikke give mig ret i at det er\n"
    .string "et vidunderligt trick?$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "Du bör lave plads til dette.$"

CeladonCity_Gym_Text_KayIntro::
    .string "Jeg bör fortälle dig om denne GYM.\p"
    .string "Kun rigtige damer mâ komme ind\n"
    .string "her!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "Du er for grov!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "Bleâh!\n"
    .string "Jeg hâber ERIKA udsletter dig!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Aah, velkommen.\n"
    .string "Jeg kede mig.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "Mit makeup!$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "GRASS-type POKeMON er hârde\n"
    .string "mod WATER typen.\p"
    .string "De har ogsâ fordel mod ROCK-\n"
    .string "og GROUND-type POKeMON.$"

CeladonCity_Gym_Text_TinaIntro::
    .string "…Kiggede du ikke ind her\n"
    .string "tidligere?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "Du er en ojenabner!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "Aah, du kiggede pâ ERIKA…\n"
    .string "Du kiggede ikke pâ mig…$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "Se, se!\n"
    .string "Se mine POKeMON!\p"
    .string "Jeg kan lide GRASS typen.\n"
    .string "Jeg kan lide at de er nemme at opdrage.$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "Nej!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "Vi bruger kun GRASS-type POKeMON i\n"
    .string "vores GYM.\p"
    .string "Hvorfor? Vi bruger dem ogsâ til\n"
    .string "blomsterarrangementer!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "Aah, hej!\p"
    .string "Vi kan ikke lide BUG- eller FIRE-type\n"
    .string "POKeMON herinde!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "Aah!\n"
    .string "Dig!$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "Vores LEADER ERIKA er mâske tavs,\n"
    .string "men hun er berömt heroppe.$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Dejligt at möde dig.\n"
    .string "Min hobby er POKeMON träning.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "Aah!\n"
    .string "Splendidt!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "Jeg har en blind date pâ vej.\n"
    .string "Jeg mâ läre at väre höflig,\l"
    .string "isär hvis jeg skal kämpe.$"

CeladonCity_Gym_Text_MaryIntro::
    .string "Velkommen til CELADON GYM!\p"
    .string "Du bör ikke undervurdere\n"
    .string "de rare damer her.$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "Aah!\n"
    .string "Slâet!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "Jeg tog ikke mine bedste POKeMON med.\n"
    .string "Vent til näste gang!$"

CeladonCity_Gym_Text_GymStatue::
    .string "CELADON POKeMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "CELADON POKeMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
