CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "Jeg er törst!\n"
    .string "Jeg vil have noget at drikke!\p"
    .string "{FONT_NORMAL}Giv hende en drink?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "Hvilken drink vil du give hende?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "Yay!\p"
    .string "FRESH WATER!\p"
    .string "Tak!\n"
    .string "Du mâ fâ dette fra mig!$"

Text_ReceivedItemFromLittleGirl::
    .string "{PLAYER} modtog en {STR_VAR_2}\n"
    .string "fra den lille pige.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .string "TM16 indeholder LIGHT SCREEN.\p"
    .string "Det er et trick der sväkker kräfterne\n"
    .string "af specialangreb fra din modstander.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "Yay!\p"
    .string "SODA POP!\p"
    .string "Tak!\n"
    .string "Du mâ fâ dette fra mig!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .string "TM20 indeholder SAFEGUARD.\p"
    .string "Det er et trick der forhindrer\n"
    .string "statusproblemer hos dine POKéMON.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "Yay!\p"
    .string "LEMONADE!\p"
    .string "Tak!\n"
    .string "Du mâ fâ dette fra mig!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .string "TM33 indeholder REFLECT.\p"
    .string "Det er et trick der sväkker kräfterne\n"
    .string "af fysiske angreb fra din modstander.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "Du har ikke plads til dette!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "Nej tak!\n"
    .string "Jeg er slet ikke törst alligevel!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .string "Min söster er TRAINER, tro det eller ej.\p"
    .string "Men hun er sâ umoden, hun driver\n"
    .string "mig til vanvid!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "Jeg er törst!\n"
    .string "Jeg vil have noget at drikke!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .string "ROOFTOP SQUARE:\n"
    .string "VENDING MACHINES$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "En salgsautomat!\n"
    .string "Hvad har den?$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "Ups, ikke nok penge!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "En dâse {STR_VAR_1} poppet ud!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "Der er ikke mere plads til ting!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "Ikke törst!$"
