SSAnne_1F_Room2_Text_TylerIntro::
    .string "Jeg elsker POKeMON!\n"
    .string "Goer du?$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "Wow!\n"
    .string "Du er fantastisk!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "Hoer, hoer!\n"
    .string "Lad mig vaere din ven, okay?\p"
    .string "Saa kan vi bytte POKeMON og\n"
    .string "saa videre.$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "Jeg har samlet disse POKeMON\n"
    .string "fra hele verden!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "Aah, nej!\n"
    .string "Jeg rejste verden rundt for dem!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "Du skadede mine stakkels POKeMON!\p"
    .string "Jeg kraever at du helbreder dem paa\n"
    .string "et POKeMON CENTER!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "Vi sejler rundt i verden,\n"
    .string "mine boern og jeg.$"

