SSAnne_1F_Room2_Text_TylerIntro::
    .string "Jeg elsker POKéMON!\n"
    .string "Gör du?$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "Wow!\n"
    .string "Du er fantastisk!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "Hör, hör!\n"
    .string "Lad mig väre din ven, okay?\p"
    .string "Sâ kan vi bytte POKéMON og\n"
    .string "sâ videre.$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "Jeg har samlet disse POKéMON\n"
    .string "fra hele verden!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "Aah, nej!\n"
    .string "Jeg rejste verden rundt for dem!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "Du skadede mine stakkels POKéMON!\p"
    .string "Jeg kräver at du helbreder dem pâ\n"
    .string "et POKéMON CENTER!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "Vi sejler rundt i verden,\n"
    .string "mine börn og jeg.$"

