FuchsiaCity_House2_Text_DoYouLikeToFish::
    .string "Jeg er FISKE-GURUENS äldre\n"
    .string "bror.\p"
    .string "Jeg elsker simpelthen at fiske!\n"
    .string "Jeg kan ikke undväre det.\p"
    .string "Sig mig, kan du lide at fiske?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
    .string "Stort! Jeg kan lide din stil.\n"
    .string "Jeg tror vi kan väre venner.\p"
    .string "Tag dette og fisk, unge ven!$"

FuchsiaCity_House2_Text_ReceivedGoodRod::
    .string "{PLAYER} modtog en GOOD ROD fra\n"
    .string "FISKE-GURUENS bror.$"

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons::
    .string "Fiskeri er en livsstil!\n"
    .string "Det er som den fineste pösi.\p"
    .string "En dârlig OLD ROD kunne kun fange\n"
    .string "MAGIKARP, ikke?\p"
    .string "Men med en GOOD ROD kan du fange\n"
    .string "meget bedre POKeMON.$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
    .string "Oeh…\n"
    .string "Sâ skuffende…$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
    .string "Hej med dig, {PLAYER}!\p"
    .string "Hvordan bider fiskene?$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
    .string "Oeh, nej!\p"
    .string "Jeg havde en gave til dig, men du\n"
    .string "har ikke plads til den!$"

