IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i blomst!\p"
    .string "Ved POKéMON LEAGUE møder du\n"
    .string "ELITE FOUR i træk.\p"
    .string "Taber du, skal du starte for\n"
    .string "fra igen!\p"
    .string "Dette er det!\n"
    .string "Kør pâ!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "Herfra møder du ELITE FOUR\n"
    .string "een ad gangen.\p"
    .string "Vinder du, âbner en dør til\n"
    .string "næste TRAINER. Held og lykke!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "Jeg er ked af at du har spildt din\n"
    .string "tid med at komme her.\p"
    .string "LORELEI fra ELITE FOUR er\n"
    .string "nemlig fraværende.\p"
    .string "Som følge heraf er POKéMON\n"
    .string "LEAGUE lukket for nu.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "AGATHAs SPØGELSES-type POKéMON er\n"
    .string "rædselsvækkende hârde.\p"
    .string "Jeg tog mine KAMP-type POKéMON\n"
    .string "og trænede dem maksimalt.\p"
    .string "Jeg gik mod AGATHA ret selvsikker,\n"
    .string "men hun bankede os.\p"
    .string "Den gamle dame har ogsâ et kort\n"
    .string "lunte.\p"
    .string "Det kræver ikke meget at fâ den\n"
    .string "skræmmente dame til at râbe.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Mâske er det i blodet at blive\n"
    .string "ELITE FOUR-medlem.\p"
    .string "Sâvidt jeg har hørt har LANCE en\n"
    .string "fætter der er GYM LEDER\l"
    .string "et sted langt væk.$"

