IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i blomst!\p"
    .string "Ved POKeMON LEAGUE moeder du\n"
    .string "ELITE FOUR i traek.\p"
    .string "Taber du, skal du starte for\n"
    .string "fra igen!\p"
    .string "Dette er det!\n"
    .string "Koer paa!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "Herfra moeder du ELITE FOUR\n"
    .string "een ad gangen.\p"
    .string "Vinder du, aabner en doer til\n"
    .string "naeste TRAINER. Held og lykke!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "Jeg er ked af at du har spildt din\n"
    .string "tid med at komme her.\p"
    .string "LORELEI fra ELITE FOUR er\n"
    .string "nemlig fravaerende.\p"
    .string "Som foelge heraf er POKeMON\n"
    .string "LEAGUE lukket for nu.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "AGATHAs SPOEGELSES-type POKeMON er\n"
    .string "raedselsvaekkende haarde.\p"
    .string "Jeg tog mine KAMP-type POKeMON\n"
    .string "og traenede dem maksimalt.\p"
    .string "Jeg gik mod AGATHA ret selvsikker,\n"
    .string "men hun bankede os.\p"
    .string "Den gamle dame har ogsaa et kort\n"
    .string "lunte.\p"
    .string "Det kraever ikke meget at faa den\n"
    .string "skraemmente dame til at raabe.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Maaske er det i blodet at blive\n"
    .string "ELITE FOUR-medlem.\p"
    .string "Saavidt jeg har hoert har LANCE en\n"
    .string "faetter der er GYM LEDER\l"
    .string "et sted langt vaek.$"

