IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i blomst!\p"
    .string "Ved POKéMON LEAGUE möder du\n"
    .string "ELITE FOUR i träk.\p"
    .string "Taber du, skal du starte for\n"
    .string "fra igen!\p"
    .string "Dette er det!\n"
    .string "Kör pâ!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "Herfra möder du ELITE FOUR\n"
    .string "een ad gangen.\p"
    .string "Vinder du, âbner en dör til\n"
    .string "näste TRAINER. Held og lykke!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "Jeg er ked af at du har spildt din\n"
    .string "tid med at komme her.\p"
    .string "LORELEI fra ELITE FOUR er\n"
    .string "nemlig fravärende.\p"
    .string "Som fölge heraf er POKéMON\n"
    .string "LEAGUE lukket for nu.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "AGATHAs SPÖGELSES-type POKéMON er\n"
    .string "rädselsväkkende hârde.\p"
    .string "Jeg tog mine KAMP-type POKéMON\n"
    .string "og tränede dem maksimalt.\p"
    .string "Jeg gik mod AGATHA ret selvsikker,\n"
    .string "men hun bankede os.\p"
    .string "Den gamle dame har ogsâ et kort\n"
    .string "lunte.\p"
    .string "Det kräver ikke meget at fâ den\n"
    .string "skrämmente dame til at râbe.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Mâske er det i blodet at blive\n"
    .string "ELITE FOUR-medlem.\p"
    .string "Sâvidt jeg har hört har LANCE en\n"
    .string "fätter der er GYM LEDER\l"
    .string "et sted langt väk.$"

