Text_MetronomeTeach::
    .string "Tch-tch-tch!\n"
    .string "Jeg lærer dig et smart trick.\p"
    .string "Lær det til en POKéMON, og se\n"
    .string "morøn udfolde sig!\p"
    .string "Det er et trick kaldt METRONOME.\n"
    .string "Lyder det tiltalende?$"

Text_MetronomeDeclined::
    .string "Jeg siger dig, det er meget moro!$"

Text_MetronomeWhichMon::
    .string "Okay!\n"
    .string "Hvilken POKéMON skal jeg lære?$"

Text_MetronomeTaught::
    .string "Tch-tch-tch!\n"
    .string "Det er lyden af en METRONOME.\p"
    .string "Det fâr din POKéMONs hjerne til at\n"
    .string "bruge tricks den ikke engang kender.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "Hej!\p"
    .string "Jeg er vigtig doktor.\n"
    .string "Ja, meget, sandelig.\p"
    .string "Her studerer jeg sjældne POKéMON-fossiler.\n"
    .string "Hele tiden studerer jeg.\p"
    .string "Dig!\n"
    .string "Har du et fossil til mig?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "Nej!\n"
    .string "Er for sørgeligt!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "Du er sent.\n"
    .string "Hvor var du?\p"
    .string "Dit fossil er tilbage til livet!\n"
    .string "Det var {STR_VAR_1} som jeg trøde!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER} modtog {STR_VAR_1}\n"
    .string "fra doktoren.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "Oh!\n"
    .string "Det er {STR_VAR_2}, det er!\p"
    .string "Det er fossil af {STR_VAR_1},\n"
    .string "en POKéMON der allerede er uddød!\p"
    .string "Min Genopstandelsesmaskine vil fâ\n"
    .string "den POKéMON til at leve igen!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "Sa!\n"
    .string "Du skynder dig og giver mig det!\p"
    .string "{FONT_NORMAL}{PLAYER} overrakte\n"
    .string "{STR_VAR_2} til den mærkelige doktor.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "Jeg tager lidt tid!\n"
    .string "Du gâr en tur et stykke tid!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "Aiyah!\n"
    .string "Du kommer igen!$"
