Route21_North_Text_RonaldIntro::
	.string "Vil du vide om fiskene bider?$"

Route21_North_Text_RonaldDefeat::
	.string "Pokker!$"

Route21_North_Text_RonaldPostBattle::
	.string "Jeg kan ikke fange noget godt.\n"
	.string "Ikke en eneste god POKeMON!$"

Route21_North_Text_WadeIntro::
	.string "Jeg fik et stort fangst!\n"
	.string "Vil du kämpe?$"

Route21_North_Text_WadeDefeat::
	.string "Heheh, MAGIKARP er bare ikke\n"
	.string "gode nok, vel?$"

Route21_North_Text_WadePostBattle::
	.string "Jeg synes kun jeg fanger MAGIKARP!$"

Route21_North_Text_SpencerIntro::
	.string "Havet renser min krop og själ!$"

Route21_North_Text_SpencerDefeat::
	.string "Ayah!$"

Route21_North_Text_SpencerPostBattle::
	.string "Havet er fantastisk, men jeg\n"
	.string "kan ogsâ lide bjergene.$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "Hvad er der galt med at jeg svömmer?$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "Billigt slag!$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "Jeg ligner hvad? Et oppustet däk?\n"
	.string "Forsvind!$"
