Route15_Text_KindraIntro::
    .string "Jeg har lige fâet nogle POKeMON i\n"
    .string "bytte. Ma jeg pröve dem pâ dig?$"

Route15_Text_KindraDefeat::
    .string "Ikke god nok!$"

Route15_Text_KindraPostBattle::
    .string "Du kan ikke ändre kaldenavnet pâ\n"
    .string "POKeMON du fâr i et bytte.\p"
    .string "Kun den oprindelige TRAINER kan\n"
    .string "fâ kaldenavnet ändret.$"

Route15_Text_BeckyIntro::
    .string "Du ser blid ud, sâ jeg tror jeg\n"
    .string "kan slâ dig.\p"
    .string "Jeg pröver!$"

Route15_Text_BeckyDefeat::
    .string "Nej, forkert!$"

Route15_Text_BeckyPostBattle::
    .string "Jeg er bange for BIKERS. De ser sâ\n"
    .string "grimme og onde ud!$"

Route15_Text_EdwinIntro::
    .string "Nâr jeg flöjter, kan jeg tilkalde\n"
    .string "fugle-POKeMON.$"

Route15_Text_EdwinDefeat::
    .string "Av!\n"
    .string "Det er tragisk!$"

Route15_Text_EdwinPostBattle::
    .string "Mâske er jeg ikke skabt til kampe.\n"
    .string "Jeg er ikke den rigtige type.$"

Route15_Text_ChesterIntro::
    .string "Hmm? Mine fugle ryster!\n"
    .string "Du er god, er du ikke?$"

Route15_Text_ChesterDefeat::
    .string "Som jeg tänkte!$"

Route15_Text_ChesterPostBattle::
    .string "Det her er sâ indlysende, du burde\n"
    .string "vide det, men...\p"
    .string "Angreb som EARTHQUAKE og FISSURE\n"
    .string "har ingen effekt pâ fugle-POKeMON.$"

Route15_Text_GraceIntro::
    .string "Aa, du er sâ söd!\n"
    .string "Som en söd POKeMON!$"

Route15_Text_GraceDefeat::
    .string "Du sâ ogsâ sâ söd ud!$"

Route15_Text_GracePostBattle::
    .string "Jeg tilgiver dig.\n"
    .string "Jeg kan tage det.\l"
    .string "Jeg er en stor pige nu.$"

Route15_Text_OliviaIntro::
    .string "Jeg opdrager POKeMON til beskyttelse\n"
    .string "fordi jeg bor alene.$"

Route15_Text_OliviaDefeat::
    .string "POKeMON handler ikke om at vinde\n"
    .string "eller tabe for mig.$"

Route15_Text_OliviaPostBattle::
    .string "Jeg elsker at mine POKeMON hilser\n"
    .string "mig nâr jeg kommer hjem.\p"
    .string "Det er sâ betryggende.$"

Route15_Text_ErnestIntro::
    .string "Hey, unge! Kom!\n"
    .string "Jeg fik dem lige fra en taber!$"

Route15_Text_ErnestDefeat::
    .string "Hvorfor ikke?$"

Route15_Text_ErnestPostBattle::
    .string "Livet er for kort.\n"
    .string "Det er sejt at leve som outlaw.\l"
    .string "TEAM ROCKET REGLER!$"

Route15_Text_AlexIntro::
    .string "Aflever alle dine penge nâr du\n"
    .string "taber til mig, unge!$"

Route15_Text_AlexDefeat::
    .string "Det kan ikke väre sandt!$"

Route15_Text_AlexPostBattle::
    .string "Jeg jokede bare med pengene.\n"
    .string "Tag mig ikke sâ alvorligt.$"

Route15_Text_CeliaIntro::
    .string "Hvad er sejt og sker?\n"
    .string "At bytte POKeMON!$"

Route15_Text_CeliaDefeat::
    .string "Jeg sagde bytte!$"

Route15_Text_CeliaPostBattle::
    .string "Jeg bytter POKeMON med mine\n"
    .string "venner hele tiden.$"

Route15_Text_YazminIntro::
    .string "Vil du lege med mine POKeMON?$"

Route15_Text_YazminDefeat::
    .string "Jeg var for utâlmodig!$"

Route15_Text_YazminPostBattle::
    .string "Jeg tager hen og träner med\n"
    .string "svagere folk.$"

Route15_Text_RouteSign::
    .string "ROUTE 15\n"
    .string "Vest til FUCHSIA CITY$"

Route15_Text_MyaIntro::
    .string "MYA: Du er perfekt.\n"
    .string "Hjälp mig med at träne min lillebror?$"

Route15_Text_MyaDefeat::
    .string "MYA: RON, du skal fokusere!\n"
    .string "Konsentrer dig om hvad du gör!$"

Route15_Text_MyaPostBattle::
    .string "MYA: Okay, vi skruer op.\n"
    .string "Jeg tilföjer til vores träningsmenu!$"

Route15_Text_MyaNotEnoughMons::
    .string "MYA: Vil du udfordre os?\n"
    .string "Du skal bruge to POKeMON, dog.$"

Route15_Text_RonIntro::
    .string "RON: Min söster bliver skrämmende\n"
    .string "nâr vi taber.$"

Route15_Text_RonDefeat::
    .string "RON: Aa, nej, nej...\n"
    .string "Sös, undskyld!$"

Route15_Text_RonPostBattle::
    .string "RON: Aa, böv...\n"
    .string "Jeg ville önske jeg havde en rar söster...$"

Route15_Text_RonNotEnoughMons::
    .string "RON: Ville du kämpe med min\n"
    .string "söster og mig?\p"
    .string "Du skal bruge to POKeMON, sâ.$"
