Route15_Text_KindraIntro::
    .string "Jeg har lige faaet nogle POKeMON i\n"
    .string "bytte. Ma jeg proeve dem paa dig?$"

Route15_Text_KindraDefeat::
    .string "Ikke god nok!$"

Route15_Text_KindraPostBattle::
    .string "Du kan ikke aendre kaldenavnet paa\n"
    .string "POKeMON du faar i et bytte.\p"
    .string "Kun den oprindelige TRAINER kan\n"
    .string "faa kaldenavnet aendret.$"

Route15_Text_BeckyIntro::
    .string "Du ser blid ud, saa jeg tror jeg\n"
    .string "kan slaa dig.\p"
    .string "Jeg proever!$"

Route15_Text_BeckyDefeat::
    .string "Nej, forkert!$"

Route15_Text_BeckyPostBattle::
    .string "Jeg er bange for BIKERS. De ser saa\n"
    .string "grimme og onde ud!$"

Route15_Text_EdwinIntro::
    .string "Naar jeg floejter, kan jeg tilkalde\n"
    .string "fugle-POKeMON.$"

Route15_Text_EdwinDefeat::
    .string "Av!\n"
    .string "Det er tragisk!$"

Route15_Text_EdwinPostBattle::
    .string "Maaske er jeg ikke skabt til kampe.\n"
    .string "Jeg er ikke den rigtige type.$"

Route15_Text_ChesterIntro::
    .string "Hmm? Mine fugle ryster!\n"
    .string "Du er god, er du ikke?$"

Route15_Text_ChesterDefeat::
    .string "Som jeg taenkte!$"

Route15_Text_ChesterPostBattle::
    .string "Det her er saa indlysende, du burde\n"
    .string "vide det, men...\p"
    .string "Angreb som EARTHQUAKE og FISSURE\n"
    .string "har ingen effekt paa fugle-POKeMON.$"

Route15_Text_GraceIntro::
    .string "Aa, du er saa soed!\n"
    .string "Som en soed POKeMON!$"

Route15_Text_GraceDefeat::
    .string "Du saa ogsaa saa soed ud!$"

Route15_Text_GracePostBattle::
    .string "Jeg tilgiver dig.\n"
    .string "Jeg kan tage det.\l"
    .string "Jeg er en stor pige nu.$"

Route15_Text_OliviaIntro::
    .string "Jeg opdrager POKeMON til beskyttelse\n"
    .string "fordi jeg bor alene.$"

Route15_Text_OliviaDefeat::
    .string "POKeMON handler ikke om at vinde\n"
    .string "eller tabe for mig.$"

Route15_Text_OliviaPostBattle::
    .string "Jeg elsker at mine POKeMON hilser\n"
    .string "mig naar jeg kommer hjem.\p"
    .string "Det er saa betryggende.$"

Route15_Text_ErnestIntro::
    .string "Hey, unge! Kom!\n"
    .string "Jeg fik dem lige fra en taber!$"

Route15_Text_ErnestDefeat::
    .string "Hvorfor ikke?$"

Route15_Text_ErnestPostBattle::
    .string "Livet er for kort.\n"
    .string "Det er sejt at leve som outlaw.\l"
    .string "TEAM ROCKET REGLER!$"

Route15_Text_AlexIntro::
    .string "Aflever alle dine penge naar du\n"
    .string "taber til mig, unge!$"

Route15_Text_AlexDefeat::
    .string "Det kan ikke vaere sandt!$"

Route15_Text_AlexPostBattle::
    .string "Jeg jokede bare med pengene.\n"
    .string "Tag mig ikke saa alvorligt.$"

Route15_Text_CeliaIntro::
    .string "Hvad er sejt og sker?\n"
    .string "At bytte POKeMON!$"

Route15_Text_CeliaDefeat::
    .string "Jeg sagde bytte!$"

Route15_Text_CeliaPostBattle::
    .string "Jeg bytter POKeMON med mine\n"
    .string "venner hele tiden.$"

Route15_Text_YazminIntro::
    .string "Vil du lege med mine POKeMON?$"

Route15_Text_YazminDefeat::
    .string "Jeg var for utaalmodig!$"

Route15_Text_YazminPostBattle::
    .string "Jeg tager hen og traener med\n"
    .string "svagere folk.$"

Route15_Text_RouteSign::
    .string "ROUTE 15\n"
    .string "Vest til FUCHSIA CITY$"

Route15_Text_MyaIntro::
    .string "MYA: Du er perfekt.\n"
    .string "Hjaelp mig med at traene min lillebror?$"

Route15_Text_MyaDefeat::
    .string "MYA: RON, du skal fokusere!\n"
    .string "Konsentrer dig om hvad du goer!$"

Route15_Text_MyaPostBattle::
    .string "MYA: Okay, vi skruer op.\n"
    .string "Jeg tilfoejer til vores traeningsmenu!$"

Route15_Text_MyaNotEnoughMons::
    .string "MYA: Vil du udfordre os?\n"
    .string "Du skal bruge to POKeMON, dog.$"

Route15_Text_RonIntro::
    .string "RON: Min soester bliver skraemmende\n"
    .string "naar vi taber.$"

Route15_Text_RonDefeat::
    .string "RON: Aa, nej, nej...\n"
    .string "Soes, undskyld!$"

Route15_Text_RonPostBattle::
    .string "RON: Aa, boev...\n"
    .string "Jeg ville oenske jeg havde en rar soester...$"

Route15_Text_RonNotEnoughMons::
    .string "RON: Ville du kaempe med min\n"
    .string "soester og mig?\p"
    .string "Du skal bruge to POKeMON, saa.$"
