CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .string "Velkommen!\p"
    .string "Du kan indlöse dine COINS for\n"
    .string "fremragende prämier ved siden af.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
    .string "Velkommen til ROCKET GAME CORNER!\p"
    .string "Har du brug for nogle spil-COINS?\n"
    .string "Vil du köbe nogle?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
    .string "Nej?\n"
    .string "Kom venligst og spil en gang!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .string "Aah, beklager.\n"
    .string "Du har ikke en COIN CASE.$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .string "Ups!\n"
    .string "Din COIN CASE er fuld.$"

CeladonCity_GameCorner_Text_CantAffordCoins::
    .string "Du har ikke râd til COINS.$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .string "Tak.\n"
    .string "Her er dine COINS!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .string "Hold det hemmeligt.\p"
    .string "Det siges at dette sted drives\n"
    .string "af TEAM ROCKET.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .string "Jeg tror disse maskiner har\n"
    .string "forskellige odds.$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .string "Barn, vil du spille?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
    .string "{PLAYER} modtog 10 COINS\n"
    .string "fra manden.$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
    .string "Du har ikke brug for mine COINS!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .string "Sejre kommer og gâr.\n"
    .string "Intet er sikkert.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .string "Disse spilleautomater…\n"
    .string "Vind eller tab, det er kun held.$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .string "Hej!\p"
    .string "Du har bedre ting at tage dig til,\n"
    .string "champion i blive!\p"
    .string "CELADON GYMs LEADER er ERIKA.\p"
    .string "Hun bruger GRASS-type\n"
    .string "POKeMON og er et med naturen.\p"
    .string "Hun virker mâske rolig pga.\n"
    .string "sine blomsterarrangementer…\p"
    .string "Men hun er ikke en man skal\n"
    .string "tage let pâ!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
    .string "De tilbyder själdne POKeMON der kan\n"
    .string "indlöses for dine COINS.\p"
    .string "Men jeg kan bare ikke vinde!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .string "Spil er skrämmende!\n"
    .string "Det er sâ nemt at blive afhängig!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
    .string "Hvad sâ?\n"
    .string "Vil du have nogle COINS?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
    .string "{PLAYER} modtog 20 COINS\n"
    .string "fra den rare fyr.$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
    .string "Du har masser af COINS!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
    .string "Pokkers! Jeg har brug for flere COINS til den\n"
    .string "POKeMON jeg vil have!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .string "Hey, hvad? Du distraherer mig!\n"
    .string "Her er nogle COINS, sâ försvind!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
    .string "{PLAYER} modtog 20 COINS\n"
    .string "fra manden.$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .string "Du har masser af dine egne\n"
    .string "COINS!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .string "Kunsten er at se hjulene nöje.$"

CeladonCity_GameCorner_Text_GruntIntro::
    .string "Jeg vogter denne plakat!\n"
    .string "Forsvind, ellers!$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "Forbandet!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
    .string "TEAM ROCKET HIDEOUT kunne\n"
    .string "blive opdaget!\p"
    .string "Jeg bör fortälle det til BOSS!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "Hey!\p"
    .string "En kontakt bag plakaten!?\n"
    .string "Lad os trykke pâ den!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .string "En COIN CASE er nödvendig…$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "Ups!\n"
    .string "Har ikke COIN CASE!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "En spilleautomat!\n"
    .string "Vil du spille?$"

CeladonCity_GameCorner_Text_OutOfOrder::
    .string "UDE AF DRIFT\n"
    .string "Denne er i stykker.$"

CeladonCity_GameCorner_Text_OutToLunch::
    .string "PÂ FROKOST\n"
    .string "Denne er reserveret.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "Nogens nögler!\n"
    .string "De kommer tilbage.$"
