SixIsland_WaterPath_Text_RoseIntro::
    .string "Jeg lod en behagelig brise lede mig\n"
    .string "hele vejen hertil.$"

SixIsland_WaterPath_Text_RoseDefeat::
    .string "Fnis… Du er så sød når du er\n"
    .string "beslutsom.$"

SixIsland_WaterPath_Text_RosePostBattle::
    .string "Jeg vil gerne til skoven derovre,\n"
    .string "men…\p"
    .string "Der er masser af BUG POKéMON.\n"
    .string "De skræmmer mig lidt.$"

SixIsland_WaterPath_Text_EdwardIntro::
    .string "Jeg træner i hemmelighed så ingen\n"
    .string "kan se mig.$"

SixIsland_WaterPath_Text_EdwardDefeat::
    .string "Ingen så mig tabe, vel?$"

SixIsland_WaterPath_Text_EdwardPostBattle::
    .string "Som performer vil jeg ikke have folk\n"
    .string "til at vide om indsatsen jeg lægger.$"

SixIsland_WaterPath_Text_SamirIntro::
    .string "Hvad, foreslår du at du er træt af\n"
    .string "at se SVØMMERE som mig?\p"
    .string "Aah, vær ikke hadsk!$"

SixIsland_WaterPath_Text_SamirDefeat::
    .string "Aah, nej, nej, nej.$"

SixIsland_WaterPath_Text_SamirPostBattle::
    .string "Jeg kunne ikke løfte stigmæt af at\n"
    .string "være en SVØMMER…$"

SixIsland_WaterPath_Text_DeniseIntro::
    .string "Min kæreste er altid optaget, så jeg\n"
    .string "kommer og svømmer alene.$"

SixIsland_WaterPath_Text_DeniseDefeat::
    .string "Aååah, jeg vidste det ville ske!$"

SixIsland_WaterPath_Text_DenisePostBattle::
    .string "Når jeg ikke kan være med min kæreste,\n"
    .string "tilbringer jeg tid med den POKéMON han\l"
    .string "gav mig.$"

SixIsland_WaterPath_Text_EarlIntro::
    .string "Sig mig, hvor er bjergene\n"
    .string "omkring disse egne?$"

SixIsland_WaterPath_Text_EarlDefeat::
    .string "Jeg mistede vejen mens jeg var\n"
    .string "optaget af at kæmpe!$"

SixIsland_WaterPath_Text_EarlPostBattle::
    .string "Er der ikke nogen bjerge omkring\n"
    .string "disse egne?$"

SixIsland_WaterPath_Text_MiuIntro::
    .string "MIU: Hej, POKéMON!\n"
    .string "Det er tid til at lege!$"

SixIsland_WaterPath_Text_MiuDefeat::
    .string "MIU: Aah, nej!\n"
    .string "Mor!$"

SixIsland_WaterPath_Text_MiuPostBattle::
    .string "MIU: Det gør mig så trist indeni\n"
    .string "når vi taber…$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
    .string "MIU: MIA og jeg er TVILLINGER.\n"
    .string "Vi vil gerne kæmpe sammen.$"

SixIsland_WaterPath_Text_MiaIntro::
    .string "MIA: Hej, POKéMON!\n"
    .string "Det er tid til kamp!$"

SixIsland_WaterPath_Text_MiaDefeat::
    .string "MIA: Du er ond!\n"
    .string "Du er slem ved at vinde!$"

SixIsland_WaterPath_Text_MiaPostBattle::
    .string "MIA: Aååah…\n"
    .string "Undskyld, min POKéMON…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
    .string "MIA: Aah, har du kun én\n"
    .string "POKéMON?\p"
    .string "Føler du dig ikke ensom?$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
    .string "Søges!\n"
    .string "Det ultimative horn!$"

SixIsland_WaterPath_Text_RouteSign::
    .string "WATER PATH\n"
    .string "Fører til RUIN VALLEY$"

