SixIsland_WaterPath_Text_RoseIntro::
    .string "Jeg lod en behagelig brise lede mig\n"
    .string "hele vejen hertil.$"

SixIsland_WaterPath_Text_RoseDefeat::
    .string "Fnis… Du er saa soed naar du er\n"
    .string "beslutsom.$"

SixIsland_WaterPath_Text_RosePostBattle::
    .string "Jeg vil gerne til skoven derovre,\n"
    .string "men…\p"
    .string "Der er masser af BUG POKeMON.\n"
    .string "De skraemmer mig lidt.$"

SixIsland_WaterPath_Text_EdwardIntro::
    .string "Jeg traener i hemmelighed saa ingen\n"
    .string "kan se mig.$"

SixIsland_WaterPath_Text_EdwardDefeat::
    .string "Ingen saa mig tabe, vel?$"

SixIsland_WaterPath_Text_EdwardPostBattle::
    .string "Som performer vil jeg ikke have folk\n"
    .string "til at vide om indsatsen jeg laegger.$"

SixIsland_WaterPath_Text_SamirIntro::
    .string "Hvad, foreslaar du at du er traet af\n"
    .string "at se SVOEMMERE som mig?\p"
    .string "Aah, vaer ikke hadsk!$"

SixIsland_WaterPath_Text_SamirDefeat::
    .string "Aah, nej, nej, nej.$"

SixIsland_WaterPath_Text_SamirPostBattle::
    .string "Jeg kunne ikke loefte stigmaet af at\n"
    .string "vaere en SVOEMMER…$"

SixIsland_WaterPath_Text_DeniseIntro::
    .string "Min kaereste er altid optaget, saa jeg\n"
    .string "kommer og svoemmer alene.$"

SixIsland_WaterPath_Text_DeniseDefeat::
    .string "Aaaaaah, jeg vidste det ville ske!$"

SixIsland_WaterPath_Text_DenisePostBattle::
    .string "Naar jeg ikke kan vaere med min kaereste,\n"
    .string "tilbringer jeg tid med den POKeMON han\l"
    .string "gav mig.$"

SixIsland_WaterPath_Text_EarlIntro::
    .string "Sig mig, hvor er bjergene\n"
    .string "omkring disse egne?$"

SixIsland_WaterPath_Text_EarlDefeat::
    .string "Jeg mistede vejen mens jeg var\n"
    .string "optaget af at kaempe!$"

SixIsland_WaterPath_Text_EarlPostBattle::
    .string "Er der ikke nogen bjerge omkring\n"
    .string "disse egne?$"

SixIsland_WaterPath_Text_MiuIntro::
    .string "MIU: Hej, POKeMON!\n"
    .string "Det er tid til at lege!$"

SixIsland_WaterPath_Text_MiuDefeat::
    .string "MIU: Aah, nej!\n"
    .string "Mor!$"

SixIsland_WaterPath_Text_MiuPostBattle::
    .string "MIU: Det goer mig saa trist indeni\n"
    .string "naar vi taber…$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
    .string "MIU: MIA og jeg er TVILLINGER.\n"
    .string "Vi vil gerne kaempe sammen.$"

SixIsland_WaterPath_Text_MiaIntro::
    .string "MIA: Hej, POKeMON!\n"
    .string "Det er tid til kamp!$"

SixIsland_WaterPath_Text_MiaDefeat::
    .string "MIA: Du er ond!\n"
    .string "Du er slem ved at vinde!$"

SixIsland_WaterPath_Text_MiaPostBattle::
    .string "MIA: Aaaaaah…\n"
    .string "Undskyld, min POKeMON…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
    .string "MIA: Aah, har du kun én\n"
    .string "POKeMON?\p"
    .string "Foeler du dig ikke ensom?$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
    .string "Soeges!\n"
    .string "Det ultimative horn!$"

SixIsland_WaterPath_Text_RouteSign::
    .string "WATER PATH\n"
    .string "Foerer til RUIN VALLEY$"

