CinnabarIsland_Text_DoorIsLocked::
    .string "Dören er lâset…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "CINNABAR GYMs BLAINE er ret\n"
    .string "märkelig.\p"
    .string "Han har böt pâ ön länge för\n"
    .string "LAB blev bygget.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Forskere udförer eksperimenter\n"
    .string "i den nedbrändte bygning.\p"
    .string "Du ved, den de kalder\n"
    .string "POKéMON MANSION.$"

CinnabarIsland_Text_IslandSign::
    .string "CINNABAR ISLAND\n"
    .string "Den Ildende Bys Brändende Lyst$"

CinnabarIsland_Text_PokemonLab::
    .string "POKéMON LAB$"

CinnabarIsland_Text_GymSign::
    .string "CINNABAR ISLAND POKéMON GYM\n"
    .string "LEADER: BLAINE\l"
    .string "Den Hidsige Quiz-Mester!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "Hva?\n"
    .string "Hey, er det ikke {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Se, det er mig, BILL.\n"
    .string "Länge siden!\p"
    .string "Jeg hâber du stadig bruger mit\n"
    .string "PC-system.\p"
    .string "Nâr, hör nu, siden vi mödtes her,\n"
    .string "hvad med at tilbringe tid med mig?\p"
    .string "Der er en lille ö i det fjerne\n"
    .string "syd kaldet ONE ISLAND.\p"
    .string "En ven inviterede mig, sâ jeg er\n"
    .string "pâ vej derud.\p"
    .string "Hvad med det?\n"
    .string "Har du lyst til at komme med?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "Okay, sâ.\n"
    .string "Lad os gâ!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "Hvad, er du for optaget?\p"
    .string "Nâr, okay.\n"
    .string "Bâden er ikke ankommet endnu.\p"
    .string "Jeg venter i POKéMON\n"
    .string "CENTER derovre.\p"
    .string "Kom til mig nâr du er färdig\n"
    .string "med dine ting her.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Det ser ud til min kammerats bâd\n"
    .string "er ankommet, ogsâ.\p"
    .string "Han sendte den specielt her til\n"
    .string "CINNABAR for at hente mig.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Hey, var det ikke en lang sejltur?\p"
    .string "Min kammerat CELIO syntes at nyde\n"
    .string "dit selskab.\p"
    .string "Jeg er sikker pâ han vil byde dig\n"
    .string "velkommen hvis du besöger ham igen.\p"
    .string "Hvis du har et TRI-PASS, kan du\n"
    .string "altid tage en färge derfra fra\l"
    .string "VERMILION PORT.\p"
    .string "Okay, tak for selskabet!$"
