CinnabarIsland_Text_DoorIsLocked::
    .string "Doeren er laaset…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "CINNABAR GYMs BLAINE er ret\n"
    .string "maerkelig.\p"
    .string "Han har boet paa oen laenge foer\n"
    .string "LAB blev bygget.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Forskere udfoerer eksperimenter\n"
    .string "i den nedbraendte bygning.\p"
    .string "Du ved, den de kalder\n"
    .string "POKeMON MANSION.$"

CinnabarIsland_Text_IslandSign::
    .string "CINNABAR ISLAND\n"
    .string "Den Ildende Bys Braendende Lyst$"

CinnabarIsland_Text_PokemonLab::
    .string "POKeMON LAB$"

CinnabarIsland_Text_GymSign::
    .string "CINNABAR ISLAND POKeMON GYM\n"
    .string "LEADER: BLAINE\l"
    .string "Den Hidsige Quiz-Mester!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "Hva?\n"
    .string "Hey, er det ikke {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Se, det er mig, BILL.\n"
    .string "Laenge siden!\p"
    .string "Jeg haaber du stadig bruger mit\n"
    .string "PC-system.\p"
    .string "Naar, hoer nu, siden vi moedtes her,\n"
    .string "hvad med at tilbringe tid med mig?\p"
    .string "Der er en lille oe i det fjerne\n"
    .string "syd kaldet ONE ISLAND.\p"
    .string "En ven inviterede mig, saa jeg er\n"
    .string "paa vej derud.\p"
    .string "Hvad med det?\n"
    .string "Har du lyst til at komme med?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "Okay, saa.\n"
    .string "Lad os gaa!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "Hvad, er du for optaget?\p"
    .string "Naar, okay.\n"
    .string "Baaden er ikke ankommet endnu.\p"
    .string "Jeg venter i POKeMON\n"
    .string "CENTER derovre.\p"
    .string "Kom til mig naar du er faerdig\n"
    .string "med dine ting her.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Det ser ud til min kammerats baad\n"
    .string "er ankommet, ogsaa.\p"
    .string "Han sendte den specielt her til\n"
    .string "CINNABAR for at hente mig.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Hey, var det ikke en lang sejltur?\p"
    .string "Min kammerat CELIO syntes at nyde\n"
    .string "dit selskab.\p"
    .string "Jeg er sikker paa han vil byde dig\n"
    .string "velkommen hvis du besoeger ham igen.\p"
    .string "Hvis du har et TRI-PASS, kan du\n"
    .string "altid tage en faerge derfra fra\l"
    .string "VERMILION PORT.\p"
    .string "Okay, tak for selskabet!$"
