OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "Hm!\n"
    .string "Hâââââah!\p"
    .string "Aâah! Det er himmelsk!\n"
    .string "Vandet varmer mig ind til benet!\p"
    .string "Du burde ogsâ hoppe i.\p"
    .string "Gâ til midten, slap af og bliv\n"
    .string "godt varm!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "Min yndlingsdel af badet kommer\n"
    .string "lige efter dette.\p"
    .string "Jeg nyder en skâl suppe for at\n"
    .string "blive varm indefra ogsâ!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "Vandet er perfekt varmt.\n"
    .string "Det föles udsögt…\p"
    .string "{PLAYER} og POKeMONene blev\n"
    .string "helt forfrisket!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "At ligge i et varmt kildepool siges\n"
    .string "at väre terapeutisk.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "Se mit ansigt.\n"
    .string "Se hvor glat min hud er?\p"
    .string "Kildevandet holder min hud\n"
    .string "yngre end min alder.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "Efter en ärlig dags träning er\n"
    .string "der ikke bedre end et afslappende\l"
    .string "bad i kildepoolen.\p"
    .string "BRUNO, som er senior over mig,\n"
    .string "besöger SPA'en lejlighedsvis.\p"
    .string "Han kommer for at rehabilitere\n"
    .string "skader, bâde sine og sine POKeMONs.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "Varme kilder hänger sammen med\n"
    .string "vulkaner.\p"
    .string "EMBER SPA her, ja,\n"
    .string "jeg lavede den for âr siden.\p"
    .string "Jeg huggede poolen ud af en\n"
    .string "kämpe kampesten for hând.\p"
    .string "Jeg brugte denne dengang.\n"
    .string "Jeg kan nok undväre den.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "Den splintrer kampesten som om de\n"
    .string "var lavet af kiks.$"

