OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "Hm!\n"
    .string "Håååååah!\p"
    .string "Aåah! Det er himmelsk!\n"
    .string "Vandet varmer mig ind til benet!\p"
    .string "Du burde også hoppe i.\p"
    .string "Gå til midten, slap af og bliv\n"
    .string "godt varm!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "Min yndlingsdel af badet kommer\n"
    .string "lige efter dette.\p"
    .string "Jeg nyder en skål suppe for at\n"
    .string "blive varm indefra også!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "Vandet er perfekt varmt.\n"
    .string "Det føles udsøgt…\p"
    .string "{PLAYER} og POKéMONene blev\n"
    .string "helt forfrisket!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "At ligge i et varmt kildepool siges\n"
    .string "at være terapeutisk.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "Se mit ansigt.\n"
    .string "Se hvor glat min hud er?\p"
    .string "Kildevandet holder min hud\n"
    .string "yngre end min alder.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "Efter en ærlig dags træning er\n"
    .string "der ikke bedre end et afslappende\l"
    .string "bad i kildepoolen.\p"
    .string "BRUNO, som er senior over mig,\n"
    .string "besøger SPA'en lejlighedsvis.\p"
    .string "Han kommer for at rehabilitere\n"
    .string "skader, både sine og sine POKéMONs.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "Varme kilder hænger sammen med\n"
    .string "vulkaner.\p"
    .string "EMBER SPA her, ja,\n"
    .string "jeg lavede den for år siden.\p"
    .string "Jeg huggede poolen ud af en\n"
    .string "kæmpe kampesten for hånd.\p"
    .string "Jeg brugte denne dengang.\n"
    .string "Jeg kan nok undvære den.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "Den splintrer kampesten som om de\n"
    .string "var lavet af kiks.$"

