OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "Hm!\n"
    .string "Haaaaaaaaaaah!\p"
    .string "Aaaah! Det er himmelsk!\n"
    .string "Vandet varmer mig ind til benet!\p"
    .string "Du burde ogsaa hoppe i.\p"
    .string "Gaa til midten, slap af og bliv\n"
    .string "godt varm!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "Min yndlingsdel af badet kommer\n"
    .string "lige efter dette.\p"
    .string "Jeg nyder en skaal suppe for at\n"
    .string "blive varm indefra ogsaa!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "Vandet er perfekt varmt.\n"
    .string "Det foeles udsoegt…\p"
    .string "{PLAYER} og POKeMONene blev\n"
    .string "helt forfrisket!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "At ligge i et varmt kildepool siges\n"
    .string "at vaere terapeutisk.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "Se mit ansigt.\n"
    .string "Se hvor glat min hud er?\p"
    .string "Kildevandet holder min hud\n"
    .string "yngre end min alder.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "Efter en aerlig dags traening er\n"
    .string "der ikke bedre end et afslappende\l"
    .string "bad i kildepoolen.\p"
    .string "BRUNO, som er senior over mig,\n"
    .string "besoeger SPA'en lejlighedsvis.\p"
    .string "Han kommer for at rehabilitere\n"
    .string "skader, baade sine og sine POKeMONs.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "Varme kilder haenger sammen med\n"
    .string "vulkaner.\p"
    .string "EMBER SPA her, ja,\n"
    .string "jeg lavede den for aar siden.\p"
    .string "Jeg huggede poolen ud af en\n"
    .string "kaempe kampesten for haand.\p"
    .string "Jeg brugte denne dengang.\n"
    .string "Jeg kan nok undvaere den.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "Den splintrer kampesten som om de\n"
    .string "var lavet af kiks.$"

