SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "ROCKETs kom og overtog\n"
    .string "bygningen!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "Nâ, bedre at komme tilbage til arbejde.$"

SilphCo_6F_Text_HelpMePlease::
    .string "Oh nej, oh nej.\n"
    .string "Hjälp mig, venligst!$"

SilphCo_6F_Text_WeGotEngaged::
    .string "Vi blev forlovet.\n"
    .string "Heheh!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "Den mand ved siden af mig…\n"
    .string "Han er sâ fej!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "Han er sâ hjälpelös, han havde brug for\n"
    .string "en som mig til at passe pâ ham.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "TEAM ROCKET pröver at erobre\n"
    .string "verden med POKéMON.$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "TEAM ROCKET löb väk, og det er\n"
    .string "alt sammen takket väre dig!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "De mâ have mâlrettet SILPH for\n"
    .string "vores POKéMON-produkter.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "Kom og arbejd for SILPH nâr du\n"
    .string "bliver äldre.$"

SilphCo_6F_Text_Grunt1Intro::
    .string "Jeg er en af de fire ROCKET\n"
    .string "BRÖDRE!$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "Flammen ud!$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "Ligemeget!\n"
    .string "Mine brödre vil hävne mig!$"

SilphCo_6F_Text_TaylorIntro::
    .string "Den râdne PRESIDENT!\p"
    .string "Det fortjener han for at sende mig\n"
    .string "til TIKSI FILIALEN!\p"
    .string "Det er derfor TEAM ROCKET kom efter\n"
    .string "os, det er jeg sikker pâ!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "Skud!$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "TIKSI FILIALEN?\n"
    .string "Den er i russisk ingenmandsland!$"

SilphCo_6F_Text_Grunt2Intro::
    .string "Du vâger at forräde TEAM ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "Du forräder!$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "Hvis du stâr for retfärdighed,\n"
    .string "forräder du os slemme fyre!$"

SilphCo_6F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "6. SAL$"

