SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "ROCKETs kom og overtog\n"
    .string "bygningen!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "Naa, bedre at komme tilbage til arbejde.$"

SilphCo_6F_Text_HelpMePlease::
    .string "Oh nej, oh nej.\n"
    .string "Hjaelp mig, venligst!$"

SilphCo_6F_Text_WeGotEngaged::
    .string "Vi blev forlovet.\n"
    .string "Heheh!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "Den mand ved siden af mig…\n"
    .string "Han er saa fej!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "Han er saa hjaelpeloes, han havde brug for\n"
    .string "en som mig til at passe paa ham.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "TEAM ROCKET proever at erobre\n"
    .string "verden med POKeMON.$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "TEAM ROCKET loeb vaek, og det er\n"
    .string "alt sammen takket vaere dig!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "De maa have maalrettet SILPH for\n"
    .string "vores POKeMON-produkter.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "Kom og arbejd for SILPH naar du\n"
    .string "bliver aeldre.$"

SilphCo_6F_Text_Grunt1Intro::
    .string "Jeg er en af de fire ROCKET\n"
    .string "BROEDRE!$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "Flammen ud!$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "Ligemeget!\n"
    .string "Mine broedre vil haevne mig!$"

SilphCo_6F_Text_TaylorIntro::
    .string "Den raadne PRESIDENT!\p"
    .string "Det fortjener han for at sende mig\n"
    .string "til TIKSI FILIALEN!\p"
    .string "Det er derfor TEAM ROCKET kom efter\n"
    .string "os, det er jeg sikker paa!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "Skud!$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "TIKSI FILIALEN?\n"
    .string "Den er i russisk ingenmandsland!$"

SilphCo_6F_Text_Grunt2Intro::
    .string "Du vaager at forraede TEAM ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "Du forraeder!$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "Hvis du staar for retfaerdighed,\n"
    .string "forraeder du os slemme fyre!$"

SilphCo_6F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "6. SAL$"

