SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "ROCKETs kom og overtog\n"
    .string "bygningen!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "Nå, bedre at komme tilbage til arbejde.$"

SilphCo_6F_Text_HelpMePlease::
    .string "Oh nej, oh nej.\n"
    .string "Hjælp mig, venligst!$"

SilphCo_6F_Text_WeGotEngaged::
    .string "Vi blev forlovet.\n"
    .string "Heheh!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "Den mand ved siden af mig…\n"
    .string "Han er så fej!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "Han er så hjælpeløs, han havde brug for\n"
    .string "en som mig til at passe på ham.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "TEAM ROCKET prøver at erobre\n"
    .string "verden med POKéMON.$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "TEAM ROCKET løb væk, og det er\n"
    .string "alt sammen takket være dig!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "De må have målrettet SILPH for\n"
    .string "vores POKéMON-produkter.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "Kom og arbejd for SILPH når du\n"
    .string "bliver ældre.$"

SilphCo_6F_Text_Grunt1Intro::
    .string "Jeg er en af de fire ROCKET\n"
    .string "BRØDRE!$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "Flammen ud!$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "Ligemeget!\n"
    .string "Mine brødre vil hævne mig!$"

SilphCo_6F_Text_TaylorIntro::
    .string "Den rådne PRESIDENT!\p"
    .string "Det fortjener han for at sende mig\n"
    .string "til TIKSI FILIALEN!\p"
    .string "Det er derfor TEAM ROCKET kom efter\n"
    .string "os, det er jeg sikker på!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "Skud!$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "TIKSI FILIALEN?\n"
    .string "Den er i russisk ingenmandsland!$"

SilphCo_6F_Text_Grunt2Intro::
    .string "Du våger at forræde TEAM ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "Du forræder!$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "Hvis du står for retfærdighed,\n"
    .string "forræder du os slemme fyre!$"

SilphCo_6F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "6. SAL$"

