ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .string "Urrrrrrrrgggghhhh…\n"
    .string "Kwaaaaah!\p"
    .string "…Det er nytteloest! Jeg kan ikke faa\n"
    .string "denne ske til at boeje med mit sind.\p"
    .string "Maaske har jeg virkelig ikke nogen\n"
    .string "psykiske kraefter.$"

ThreeIsland_House2_Text_IAdmireSabrina::
    .string "Kender du en pige GYM LEADER\n"
    .string "i SAFFRON CITY?\p"
    .string "Hun bruger PSYCHIC-type POKeMON,\n"
    .string "ikke?\p"
    .string "Jeg beundrer hende, virkelig.\p"
    .string "Jeg har hoert at hun er cool\n"
    .string "og smuk ogsaa.$"

