ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .string "Urrrrrrrrgggghhhh…\n"
    .string "Kwââah!\p"
    .string "…Det er nyttelöst! Jeg kan ikke fâ\n"
    .string "denne ske til at böje med mit sind.\p"
    .string "Mâske har jeg virkelig ikke nogen\n"
    .string "psykiske kräfter.$"

ThreeIsland_House2_Text_IAdmireSabrina::
    .string "Kender du en pige GYM LEADER\n"
    .string "i SAFFRON CITY?\p"
    .string "Hun bruger PSYCHIC-type POKéMON,\n"
    .string "ikke?\p"
    .string "Jeg beundrer hende, virkelig.\p"
    .string "Jeg har hört at hun er cool\n"
    .string "og smuk ogsâ.$"

