FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "Du bliver ikke en god TRAINER\n"
    .string "med bare én stärk POKeMON.\p"
    .string "Men at opdrage mange POKeMON\n"
    .string "jävnt er heller ikke nemt.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "Der er en smal sti vest for\n"
    .string "VIRIDIAN CITY.\p"
    .string "Den gâr til POKeMON LEAGUE HQ.\n"
    .string "HQ styrer alle TRAINERs.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "Hvis du arbejder pâ en POKeDEX,\n"
    .string "besög SAFARI ZONE.\p"
    .string "Alle mulige själde POKeMON\n"
    .string "yngler der.$"

