Route6_NorthEntrance_Text_ThirstyOnGuardDuty::
    .string "Jeg er paa vagt.\n"
    .string "Av, jeg er toerstig!\p"
    .string "Oh vent, vejen er lukket.$"

Route6_NorthEntrance_Text_ThatTeaLooksTasty::
    .string "Oh, den TEA…\n"
    .string "Den ser rigtig laekker ud…$"

Route6_NorthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Hvad? Maa jeg faa den drink?\n"
    .string "Av, tak!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "Hvis du vil til SAFFRON\l"
    .string "CITY…\l"
    .string "… …\l"
    .string "Ma du gaae igennem.\p"
    .string "Jeg deler denne TEA med de andre\n"
    .string "vagter!$"

Route6_NorthEntrance_Text_HiHowsItGoing::
    .string "Hej, hvordan gaar det?$"
