CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "Den BILL!\p"
    .string "Jeg hørte at han vil gøre hvad som\n"
    .string "helst for at fâ sjældne POKéMON.\p"
    .string "Han er ikke for fin til at gøre alle\n"
    .string "mulige ting, har jeg hørt.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Har du hørt om BILL?\p"
    .string "Alle kalder ham en POKeMANIAC!\p"
    .string "Jeg tror folk bare er misundelige pâ\n"
    .string "BILL, dog.\p"
    .string "Hvem ville ikke ville prale af\n"
    .string "sine POKéMON?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL har masser af POKéMON!\n"
    .string "Han samler ogsâ sjældne!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "Hvorfor gâer du ikke ovenpâ og prøver\n"
    .string "at bytte POKéMON med dine venner?\p"
    .string "Du kunne fâ meget mere variation\n"
    .string "ved at bytte.\p"
    .string "De POKéMON du fâr ved bytte grør\n"
    .string "hurtigt, ogsâ.$"
