CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "Den BILL!\p"
    .string "Jeg hörte at han vil göre hvad som\n"
    .string "helst for at fâ själdne POKeMON.\p"
    .string "Han er ikke for fin til at göre alle\n"
    .string "mulige ting, har jeg hört.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Har du hört om BILL?\p"
    .string "Alle kalder ham en POKeMANIAC!\p"
    .string "Jeg tror folk bare er misundelige pâ\n"
    .string "BILL, dog.\p"
    .string "Hvem ville ikke ville prale af\n"
    .string "sine POKeMON?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL har masser af POKeMON!\n"
    .string "Han samler ogsâ själdne!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "Hvorfor gâer du ikke ovenpâ og pröver\n"
    .string "at bytte POKeMON med dine venner?\p"
    .string "Du kunne fâ meget mere variation\n"
    .string "ved at bytte.\p"
    .string "De POKeMON du fâr ved bytte grör\n"
    .string "hurtigt, ogsâ.$"
