CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "Den BILL!\p"
    .string "Jeg hoerte at han vil goere hvad som\n"
    .string "helst for at faa sjaeldne POKeMON.\p"
    .string "Han er ikke for fin til at goere alle\n"
    .string "mulige ting, har jeg hoert.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Har du hoert om BILL?\p"
    .string "Alle kalder ham en POKeMANIAC!\p"
    .string "Jeg tror folk bare er misundelige paa\n"
    .string "BILL, dog.\p"
    .string "Hvem ville ikke ville prale af\n"
    .string "sine POKeMON?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL har masser af POKeMON!\n"
    .string "Han samler ogsaa sjaeldne!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "Hvorfor gaaer du ikke ovenpaa og proever\n"
    .string "at bytte POKeMON med dine venner?\p"
    .string "Du kunne faa meget mere variation\n"
    .string "ved at bytte.\p"
    .string "De POKeMON du faar ved bytte groer\n"
    .string "hurtigt, ogsaa.$"
