SaffronCity_Text_WhatDoYouWantGetLost::
    .string "Hvad vil du?\n"
    .string "Forsvind!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
    .string "BOSS sagde, at han tager byen\n"
    .string "i TEAM ROCKETs navn!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .string "Vaer ikke trodsig!\n"
    .string "Saa skal jeg goere dig ondt!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .string "SAFFRON tilhoerer TEAM ROCKET!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .string "Mit liv som kriminel faar mig til at\n"
    .string "foele mig sa levende!$"

SaffronCity_Text_WatchWhereYoureWalking::
    .string "Av!\n"
    .string "Pas paa hvor du gaar!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .string "Med SILPH under kontrol kan vi\n"
    .string "udnytte POKeMON verden over!\p"
    .string "Vi bliver stinkende rige, jaha!$"

SaffronCity_Text_YouBeatTeamRocket::
    .string "Besejrede du TEAM ROCKET helt alene?\n"
    .string "Det er fantastisk!$"

SaffronCity_Text_SafeToGoOutAgain::
    .string "Ja! TEAM ROCKET er vaek!\n"
    .string "Det er sikkert at ga ud igen!$"

SaffronCity_Text_PeopleComingBackToSaffron::
    .string "Folk flygtede herfra i hobetal\n"
    .string "da de ROCKETs kom.\p"
    .string "De boer flyde tilbage til\n"
    .string "SAFFRON nu.$"

SaffronCity_Text_FlewHereOnPidgeot::
    .string "Jeg floj hertil paa min PIDGEOT da\n"
    .string "jeg laeste om SILPH.\p"
    .string "Er det allerede forbi?\n"
    .string "Jeg missede medieaktionen…$"

SaffronCity_Text_Pidgeot::
    .string "PIDGEOT: Bi bibii!$"

SaffronCity_Text_SawRocketBossEscaping::
    .string "Jeg sa ROCKET BOSS flygte fra\n"
    .string "SILPHs bygning.$"

SaffronCity_Text_ImASecurityGuard::
    .string "Jeg er sikkerhedsvagt.\p"
    .string "Mistaenkelige boern lukker jeg ikke ind!$"

SaffronCity_Text_HesTakingASnooze::
    .string "…\n"
    .string "Snork…\p"
    .string "Hah! Han tager en lur!$"

SaffronCity_Text_CitySign::
    .string "SAFFRON CITY\n"
    .string "Skinnende, gyldent handelsland$"

SaffronCity_Text_FightingDojo::
    .string "FIGHTING DOJO$"

SaffronCity_Text_GymSign::
    .string "SAFFRON CITY POKeMON GYM\n"
    .string "LEADER: SABRINA\l"
    .string "Mesteren af PSYCHIC POKeMON!$"

SaffronCity_Text_FullHealCuresStatus::
    .string "TRAINER TIPS\p"
    .string "FULL HEAL kurerer alle plager som\n"
    .string "braend, lamhed, forgiftning,\l"
    .string "frysning og soevn.\p"
    .string "Det koster lidt mere, men det er\n"
    .string "mere bekvemt end at koebe andre ting.$"

SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "TRAINER TIPS\p"
    .string "Den nye GREAT BALL giver bedre\n"
    .string "fangstrate.\p"
    .string "Proev den paa de svaert-fangbare\n"
    .string "POKeMON.$"

SaffronCity_Text_SilphCoSign::
    .string "SILPH CO. KONTORBYGNING$"

SaffronCity_Text_MrPsychicsHouse::
    .string "MR. PSYCHICS HUS$"

SaffronCity_Text_SilphsLatestProduct::
    .string "SILPHs seneste produkt!\n"
    .string "Udgivelse afgoeres…$"

SaffronCity_Text_TrainerFanClubSign::
    .string "POKeMON TRAINER FAN CLUB\p"
    .string "Mange TRAINERE har skrevet deres\n"
    .string "navne paa dette skilt.$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .string "Denne FAN CLUB…\n"
    .string "Ingen her aner noget!\p"
    .string "Hvordan kunne de ikke genkende\n"
    .string "brilliancen der er LANCE?\p"
    .string "Han staar for retfaerdighed!\n"
    .string "Han er cool og alligevel passioneret!\l"
    .string "Han er den stoerste, LANCE!$"

