TwoIsland_Text_IslandSign::
    .string "TWO ISLAND\n"
    .string "Velsignelsesøn for to$"

TwoIsland_Text_JoyfulGameCornerSign::
    .string "Skip & Chomp!\n"
    .string "Joyful GAME CORNER$"

TwoIsland_Text_DangerFastCurrent::
    .string "FARE! STÆRK STRØMNING!\n"
    .string "Fiskeri og surfing forbudt!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
    .string "Aah!\n"
    .string "Hej, velkommen til min butik!\p"
    .string "Vi har kun lige âbnet.\p"
    .string "Vores varer er begrænsede, men jeg\n"
    .string "hâber vi kan dække dine behov.$"

TwoIsland_Text_AddedMerchandiseForLostelle::
    .string "Jeg kan ikke sige hvor taknemmelig jeg er\n"
    .string "for at du reddede LOSTELLE.\p"
    .string "Takket være din bedrift har folk pâ\n"
    .string "THREE ISLAND ændret holdning til\l"
    .string "KANTO-folk.\p"
    .string "Og jeg er fra KANTO, ser du.\p"
    .string "Folkene pâ THREE ISLAND\n"
    .string "hjalp mig med at udvide mine varer.$"

TwoIsland_Text_HopeYouGiveItYourBest::
    .string "Hej! Jeg giver den bedste her.\n"
    .string "Jeg hâber du ogsâ gør det, {PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands::
    .string "Aah, hej, {PLAYER}!\n"
    .string "Velkommen!\p"
    .string "Jeg er begyndt at hente varer fra\n"
    .string "fjerne lande.\p"
    .string "Jeg har ogsâ nogle sjældne varer.\n"
    .string "Kig venligst!$"

TwoIsland_Text_FellowMovedFromCeladonCity::
    .string "Den fyr derovre flyttede herfra\n"
    .string "CELADON CITY.\p"
    .string "Han startede en butik med sin\n"
    .string "yngre bror.\p"
    .string "Man mâ undre sig om han vidste\n"
    .string "hvad han gik til.$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
    .string "Butiksejerens bror tog et job\n"
    .string "i GAME CORNER.\p"
    .string "Han prøver at skrabe penge sammen\n"
    .string "sâ de kan købe flere varer.$"

TwoIsland_Text_BrunoCameToIslandWhileBack::
    .string "Hør, hør.\n"
    .string "Vidste du det?\p"
    .string "En berømt TRAINER kom til\n"
    .string "Øen for ikke længe siden.\p"
    .string "Han er en af ELITE FOUR.\n"
    .string "Hans navn er BRUNO.\p"
    .string "Han gik skuffet væk da han fandt\n"
    .string "ud af at Rage Candybars var\l"
    .string "udsolgt.$"

TwoIsland_Text_BuyRareItemsHere::
    .string "Den kritiske TRAINER ved at\n"
    .string "købe sjældne varer her!$"

TwoIsland_Text_OldWomanLivesOutOnCape::
    .string "Der er en gammel dame der bor i\n"
    .string "et hus ude pâ næsset.\p"
    .string "Hun giver POKéMON øjenene.\n"
    .string "Det er lidt uhyggeligt.$"

TwoIsland_Text_HaveYouTriedJumpingGame::
    .string "Boing! Boing!\n"
    .string "Har du prøvet hoppespillet?\p"
    .string "Den POKéMON du kan bruge…\n"
    .string "Boing!\p"
    .string "Nogle hopper boing!\p"
    .string "Og nogle hopper boooooooing!\p"
    .string "Vidste du det?\n"
    .string "Boing!$"

