TwoIsland_Text_IslandSign::
    .string "TWO ISLAND\n"
    .string "Velsignelsesoen for to$"

TwoIsland_Text_JoyfulGameCornerSign::
    .string "Skip & Chomp!\n"
    .string "Joyful GAME CORNER$"

TwoIsland_Text_DangerFastCurrent::
    .string "FARE! STAERK STROEMNING!\n"
    .string "Fiskeri og surfing forbudt!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
    .string "Aah!\n"
    .string "Hej, velkommen til min butik!\p"
    .string "Vi har kun lige aabnet.\p"
    .string "Vores varer er begraensede, men jeg\n"
    .string "haaber vi kan daekke dine behov.$"

TwoIsland_Text_AddedMerchandiseForLostelle::
    .string "Jeg kan ikke sige hvor taknemmelig jeg er\n"
    .string "for at du reddede LOSTELLE.\p"
    .string "Takket vaere din bedrift har folk paa\n"
    .string "THREE ISLAND aendret holdning til\l"
    .string "KANTO-folk.\p"
    .string "Og jeg er fra KANTO, ser du.\p"
    .string "Folkene paa THREE ISLAND\n"
    .string "hjalp mig med at udvide mine varer.$"

TwoIsland_Text_HopeYouGiveItYourBest::
    .string "Hej! Jeg giver den bedste her.\n"
    .string "Jeg haaber du ogsaa goer det, {PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands::
    .string "Aah, hej, {PLAYER}!\n"
    .string "Velkommen!\p"
    .string "Jeg er begyndt at hente varer fra\n"
    .string "fjerne lande.\p"
    .string "Jeg har ogsaa nogle sjaeldne varer.\n"
    .string "Kig venligst!$"

TwoIsland_Text_FellowMovedFromCeladonCity::
    .string "Den fyr derovre flyttede herfra\n"
    .string "CELADON CITY.\p"
    .string "Han startede en butik med sin\n"
    .string "yngre bror.\p"
    .string "Man maa undre sig om han vidste\n"
    .string "hvad han gik til.$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
    .string "Butiksejerens bror tog et job\n"
    .string "i GAME CORNER.\p"
    .string "Han proever at skrabe penge sammen\n"
    .string "saa de kan koebe flere varer.$"

TwoIsland_Text_BrunoCameToIslandWhileBack::
    .string "Hoer, hoer.\n"
    .string "Vidste du det?\p"
    .string "En beroemt TRAINER kom til\n"
    .string "OeEN for ikke laenge siden.\p"
    .string "Han er en af ELITE FOUR.\n"
    .string "Hans navn er BRUNO.\p"
    .string "Han gik skuffet vaek da han fandt\n"
    .string "ud af at Rage Candybars var\l"
    .string "udsolgt.$"

TwoIsland_Text_BuyRareItemsHere::
    .string "Den kritiske TRAINER ved at\n"
    .string "koebe sjaeldne varer her!$"

TwoIsland_Text_OldWomanLivesOutOnCape::
    .string "Der er en gammel dame der bor i\n"
    .string "et hus ude paa naesset.\p"
    .string "Hun giver POKeMON oejenene.\n"
    .string "Det er lidt uhyggeligt.$"

TwoIsland_Text_HaveYouTriedJumpingGame::
    .string "Boing! Boing!\n"
    .string "Har du proevet hoppespillet?\p"
    .string "Den POKeMON du kan bruge…\n"
    .string "Boing!\p"
    .string "Nogle hopper boing!\p"
    .string "Og nogle hopper boooooooing!\p"
    .string "Vidste du det?\n"
    .string "Boing!$"

