TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner::
    .string "Har du besøgt GAME CORNER\n"
    .string "allerede?\p"
    .string "Det er ikke godt at tage af sted alene.\n"
    .string "Du skal tage en ven med.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape::
    .string "Der bor ikke mange mennesker pâ\n"
    .string "TWO ISLAND.\p"
    .string "Der er denne gamle dame der bor\n"
    .string "ude pâ næsset.\p"
    .string "Hun har bøt der siden jeg ikke\n"
    .string "ved hvornâr.$"

