TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner::
    .string "Har du besoegt GAME CORNER\n"
    .string "allerede?\p"
    .string "Det er ikke godt at tage af sted alene.\n"
    .string "Du skal tage en ven med.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape::
    .string "Der bor ikke mange mennesker paa\n"
    .string "TWO ISLAND.\p"
    .string "Der er denne gamle dame der bor\n"
    .string "ude paa naesset.\p"
    .string "Hun har boet der siden jeg ikke\n"
    .string "ved hvornaar.$"

