FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .string "SELPHY: Øh?\n"
    .string "Kender jeg dig et sted fra?\p"
    .string "Men det er lige meget.\p"
    .string "Jeg keder mig uendeligt.\n"
    .string "Hör venligst min önskning.$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .string "Jeg vil gerne se en POKéMON.\n"
    .string "En söd {STR_VAR_1}.\p"
    .string "Jeg vil se en med det samme.\n"
    .string "Opfyld venligst min önskning.$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .string "SELPHY: Av, jeg er trät af det.\n"
    .string "Jeg er trät af at vente pâ dig.\p"
    .string "Jeg tilgiver dig denne gang, men\n"
    .string "vär venlig ikke at skuffe näste gang.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "SELPHY: Øh, hej.\p"
    .string "Øh, du godeste. Det mâ väre den\n"
    .string "{STR_VAR_1}, du fangede til mig.\p"
    .string "Fnise…\n"
    .string "Den ligner dig.\p"
    .string "Mange tak.\p"
    .string "… …  … …  … …\n"
    .string "Er der noget galt?\p"
    .string "Du mâ gâ.\p"
    .string "… …  … …  … …\n"
    .string "Nâja, jeg forstâr nu.\p"
    .string "SEBASTIAN!\n"
    .string "Jeg har brug for dig med det samme!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "Butler: Ja, min frue.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "SELPHY: Sörg for at denne person\n"
    .string "fâr en takkegaver.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "Butler: Jeg gör som De befaler,\n"
    .string "min frue.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "Butler: Jeg takker oprigtigt for at\n"
    .string "De gjorde frue SELPHY tilpas.\p"
    .string "Modtag venligst dette som hendes\n"
    .string "tak…$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .string "Butler: Din TASKE lader til at väre\n"
    .string "desvärre fuld.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .string "Øh…\n"
    .string "Sâ skuffende.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "SELPHY: Jeg önsker dig al mulig\n"
    .string "lykke.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "Butler: Frue SELPHYs smil har\n"
    .string "solens glans.\p"
    .string "Jeg beder dig bringe gläde til\n"
    .string "frue SELPHY.$"

