FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .string "SELPHY: Oeh?\n"
    .string "Kender jeg dig et sted fra?\p"
    .string "Men det er lige meget.\p"
    .string "Jeg keder mig uendeligt.\n"
    .string "Hoer venligst min oenskning.$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .string "Jeg vil gerne se en POKeMON.\n"
    .string "En soed {STR_VAR_1}.\p"
    .string "Jeg vil se en med det samme.\n"
    .string "Opfyld venligst min oenskning.$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .string "SELPHY: Av, jeg er traet af det.\n"
    .string "Jeg er traet af at vente paa dig.\p"
    .string "Jeg tilgiver dig denne gang, men\n"
    .string "vaer venlig ikke at skuffe naeste gang.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "SELPHY: Oeh, hej.\p"
    .string "Oeh, du godeste. Det maa vaere den\n"
    .string "{STR_VAR_1}, du fangede til mig.\p"
    .string "Fnise…\n"
    .string "Den ligner dig.\p"
    .string "Mange tak.\p"
    .string "… …  … …  … …\n"
    .string "Er der noget galt?\p"
    .string "Du maa gaa.\p"
    .string "… …  … …  … …\n"
    .string "Naaja, jeg forstaar nu.\p"
    .string "SEBASTIAN!\n"
    .string "Jeg har brug for dig med det samme!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "Butler: Ja, min frue.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "SELPHY: Soerg for at denne person\n"
    .string "faar en takkegaver.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "Butler: Jeg goer som De befaler,\n"
    .string "min frue.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "Butler: Jeg takker oprigtigt for at\n"
    .string "De gjorde frue SELPHY tilpas.\p"
    .string "Modtag venligst dette som hendes\n"
    .string "tak…$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .string "Butler: Din TASKE lader til at vaere\n"
    .string "desvaerre fuld.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .string "Oeh…\n"
    .string "Saa skuffende.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "SELPHY: Jeg oensker dig al mulig\n"
    .string "lykke.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "Butler: Frue SELPHYs smil har\n"
    .string "solens glans.\p"
    .string "Jeg beder dig bringe glaede til\n"
    .string "frue SELPHY.$"

