FiveIsland_LostCave_Room4_Text_LauraIntro::
    .string "Jeg tror der er en mystisk kraft\n"
    .string "i virke i denne hule.$"

FiveIsland_LostCave_Room4_Text_LauraDefeat::
    .string "Hvis du ikke gaar ind i den rigtige\n"
    .string "tunnel, kommer du ikke videre.$"

FiveIsland_LostCave_Room4_Text_LauraPostBattle::
    .string "Tidligere gik en dame ind i\n"
    .string "hulerne laengere fremme.$"

