Route16_Text_LaoIntro::
    .string "Hvad vil du?$"

Route16_Text_LaoDefeat::
    .string "Vag dig for at grine!$"

Route16_Text_LaoPostBattle::
    .string "Vi kan bare lide at haenge her.\n"
    .string "Hvad raeger det dig?$"

Route16_Text_KojiIntro::
    .string "Fin CYKEL!\n"
    .string "Aflever den!$"

Route16_Text_KojiDefeat::
    .string "Knockout!$"

Route16_Text_KojiPostBattle::
    .string "Glem det, hvem har brug for din CYKEL!$"

Route16_Text_LukeIntro::
    .string "Kom ud og leg, lille mus!$"

Route16_Text_LukeDefeat::
    .string "Din lille rotte!$"

Route16_Text_LukePostBattle::
    .string "Jeg hader at tabe!\n"
    .string "Forsvind fra mig!$"

Route16_Text_HideoIntro::
    .string "Hey, du stodte lige mig!$"

Route16_Text_HideoDefeat::
    .string "Kaboom!$"

Route16_Text_HideoPostBattle::
    .string "Vi haenger altid her\n"
    .string "selv om du ikke kan lide det.\p"
    .string "Du kan koere omvej til VERMILION\n"
    .string "fra FUCHSIA langs kysten.$"

Route16_Text_CamronIntro::
    .string "Jeg er sulten og ond!\n"
    .string "Jeg har brug for en punchingsaek!$"

Route16_Text_CamronDefeat::
    .string "Daarligt, daarligt, daarligt!$"

Route16_Text_CamronPostBattle::
    .string "Hvis jeg skal have POKeMON, kan de\n"
    .string "lige saa godt vaere vilde.\p"
    .string "Jeg ville bruge dem til at efterlade\n"
    .string "mine fjender i stykker.$"

Route16_Text_RubenIntro::
    .string "Hey, der!\n"
    .string "Lad os more os ordentligt!$"

Route16_Text_RubenDefeat::
    .string "Goer mig ikke vred!$"

Route16_Text_RubenPostBattle::
    .string "Jeg faar kicks af at chikanere folk\n"
    .string "med mine stinkende POKeMON.\p"
    .string "De er gode til at skraemme folk.\n"
    .string "Og de bider ogsaa.$"

Route16_Text_MonSprawledOutInSlumber::
    .string "En POKeMON ligger og sover dybt\n"
    .string "og behageligt.$"

Route16_Text_CyclingRoadSign::
    .string "Nyd skraaningen!\n"
    .string "CYKELVEJ$"

Route16_Text_RouteSign::
    .string "ROUTE 16\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route16_Text_JedIntro::
    .string "JED: Vor kaerlighed kender ingen\n"
    .string "graenser. Vi er forelskede!$"

Route16_Text_JedDefeat::
    .string "JED: Aa, nej!\n"
    .string "Min kaerlighed saa mig som taber!$"

Route16_Text_JedPostBattle::
    .string "JED: Hor, LEA.\n"
    .string "Du skal fokusere mindre paa mig.$"

Route16_Text_JedNotEnoughMons::
    .string "JED: Du har kun en POKeMON?\n"
    .string "Er der ingen kaerlighed i dit hjerte?$"

Route16_Text_LeaIntro::
    .string "LEA: Nogle gange skraemmer styrken\n"
    .string "af vor kaerlighed mig.$"

Route16_Text_LeaDefeat::
    .string "LEA: Aah! Men JED ser sej ud\n"
    .string "selv i nederlag!$"

Route16_Text_LeaPostBattle::
    .string "LEA: Ehehe, undskyld.\n"
    .string "JED er saa sej.$"

Route16_Text_LeaNotEnoughMons::
    .string "LEA: Aa, du har ikke to\n"
    .string "POKeMON med dig?\p"
    .string "Foeles det ikke ensomt for dig eller\n"
    .string "dine POKeMON?$"
