Route6_Text_RickyIntro::
    .string "Hvem er der?\n"
    .string "Hold op med at lytte til os!$"

Route6_Text_RickyDefeat::
    .string "Jeg kan bare ikke vinde!$"

Route6_Text_RickyPostBattle::
    .string "Hvisken…\n"
    .string "Hvisken…$"

Route6_Text_NancyIntro::
    .string "Undskyld!\n"
    .string "Det her er en privat samtale!$"

Route6_Text_NancyDefeat::
    .string "Ugh!\n"
    .string "Jeg hader at tabe.$"

Route6_Text_NancyPostBattle::
    .string "Hvisken…\n"
    .string "Hvisken…$"

Route6_Text_KeigoIntro::
    .string "Der er ikke mange insekter her.$"

Route6_Text_KeigoDefeat::
    .string "Nej!\n"
    .string "Du laver sjov!$"

Route6_Text_KeigoPostBattle::
    .string "Jeg kan lide insekter, saa jeg tager\n"
    .string "tilbage til VIRIDIAN FOREST.$"

Route6_Text_JeffIntro::
    .string "Hvad?\n"
    .string "Vil du tale med mig?$"

Route6_Text_JeffDefeat::
    .string "Det her stinker…\n"
    .string "Jeg kunne ikke slaa din udfordring…$"

Route6_Text_JeffPostBattle::
    .string "Jeg burde tage flere POKeMON med.\n"
    .string "Saadan foeler jeg mig mere sikker.$"

Route6_Text_IsabelleIntro::
    .string "Mig?\n"
    .string "Okay, jeg spiller med!$"

Route6_Text_IsabelleDefeat::
    .string "Det gik bare ikke…$"

Route6_Text_IsabellePostBattle::
    .string "Jeg vil blive staerkere.\n"
    .string "Hvad er din hemmelighed?$"

Route6_Text_ElijahIntro::
    .string "Jeg har aldrig set dig her.\n"
    .string "Er du god?$"

Route6_Text_ElijahDefeat::
    .string "Du er for god!$"

Route6_Text_ElijahPostBattle::
    .string "Er mine POKeMON svage?\n"
    .string "Eller er jeg bare daarlig?\l"
    .string "Hvad synes du?$"

Route6_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CERULEAN CITY - VERMILION CITY$"
