CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Kun dygtige TRAINERS kan samle\n"
    .string "POKeMON BADGES.\p"
    .string "Jeg ser du har mindst een.\p"
    .string "Disse BADGES har fantastiske hemmeligheder,\n"
    .string "vidste du det?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Naar saa…\p"
    .string "Hvilken af de otte BADGES skal\n"
    .string "jeg beskrive?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Kom og besoeg mig naar du vil.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "ATTACK staten af alle dine\n"
    .string "POKeMON oeger en lille smule.\p"
    .string "Den lader dig ogsaa bruge tricket\n"
    .string "FLASH uden for kamp.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "POKeMON op til Lv. 30 vil adlyde\n"
    .string "dig.\p"
    .string "Det inkluderer endda dem du faar\n"
    .string "ved bytte.\p"
    .string "POKeMON paa hoejere niveauer vil\n"
    .string "vaere urolige i kamp, dog.\p"
    .string "Den lader dig ogsaa bruge tricket\n"
    .string "CUT uden for kamp.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "SPEED staten af alle dine\n"
    .string "POKeMON oeger en lille smule.\p"
    .string "Den lader dig ogsaa bruge tricket\n"
    .string "FLY uden for kamp.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "POKeMON op til Lv. 50 vil adlyde\n"
    .string "dig.\p"
    .string "Det inkluderer endda dem du faar\n"
    .string "ved bytte.\p"
    .string "POKeMON paa hoejere niveauer vil\n"
    .string "vaere urolige i kamp, dog.\p"
    .string "Den lader dig ogsaa bruge tricket\n"
    .string "STRENGTH uden for kamp.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "DEFENSE staten af alle dine\n"
    .string "POKeMON oeger en lille smule.\p"
    .string "Den lader dig ogsaa bruge tricket\n"
    .string "SURF uden for kamp.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "POKeMON op til Lv. 70 vil adlyde\n"
    .string "dig.\p"
    .string "Det inkluderer endda dem du faar\n"
    .string "ved bytte.\p"
    .string "POKeMON paa hoejere niveauer vil\n"
    .string "vaere urolige i kamp, dog.\p"
    .string "Den lader dig ogsaa bruge tricket\n"
    .string "ROCK SMASH uden for kamp.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "SP. ATK og SP. DEF staten af\n"
    .string "alle dine POKeMON stiger en smule.\p"
    .string "Den lader dig ogsaa bruge tricket\n"
    .string "WATERFALL uden for kamp.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "Alle POKeMON vil adlyde dig!$"
