ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Brug endelig den PC i hjørnet.\p"
    .string "Receptionisten sagde det til mig.\n"
    .string "Hvor venligt af hende!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "Der er et POKéMON CENTER i hver\n"
    .string "by forude.\p"
    .string "De tager ikke penge, sâ vær ikke\n"
    .string "genert med at helbrede POKéMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "POKéMON CENTRES helbreder dine trætte,\n"
    .string "sârede eller besvimede POKéMON.\p"
    .string "De gør alle POKéMON fuldstændigt\n"
    .string "sunde.$"

