ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Brug endelig den PC i hjoernet.\p"
    .string "Receptionisten sagde det til mig.\n"
    .string "Hvor venligt af hende!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "Der er et POKeMON CENTER i hver\n"
    .string "by forude.\p"
    .string "De tager ikke penge, saa vaer ikke\n"
    .string "genert med at helbrede POKeMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "POKeMON CENTRES helbreder dine traette,\n"
    .string "saarede eller besvimede POKeMON.\p"
    .string "De goer alle POKeMON fuldstaendigt\n"
    .string "sunde.$"

