ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Brug endelig den PC i hjörnet.\p"
    .string "Receptionisten sagde det til mig.\n"
    .string "Hvor venligt af hende!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "Der er et POKéMON CENTER i hver\n"
    .string "by forude.\p"
    .string "De tager ikke penge, sâ vär ikke\n"
    .string "genert med at helbrede POKéMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "POKéMON CENTRES helbreder dine trätte,\n"
    .string "sârede eller besvimede POKéMON.\p"
    .string "De gör alle POKéMON fuldständigt\n"
    .string "sunde.$"

