Route3_Text_TunnelFromCeruleanTiring::
    .string "Puha… Jeg maa tage en pause…\n"
    .string "Stoen…\p"
    .string "Tunnelen fra CERULEAN tager alt\n"
    .string "energien fra en!$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "Jeg sa dig i VIRIDIAN FOREST!$"

Route3_Text_ColtonDefeat::
    .string "Du slog mig igen!$"

Route3_Text_ColtonPostBattle::
    .string "Der findes andre slags POKeMON\n"
    .string "end dem du finder i skove.$"

Route3_Text_BenIntro::
    .string "Hej!\n"
    .string "Jeg kan lide shorts!\p"
    .string "De er dejligt behagelige og\n"
    .string "lette at have paa!$"

Route3_Text_BenDefeat::
    .string "Det troer jeg ikke paa!$"

Route3_Text_BenPostBattle::
    .string "Bruger du et POKeMON CENTERs PC\n"
    .string "til at opbevare dine POKeMON?\p"
    .string "Hver BOX kan indeholde op til\n"
    .string "30 POKeMON.$"

Route3_Text_JaniceIntro::
    .string "Undskyld!\n"
    .string "Du kiggede paa mig, gjorde du ikke?$"

Route3_Text_JaniceDefeat::
    .string "Du er ond!$"

Route3_Text_JanicePostBattle::
    .string "Du burde ikke glo, hvis du ikke\n"
    .string "vil kaempe!$"

Route3_Text_GregIntro::
    .string "Er du en TRAINER?\n"
    .string "Lad os komme i gang med det samme!$"

Route3_Text_GregDefeat::
    .string "Havde jeg haft nye POKeMON, havde\n"
    .string "jeg vundet!$"

Route3_Text_GregPostBattle::
    .string "Hvis en POKeMON BOX paa PC'en\n"
    .string "bliver fuld, skift bare til en anden BOX.$"

Route3_Text_SallyIntro::
    .string "Det blik du gav mig…\n"
    .string "Det er saaa spaendende!$"

Route3_Text_SallyDefeat::
    .string "Vaer soed!$"

Route3_Text_SallyPostBattle::
    .string "Du kan undgaa kampe ved ikke at\n"
    .string "lade TRAINERs se dig.$"

Route3_Text_CalvinIntro::
    .string "Hey! Du har ikke shorts paa!\n"
    .string "Hvad er der galt med dig?$"

Route3_Text_CalvinDefeat::
    .string "Tabt!\n"
    .string "Tabt! Tabt!$"

Route3_Text_CalvinPostBattle::
    .string "Jeg har altid shorts paa, selv om\n"
    .string "vinteren. Det er min politik.$"

Route3_Text_JamesIntro::
    .string "Jeg kaemper mod dig med de POKeMON\n"
    .string "jeg lige har fanget.$"

Route3_Text_JamesDefeat::
    .string "Faerdig som aftensmad!$"

Route3_Text_JamesPostBattle::
    .string "Traenede POKeMON er staerkere end\n"
    .string "de vilde.$"

Route3_Text_RobinIntro::
    .string "Av!\n"
    .string "Roerte du mig?$"

Route3_Text_RobinDefeat::
    .string "Var det det?$"

Route3_Text_RobinPostBattle::
    .string "ROUTE 4 er ved foden af\n"
    .string "MT. MOON.$"

Route3_Text_RouteSign::
    .string "ROUTE 3\n"
    .string "MT. MOON LIGGER FORAN$"
