Route3_Text_TunnelFromCeruleanTiring::
    .string "Puha… Jeg mâ tage en pause…\n"
    .string "Stön…\p"
    .string "Tunnelen fra CERULEAN tager alt\n"
    .string "energien fra en!$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "Jeg sa dig i VIRIDIAN FOREST!$"

Route3_Text_ColtonDefeat::
    .string "Du slog mig igen!$"

Route3_Text_ColtonPostBattle::
    .string "Der findes andre slags POKéMON\n"
    .string "end dem du finder i skove.$"

Route3_Text_BenIntro::
    .string "Hej!\n"
    .string "Jeg kan lide shorts!\p"
    .string "De er dejligt behagelige og\n"
    .string "lette at have pâ!$"

Route3_Text_BenDefeat::
    .string "Det trör jeg ikke pâ!$"

Route3_Text_BenPostBattle::
    .string "Bruger du et POKéMON CENTERs PC\n"
    .string "til at opbevare dine POKéMON?\p"
    .string "Hver BOX kan indeholde op til\n"
    .string "30 POKéMON.$"

Route3_Text_JaniceIntro::
    .string "Undskyld!\n"
    .string "Du kiggede pâ mig, gjorde du ikke?$"

Route3_Text_JaniceDefeat::
    .string "Du er ond!$"

Route3_Text_JanicePostBattle::
    .string "Du burde ikke glo, hvis du ikke\n"
    .string "vil kämpe!$"

Route3_Text_GregIntro::
    .string "Er du en TRAINER?\n"
    .string "Lad os komme i gang med det samme!$"

Route3_Text_GregDefeat::
    .string "Havde jeg haft nye POKéMON, havde\n"
    .string "jeg vundet!$"

Route3_Text_GregPostBattle::
    .string "Hvis en POKéMON BOX pâ PC'en\n"
    .string "bliver fuld, skift bare til en anden BOX.$"

Route3_Text_SallyIntro::
    .string "Det blik du gav mig…\n"
    .string "Det er sâa spändende!$"

Route3_Text_SallyDefeat::
    .string "Vär söd!$"

Route3_Text_SallyPostBattle::
    .string "Du kan undgâ kampe ved ikke at\n"
    .string "lade TRAINERs se dig.$"

Route3_Text_CalvinIntro::
    .string "Hey! Du har ikke shorts pâ!\n"
    .string "Hvad er der galt med dig?$"

Route3_Text_CalvinDefeat::
    .string "Tabt!\n"
    .string "Tabt! Tabt!$"

Route3_Text_CalvinPostBattle::
    .string "Jeg har altid shorts pâ, selv om\n"
    .string "vinteren. Det er min politik.$"

Route3_Text_JamesIntro::
    .string "Jeg kämper mod dig med de POKéMON\n"
    .string "jeg lige har fanget.$"

Route3_Text_JamesDefeat::
    .string "Färdig som aftensmad!$"

Route3_Text_JamesPostBattle::
    .string "Tränede POKéMON er stärkere end\n"
    .string "de vilde.$"

Route3_Text_RobinIntro::
    .string "Av!\n"
    .string "Rörte du mig?$"

Route3_Text_RobinDefeat::
    .string "Var det det?$"

Route3_Text_RobinPostBattle::
    .string "ROUTE 4 er ved foden af\n"
    .string "MT. MOON.$"

Route3_Text_RouteSign::
    .string "ROUTE 3\n"
    .string "MT. MOON LIGGER FORAN$"
