SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
    .string "POKeMON har deres egen personlighed,\n"
    .string "ligesom mennesker.\p"
    .string "Min PIKACHU har en HASTY natur,\n"
    .string "saa den blev en hurtig POKeMON.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
    .string "Okay, forberedelserne er faerdige\n"
    .string "til at jeg kan udforske RUINS.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
    .string "Jeg skal fiske paa SEVEN ISLAND.\p"
    .string "Det vil fuldende min fisketur\n"
    .string "gennem SEVII ISLANDS.\p"
    .string "Jeg boer lige koebe nogle\n"
    .string "POKe BALLS foerst.$"

