Text_DoubleEdgeTeach::
    .string "Du skal vaere stolt af dig selv,\n"
    .string "som har kaempet dig igennem\l"
    .string "VICTORY ROAD saa modigt.\p"
    .string "Som anerkendelse af din bedrift\n"
    .string "laerer jeg dig DOUBLE-EDGE.\p"
    .string "Vil du have mig til at laere den\n"
    .string "teknik?$"

Text_DoubleEdgeDeclined::
    .string "Jeg laerer dig teknikken\n"
    .string "naar som helst.$"

Text_DoubleEdgeWhichMon::
    .string "Hvilken POKeMON skal jeg laere\n"
    .string "DOUBLE-EDGE?$"

Text_DoubleEdgeTaught::
    .string "Hold den drive koerende mod\n"
    .string "POKeMON LEAGUE!\p"
    .string "Loeb ind i dem og slaa dem ud!$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "Jeg hoerte rygter om et vidunderbarn.$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "Rygterne var sande!$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "Saa det var dig der besejrede GIOVANNI\n"
    .string "fra TEAM ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "TRAeNERE lever for at soege staerkere\n"
    .string "modstandere.$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "Aah!\n"
    .string "Saa staerk!$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "Ved at kaempe haarde kampe bliver man\n"
    .string "staerkere.$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "Jeg viser dig lige hvor god du\n"
    .string "er. Ikke!$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "Jeg er rasende!$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "Du viste mig lige hvor god\n"
    .string "jeg var…$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "Kun de udvalgte kan passere her!$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "Jeg tror det ikke!$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "Alle TRAeNERE her er paa vej til\n"
    .string "POKeMON LEAGUE.\p"
    .string "Slap ikke af med vagtsomheden.$"

VictoryRoad_3F_Text_RayIntro::
    .string "RAY: Sammen er vi to bestemt for\n"
    .string "storhed!$"

VictoryRoad_3F_Text_RayDefeat::
    .string "RAY: Latterligt!\n"
    .string "Det kan ikke vaere sandt!$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "RAY: Du har besejret os.\n"
    .string "Storhed forbliver uopnaaelig…$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "RAY: Sammen straeber vi to efter\n"
    .string "tinden.\p"
    .string "Du skal have to POKeMON med\n"
    .string "i kamp mod os.$"

VictoryRoad_3F_Text_TyraIntro::
    .string "TYRA: Vi proever at blive mestre\n"
    .string "sammen.$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "TYRA: Aah, men…$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "TYRA: Du har laert mig at styrke\n"
    .string "kan vaere uendelig i form og skikkelse.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "TYRA: Du kan ikke kaempe med os hvis\n"
    .string "du kun har en POKeMON.$"

