Text_DoubleEdgeTeach::
    .string "Du skal väre stolt af dig selv,\n"
    .string "som har kämpet dig igennem\l"
    .string "VICTORY ROAD sâ modigt.\p"
    .string "Som anerkendelse af din bedrift\n"
    .string "lärer jeg dig DOUBLE-EDGE.\p"
    .string "Vil du have mig til at läre den\n"
    .string "teknik?$"

Text_DoubleEdgeDeclined::
    .string "Jeg lärer dig teknikken\n"
    .string "nâr som helst.$"

Text_DoubleEdgeWhichMon::
    .string "Hvilken POKeMON skal jeg läre\n"
    .string "DOUBLE-EDGE?$"

Text_DoubleEdgeTaught::
    .string "Hold den drive körende mod\n"
    .string "POKeMON LEAGUE!\p"
    .string "Löb ind i dem og slâ dem ud!$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "Jeg hörte rygter om et vidunderbarn.$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "Rygterne var sande!$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "Sâ det var dig der besejrede GIOVANNI\n"
    .string "fra TEAM ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "TRAeNERE lever for at söge stärkere\n"
    .string "modstandere.$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "Aah!\n"
    .string "Sâ stärk!$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "Ved at kämpe hârde kampe bliver man\n"
    .string "stärkere.$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "Jeg viser dig lige hvor god du\n"
    .string "er. Ikke!$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "Jeg er rasende!$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "Du viste mig lige hvor god\n"
    .string "jeg var…$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "Kun de udvalgte kan passere her!$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "Jeg tror det ikke!$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "Alle TRAeNERE her er pâ vej til\n"
    .string "POKeMON LEAGUE.\p"
    .string "Slap ikke af med vagtsomheden.$"

VictoryRoad_3F_Text_RayIntro::
    .string "RAY: Sammen er vi to bestemt for\n"
    .string "storhed!$"

VictoryRoad_3F_Text_RayDefeat::
    .string "RAY: Latterligt!\n"
    .string "Det kan ikke väre sandt!$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "RAY: Du har besejret os.\n"
    .string "Storhed forbliver uopnâelig…$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "RAY: Sammen sträber vi to efter\n"
    .string "tinden.\p"
    .string "Du skal have to POKeMON med\n"
    .string "i kamp mod os.$"

VictoryRoad_3F_Text_TyraIntro::
    .string "TYRA: Vi pröver at blive mestre\n"
    .string "sammen.$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "TYRA: Aah, men…$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "TYRA: Du har lärt mig at styrke\n"
    .string "kan väre uendelig i form og skikkelse.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "TYRA: Du kan ikke kämpe med os hvis\n"
    .string "du kun har en POKeMON.$"

