Text_DoubleEdgeTeach::
    .string "Du skal være stolt af dig selv,\n"
    .string "som har kæmpet dig igennem\l"
    .string "VICTORY ROAD sâ modigt.\p"
    .string "Som anerkendelse af din bedrift\n"
    .string "lærer jeg dig DOUBLE-EDGE.\p"
    .string "Vil du have mig til at lære den\n"
    .string "teknik?$"

Text_DoubleEdgeDeclined::
    .string "Jeg lærer dig teknikken\n"
    .string "nâr som helst.$"

Text_DoubleEdgeWhichMon::
    .string "Hvilken POKéMON skal jeg lære\n"
    .string "DOUBLE-EDGE?$"

Text_DoubleEdgeTaught::
    .string "Hold den drive kørende mod\n"
    .string "POKéMON LEAGUE!\p"
    .string "Løb ind i dem og slâ dem ud!$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "Jeg hørte rygter om et vidunderbarn.$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "Rygterne var sande!$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "Sâ det var dig der besejrede GIOVANNI\n"
    .string "fra TEAM ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "TRÆNERE lever for at søge stærkere\n"
    .string "modstandere.$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "Aah!\n"
    .string "Sâ stærk!$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "Ved at kæmpe hârde kampe bliver man\n"
    .string "stærkere.$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "Jeg viser dig lige hvor god du\n"
    .string "er. Ikke!$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "Jeg er rasende!$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "Du viste mig lige hvor god\n"
    .string "jeg var…$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "Kun de udvalgte kan passere her!$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "Jeg tror det ikke!$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "Alle TRÆNERE her er pâ vej til\n"
    .string "POKéMON LEAGUE.\p"
    .string "Slap ikke af med vagtsomheden.$"

VictoryRoad_3F_Text_RayIntro::
    .string "RAY: Sammen er vi to bestemt for\n"
    .string "storhed!$"

VictoryRoad_3F_Text_RayDefeat::
    .string "RAY: Latterligt!\n"
    .string "Det kan ikke være sandt!$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "RAY: Du har besejret os.\n"
    .string "Storhed forbliver uopnâelig…$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "RAY: Sammen stræber vi to efter\n"
    .string "tinden.\p"
    .string "Du skal have to POKéMON med\n"
    .string "i kamp mod os.$"

VictoryRoad_3F_Text_TyraIntro::
    .string "TYRA: Vi prøver at blive mestre\n"
    .string "sammen.$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "TYRA: Aah, men…$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "TYRA: Du har lært mig at styrke\n"
    .string "kan være uendelig i form og skikkelse.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "TYRA: Du kan ikke kæmpe med os hvis\n"
    .string "du kun har en POKéMON.$"

