FiveIsland_Text_IslandSign::
    .string "FEM OE\n"
    .string "Chrono Island: Hvor tiden gaar$"

FiveIsland_Text_WeirdBuildingInMeadow::
    .string "Av, det er traels. Jeg ville lege i\n"
    .string "ENGEN.\p"
    .string "Men de har bygget et underligt\n"
    .string "hus der, saa jeg kan ikke lege der.$"

FiveIsland_Text_BeenGettingBusierAroundHere::
    .string "Det er blevet mere liv her omkring\n"
    .string "paa det sidste.\p"
    .string "Jeg faar ikke fanget saerlig mange\n"
    .string "gode fisk for tiden, heller.$"

