FiveIsland_Text_IslandSign::
    .string "FEM Ø\n"
    .string "Chrono Island: Hvor tiden gâr$"

FiveIsland_Text_WeirdBuildingInMeadow::
    .string "Av, det er træls. Jeg ville lege i\n"
    .string "ENGEN.\p"
    .string "Men de har bygget et underligt\n"
    .string "hus der, sâ jeg kan ikke lege der.$"

FiveIsland_Text_BeenGettingBusierAroundHere::
    .string "Det er blevet mere liv her omkring\n"
    .string "pâ det sidste.\p"
    .string "Jeg fâr ikke fanget særlig mange\n"
    .string "gode fisk for tiden, heller.$"

