ViridianForest_Text_FriendsItchingToBattle::
    .string "Jeg kom her med nogle venner for at\n"
    .string "fange BUG POKéMON!\p"
    .string "De er alle ivrige efter at komme i\n"
    .string "POKéMON kampe!$"

ViridianForest_Text_RickIntro::
    .string "Hey! Du har POKéMON!\n"
    .string "Kom an!\l"
    .string "Lad os kämpe med dem!$"

ViridianForest_Text_RickDefeat::
    .string "Nej!\n"
    .string "CATERPIE kan ikke klare det!$"

ViridianForest_Text_RickPostBattle::
    .string "Ssh! Du skrämmer insekterne väk.\n"
    .string "En anden gang, okay?$"

ViridianForest_Text_DougIntro::
    .string "Yo!\n"
    .string "Du kan ikke jamme hvis du er en\l"
    .string "POKéMON TRÄNER!$"

ViridianForest_Text_DougDefeat::
    .string "Huh?\n"
    .string "Jeg löb tör for POKéMON!$"

ViridianForest_Text_DougPostBattle::
    .string "Det stinker totalt! Jeg fanger nogle\n"
    .string "stärkere!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, vent!\n"
    .string "Hvad er travlt? Hvorfor hastvärk?$"

ViridianForest_Text_SammyDefeat::
    .string "Jeg giver op!\n"
    .string "Du er god til det her!$"

ViridianForest_Text_SammyPostBattle::
    .string "Nogle gange kan man finde ting pâ\n"
    .string "jorden.\p"
    .string "Jeg leder efter tingene jeg\n"
    .string "tabte. Kan du hjälpe mig?$"

ViridianForest_Text_AnthonyIntro::
    .string "Jeg er mâske lille, men jeg vil ikke\n"
    .string "lide det hvis du gâr let pâ mig!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Aah, buh.\n"
    .string "Intet gik rigtigt.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "Jeg tabte noget af mine lommepenge…$"

ViridianForest_Text_CharlieIntro::
    .string "Vidste du at POKéMON udvikler sig?$"

ViridianForest_Text_CharlieDefeat::
    .string "Aah!\n"
    .string "Jeg tabte!$"

ViridianForest_Text_CharliePostBattle::
    .string "BUG POKéMON udvikler sig hurtigt.\n"
    .string "De er rigtig sjove!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "Jeg kastede POKe BALLS for at\n"
    .string "fange POKéMON, og jeg löb tör.\p"
    .string "Derfor kan man aldrig have for\n"
    .string "mange POKe BALLS.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "TRÄNER TIPS\p"
    .string "Hvis dine POKéMON er svage og du\n"
    .string "vil undgâ kampe, hold dig väk\l"
    .string "fra gräsomrâder!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "Mod gift, brug ANTIDOTE!\n"
    .string "Fâ det i POKéMON MARTS!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "TRÄNER TIPS\p"
    .string "Kontakt PROF. OAK via en PC for at\n"
    .string "fâ din POKéDEX vurderet!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "TRÄNER TIPS\p"
    .string "Du kan ikke fange en POKéMON der\n"
    .string "tilhörer en anden.\p"
    .string "Kast kun POKe BALLS mod vilde\n"
    .string "POKéMON for at fange dem!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "TRÄNER TIPS\p"
    .string "Sväkk POKéMON för du pröver at\n"
    .string "fange dem!\p"
    .string "Nâr de er sunde, kan de flygte!$"

ViridianForest_Text_LeavingViridianForest::
    .string "FORLADER VIRIDIAN FOREST\n"
    .string "PEWTER CITY FORUDE$"

