ViridianForest_Text_FriendsItchingToBattle::
    .string "Jeg kom her med nogle venner for at\n"
    .string "fange BUG POKeMON!\p"
    .string "De er alle ivrige efter at komme i\n"
    .string "POKeMON kampe!$"

ViridianForest_Text_RickIntro::
    .string "Hey! Du har POKeMON!\n"
    .string "Kom an!\l"
    .string "Lad os kaempe med dem!$"

ViridianForest_Text_RickDefeat::
    .string "Nej!\n"
    .string "CATERPIE kan ikke klare det!$"

ViridianForest_Text_RickPostBattle::
    .string "Ssh! Du skraemmer insekterne vaek.\n"
    .string "En anden gang, okay?$"

ViridianForest_Text_DougIntro::
    .string "Yo!\n"
    .string "Du kan ikke jamme hvis du er en\l"
    .string "POKeMON TRAENER!$"

ViridianForest_Text_DougDefeat::
    .string "Huh?\n"
    .string "Jeg loeb toer for POKeMON!$"

ViridianForest_Text_DougPostBattle::
    .string "Det stinker totalt! Jeg fanger nogle\n"
    .string "staerkere!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, vent!\n"
    .string "Hvad er travlt? Hvorfor hastvaerk?$"

ViridianForest_Text_SammyDefeat::
    .string "Jeg giver op!\n"
    .string "Du er god til det her!$"

ViridianForest_Text_SammyPostBattle::
    .string "Nogle gange kan man finde ting paa\n"
    .string "jorden.\p"
    .string "Jeg leder efter tingene jeg\n"
    .string "tabte. Kan du hjaelpe mig?$"

ViridianForest_Text_AnthonyIntro::
    .string "Jeg er maaske lille, men jeg vil ikke\n"
    .string "lide det hvis du gaar let paa mig!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Aah, buh.\n"
    .string "Intet gik rigtigt.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "Jeg tabte noget af mine lommepenge…$"

ViridianForest_Text_CharlieIntro::
    .string "Vidste du at POKeMON udvikler sig?$"

ViridianForest_Text_CharlieDefeat::
    .string "Aah!\n"
    .string "Jeg tabte!$"

ViridianForest_Text_CharliePostBattle::
    .string "BUG POKeMON udvikler sig hurtigt.\n"
    .string "De er rigtig sjove!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "Jeg kastede POKe BALLS for at\n"
    .string "fange POKeMON, og jeg loeb toer.\p"
    .string "Derfor kan man aldrig have for\n"
    .string "mange POKe BALLS.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "TRAENER TIPS\p"
    .string "Hvis dine POKeMON er svage og du\n"
    .string "vil undgaa kampe, hold dig vaek\l"
    .string "fra graesomraader!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "Mod gift, brug ANTIDOTE!\n"
    .string "Faa det i POKeMON MARTS!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "TRAENER TIPS\p"
    .string "Kontakt PROF. OAK via en PC for at\n"
    .string "faa din POKeDEX vurderet!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "TRAENER TIPS\p"
    .string "Du kan ikke fange en POKeMON der\n"
    .string "tilhoerer en anden.\p"
    .string "Kast kun POKe BALLS mod vilde\n"
    .string "POKeMON for at fange dem!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "TRAENER TIPS\p"
    .string "Svaekk POKeMON foer du proever at\n"
    .string "fange dem!\p"
    .string "Naar de er sunde, kan de flygte!$"

ViridianForest_Text_LeavingViridianForest::
    .string "FORLADER VIRIDIAN FOREST\n"
    .string "PEWTER CITY FORUDE$"

