SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .string "Jeg ser maaske ikke meget ud nu,\n"
    .string "men da jeg var yngre…\p"
    .string "Jeg floej overalt og udfordrede\n"
    .string "TRAINERS hvor jeg fandt dem.\p"
    .string "Nu er min eneste fornoejelse at\n"
    .string "mindes fortiden mens jeg ser kampe.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .string "Der blaeser en let brise omkring\n"
    .string "kassen.$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
    .string "Aah!\n"
    .string "Velkommen, min ven!\p"
    .string "Lad mig fortaelle dig noget. Der er\n"
    .string "et skjult rum i kaelderen.\p"
    .string "En TRAINER ved navn {STR_VAR_1} venter\n"
    .string "der nu.\p"
    .string "Sig mig, du er kommet for at udfordre\n"
    .string "{STR_VAR_1}, er du ikke?$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
    .string "Aah…\n"
    .string "Du vil ikke kaempe…\p"
    .string "Jeg forstaar, jeg forstaar.\n"
    .string "… …\p"
    .string "Tja, hvis du ombestemmer dig,\n"
    .string "kom gerne tilbage.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
    .string "Aah!\n"
    .string "Du vil kaempe for mig?\p"
    .string "Saa var det min tid vaerd at\n"
    .string "flytte kassen til side.\p"
    .string "… …\n"
    .string "Men der er et lille problem.\p"
    .string "Dette skjulte rum er ikke bygget\n"
    .string "saerlig solidt.\p"
    .string "Kan jeg faa dig til at begraense det\n"
    .string "til kampe med tre POKeMON per side?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
    .string "Fint! Foer din kamp, vil du\n"
    .string "gerne gemme spillet?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
    .string "Okay.\n"
    .string "Hold ikke noget tilbage!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
    .string "Kampen endte uafgjort.$"

SevenIsland_House_Room1_Text_DrawWasIt::
    .string "Uafgjort, var det?\p"
    .string "Men lad mig sige at det var\n"
    .string "et vaerdigt syn.\p"
    .string "Jeg vil sige det var en vidunderlig\n"
    .string "kamp med rigtig dybde!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
    .string "Bravo!\p"
    .string "Bravo, ja!\n"
    .string "Hvilken forbloeffende kamp!\p"
    .string "Saa forbloeffende at den konstant\n"
    .string "fylder mine oejne med taarer!\p"
    .string "Stoed og parering af ekspert\n"
    .string "brugte teknikker!\p"
    .string "Klangen af kraft mod kraft!\p"
    .string "Ja!\n"
    .string "Det var ren storhed!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
    .string "Aergerligt!\n"
    .string "Jeg foeler din skuffelse.\p"
    .string "Men den skuffelse er det der\n"
    .string "vil goere dig bedre.\p"
    .string "Brug den, laer af den og lad den\n"
    .string "motivere dig til storhed.\p"
    .string "Glem ikke denne skuffelse og\n"
    .string "fordoble din traening!$"

