SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .string "Jeg ser mâske ikke meget ud nu,\n"
    .string "men da jeg var yngre…\p"
    .string "Jeg fløj overalt og udfordrede\n"
    .string "TRAINERS hvor jeg fandt dem.\p"
    .string "Nu er min eneste fornøjelse at\n"
    .string "mindes fortiden mens jeg ser kampe.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .string "Der blæser en let brise omkring\n"
    .string "kassen.$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
    .string "Aah!\n"
    .string "Velkommen, min ven!\p"
    .string "Lad mig fortælle dig noget. Der er\n"
    .string "et skjult rum i kælderen.\p"
    .string "En TRAINER ved navn {STR_VAR_1} venter\n"
    .string "der nu.\p"
    .string "Sig mig, du er kommet for at udfordre\n"
    .string "{STR_VAR_1}, er du ikke?$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
    .string "Aah…\n"
    .string "Du vil ikke kæmpe…\p"
    .string "Jeg forstâr, jeg forstâr.\n"
    .string "… …\p"
    .string "Tja, hvis du ombestemmer dig,\n"
    .string "kom gerne tilbage.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
    .string "Aah!\n"
    .string "Du vil kæmpe for mig?\p"
    .string "Sâ var det min tid værd at\n"
    .string "flytte kassen til side.\p"
    .string "… …\n"
    .string "Men der er et lille problem.\p"
    .string "Dette skjulte rum er ikke bygget\n"
    .string "særlig solidt.\p"
    .string "Kan jeg fâ dig til at begrænse det\n"
    .string "til kampe med tre POKéMON per side?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
    .string "Fint! Før din kamp, vil du\n"
    .string "gerne gemme spillet?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
    .string "Okay.\n"
    .string "Hold ikke noget tilbage!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
    .string "Kampen endte uafgjort.$"

SevenIsland_House_Room1_Text_DrawWasIt::
    .string "Uafgjort, var det?\p"
    .string "Men lad mig sige at det var\n"
    .string "et værdigt syn.\p"
    .string "Jeg vil sige det var en vidunderlig\n"
    .string "kamp med rigtig dybde!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
    .string "Bravo!\p"
    .string "Bravo, ja!\n"
    .string "Hvilken forbløffende kamp!\p"
    .string "Sâ forbløffende at den konstant\n"
    .string "fylder mine øjne med târer!\p"
    .string "Stød og parering af ekspert\n"
    .string "brugte teknikker!\p"
    .string "Klangen af kraft mod kraft!\p"
    .string "Ja!\n"
    .string "Det var ren storhed!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
    .string "Aergerligt!\n"
    .string "Jeg føler din skuffelse.\p"
    .string "Men den skuffelse er det der\n"
    .string "vil gøre dig bedre.\p"
    .string "Brug den, lær af den og lad den\n"
    .string "motivere dig til storhed.\p"
    .string "Glem ikke denne skuffelse og\n"
    .string "fordoble din træning!$"

