FiveIsland_House1_JPText_HusbandWentOffFishing::
    .string "こんばんの　おかずは\n"
    .string "ようい　しなくて　いいぞ！\p"
    .string "って　だんなが\n"
    .string "つりに　いったん　だけど‥\l"
    .string "しんじて　いいのかねえ$"

FiveIsland_House1_Text_HusbandWentOffFishing::
    .string "Bekymr dig ikke om at köbe noget\n"
    .string "til middag i aften!\p"
    .string "…Det sagde min mand, da han tog\n"
    .string "ud at fiske i dag.\p"
    .string "Jeg er ikke sikker pâ om jeg kan\n"
    .string "regne med at han holder det löfte.$"

