MtMoon_B2F_Text_MiguelIntro::
    .string "Hey, stop!\p"
    .string "Jeg fandt disse fossiler!\n"
    .string "De er begge mine!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Okay!\n"
    .string "Jeg deler!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "Vi tager hver et fossil!\n"
    .string "Vaer ikke graadig!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "Okay.\n"
    .string "Saa er dette fossil mit!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Langt vaek, paa CINNABAR ISLAND,\n"
    .string "er der et POKeMON LAB.\p"
    .string "De forsker i at regenerere\n"
    .string "fossiler.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "Vi, TEAM ROCKET, finder fossilerne!\p"
    .string "At genoplive POKeMON fra dem\n"
    .string "indbringer os enorme rigdomme!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "Urgh!\n"
    .string "Nu er jeg vred!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "Du gjorde mig vred!\n"
    .string "TEAM ROCKET saetter dig paa sort liste!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "Vi, TEAM ROCKET, er POKeMON-\n"
    .string "gangstere!\l"
    .string "Vi indgyder frygt med vores styrke!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "Jeg roede det!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "Pokkers!\n"
    .string "Mine medsammensvorne accepterer ikke dette!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "Vi har et stort job her!\n"
    .string "Forsvind, unge!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "Saa du er god…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "Hvis du finder et fossil, giv mig det\n"
    .string "og forsvind!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "Smaa boern boer ikke blande sig med\n"
    .string "voksne!\p"
    .string "Det kan blive slemme nyheder!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "Jeg er dampende!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "POKeMON levede her laenge foer\n"
    .string "mennesker kom.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "Vil du have DOME FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "Vil du have HELIX FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "Fik HELIX FOSSIL!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "Fik DOME FOSSIL!$"

