FiveIsland_LostCave_Room1_Text_LawsonIntro::
    .string "Aijeeeeh!\p"
    .string "Jeg troede det var et gammelt\n"
    .string "ruin. Men det vrimler med spoegelser!$"

FiveIsland_LostCave_Room1_Text_LawsonDefeat::
    .string "Aijeeeeh!\n"
    .string "Naaade!$"

FiveIsland_LostCave_Room1_Text_LawsonPostBattle::
    .string "Jeg proever at komme herfra, men\n"
    .string "ender altid paa samme sted.\p"
    .string "Maaske antallet af kampesten er\n"
    .string "et tip…$"

