FiveIsland_LostCave_Room1_Text_LawsonIntro::
    .string "Aijeeeeh!\p"
    .string "Jeg tröde det var et gammelt\n"
    .string "ruin. Men det vrimler med spögelser!$"

FiveIsland_LostCave_Room1_Text_LawsonDefeat::
    .string "Aijeeeeh!\n"
    .string "Nâade!$"

FiveIsland_LostCave_Room1_Text_LawsonPostBattle::
    .string "Jeg pröver at komme herfra, men\n"
    .string "ender altid pâ samme sted.\p"
    .string "Mâske antallet af kampesten er\n"
    .string "et tip…$"

