TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "Hvor er LOSTELLE blevet af\n"
    .string "i dag?\p"
    .string "Hun bringer mig altid frokost hver\n"
    .string "dag lige omkring nu…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "Hm? Du der!\n"
    .string "Er du ven med LOSTELLE?\p"
    .string "Har du set LOSTELLE?\n"
    .string "Jeg ved ikke hvor hun kan vaere.\l"
    .string "Hun burde have vaeret her for laenge siden.\p"
    .string "LOSTELLE er saet - hun har mine\n"
    .string "traek - saa hvad hvis nogen…\p"
    .string "Hvad hvis der er sket noget med\n"
    .string "min LOSTELLE?!\p"
    .string "Hjaelp mig venligst med at finde hende!\n"
    .string "Gaa venligst og soeg paa THREE ISLAND!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "Hah? Hvad er denne GAME CORNER?\n"
    .string "Hvor meget tristere kan det blive?\p"
    .string "De klovne…\p"
    .string "De sagde de ville vente paa oeen,\n"
    .string "saa hvor er de?\p"
    .string "Hey, du! Er dette den eneste THREE\n"
    .string "ISLAND heromkring?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "Proev at vaagne foer du kravler ud\n"
    .string "af sengen, din bandit.\p"
    .string "Dette er TWO ISLAND!\p"
    .string "Skrid! Faa din beskidte motorcykel\n"
    .string "vaek fra mit sted!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "Huh…\n"
    .string "Aah, aah, forstaaet.\p"
    .string "Tch…\n"
    .string "Disse oeer er forvirrende…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "Se lige det?\n"
    .string "Den bandit ridser mit gulv.$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "Hey, men hoer! Jeg beder dig,\n"
    .string "du skal til THREE ISLAND.\p"
    .string "Hvis der skete noget med min\n"
    .string "LOSTELLE…\p"
    .string "Mit hus er det med det roede tag\n"
    .string "paa THREE ISLAND.\p"
    .string "Hun dukker maaske bare sent op her,\n"
    .string "saa jeg kan ikke loebe nogen steder.\p"
    .string "Derfor maa jeg bede dig om\n"
    .string "denne store tjeneste.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "Undskyld.\n"
    .string "Vi koerer ikke nogen spil i dag.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "Vi faar spillet i gang snart\n"
    .string "for dig!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "Saa du reddede LOSTELLE?\n"
    .string "Hvordan kan jeg takke dig?\p"
    .string "LOSTELLE, skat, tilgiv mig!\p"
    .string "Far vidste ikke du var bange\n"
    .string "og i knibe!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "LOSTELLE: Det er okay, Far.\n"
    .string "Jeg blev venner med {PLAYER}!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "Aah, hvad er det?\n"
    .string "Du siger at dette er til mig?\p"
    .string "Hvordan vidste du at jeg elsker\n"
    .string "sjaeldne sten og aedelstene?\p"
    .string "Du ved hvordan man goer en fyr\n"
    .string "glad.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER} gav METEORITEN\n"
    .string "til LOSTELLEs far.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "Aah, jeg ser, dette er fra BILL!\n"
    .string "Du skal takke ham for mig!\p"
    .string "Du ved, du har vaeret fantastisk.\n"
    .string "Jeg vil gerne give dig dette.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "{PLAYER} modtog en MOON STONE\n"
    .string "fra LOSTELLEs far.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "Din TASKE har ikke plads til mere…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "Okay, jeg faar GAME CORNER\n"
    .string "i gang med det samme.\p"
    .string "Du skal besoege med en ven.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "Hoer, hoer!\p"
    .string "Vis mig venligst at du er cool\n"
    .string "igen!$"

