Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Hey! {PLAYER}!\p"
	.string "Er du pâ vej til POKéMON LEAGUE?\n"
	.string "Glem det!\p"
	.string "Du har sikkert ikke nogen\n"
	.string "BADGES, har du?\p"
	.string "Vagten lukker dig ikke ind\n"
	.string "uden dem.\p"
	.string "For resten, er dine POKéMON blevet\n"
	.string "stærkere?$"

Route22_Text_EarlyRivalDefeat::
	.string "Awww!\n"
	.string "Du havde bare held!$"

Route22_Text_EarlyRivalPostBattle::
	.string "Jeg horte POKéMON LEAGUE er\n"
	.string "fuld af hârde TRAINERS.\p"
	.string "Jeg mâ finde ud af hvordan jeg\n"
	.string "kommer forbi dem.\p"
	.string "Du skal stoppe med at dovne dig\n"
	.string "og komme videre!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}: Hvad? Hvorfor har jeg 2\n"
	.string "POKéMON? Du skal ogsâ fange flere!\l"
	.string "$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: Hvad? {PLAYER}!\n"
	.string "Sikke en overraskelse at se dig her!\p"
	.string "Sâ du skal til POKéMON\n"
	.string "LEAGUE?\p"
	.string "Du har samlet alle BADGES ogsâ?\n"
	.string "Det er sejt!\p"
	.string "Sâ slâr jeg dig, {PLAYER}, som\n"
	.string "opvarmning til POKéMON LEAGUE!\p"
	.string "Kom an!$"

Route22_Text_LateRivalDefeat::
	.string "Hvad!?\p"
	.string "Jeg var bare skødesløs!$"

Route22_Text_LateRivalPostBattle::
	.string "Det løsnede mig op.\n"
	.string "Jeg er klar til POKéMON LEAGUE!\p"
	.string "{PLAYER}, du har brug for mere træning.\p"
	.string "Men du ved det jo!\n"
	.string "Jeg er ude herfra. Ses!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}: Hahaha! {PLAYER}! Er det det\n"
	.string "bedste du kan? Du er langt fra sâ\l"
	.string "god som mig! Træn mere! Taber!\l"
	.string "$"

Route22_Text_LeagueGateSign::
	.string "POKéMON LEAGUE\n"
	.string "Front Gate$"
