Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Hey! {PLAYER}!\p"
	.string "Er du paa vej til POKeMON LEAGUE?\n"
	.string "Glem det!\p"
	.string "Du har sikkert ikke nogen\n"
	.string "BADGES, har du?\p"
	.string "Vagten lukker dig ikke ind\n"
	.string "uden dem.\p"
	.string "For resten, er dine POKeMON blevet\n"
	.string "staerkere?$"

Route22_Text_EarlyRivalDefeat::
	.string "Awww!\n"
	.string "Du havde bare held!$"

Route22_Text_EarlyRivalPostBattle::
	.string "Jeg horte POKeMON LEAGUE er\n"
	.string "fuld af haarde TRAINERS.\p"
	.string "Jeg maa finde ud af hvordan jeg\n"
	.string "kommer forbi dem.\p"
	.string "Du skal stoppe med at dovne dig\n"
	.string "og komme videre!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}: Hvad? Hvorfor har jeg 2\n"
	.string "POKeMON? Du skal ogsaa fange flere!\l"
	.string "$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: Hvad? {PLAYER}!\n"
	.string "Sikke en overraskelse at se dig her!\p"
	.string "Saa du skal til POKeMON\n"
	.string "LEAGUE?\p"
	.string "Du har samlet alle BADGES ogsaa?\n"
	.string "Det er sejt!\p"
	.string "Saa slaar jeg dig, {PLAYER}, som\n"
	.string "opvarmning til POKeMON LEAGUE!\p"
	.string "Kom an!$"

Route22_Text_LateRivalDefeat::
	.string "Hvad!?\p"
	.string "Jeg var bare skoedesloes!$"

Route22_Text_LateRivalPostBattle::
	.string "Det loesnede mig op.\n"
	.string "Jeg er klar til POKeMON LEAGUE!\p"
	.string "{PLAYER}, du har brug for mere traening.\p"
	.string "Men du ved det jo!\n"
	.string "Jeg er ude herfra. Ses!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}: Hahaha! {PLAYER}! Er det det\n"
	.string "bedste du kan? Du er langt fra saa\l"
	.string "god som mig! Traen mere! Taber!\l"
	.string "$"

Route22_Text_LeagueGateSign::
	.string "POKeMON LEAGUE\n"
	.string "Front Gate$"
