OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "Liggende tilbage, vugget af bölgerne…\n"
    .string "Det er udsögt.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "Jeg tabte…\n"
    .string "Det föles forfärdeligt.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "Havet er behageligt varmt her.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "Gode ting bliver skyllet op af\n"
    .string "havströmmen pâ denne strand.\p"
    .string "Derfor kommer jeg ofte her for at\n"
    .string "söge efter skatte pâ stranden.$"

