OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "Liggende tilbage, vugget af bølgerne…\n"
    .string "Det er udsøgt.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "Jeg tabte…\n"
    .string "Det føles forfærdeligt.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "Havet er behageligt varmt her.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "Gode ting bliver skyllet op af\n"
    .string "havstrømmen pâ denne strand.\p"
    .string "Derfor kommer jeg ofte her for at\n"
    .string "søge efter skatte pâ stranden.$"

