SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "PRESIDENT: Oh, kære dreng!\n"
    .string "Tak for at redde SILPH.\p"
    .string "Jeg glemmer aldrig at du reddede os i\n"
    .string "vores farefulde øjeblik.\p"
    .string "Jeg mâ takke dig pâ en eller anden\n"
    .string "mâde.\p"
    .string "Fordi jeg er rig, kan jeg give dig\n"
    .string "hvad som helst.\p"
    .string "Her, mâske kan dette gøre det.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "PRESIDENT: Oh, kære pige!\n"
    .string "Tak for at redde SILPH.\p"
    .string "Jeg glemmer aldrig at du reddede os i\n"
    .string "vores farefulde øjeblik.\p"
    .string "Jeg mâ takke dig pâ en eller anden\n"
    .string "mâde.\p"
    .string "Fordi jeg er rig, kan jeg give dig\n"
    .string "hvad som helst.\p"
    .string "Her, mâske kan dette gøre det.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} fik en MASTER BALL\n"
    .string "fra PRESIDENTEN!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "PRESIDENT: Du kan ikke købe den\n"
    .string "nogen steder.\p"
    .string "Det er vores hemmelige prototype\n"
    .string "MASTER BALL.\p"
    .string "Den fanger ethvert POKéMON uden\n"
    .string "at fejle!\p"
    .string "Du bør dog være stille om at bruge den.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "Du har ikke plads til dette.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "SEKRETÆR: Tak for at redde\n"
    .string "os alle.\p"
    .string "Vi, fra PRESIDENTEN og ned,\n"
    .string "stâr i gæld til dig.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "Ah, {PLAYER}!\n"
    .string "Sâ mødes vi igen!\p"
    .string "PRESIDENTEN og jeg diskuterer\n"
    .string "et vigtigt forretningsforslag.\p"
    .string "Hold din næse ude af voksne\n"
    .string "anliggender…\p"
    .string "Eller oplev en verden af smerte!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "Arrgh!!\n"
    .string "Jeg tabte igen!?$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "Forbandet!\n"
    .string "Du ødelagde vores planer for SILPH!\p"
    .string "Men TEAM ROCKET falder aldrig!\p"
    .string "{PLAYER}! Glem aldrig at alle\n"
    .string "POKéMON eksisterer for TEAM ROCKET!\p"
    .string "Jeg mâ ga, men jeg vender tilbage!$"

SilphCo_11F_Text_Grunt2Intro::
    .string "Stop lige der!\n"
    .string "Bevæg dig ikke!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "Ikke…\n"
    .string "Venligst!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "Sâ du vil se min BOSS?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "Stop! Har du en aftale\n"
    .string "med min BOSS?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "Gâh!\n"
    .string "Ødelagt!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Pas pâ…\n"
    .string "Min BOSS kan lide sine POKéMON hârde!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "Skærmen har POKéMON pâ den!$"

SilphCo_11F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "11. SAL$"

