PokemonMansion_Text_PressSecretSwitch::
    .string "En hemmelig kontakt!\p"
    .string "Tryk pâ den?$"

PokemonMansion_Text_WhoWouldnt::
    .string "Hvem ville ikke?$"

PokemonMansion_Text_NotQuiteYet::
    .string "Ikke helt endnu!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "Jeg kan ikke komme ud!\n"
    .string "Dette gamle sted er et stort puslespil.$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "Aah nej!\n"
    .string "Min pose med bytte!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "Kontakterne her âbner og lukker\n"
    .string "vekslende sät döre.$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "Dagbog: 5. juli\n"
    .string "Guyana, Sydamerika\p"
    .string "En ny POKeMON blev opdaget dybt\n"
    .string "i junglen.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "Dagbog: 10. juli\n"
    .string "Vi döbte den nylig opdagede\l"
    .string "POKeMON, MEW.$"
