CinnabarIsland_Gym_Text_BlaineIntro::
    .string "Hah!\p"
    .string "Jeg er BLAINE, den glönde LEADER\n"
    .string "af CINNABAR GYM!\p"
    .string "Mine ildende POKéMON er alle\n"
    .string "hârde og klar med intens varme!\p"
    .string "De bränder alle udfordrere!\p"
    .string "Hah!\n"
    .string "Du bör have BURN HEAL!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "Jeg er brändt ned til intet!\n"
    .string "Ikke engang aske er tilbage!\p"
    .string "Du har fortjent VOLCANOBADGE.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "FIRE BLAST er den ultimative ild-\n"
    .string "teknik.\p"
    .string "Spild den ikke pâ WATER POKéMON.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "Hah!\p"
    .string "VOLCANOBADGE öger SPECIAL-\n"
    .string "staterne af dine POKéMON.\p"
    .string "Her, du kan ogsâ fâ dette!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER} modtog TM38\n"
    .string "fra BLAINE.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "TM38 indeholder FIRE BLAST.\n"
    .string "Lär det til FIRE-type POKéMON.\p"
    .string "VULPIX eller CHARMELEON ville väre\n"
    .string "ideel til det trick.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "Lav plads til dette, barn!$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "Ved du hvor varm POKéMON ild-\n"
    .string "ânde kan blive?$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "Av!\n"
    .string "Varmt, varmt, varmt!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "Ild, eller mere präcist,\n"
    .string "forbränding…\p"
    .string "…Ilt i luften…\n"
    .string "Blah, blah, blah, blah…$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "Jeg var tyv, men jeg blev ordentlig\n"
    .string "som TRAINER.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "Jeg overgiver mig!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "Jeg fâr denne uimodstâelige trang til at\n"
    .string "stjäle andre folks POKéMON.$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "Jeg har studeret POKéMON grundigt.\n"
    .string "Du kan ikke vinde!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "Wâh!\n"
    .string "Mine studier var utilsträkkelige!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "Mine teorier er for komplicerede\n"
    .string "for dig at forstâ.$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "Jeg kan lide at bruge FIRE-type POKéMON.\n"
    .string "Det gör jeg bare.$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "For varmt at hândtere!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "Jeg ville önske der var en tyv-POKéMON.\n"
    .string "Den ville jeg bruge!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "Jeg ved hvorfor BLAINE blev\n"
    .string "TRAINER.$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "Av!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "Vores LEADER, BLAINE, blev godt\n"
    .string "tabt i bjergene.\p"
    .string "Det blev mörkt da en ildfugl-\n"
    .string "POKéMON dukked op.\p"
    .string "Dens lys hjalp BLAINE med at finde\n"
    .string "vej ned i sikkerhed.$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "Jeg har väret i mange GYMs, men denne\n"
    .string "passer bedst til min stil.$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "Yowza!\n"
    .string "For varmt!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "PONYTA, NINETALES…\n"
    .string "De er populäre FIRE POKéMON.$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "Ild er sväk mod H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "Oh!\n"
    .string "Slukket!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "Vand slâer ild, selvfölgelig.\p"
    .string "Men ild smelter is, sâ FIRE-\n"
    .string "typen slâer ICE-type POKéMON.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i blive!\p"
    .string "Den hidsige BLAINE er en FIRE-\n"
    .string "POKéMON pro.\p"
    .string "Sluk hans ând med vand!\p"
    .string "Du bör ogsâ tage nogle\n"
    .string "BURN HEALS med.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}!\n"
    .string "Du slog den ildebrand!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "POKéMON Quiz!\p"
    .string "Svar rigtigt, sâ âbnes dören til\n"
    .string "näste rum.\p"
    .string "Svar forkert, og möd en TRAINER!\p"
    .string "Hvis du vil spare dine POKéMON\n"
    .string "til GYM LEADER…\p"
    .string "Sâ svar rigtigt!\n"
    .string "Her gâr vi!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "CATERPIE udvikler sig til METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "Der er ni certificerede POKéMON\n"
    .string "LEAGUE BADGES?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "POLIWAG udvikler sig tre gange?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "Er elektriske tricks effektive\n"
    .string "mod GROUND-type POKéMON?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "POKéMON af samme slags og niveau\n"
    .string "er ikke identiske?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "Indeholder TM28 TOMBSTONY?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "Du har fuldständig ret!\p"
    .string "Gâ videre!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "Beklager!\n"
    .string "Forkert svar!$"
