CinnabarIsland_Gym_Text_BlaineIntro::
    .string "Hah!\p"
    .string "Jeg er BLAINE, den gloende LEADER\n"
    .string "af CINNABAR GYM!\p"
    .string "Mine ildende POKeMON er alle\n"
    .string "haarde og klar med intens varme!\p"
    .string "De braender alle udfordrere!\p"
    .string "Hah!\n"
    .string "Du boer have BURN HEAL!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "Jeg er braendt ned til intet!\n"
    .string "Ikke engang aske er tilbage!\p"
    .string "Du har fortjent VOLCANOBADGE.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "FIRE BLAST er den ultimative ild-\n"
    .string "teknik.\p"
    .string "Spild den ikke paa WATER POKeMON.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "Hah!\p"
    .string "VOLCANOBADGE oeger SPECIAL-\n"
    .string "staterne af dine POKeMON.\p"
    .string "Her, du kan ogsaa faa dette!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER} modtog TM38\n"
    .string "fra BLAINE.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "TM38 indeholder FIRE BLAST.\n"
    .string "Laer det til FIRE-type POKeMON.\p"
    .string "VULPIX eller CHARMELEON ville vaere\n"
    .string "ideel til det trick.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "Lav plads til dette, barn!$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "Ved du hvor varm POKeMON ild-\n"
    .string "aande kan blive?$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "Av!\n"
    .string "Varmt, varmt, varmt!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "Ild, eller mere praecist,\n"
    .string "forbraending…\p"
    .string "…Ilt i luften…\n"
    .string "Blah, blah, blah, blah…$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "Jeg var tyv, men jeg blev ordentlig\n"
    .string "som TRAINER.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "Jeg overgiver mig!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "Jeg faar denne uimodstaaelige trang til at\n"
    .string "stjaele andre folks POKeMON.$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "Jeg har studeret POKeMON grundigt.\n"
    .string "Du kan ikke vinde!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "Waah!\n"
    .string "Mine studier var utilstraekkelige!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "Mine teorier er for komplicerede\n"
    .string "for dig at forstaa.$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "Jeg kan lide at bruge FIRE-type POKeMON.\n"
    .string "Det goer jeg bare.$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "For varmt at haandtere!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "Jeg ville oenske der var en tyv-POKeMON.\n"
    .string "Den ville jeg bruge!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "Jeg ved hvorfor BLAINE blev\n"
    .string "TRAINER.$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "Av!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "Vores LEADER, BLAINE, blev godt\n"
    .string "tabt i bjergene.\p"
    .string "Det blev moerkt da en ildfugl-\n"
    .string "POKeMON dukked op.\p"
    .string "Dens lys hjalp BLAINE med at finde\n"
    .string "vej ned i sikkerhed.$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "Jeg har vaeret i mange GYMs, men denne\n"
    .string "passer bedst til min stil.$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "Yowza!\n"
    .string "For varmt!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "PONYTA, NINETALES…\n"
    .string "De er populaere FIRE POKeMON.$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "Ild er svaek mod H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "Oh!\n"
    .string "Slukket!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "Vand slaaer ild, selvfoelgelig.\p"
    .string "Men ild smelter is, saa FIRE-\n"
    .string "typen slaaer ICE-type POKeMON.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i blive!\p"
    .string "Den hidsige BLAINE er en FIRE-\n"
    .string "POKeMON pro.\p"
    .string "Sluk hans aand med vand!\p"
    .string "Du boer ogsaa tage nogle\n"
    .string "BURN HEALS med.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}!\n"
    .string "Du slog den ildebrand!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "CINNABAR POKeMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "CINNABAR POKeMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "POKeMON Quiz!\p"
    .string "Svar rigtigt, saa aabnes doeren til\n"
    .string "naeste rum.\p"
    .string "Svar forkert, og moed en TRAINER!\p"
    .string "Hvis du vil spare dine POKeMON\n"
    .string "til GYM LEADER…\p"
    .string "Saa svar rigtigt!\n"
    .string "Her gaar vi!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "CATERPIE udvikler sig til METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "Der er ni certificerede POKeMON\n"
    .string "LEAGUE BADGES?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "POLIWAG udvikler sig tre gange?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "Er elektriske tricks effektive\n"
    .string "mod GROUND-type POKeMON?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "POKeMON af samme slags og niveau\n"
    .string "er ikke identiske?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "Indeholder TM28 TOMBSTONY?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "Du har fuldstaendig ret!\p"
    .string "Gaa videre!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "Beklager!\n"
    .string "Forkert svar!$"
