PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "Hvad!?\p"
    .string "TEAM ROCKET er ved MT. MOON?\n"
    .string "Hva?\p"
    .string "Jeg er i telefonen!\n"
    .string "Forsvind!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "JIGGLYPUFF: Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Gaben!\p"
    .string "Naar JIGGLYPUFF synger, bliver\n"
    .string "POKeMON doese…\p"
    .string "…Mig ogsaa…\n"
    .string "Snork…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "Jeg vil virkelig have en PIKACHU, saa jeg\n"
    .string "bytter min CLEFAIRY for een.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "Jeg bytter POKeMON med det barn\n"
    .string "derovre.\p"
    .string "Jeg havde to PIKACHU, saa jeg\n"
    .string "taenkte jeg kunne bytte een.$"
