PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "Hvad!?\p"
    .string "TEAM ROCKET er ved MT. MOON?\n"
    .string "Hva?\p"
    .string "Jeg er i telefonen!\n"
    .string "Forsvind!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "JIGGLYPUFF: Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Gaben!\p"
    .string "Nâr JIGGLYPUFF synger, bliver\n"
    .string "POKeMON döse…\p"
    .string "…Mig ogsâ…\n"
    .string "Snork…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "Jeg vil virkelig have en PIKACHU, sâ jeg\n"
    .string "bytter min CLEFAIRY for een.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "Jeg bytter POKeMON med det barn\n"
    .string "derovre.\p"
    .string "Jeg havde to PIKACHU, sâ jeg\n"
    .string "tänkte jeg kunne bytte een.$"
