SSAnne_B1F_Room1_Text_PhillipIntro::
    .string "Kammerat, du gaar planken hvis\n"
    .string "du taber!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .string "Argh!\n"
    .string "Slaaet af et barn!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .string "Naar vi er ude paa havet, driver\n"
    .string "vandmands-POKeMON nogle gange forbi.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
    .string "Hej, fremmed!\p"
    .string "Jeg kan ikke se om du er fra havet\n"
    .string "eller bjergene, men stop og snak.\p"
    .string "Alle mine POKeMON er fra havet.$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .string "Pokkers!\n"
    .string "Jeg lod den slippe vaek!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .string "Jeg ville lige have gjort dig til min\n"
    .string "assistent!$"

