SSAnne_B1F_Room1_Text_PhillipIntro::
    .string "Kammerat, du går planken hvis\n"
    .string "du taber!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .string "Argh!\n"
    .string "Slået af et barn!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .string "Når vi er ude på havet, driver\n"
    .string "vandmands-POKéMON nogle gange forbi.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
    .string "Hej, fremmed!\p"
    .string "Jeg kan ikke se om du er fra havet\n"
    .string "eller bjergene, men stop og snak.\p"
    .string "Alle mine POKéMON er fra havet.$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .string "Pokkers!\n"
    .string "Jeg lod den slippe væk!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .string "Jeg ville lige have gjort dig til min\n"
    .string "assistent!$"

