Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "Hej! Jeg er en POKéMON...\n"
    .string "...Nej er jeg ikke!\p"
    .string "Kald mig BILL!\n"
    .string "Jeg er en ägte POKeMANIAC!\p"
    .string "Hey!\n"
    .string "Hvad er det for et skeptisk blik?\p"
    .string "Jeg laver ikke sjov med dig.\p"
    .string "Jeg lavede en fejl i et eksperiment\n"
    .string "og blev kombineret med en POKéMON!\p"
    .string "Sâ hvad siger du?\n"
    .string "Hjälp mig!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "Hej! Jeg er en POKéMON...\n"
    .string "...Nej er jeg ikke!\p"
    .string "Kald mig BILL!\n"
    .string "Jeg er en ägte POKeMANIAC!\p"
    .string "Hey!\n"
    .string "Hvad er det for et skeptisk blik?\p"
    .string "Jeg laver ikke sjov med dig, fröken.\p"
    .string "Jeg lavede en fejl i et eksperiment\n"
    .string "og blev kombineret med en POKéMON!\p"
    .string "Sâ hvad siger du?\n"
    .string "Hjälp mig!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "Vent til jeg er inde i\n"
    .string "TELEPORTEREN.\p"
    .string "Nâr jeg er det, ga til min PC og\n"
    .string "kör Celleadskillelses-systemet.$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "Nej!?\n"
    .string "Vär nu ikke sâ kold!\p"
    .string "Kom nu, du mâ hjälpe en fyr i\n"
    .string "dyb, dyb problemer!\p"
    .string "Hvad siger du, chef?\n"
    .string "Vär sâ venlig?\l"
    .string "Okay?\l"
    .string "Aftale!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "Nej!?\n"
    .string "Vär nu ikke sâ kold!\p"
    .string "Kom nu, du mâ hjälpe en fyr i\n"
    .string "dyb, dyb problemer!\p"
    .string "Hvad siger du, smukke?\n"
    .string "Vär sâ venlig?\l"
    .string "Okay?\l"
    .string "Aftale!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "BILL: Yeehah!\n"
    .string "Tak, ven! Jeg skylder dig en!\p"
    .string "Sâ kom du for at se min\n"
    .string "POKéMON-samling?\p"
    .string "Det gjorde du ikke?\n"
    .string "Det er ärgerligt.\p"
    .string "Jeg mâ takke dig...\n"
    .string "Aa, her, mâske er dette okay.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "BILL: Yeehah!\n"
    .string "Tak, fröken! Jeg skylder dig en!\p"
    .string "Sâ kom du for at se min\n"
    .string "POKéMON-samling?\p"
    .string "Det gjorde du ikke?\n"
    .string "Det er ärgerligt.\p"
    .string "Jeg mâ takke dig...\n"
    .string "Aa, her, mâske er dette okay.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER} modtog et S.S. TICKET\n"
    .string "fra BILL.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "Du har for meget med!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "Det krydstogtskib S.S. ANNE er i\n"
    .string "VERMILION CITY.\p"
    .string "Jeg horer der er masser af TRAINERS\n"
    .string "om bord ogsâ.\p"
    .string "De inviterede mig til deres fest, men\n"
    .string "jeg kan ikke udstâ finesse.\p"
    .string "Hvorfor gâr du ikke i stedet for mig?\n"
    .string "Ha det sjovt!$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "BILL: Vil du se nogle af mine\n"
    .string "själdne POKéMON pâ min PC?\p"
    .string "Ga til min PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "TELEPORTER vises pâ PC-skärmen.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} startede TELEPORTERs\n"
    .string "Celleadskiller.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "BILLs liste over yndlings-POKéMON!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "Hvilken POKéMON vil du se?$"
