Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "Hej! Jeg er en POKeMON...\n"
    .string "...Nej er jeg ikke!\p"
    .string "Kald mig BILL!\n"
    .string "Jeg er en aegte POKeMANIAC!\p"
    .string "Hey!\n"
    .string "Hvad er det for et skeptisk blik?\p"
    .string "Jeg laver ikke sjov med dig.\p"
    .string "Jeg lavede en fejl i et eksperiment\n"
    .string "og blev kombineret med en POKeMON!\p"
    .string "Saa hvad siger du?\n"
    .string "Hjaelp mig!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "Hej! Jeg er en POKeMON...\n"
    .string "...Nej er jeg ikke!\p"
    .string "Kald mig BILL!\n"
    .string "Jeg er en aegte POKeMANIAC!\p"
    .string "Hey!\n"
    .string "Hvad er det for et skeptisk blik?\p"
    .string "Jeg laver ikke sjov med dig, froeken.\p"
    .string "Jeg lavede en fejl i et eksperiment\n"
    .string "og blev kombineret med en POKeMON!\p"
    .string "Saa hvad siger du?\n"
    .string "Hjaelp mig!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "Vent til jeg er inde i\n"
    .string "TELEPORTEREN.\p"
    .string "Naar jeg er det, ga til min PC og\n"
    .string "koer Celleadskillelses-systemet.$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "Nej!?\n"
    .string "Vaer nu ikke saa kold!\p"
    .string "Kom nu, du maa hjaelpe en fyr i\n"
    .string "dyb, dyb problemer!\p"
    .string "Hvad siger du, chef?\n"
    .string "Vaer saa venlig?\l"
    .string "Okay?\l"
    .string "Aftale!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "Nej!?\n"
    .string "Vaer nu ikke saa kold!\p"
    .string "Kom nu, du maa hjaelpe en fyr i\n"
    .string "dyb, dyb problemer!\p"
    .string "Hvad siger du, smukke?\n"
    .string "Vaer saa venlig?\l"
    .string "Okay?\l"
    .string "Aftale!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "BILL: Yeehah!\n"
    .string "Tak, ven! Jeg skylder dig en!\p"
    .string "Saa kom du for at se min\n"
    .string "POKeMON-samling?\p"
    .string "Det gjorde du ikke?\n"
    .string "Det er aergerligt.\p"
    .string "Jeg maa takke dig...\n"
    .string "Aa, her, maaske er dette okay.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "BILL: Yeehah!\n"
    .string "Tak, froeken! Jeg skylder dig en!\p"
    .string "Saa kom du for at se min\n"
    .string "POKeMON-samling?\p"
    .string "Det gjorde du ikke?\n"
    .string "Det er aergerligt.\p"
    .string "Jeg maa takke dig...\n"
    .string "Aa, her, maaske er dette okay.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER} modtog et S.S. TICKET\n"
    .string "fra BILL.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "Du har for meget med!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "Det krydstogtskib S.S. ANNE er i\n"
    .string "VERMILION CITY.\p"
    .string "Jeg horer der er masser af TRAINERS\n"
    .string "om bord ogsaa.\p"
    .string "De inviterede mig til deres fest, men\n"
    .string "jeg kan ikke udstaa finesse.\p"
    .string "Hvorfor gaar du ikke i stedet for mig?\n"
    .string "Ha det sjovt!$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "BILL: Vil du se nogle af mine\n"
    .string "sjaeldne POKeMON paa min PC?\p"
    .string "Ga til min PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "TELEPORTER vises paa PC-skaermen.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} startede TELEPORTERs\n"
    .string "Celleadskiller.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "BILLs liste over yndlings-POKeMON!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "Hvilken POKeMON vil du se?$"
