@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "Mine POKeMONs aske opbevares i\n"
    .string "POKeMON TOWER.\p"
    .string "Du maa faa denne TM.\n"
    .string "Jeg har ikke brug for den laengere…$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "Mine POKeMONs aske opbevares i\n"
    .string "POKeMON TOWER.\p"
    .string "Du maa faa denne TM.\n"
    .string "Jeg har ikke brug for den laengere…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .string "{PLAYER} modtog TM27\n"
    .string "fra den lille pige.$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .string "TM27 er et traek kaldt RETURN…\p"
    .string "Hvis du behandler din POKeMON godt,\n"
    .string "returnerer den din kaerlighed ved at\l"
    .string "arbejde haardest i kamp.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "Du har ikke plads til dette.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "Lad os se hvad kikkerten viser…\p"
    .string "Der er en mand der fisker!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "Lad os se hvad kikkerten viser…\p"
    .string "Det er POKeMON TOWER!$"
