CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "Jeg kom for at besoege CINNABAR GYM,\n"
    .string "men doeren er laaset godt til.\p"
    .string "Der boer vaere en noegel til den\n"
    .string "et sted.\p"
    .string "Kunne den vaere i den nedbraendte\n"
    .string "mansion?\p"
    .string "GYM LEADERens ven boede\n"
    .string "der, siges det.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "Har du masser af venner?\p"
    .string "At linke med de saedvanlige venner\n"
    .string "er selvfoelgelig sjovt.\p"
    .string "Men hvad med at besoege\n"
    .string "UNION ROOM nu og da?\p"
    .string "Hvem ved, du ender maaske med at\n"
    .string "faa nye venner.\p"
    .string "Jeg tror det ville vaere din tid vaerd\n"
    .string "at tjekke UNION ROOM.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "POKeMON kan stadig laere teknikker\n"
    .string "efter at have annulleret evolution.\p"
    .string "Evolution kan vente til nye tricks\n"
    .string "er laert.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "BILL: Hey, du fik mig til at vente!\n"
    .string "Klar til at sejle til ONE ISLAND?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "Oh, du er stadig ikke faerdig?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "Naar, det var det.\n"
    .string "Lad os gaa!$"
