CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "Jeg kom for at besøge CINNABAR GYM,\n"
    .string "men døren er lâset godt til.\p"
    .string "Der bør være en nøgel til den\n"
    .string "et sted.\p"
    .string "Kunne den være i den nedbrændte\n"
    .string "mansion?\p"
    .string "GYM LEADERens ven bøde\n"
    .string "der, siges det.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "Har du masser af venner?\p"
    .string "At linke med de sædvanlige venner\n"
    .string "er selvfølgelig sjovt.\p"
    .string "Men hvad med at besøge\n"
    .string "UNION ROOM nu og da?\p"
    .string "Hvem ved, du ender mâske med at\n"
    .string "fâ nye venner.\p"
    .string "Jeg tror det ville være din tid værd\n"
    .string "at tjekke UNION ROOM.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "POKéMON kan stadig lære teknikker\n"
    .string "efter at have annulleret evolution.\p"
    .string "Evolution kan vente til nye tricks\n"
    .string "er lært.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "BILL: Hey, du fik mig til at vente!\n"
    .string "Klar til at sejle til ONE ISLAND?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "Oh, du er stadig ikke færdig?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "Nâr, det var det.\n"
    .string "Lad os gâ!$"
