CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "Jeg kom for at besöge CINNABAR GYM,\n"
    .string "men dören er lâset godt til.\p"
    .string "Der bör väre en nögel til den\n"
    .string "et sted.\p"
    .string "Kunne den väre i den nedbrändte\n"
    .string "mansion?\p"
    .string "GYM LEADERens ven böde\n"
    .string "der, siges det.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "Har du masser af venner?\p"
    .string "At linke med de sädvanlige venner\n"
    .string "er selvfölgelig sjovt.\p"
    .string "Men hvad med at besöge\n"
    .string "UNION ROOM nu og da?\p"
    .string "Hvem ved, du ender mâske med at\n"
    .string "fâ nye venner.\p"
    .string "Jeg tror det ville väre din tid värd\n"
    .string "at tjekke UNION ROOM.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "POKéMON kan stadig läre teknikker\n"
    .string "efter at have annulleret evolution.\p"
    .string "Evolution kan vente til nye tricks\n"
    .string "er lärt.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "BILL: Hey, du fik mig til at vente!\n"
    .string "Klar til at sejle til ONE ISLAND?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "Oh, du er stadig ikke färdig?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "Nâr, det var det.\n"
    .string "Lad os gâ!$"
