PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "Hvad bringer dig her?\l"
    .string "Er din POKéMON död?\p"
    .string "Hey! Den lever!\p"
    .string "Jeg kan i det mindste fâ dem til at besvime!\n"
    .string "Kom sâ!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "Hvad?\n"
    .string "Din stinker!\p"
    .string "Jeg tog det ogsâ let pâ dig!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "Hvordan kommer din POKéDEX?\n"
    .string "Jeg fangede lige en CUBONE!\p"
    .string "Jeg kan ikke finde den större MAROWAK.\n"
    .string "Hvor kan de väre?\p"
    .string "Jeg vedder pâ der ikke er flere!\p"
    .string "Nâ, jeg bör komme afsted.\n"
    .string "Jeg har meget at udrette,\l"
    .string "til forskel fra dig.\p"
    .string "Vi ses!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Selv vi kunne ikke identificere de\n"
    .string "vildfarne spögelser.\p"
    .string "Et SILPH SCOPE kunne mâske\n"
    .string "afslöre dem.$"
