SSAnne_1F_Corridor_Text_LeStrongSilentType::
    .string "Bonjour!\n"
    .string "Jeg er oberen pâ dette skib!\p"
    .string "Jeg serverer gerne hvad som helst\n"
    .string "du oonsker!\p"
    .string "… … …\n"
    .string "Aah! Den stärke tavse type!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
    .string "Passagererne er urolige efter\n"
    .string "denne lange rejse.\p"
    .string "Du kan blive udfordret af de\n"
    .string "mere kede af dem!$"

