CeruleanCity_Gym_Text_MistyIntro::
    .string "Hej, du er et nyt ansigt!\p"
    .string "Kun TRAINERS der har en politik om\n"
    .string "POKeMON kan blive professionelle.\p"
    .string "Hvad er din tilgang nâr du\n"
    .string "fanger og träner POKeMON?\p"
    .string "Min politik er et totalt angreb\n"
    .string "med WATER-type POKeMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 lärer WATER PULSE.\p"
    .string "Brug det pâ en vand-POKeMON!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "CASCADEBADGE fâr alle POKeMON\n"
    .string "op til Lv. 30 til at adlyde.\p"
    .string "Det inkluderer endda dem du\n"
    .string "fik ved bytte.\p"
    .string "Der er mere. Du kan nu bruge CUT\n"
    .string "nâr som helst, endda uden kamp.\p"
    .string "Du kan CUTte smâ träer ned for at\n"
    .string "âbne nye stier.\p"
    .string "Du kan ogsâ fâ min yndlings-TM.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} modtog TM03\n"
    .string "fra MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "Du bör lave plads til dette!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Wow!\n"
    .string "Du er for stärk!\p"
    .string "Okay!\p"
    .string "Du kan fâ CASCADEBADGE for at\n"
    .string "vise at du slog mig.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "Hvad? Dig?\n"
    .string "Jeg er mere end god nok til dig!\p"
    .string "MISTY behöver ikke blive forstyrret.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "Du overväldede mig!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "Du mâ möde andre TRAINERS\n"
    .string "for at se hvor gode du virkelig er.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Plask!\p"
    .string "Jeg er först!\n"
    .string "Lad os göre det!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "Det kan ikke väre rigtigt!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY er en TRAINER der bliver\n"
    .string "bedre og bedre.\p"
    .string "Hun taber ikke til en som dig!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i blive!\p"
    .string "Lad mig give dig et râd!\p"
    .string "LEADERen, MISTY, er en pro der\n"
    .string "bruger WATER-type POKeMON.\p"
    .string "Du kan däne alt deres vand med\n"
    .string "GRASS-type POKeMON.\p"
    .string "Eller du kan bruge ELECTRIC-type\n"
    .string "POKeMON og give dem stöd!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "Du slog MISTY!\n"
    .string "Se, hvad sagde jeg?\p"
    .string "Dig og mig, barn, vi er et ret\n"
    .string "godt team!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "CERULEAN POKeMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "CERULEAN POKeMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "VINDENDE TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
