FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Oeh…\n"
    .string "Ja, jeg er MOVE DELETER.\p"
    .string "Jeg kan faa POKeMON til at glemme\n"
    .string "deres angreb.\p"
    .string "Vil du have mig til at goere det?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "Hvilken POKeMON skal glemme et\n"
    .string "angreb?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "Hvilket angreb skal glemmes?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{STR_VAR_1} ser ud til kun at kende\n"
    .string "ét angreb…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Hm! {STR_VAR_1}s {STR_VAR_2}?\n"
    .string "Skal det angreb glemmes?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "Det lykkedes perfekt!\p"
    .string "{STR_VAR_1} har glemt\n"
    .string "{STR_VAR_2} helt.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Kom igen hvis der er andre\n"
    .string "angreb der skal glemmes.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "Hvad?\n"
    .string "Et AeG boer ikke kende nogen angreb.$"

