Text_DreamEaterTeach::
    .string "Gaben!\n"
    .string "Jeg maa vaere faldet i soevn i solen.\p"
    .string "Jeg havde denne underlige drom om\n"
    .string "en DROWZEE der spiste min drom.\p"
    .string "Og…\n"
    .string "Jeg laerte at spise dromme…\p"
    .string "Ugh, det er for uhyggeligt!\p"
    .string "Lad mig laere det til en POKeMON saa\n"
    .string "jeg kan glemme det!$"

Text_DreamEaterDeclined::
    .string "…Snork…$"

Text_DreamEaterWhichMon::
    .string "Hvilken POKeMON vil laere\n"
    .string "DREAM EATER?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "Jeg…kan ikke spise…mere…$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "CLEFAIRY kom fra maanen.\n"
    .string "Det er rygtet.\p"
    .string "De dukkede op efter MOON STONES\n"
    .string "faldt paa MT. MOON.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "Der er ikke mange serioese POKeMON\n"
    .string "TRAeNERE her.\p"
    .string "De er alle som BUG CATCHERS,\n"
    .string "du ved, bare hobbyister.\p"
    .string "Men PEWTER GYMs BROCK er ikke\n"
    .string "sadan, overhovedet.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "Tjekkede du MUSEET?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "Var de fossiler fra MT. MOON\n"
    .string "ikke fantastiske?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Virkelig?\n"
    .string "Du maa absolut ga derhen!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "Her er det, MUSEET.\p"
    .string "Du skal betale for at komme ind, men det\n"
    .string "er det vaerd. Vi ses!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Pst!\n"
    .string "Ved du hvad jeg laver?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "Lige praecis!\n"
    .string "Det er haardt arbejde!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "Jeg sprayer REPEL for at holde vilde\n"
    .string "POKeMON ude af min have!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "Du er TRAeNER, ikke?\p"
    .string "BROCK leder efter nye\n"
    .string "udfordrere. Foelg mig!$"

PewterCity_Text_GoTakeOnBrock::
    .string "Hvis du har hvad det kraever,\n"
    .string "gaa og tag kampen op med BROCK!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "TRAeNER TIPS\p"
    .string "Alle POKeMON der optraeder i kamp,\n"
    .string "uanset hvor kort, faar EXP Point.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "OPSLAG!\p"
    .string "Tyve har stjaalet POKeMON\n"
    .string "fossiler fra MT. MOON.\p"
    .string "Ring til PEWTER POLITIET hvis\n"
    .string "du har oplysninger.$"

PewterCity_Text_MuseumOfScience::
    .string "PEWTER MUSEUM FOR VIDENSKAB$"

PewterCity_Text_GymSign::
    .string "PEWTER CITY POKeMON GYM\n"
    .string "LEDER: BROCK\l"
    .string "Den stensikre POKeMON TRAeNER!$"

PewterCity_Text_CitySign::
    .string "PEWTER CITY\n"
    .string "En stengraa by$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "Aah, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "Godt jeg indhentede dig.\n"
    .string "Jeg er PROF. OAKs ASSISTENT.\p"
    .string "Jeg er blevet bedt om at aflevere dette,\n"
    .string "saa vaersgo.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} modtog\n"
    .string "LOEBESKO fra ASSISTENTEN.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} skiftede sko med\n"
    .string "LOEBESKOENE.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Tryk B-knappen for at loebe.\n"
    .string "Men kun hvor der er plads!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Naa, jeg maa tilbage til\n"
    .string "LABORATORIET.\p"
    .string "Hej hej!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "Der er et brev vedhaeftet…\p"
    .string "Kaere {PLAYER},\p"
    .string "Her er et par LOEBESKO\n"
    .string "til min kaere udfordrer.\p"
    .string "Husk, jeg hepper altid paa dig!\n"
    .string "Giv aldrig op!\p"
    .string "Fra Mor$"
