PokemonTower_3F_Text_HopeIntro::
    .string "Urrg… Awâ…\n"
    .string "Huhu… Grâ…$"

PokemonTower_3F_Text_HopeDefeat::
    .string "Hwa!\n"
    .string "Jeg er reddet!$"

PokemonTower_3F_Text_HopePostBattle::
    .string "Spøgelserne kan identificeres med\n"
    .string "SILPH SCOPE.$"

PokemonTower_3F_Text_CarlyIntro::
    .string "Kekeke…\n"
    .string "Kwâah!$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "Hmm?\n"
    .string "Hvad laver jeg?$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "Undskyld!\n"
    .string "Jeg var besat!$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "Forsvind!\n"
    .string "Ondskâbsfuld ând!$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "Puha!\n"
    .string "Aanden forlod!$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "De andre ovenpâ…\n"
    .string "De mâ have været besat.$"
