Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "Hej! Husker du mig?\n"
    .string "Jeg er en af PROF. OAKs assistenter.\p"
    .string "Hvis din POKeDEX har fulde data\n"
    .string "om {STR_VAR_1} arter, skal jeg\l"
    .string "give dig en beloenning.\p"
    .string "PROF. OAK betroede mig\n"
    .string "{STR_VAR_2} til dig.\p"
    .string "Saa, {PLAYER}, lad mig spoerge dig.\p"
    .string "Har du indsamlet data om mindst\n"
    .string "{STR_VAR_1} slags POKeMON?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "Super! Du har fanget eller ejet\n"
    .string "{STR_VAR_3} slags POKeMON!\p"
    .string "Tillykke!\n"
    .string "Her har du den!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "{PLAYER} modtog {STR_VAR_2}\n"
    .string "fra assistenten.$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "EXP. SHARE er en genstand en\n"
    .string "POKeMON kan baere.\p"
    .string "POKeMON modtager en del af\n"
    .string "EXP-pointene uden at kaempe.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "Lad os se hvad kikkerten viser...\p"
    .string "En stor, skinhende fugl flyver\n"
    .string "mod havet.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "Lad os se hvad kikkerten viser...\p"
    .string "Det ligner en lille oe i horisonten!$"
