SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "Du ser traet ud.\n"
    .string "Du boer tage en kort lur.$"

SilphCo_9F_Text_DontGiveUp::
    .string "Giv ikke op!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "Tusind tak.$"

SilphCo_9F_Text_Grunt1Intro::
    .string "Dine POKeMON ser ud til at tilbede dig,\n"
    .string "unge!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "Ghaaah!$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "Hvis jeg var startet som TRAINER i\n"
    .string "din alder…$"

SilphCo_9F_Text_EdIntro::
    .string "Dine POKeMON har svaaghedspunkter!\n"
    .string "Jeg kan ramme dem!$"

SilphCo_9F_Text_EdDefeat::
    .string "Du hamrede mig!$"

SilphCo_9F_Text_EdPostBattle::
    .string "At udnytte svaaghedspunkter virker.\n"
    .string "Taenk paa typefordele.$"

SilphCo_9F_Text_Grunt2Intro::
    .string "Jeg er en af de fire ROCKET\n"
    .string "BROEDRE!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "Warg!\n"
    .string "Broedre, jeg tabte!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "Mine broedre vil haevne mig!$"

SilphCo_9F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "9. SAL$"

