SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "Du ser træt ud.\n"
    .string "Du bør tage en kort lur.$"

SilphCo_9F_Text_DontGiveUp::
    .string "Giv ikke op!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "Tusind tak.$"

SilphCo_9F_Text_Grunt1Intro::
    .string "Dine POKéMON ser ud til at tilbede dig,\n"
    .string "unge!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "Ghâah!$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "Hvis jeg var startet som TRAINER i\n"
    .string "din alder…$"

SilphCo_9F_Text_EdIntro::
    .string "Dine POKéMON har svâghedspunkter!\n"
    .string "Jeg kan ramme dem!$"

SilphCo_9F_Text_EdDefeat::
    .string "Du hamrede mig!$"

SilphCo_9F_Text_EdPostBattle::
    .string "At udnytte svâghedspunkter virker.\n"
    .string "Tænk pâ typefordele.$"

SilphCo_9F_Text_Grunt2Intro::
    .string "Jeg er en af de fire ROCKET\n"
    .string "BRØDRE!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "Warg!\n"
    .string "Brødre, jeg tabte!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "Mine brødre vil hævne mig!$"

SilphCo_9F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "9. SAL$"

