SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
    .string "Aah ja, jeg har set nogle POKeMON\n"
    .string "faerge folk over vandet!$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
    .string "Smaa traeer kan faeldes med\n"
    .string "traekket CUT.\p"
    .string "Men husk!\n"
    .string "CUT er en HM-teknik.\p"
    .string "Naar den er laert, er den ikke saa\n"
    .string "nem at slippe af med.$"

