Route25_Text_JoeyIntro::
    .string "Lokale TRAINERS kommer her for at\n"
    .string "oeve.$"

Route25_Text_JoeyDefeat::
    .string "Du er okay.$"

Route25_Text_JoeyPostBattle::
    .string "Alle POKeMON har svagheder.\n"
    .string "Selv de staerkeste.\p"
    .string "Derfor er det bedst at opdrage\n"
    .string "POKeMON af forskellige typer.$"

Route25_Text_DanIntro::
    .string "Far tog mig med til en fest paa\n"
    .string "S.S. ANNE i VERMILION CITY.$"

Route25_Text_DanDefeat::
    .string "Jeg er ikke vred!$"

Route25_Text_DanPostBattle::
    .string "Paa S.S. ANNE saa jeg TRAINERS\n"
    .string "fra hele verden.$"

Route25_Text_FlintIntro::
    .string "Jeg er en sej fyr.\n"
    .string "Jeg har en kaereste!$"

Route25_Text_FlintDefeat::
    .string "Aa, pokker...$"

Route25_Text_FlintPostBattle::
    .string "Aaa, ja.\n"
    .string "Min kaereste opmuntrer mig.$"

Route25_Text_KelseyIntro::
    .string "Hej!\n"
    .string "Min kaereste er sej!$"

Route25_Text_KelseyDefeat::
    .string "Min form er ikke den bedste...$"

Route25_Text_KelseyPostBattle::
    .string "Jeg ville oenske min kaereste var\n"
    .string "saa god som dig.$"

Route25_Text_ChadIntro::
    .string "Jeg havde en fornemmelse...\n"
    .string "Jeg vidste jeg maatte kaempe dig!$"

Route25_Text_ChadDefeat::
    .string "Jeg vidste ogsaa jeg ville tabe!$"

Route25_Text_ChadPostBattle::
    .string "Hvis din POKeMON bliver forvirret,\n"
    .string "skift den ud.\p"
    .string "Det er en god taktik.$"

Route25_Text_HaleyIntro::
    .string "Min veninde har mange soede POKeMON.\n"
    .string "Jeg er saa misundelig!$"

Route25_Text_HaleyDefeat::
    .string "Jeg er ikke saa misundelig!$"

Route25_Text_HaleyPostBattle::
    .string "Kom du fra MT. MOON?\n"
    .string "Ma jeg faa en CLEFAIRY?$"

Route25_Text_FranklinIntro::
    .string "Jeg kom lige ned fra MT. MOON,\n"
    .string "men jeg har stadig energi!$"

Route25_Text_FranklinDefeat::
    .string "Du arbejdede haardt!$"

Route25_Text_FranklinPostBattle::
    .string "Pokker!\n"
    .string "En ZUBAT bed mig i grotten.$"

Route25_Text_NobIntro::
    .string "Jeg er paa vej for at se en\n"
    .string "POKeMANIACs samling paa odden.$"

Route25_Text_NobDefeat::
    .string "Du fik mig, og rigtig godt!$"

Route25_Text_NobPostBattle::
    .string "POKeMANIAC lever virkelig op til\n"
    .string "sit navn.\p"
    .string "Hans samling indeholder mange\n"
    .string "sjaeldne POKeMON-arter.$"

Route25_Text_WayneIntro::
    .string "Skal du til BILL?\n"
    .string "Foerst kaemper vi!$"

Route25_Text_WayneDefeat::
    .string "Du er noget saerligt.$"

Route25_Text_WaynePostBattle::
    .string "Stien nedenunder er en genvej til\n"
    .string "CERULEAN CITY.$"

Route25_Text_SeaCottageSign::
    .string "SEA COTTAGE\n"
    .string "BILL bor her!$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "Denne odde er et kendt staevnemoedested.\p"
    .string "MISTY, GYM LEADER, har store\n"
    .string "forhaabninger til dette sted.$"

Route25_Text_AreYouHereAlone::
    .string "Hej, er du her alene?\p"
    .string "Hvis du er ude paa CERULEANs odde...\n"
    .string "Ja, saa burde det vaere som par.$"
