ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "Vi er KANTO RIDER FEDERATION!\n"
    .string "Vroom! Vavavavooom! Vroom!\p"
    .string "Min cykel er svag, sâ jeg mâ\n"
    .string "lave udstødningslyde selv!$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "Hey, hey, dame!\n"
    .string "Kom med lidt lommepenge!$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "Aijeeh!\p"
    .string "Hv-hvem er du?!\n"
    .string "Jeg… Jeg ringer til politiet!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "De BIKERS…\n"
    .string "Er de væk?\p"
    .string "Aah, tak gud!\n"
    .string "De skræmte mig virkelig!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "De BIKERS løb væk, og\n"
    .string "LOSTELLE blev fundet i sikkerhed.\p"
    .string "Alt endte for det bedste!$"

