PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: Hvad, det er kun {PLAYER}?\n"
    .string "Bedstefar er ikke her.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: Bedstefar!\n"
    .string "Jeg er traet af at vente!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: Hey! Bedstefar! Det er uretfaerdigt!\n"
    .string "Hvad med mig?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Heh, jeg behoever ikke vaerre\n"
    .string "graadig som dig. Jeg er moden!\p"
    .string "Vaeg du og vaelg, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: Saa tager jeg den her!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} modtog {STR_VAR_1}\n"
    .string "fra PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: Min POKeMON ser meget\n"
    .string "staerkere ud end din.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Vent, {PLAYER}!\n"
    .string "Lad os tjekke vores POKeMON!\p"
    .string "Kom saa, jeg tager imod dig!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "HVAD?\n"
    .string "Utroligt!\l"
    .string "Jeg valgte den forkerte POKeMON!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: Ja!\n"
    .string "Er jeg ikke fantastisk?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: Okay! Jeg vil laade min\n"
    .string "POKeMON kaempe for at staerke den!\p"
    .string "{PLAYER}! Bedstefar!\n"
    .string "Vi ses!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: Bedstefar!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: Jeg glemte naesten!\n"
    .string "Hvad kaldte du mig for?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: Okay, bedstefar!\n"
    .string "Lad det hele vaere op til mig!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, jeg hader at sige det, men du\n"
    .string "bliver ikke noedvendig til dette.\p"
    .string "Jeg ved det! Jeg laaner et BYKORT\n"
    .string "fra min soester!\p"
    .string "Jeg siger til hende, at hun ikke maa\n"
    .string "laane dig et, {PLAYER}! Hahaha!\p"
    .string "Gaet ikke og besoeg mig\n"
    .string "efter dette!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "OAK: {RIVAL}?\n"
    .string "Lad mig taenke…\p"
    .string "Aah, det er rigtigt, jeg bad dig\n"
    .string "komme! Bare vent!\p"
    .string "Her, {PLAYER}.\p"
    .string "Der er tre POKeMON her.\p"
    .string "Haha!\p"
    .string "POKeMON er inde i\n"
    .string "disse POKe BALLS.\p"
    .string "Da jeg var ung, var jeg en serioes\n"
    .string "POKeMON TRAeNER.\p"
    .string "Men nu, i min alderdom, har jeg\n"
    .string "kun disse tre tilbage.\p"
    .string "Du maa tage een.\n"
    .string "Kom nu, vaelg!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "OAK: Vaer taalmodig, {RIVAL}.\n"
    .string "Du maa ogsaa faa een!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "OAK: Nu, {PLAYER}.\p"
    .string "I de tre POKe BALLS er der\n"
    .string "POKeMON.\p"
    .string "Hvilken vil du vaelge til\n"
    .string "dig selv?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "OAK: Hey!\n"
    .string "Gaet ikke endnu!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Ah! CHARMANDER er dit valg.\n"
    .string "Du boer opdrage den taalmodigt.\p"
    .string "Saa, {PLAYER}, du tager den\n"
    .string "ILD POKeMON CHARMANDER?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Hm! SQUIRTLE er dit valg.\n"
    .string "Den er vaerd at opdrage.\p"
    .string "Saa, {PLAYER}, du har valgt den\n"
    .string "VAND POKeMON SQUIRTLE?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "Jeg forstaar! BULBASAUR er dit valg.\n"
    .string "Den er meget nem at opdrage.\p"
    .string "Saa, {PLAYER}, du vil have den\n"
    .string "GRAeS POKeMON BULBASAUR?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "Denne POKeMON er virkelig ret\n"
    .string "energisk!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} modtog {STR_VAR_1}\n"
    .string "fra PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "OAK: Hvis en vild POKeMON dukker op,\n"
    .string "kan din POKeMON kaempe mod den.\p"
    .string "Med den ved din side burde du\n"
    .string "kunne naa naeste by.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "OAK: {PLAYER}, opdrag din unge\n"
    .string "POKeMON ved at laade den kaempe.\p"
    .string "Den maa kaempe for at vokse.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "OAK: Aah, {PLAYER}!\n"
    .string "Hvordan har min gamle POKeMON det?\p"
    .string "Naa, den synes at blive mere\n"
    .string "knyttet til dig.\p"
    .string "Du maa vaere talentfuld som\n"
    .string "POKeMON TRAeNER.\p"
    .string "Hvad er det?\n"
    .string "Du har noget til mig?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} afleverede OAKS PAKKE.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Ah!\n"
    .string "Det er den speciallavede POKe BALL!\p"
    .string "Jeg havde bestilt den.\n"
    .string "Tak!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "OAK: Aah, rigtigt!\n"
    .string "Jeg har en anmodning til jer to.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "Paa bordet er min opfindelse,\n"
    .string "POKeDEX!\p"
    .string "Den registrerer automatisk data om\n"
    .string "POKeMON du har set eller fanget.\p"
    .string "Det er en hojteknologisk encyklopaedi!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: {PLAYER} og {RIVAL}.\n"
    .string "Tag disse med.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} modtog POKeDEX\n"
    .string "fra PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: Du kan ikke faa detaljerede data\n"
    .string "om POKeMON ved bare at se dem.\p"
    .string "Du maa fange dem for at faa\n"
    .string "komplette data.\p"
    .string "Saa her er nogle redskaber til at\n"
    .string "fange vilde POKeMON.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} modtog fem POKe BALLS.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "Naar en vild POKeMON dukker op,\n"
    .string "er det frit spil.\p"
    .string "Bare kast en POKe BALL efter den og\n"
    .string "proev at fange den!\p"
    .string "Det virker dog ikke altid.\p"
    .string "En rask POKeMON kan slippe vaek.\n"
    .string "Du maa have held!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "At lave en komplet guide over alle\n"
    .string "POKeMON i verden…\p"
    .string "Det var min drom!\p"
    .string "Men jeg er for gammel.\n"
    .string "Jeg kan ikke faa jobbet gjort.\p"
    .string "Saa jeg vil have jer to til at\n"
    .string "opfylde min drom for mig.\p"
    .string "Kom i gang, I to.\p"
    .string "Dette er et stort foretagende i\n"
    .string "POKeMON historien!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "POKeMON rundt om i verden venter\n"
    .string "paa dig, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "Hvordan ser din POKeDEX ud?\p"
    .string "{RIVAL} har allerede fanget nogle\n"
    .string "POKeMON og tilfojet til dataene.\p"
    .string "Saa, {PLAYER}, lad os se paa\n"
    .string "din POKeDEX.\p"
    .string "…Hvad er der galt?\n"
    .string "Du har ikke tilfojet nye data.\p"
    .string "Jeg giver dig disse, saa proev lidt\n"
    .string "hardere.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Kom og besoeg mig engang.\p"
    .string "Jeg vil gerne vide, hvordan din\n"
    .string "POKeDEX kommer fremad.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "Det er som en encyklopaedi, men\n"
    .string "siderne er tomme.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Det er POKe BALLS.\n"
    .string "De indeholder POKeMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "Det er PROF. OAKs sidste POKeMON.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Tryk START for at aabne MENUEN!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "GEM-muligheden er i MENUEN.\n"
    .string "Brug den regelmaessigt.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "Alle POKeMON-typer har staerker og\n"
    .string "svagheder over for andre.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "Der er en e-mail her.\p"
    .string "…\p"
    .string "Endelig!\n"
    .string "De ultimative TRAeNERE fra\l"
    .string "POKeMON LEAGUE er klar til\l"
    .string "at modtage alle udfordrere!\p"
    .string "Medbring dine bedste POKeMON og se\n"
    .string "hvordan du rangerer som TRAeNER!\p"
    .string "POKeMON LEAGUE HQ\n"
    .string "INDIGO PLATEAU\p"
    .string "PROF. OAK, besoeg os venligst!\n"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Jeg studerer POKeMON som PROF. OAKs\n"
    .string "ASSISTENT.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hej, {PLAYER}. Jeg ved du er blevet\n"
    .string "gode venner med din POKeMON.\p"
    .string "For oevrigt, vidste du om\n"
    .string "DAISY?\p"
    .string "Hvis du viser DAISY din POKeMON,\n"
    .string "kan hun sige hvor meget den kan lide dig.\p"
    .string "Lejlighedsvis vil hun endda pusle\n"
    .string "en POKeMON for dig.\p"
    .string "Det er en hemmelighed, saa fortael\n"
    .string "det ikke til nogen.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "PROF. OAK faar snart sit eget\n"
    .string "radioprogram.\p"
    .string "Programmet hedder PROF.\n"
    .string "OAKs POKeMON SEMINAR.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "PROF. OAK ser maaske ikke ud af meget,\n"
    .string "men han er autoriteten paa POKeMON.\p"
    .string "Mange POKeMON TRAeNERE holder\n"
    .string "ham i hoej anseelse.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, nu er dette fremragende!\p"
    .string "{PLAYER}, jeg har endnu en vigtig\n"
    .string "tjeneste at bede dig om.\p"
    .string "Jeg har brug for at du lytter noje.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "For nylig har der vaeret observationer\n"
    .string "af mange sjaeldne POKeMON-arter.\p"
    .string "Jeg taler om POKeMON der\n"
    .string "aldrig er set i KANTO.\p"
    .string "Jeg ville elske at se det selv,\n"
    .string "men jeg er for gammel.\p"
    .string "Da jeg ikke kan goere det, {PLAYER},\n"
    .string "vil jeg have dig til at ga i mit sted.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey, det hoerte jeg!\p"
    .string "Bedstefar, hvorfor foretraekker du\n"
    .string "{PLAYER} frem for mig hele tiden?\p"
    .string "Jeg har samlet flere POKeMON,\n"
    .string "og hurtigere ogsaa.\p"
    .string "Du burde bare lade mig tage\n"
    .string "sig af alt.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: Jeg ved det, jeg ved det.\n"
    .string "Selvfoelgelig har jeg brug for din hjaelp ogsaa.\p"
    .string "Nu har jeg brug for at se jeres\n"
    .string "POKeDEX.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. OAK tog begge POKeDEX\n"
    .string "enheder.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…Og det er gjort!\p"
    .string "Nu kan disse enheder registrere data om\n"
    .string "meget flere POKeMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}s POKeDEX blev opgraderet!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Nu, {PLAYER} og {RIVAL}!\p"
    .string "Denne gang maa I virkelig arbejde\n"
    .string "paa at udfylde jeres POKeDEX.\p"
    .string "Jeg opfordrer jer til at goere dem til de\n"
    .string "bedste og mest komplette nogensinde!\p"
    .string "Dette er virkelig et monumentalt stort\n"
    .string "foretagende i POKeMON historien!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Bedstefar, tag det roligt.\n"
    .string "Bliv ikke saa begejstret.\p"
    .string "Jeg faar POKeDEX fuldendt,\n"
    .string "bare rolig.\p"
    .string "Jeg taenker jeg proever at kigge\n"
    .string "rundt paa ONE ISLAND foerst…\p"
    .string "Anyway, jeg smutter!$"
