PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: Hvad, det er kun {PLAYER}?\n"
    .string "Bedstefar er ikke her.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: Bedstefar!\n"
    .string "Jeg er træt af at vente!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: Hey! Bedstefar! Det er uretfærdigt!\n"
    .string "Hvad med mig?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Heh, jeg behøver ikke værre\n"
    .string "grådig som dig. Jeg er moden!\p"
    .string "Væg du og vælg, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: Så tager jeg den her!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} modtog {STR_VAR_1}\n"
    .string "fra PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: Min POKéMON ser meget\n"
    .string "stærkere ud end din.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Vent, {PLAYER}!\n"
    .string "Lad os tjekke vores POKéMON!\p"
    .string "Kom så, jeg tager imod dig!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "HVAD?\n"
    .string "Utroligt!\l"
    .string "Jeg valgte den forkerte POKéMON!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: Ja!\n"
    .string "Er jeg ikke fantastisk?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: Okay! Jeg vil låde min\n"
    .string "POKéMON kæmpe for at stærke den!\p"
    .string "{PLAYER}! Bedstefar!\n"
    .string "Vi ses!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: Bedstefar!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: Jeg glemte næsten!\n"
    .string "Hvad kaldte du mig for?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: Okay, bedstefar!\n"
    .string "Lad det hele være op til mig!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, jeg hader at sige det, men du\n"
    .string "bliver ikke nødvendig til dette.\p"
    .string "Jeg ved det! Jeg låner et BYKORT\n"
    .string "fra min søster!\p"
    .string "Jeg siger til hende, at hun ikke må\n"
    .string "låne dig et, {PLAYER}! Hahaha!\p"
    .string "Gæt ikke og besøg mig\n"
    .string "efter dette!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "OAK: {RIVAL}?\n"
    .string "Lad mig tænke…\p"
    .string "Aah, det er rigtigt, jeg bad dig\n"
    .string "komme! Bare vent!\p"
    .string "Her, {PLAYER}.\p"
    .string "Der er tre POKéMON her.\p"
    .string "Haha!\p"
    .string "POKéMON er inde i\n"
    .string "disse POKe BALLS.\p"
    .string "Da jeg var ung, var jeg en seriøs\n"
    .string "POKéMON TRÆNER.\p"
    .string "Men nu, i min alderdom, har jeg\n"
    .string "kun disse tre tilbage.\p"
    .string "Du må tage een.\n"
    .string "Kom nu, vælg!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "OAK: Vær tålmodig, {RIVAL}.\n"
    .string "Du må også få een!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "OAK: Nu, {PLAYER}.\p"
    .string "I de tre POKe BALLS er der\n"
    .string "POKéMON.\p"
    .string "Hvilken vil du vælge til\n"
    .string "dig selv?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "OAK: Hey!\n"
    .string "Gæt ikke endnu!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Ah! CHARMANDER er dit valg.\n"
    .string "Du bør opdrage den tålmodigt.\p"
    .string "Så, {PLAYER}, du tager den\n"
    .string "ILD POKéMON CHARMANDER?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Hm! SQUIRTLE er dit valg.\n"
    .string "Den er værd at opdrage.\p"
    .string "Så, {PLAYER}, du har valgt den\n"
    .string "VAND POKéMON SQUIRTLE?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "Jeg forstår! BULBASAUR er dit valg.\n"
    .string "Den er meget nem at opdrage.\p"
    .string "Så, {PLAYER}, du vil have den\n"
    .string "GRÆS POKéMON BULBASAUR?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "Denne POKéMON er virkelig ret\n"
    .string "energisk!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} modtog {STR_VAR_1}\n"
    .string "fra PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "OAK: Hvis en vild POKéMON dukker op,\n"
    .string "kan din POKéMON kæmpe mod den.\p"
    .string "Med den ved din side burde du\n"
    .string "kunne nå næste by.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "OAK: {PLAYER}, opdrag din unge\n"
    .string "POKéMON ved at låde den kæmpe.\p"
    .string "Den må kæmpe for at vokse.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "OAK: Aah, {PLAYER}!\n"
    .string "Hvordan har min gamle POKéMON det?\p"
    .string "Nå, den synes at blive mere\n"
    .string "knyttet til dig.\p"
    .string "Du må være talentfuld som\n"
    .string "POKéMON TRÆNER.\p"
    .string "Hvad er det?\n"
    .string "Du har noget til mig?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} afleverede OAKS PAKKE.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Ah!\n"
    .string "Det er den speciallavede POKe BALL!\p"
    .string "Jeg havde bestilt den.\n"
    .string "Tak!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "OAK: Aah, rigtigt!\n"
    .string "Jeg har en anmodning til jer to.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "På bordet er min opfindelse,\n"
    .string "POKéDEX!\p"
    .string "Den registrerer automatisk data om\n"
    .string "POKéMON du har set eller fanget.\p"
    .string "Det er en hojteknologisk encyklopædi!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: {PLAYER} og {RIVAL}.\n"
    .string "Tag disse med.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} modtog POKéDEX\n"
    .string "fra PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: Du kan ikke få detaljerede data\n"
    .string "om POKéMON ved bare at se dem.\p"
    .string "Du må fange dem for at få\n"
    .string "komplette data.\p"
    .string "Så her er nogle redskaber til at\n"
    .string "fange vilde POKéMON.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} modtog fem POKe BALLS.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "Når en vild POKéMON dukker op,\n"
    .string "er det frit spil.\p"
    .string "Bare kast en POKe BALL efter den og\n"
    .string "prøv at fange den!\p"
    .string "Det virker dog ikke altid.\p"
    .string "En rask POKéMON kan slippe væk.\n"
    .string "Du må have held!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "At lave en komplet guide over alle\n"
    .string "POKéMON i verden…\p"
    .string "Det var min drom!\p"
    .string "Men jeg er for gammel.\n"
    .string "Jeg kan ikke få jobbet gjort.\p"
    .string "Så jeg vil have jer to til at\n"
    .string "opfylde min drom for mig.\p"
    .string "Kom i gang, I to.\p"
    .string "Dette er et stort foretagende i\n"
    .string "POKéMON historien!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "POKéMON rundt om i verden venter\n"
    .string "på dig, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "Hvordan ser din POKéDEX ud?\p"
    .string "{RIVAL} har allerede fanget nogle\n"
    .string "POKéMON og tilfojet til datæne.\p"
    .string "Så, {PLAYER}, lad os se på\n"
    .string "din POKéDEX.\p"
    .string "…Hvad er der galt?\n"
    .string "Du har ikke tilfojet nye data.\p"
    .string "Jeg giver dig disse, så prøv lidt\n"
    .string "hardere.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Kom og besøg mig engang.\p"
    .string "Jeg vil gerne vide, hvordan din\n"
    .string "POKéDEX kommer fremad.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "Det er som en encyklopædi, men\n"
    .string "siderne er tomme.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Det er POKe BALLS.\n"
    .string "De indeholder POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "Det er PROF. OAKs sidste POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Tryk START for at åbne MENUEN!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "GEM-muligheden er i MENUEN.\n"
    .string "Brug den regelmæssigt.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "Alle POKéMON-typer har stærker og\n"
    .string "svagheder over for andre.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "Der er en e-mail her.\p"
    .string "…\p"
    .string "Endelig!\n"
    .string "De ultimative TRÆNERE fra\l"
    .string "POKéMON LEAGUE er klar til\l"
    .string "at modtage alle udfordrere!\p"
    .string "Medbring dine bedste POKéMON og se\n"
    .string "hvordan du rangerer som TRÆNER!\p"
    .string "POKéMON LEAGUE HQ\n"
    .string "INDIGO PLATEAU\p"
    .string "PROF. OAK, besøg os venligst!\n"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Jeg studerer POKéMON som PROF. OAKs\n"
    .string "ASSISTENT.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hej, {PLAYER}. Jeg ved du er blevet\n"
    .string "gode venner med din POKéMON.\p"
    .string "For øvrigt, vidste du om\n"
    .string "DAISY?\p"
    .string "Hvis du viser DAISY din POKéMON,\n"
    .string "kan hun sige hvor meget den kan lide dig.\p"
    .string "Lejlighedsvis vil hun endda pusle\n"
    .string "en POKéMON for dig.\p"
    .string "Det er en hemmelighed, så fortæl\n"
    .string "det ikke til nogen.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "PROF. OAK får snart sit eget\n"
    .string "radioprogram.\p"
    .string "Programmet hedder PROF.\n"
    .string "OAKs POKéMON SEMINAR.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "PROF. OAK ser måske ikke ud af meget,\n"
    .string "men han er autoriteten på POKéMON.\p"
    .string "Mange POKéMON TRÆNERE holder\n"
    .string "ham i høj anseelse.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, nu er dette fremragende!\p"
    .string "{PLAYER}, jeg har endnu en vigtig\n"
    .string "tjeneste at bede dig om.\p"
    .string "Jeg har brug for at du lytter noje.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "For nylig har der været observationer\n"
    .string "af mange sjældne POKéMON-arter.\p"
    .string "Jeg taler om POKéMON der\n"
    .string "aldrig er set i KANTO.\p"
    .string "Jeg ville elske at se det selv,\n"
    .string "men jeg er for gammel.\p"
    .string "Da jeg ikke kan gøre det, {PLAYER},\n"
    .string "vil jeg have dig til at ga i mit sted.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey, det hørte jeg!\p"
    .string "Bedstefar, hvorfor foretrækker du\n"
    .string "{PLAYER} frem for mig hele tiden?\p"
    .string "Jeg har samlet flere POKéMON,\n"
    .string "og hurtigere også.\p"
    .string "Du burde bare lade mig tage\n"
    .string "sig af alt.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: Jeg ved det, jeg ved det.\n"
    .string "Selvfølgelig har jeg brug for din hjælp også.\p"
    .string "Nu har jeg brug for at se jeres\n"
    .string "POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. OAK tog begge POKéDEX\n"
    .string "enheder.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…Og det er gjort!\p"
    .string "Nu kan disse enheder registrere data om\n"
    .string "meget flere POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}s POKéDEX blev opgraderet!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Nu, {PLAYER} og {RIVAL}!\p"
    .string "Denne gang må I virkelig arbejde\n"
    .string "på at udfylde jeres POKéDEX.\p"
    .string "Jeg opfordrer jer til at gøre dem til de\n"
    .string "bedste og mest komplette nogensinde!\p"
    .string "Dette er virkelig et monumentalt stort\n"
    .string "foretagende i POKéMON historien!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Bedstefar, tag det roligt.\n"
    .string "Bliv ikke så begejstret.\p"
    .string "Jeg får POKéDEX fuldendt,\n"
    .string "bare rolig.\p"
    .string "Jeg tænker jeg prøver at kigge\n"
    .string "rundt på ONE ISLAND først…\p"
    .string "Anyway, jeg smutter!$"
