FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .string "Vi har haft en stor og stærk\n"
    .string "TRAINER vokse op pâ denne ø.\p"
    .string "Selv du kender hende sikkert.\n"
    .string "Det er LORELEI fra ELITE FOUR!\p"
    .string "Da LORELEI var lille lærte jeg\n"
    .string "hende om POKéMON.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "SEVII ISLANDS er et varmt\n"
    .string "omrâde overall.\p"
    .string "Men der er én undtagelse du skal\n"
    .string "vide om.\p"
    .string "ICEFALL CAVE er isnende pga. de\n"
    .string "POKéMON der lever der.$"

