FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .string "Vi har haft en stor og staerk\n"
    .string "TRAINER vokse op paa denne oe.\p"
    .string "Selv du kender hende sikkert.\n"
    .string "Det er LORELEI fra ELITE FOUR!\p"
    .string "Da LORELEI var lille laerte jeg\n"
    .string "hende om POKeMON.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "SEVII ISLANDS er et varmt\n"
    .string "omraade overall.\p"
    .string "Men der er én undtagelse du skal\n"
    .string "vide om.\p"
    .string "ICEFALL CAVE er isnende pga. de\n"
    .string "POKeMON der lever der.$"

