@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}s taske ser fuld ud.$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "Synes du ikke det er svært at finde\n"
    .string "pâ gode navne til POKéMON?\p"
    .string "Især hvis du har fanget en hel\n"
    .string "flok?\p"
    .string "I LAVENDER TOWN er der en mand\n"
    .string "der bedømmer POKéMON-kælenavne.\p"
    .string "Han kan endda hjælpe dig med at\n"
    .string "omdøbe dine POKéMON.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "Hvis du vil til LAVENDER TOWN,\n"
    .string "tag ROCK TUNNEL.\p"
    .string "Du kan nâ ROCK TUNNEL fra\n"
    .string "CERULEAN CITY.$"
