@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}s taske ser fuld ud.$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "Synes du ikke det er svaert at finde\n"
    .string "paa gode navne til POKeMON?\p"
    .string "Isaer hvis du har fanget en hel\n"
    .string "flok?\p"
    .string "I LAVENDER TOWN er der en mand\n"
    .string "der bedoemmer POKeMON-kaelenavne.\p"
    .string "Han kan endda hjaelpe dig med at\n"
    .string "omdoebe dine POKeMON.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "Hvis du vil til LAVENDER TOWN,\n"
    .string "tag ROCK TUNNEL.\p"
    .string "Du kan naa ROCK TUNNEL fra\n"
    .string "CERULEAN CITY.$"
