Route9_Text_AliciaIntro::
    .string "Du har POKeMON med dig!\n"
    .string "Du er min!$"

Route9_Text_AliciaDefeat::
    .string "Du bedrog mig…$"

Route9_Text_AliciaPostBattle::
    .string "Tunnelen forude er bälgmörk\n"
    .string "inde.\p"
    .string "Du har brug for FLASH for at\n"
    .string "komme igennem.$"

Route9_Text_ChrisIntro::
    .string "Hvem er det der gâr med sâdanne\n"
    .string "flotte POKeMON?$"

Route9_Text_ChrisDefeat::
    .string "Ude som et lys!$"

Route9_Text_ChrisPostBattle::
    .string "Bliv ved at gâ!$"

Route9_Text_DrewIntro::
    .string "Jeg tager ROCK TUNNEL for at\n"
    .string "komme til LAVENDER…$"

Route9_Text_DrewDefeat::
    .string "Kan ikke mâle mig…$"

Route9_Text_DrewPostBattle::
    .string "Skal du ogsâ til ROCK TUNNEL?$"

Route9_Text_CaitlinIntro::
    .string "Du mâ ikke tale ned til mig!$"

Route9_Text_CaitlinDefeat::
    .string "Nej!\n"
    .string "Du er for meget.$"

Route9_Text_CaitlinPostBattle::
    .string "Du er tydeligvis talentfuld.\n"
    .string "Held og lykke!$"

Route9_Text_JeremyIntro::
    .string "Bwahaha!\n"
    .string "Fedt! Jeg kede mig, eh!$"

Route9_Text_JeremyDefeat::
    .string "Kom med mere, eh!\p"
    .string "Oh vent.\n"
    .string "Jeg har ikke flere POKeMON!$"

Route9_Text_JeremyPostBattle::
    .string "Du havde virkelig mod til at\n"
    .string "stâ op mod mig, eh?$"

Route9_Text_BriceIntro::
    .string "Hahaha!\n"
    .string "Er du ikke en lille hârdnakket en!$"

Route9_Text_BriceDefeat::
    .string "Hvad var det?$"

Route9_Text_BricePostBattle::
    .string "Hahaha!\n"
    .string "Börn bör väre hârdnakkede!$"

Route9_Text_BrentIntro::
    .string "Jeg stod op tidligt hver dag for at\n"
    .string "opdrage mine POKeMON fra kokoner!$"

Route9_Text_BrentDefeat::
    .string "HVAD?\p"
    .string "Sikke et spild af tid!$"

Route9_Text_BrentPostBattle::
    .string "Jeg mâ samle mere end insekter\n"
    .string "for at blive stärkere…$"

Route9_Text_AlanIntro::
    .string "Hahahaha!\n"
    .string "Kom an!$"

Route9_Text_AlanDefeat::
    .string "Hahahaha!\n"
    .string "Du slog mig ärligt!$"

Route9_Text_AlanPostBattle::
    .string "Hahahaha!\n"
    .string "Os härtige fyre griner altid!$"

Route9_Text_ConnerIntro::
    .string "Frem, mine super BUG POKeMON!$"

Route9_Text_ConnerDefeat::
    .string "Mine insekter…$"

Route9_Text_ConnerPostBattle::
    .string "Hvis du ikke kan lide BUG POKeMON,\n"
    .string "irriterer du mig!$"

Route9_Text_RouteSign::
    .string "ROUTE 9\n"
    .string "CERULEAN CITY - ROCK TUNNEL$"
