Route24_Text_JustEarnedFabulousPrize::
    .string "Tillykke! Du slog vores fem\n"
    .string "konkurrence-TRAINERS!\p"
    .string "Du har lige tjent en fantastisk prämie!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer::
    .string "{PLAYER} modtog et NUGGET\n"
    .string "fra den mystiske TRAINER!$"

Route24_Text_YouDontHaveAnyRoom::
    .string "Du har ikke plads!$"

Route24_Text_JoinTeamRocket::
    .string "For resten, hvad siger du til at\n"
    .string "bli med i TEAM ROCKET?\p"
    .string "Vi er en gruppe professionelle\n"
    .string "kriminelle der specialiserer sig i POKéMON!\p"
    .string "Vil du väre med?\p"
    .string "Er du sikker?\p"
    .string "Kom nu, vär med os!\p"
    .string "Jeg siger du skal väre med!\p"
    .string "...Okay, du har brug for overbevisning!\p"
    .string "Jeg giver dig et tilbud du ikke\n"
    .string "kan sige nej til!$"

Route24_Text_RocketDefeat::
    .string "Arrgh!\n"
    .string "Du er god!$"

Route24_Text_YoudBecomeTopRocketLeader::
    .string "Med dine evner ville du blive\n"
    .string "en top-leder i TEAM ROCKET.\p"
    .string "Kom nu, tänk pâ muligheden!\n"
    .string "Spild ikke denne chance.$"

Route24_Text_ShaneIntro::
    .string "Jeg sâ din bedrift fra grässet!$"

Route24_Text_ShaneDefeat::
    .string "Som jeg tänkte!$"

Route24_Text_ShanePostBattle::
    .string "Jeg gemte mig fordi folkene pâ\n"
    .string "brön skrämte mig.$"

Route24_Text_EthanIntro::
    .string "Okay! Jeg er nr. 5!\n"
    .string "Jeg tramper dig!$"

Route24_Text_EthanDefeat::
    .string "Whoa!\n"
    .string "For meget!$"

Route24_Text_EthanPostBattle::
    .string "Jeg gjorde mit bedste. Ingen fortrydelser!$"

Route24_Text_ReliIntro::
    .string "Jeg er nr. 4!\n"
    .string "Bliver du trät?$"

Route24_Text_ReliDefeat::
    .string "Jeg tabte ogsâ!$"

Route24_Text_ReliPostBattle::
    .string "Jeg gjorde mit bedste, sâ jeg\n"
    .string "har ingen fortrydelser!$"

Route24_Text_TimmyIntro::
    .string "Her er nr. 3!\n"
    .string "Jeg bliver ikke nem!$"

Route24_Text_TimmyDefeat::
    .string "Av!\n"
    .string "Fladet helt!$"

Route24_Text_TimmyPostBattle::
    .string "Jeg gjorde mit bedste. Ingen fortrydelser!$"

Route24_Text_AliIntro::
    .string "Jeg er nr. 2!\n"
    .string "Nu bliver det alvorligt!$"

Route24_Text_AliDefeat::
    .string "Hvordan kunne jeg tabe?$"

Route24_Text_AliPostBattle::
    .string "Jeg gjorde mit bedste. Ingen fortrydelser!$"

Route24_Text_CaleIntro::
    .string "Folk kalder dette NUGGET BRÖN!\p"
    .string "Slâ os fem TRAINERS og vind\n"
    .string "en fantastisk prämie!\p"
    .string "Tror du du har hvad det kräver?$"

Route24_Text_CaleDefeat::
    .string "Whoo!\n"
    .string "Godt gâet!$"

Route24_Text_CalePostBattle::
    .string "Jeg gjorde mit bedste. Ingen fortrydelser!$"
