ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
    .string "Er det sandt?\p"
    .string "CELADON DEPT. STORE er flere\n"
    .string "gange stoerre end denne butik?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
    .string "Jeg koebe nogle gange medicin her.\p"
    .string "Men mange helbreder POKeMON\n"
    .string "med BAeR fra BERRY FOREST.\p"
    .string "BAeR er trods alt gratis og\n"
    .string "de loebe aldrig toer.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
    .string "De BIKERS var ved at oedelaegge\n"
    .string "denne POKeMON MART.\p"
    .string "Er jeg glad for de besluttede at tage af sted!$"

