ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
    .string "Er det sandt?\p"
    .string "CELADON DEPT. STORE er flere\n"
    .string "gange större end denne butik?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
    .string "Jeg köbe nogle gange medicin her.\p"
    .string "Men mange helbreder POKéMON\n"
    .string "med BÆR fra BERRY FOREST.\p"
    .string "BÆR er trods alt gratis og\n"
    .string "de löbe aldrig tör.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
    .string "De BIKERS var ved at ödelägge\n"
    .string "denne POKéMON MART.\p"
    .string "Er jeg glad for de besluttede at tage af sted!$"

