ThreeIsland_BondBridge_Text_NikkiIntro::
    .string "Det salte tang fra havet…\n"
    .string "Det kilder mit hjerte.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
    .string "…Snus, snus…\n"
    .string "Noget lugter ubehageligt…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
    .string "Mâske er den stank din svedige\n"
    .string "POKéMONs kropslugt…$"

ThreeIsland_BondBridge_Text_VioletIntro::
    .string "Hvor skal du hen i sâ stor fart?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
    .string "Du opdrager nogle vidunderlige\n"
    .string "POKéMON.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
    .string "Hvis du fortsætter denne vej, nâr\n"
    .string "du til sidst BERRY FOREST.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
    .string "Min mor sagde at jeg ikke mâ svømme\n"
    .string "uden min svømmering.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
    .string "Wâah!\n"
    .string "Wâah!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
    .string "I âr lærer jeg endelig\n"
    .string "at svømme!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
    .string "Yay, yay!\n"
    .string "POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
    .string "Hvad sker der nu?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
    .string "Vandt jeg lige?\n"
    .string "Eller tabte jeg?$"

ThreeIsland_BondBridge_Text_TishaIntro::
    .string "Aah nej, kom ikke her!\n"
    .string "Venligst hold dig væk fra mig!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
    .string "Okay, du vandt!\n"
    .string "Vil du venligst gâ væk nu?$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
    .string "En POKéMON bed igennem mit\n"
    .string "badedragt.\p"
    .string "Jeg kan ikke komme ud af vandet!$"

ThreeIsland_BondBridge_Text_JoyIntro::
    .string "JOY: Vi lærer dig hvad vores\n"
    .string "yndlings-POKéMON er!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
    .string "JOY: Aâah…\n"
    .string "MEG!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
    .string "JOY: Var det ikke sjovt?\n"
    .string "Jeg hâber vi kan kæmpe igen!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
    .string "JOY: Jeg vil virkelig gerne kæmpe med\n"
    .string "MEG.\p"
    .string "Én POKéMON er ikke nok.$"

ThreeIsland_BondBridge_Text_MegIntro::
    .string "MEG: Vi viser dig vores yndlings-\n"
    .string "POKéMON.$"

ThreeIsland_BondBridge_Text_MegDefeat::
    .string "MEG: Aâah…\n"
    .string "JOY!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
    .string "MEG: JOY, var det ikke sjovt?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
    .string "MEG: Jeg vil gerne kæmpe sammen\n"
    .string "med JOY.\p"
    .string "Én POKéMON er ikke nok.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .string "BERRY FOREST FORUDE$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .string "BOND BRIDGE\n"
    .string "Vær venligst stille ved overgang.\p"
    .string "BERRY FOREST FORUDE$"

