ThreeIsland_BondBridge_Text_NikkiIntro::
    .string "Det salte tang fra havet…\n"
    .string "Det kilder mit hjerte.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
    .string "…Snus, snus…\n"
    .string "Noget lugter ubehageligt…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
    .string "Maaske er den stank din svedige\n"
    .string "POKeMONs kropslugt…$"

ThreeIsland_BondBridge_Text_VioletIntro::
    .string "Hvor skal du hen i saa stor fart?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
    .string "Du opdrager nogle vidunderlige\n"
    .string "POKeMON.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
    .string "Hvis du fortsaetter denne vej, naar\n"
    .string "du til sidst BERRY FOREST.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
    .string "Min mor sagde at jeg ikke maa svoemme\n"
    .string "uden min svoemmering.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
    .string "Waaah!\n"
    .string "Waaah!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
    .string "I aar laerer jeg endelig\n"
    .string "at svoemme!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
    .string "Yay, yay!\n"
    .string "POKeMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
    .string "Hvad sker der nu?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
    .string "Vandt jeg lige?\n"
    .string "Eller tabte jeg?$"

ThreeIsland_BondBridge_Text_TishaIntro::
    .string "Aah nej, kom ikke her!\n"
    .string "Venligst hold dig vaek fra mig!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
    .string "Okay, du vandt!\n"
    .string "Vil du venligst gaa vaek nu?$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
    .string "En POKeMON bed igennem mit\n"
    .string "badedragt.\p"
    .string "Jeg kan ikke komme ud af vandet!$"

ThreeIsland_BondBridge_Text_JoyIntro::
    .string "JOY: Vi laerer dig hvad vores\n"
    .string "yndlings-POKeMON er!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
    .string "JOY: Aaaah…\n"
    .string "MEG!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
    .string "JOY: Var det ikke sjovt?\n"
    .string "Jeg haaber vi kan kaempe igen!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
    .string "JOY: Jeg vil virkelig gerne kaempe med\n"
    .string "MEG.\p"
    .string "Én POKeMON er ikke nok.$"

ThreeIsland_BondBridge_Text_MegIntro::
    .string "MEG: Vi viser dig vores yndlings-\n"
    .string "POKeMON.$"

ThreeIsland_BondBridge_Text_MegDefeat::
    .string "MEG: Aaaah…\n"
    .string "JOY!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
    .string "MEG: JOY, var det ikke sjovt?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
    .string "MEG: Jeg vil gerne kaempe sammen\n"
    .string "med JOY.\p"
    .string "Én POKeMON er ikke nok.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .string "BERRY FOREST FORUDE$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .string "BOND BRIDGE\n"
    .string "Vaer venligst stille ved overgang.\p"
    .string "BERRY FOREST FORUDE$"

