FiveIsland_ResortGorgeous_Text_DaisyIntro::
    .string "Med disse hænder skaber jeg\n"
    .string "min sejr!$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
    .string "Skammen ved det her…\n"
    .string "Jeg er rød i hovedet…$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
    .string "Ups, mine malerrør er spredt\n"
    .string "overalt!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro::
    .string "Undskyld!\n"
    .string "Jeg prøver at male.\l"
    .string "Hold dig væk fra mit syn!$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
    .string "Dette nederlag…\n"
    .string "Jeg føler mig hvid ud…$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
    .string "GILLIAN?\n"
    .string "Hold venligst hovedet lidt…\l"
    .string "Sâ! Det er det udtryk jeg vil!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro::
    .string "Hmm…\n"
    .string "Vinklen er ikke helt rigtig…$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
    .string "Øh…\n"
    .string "Mine følelser er blâe…$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
    .string "Himlen og havet…\n"
    .string "De er sâ ustadige.\p"
    .string "Deres skiftende udtryk gør dem\n"
    .string "svære at fânge.$"

FiveIsland_ResortGorgeous_Text_JackiIntro::
    .string "Jeg besøger min vens tilflugtssted,\n"
    .string "hvis du vil vide det.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat::
    .string "Øh, du er stærk.$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
    .string "Jeg synes det er behageligt at\n"
    .string "kæmpe roligt i den blide havbrise.$"

FiveIsland_ResortGorgeous_Text_GillianIntro::
    .string "Jeg overvejer at lave et pool\n"
    .string "specielt til POKéMON.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat::
    .string "Øh, du godeste!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
    .string "Et pool ville være rart, men et\n"
    .string "solrum kunne være sublimt.$"

FiveIsland_ResortGorgeous_Text_DestinIntro::
    .string "Jeg er god til at løbe.\n"
    .string "Jeg er virkelig hurtig!$"

FiveIsland_ResortGorgeous_Text_DestinDefeat::
    .string "Ups!\n"
    .string "Jeg skyndte mig for meget!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
    .string "Nâr jeg løber med vinden, føles\n"
    .string "det som om jeg kunne flyve!$"

FiveIsland_ResortGorgeous_Text_TobyIntro::
    .string "Marinelivet her pâ dette resort\n"
    .string "tiltaler mig.$"

FiveIsland_ResortGorgeous_Text_TobyDefeat::
    .string "Det er chokerende!\n"
    .string "Du mâ joke.$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
    .string "At tage det sâ alvorligt…\n"
    .string "Hvor meningsløst.$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
    .string "SELPHY: Tak.\p"
    .string "Du mâ gâ nu.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse::
    .string "SELPHYS HUS$"

