CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "REPEL holder ikke kun insekter væk,\n"
    .string "det virker ogsâ pâ svække POKéMON.\p"
    .string "Sæt din stærkeste POKéMON til\n"
    .string "venstre i POKéMON LISTEN.\p"
    .string "Hvis din første POKéMON er stærk,\n"
    .string "forstærkes REPELs effekt.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Ved du noget om RARE CANDY?\n"
    .string "De sælges ikke i butikker.\p"
    .string "Jeg tror det fâr POKéMON til at gro\n"
    .string "meget hurtigt med et.$"
