CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "REPEL holder ikke kun insekter väk,\n"
    .string "det virker ogsâ pâ sväkke POKéMON.\p"
    .string "Sät din stärkeste POKéMON til\n"
    .string "venstre i POKéMON LISTEN.\p"
    .string "Hvis din förste POKéMON er stärk,\n"
    .string "forstärkes REPELs effekt.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Ved du noget om RARE CANDY?\n"
    .string "De sälges ikke i butikker.\p"
    .string "Jeg tror det fâr POKéMON til at gro\n"
    .string "meget hurtigt med et.$"
