CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "REPEL holder ikke kun insekter vaek,\n"
    .string "det virker ogsaa paa svaekke POKeMON.\p"
    .string "Saet din staerkeste POKeMON til\n"
    .string "venstre i POKeMON LISTEN.\p"
    .string "Hvis din foerste POKeMON er staerk,\n"
    .string "forstaerkes REPELs effekt.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Ved du noget om RARE CANDY?\n"
    .string "De saelges ikke i butikker.\p"
    .string "Jeg tror det faar POKeMON til at gro\n"
    .string "meget hurtigt med et.$"
