Route11_Text_HugoIntro::
    .string "Vind, tab eller uafgjort!$"

Route11_Text_HugoDefeat::
    .string "Atcha!\n"
    .string "Det gik ikke min vej!$"

Route11_Text_HugoPostBattle::
    .string "POKéMON er livet!\n"
    .string "Og at leve er at spille spil!$"

Route11_Text_JasperIntro::
    .string "Konkurrence!\n"
    .string "Jeg fâr ikke nok!$"

Route11_Text_JasperDefeat::
    .string "Jeg havde en chance!$"

Route11_Text_JasperPostBattle::
    .string "Du kan ikke være en kujon i\n"
    .string "POKéMONs verden!$"

Route11_Text_EddieIntro::
    .string "Lad os kæmpe, men fuske ikke!$"

Route11_Text_EddieDefeat::
    .string "Hvad?\n"
    .string "Det er ikke rigtigt!$"

Route11_Text_EddiePostBattle::
    .string "Jeg gjorde mit bedste.\n"
    .string "Jeg har ingen fortrydelser.$"

Route11_Text_BraxtonIntro::
    .string "Forsigtig!\n"
    .string "Jeg lægger kabler!$"

Route11_Text_BraxtonDefeat::
    .string "Det var elektrisk!$"

Route11_Text_BraxtonPostBattle::
    .string "Spred ordet om at spare energi!$"

Route11_Text_DillonIntro::
    .string "Jeg er lige blevet TRAINER.\n"
    .string "Men jeg tror jeg kan vinde.$"

Route11_Text_DillonDefeat::
    .string "Mine POKéMON kunne ikke vinde…\n"
    .string "Er de ikke vokset nok?$"

Route11_Text_DillonPostBattle::
    .string "Hvad nu?\n"
    .string "Lad mig være!$"

Route11_Text_DirkIntro::
    .string "Fwahaha!\n"
    .string "Jeg har aldrig tabt!$"

Route11_Text_DirkDefeat::
    .string "Mit første nederlag!$"

Route11_Text_DirkPostBattle::
    .string "Du havde bare held, det er alt.$"

Route11_Text_DarianIntro::
    .string "Jeg har aldrig vundet før…$"

Route11_Text_DarianDefeat::
    .string "Jeg sâ det komme…$"

Route11_Text_DarianPostBattle::
    .string "Jeg var uheldig, som altid.$"

Route11_Text_YasuIntro::
    .string "Jeg er den bedste i min klasse.\n"
    .string "Jeg træner hver morgen.$"

Route11_Text_YasuDefeat::
    .string "Pokkers!\n"
    .string "Mine POKéMON skal være stærkere!$"

Route11_Text_YasuPostBattle::
    .string "Der er en fed POKéMON der kommer\n"
    .string "ned fra bjergene.\p"
    .string "Jeg vedder pâ den er stærk, hvis\n"
    .string "du kan fange den.$"

Route11_Text_BernieIntro::
    .string "Pas pâ de levende ledninger!$"

Route11_Text_BernieDefeat::
    .string "Whoa!\n"
    .string "Du gnistplade!$"

Route11_Text_BerniePostBattle::
    .string "Nu mâ jeg tilbage til arbejdet.$"

Route11_Text_DaveIntro::
    .string "Jeg har opdraget mine POKéMON\n"
    .string "omhyggeligt. De bør være klar nu!$"

Route11_Text_DaveDefeat::
    .string "Hej-hej!\n"
    .string "Tak og farvel!$"

Route11_Text_DavePostBattle::
    .string "Tch…\n"
    .string "Jeg mâ finde stærkere!$"

Route11_Text_DiglettsCave::
    .string "DIGLETT'S CAVE$"
