CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "Hehehe!\p"
    .string "Spilleautomaterne traekker bare\n"
    .string "penge ind, stort!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "CHEF!\p"
    .string "Vi har lige sendt to tusind\n"
    .string "flere POKeMON som spillepraemier\l"
    .string "igen i dag!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "Roer ikke plakaten ved GAME\n"
    .string "CORNER!\p"
    .string "Der er ingen hemmelig kontakt bag den!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
