SixIsland_OutcastIsland_Text_RocketIntro::
    .string "Der er ingen sjældne POKéMON omkring\n"
    .string "disse egne! Ikke én!\p"
    .string "Det ærger mig, mand.\n"
    .string "Jeg tager det ud over dig!$"

SixIsland_OutcastIsland_Text_RocketDefeat::
    .string "…Hva?$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
    .string "Hør her, har du ikke set nogen\n"
    .string "sjældne POKéMON?$"

SixIsland_OutcastIsland_Text_TylorIntro::
    .string "Jeg har slet ikke heldet med mig.\n"
    .string "En kamp ville være en afveksling!$"

SixIsland_OutcastIsland_Text_TylorDefeat::
    .string "Næ, intet held overhovedet…$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
    .string "Jeg kan ikke rigtig tage hjem uden\n"
    .string "at fange noget.$"

SixIsland_OutcastIsland_Text_MymoIntro::
    .string "Gisp… Gisp…\p"
    .string "Jeg svømmede herfra SIX ISLE PORT\n"
    .string "i én omgang.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
    .string "Gisp…\n"
    .string "Gisp…$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
    .string "Jeg er kun halvvejs…\n"
    .string "Jeg er udmattet…$"

SixIsland_OutcastIsland_Text_NicoleIntro::
    .string "Det er ikke sâ let at sende POKéMON\n"
    .string "ud mens man svømmer, ved du?$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
    .string "Jeg tabte ikke til dig i svømning.\n"
    .string "Det generer mig ikke.$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
    .string "Er du pâ vej til øen deroppe\n"
    .string "forbi her?\p"
    .string "Jeg sâ ikke noget interessant\n"
    .string "der.$"

SixIsland_OutcastIsland_Text_AvaIntro::
    .string "AVA: Lad os have en to-mod-to\n"
    .string "marinkamp!$"

SixIsland_OutcastIsland_Text_AvaDefeat::
    .string "AVA: Aah, du er fantastisk!\n"
    .string "Endnu bedre, du er alene!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
    .string "AVA: Du ved, jeg foretrækker\n"
    .string "havet fremfor nogen pool.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
    .string "AVA: Du udfordrer os til\n"
    .string "en kamp?\p"
    .string "Du skal bruge mindst to POKéMON\n"
    .string "hvis du vil gøre det.$"

SixIsland_OutcastIsland_Text_GebIntro::
    .string "GEB: Store Søster, hjælp!\n"
    .string "Kæmp venligst med mig!$"

SixIsland_OutcastIsland_Text_GebDefeat::
    .string "GEB: Wow, Store Søster, denne person\n"
    .string "er virkelig god!$"

SixIsland_OutcastIsland_Text_GebPostBattle::
    .string "GEB: Jeg holder fast i min søster\n"
    .string "fordi jeg ikke kan nâ bunden.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
    .string "GEB: Kæmp venligst mod mig og\n"
    .string "min søster!\p"
    .string "…Aah, har du ikke to POKéMON?$"
