Route14_Text_CarterIntro::
    .string "Du skal bruge TMs til at laere\n"
    .string "gode angreb til POKeMON.$"

Route14_Text_CarterDefeat::
    .string "Ikke helt god nok endnu.$"

Route14_Text_CarterPostBattle::
    .string "Du har nogle HMs, ikke? POKeMON\n"
    .string "kan ikke glemme de angreb nemt.$"

Route14_Text_MitchIntro::
    .string "Mine fugle-POKeMON burde vaere\n"
    .string "klar til kamp.$"

Route14_Text_MitchDefeat::
    .string "Ikke klar endnu!$"

Route14_Text_MitchPostBattle::
    .string "Mine fugle-POKeMON skal laere\n"
    .string "bedre angreb.$"

Route14_Text_BeckIntro::
    .string "De har TMs til salg i\n"
    .string "CELADON DEPT. STORE.\p"
    .string "TMs er ikke rigtig sjaeldne, men ikke\n"
    .string "mange har HMs.$"

Route14_Text_BeckDefeat::
    .string "Av, aergerligt!$"

Route14_Text_BeckPostBattle::
    .string "Proev at laere POKeMON et angreb\n"
    .string "af samme type som den.\p"
    .string "Det boester tilsyneladende angrebets\n"
    .string "styrke.$"

Route14_Text_MarlonIntro::
    .string "Har du laert dine fugle-POKeMON\n"
    .string "at FLY?\p"
    .string "Du kan sveve med den op i\n"
    .string "himlen!$"

Route14_Text_MarlonDefeat::
    .string "Skudt ned i flammer!$"

Route14_Text_MarlonPostBattle::
    .string "Fugle-POKeMON er min eneste sande\n"
    .string "kaerlighed. Jeg vil ikke opdrage andet.$"

Route14_Text_DonaldIntro::
    .string "Har du hort legenden om de\n"
    .string "vingede luftspejlinger?$"

Route14_Text_DonaldDefeat::
    .string "Hvorfor?\n"
    .string "Hvorfor tabte jeg?$"

Route14_Text_DonaldPostBattle::
    .string "De vingede luftspejlinger er de\n"
    .string "legendariske fugle-POKeMON.\p"
    .string "Der er tre af dem: ARTICUNO,\n"
    .string "ZAPDOS og MOLTRES.$"

Route14_Text_BennyIntro::
    .string "Jeg er ikke til det, men okay.\n"
    .string "Lad os gaa!$"

Route14_Text_BennyDefeat::
    .string "Jeg vidste det!$"

Route14_Text_BennyPostBattle::
    .string "At vinde, tabe... Det er uvaesentligt\n"
    .string "under denne store himmel.$"

Route14_Text_LukasIntro::
    .string "Kom nu, kom nu.\n"
    .string "Lad os gaa, lad os gaa!$"

Route14_Text_LukasDefeat::
    .string "Arrg!\n"
    .string "Tabt! Forsvind!$"

Route14_Text_LukasPostBattle::
    .string "Hvad, hvad, hvad?\n"
    .string "Hvad vil du stadig?$"

Route14_Text_IsaacIntro::
    .string "Jeg skal bruge tiden.\n"
    .string "Hold kaeft og kaemp.$"

Route14_Text_IsaacDefeat::
    .string "Hvad?\n"
    .string "Dig!?$"

Route14_Text_IsaacPostBattle::
    .string "At opdrage POKeMON er kedeligt.$"

Route14_Text_GeraldIntro::
    .string "Vi koerer herude pga. det\n"
    .string "vide aabne land.$"

Route14_Text_GeraldDefeat::
    .string "Wipeout!$"

Route14_Text_GeraldPostBattle::
    .string "Det er sejt at du har gjort dine\n"
    .string "POKeMON saa staerke.\p"
    .string "Styrke er ret! Og det ved du!$"

Route14_Text_MalikIntro::
    .string "POKeMON kamp?\n"
    .string "Sejt! Slagsmaal!$"

Route14_Text_MalikDefeat::
    .string "Blaest vaek!$"

Route14_Text_MalikPostBattle::
    .string "Du ved hvem der vinder, dig og mig\n"
    .string "en mod en!$"

Route14_Text_RouteSign::
    .string "ROUTE 14\n"
    .string "Vest til FUCHSIA CITY$"

Route14_Text_KiriIntro::
    .string "KIRI: JAN, lad os virkelig\n"
    .string "goere os umage sammen.$"

Route14_Text_KiriDefeat::
    .string "KIRI: Hulk...\n"
    .string "Vi tabte, goer vi ikke?$"

Route14_Text_KiriPostBattle::
    .string "KIRI: Tabte vi pga. mig?$"

Route14_Text_KiriNotEnoughMons::
    .string "KIRI: Vi kan kaempe hvis du har\n"
    .string "to POKeMON.$"

Route14_Text_JanIntro::
    .string "JAN: KIRI, saa er vi i gang!\n"
    .string "Vi skal goere os umage!$"

Route14_Text_JanDefeat::
    .string "JAN: Eeeh!\n"
    .string "Unfair!$"

Route14_Text_JanPostBattle::
    .string "JAN: KIRI, graed ikke!\n"
    .string "Vi proever bare haardere naeste gang.$"

Route14_Text_JanNotEnoughMons::
    .string "JAN: Vil du kaempe?\n"
    .string "Du har ikke nok POKeMON.$"
