Route14_Text_CarterIntro::
    .string "Du skal bruge TMs til at läre\n"
    .string "gode angreb til POKéMON.$"

Route14_Text_CarterDefeat::
    .string "Ikke helt god nok endnu.$"

Route14_Text_CarterPostBattle::
    .string "Du har nogle HMs, ikke? POKéMON\n"
    .string "kan ikke glemme de angreb nemt.$"

Route14_Text_MitchIntro::
    .string "Mine fugle-POKéMON burde väre\n"
    .string "klar til kamp.$"

Route14_Text_MitchDefeat::
    .string "Ikke klar endnu!$"

Route14_Text_MitchPostBattle::
    .string "Mine fugle-POKéMON skal läre\n"
    .string "bedre angreb.$"

Route14_Text_BeckIntro::
    .string "De har TMs til salg i\n"
    .string "CELADON DEPT. STORE.\p"
    .string "TMs er ikke rigtig själdne, men ikke\n"
    .string "mange har HMs.$"

Route14_Text_BeckDefeat::
    .string "Av, ärgerligt!$"

Route14_Text_BeckPostBattle::
    .string "Pröv at läre POKéMON et angreb\n"
    .string "af samme type som den.\p"
    .string "Det böster tilsyneladende angrebets\n"
    .string "styrke.$"

Route14_Text_MarlonIntro::
    .string "Har du lärt dine fugle-POKéMON\n"
    .string "at FLY?\p"
    .string "Du kan sveve med den op i\n"
    .string "himlen!$"

Route14_Text_MarlonDefeat::
    .string "Skudt ned i flammer!$"

Route14_Text_MarlonPostBattle::
    .string "Fugle-POKéMON er min eneste sande\n"
    .string "kärlighed. Jeg vil ikke opdrage andet.$"

Route14_Text_DonaldIntro::
    .string "Har du hort legenden om de\n"
    .string "vingede luftspejlinger?$"

Route14_Text_DonaldDefeat::
    .string "Hvorfor?\n"
    .string "Hvorfor tabte jeg?$"

Route14_Text_DonaldPostBattle::
    .string "De vingede luftspejlinger er de\n"
    .string "legendariske fugle-POKéMON.\p"
    .string "Der er tre af dem: ARTICUNO,\n"
    .string "ZAPDOS og MOLTRES.$"

Route14_Text_BennyIntro::
    .string "Jeg er ikke til det, men okay.\n"
    .string "Lad os gâ!$"

Route14_Text_BennyDefeat::
    .string "Jeg vidste det!$"

Route14_Text_BennyPostBattle::
    .string "At vinde, tabe... Det er uväsentligt\n"
    .string "under denne store himmel.$"

Route14_Text_LukasIntro::
    .string "Kom nu, kom nu.\n"
    .string "Lad os gâ, lad os gâ!$"

Route14_Text_LukasDefeat::
    .string "Arrg!\n"
    .string "Tabt! Forsvind!$"

Route14_Text_LukasPostBattle::
    .string "Hvad, hvad, hvad?\n"
    .string "Hvad vil du stadig?$"

Route14_Text_IsaacIntro::
    .string "Jeg skal bruge tiden.\n"
    .string "Hold käft og kämp.$"

Route14_Text_IsaacDefeat::
    .string "Hvad?\n"
    .string "Dig!?$"

Route14_Text_IsaacPostBattle::
    .string "At opdrage POKéMON er kedeligt.$"

Route14_Text_GeraldIntro::
    .string "Vi körer herude pga. det\n"
    .string "vide âbne land.$"

Route14_Text_GeraldDefeat::
    .string "Wipeout!$"

Route14_Text_GeraldPostBattle::
    .string "Det er sejt at du har gjort dine\n"
    .string "POKéMON sâ stärke.\p"
    .string "Styrke er ret! Og det ved du!$"

Route14_Text_MalikIntro::
    .string "POKéMON kamp?\n"
    .string "Sejt! Slagsmâl!$"

Route14_Text_MalikDefeat::
    .string "Bläst väk!$"

Route14_Text_MalikPostBattle::
    .string "Du ved hvem der vinder, dig og mig\n"
    .string "en mod en!$"

Route14_Text_RouteSign::
    .string "ROUTE 14\n"
    .string "Vest til FUCHSIA CITY$"

Route14_Text_KiriIntro::
    .string "KIRI: JAN, lad os virkelig\n"
    .string "göre os umage sammen.$"

Route14_Text_KiriDefeat::
    .string "KIRI: Hulk...\n"
    .string "Vi tabte, gör vi ikke?$"

Route14_Text_KiriPostBattle::
    .string "KIRI: Tabte vi pga. mig?$"

Route14_Text_KiriNotEnoughMons::
    .string "KIRI: Vi kan kämpe hvis du har\n"
    .string "to POKéMON.$"

Route14_Text_JanIntro::
    .string "JAN: KIRI, sâ er vi i gang!\n"
    .string "Vi skal göre os umage!$"

Route14_Text_JanDefeat::
    .string "JAN: Eeeh!\n"
    .string "Unfair!$"

Route14_Text_JanPostBattle::
    .string "JAN: KIRI, gräd ikke!\n"
    .string "Vi pröver bare hârdere näste gang.$"

Route14_Text_JanNotEnoughMons::
    .string "JAN: Vil du kämpe?\n"
    .string "Du har ikke nok POKéMON.$"
