ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Puha! Jeg proever at memorere alle mine\n"
    .string "noter.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Okay!\p"
    .string "Soerg for at laese hvad der staar paa\n"
    .string "tavlen omhyggeligt!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Lad os tjekke notesbogen.\p"
    .string "Foerste side…\p"
    .string "POKe BALLS bruges til at fange\n"
    .string "POKeMON.\p"
    .string "Op til seks POKeMON kan baeres\n"
    .string "i din gruppe.\p"
    .string "Folk der opfostrer og kaemper\n"
    .string "med POKeMON kaldes TRAeNERE.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Anden side…\p"
    .string "En sund POKeMON kan vaere svaer at\n"
    .string "fange, saa svaekk den foerst.\p"
    .string "Forgift, braend eller foraarsag et andet\n"
    .string "tilstandsproblem for at svaekke den.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Tredje side…\p"
    .string "POKeMON TRAeNERE soeger andre til at\n"
    .string "indgaa i POKeMON kampe.\p"
    .string "For TRAeNERE er smagen af sejr\n"
    .string "soed, sandelig.\p"
    .string "Kampe udkaempes konstant paa\n"
    .string "POKeMON GYMS overalt.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fjerde side…\p"
    .string "Det ultimative maal for alle POKeMON\n"
    .string "TRAeNERE er enkelt.\p"
    .string "Det er at besejre de top otte\n"
    .string "POKeMON GYM LEDERE.\p"
    .string "Goer det for at fortjene retten til at moede…\p"
    .string "ELITE FOUR af POKeMON\n"
    .string "LEAGUE!$"

ViridianCity_School_Text_TurnThePage::
    .string "Vende siden?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "PIGE: Hej!\n"
    .string "Kig ikke paa mine noter!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "Tavlen viser POKeMON\n"
    .string "TILSTANDS problemer under kampe.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Hvilket emne vil du laese?$"

ViridianCity_School_Text_ExplainSleep::
    .string "En POKeMON kan ikke angribe hvis den\n"
    .string "sover.\p"
    .string "POKeMON forbliver sovende selv\n"
    .string "efter kampe.\p"
    .string "Brug AWAKENING for at vaekke en\n"
    .string "fra soevn.$"

ViridianCity_School_Text_ExplainBurn::
    .string "En forbraendning reducerer ANGREBS styrke.\n"
    .string "Den foraarsager ogsaa loebende HP-tab.\p"
    .string "En forbraendning forbliver efter en kamp.\n"
    .string "Brug BURN HEAL for at helbrede en forbraendning.$"

ViridianCity_School_Text_ExplainPoison::
    .string "Naar den er forgiftet, falder en POKeMONs\n"
    .string "sundhed jaevnt.\p"
    .string "Gift vedvarer efter kampe.\n"
    .string "Brug et ANTIDOTE for at helbrede gift!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "En frossen POKeMON bliver\n"
    .string "hjaelpeloest ubevaegelig.\p"
    .string "Den forbliver frossen selv efter\n"
    .string "kampen slutter.\p"
    .string "Brug ICE HEAL for at toe op den\n"
    .string "lidende POKeMON.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Lammelse reducerer HASTIGHED og kan\n"
    .string "forhindre POKeMON i at bevaege sig.\p"
    .string "Lammelse forbliver efter kampe.\n"
    .string "Brug PARLYZ HEAL til behandling.$"

