ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Puha! Jeg pröver at memorere alle mine\n"
    .string "noter.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Okay!\p"
    .string "Sörg for at läse hvad der stâr pâ\n"
    .string "tavlen omhyggeligt!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Lad os tjekke notesbogen.\p"
    .string "Förste side…\p"
    .string "POKe BALLS bruges til at fange\n"
    .string "POKéMON.\p"
    .string "Op til seks POKéMON kan bäres\n"
    .string "i din gruppe.\p"
    .string "Folk der opfostrer og kämper\n"
    .string "med POKéMON kaldes TRÆNERE.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Anden side…\p"
    .string "En sund POKéMON kan väre svär at\n"
    .string "fange, sâ sväkk den först.\p"
    .string "Forgift, bränd eller forârsag et andet\n"
    .string "tilstandsproblem for at sväkke den.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Tredje side…\p"
    .string "POKéMON TRÆNERE söger andre til at\n"
    .string "indgâ i POKéMON kampe.\p"
    .string "For TRÆNERE er smagen af sejr\n"
    .string "söd, sandelig.\p"
    .string "Kampe udkämpes konstant pâ\n"
    .string "POKéMON GYMS overalt.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fjerde side…\p"
    .string "Det ultimative mâl for alle POKéMON\n"
    .string "TRÆNERE er enkelt.\p"
    .string "Det er at besejre de top otte\n"
    .string "POKéMON GYM LEDERE.\p"
    .string "Gör det for at fortjene retten til at möde…\p"
    .string "ELITE FOUR af POKéMON\n"
    .string "LEAGUE!$"

ViridianCity_School_Text_TurnThePage::
    .string "Vende siden?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "PIGE: Hej!\n"
    .string "Kig ikke pâ mine noter!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "Tavlen viser POKéMON\n"
    .string "TILSTANDS problemer under kampe.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Hvilket emne vil du läse?$"

ViridianCity_School_Text_ExplainSleep::
    .string "En POKéMON kan ikke angribe hvis den\n"
    .string "sover.\p"
    .string "POKéMON forbliver sovende selv\n"
    .string "efter kampe.\p"
    .string "Brug AWAKENING for at väkke en\n"
    .string "fra sövn.$"

ViridianCity_School_Text_ExplainBurn::
    .string "En forbrändning reducerer ANGREBS styrke.\n"
    .string "Den forârsager ogsâ löbende HP-tab.\p"
    .string "En forbrändning forbliver efter en kamp.\n"
    .string "Brug BURN HEAL for at helbrede en forbrändning.$"

ViridianCity_School_Text_ExplainPoison::
    .string "Nâr den er forgiftet, falder en POKéMONs\n"
    .string "sundhed jävnt.\p"
    .string "Gift vedvarer efter kampe.\n"
    .string "Brug et ANTIDOTE for at helbrede gift!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "En frossen POKéMON bliver\n"
    .string "hjälpelöst ubevägelig.\p"
    .string "Den forbliver frossen selv efter\n"
    .string "kampen slutter.\p"
    .string "Brug ICE HEAL for at tö op den\n"
    .string "lidende POKéMON.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Lammelse reducerer HASTIGHED og kan\n"
    .string "forhindre POKéMON i at beväge sig.\p"
    .string "Lammelse forbliver efter kampe.\n"
    .string "Brug PARLYZ HEAL til behandling.$"

