ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Puha! Jeg prøver at memorere alle mine\n"
    .string "noter.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Okay!\p"
    .string "Sørg for at læse hvad der stâr pâ\n"
    .string "tavlen omhyggeligt!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Lad os tjekke notesbogen.\p"
    .string "Første side…\p"
    .string "POKe BALLS bruges til at fange\n"
    .string "POKéMON.\p"
    .string "Op til seks POKéMON kan bæres\n"
    .string "i din gruppe.\p"
    .string "Folk der opfostrer og kæmper\n"
    .string "med POKéMON kaldes TRÆNERE.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Anden side…\p"
    .string "En sund POKéMON kan være svær at\n"
    .string "fange, sâ svækk den først.\p"
    .string "Forgift, brænd eller forârsag et andet\n"
    .string "tilstandsproblem for at svække den.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Tredje side…\p"
    .string "POKéMON TRÆNERE søger andre til at\n"
    .string "indgâ i POKéMON kampe.\p"
    .string "For TRÆNERE er smagen af sejr\n"
    .string "sød, sandelig.\p"
    .string "Kampe udkæmpes konstant pâ\n"
    .string "POKéMON GYMS overalt.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fjerde side…\p"
    .string "Det ultimative mâl for alle POKéMON\n"
    .string "TRÆNERE er enkelt.\p"
    .string "Det er at besejre de top otte\n"
    .string "POKéMON GYM LEDERE.\p"
    .string "Gør det for at fortjene retten til at møde…\p"
    .string "ELITE FOUR af POKéMON\n"
    .string "LEAGUE!$"

ViridianCity_School_Text_TurnThePage::
    .string "Vende siden?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "PIGE: Hej!\n"
    .string "Kig ikke pâ mine noter!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "Tavlen viser POKéMON\n"
    .string "TILSTANDS problemer under kampe.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Hvilket emne vil du læse?$"

ViridianCity_School_Text_ExplainSleep::
    .string "En POKéMON kan ikke angribe hvis den\n"
    .string "sover.\p"
    .string "POKéMON forbliver sovende selv\n"
    .string "efter kampe.\p"
    .string "Brug AWAKENING for at vække en\n"
    .string "fra søvn.$"

ViridianCity_School_Text_ExplainBurn::
    .string "En forbrændning reducerer ANGREBS styrke.\n"
    .string "Den forârsager ogsâ løbende HP-tab.\p"
    .string "En forbrændning forbliver efter en kamp.\n"
    .string "Brug BURN HEAL for at helbrede en forbrændning.$"

ViridianCity_School_Text_ExplainPoison::
    .string "Nâr den er forgiftet, falder en POKéMONs\n"
    .string "sundhed jævnt.\p"
    .string "Gift vedvarer efter kampe.\n"
    .string "Brug et ANTIDOTE for at helbrede gift!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "En frossen POKéMON bliver\n"
    .string "hjælpeløst ubevægelig.\p"
    .string "Den forbliver frossen selv efter\n"
    .string "kampen slutter.\p"
    .string "Brug ICE HEAL for at tø op den\n"
    .string "lidende POKéMON.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Lammelse reducerer HASTIGHED og kan\n"
    .string "forhindre POKéMON i at bevæge sig.\p"
    .string "Lammelse forbliver efter kampe.\n"
    .string "Brug PARLYZ HEAL til behandling.$"

