SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "Dette skib er en luksusliner for\n"
    .string "TRAINERS fra hele verden!\p"
    .string "Ved hver havn holder vi fester med\n"
    .string "inviterede TRAINERS.$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{RIVAL}: Bonjour!\n"
    .string "{PLAYER}!\p"
    .string "Tänk at möde dig her!\n"
    .string "{PLAYER}, var du virkelig inviteret?\p"
    .string "Hvordan kommer din POKéDEX?\p"
    .string "Jeg har allerede fanget 40 slags, makker.\n"
    .string "Forskellige slags er overalt.\p"
    .string "Krav rundt i gräsomrâder og\n"
    .string "kig grundigt efter dem.$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "Humph!\p"
    .string "I det mindste opdrager du dine\n"
    .string "POKéMON!$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "{RIVAL}: Jeg hörte at der var en CUT-\n"
    .string "mester om bord.\p"
    .string "Men han var bare en sösyg gammel mand!\p"
    .string "CUT selv er virkelig nyttig.\n"
    .string "Ja, den vil väre handy.\p"
    .string "Du bör ogsâ gâ og se ham.\n"
    .string "Vi ses!$"

