Route10_Text_MarkIntro::
    .string "Wow, du kom hele vejen her?\n"
    .string "Maaske er du ogsaa POKeMANIAC?\l"
    .string "Vil du se min samling?$"

Route10_Text_MarkDefeat::
    .string "Humph.\n"
    .string "Jeg er ikke vred!$"

Route10_Text_MarkPostBattle::
    .string "Jeg har flere sjaeldne POKeMON derhjemme!$"

Route10_Text_ClarkIntro::
    .string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
    .string "Ha-haha!\n"
    .string "Griner ikke!\l"
    .string "Ha-hay feber! Haha-ha-tjo!$"

Route10_Text_ClarkPostBattle::
    .string "Haha-ha-tjo!\n"
    .string "Ha-tjo!\l"
    .string "Snue! Snoevlen!$"

Route10_Text_HermanIntro::
    .string "Hej, unge!\n"
    .string "Vil du se mine POKeMON?$"

Route10_Text_HermanDefeat::
    .string "Oh, nej!\n"
    .string "Mine POKeMON!$"

Route10_Text_HermanPostBattle::
    .string "Jeg kan ikke lide dig.\n"
    .string "Jeg kan ikke lide nogen bedre end mig!$"

Route10_Text_HeidiIntro::
    .string "Jeg har vaeret ved et POKeMON GYM\n"
    .string "et par gange.\p"
    .string "…Men jeg taber altid.$"

Route10_Text_HeidiDefeat::
    .string "Ohh!\n"
    .string "Efter al min traening!$"

Route10_Text_HeidiPostBattle::
    .string "Jeg lagde maerke til nogle POKeMANIACs\n"
    .string "der strejfede omkring.\p"
    .string "Kan du forestille dig? Dem?\n"
    .string "Her oppe i bjergene?$"

Route10_Text_TrentIntro::
    .string "Ah!\n"
    .string "Denne bjergluft er delikat!$"

Route10_Text_TrentDefeat::
    .string "Det ryddede hovedet!$"

Route10_Text_TrentPostBattle::
    .string "Jeg foeler mig oppustet af bjergluft!$"

Route10_Text_CarolIntro::
    .string "Jeg foeler mig lidt svag.\n"
    .string "Jeg har ikke vandret i lang tid.$"

Route10_Text_CarolDefeat::
    .string "Jeg er for traet.\n"
    .string "Jeg var ikke klar til det.$"

Route10_Text_CarolPostBattle::
    .string "POKeMON her i bjergene er saa\n"
    .string "tunge…\p"
    .string "Jeg ville oenske der var lyseroede\n"
    .string "POKeMON med blomstermoenster!$"

Route10_Text_RockTunnelDetourToLavender::
    .string "ROCK TUNNEL\n"
    .string "Omvej til LAVENDER TOWN$"

Route10_Text_RockTunnel::
    .string "ROCK TUNNEL$"

Route10_Text_PowerPlant::
    .string "POWER PLANT$"
