LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "Jeg flyttede nylig til denne by.\p"
    .string "Jeg hoerer at MR. FUJI heller ikke\n"
    .string "er herfra oprindeligt.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "Maerkeligt, MR. FUJI er ikke her.\n"
    .string "Hvor blev han af?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "MR. FUJI havde bedt alene for\n"
    .string "CUBONEs mor.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "Dette er faktisk MR. FUJIs hus.\p"
    .string "Han er virkelig venlig.\p"
    .string "Han passer forladte og foraeldreloese\n"
    .string "POKeMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "Det er saa varmt!\n"
    .string "POKeMON er saa rare at kramme.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Din POKeDEX-rejse kraever staerk\n"
    .string "engagement.\p"
    .string "Uden dyb kaerlighed til POKeMON kan\n"
    .string "din rejse mislykkes.\p"
    .string "Jeg ved ikke om det hjaelper, men\n"
    .string "jeg vil gerne give dig dette.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} modtog en POKe FLUTE\n"
    .string "fra MR. FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "Naar man hoerer POKe FLUTE, vaagner\n"
    .string "sovende POKeMON med det samme.\p"
    .string "Proev at bruge den paa POKeMON der\n"
    .string "er sovende hindringer.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "Du skal goere plads til dette!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "MR. FUJI: Har min POKe FLUTE\n"
    .string "hjulpet dig?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "POKeMON FAN MAGAZINE\n"
    .string "Maanedlig hovedpraemie-lodtraekning!\p"
    .string "Ansoegningsskemaet er…\p"
    .string "Vaek! Det er klippet ud.\n"
    .string "Nogen maa allerede have ansoegt.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "POKeMON-magasiner staar paa hylden.\p"
    .string "POKeMON INSIDER…\p"
    .string "POKeMON FAN…$"

