RockTunnel_1F_Text_LennyIntro::
    .string "Denne tunnel gâr langt, unge!$"

RockTunnel_1F_Text_LennyDefeat::
    .string "Doh!\n"
    .string "Du vinder!$"

RockTunnel_1F_Text_LennyPostBattle::
    .string "Pas pâ ONIX.\n"
    .string "De dukker kun lejlighedsvis op.\p"
    .string "Højt-niveau kan klemme dig!$"

RockTunnel_1F_Text_OliverIntro::
    .string "Hmm.\n"
    .string "Mâske er jeg faret vild her…$"

RockTunnel_1F_Text_OliverDefeat::
    .string "Slap af!\n"
    .string "Hvad laver jeg?\l"
    .string "Hvilken vej er ud?$"

RockTunnel_1F_Text_OliverPostBattle::
    .string "Den sovende POKéMON pâ ROUTE 12\n"
    .string "tvang mig til at tage denne omvej.$"

RockTunnel_1F_Text_LucasIntro::
    .string "Udenforstâende som dig skal vise mig\n"
    .string "respekt!$"

RockTunnel_1F_Text_LucasDefeat::
    .string "Jeg giver op!$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "Du er talentfuld nok til at vandre!$"

RockTunnel_1F_Text_AshtonIntro::
    .string "POKéMON kæmper!\n"
    .string "Klar, start!$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "Game over!$"

RockTunnel_1F_Text_AshtonPostBattle::
    .string "Nâ ja, jeg fâr en ZUBAT pâ vejen!$"

RockTunnel_1F_Text_LeahIntro::
    .string "Eek!\p"
    .string "Prøv ikke noget morsomt i\n"
    .string "mørket!$"

RockTunnel_1F_Text_LeahDefeat::
    .string "Det var for mørkt…$"

RockTunnel_1F_Text_LeahPostBattle::
    .string "Jeg sâ en MACHOP i denne tunnel.$"

RockTunnel_1F_Text_DanaIntro::
    .string "Jeg kom sâ langt for at lede efter vilde\n"
    .string "POKéMON.$"

RockTunnel_1F_Text_DanaDefeat::
    .string "Jeg har ikke flere POKéMON!$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "Du sâ sød og harmløs ud.\n"
    .string "Hvor tog jeg fejl!$"

RockTunnel_1F_Text_ArianaIntro::
    .string "Du har POKéMON!\n"
    .string "Lad os starte!$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "Du spiller hârdt!$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "Puha!\n"
    .string "Jeg er helt svedig nu.$"

RockTunnel_1F_Text_RouteSign::
    .string "ROCK TUNNEL\n"
    .string "CERULEAN CITY - LAVENDER TOWN$"
