CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "Hej!\p"
    .string "Beklager, men vi holder pause\n"
    .string "lige nu.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "Mine POKéMON er sväkke, sâ jeg mâ ofte\n"
    .string "til DRUGSTORE.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "Psst! Der er en kälder under\n"
    .string "GAME CORNER, har jeg hört.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Munch…\p"
    .string "Manden ved det bord tabte det hele\n"
    .string "ved spilleautomaterne.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "Gâr du bare! Grin!\n"
    .string "Jeg er helt flad!\p"
    .string "Ikke flere spilleautomater!\n"
    .string "Jeg bliver ordentlig!\p"
    .string "Her!\n"
    .string "Jeg har ikke brug for dette mere!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER} modtog en COIN CASE\n"
    .string "fra manden.$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "Lav plads til dette!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "Jeg tröde altid jeg skulle\n"
    .string "vinde det tilbage…$"
