TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Jeg er POKéMON TRÆK-MANIAC.\p"
    .string "Jeg kender hvert enkelt träk som\n"
    .string "POKéMON lärer under opväkst.\p"
    .string "Jeg er ogsâ svampe-maniac.\p"
    .string "Bring mig to TINYMUSHROOMS,\n"
    .string "eller én BIG MUSHROOM.\p"
    .string "Hvis du gör det for mig, lärer jeg\n"
    .string "et träk til én POKéMON.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Snus, snus…\n"
    .string "Hm! Du lugter af MUSHROOMS!\p"
    .string "Vil du have mig til at läre et träk\n"
    .string "til en af dine POKéMON?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Hvilken POKéMON har brug for undervisning?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Hvilket träk vil du have mig til at läre?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Undskyld…\p"
    .string "Det ser ikke ud til at jeg har et\n"
    .string "träk jeg kan läre den POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Sâ har jeg brug for en MUSHROOM eller to.\n"
    .string "Hvad vil du give mig?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} gav to\n"
    .string "TINYMUSHROOMS i bytte.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} gav én\n"
    .string "BIG MUSHROOM i bytte.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "Hvis dine POKéMON skal läre et\n"
    .string "träk, har jeg brug for en MUSHROOM eller to.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Hunh? Der er ikke et enkelt träk\n"
    .string "jeg kan läre et EGG.$"

