TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Jeg er POKeMON TRAeK-MANIAC.\p"
    .string "Jeg kender hvert enkelt traek som\n"
    .string "POKeMON laerer under opvaekst.\p"
    .string "Jeg er ogsaa svampe-maniac.\p"
    .string "Bring mig to TINYMUSHROOMS,\n"
    .string "eller én BIG MUSHROOM.\p"
    .string "Hvis du goer det for mig, laerer jeg\n"
    .string "et traek til én POKeMON.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Snus, snus…\n"
    .string "Hm! Du lugter af MUSHROOMS!\p"
    .string "Vil du have mig til at laere et traek\n"
    .string "til en af dine POKeMON?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Hvilken POKeMON har brug for undervisning?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Hvilket traek vil du have mig til at laere?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Undskyld…\p"
    .string "Det ser ikke ud til at jeg har et\n"
    .string "traek jeg kan laere den POKeMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Saa har jeg brug for en MUSHROOM eller to.\n"
    .string "Hvad vil du give mig?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} gav to\n"
    .string "TINYMUSHROOMS i bytte.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} gav én\n"
    .string "BIG MUSHROOM i bytte.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "Hvis dine POKeMON skal laere et\n"
    .string "traek, har jeg brug for en MUSHROOM eller to.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Hunh? Der er ikke et enkelt traek\n"
    .string "jeg kan laere et EGG.$"

