TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Jeg er POKéMON TRÆK-MANIAC.\p"
    .string "Jeg kender hvert enkelt træk som\n"
    .string "POKéMON lærer under opvækst.\p"
    .string "Jeg er ogsâ svampe-maniac.\p"
    .string "Bring mig to TINYMUSHROOMS,\n"
    .string "eller én BIG MUSHROOM.\p"
    .string "Hvis du gør det for mig, lærer jeg\n"
    .string "et træk til én POKéMON.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Snus, snus…\n"
    .string "Hm! Du lugter af MUSHROOMS!\p"
    .string "Vil du have mig til at lære et træk\n"
    .string "til en af dine POKéMON?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Hvilken POKéMON har brug for undervisning?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Hvilket træk vil du have mig til at lære?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Undskyld…\p"
    .string "Det ser ikke ud til at jeg har et\n"
    .string "træk jeg kan lære den POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Sâ har jeg brug for en MUSHROOM eller to.\n"
    .string "Hvad vil du give mig?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} gav to\n"
    .string "TINYMUSHROOMS i bytte.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} gav én\n"
    .string "BIG MUSHROOM i bytte.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "Hvis dine POKéMON skal lære et\n"
    .string "træk, har jeg brug for en MUSHROOM eller to.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Hunh? Der er ikke et enkelt træk\n"
    .string "jeg kan lære et EGG.$"

