SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire::
    .string "{PLAYER} fandt en SAPPHIRE!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou::
    .string "Fufu… Fufufufu…\n"
    .string "Jeg gättede rigtigt.\p"
    .string "Jeg havde ret i at skygge dig!$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword::
    .string "Jeg vidste at der var en SAPPHIRE\n"
    .string "her, sâ den tilhörer mig!\p"
    .string "Jeg sälger den til TEAM ROCKET for\n"
    .string "alvorlige penge.\p"
    .string "…B-blik ikke sâ vredt pâ mig!\p"
    .string "Hvis du vil have den tilbage, hvorfor\n"
    .string "henter du den ikke efter jeg har solgt?\p"
    .string "Jeg fortäller dig endda et af\n"
    .string "adgangskoderne til TEAM ROCKETs\l"
    .string "WAREHOUSE.\p"
    .string "WAREHOUSE-adgangskoden jeg kender er\n"
    .string "Yes, nah, CHANSEY.\p"
    .string "Jeg er färdig.\n"
    .string "Tänk ikke dârligt om mig!$"

