FiveIsland_MemorialPillar_Text_MiloIntro::
    .string "Jeg er den aeldste af FUGLE-\n"
    .string "BROEDRENE.\p"
    .string "Det bedste ved fugle…\n"
    .string "Det maa vaere naebbet.$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
    .string "Oeh, saa skarp!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
    .string "Du kan flyve til FOUR ISLAND\n"
    .string "herfra.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
    .string "Jeg er mellemste barn af FUGLE-\n"
    .string "BROEDRENE.\p"
    .string "Det bedste ved fugle…\n"
    .string "Det maa vaere vingerne.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
    .string "Flap, flap!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
    .string "Der var en virkelig dyster fyr\n"
    .string "den vej.$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
    .string "Jeg er den yngste af FUGLE-\n"
    .string "BROEDRENE.\p"
    .string "Det bedste ved fugle…\n"
    .string "Det maa vaere dunet.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
    .string "Dun er saa behageligt…\n"
    .string "Det goer mig doesig…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
    .string "Det fylder mig med glaede naar\n"
    .string "fugle-POKeMON tigger legende…$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
    .string "Gnub, gnub…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
    .string "Hej…\n"
    .string "Dine POKeMON ser sunde ud…$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
    .string "Her er hvor jeg begravede min ONIX…\n"
    .string "Den hed TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
    .string "Her hviler TECTONIX er indgraveret\n"
    .string "paa en kampesten.\p"
    .string "Der er en LEMONADE anbragt som\n"
    .string "offer foran graven.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
    .string "Vil du laegge endnu en LEMONADE\n"
    .string "som offer?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
    .string "{PLAYER} anbragte en daase LEMONADE\n"
    .string "foran graven.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
    .string "T-tak…\p"
    .string "Det var min TECTONIXs yndlings-\n"
    .string "drik…\p"
    .string "Jeg kender dig ikke engang, men din\n"
    .string "venlighed…\p"
    .string "Har loeftet mig lidt.\p"
    .string "Vaersgo tag dette som tak?$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
    .string "Vaer venlig ved dine POKeMON\n"
    .string "ogsaa.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
    .string "Hvis du ikke har plads til det,\n"
    .string "gemmer jeg det til naeste gang.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
    .string "Oeh, det er dig fra dengang…\p"
    .string "Jeg har stadig den ting jeg ville\n"
    .string "give dig som tak.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
    .string "Gnub, gnub…\p"
    .string "… … …\n"
    .string "TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
    .string "Kampesten og sten er paent stablet\n"
    .string "som en varde.\p"
    .string "Her hviler TECTONIX er indgraveret\n"
    .string "paa en kampesten.$"

