FiveIsland_MemorialPillar_Text_MiloIntro::
    .string "Jeg er den ældste af FUGLE-\n"
    .string "BRØDRENE.\p"
    .string "Det bedste ved fugle…\n"
    .string "Det mâ være næbbet.$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
    .string "Øh, sâ skarp!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
    .string "Du kan flyve til FOUR ISLAND\n"
    .string "herfra.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
    .string "Jeg er mellemste barn af FUGLE-\n"
    .string "BRØDRENE.\p"
    .string "Det bedste ved fugle…\n"
    .string "Det mâ være vingerne.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
    .string "Flap, flap!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
    .string "Der var en virkelig dyster fyr\n"
    .string "den vej.$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
    .string "Jeg er den yngste af FUGLE-\n"
    .string "BRØDRENE.\p"
    .string "Det bedste ved fugle…\n"
    .string "Det mâ være dunet.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
    .string "Dun er sâ behageligt…\n"
    .string "Det gør mig døsig…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
    .string "Det fylder mig med glæde nâr\n"
    .string "fugle-POKéMON tigger legende…$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
    .string "Gnub, gnub…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
    .string "Hej…\n"
    .string "Dine POKéMON ser sunde ud…$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
    .string "Her er hvor jeg begravede min ONIX…\n"
    .string "Den hed TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
    .string "Her hviler TECTONIX er indgraveret\n"
    .string "pâ en kampesten.\p"
    .string "Der er en LEMONADE anbragt som\n"
    .string "offer foran graven.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
    .string "Vil du lægge endnu en LEMONADE\n"
    .string "som offer?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
    .string "{PLAYER} anbragte en dâse LEMONADE\n"
    .string "foran graven.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
    .string "T-tak…\p"
    .string "Det var min TECTONIXs yndlings-\n"
    .string "drik…\p"
    .string "Jeg kender dig ikke engang, men din\n"
    .string "venlighed…\p"
    .string "Har løftet mig lidt.\p"
    .string "Værsgo tag dette som tak?$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
    .string "Vær venlig ved dine POKéMON\n"
    .string "ogsâ.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
    .string "Hvis du ikke har plads til det,\n"
    .string "gemmer jeg det til næste gang.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
    .string "Øh, det er dig fra dengang…\p"
    .string "Jeg har stadig den ting jeg ville\n"
    .string "give dig som tak.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
    .string "Gnub, gnub…\p"
    .string "… … …\n"
    .string "TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
    .string "Kampesten og sten er pænt stablet\n"
    .string "som en varde.\p"
    .string "Her hviler TECTONIX er indgraveret\n"
    .string "pâ en kampesten.$"

