Text_UltimateMoveThatMon::
    .string "Jeg perfektionerede det ultimative träk\n"
    .string "af sin type…\p"
    .string "Men vil ingen tage det til\n"
    .string "fremtidig brug?\p"
    .string "…Hm? Hmmm!\p"
    .string "D-dig…\n"
    .string "D-den {STR_VAR_1}…$"

Text_JustMistaken::
    .string "…Nej…\n"
    .string "Jeg tog fejl.$"

Text_AllowMeToTeachMonUltimateMove::
    .string "Aah! Det er den!\n"
    .string "Det er POKeMON!\p"
    .string "Denne {STR_VAR_1} er värdig til at\n"
    .string "läre mit ultimative träk!\p"
    .string "Tillader du det?\p"
    .string "Tillader du din {STR_VAR_1} at\n"
    .string "läre mit {STR_VAR_2}?$"

Text_YouRejectIt::
    .string "Gâh! Du afviser det?\n"
    .string "Nej, jeg lader mig ikke overtale!$"

Text_LetMeConferUltimateMove::
    .string "Du tillader det?\p"
    .string "Sâ lader jeg mig overbringe mit\n"
    .string "ultimative {STR_VAR_2} til din {STR_VAR_1}.\p"
    .string "Ggggrah-awooo!$"

Text_TaughtMove::
    .string "Gisp, gisp, gisp…\p"
    .string "Jeg tröde ikke jeg kunne läre det\n"
    .string "träk mens jeg stadig lever…$"

Text_MakeBestUseOfMove::
    .string "Jeg beder dig bruge det träk\n"
    .string "bedst muligt og vinde kraft!$"

Text_PassedOnEverythingIKnow::
    .string "Gisp, gisp, gisp…\p"
    .string "Jeg har ingen anger nu.\n"
    .string "Jeg har givet videre alt hvad jeg ved.\p"
    .string "Nu kan jeg leve mit liv vidende om\n"
    .string "at mit arbejde er gjort.$"

Text_FeelRejuvenated::
    .string "Efter jeg gav mine kundskaber videre til\n"
    .string "dig, fölte jeg sâ meget lettelse.\p"
    .string "Faktisk föler jeg mig forynget,\n"
    .string "som om jeg var yngre igen!$"
