Text_UltimateMoveThatMon::
    .string "Jeg perfektionerede det ultimative traek\n"
    .string "af sin type…\p"
    .string "Men vil ingen tage det til\n"
    .string "fremtidig brug?\p"
    .string "…Hm? Hmmm!\p"
    .string "D-dig…\n"
    .string "D-den {STR_VAR_1}…$"

Text_JustMistaken::
    .string "…Nej…\n"
    .string "Jeg tog fejl.$"

Text_AllowMeToTeachMonUltimateMove::
    .string "Aah! Det er den!\n"
    .string "Det er POKeMON!\p"
    .string "Denne {STR_VAR_1} er vaerdig til at\n"
    .string "laere mit ultimative traek!\p"
    .string "Tillader du det?\p"
    .string "Tillader du din {STR_VAR_1} at\n"
    .string "laere mit {STR_VAR_2}?$"

Text_YouRejectIt::
    .string "Gaah! Du afviser det?\n"
    .string "Nej, jeg lader mig ikke overtale!$"

Text_LetMeConferUltimateMove::
    .string "Du tillader det?\p"
    .string "Saa lader jeg mig overbringe mit\n"
    .string "ultimative {STR_VAR_2} til din {STR_VAR_1}.\p"
    .string "Ggggrah-awooo!$"

Text_TaughtMove::
    .string "Gisp, gisp, gisp…\p"
    .string "Jeg troede ikke jeg kunne laere det\n"
    .string "traek mens jeg stadig lever…$"

Text_MakeBestUseOfMove::
    .string "Jeg beder dig bruge det traek\n"
    .string "bedst muligt og vinde kraft!$"

Text_PassedOnEverythingIKnow::
    .string "Gisp, gisp, gisp…\p"
    .string "Jeg har ingen anger nu.\n"
    .string "Jeg har givet videre alt hvad jeg ved.\p"
    .string "Nu kan jeg leve mit liv vidende om\n"
    .string "at mit arbejde er gjort.$"

Text_FeelRejuvenated::
    .string "Efter jeg gav mine kundskaber videre til\n"
    .string "dig, foelte jeg saa meget lettelse.\p"
    .string "Faktisk foeler jeg mig forynget,\n"
    .string "som om jeg var yngre igen!$"
