Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hej!\n"
    .string "Jeg arbejder i en POKéMON BUTIK.\p"
    .string "Det er del af en kede, der sälger\n"
    .string "alle mulige ting.\p"
    .string "Besog os i VIRIDIAN CITY.\p"
    .string "Jeg giver dig en pröve.\n"
    .string "Värsgo!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Kom forbi, hvis du har brug for\n"
    .string "POKe BALLS til at fange POKéMON.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} lagde POTION i\n"
    .string "TASKENS TING-Lomme.$"

Route1_Text_CanJumpFromLedges::
    .string "Ser du kanten langs vejen?\p"
    .string "Det er lidt skrämmende, men du\n"
    .string "kan hoppe ned fra dem.\p"
    .string "Sâdan kommer du hurtigere tilbage\n"
    .string "til PALLET TOWN.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"
