Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hej!\n"
    .string "Jeg arbejder i en POKeMON BUTIK.\p"
    .string "Det er del af en kede, der saelger\n"
    .string "alle mulige ting.\p"
    .string "Besog os i VIRIDIAN CITY.\p"
    .string "Jeg giver dig en proeve.\n"
    .string "Vaersgo!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Kom forbi, hvis du har brug for\n"
    .string "POKe BALLS til at fange POKeMON.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} lagde POTION i\n"
    .string "TASKENS TING-Lomme.$"

Route1_Text_CanJumpFromLedges::
    .string "Ser du kanten langs vejen?\p"
    .string "Det er lidt skraemmende, men du\n"
    .string "kan hoppe ned fra dem.\p"
    .string "Saadan kommer du hurtigere tilbage\n"
    .string "til PALLET TOWN.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"
