PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "Kom, barn!\n"
    .string "Jeg har renset dette sted.\l"
    .string "Du kan hvile her.$"

PokemonTower_5F_Text_TammyIntro::
    .string "Giv…mig…\n"
    .string "dit…alt…$"

PokemonTower_5F_Text_TammyDefeat::
    .string "Gisp!$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "Jeg var under besaettelse.$"

PokemonTower_5F_Text_RuthIntro::
    .string "Du…skal…\n"
    .string "slutte…dig…til…os…$"

PokemonTower_5F_Text_RuthDefeat::
    .string "Hvilket mareridt!$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "Jeg var besat.$"

PokemonTower_5F_Text_KarinaIntro::
    .string "Zombier!$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "Ha?$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "Jeg genvandt mine sanser.$"

PokemonTower_5F_Text_JanaeIntro::
    .string "Urgah…\n"
    .string "Urff…$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "Whoo!$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "Jeg faldt for onde aander trods min\n"
    .string "traening i bjergene…$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "Traadte ind i den rensede og beskyttede\n"
    .string "zone.\p"
    .string "{PLAYER}s POKeMON blev fuldt\n"
    .string "helbredt.$"
