Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
    .string "Fodgængere er ikke tilladt på\n"
    .string "CYKELVEJ!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
    .string "CYKELVEJ er en nedadgående bane\n"
    .string "ved havet. Det er en fantastisk tur.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .string "Undskyld mig!\n"
    .string "Vent, tak!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
    .string "Hvordan kom du ind?\n"
    .string "God indsats!$"
