Route12_FishingHouse_Text_DoYouLikeToFish::
    .string "Jeg er FISHING GURUs yngre\n"
    .string "bror.\p"
    .string "Jeg elsker bare at fiske!\n"
    .string "Jeg kan ikke undvære det.\p"
    .string "Sig mig, kan du lide at fiske?$"

Route12_FishingHouse_Text_TakeThisAndFish::
    .string "Stort! Jeg kan lide din stil.\n"
    .string "Jeg tror vi kan være venner.\p"
    .string "Tag dette og fisk, unge ven!$"

Route12_FishingHouse_Text_ReceivedSuperRod::
    .string "{PLAYER} modtog en SUPER ROD fra\n"
    .string "FISHING GURUs bror.$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe::
    .string "Fiskeri er en livsstil!\n"
    .string "Det er som de fineste digte.\p"
    .string "Fra havet til floder, ga ud og\n"
    .string "fang den store en, min ven.\p"
    .string "Nu har jeg en anmodning.\p"
    .string "Hvis du fanger en stor MAGIKARP\n"
    .string "med den ROD, vil jeg gerne se den.\p"
    .string "Lige sâ meget som jeg elsker at\n"
    .string "fiske, elsker jeg at se kæmpe MAGIKARP.$"

Route12_FishingHouse_Text_OhThatsDisappointing::
    .string "Oh…\n"
    .string "Det er sâ skuffende…$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
    .string "Hej der, {PLAYER}!\n"
    .string "Har du fisket?\p"
    .string "Prøv at fiske med SUPER ROD i\n"
    .string "enhver vandmasse.\p"
    .string "Du finder forskellige POKéMON pâ\n"
    .string "forskellige steder.\p"
    .string "Oh, og glem ikke at bringe mig\n"
    .string "kæmpe MAGIKARP.$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
    .string "Oh? {PLAYER}?\n"
    .string "Hvis det ikke er en MAGIKARP!\p"
    .string "Lad mig se den, hurtigt!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
    .string "… … …Whoa!\n"
    .string "{STR_VAR_2} tommer!\p"
    .string "Du har en sjælden forstâelse for\n"
    .string "fiskeriets fine, pøtiske sider!\p"
    .string "Du mâ tage dette.\n"
    .string "Jeg insisterer!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
    .string "Jeg glæder mig til at se større\n"
    .string "rekorder fra dig!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
    .string "Hvad?\n"
    .string "{STR_VAR_2} tommer?\p"
    .string "Det er samme størrelse som den\n"
    .string "jeg sâ sidst.$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
    .string "Hmm…\n"
    .string "Denne er {STR_VAR_2} tommer lang.\p"
    .string "Den mâler ikke op til den\n"
    .string "{STR_VAR_3}-tommers du bragte sidst.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
    .string "Uh… Det ligner ikke rigtig\n"
    .string "en MAGIKARP.$"

Route12_FishingHouse_Text_NoRoomForGift::
    .string "Oh, nej!\p"
    .string "Jeg havde en gave til dig, men du\n"
    .string "har ikke plads til den.$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
    .string "Den mest gigantiske MAGIKARP\n"
    .string "jeg nogensinde har set…\p"
    .string "{STR_VAR_3} tommer!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort::
    .string "Det er et blankt diagram af en art.\p"
    .string "Det har plads til at skrive\n"
    .string "rekorder af en slags.$"
