CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "Der er intet jeg ikke ved,\n"
    .string "som jeg skrev paa tavlen.\p"
    .string "Jeg ved alt om POKeMON-verdenen\n"
    .string "i din GAME BOY ADVANCE!\p"
    .string "Find sammen med dine venner og\n"
    .string "nyd at bytte POKeMON!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} fik en EEVEE!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "POKeMON Forelaesning\p"
    .string "At spille med Wireless Adapter$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "Hvilket afsnit vil du laese?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "POKeMON WIRELESS CLUB er\n"
    .string "ovenpaa i ethvert POKeMON CENTER.\p"
    .string "Besoeg et for at linke med ven(ner)\n"
    .string "med din Wireless Adapter.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "For kun at linke med en ven, gaa til\n"
    .string "DIRECT CORNER.\p"
    .string "Det er disken til hoejre i\n"
    .string "POKeMON WIRELESS CLUB.\p"
    .string "Gaa ind i TRADE CORNER eller\n"
    .string "COLOSSEUM med din ven.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "For at linke og kommunikere med\n"
    .string "alle, gaa til UNION ROOM.\p"
    .string "Det er disken til venstre i\n"
    .string "POKeMON WIRELESS CLUB.\p"
    .string "Gaa til UNION ROOM og nyd at\n"
    .string "moede andre TRAINERS.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "Det er en brochure om TMs.\p"
    .string "… …\p"
    .string "Der er halvtreds TMs i alt.\p"
    .string "Der er ogsaa syv HMs der\n"
    .string "kan bruges gentagne gange.\p"
    .string "SILPH CO.$"
