CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "Der er intet jeg ikke ved,\n"
    .string "som jeg skrev pâ tavlen.\p"
    .string "Jeg ved alt om POKéMON-verdenen\n"
    .string "i din GAME BOY ADVANCE!\p"
    .string "Find sammen med dine venner og\n"
    .string "nyd at bytte POKéMON!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} fik en EEVEE!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "POKéMON Foreläsning\p"
    .string "At spille med Wireless Adapter$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "Hvilket afsnit vil du läse?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "POKéMON WIRELESS CLUB er\n"
    .string "ovenpâ i ethvert POKéMON CENTER.\p"
    .string "Besög et for at linke med ven(ner)\n"
    .string "med din Wireless Adapter.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "For kun at linke med en ven, gâ til\n"
    .string "DIRECT CORNER.\p"
    .string "Det er disken til höjre i\n"
    .string "POKéMON WIRELESS CLUB.\p"
    .string "Gâ ind i TRADE CORNER eller\n"
    .string "COLOSSEUM med din ven.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "For at linke og kommunikere med\n"
    .string "alle, gâ til UNION ROOM.\p"
    .string "Det er disken til venstre i\n"
    .string "POKéMON WIRELESS CLUB.\p"
    .string "Gâ til UNION ROOM og nyd at\n"
    .string "möde andre TRAINERS.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "Det er en brochure om TMs.\p"
    .string "… …\p"
    .string "Der er halvtreds TMs i alt.\p"
    .string "Der er ogsâ syv HMs der\n"
    .string "kan bruges gentagne gange.\p"
    .string "SILPH CO.$"
