CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
    .string "Jeg kan virkelig lide den PORYGON!\n"
    .string "Men det er svärt at vinde ved spilleautomaterne!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
    .string "Gahaha! Jeg tjente godt i dag!\n"
    .string "Hvis bare hver dag var som denne…$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
    .string "En COIN CASE er nödvendig…$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
    .string "Vi indlöser dine COINS for prämier.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
    .string "Hvilken prämie vil du have?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
    .string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
    .string "Sa du vil have {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
    .string "Okay, en TM af {STR_VAR_2}\n"
    .string "er hvad du vil have?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
    .string "Beklager, du har brug for flere COINS\n"
    .string "end det.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
    .string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
    .string "あっ そう$"
