SixIsland_PatternBush_Text_BethanyIntro::
    .string "Jeg er nysgerrig, hvordan opdrager du\n"
    .string "dine POKeMON?$"

SixIsland_PatternBush_Text_BethanyDefeat::
    .string "Du opdrager dine POKeMON med en\n"
    .string "masse kärlighed!$"

SixIsland_PatternBush_Text_BethanyPostBattle::
    .string "Pâ samme mâde som din mor opdrog\n"
    .string "dig fuld af kärlighed, bör du opdrage\l"
    .string "dine POKeMON.$"

SixIsland_PatternBush_Text_AllisonIntro::
    .string "Jeg arbejder for at bevare den\n"
    .string "naturlige ökologi af POKeMON her.$"

SixIsland_PatternBush_Text_AllisonDefeat::
    .string "Aah, for en sâ ung er du\n"
    .string "enorm!$"

SixIsland_PatternBush_Text_AllisonPostBattle::
    .string "Jeg siger ikke at du ikke bör\n"
    .string "fange POKeMON.\p"
    .string "Jeg vil bare have folk til at opdrage\n"
    .string "deres POKeMON ansvarligt.$"

SixIsland_PatternBush_Text_GarretIntro::
    .string "Jeg fangede en BUG POKeMON der kun\n"
    .string "lever her omkring!$"

SixIsland_PatternBush_Text_GarretDefeat::
    .string "Heheh…\n"
    .string "Er min POKeMON ikke fantastisk?$"

SixIsland_PatternBush_Text_GarretPostBattle::
    .string "Der er en pige ved BUSH der\n"
    .string "mâler HERACROSS for TRAINERS.$"

SixIsland_PatternBush_Text_JonahIntro::
    .string "Du ved, det föles bare ikke rigtigt\n"
    .string "hvis jeg ikke bruger BUG POKeMON.$"

SixIsland_PatternBush_Text_JonahDefeat::
    .string "Det er okay, at tabe er ogsâ en\n"
    .string "sjov del af POKeMONs appel.$"

SixIsland_PatternBush_Text_JonahPostBattle::
    .string "For resten, appel er et underligt\n"
    .string "ord, hvis man tänker over det.\p"
    .string "Altsâ, er det som en appelsinskral?\n"
    .string "Eller som en ringende klokke?$"

SixIsland_PatternBush_Text_VanceIntro::
    .string "Ja, ja, ja!\n"
    .string "Se alle BUG POKeMON!$"

SixIsland_PatternBush_Text_VanceDefeat::
    .string "Jeg blev slâet mens jeg stadig var\n"
    .string "optaget af at fejre!$"

SixIsland_PatternBush_Text_VancePostBattle::
    .string "Jeg tager min lillebror med\n"
    .string "hernäst gang.$"

SixIsland_PatternBush_Text_NashIntro::
    .string "Se, se! Der er underlige\n"
    .string "mönstre pâ jorden.$"

SixIsland_PatternBush_Text_NashDefeat::
    .string "Super fantastisk!$"

SixIsland_PatternBush_Text_NashPostBattle::
    .string "De underlige mönstre pâ jorden…\p"
    .string "De ligner mönstrene pâ min\n"
    .string "bedstefars töj.$"

SixIsland_PatternBush_Text_CordellIntro::
    .string "Jeg ved du tror jeg bare er en eller\n"
    .string "anden fyr, gör du ikke?$"

SixIsland_PatternBush_Text_CordellDefeat::
    .string "Jeg ved du tror jeg er svag,\n"
    .string "gör du ikke?$"

SixIsland_PatternBush_Text_CordellPostBattle::
    .string "Ja, I bybör kommer rundt sâ\n"
    .string "flot med en sâ iöjnefaldende hat…\p"
    .string "Hvad med at give mig den?$"

SixIsland_PatternBush_Text_DaliaIntro::
    .string "Träk vejret dybt.\n"
    .string "Er luften ikke herlig?$"

SixIsland_PatternBush_Text_DaliaDefeat::
    .string "Hvis du vil, kan jeg läre dig at\n"
    .string "träkke vejret ordentligt.$"

SixIsland_PatternBush_Text_DaliaPostBattle::
    .string "Först, pust ud.\n"
    .string "Bläs alt ud.\p"
    .string "Nâr du ikke kan puste mere ud,\n"
    .string "indâand den rene luft!\p"
    .string "Er det ikke forfriskende?$"

SixIsland_PatternBush_Text_JoanaIntro::
    .string "Jeg elsker BUG POKeMON.\n"
    .string "Derfor er jeg her hele tiden.\p"
    .string "Er jeg den eneste pige sâdan?$"

SixIsland_PatternBush_Text_JoanaDefeat::
    .string "Jeg tabte, men jeg griner stadig.\n"
    .string "Er jeg den eneste pige sâdan?$"

SixIsland_PatternBush_Text_JoanaPostBattle::
    .string "Jeg bliver ved med at samle\n"
    .string "BUG POKeMON.\p"
    .string "Er jeg den eneste pige sâdan?$"

SixIsland_PatternBush_Text_RileyIntro::
    .string "Det her er et godt sted.\n"
    .string "Jeg sätter mit telt op her.$"

SixIsland_PatternBush_Text_RileyDefeat::
    .string "Blev kört over…$"

SixIsland_PatternBush_Text_RileyPostBattle::
    .string "Jeg vil observere nattehimlen\n"
    .string "her.$"

SixIsland_PatternBush_Text_MarcyIntro::
    .string "Aah, ad!\n"
    .string "Jeg tror et insekt stak mig!$"

SixIsland_PatternBush_Text_MarcyDefeat::
    .string "Det var ikke et insekt.\n"
    .string "Jeg skar mig pâ noget gräs.$"

SixIsland_PatternBush_Text_MarcyPostBattle::
    .string "Et lille skâr som det…\n"
    .string "Lidt spyt er nok til at kurere det!$"

SixIsland_PatternBush_Text_LaytonIntro::
    .string "Har du lagt märke til noget märkeligt\n"
    .string "ved disse egne?$"

SixIsland_PatternBush_Text_LaytonDefeat::
    .string "Har du set ordentligt rundt om\n"
    .string "dine födder?$"

SixIsland_PatternBush_Text_LaytonPostBattle::
    .string "Der er steder her i PATTERN\n"
    .string "BUSH hvor gräs ikke vil gro.\p"
    .string "Hvad kunne ârsagen väre til sâ\n"
    .string "et fänomen?$"

