SixIsland_PatternBush_Text_BethanyIntro::
    .string "Jeg er nysgerrig, hvordan opdrager du\n"
    .string "dine POKéMON?$"

SixIsland_PatternBush_Text_BethanyDefeat::
    .string "Du opdrager dine POKéMON med en\n"
    .string "masse kærlighed!$"

SixIsland_PatternBush_Text_BethanyPostBattle::
    .string "Pâ samme mâde som din mor opdrog\n"
    .string "dig fuld af kærlighed, bør du opdrage\l"
    .string "dine POKéMON.$"

SixIsland_PatternBush_Text_AllisonIntro::
    .string "Jeg arbejder for at bevare den\n"
    .string "naturlige økologi af POKéMON her.$"

SixIsland_PatternBush_Text_AllisonDefeat::
    .string "Aah, for en sâ ung er du\n"
    .string "enorm!$"

SixIsland_PatternBush_Text_AllisonPostBattle::
    .string "Jeg siger ikke at du ikke bør\n"
    .string "fange POKéMON.\p"
    .string "Jeg vil bare have folk til at opdrage\n"
    .string "deres POKéMON ansvarligt.$"

SixIsland_PatternBush_Text_GarretIntro::
    .string "Jeg fangede en BUG POKéMON der kun\n"
    .string "lever her omkring!$"

SixIsland_PatternBush_Text_GarretDefeat::
    .string "Heheh…\n"
    .string "Er min POKéMON ikke fantastisk?$"

SixIsland_PatternBush_Text_GarretPostBattle::
    .string "Der er en pige ved BUSH der\n"
    .string "mâler HERACROSS for TRAINERS.$"

SixIsland_PatternBush_Text_JonahIntro::
    .string "Du ved, det føles bare ikke rigtigt\n"
    .string "hvis jeg ikke bruger BUG POKéMON.$"

SixIsland_PatternBush_Text_JonahDefeat::
    .string "Det er okay, at tabe er ogsâ en\n"
    .string "sjov del af POKéMONs appel.$"

SixIsland_PatternBush_Text_JonahPostBattle::
    .string "For resten, appel er et underligt\n"
    .string "ord, hvis man tænker over det.\p"
    .string "Altsâ, er det som en appelsinskral?\n"
    .string "Eller som en ringende klokke?$"

SixIsland_PatternBush_Text_VanceIntro::
    .string "Ja, ja, ja!\n"
    .string "Se alle BUG POKéMON!$"

SixIsland_PatternBush_Text_VanceDefeat::
    .string "Jeg blev slâet mens jeg stadig var\n"
    .string "optaget af at fejre!$"

SixIsland_PatternBush_Text_VancePostBattle::
    .string "Jeg tager min lillebror med\n"
    .string "hernæst gang.$"

SixIsland_PatternBush_Text_NashIntro::
    .string "Se, se! Der er underlige\n"
    .string "mønstre pâ jorden.$"

SixIsland_PatternBush_Text_NashDefeat::
    .string "Super fantastisk!$"

SixIsland_PatternBush_Text_NashPostBattle::
    .string "De underlige mønstre pâ jorden…\p"
    .string "De ligner mønstrene pâ min\n"
    .string "bedstefars tøj.$"

SixIsland_PatternBush_Text_CordellIntro::
    .string "Jeg ved du tror jeg bare er en eller\n"
    .string "anden fyr, gør du ikke?$"

SixIsland_PatternBush_Text_CordellDefeat::
    .string "Jeg ved du tror jeg er svag,\n"
    .string "gør du ikke?$"

SixIsland_PatternBush_Text_CordellPostBattle::
    .string "Ja, I bybør kommer rundt sâ\n"
    .string "flot med en sâ iøjnefaldende hat…\p"
    .string "Hvad med at give mig den?$"

SixIsland_PatternBush_Text_DaliaIntro::
    .string "Træk vejret dybt.\n"
    .string "Er luften ikke herlig?$"

SixIsland_PatternBush_Text_DaliaDefeat::
    .string "Hvis du vil, kan jeg lære dig at\n"
    .string "trække vejret ordentligt.$"

SixIsland_PatternBush_Text_DaliaPostBattle::
    .string "Først, pust ud.\n"
    .string "Blæs alt ud.\p"
    .string "Nâr du ikke kan puste mere ud,\n"
    .string "indâand den rene luft!\p"
    .string "Er det ikke forfriskende?$"

SixIsland_PatternBush_Text_JoanaIntro::
    .string "Jeg elsker BUG POKéMON.\n"
    .string "Derfor er jeg her hele tiden.\p"
    .string "Er jeg den eneste pige sâdan?$"

SixIsland_PatternBush_Text_JoanaDefeat::
    .string "Jeg tabte, men jeg griner stadig.\n"
    .string "Er jeg den eneste pige sâdan?$"

SixIsland_PatternBush_Text_JoanaPostBattle::
    .string "Jeg bliver ved med at samle\n"
    .string "BUG POKéMON.\p"
    .string "Er jeg den eneste pige sâdan?$"

SixIsland_PatternBush_Text_RileyIntro::
    .string "Det her er et godt sted.\n"
    .string "Jeg sætter mit telt op her.$"

SixIsland_PatternBush_Text_RileyDefeat::
    .string "Blev kørt over…$"

SixIsland_PatternBush_Text_RileyPostBattle::
    .string "Jeg vil observere nattehimlen\n"
    .string "her.$"

SixIsland_PatternBush_Text_MarcyIntro::
    .string "Aah, ad!\n"
    .string "Jeg tror et insekt stak mig!$"

SixIsland_PatternBush_Text_MarcyDefeat::
    .string "Det var ikke et insekt.\n"
    .string "Jeg skar mig pâ noget græs.$"

SixIsland_PatternBush_Text_MarcyPostBattle::
    .string "Et lille skâr som det…\n"
    .string "Lidt spyt er nok til at kurere det!$"

SixIsland_PatternBush_Text_LaytonIntro::
    .string "Har du lagt mærke til noget mærkeligt\n"
    .string "ved disse egne?$"

SixIsland_PatternBush_Text_LaytonDefeat::
    .string "Har du set ordentligt rundt om\n"
    .string "dine fødder?$"

SixIsland_PatternBush_Text_LaytonPostBattle::
    .string "Der er steder her i PATTERN\n"
    .string "BUSH hvor græs ikke vil gro.\p"
    .string "Hvad kunne ârsagen være til sâ\n"
    .string "et fænomen?$"

