SilphCo_10F_Text_GruntIntro::
    .string "Velkommen til 10. sal!\n"
    .string "Sa godt at du sluttede dig til mig!$"

SilphCo_10F_Text_GruntDefeat::
    .string "Jeg er lamslaaet!$"

SilphCo_10F_Text_GruntPostBattle::
    .string "Godt forsoeg, men modesalen er eet\n"
    .string "sal op.$"

SilphCo_10F_Text_TravisIntro::
    .string "Nok af jeres taabelige spil!$"

SilphCo_10F_Text_TravisDefeat::
    .string "Ingen continues tilbage!$"

SilphCo_10F_Text_TravisPostBattle::
    .string "Er du tilfreds med at besejre mig?\n"
    .string "Sa ga hjem!$"

SilphCo_10F_Text_WaaaImScared::
    .string "Waaaaa!\n"
    .string "Jeg er bange!$"

SilphCo_10F_Text_KeepMeCryingASecret::
    .string "At jeg graed…\n"
    .string "Hold det venligst hemmeligt.$"

SilphCo_10F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "10. SAL$"

