SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "{PLAYER}: Hej!\n"
    .string "Kan du lide POKeMON?\p"
    .string "{PLAYER}: Oehm, nej, jeg spurgte bare dig.\p"
    .string "{PLAYER}: Hvad?\n"
    .string "Du er underlig!\p"
    .string "COPYCAT: Hmm? Holde op med at efterligne?\n"
    .string "Men det er min yndlingshobby!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "{PLAYER}: Hej.\n"
    .string "Du kan vel lide POKeMON.\p"
    .string "{PLAYER}: Nej, ikke mig.\n"
    .string "Jeg spurgte dig.\p"
    .string "{PLAYER}: Undskyld?\n"
    .string "Du er underlig!\l"
    .string " \l"
    .string "COPYCAT: Hmm? Holde op med at efterligne?\l"
    .string "Men det er min yndlingshobby!$"

Text_MimicTeach::
    .string "Oh wow!\n"
    .string "En POKe DOLL!\p"
    .string "Til mig?\n"
    .string "Tak!\p"
    .string "Ved du hvad?\n"
    .string "Jeg kan läre angrebet MIMIC.$"

Text_MimicDeclined::
    .string "Kan du ikke lide MIMIC?$"

Text_MimicWhichMon::
    .string "Jeg elsker virkelig MIMIC!\n"
    .string "Hvem skal läre det?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: Hej!\n"
    .string "Tak for tidligere!\p"
    .string "{PLAYER}: Undskyld?\p"
    .string "{PLAYER}: Er det sâ sjovt at efterligne\n"
    .string "hver min bevägelse?\p"
    .string "COPYCAT: Ja da!\n"
    .string "Det er vanvittigt!$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: Hej!\n"
    .string "Tak for hvad du gjorde for os.\p"
    .string "{PLAYER}: Undskyld?\p"
    .string "{PLAYER}: Er det virkelig sâ sjovt at\n"
    .string "kopiere hvad jeg siger og gör?\p"
    .string "COPYCAT: Ja da!\n"
    .string "Det er vanvittigt!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "{PLAYER}“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "{PLAYER}“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "{PLAYER}“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "{PLAYER}“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "DODUO: Giiih!\p"
    .string "PRETTY MIRROR LOOK AT ME,\n"
    .string "SEE HOW PRETTY I CAN BE?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "Det her er et själdent POKeMON!\n"
    .string "Hva? Det er kun en dukke!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "Et spil med MARIO med en spand\n"
    .string "pâ hovedet!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "…\p"
    .string "Mine hemmeligheder!\p"
    .string "Evne: Efterligning!\n"
    .string "Hobby: Samle dukker!\l"
    .string "Yndlings-POKeMON: CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "？　みえないぞ‥$"

