PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MOR: …Lige sâ.\n"
    .string "Alle drenge forlader hjemmet en dag.\l"
    .string "Sâ stâr der i TV.\p"
    .string "Oh ja. PROF. OAK, ved siden af,\n"
    .string "ledte efter dig.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MOR: …Lige sâ.\n"
    .string "Alle piger drömmer om at rejse.\l"
    .string "Sâ stâr der i TV.\p"
    .string "Oh ja. PROF. OAK, ved siden af,\n"
    .string "ledte efter dig.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MOR: {PLAYER}!\n"
    .string "Du bör tage en kort hvile.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOR: Oh, godt! Du og dine\n"
    .string "POKéMON ser godt ud.\l"
    .string "Pas pâ dig selv!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Der er en film i TV.\n"
    .string "Fire drenge gâr pâ jernbanen.\l"
    .string "…Jeg mâ hellere gâ ogsâ.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Der er en film i TV.\n"
    .string "En pige med fletninger gâr op ad\l"
    .string "en brostensbelagt vej.\p"
    .string "…Jeg mâ hellere gâ ogsâ.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Ups, forkert side…$"

