PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MOR: …Lige så.\n"
    .string "Alle drenge forlader hjemmet en dag.\l"
    .string "Så står der i TV.\p"
    .string "Oh ja. PROF. OAK, ved siden af,\n"
    .string "ledte efter dig.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MOR: …Lige så.\n"
    .string "Alle piger drømmer om at rejse.\l"
    .string "Så står der i TV.\p"
    .string "Oh ja. PROF. OAK, ved siden af,\n"
    .string "ledte efter dig.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MOR: {PLAYER}!\n"
    .string "Du bør tage en kort hvile.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOR: Oh, godt! Du og dine\n"
    .string "POKéMON ser godt ud.\l"
    .string "Pas på dig selv!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Der er en film i TV.\n"
    .string "Fire drenge går på jernbanen.\l"
    .string "…Jeg må hellere gå også.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Der er en film i TV.\n"
    .string "En pige med fletninger går op ad\l"
    .string "en brostensbelagt vej.\p"
    .string "…Jeg må hellere gå også.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Ups, forkert side…$"

