PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MOR: …Lige saa.\n"
    .string "Alle drenge forlader hjemmet en dag.\l"
    .string "Saa staar der i TV.\p"
    .string "Oh ja. PROF. OAK, ved siden af,\n"
    .string "ledte efter dig.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MOR: …Lige saa.\n"
    .string "Alle piger droemmer om at rejse.\l"
    .string "Saa staar der i TV.\p"
    .string "Oh ja. PROF. OAK, ved siden af,\n"
    .string "ledte efter dig.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MOR: {PLAYER}!\n"
    .string "Du boer tage en kort hvile.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOR: Oh, godt! Du og dine\n"
    .string "POKeMON ser godt ud.\l"
    .string "Pas paa dig selv!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Der er en film i TV.\n"
    .string "Fire drenge gaar paa jernbanen.\l"
    .string "…Jeg maa hellere gaa ogsaa.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Der er en film i TV.\n"
    .string "En pige med fletninger gaar op ad\l"
    .string "en brostensbelagt vej.\p"
    .string "…Jeg maa hellere gaa ogsaa.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Ups, forkert side…$"

