LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "Hej, hej!\n"
    .string "Jeg er den officielle NAVNGIVNING!\p"
    .string "Vil du have mig til at bedømme\n"
    .string "dine POKéMONs kaldenavne?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "Hvilken POKéMONs kaldenavn skal\n"
    .string "jeg bedømme?$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "{STR_VAR_1}, ikke?\n"
    .string "Det er et anstændigt kaldenavn!\p"
    .string "Men vil du have mig til at give det\n"
    .string "et pænere navn?\p"
    .string "Hvad med det?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Ah, godt. Hvad skal det nye\n"
    .string "kaldenavn sâ være?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "Færdig! Fra nu af skal denne\n"
    .string "POKéMON kaldes {STR_VAR_1}!\p"
    .string "Det er et bedre navn end før!\n"
    .string "Heldigt for dig!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "Jeg forstâr.\n"
    .string "Kom igen.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "Færdig! Fra nu af skal denne\n"
    .string "POKéMON kaldes {STR_VAR_1}!\p"
    .string "Det ser ikke anderledes ud end før,\n"
    .string "men det er langt bedre!\p"
    .string "Heldigt for dig!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "{STR_VAR_1}, ikke?\n"
    .string "Det er et virkelig ufejlbarligt navn!\p"
    .string "Pas godt pâ {STR_VAR_1}!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "Nej, nej.\n"
    .string "Det er blot et ÆG!$"

