LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "Hej, hej!\n"
    .string "Jeg er den officielle NAVNGIVNING!\p"
    .string "Vil du have mig til at bedoemme\n"
    .string "dine POKeMONs kaldenavne?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "Hvilken POKeMONs kaldenavn skal\n"
    .string "jeg bedoemme?$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "{STR_VAR_1}, ikke?\n"
    .string "Det er et anstaendigt kaldenavn!\p"
    .string "Men vil du have mig til at give det\n"
    .string "et paenere navn?\p"
    .string "Hvad med det?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Ah, godt. Hvad skal det nye\n"
    .string "kaldenavn saa vaere?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "Faerdig! Fra nu af skal denne\n"
    .string "POKeMON kaldes {STR_VAR_1}!\p"
    .string "Det er et bedre navn end foer!\n"
    .string "Heldigt for dig!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "Jeg forstaar.\n"
    .string "Kom igen.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "Faerdig! Fra nu af skal denne\n"
    .string "POKeMON kaldes {STR_VAR_1}!\p"
    .string "Det ser ikke anderledes ud end foer,\n"
    .string "men det er langt bedre!\p"
    .string "Heldigt for dig!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "{STR_VAR_1}, ikke?\n"
    .string "Det er et virkelig ufejlbarligt navn!\p"
    .string "Pas godt paa {STR_VAR_1}!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "Nej, nej.\n"
    .string "Det er blot et AeG!$"

