RocketHideout_B3F_Text_Grunt1Intro::
    .string "Stop med at blande dig i TEAM ROCKETs\n"
    .string "anliggender eller andet!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "Oof!\n"
    .string "Nedlagt!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "SILPH SCOPE?\n"
    .string "Aah, den maskine BOSS stjal.\p"
    .string "Den er et sted her.$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "Vi fik besked oppefra om at du\n"
    .string "kom!$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "Hvad?\n"
    .string "Jeg tabte? Nej!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "Fortsaet bare!\p"
    .string "Men du kan ikke koere elevatoren\n"
    .string "uden LIFT KEY.$"
