SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
    .string "POKéMON väkstrater varierer fra\n"
    .string "art til art.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
    .string "SILPH CO. er bredt kendt af alle.\p"
    .string "Det er offer for sin egen berömmelse - det\n"
    .string "tiltrak TEAM ROCKET.$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .string "Suk…\n"
    .string "Ville det ikke väre fedt?\p"
    .string "Hvis ELITE FOUR kom og\n"
    .string "trampede TEAM ROCKET ned?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
    .string "TEAM ROCKET er stukket af!\n"
    .string "Vi kan ga ud sikkert igen!\l"
    .string "Det er fantastisk!$"

