Route16_House_Text_FoundMySecretRetreat::
    .string "Aa, kaere.\n"
    .string "Du har fundet mit hemmelige tilflugtssted.\p"
    .string "Fortael det ikke til nogen.\n"
    .string "Jeg goer det godt med dette!$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} modtog HM02\n"
    .string "fra pigen.$"

Route16_House_Text_ExplainHM02::
    .string "HM02 er FLY.\n"
    .string "Det er et vidunderligt bekvemt angreb.\p"
    .string "Brug det venligst godt.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "Du har ikke plads til dette.$"

Route16_House_Text_Fearow::
    .string "FEAROW: Kyueen!$"
