PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "POKéMON TOWER blev rejst til\n"
    .string "minde om POKéMON der döde.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Kom du for at vise respekt?\p"
    .string "Velsign dit POKéMON-elskkende hjerte,\n"
    .string "sön.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Kom du for at vise respekt?\p"
    .string "Velsign dit POKéMON-elskkende hjerte,\n"
    .string "pige.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Jeg kom for at bede for min dybt\n"
    .string "afdöde CLEFAIRY.\p"
    .string "Snöft!\n"
    .string "Jeg er oversvömmet af târer…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "Min GROWLITHE…\n"
    .string "Hvorfor döde du?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "Jeg er en CHANNELER.\p"
    .string "Der er ânder der laver ballade.\n"
    .string "Jeg märker dem höjt i TÅRNET.$"
