PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "POKéMON TOWER blev rejst til\n"
    .string "minde om POKéMON der døde.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Kom du for at vise respekt?\p"
    .string "Velsign dit POKéMON-elskkende hjerte,\n"
    .string "søn.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Kom du for at vise respekt?\p"
    .string "Velsign dit POKéMON-elskkende hjerte,\n"
    .string "pige.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Jeg kom for at bede for min dybt\n"
    .string "afdøde CLEFAIRY.\p"
    .string "Snøft!\n"
    .string "Jeg er oversvømmet af târer…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "Min GROWLITHE…\n"
    .string "Hvorfor døde du?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "Jeg er en CHANNELER.\p"
    .string "Der er ânder der laver ballade.\n"
    .string "Jeg mærker dem højt i TÅRNET.$"
