PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "POKeMON TOWER blev rejst til\n"
    .string "minde om POKeMON der doede.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Kom du for at vise respekt?\p"
    .string "Velsign dit POKeMON-elskkende hjerte,\n"
    .string "soen.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Kom du for at vise respekt?\p"
    .string "Velsign dit POKeMON-elskkende hjerte,\n"
    .string "pige.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Jeg kom for at bede for min dybt\n"
    .string "afdoede CLEFAIRY.\p"
    .string "Snoeft!\n"
    .string "Jeg er oversvoemmet af taarer…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "Min GROWLITHE…\n"
    .string "Hvorfor doede du?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "Jeg er en CHANNELER.\p"
    .string "Der er aander der laver ballade.\n"
    .string "Jeg maerker dem hoejt i TAaRNET.$"
