FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "Vi gav VOGTEREN tilnavnet\n"
    .string "SLOWPOKE.\p"
    .string "Han har det fraværende blik\n"
    .string "som en SLOWPOKE.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "VOGTER SLOWPOKE er meget\n"
    .string "velinformeret om POKéMON.\p"
    .string "Han har endda fossiler af sjælde,\n"
    .string "uddøde POKéMON.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "VOGTER SLOWPOKE kom ind, men\n"
    .string "jeg kunne ikke forstâ ham.\p"
    .string "Jeg tror han har et taleproblem!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "VOGTER SLOWPOKE kører en\n"
    .string "kampagne lige nu.\p"
    .string "Prøv at nâ det fjerneste hjørne\n"
    .string "af SAFARI ZONE.\p"
    .string "Hvis du kan, vinder du en meget\n"
    .string "praktisk præmie.$"

