FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "Vi gav VOGTEREN tilnavnet\n"
    .string "SLOWPOKE.\p"
    .string "Han har det fravärende blik\n"
    .string "som en SLOWPOKE.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "VOGTER SLOWPOKE er meget\n"
    .string "velinformeret om POKeMON.\p"
    .string "Han har endda fossiler af själde,\n"
    .string "uddöde POKeMON.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "VOGTER SLOWPOKE kom ind, men\n"
    .string "jeg kunne ikke forstâ ham.\p"
    .string "Jeg tror han har et taleproblem!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "VOGTER SLOWPOKE körer en\n"
    .string "kampagne lige nu.\p"
    .string "Pröv at nâ det fjerneste hjörne\n"
    .string "af SAFARI ZONE.\p"
    .string "Hvis du kan, vinder du en meget\n"
    .string "praktisk prämie.$"

