Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "POKeMON-typerne matcher forskelligt\n"
    .string "med hinanden.\p"
    .string "Hver type er staerkere end nogle\n"
    .string "typer og svagere end andre.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "En NUGGET er totalt ubrugelig.\n"
    .string "Saa jeg solgte den for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "Jeg hoerte at spoegelser hjemsoger\n"
    .string "LAVENDER TOWN.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "Jeg har ledt efter dig!\p"
    .string "Det er mig, en af PROF. OAKs\n"
    .string "altid til stede ASSISTENTER.\p"
    .string "Hvis din POKeDEX har fulde data\n"
    .string "paa tyve arter, skal jeg give dig\l"
    .string "en beloenning fra PROF. OAK.\p"
    .string "Han betroede mig denne\n"
    .string "EVERSTONE.\p"
    .string "Saa, {PLAYER}, lad mig spoerge.\p"
    .string "Har du samlet data paa mindst\n"
    .string "tyve slags POKeMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Stort! Du har fanget eller ejet\n"
    .string "{STR_VAR_3} slags POKeMON!\p"
    .string "Tillykke!\n"
    .string "Vaersgo!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} modtog EVERSTONE\n"
    .string "fra ASSISTENTEN.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "At faa POKeMON til at udvikle sig\n"
    .string "tilfoejer bestemt til POKeDEX.\p"
    .string "Men nogle gange vil du maaske ikke\n"
    .string "have en bestemt POKeMON til at udvikle sig.\p"
    .string "I saa fald, giv EVERSTONE\n"
    .string "til den POKeMON.\p"
    .string "Den forhindrer evolution ifoelge\n"
    .string "PROFESSOREN.$"
