Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "POKéMON-typerne matcher forskelligt\n"
    .string "med hinanden.\p"
    .string "Hver type er stærkere end nogle\n"
    .string "typer og svagere end andre.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "En NUGGET er totalt ubrugelig.\n"
    .string "Sâ jeg solgte den for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "Jeg hørte at spøgelser hjemsoger\n"
    .string "LAVENDER TOWN.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "Jeg har ledt efter dig!\p"
    .string "Det er mig, en af PROF. OAKs\n"
    .string "altid til stede ASSISTENTER.\p"
    .string "Hvis din POKéDEX har fulde data\n"
    .string "pâ tyve arter, skal jeg give dig\l"
    .string "en belønning fra PROF. OAK.\p"
    .string "Han betrøde mig denne\n"
    .string "EVERSTONE.\p"
    .string "Sâ, {PLAYER}, lad mig spørge.\p"
    .string "Har du samlet data pâ mindst\n"
    .string "tyve slags POKéMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Stort! Du har fanget eller ejet\n"
    .string "{STR_VAR_3} slags POKéMON!\p"
    .string "Tillykke!\n"
    .string "Værsgo!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} modtog EVERSTONE\n"
    .string "fra ASSISTENTEN.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "At fâ POKéMON til at udvikle sig\n"
    .string "tilføjer bestemt til POKéDEX.\p"
    .string "Men nogle gange vil du mâske ikke\n"
    .string "have en bestemt POKéMON til at udvikle sig.\p"
    .string "I sâ fald, giv EVERSTONE\n"
    .string "til den POKéMON.\p"
    .string "Den forhindrer evolution ifølge\n"
    .string "PROFESSOREN.$"
