SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
    .string "Leg med POKéMON meget og lev et\n"
    .string "langt liv!\p"
    .string "Tag AGATHA for eksempel.\p"
    .string "Hun satte rekord for at være det\n"
    .string "ældste ELITE FOUR-medlem nogensinde.\p"
    .string "Hun sporer mig til at gøre større ting.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
    .string "Jeg burde købe noget MAIL og skrive\n"
    .string "ham et brev…$"

