SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
    .string "Leg med POKeMON meget og lev et\n"
    .string "langt liv!\p"
    .string "Tag AGATHA for eksempel.\p"
    .string "Hun satte rekord for at vaere det\n"
    .string "aeldste ELITE FOUR-medlem nogensinde.\p"
    .string "Hun sporer mig til at goere stoerre ting.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
    .string "Jeg burde koebe noget MAIL og skrive\n"
    .string "ham et brev…$"

