CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: Yo! {PLAYER}!\p"
    .string "Du kaemper stadig dig frem her\n"
    .string "bagved?\p"
    .string "Jeg har det fantastisk! Jeg fangede en masse\n"
    .string "staerke og kloge POKeMON!\p"
    .string "Her, lad mig se hvad du fangede,\n"
    .string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
    .string "Hey!\n"
    .string "Tag det roligt!\l"
    .string "Du har allerede vundet!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: Hey, gaet hvad?\p"
    .string "Jeg var hos BILL og fik ham til at\n"
    .string "vise mig sine sjaeldne POKeMON.\p"
    .string "Det tilfoejede mange sider til min\n"
    .string "POKeDEX!\p"
    .string "BILL er trods alt verdensberoemt som\n"
    .string "POKeMANIAC.\p"
    .string "Han opfandt ogsaa POKeMON Storage\n"
    .string "System paa PC.\p"
    .string "Siden du bruger hans system,\n"
    .string "boer du takke ham.\p"
    .string "Naa, jeg maa videre!\n"
    .string "Vi ses!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Aah, ja, lige det.\p"
    .string "Jeg har ondt af dig. Nej, virkelig.\n"
    .string "Du pladrer altid bag mig.\p"
    .string "Sa her, jeg giver dig en lille\n"
    .string "gave som tjeneste.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "En sladderhank som dig…\n"
    .string "Den ting er perfekt.\p"
    .string "Jeg har ikke brug for den for jeg\n"
    .string "bryder mig ikke om andre.\p"
    .string "Okay, denne gang er jeg virkelig\n"
    .string "vaek. Vi ses!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .string "Hey! Hold dig vaek!\n"
    .string "Det er ikke din have!\p"
    .string "…Hva?\n"
    .string "Mig?\p"
    .string "Jeg er et uskyldigt vidne!\n"
    .string "Tror du ikke paa mig?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat::
    .string "GRUNT: Stop! Jeg giver op!\n"
    .string "Jeg gaaer stille!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "…Okay.\n"
    .string "Jeg returnerer TM'en jeg stjal.$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER} genvandt TM28 fra\n"
    .string "TEAM ROCKET GRUNT.$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "Jeg maa videre!\n"
    .string "Hej hej!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "Lav plads til dette!\n"
    .string "Jeg kan ikke loebe foer jeg har givet dig det!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "Du er ogsaa TRAINER?\p"
    .string "Samle, kaempe…\n"
    .string "Det er et haardt liv, er det ikke?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "Vidste du at du kan CUT ned\n"
    .string "smaa traeer?\p"
    .string "Selv det lille trae foran\n"
    .string "butikken kan CUTtes ned.\p"
    .string "Jeg tror der er en vej rundt om det,\n"
    .string "dog.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "Hvis den SLOWBRO ikke var der, kunne du\n"
    .string "CUTte det lille trae ned.\p"
    .string "Saadan kunne du naa den\n"
    .string "anden side.\p"
    .string "Jeg tror der er en vej rundt om det,\n"
    .string "dog.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "Du laver en leksikon om\n"
    .string "POKeMON? Det lyder morsomt.$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "Folkene her blev roevet.\p"
    .string "Det er tydeligt at TEAM ROCKET er\n"
    .string "bag denne grufulde forbrydelse!\p"
    .string "Selv vores POLITI har\n"
    .string "besvaer med ROCKETs!$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "Okay! SLOWBRO!\n"
    .string "Brug SONICBOOM!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "Kom nu, SLOWBRO, vaer opmaerksom!$"

CeruleanCity_Text_SlowbroPunch::
    .string "SLOWBRO, slaa!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "Nej!\n"
    .string "Du oedelagde det igen!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "SLOWBRO, WITHDRAW!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "Nej! Det er forkert!\n"
    .string "Det er saa svaert at kontrollere POKeMON!\p"
    .string "Din POKeMONs lydighed afhaenger af\n"
    .string "dine evner som TRAINER.$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLOWBRO tog en lur…$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLOWBRO driver…$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLOWBRO vendte sig vaek…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLOWBRO ignorerede ordrer…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "Jeg vil have en skinnende roed cykel.\p"
    .string "Jeg holder den hjemme, saa den ikke\n"
    .string "bliver beskidt.$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "Dette er CERULEAN CAVE.\p"
    .string "Forfaerdeligt staerke POKeMON bor\n"
    .string "derinde.\p"
    .string "Det kraever en meget speciel TRAINER\n"
    .string "for at faa lov til at komme ind.\p"
    .string "Du skal i det mindste vaere staerk nok\n"
    .string "til at blive POKeMON LEAGUE\l"
    .string "CHAMPION for at starte.\p"
    .string "Og du skal have gjort en stor\n"
    .string "bedrift.$"

CeruleanCity_Text_CitySign::
    .string "CERULEAN CITY\n"
    .string "En mystisk, blaa aura omgiver\l"
    .string "den$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "TRAINER TIPS\p"
    .string "En POKeMON kan faa et item at\n"
    .string "holde.\p"
    .string "Nogle items kan endda bruges af\n"
    .string "den holdende POKeMON i kamp.$"

CeruleanCity_Text_BikeShopSign::
    .string "Graes og huler haandteres nemt!\n"
    .string "BIKE SHOP$"

CeruleanCity_Text_GymSign::
    .string "CERULEAN CITY POKeMON GYM\n"
    .string "LEADER: MISTY\l"
    .string "Den drengede Havfrue!$"
