CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .string "Hej!\n"
    .string "Velkommen til vores BIKE SHOP.\p"
    .string "Vi har lige den BIKE til dig!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .string "Beklager!\n"
    .string "Du har ikke râd til den!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .string "Aah, det er…\p"
    .string "En BIKE VOUCHER!\p"
    .string "Okay!\n"
    .string "Her har du!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .string "{PLAYER} byttede\n"
    .string "BIKE VOUCHER for en BICYCLE.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .string "Tak!\n"
    .string "Kom igen en gang!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .string "Hvordan kan du lide din nye BICYCLE?\n"
    .string "Kan du lide hvordan den kører?\p"
    .string "Du kan tage den med pâ CYCLING\n"
    .string "ROAD og endda ind i huler!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .string "Du bør lave plads til din\n"
    .string "BICYCLE!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .string "En simpel bycykel er god nok\n"
    .string "til mig.\p"
    .string "Du kan trods alt ikke sætte en indkøbs-\n"
    .string "kurv pâ en bjergcykel.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .string "Disse cykler er seje, men de er\n"
    .string "sâ dyre!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .string "Wow.\n"
    .string "Din BIKE er virkelig sej!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .string "En skinende ny BICYCLE!$"
