FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "Der er mange POKeMON lukket inde\n"
    .string "i folden…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "Folddören er lâst op.\n"
    .string "POKeMON ser ud til at väre flygtet.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "Kom du her velvidende om at det er\n"
    .string "TEAM ROCKETs LAGER?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "Hvad bilder du dig ind?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "TEAM ROCKET er oplöst?\n"
    .string "Hvilken planet kommer du fra?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "Oeh, dine POKeMON ser stärke ud.\n"
    .string "Vil du sälge dem?\p"
    .string "Oeh?\n"
    .string "Du ville kämpe?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "Oeh, men…\n"
    .string "For meget!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "Vi kan give dig et godt tilbud.\n"
    .string "Sälg os dine POKeMON!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "Jeg har hört om dig fra de andre.\p"
    .string "Men en unge som dig kan umuligt\n"
    .string "kende vores CHEF GIOVANNI!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "Vov… ikke… at… grine…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "Bland dig uden om voksnes sager,\n"
    .string "din forvovne pygmä!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "Jeg ved ikke eller bryder mig ikke om\n"
    .string "om det jeg gör er rigtigt eller galt…\p"
    .string "Jeg stoler bare pâ GIOVANNI og\n"
    .string "gör som jeg fâr besked pâ.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "Jeg…\n"
    .string "Jeg er knust…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "Du gör ting efter dine overbevisninger\n"
    .string "og moral.\p"
    .string "Jeg forstâr nu…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "Jeg har sörget for at du kan komme\n"
    .string "tilbage ind der.\p"
    .string "Hvorfor ikke hvile og blive frisk\n"
    .string "til det der venter?\p"
    .string "ADMIN'en efter mig er langt over\n"
    .string "mig som TRAINER.\p"
    .string "Du bör göre dig klar til en hârd\n"
    .string "udfordring.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "Nu er det nok med at du\n"
    .string "spiller helt, unge.\p"
    .string "Spreder lögne om at TEAM ROCKET\n"
    .string "er oplöst…\p"
    .string "Det er et sâ tydeligt forsög pâ at\n"
    .string "skabe forvirring i vores räkker.\p"
    .string "Heldigvis er vi ikke sâ naive at\n"
    .string "falde for en unges lögne!\p"
    .string "Og nu viser jeg dig hvor skrämmende\n"
    .string "en vred voksen kan väre!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "Urgh…\n"
    .string "Du var for stärk…\p"
    .string "…\n"
    .string "D-det er GIOVANNIs BADGE!\p"
    .string "Sâ det er sandt?\n"
    .string "TEAM ROCKET er virkelig oplöst?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "Vi forlader dette LAGER…\p"
    .string "Men tro ikke det er slut.\n"
    .string "Jeg lader ikke det väre enden.\p"
    .string "Jeg finder GIOVANNI.\n"
    .string "Og jeg genopliver TEAM ROCKET!\l"
    .string "Det vil jeg…\p"
    .string "Til da, farvel!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "En rapport med grafer og tekst er\n"
    .string "pâ PC-skärmen.\p"
    .string "Magnetiske bolgers indflydelse pâ\n"
    .string "POKeMON-evolution.\p"
    .string "… … … … … …\p"
    .string "Det er for svärt at forstâ…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "Jeg nästen solgte SAPPHIREN for\n"
    .string "en formue…\p"
    .string "Sâ mâtte du bare komme og\n"
    .string "ödelägge hele handlen!\p"
    .string "Fufu… Fufufufu…\n"
    .string "Der er ingen tilgivelse for dig!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "Gah! Pokkers!\n"
    .string "Pokkers! Pokkers!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "Hvis jeg ikke kan sälge den, er den\n"
    .string "värdilös! Värsgo, tag den!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "Hvad vil du nu?\n"
    .string "Forsvind, lad mig väre i fred.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "Hvad, dig igen?\p"
    .string "Du… Du er vel ikke GIOVANNIs\n"
    .string "barn?\p"
    .string "Nej, det kan ikke väre rigtigt!\n"
    .string "GIOVANNIs barn har rödt hâr.\p"
    .string "Du har ingen grunde til at\n"
    .string "gener mig. Lad mig väre!$"

