FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "Der er mange POKéMON lukket inde\n"
    .string "i folden…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "Folddøren er lâst op.\n"
    .string "POKéMON ser ud til at være flygtet.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "Kom du her velvidende om at det er\n"
    .string "TEAM ROCKETs LAGER?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "Hvad bilder du dig ind?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "TEAM ROCKET er opløst?\n"
    .string "Hvilken planet kommer du fra?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "Øh, dine POKéMON ser stærke ud.\n"
    .string "Vil du sælge dem?\p"
    .string "Øh?\n"
    .string "Du ville kæmpe?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "Øh, men…\n"
    .string "For meget!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "Vi kan give dig et godt tilbud.\n"
    .string "Sælg os dine POKéMON!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "Jeg har hørt om dig fra de andre.\p"
    .string "Men en unge som dig kan umuligt\n"
    .string "kende vores CHEF GIOVANNI!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "Vov… ikke… at… grine…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "Bland dig uden om voksnes sager,\n"
    .string "din forvovne pygmæ!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "Jeg ved ikke eller bryder mig ikke om\n"
    .string "om det jeg gør er rigtigt eller galt…\p"
    .string "Jeg stoler bare pâ GIOVANNI og\n"
    .string "gør som jeg fâr besked pâ.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "Jeg…\n"
    .string "Jeg er knust…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "Du gør ting efter dine overbevisninger\n"
    .string "og moral.\p"
    .string "Jeg forstâr nu…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "Jeg har sørget for at du kan komme\n"
    .string "tilbage ind der.\p"
    .string "Hvorfor ikke hvile og blive frisk\n"
    .string "til det der venter?\p"
    .string "ADMIN'en efter mig er langt over\n"
    .string "mig som TRAINER.\p"
    .string "Du bør gøre dig klar til en hârd\n"
    .string "udfordring.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "Nu er det nok med at du\n"
    .string "spiller helt, unge.\p"
    .string "Spreder løgne om at TEAM ROCKET\n"
    .string "er opløst…\p"
    .string "Det er et sâ tydeligt forsøg pâ at\n"
    .string "skabe forvirring i vores rækker.\p"
    .string "Heldigvis er vi ikke sâ naive at\n"
    .string "falde for en unges løgne!\p"
    .string "Og nu viser jeg dig hvor skræmmende\n"
    .string "en vred voksen kan være!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "Urgh…\n"
    .string "Du var for stærk…\p"
    .string "…\n"
    .string "D-det er GIOVANNIs BADGE!\p"
    .string "Sâ det er sandt?\n"
    .string "TEAM ROCKET er virkelig opløst?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "Vi forlader dette LAGER…\p"
    .string "Men tro ikke det er slut.\n"
    .string "Jeg lader ikke det være enden.\p"
    .string "Jeg finder GIOVANNI.\n"
    .string "Og jeg genopliver TEAM ROCKET!\l"
    .string "Det vil jeg…\p"
    .string "Til da, farvel!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "En rapport med grafer og tekst er\n"
    .string "pâ PC-skærmen.\p"
    .string "Magnetiske bolgers indflydelse pâ\n"
    .string "POKéMON-evolution.\p"
    .string "… … … … … …\p"
    .string "Det er for svært at forstâ…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "Jeg næsten solgte SAPPHIREN for\n"
    .string "en formue…\p"
    .string "Sâ mâtte du bare komme og\n"
    .string "ødelægge hele handlen!\p"
    .string "Fufu… Fufufufu…\n"
    .string "Der er ingen tilgivelse for dig!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "Gah! Pokkers!\n"
    .string "Pokkers! Pokkers!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "Hvis jeg ikke kan sælge den, er den\n"
    .string "værdiløs! Værsgo, tag den!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "Hvad vil du nu?\n"
    .string "Forsvind, lad mig være i fred.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "Hvad, dig igen?\p"
    .string "Du… Du er vel ikke GIOVANNIs\n"
    .string "barn?\p"
    .string "Nej, det kan ikke være rigtigt!\n"
    .string "GIOVANNIs barn har rødt hâr.\p"
    .string "Du har ingen grunde til at\n"
    .string "gener mig. Lad mig være!$"

