FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "Der er mange POKeMON lukket inde\n"
    .string "i folden…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "Folddoeren er laast op.\n"
    .string "POKeMON ser ud til at vaere flygtet.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "Kom du her velvidende om at det er\n"
    .string "TEAM ROCKETs LAGER?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "Hvad bilder du dig ind?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "TEAM ROCKET er oploest?\n"
    .string "Hvilken planet kommer du fra?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "Oeh, dine POKeMON ser staerke ud.\n"
    .string "Vil du saelge dem?\p"
    .string "Oeh?\n"
    .string "Du ville kaempe?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "Oeh, men…\n"
    .string "For meget!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "Vi kan give dig et godt tilbud.\n"
    .string "Saelg os dine POKeMON!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "Jeg har hoert om dig fra de andre.\p"
    .string "Men en unge som dig kan umuligt\n"
    .string "kende vores CHEF GIOVANNI!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "Vov… ikke… at… grine…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "Bland dig uden om voksnes sager,\n"
    .string "din forvovne pygmae!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "Jeg ved ikke eller bryder mig ikke om\n"
    .string "om det jeg goer er rigtigt eller galt…\p"
    .string "Jeg stoler bare paa GIOVANNI og\n"
    .string "goer som jeg faar besked paa.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "Jeg…\n"
    .string "Jeg er knust…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "Du goer ting efter dine overbevisninger\n"
    .string "og moral.\p"
    .string "Jeg forstaar nu…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "Jeg har soerget for at du kan komme\n"
    .string "tilbage ind der.\p"
    .string "Hvorfor ikke hvile og blive frisk\n"
    .string "til det der venter?\p"
    .string "ADMIN'en efter mig er langt over\n"
    .string "mig som TRAINER.\p"
    .string "Du boer goere dig klar til en haard\n"
    .string "udfordring.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "Nu er det nok med at du\n"
    .string "spiller helt, unge.\p"
    .string "Spreder loegne om at TEAM ROCKET\n"
    .string "er oploest…\p"
    .string "Det er et saa tydeligt forsoeg paa at\n"
    .string "skabe forvirring i vores raekker.\p"
    .string "Heldigvis er vi ikke saa naive at\n"
    .string "falde for en unges loegne!\p"
    .string "Og nu viser jeg dig hvor skraemmende\n"
    .string "en vred voksen kan vaere!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "Urgh…\n"
    .string "Du var for staerk…\p"
    .string "…\n"
    .string "D-det er GIOVANNIs BADGE!\p"
    .string "Saa det er sandt?\n"
    .string "TEAM ROCKET er virkelig oploest?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "Vi forlader dette LAGER…\p"
    .string "Men tro ikke det er slut.\n"
    .string "Jeg lader ikke det vaere enden.\p"
    .string "Jeg finder GIOVANNI.\n"
    .string "Og jeg genopliver TEAM ROCKET!\l"
    .string "Det vil jeg…\p"
    .string "Til da, farvel!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "En rapport med grafer og tekst er\n"
    .string "paa PC-skaermen.\p"
    .string "Magnetiske bolgers indflydelse paa\n"
    .string "POKeMON-evolution.\p"
    .string "… … … … … …\p"
    .string "Det er for svaert at forstaa…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "Jeg naesten solgte SAPPHIREN for\n"
    .string "en formue…\p"
    .string "Saa maatte du bare komme og\n"
    .string "oedelaegge hele handlen!\p"
    .string "Fufu… Fufufufu…\n"
    .string "Der er ingen tilgivelse for dig!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "Gah! Pokkers!\n"
    .string "Pokkers! Pokkers!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "Hvis jeg ikke kan saelge den, er den\n"
    .string "vaerdiloes! Vaersgo, tag den!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "Hvad vil du nu?\n"
    .string "Forsvind, lad mig vaere i fred.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "Hvad, dig igen?\p"
    .string "Du… Du er vel ikke GIOVANNIs\n"
    .string "barn?\p"
    .string "Nej, det kan ikke vaere rigtigt!\n"
    .string "GIOVANNIs barn har roedt haar.\p"
    .string "Du har ingen grunde til at\n"
    .string "gener mig. Lad mig vaere!$"

