#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("Et fysisk angreb\nmed hale eller\nforben.");
const u8 gMoveDescription_KarateChop[] = _("Fjenden rammes med\net skarpt hug.\nHoej kritisk-treffer.");
const u8 gMoveDescription_DoubleSlap[] = _("Fjenden slaaes\ngentagne gange,\nto til fem gange.");
const u8 gMoveDescription_CometPunch[] = _("Fjenden rammes med\nen byge af slag\nto til fem gange.");
const u8 gMoveDescription_MegaPunch[] = _("Fjenden rammes af\net slag med\nmuskelkraft.");
const u8 gMoveDescription_PayDay[] = _("Moenter kastes mod\nfjenden. Man tjener\npenge efter kamp.");
const u8 gMoveDescription_FirePunch[] = _("Fjenden rammes med\nen ildslukket naeve.\nKan give forbraending.");
const u8 gMoveDescription_IcePunch[] = _("Fjenden rammes med\nen isnende naeve.\nKan fryse fjenden.");
const u8 gMoveDescription_ThunderPunch[] = _("Fjenden rammes med\nen elektrisk naeve.\nKan lammelse.");
const u8 gMoveDescription_Scratch[] = _("Haarde, skarpe\nkloer rive fjenden.");
const u8 gMoveDescription_ViceGrip[] = _("Store kloer griber\nog klemmer fjenden.");
const u8 gMoveDescription_Guillotine[] = _("Et brutalt angreb\nmed kloer. Fjenden\nbesvimer hvis det rammer.");
const u8 gMoveDescription_RazorWind[] = _("Vindklinger rammer\nfjenden i 2. tur.\nHoej kritisk-treffer.");
const u8 gMoveDescription_SwordsDance[] = _("En kampdans.\nOeger ANGREB\nskarpt.");
const u8 gMoveDescription_Cut[] = _("Et grundangreb.\nKan bruges til at\nskaere traeer og graes.");
const u8 gMoveDescription_Gust[] = _("Rammer fjenden med\nen vindstod fra\nvingerne.");
const u8 gMoveDescription_WingAttack[] = _("Fjenden rammes med\nstore vinger.");
const u8 gMoveDescription_Whirlwind[] = _("Fjenden skiftes ud\nmed allieret. I vildt\nnaturen ender kampen.");
const u8 gMoveDescription_Fly[] = _("2-turs angreb.\nTraeffer i 2. tur.\nFlyv til by.");
const u8 gMoveDescription_Bind[] = _("Lang krop eller\nfangarme binder\nfjenden 2-5 ture.");
const u8 gMoveDescription_Slam[] = _("Fjenden rammes med\nhale, vinranker osv.");
const u8 gMoveDescription_VineWhip[] = _("Fjenden rammes med\ntynde, piskelign.\nvinranker.");
const u8 gMoveDescription_Stomp[] = _("Fjenden trampes\nmed stor fod.\nKan faa fjenden til at vige.");
const u8 gMoveDescription_DoubleKick[] = _("To ben sparker\nfjenden hurtigt\nto gange.");
const u8 gMoveDescription_MegaKick[] = _("Fjenden rammes af\net kraftigt spark\nmed muskelkraft.");
const u8 gMoveDescription_JumpKick[] = _("Brugeren springer\nog sparker. Skader\nsig selv ved forbier.");
const u8 gMoveDescription_RollingKick[] = _("Hurtigt spark fra\nrullende spin.\nKan faa fjenden til at vige.");
const u8 gMoveDescription_SandAttack[] = _("Sand kastes i\nfjendens ansigt og\nsaenker praecision.");
const u8 gMoveDescription_Headbutt[] = _("Brugeren stikker\nhovedet frem og\nrammer. Kan vige.");
const u8 gMoveDescription_HornAttack[] = _("Fjenden stikkes med\net skarpt horn for\nat tilfoeje skade.");
const u8 gMoveDescription_FuryAttack[] = _("Fjenden stikkes\ngentagne gange med\nhorn eller naeb 2-5 gange.");
const u8 gMoveDescription_HornDrill[] = _("Hornet roterer som\nen bor. Fjenden\nbesvimer hvis det rammer.");
const u8 gMoveDescription_Tackle[] = _("Fysisk angreb hvor\nbrugeren charger\nfuld krop ind i fjenden.");
const u8 gMoveDescription_BodySlam[] = _("Brugeren kaster\nhele kroppen over\nfjenden. Kan lammelse.");
const u8 gMoveDescription_Wrap[] = _("Lang krop eller\nvinranker vikles\nom fjenden 2-5 ture.");
const u8 gMoveDescription_TakeDown[] = _("Raa fuldkrops-angreb\nder ogsaa skader\nbrugeren lidt.");
const u8 gMoveDescription_Thrash[] = _("Brugeren raser i\n2-3 ture og bliver\nsaa forvirret.");
const u8 gMoveDescription_DoubleEdge[] = _("Livsfarligt angreb\nder ogsaa skader\nbrugeren lidt.");
const u8 gMoveDescription_TailWhip[] = _("Brugeren vifter med\nhalen. Saenker\nfjendens FORSVAR.");
const u8 gMoveDescription_PoisonSting[] = _("Fjenden stikkes med\ngiftigt brodd.\nKan forgifte.");
const u8 gMoveDescription_Twineedle[] = _("Fjenden stikkes to\ngange med forben.\nKan forgifte.");
const u8 gMoveDescription_PinMissile[] = _("Skarpe naale skydes\nog traeffer 2-5\ngange.");
const u8 gMoveDescription_Leer[] = _("Intimerende blik\nsaenker fjendens\nFORSVAR.");
const u8 gMoveDescription_Bite[] = _("Brugeren bider med\nondskabsfulde\ntaender. Kan vige.");
const u8 gMoveDescription_Growl[] = _("Brugeren knurrer\nsoedt og saenker\nfjendens ANGREB.");
const u8 gMoveDescription_Roar[] = _("Fjenden skiftes ud.\nI vildt naturen\nender kampen.");
const u8 gMoveDescription_Sing[] = _("En beroligende\nsang putter\nfjenden i soevn.");
const u8 gMoveDescription_Supersonic[] = _("Brugeren skaber\nunderlige lyde.\nKan forvirre fjenden.");
const u8 gMoveDescription_SonicBoom[] = _("Fjenden rammes af\nchokbolge der\naltid giver 20 KP skade.");
const u8 gMoveDescription_Disable[] = _("Forhindrer fjenden i\nat bruge sidste\nangreb i nogle ture.");
const u8 gMoveDescription_Acid[] = _("Fjenden spraejtes med\netsende syre.\nKan saenke FORSVAR.");
const u8 gMoveDescription_Ember[] = _("Fjenden angribes med\nsmaa flammer.\nKan give forbraending.");
const u8 gMoveDescription_Flamethrower[] = _("Fjenden braendes med\nintense flammer.\nKan forbraending.");
const u8 gMoveDescription_Mist[] = _("Allieret hold er\nbeskyttet af taage\nder forhindrer stat-nedgang.");
const u8 gMoveDescription_WaterGun[] = _("Fjenden rammes med\nvand skudt kraftigt\nfra munden.");
const u8 gMoveDescription_HydroPump[] = _("Stort vandvolumen\nblaeses mod fjenden\nunder tryk.");
const u8 gMoveDescription_Surf[] = _("Stor bolge rammer\nfjenden. Kan bruges\ntil at krydse vand.");
const u8 gMoveDescription_IceBeam[] = _("Fjenden rammes med\nisstraale. Kan\nfryse fjenden.");
const u8 gMoveDescription_Blizzard[] = _("Fjenden rammes af\nblizzard. Kan\nfryse fjenden.");
const u8 gMoveDescription_Psybeam[] = _("Saerlig straale skydes\nmod fjenden.\nKan forvirre.");
const u8 gMoveDescription_BubbleBeam[] = _("Bobler rammer\nfjenden. Kan saenke\nfjendens HASTIGHED.");
const u8 gMoveDescription_AuroraBeam[] = _("Regnbuefarvet\nangrebsstraale.\nKan saenke ANGREB.");
const u8 gMoveDescription_HyperBeam[] = _("Kraftigt angreb.\nBrugeren hviler\nnaeste tur.");
const u8 gMoveDescription_Peck[] = _("Fjenden stikkes med\nskarpt naeb eller\nhorn.");
const u8 gMoveDescription_DrillPeck[] = _("Skruende angreb med\nnaebbet som bor.");
const u8 gMoveDescription_Submission[] = _("Raa kast-angreb der\naa skader brugeren\nlidt.");
const u8 gMoveDescription_LowKick[] = _("Lav spark der giver\nmere skade til\ntungere fjender.");
const u8 gMoveDescription_Counter[] = _("Modangreb der\ngiver dobbelt skade\ntilbage ved fysisk ram.");
const u8 gMoveDescription_SeismicToss[] = _("Kast der giver\nskade svarende til\nbrugerens niveau.");
const u8 gMoveDescription_Strength[] = _("Fjenden rammes med\nfuld kraft. Kan\nflytte klippeblokke.");
const u8 gMoveDescription_Absorb[] = _("Angreb der absorberer\nhalvdelen af skaden\ntil KP-genvinding.");
const u8 gMoveDescription_MegaDrain[] = _("Haardt angreb der\ndraener halvdelen\ntil KP-genvinding.");
const u8 gMoveDescription_LeechSeed[] = _("Fro plantet paa\nfjenden stjaeler KP\ntil brugeren hver tur.");
const u8 gMoveDescription_Growth[] = _("Brugerens krop vokser\nog oeger SP. ANGREB.");
const u8 gMoveDescription_RazorLeaf[] = _("Fjenden rammes med\nskaerende blad.\nHoej kritisk-treffer.");
const u8 gMoveDescription_SolarBeam[] = _("2-turs angreb der\nrammer med absorberet\nenergi i 2. tur.");
const u8 gMoveDescription_PoisonPowder[] = _("Giftigt stoev\nspredes. Kan\nforgifte fjenden.");
const u8 gMoveDescription_StunSpore[] = _("Lammende stoev\nspredes. Kan\nlamme fjenden.");
const u8 gMoveDescription_SleepPowder[] = _("Soevn-inducerende\nstoev spredes omkring\nfjenden.");
const u8 gMoveDescription_PetalDance[] = _("Brugeren angriber med\nblomsterblade 2-3 ture\nog bliver forvirret.");
const u8 gMoveDescription_StringShot[] = _("Fjenden bindes med\ntraade fra munden\nog HASTIGHED saenkes.");
const u8 gMoveDescription_DragonRage[] = _("Chokbolge rammer\nfjenden og giver\naltid 40 KP skade.");
const u8 gMoveDescription_FireSpin[] = _("Fjenden fanges i\nildspiral i 2-5 ture.");
const u8 gMoveDescription_ThunderShock[] = _("Elektrisk chok der\nkan lamme fjenden.");
const u8 gMoveDescription_Thunderbolt[] = _("Staerkt elektrisk\nangreb. Kan lamme.");
const u8 gMoveDescription_ThunderWave[] = _("Svagt elektrisk chok\nder lammer fjenden\nhvis det rammer.");
const u8 gMoveDescription_Thunder[] = _("Brutalt lynangreb.\nKan lamme fjenden.");
const u8 gMoveDescription_RockThrow[] = _("Fjenden rammes med\nen byge af smaa\nkastede sten.");
const u8 gMoveDescription_Earthquake[] = _("Jordskaelv rammer\nalle POKeMON i kamp\nundtagen brugeren.");
const u8 gMoveDescription_Fissure[] = _("Fjenden falder i\nrevne. Besvimer\nhvis det rammer.");
const u8 gMoveDescription_Dig[] = _("Angreb der rammer\ni 2. tur. Kan\nbruges til at forlade huler.");
const u8 gMoveDescription_Toxic[] = _("Angreb der forgifter\nsvaert. Gift-skaden\nforvaerres hver tur.");
const u8 gMoveDescription_Confusion[] = _("Svagt telekinetisk\nangreb. Kan\nforvirre fjenden.");
const u8 gMoveDescription_Psychic[] = _("Staerkt telekinetisk\nangreb. Kan saenke\nSP. FORSVAR.");
const u8 gMoveDescription_Hypnosis[] = _("Hypnotisk suggestion\nfaar fjenden til at\nfalde i dyb soevn.");
const u8 gMoveDescription_Meditate[] = _("Brugeren mediterer\nog oeger ANGREB.");
const u8 gMoveDescription_Agility[] = _("Brugeren slapper af\nog letter kroppen\nfor at oge HASTIGHED.");
const u8 gMoveDescription_QuickAttack[] = _("Naesten usynligt\nhurtigt angreb der\ntraeffer foerst.");
const u8 gMoveDescription_Rage[] = _("Angreb der bliver\nstaerkere hver gang\nbrugeren rammes.");
const u8 gMoveDescription_Teleport[] = _("Brug til at flygte fra\nvilde POKeMON.\nTeleporterer til\nsidste POKe CENTER.");
const u8 gMoveDescription_NightShade[] = _("Angreb med illusion\nder giver skade\nsvarende til niveau.");
const u8 gMoveDescription_Mimic[] = _("Brugeren kopierer\nfjendens sidste\nangreb resten af kampen.");
const u8 gMoveDescription_Screech[] = _("Orebedovende skrig\nsaenker fjendens\nFORSVAR skarpt.");
const u8 gMoveDescription_DoubleTeam[] = _("Brugeren skaber\nillusioner af sig\nselv og oeger undvigelse.");
const u8 gMoveDescription_Recover[] = _("Genopretter op til\nhalvdelen af brugerens\nmax KP.");
const u8 gMoveDescription_Harden[] = _("Brugeren spaender\nmuskler og oeger\nFORSVAR.");
const u8 gMoveDescription_Minimize[] = _("Brugeren komprimerer\nceller og oeger\nundvigelse.");
const u8 gMoveDescription_Smokescreen[] = _("Taage eller blaek\nreducerer fjendens\npraecision.");
const u8 gMoveDescription_ConfuseRay[] = _("Fjenden rammes af\nuhyggelig straale\nder forvirrer.");
const u8 gMoveDescription_Withdraw[] = _("Brugeren traekker sig\ni skjold og oeger\nFORSVAR.");
const u8 gMoveDescription_DefenseCurl[] = _("Brugeren ruller sig\nsammen og oeger\nFORSVAR.");
const u8 gMoveDescription_Barrier[] = _("Brugeren skaber\nsolid mur og oeger\nFORSVAR skarpt.");
const u8 gMoveDescription_LightScreen[] = _("Lysvaeg reducerer\nskade fra SP. ANGREB\ni fem ture.");
const u8 gMoveDescription_Haze[] = _("Fjerner alle stat-\naendringer hos alle\nPOKeMON i kampen.");
const u8 gMoveDescription_Reflect[] = _("Lysvaeg reducerer\nfysisk skade i\nfem ture.");
const u8 gMoveDescription_FocusEnergy[] = _("Brugeren fokuserer\nog oeger kritisk-\ntreffer.");
const u8 gMoveDescription_Bide[] = _("Brugeren taaler\nangreb i to ture\nog slaar tilbage dobbelt.");
const u8 gMoveDescription_Metronome[] = _("Vifter med finger og\nbruger tilfaeldigt\nangreb.");
const u8 gMoveDescription_MirrorMove[] = _("Brugeren bruger\nsamme angreb som\nfjenden lige brugte.");
const u8 gMoveDescription_SelfDestruct[] = _("Brugeren eksploderer\nog tilfoejer stor\nskade, besvimer.");
const u8 gMoveDescription_EggBomb[] = _("Stort aeg kastes med\nkraft mod fjenden.");
const u8 gMoveDescription_Lick[] = _("Fjenden slikkes med\nlang tunge. Kan\nlamme.");
const u8 gMoveDescription_Smog[] = _("Fjenden angribes med\nudstoedningsgas.\nKan forgifte.");
const u8 gMoveDescription_Sludge[] = _("Giftigt slam kastes.\nKan forgifte maalet.");
const u8 gMoveDescription_BoneClub[] = _("Fjenden slaas med\nben. Kan faa til at vige.");
const u8 gMoveDescription_FireBlast[] = _("Fjenden rammes af\nintens flamme.\nKan forbraending.");
const u8 gMoveDescription_Waterfall[] = _("Kraftigt angreb.\nKan bruges til at\nklatre vandfald.");
const u8 gMoveDescription_Clamp[] = _("Fjenden klemmes af\nskal i 2-5 ture.");
const u8 gMoveDescription_Swift[] = _("Stjerne-straaler der\naltid rammer alle\nfjender.");
const u8 gMoveDescription_SkullBash[] = _("FORSVAR i 1. tur,\nangreb i 2. tur.");
const u8 gMoveDescription_SpikeCannon[] = _("Skarpe pigge skydes\not rammer 2-5 gange.");
const u8 gMoveDescription_Constrict[] = _("Fjenden rammes med\nfangarme eller\nvinranker. Kan saenke HASTIGHED.");
const u8 gMoveDescription_Amnesia[] = _("Glemmer noget og\noeger SP. FORSVAR\nskarpt.");
const u8 gMoveDescription_Kinesis[] = _("Brugeren distraerer\nmed boejet ske.\nKan saenke praecision.");
const u8 gMoveDescription_SoftBoiled[] = _("Helbreder op til\nhalvdelen af KP.\nKan helbrede allieret.");
const u8 gMoveDescription_HiJumpKick[] = _("Kraftigt spring-spark.\nSkader brugeren\nved bom.");
const u8 gMoveDescription_Glare[] = _("Brugeren skraemmer\nfjenden med moenster\nog lammer.");
const u8 gMoveDescription_DreamEater[] = _("Absorberer halvdelen\naf skaden paa\nsoevnende fjende til KP.");
const u8 gMoveDescription_PoisonGas[] = _("Giftig gas spraejes.\nKan forgifte fjenden.");
const u8 gMoveDescription_Barrage[] = _("Runde genstande\nkastes og rammer\n2-5 gange.");
const u8 gMoveDescription_LeechLife[] = _("Angreb der absorberer\nhalvdelen af skaden\ntil KP.");
const u8 gMoveDescription_LovelyKiss[] = _("Brugeren kysser\nfjenden med skraemmende\nansigt og soevn.");
const u8 gMoveDescription_SkyAttack[] = _("Angreb i 2. tur.\nHoej kritisk-treffer.\nKan vige.");
const u8 gMoveDescription_Transform[] = _("Brugeren forvandler\nsig til kopi af\nfjenden med samme angreb.");
const u8 gMoveDescription_Bubble[] = _("Bobler rammer\nfjenden. Kan saenke\nHASTIGHED.");
const u8 gMoveDescription_DizzyPunch[] = _("Rytmisk slag der\nkan forvirre fjenden.");
const u8 gMoveDescription_Spore[] = _("Brugeren spreder\nsporer der putter\ni soevn.");
const u8 gMoveDescription_Flash[] = _("Lysblitz reducerer\npraecision. Oplyser\nda og huler.");
const u8 gMoveDescription_Psywave[] = _("Fjenden rammes af\nunderlig energibolge\nmed varierende staerke.");
const u8 gMoveDescription_Splash[] = _("Brugeren plasker\nuden effekt.");
const u8 gMoveDescription_AcidArmor[] = _("Celler aendres til\nflydende og FORSVAR\noeger skarpt.");
const u8 gMoveDescription_Crabhammer[] = _("Stor klo bruges som\nhammer. Hoej kritisk.");
const u8 gMoveDescription_Explosion[] = _("Brugeren eksploderer\nfor stor skade og\nbesvimer.");
const u8 gMoveDescription_FurySwipes[] = _("Fjenden rives med\nkloer 2-5 gange.");
const u8 gMoveDescription_Bonemerang[] = _("Ben kastes, rammer\nfjenden og kommer\ntilbage og rammer igen.");
const u8 gMoveDescription_Rest[] = _("Brugeren sover to\nture og genopretter\nalt KP og status.");
const u8 gMoveDescription_RockSlide[] = _("Store sten kastes.\nKan faa fjenden til at vige.");
const u8 gMoveDescription_HyperFang[] = _("Skarpe taender.\nKan vige.");
const u8 gMoveDescription_Sharpen[] = _("Brugeren skaerper\nkanter og oeger\nANGREB.");
const u8 gMoveDescription_Conversion[] = _("Brugeren aendrer type\ntil et af sine angreb.");
const u8 gMoveDescription_TriAttack[] = _("Trippel-straale der\nkan lamme, braende\neller fryse.");
const u8 gMoveDescription_SuperFang[] = _("Skarpe taender\nhalverer fjendens KP.");
const u8 gMoveDescription_Slash[] = _("Fjenden skaeres med\nkloer. Hoej kritisk.");
const u8 gMoveDescription_Substitute[] = _("Brugeren skaber\nafledningsmanoever\nfor 1/4 af KP.");
const u8 gMoveDescription_Struggle[] = _("Bruges kun uden PP.\nSkader ogsaa brugeren.");
const u8 gMoveDescription_Sketch[] = _("Kopierer fjendens\nsidste angreb og\nforsvinder saa.");
const u8 gMoveDescription_TripleKick[] = _("Tre spark der bliver\nstaerkere ved hvert\ntraef.");
const u8 gMoveDescription_Thief[] = _("Kan stjaele fjendens\ngenstand hvis brugeren\nikke holder noget.");
const u8 gMoveDescription_SpiderWeb[] = _("Fanger fjenden i\nklistret traad saa den\nikke kan flygte.");
const u8 gMoveDescription_MindReader[] = _("Brugeren forudser\nfjendens traek saa\nnaeste angreb rammer.");
const u8 gMoveDescription_Nightmare[] = _("Soevnende fjende ser\nmareridt og tager\nskade hver tur.");
const u8 gMoveDescription_FlameWheel[] = _("Ildlad angreb.\nKan give forbraending.");
const u8 gMoveDescription_Snore[] = _("Kun under soevn.\nKan faa til at vige.");
const u8 gMoveDescription_Curse[] = _("Virker forskelligt for\nSPOEGELSES-type og\nandre typer.");
const u8 gMoveDescription_Flail[] = _("Desperat angreb der\nbliver staerkere ved\nlavt KP.");
const u8 gMoveDescription_Conversion2[] = _("Brugeren aendrer type\nsaa den er modstandsdygtig\nmod sidste angreb.");
const u8 gMoveDescription_Aeroblast[] = _("Luftvirvel skydes.\nHoej kritisk-treffer.");
const u8 gMoveDescription_CottonSpore[] = _("Bomulds-lignende\nsporer saenker\nHASTIGHED skarpt.");
const u8 gMoveDescription_Reversal[] = _("Alt-i-alt angreb\nstaerkere ved lavt KP.");
const u8 gMoveDescription_Spite[] = _("Fjerner 2-5 PP fra\nfjendens sidste angreb.");
const u8 gMoveDescription_PowderSnow[] = _("Snebyge rammer\nfjenden. Kan fryse.");
const u8 gMoveDescription_Protect[] = _("Undgaar alle angreb.\nKan fejle ved gentagen brug.");
const u8 gMoveDescription_MachPunch[] = _("Hurtigt slag der\ntraeffer foerst.");
const u8 gMoveDescription_ScaryFace[] = _("Skraemmer fjenden og\nsaenker HASTIGHED\nskarpt.");
const u8 gMoveDescription_FaintAttack[] = _("Brugeren naermer sig\nufarligt og rammer sikkert.");
const u8 gMoveDescription_SweetKiss[] = _("Soedt kys forvirrer\nfjenden.");
const u8 gMoveDescription_BellyDrum[] = _("Maximerer ANGREB\nmod halvdelen af\nfuldt KP.");
const u8 gMoveDescription_SludgeBomb[] = _("Slam kastes mod\nfjenden. Kan forgifte.");
const u8 gMoveDescription_MudSlap[] = _("Mudder kastes i\nansigtet. Skade og\nlavere praecision.");
const u8 gMoveDescription_Octazooka[] = _("Blaek skydes i ansigt\neller oejne. Skade\nog lavere praecision.");
const u8 gMoveDescription_Spikes[] = _("Pigfaelde omkring\nfjendens hold skader\nved skift.");
const u8 gMoveDescription_ZapCannon[] = _("Elektrisk kugle\nrammer og lammer.");
const u8 gMoveDescription_Foresight[] = _("Ophaever fjendens\nundvigelsesforboed.");
const u8 gMoveDescription_DestinyBond[] = _("Hvis brugeren besvimer,\nbesvimer fjenden der\ndelede sidste slag ogsaa.");
const u8 gMoveDescription_PerishSong[] = _("Alle der hoerer\nbesvimer om tre ture\nmedmindre de skifter.");
const u8 gMoveDescription_IcyWind[] = _("Kold vind angriber\nog saenker HASTIGHED.");
const u8 gMoveDescription_Detect[] = _("Undgaar alle angreb.\nKan fejle ved gentagen brug.");
const u8 gMoveDescription_BoneRush[] = _("Ben slaas med 2-5\ngange mod fjenden.");
const u8 gMoveDescription_LockOn[] = _("Brugeren laaser sig\npaa fjenden saa naeste\nangreb rammer.");
const u8 gMoveDescription_Outrage[] = _("Brugeren raser i 2-3\nture og bliver forvirret.");
const u8 gMoveDescription_Sandstorm[] = _("5-turs sandstorm skader\nalle undtagen STEN,\nJORD og STAAL.");
const u8 gMoveDescription_GigaDrain[] = _("Haardt angreb der\ndraener halvdelen\ntil KP-genvinding.");
const u8 gMoveDescription_Endure[] = _("Brugeren taaler med\n1 KP. Kan fejle ved\ngentagen brug.");
const u8 gMoveDescription_Charm[] = _("Fjenden charmeres og\nANGREB saenkes skarpt.");
const u8 gMoveDescription_Rollout[] = _("5-turs rullende angreb\nder bliver staerkere\nved hvert traef.");
const u8 gMoveDescription_FalseSwipe[] = _("Angreb der altid\nlader fjenden med\nmindst 1 KP.");
const u8 gMoveDescription_Swagger[] = _("Forvirrer fjenden men\noeger ANGREB skarpt.");
const u8 gMoveDescription_MilkDrink[] = _("Helbreder op til\nhalvdelen af KP.\nKan helbrede allieret.");
const u8 gMoveDescription_Spark[] = _("Elektrisk angreb der\nkan lamme fjenden.");
const u8 gMoveDescription_FuryCutter[] = _("Angreb der bliver\nstaerkere ved hvert\ntraef.");
const u8 gMoveDescription_SteelWing[] = _("Fjenden rammes med\nstaalvinger. Kan oge\nbrugerens FORSVAR.");
const u8 gMoveDescription_MeanLook[] = _("Fjenden faar ondt blik\nder forhindrer flugt.");
const u8 gMoveDescription_Attract[] = _("Ved modsat koen\nbliver fjenden forelsket\nog angriber sjaeldent.");
const u8 gMoveDescription_SleepTalk[] = _("Under soevn bruger\nbrugeren tilfaeldigt et\naf sine angreb.");
const u8 gMoveDescription_HealBell[] = _("Laekker klokke helbreder\nstatus hos alle allierede.");
const u8 gMoveDescription_Return[] = _("Angreb staerkere jo\nmere brugeren kan\nlide sin TRAINER.");
const u8 gMoveDescription_Present[] = _("Giver fjenden gave.\nGiver somme tider KP\neller skade.");
const u8 gMoveDescription_Frustration[] = _("Angreb staerkere jo\nmindre brugeren kan\nlide TRAINER.");
const u8 gMoveDescription_Safeguard[] = _("Beskytter holdet mod\nstatus i fem ture.");
const u8 gMoveDescription_PainSplit[] = _("Brugeren deler samlet\nKP lige med fjenden.");
const u8 gMoveDescription_SacredFire[] = _("Mystisk ildangreb.\nKan give forbraending.");
const u8 gMoveDescription_Magnitude[] = _("Jordskaelv mod alle\nPOKeMON. Staerke varierer.");
const u8 gMoveDescription_DynamicPunch[] = _("Fuld kraft slag.\nForvirrer fjenden ved traef.");
const u8 gMoveDescription_Megahorn[] = _("Brutalt hornangreb.");
const u8 gMoveDescription_DragonBreath[] = _("Kraftig aandeblast.\nKan lamme.");
const u8 gMoveDescription_BatonPass[] = _("Brugeren skifter og\noverfoerer stat-aendringer\ntil naeste.");
const u8 gMoveDescription_Encore[] = _("Faar fjenden til at\ngentage sidste angreb\ni 2-6 ture.");
const u8 gMoveDescription_Pursuit[] = _("Angreb der er staerkere\nmod fjender der skifter.");
const u8 gMoveDescription_RapidSpin[] = _("Befrier brugeren fra\nBIND, WRAP, LEECH\nSEED og SPIKES.");
const u8 gMoveDescription_SweetScent[] = _("Tiltraekker og saenker\nundvigelse. Tiltraekker\nvilde POKeMON.");
const u8 gMoveDescription_IronTail[] = _("Staalhaard hale.\nKan saenke FORSVAR.");
const u8 gMoveDescription_MetalClaw[] = _("Staalkloer. Kan oge\nbrugerens ANGREB.");
const u8 gMoveDescription_VitalThrow[] = _("Brugeren angriber sidst\nmen rammer altid.");
const u8 gMoveDescription_MorningSun[] = _("Genopretter KP.\nMaengde afhaenger af vejret.");
const u8 gMoveDescription_Synthesis[] = _("Genopretter KP.\nMaengde afhaenger af vejret.");
const u8 gMoveDescription_Moonlight[] = _("Genopretter KP.\nMaengde afhaenger af vejret.");
const u8 gMoveDescription_HiddenPower[] = _("Angreb hvis type og\nstaerke afhaenger af\nbrugeren.");
const u8 gMoveDescription_CrossChop[] = _("Dobbelt hug. Hoej\nkritisk-treffer.");
const u8 gMoveDescription_Twister[] = _("Voldsom hvirvel.\nKan vige.");
const u8 gMoveDescription_RainDance[] = _("Kraftig regn i 5 ture.\nForstaerker VAND-angreb.");
const u8 gMoveDescription_SunnyDay[] = _("Solskin i 5 ture.\nForstaerker ILD-angreb.");
const u8 gMoveDescription_Crunch[] = _("Skarpe taender.\nKan saenke SP. FORSVAR.");
const u8 gMoveDescription_MirrorCoat[] = _("Returnerer dobbelt\nskade fra specialangreb.");
const u8 gMoveDescription_PsychUp[] = _("Brugeren kopierer\nfjendens stat-aendringer.");
const u8 gMoveDescription_ExtremeSpeed[] = _("Ekstrem hastighed.\nTraeffer altid foerst.");
const u8 gMoveDescription_AncientPower[] = _("Oldgammel kraft.\nKan oge alle stats.");
const u8 gMoveDescription_ShadowBall[] = _("Skyggeblob kastes.\nKan saenke SP. FORSVAR.");
const u8 gMoveDescription_FutureSight[] = _("To ture senere rammes\nfjenden psykisk.");
const u8 gMoveDescription_RockSmash[] = _("Kan saenke FORSVAR.\nKan smadre revner.");
const u8 gMoveDescription_Whirlpool[] = _("Fjenden fanges i\nhvirvel 2-5 ture.");
const u8 gMoveDescription_BeatUp[] = _("Alle holdets POKeMON\ndeltager. Flere allierede\n= mere skade.");
const u8 gMoveDescription_FakeOut[] = _("Traeffer foerst og\nfaar til at vige.\nKun 1. tur.");
const u8 gMoveDescription_Uproar[] = _("Brugeren angriber og\nforhindrer soevn i\n2-5 ture.");
const u8 gMoveDescription_Stockpile[] = _("Oplader kraft til\nsenere brug. Op til\ntre gange.");
const u8 gMoveDescription_SpitUp[] = _("Udlaeder opladt kraft\nfra OPLADNING i et angreb.");
const u8 gMoveDescription_Swallow[] = _("Absorberer opladt\nenergi til KP.");
const u8 gMoveDescription_HeatWave[] = _("Varm aandeblast.\nKan forbraending.");
const u8 gMoveDescription_Hail[] = _("Hagl i 5 ture skader\nalle undtagen IS-type.");
const u8 gMoveDescription_Torment[] = _("Fjenden kan ikke\nbruge samme angreb\nto gange i traek.");
const u8 gMoveDescription_Flatter[] = _("Smoer forvirrer\nfjenden men oeger\nSP. ANGREB.");
const u8 gMoveDescription_WillOWisp[] = _("Blaahvid flamme\nrammer og braender.");
const u8 gMoveDescription_Memento[] = _("Brugeren besvimer men\nsaenker fjendens\nANGREB og SP. ANGREB.");
const u8 gMoveDescription_Facade[] = _("Staerkere hvis brugeren\ner braendt, forgiftet\neller lammet.");
const u8 gMoveDescription_FocusPunch[] = _("Udfoeres sidst. Brugeren\nviger hvis ramt foerst.");
const u8 gMoveDescription_SmellingSalt[] = _("Dobbelt skade mod\nlammet fjende men\nhelbreder lammelse.");
const u8 gMoveDescription_FollowMe[] = _("Brugeren traekker\nopmaerksomhed saa\nfjender kun rammer den.");
const u8 gMoveDescription_NaturePower[] = _("Angreb hvis type\nafhaenger af sted.");
const u8 gMoveDescription_Charge[] = _("Oplader til naeste\nELEKTRIK-angreb.");
const u8 gMoveDescription_Taunt[] = _("Fjenden kan kun\nbruge angreb i nogle ture.");
const u8 gMoveDescription_HelpingHand[] = _("Forstaerker allierets\nnaeste angreb.");
const u8 gMoveDescription_Trick[] = _("Bytter genstand med\nfjenden.");
const u8 gMoveDescription_RolePlay[] = _("Brugeren kopierer\nfjendens evne.");
const u8 gMoveDescription_Wish[] = _("Genopretter halvdelen\naf max KP naeste tur.");
const u8 gMoveDescription_Assist[] = _("Bruger tilfaeldigt angreb\nfra allieret POKeMON.");
const u8 gMoveDescription_Ingrain[] = _("Roedder genopretter KP\nhver tur. Kan ikke skifte.");
const u8 gMoveDescription_Superpower[] = _("Kraftigt angreb men\nsaenker ANGREB og\nFORSVAR.");
const u8 gMoveDescription_MagicCoat[] = _("Sender fjendens LEECH\nSEED og status-angreb\ntilbage.");
const u8 gMoveDescription_Recycle[] = _("Genbruger brugt\ngenstand én gang.");
const u8 gMoveDescription_Revenge[] = _("Staerkere hvis brugeren\nblev ramt i samme tur.");
const u8 gMoveDescription_BrickBreak[] = _("Bryder LYSVaeG og\nREFLECT.");
const u8 gMoveDescription_Yawn[] = _("Stort gab faar\nfjenden til at sove\nnaeste tur.");
const u8 gMoveDescription_KnockOff[] = _("Slaar fjendens genstand\naf saa den ikke kan\nbruges i kampen.");
const u8 gMoveDescription_Endeavor[] = _("Staerkere jo faerre KP\nbrugeren har mod fjenden.");
const u8 gMoveDescription_Eruption[] = _("Jo hoejere brugerens KP,\ndesto staerkere angreb.");
const u8 gMoveDescription_SkillSwap[] = _("Bytter evner med\nfjenden psykisk.");
const u8 gMoveDescription_Imprison[] = _("Forhindrer fjenden i\nangreb brugeren ogsaa kan.");
const u8 gMoveDescription_Refresh[] = _("Helbreder forgiftning,\nforbraending eller lammelse.");
const u8 gMoveDescription_Grudge[] = _("Hvis brugeren besvimer,\nbliver angrebet der slog\nden brugt 0 PP.");
const u8 gMoveDescription_Snatch[] = _("Stjaeler fjendens\nhelbredelses- eller\nstatus-effekt.");
const u8 gMoveDescription_SecretPower[] = _("Angreb med ekstra\neffekt afhaengigt af\nterraen.");
const u8 gMoveDescription_Dive[] = _("Dykker 1. tur og\nrammer 2. tur.");
const u8 gMoveDescription_ArmThrust[] = _("Hurtige armslag\n2-5 gange.");
const u8 gMoveDescription_Camouflage[] = _("Aendrer brugerens type\nafhaengigt af terraen.");
const u8 gMoveDescription_TailGlow[] = _("Lys oeger SP. ANGREB\nskarpt.");
const u8 gMoveDescription_LusterPurge[] = _("Lysburst skader.\nKan saenke SP. FORSVAR.");
const u8 gMoveDescription_MistBall[] = _("Dunbyge rammer.\nKan saenke SP. ANGREB.");
const u8 gMoveDescription_FeatherDance[] = _("Dun daekker fjenden\nog saenker ANGREB skarpt.");
const u8 gMoveDescription_TeeterDance[] = _("Vralt dans forvirrer\nalle POKeMON i kamp.");
const u8 gMoveDescription_BlazeKick[] = _("Ildspark. Hoej kritisk.\nKan forbraending.");
const u8 gMoveDescription_MudSport[] = _("Svaekker ELEKTRIK-angreb\nmens brugeren er i kamp.");
const u8 gMoveDescription_IceBall[] = _("5-turs rulle-angreb\nder bliver staerkere.");
const u8 gMoveDescription_NeedleArm[] = _("Piggede arme.\nKan vige.");
const u8 gMoveDescription_SlackOff[] = _("Brugeren slapper af\nog genopretter halvdelen af KP.");
const u8 gMoveDescription_HyperVoice[] = _("Skraekkelig raeb der\ntilfoejer skade.");
const u8 gMoveDescription_PoisonFang[] = _("Giftige taender.\nKan svaert forgifte.");
const u8 gMoveDescription_CrushClaw[] = _("Skarpe kloer.\nKan saenke FORSVAR.");
const u8 gMoveDescription_BlastBurn[] = _("Kaempe eksplosion.\nBrugeren kan ikke bevaege sig naeste tur.");
const u8 gMoveDescription_HydroCannon[] = _("Vandkanon. Brugeren\nkan ikke bevaege sig naeste tur.");
const u8 gMoveDescription_MeteorMash[] = _("Haardt hurtigt slag.\nKan oge ANGREB.");
const u8 gMoveDescription_Astonish[] = _("Overraskende raeb.\nKan vige.");
const u8 gMoveDescription_WeatherBall[] = _("Angreb hvis type og\nstaerke afhaenger af vejret.");
const u8 gMoveDescription_Aromatherapy[] = _("Duft helbreder alle\nstatus i holdet.");
const u8 gMoveDescription_FakeTears[] = _("Falske taarer saenker\nfjendens SP. FORSVAR.");
const u8 gMoveDescription_AirCutter[] = _("Skaerende vind. Hoej\nkritisk-treffer.");
const u8 gMoveDescription_Overheat[] = _("Intenst angreb der\nsaenker brugerens\nSP. ANGREB skarpt.");
const u8 gMoveDescription_OdorSleuth[] = _("Ophaever fjendens\nundvigelse.");
const u8 gMoveDescription_RockTomb[] = _("Stenblokke kastes.\nSaenker HASTIGHED ved traef.");
const u8 gMoveDescription_SilverWind[] = _("Soelvstoev rammer.\nKan oge alle stats.");
const u8 gMoveDescription_MetalSound[] = _("Metallisk skrig\nsaenker SP. FORSVAR.");
const u8 gMoveDescription_GrassWhistle[] = _("Behagelig melodi\nputter fjenden i soevn.");
const u8 gMoveDescription_Tickle[] = _("Faa fjenden til at grine\nog saenk ANGREB og FORSVAR.");
const u8 gMoveDescription_CosmicPower[] = _("Mystisk kraft oeger\nFORSVAR og SP. FORSVAR.");
const u8 gMoveDescription_WaterSpout[] = _("Jo hoejere KP,\ndesto staerkere.");
const u8 gMoveDescription_SignalBeam[] = _("Blinkende straale.\nKan forvirre.");
const u8 gMoveDescription_ShadowPunch[] = _("Slag fra skygger.\nKan ikke undgaas.");
const u8 gMoveDescription_Extrasensory[] = _("Saerlig kraft.\nKan vige.");
const u8 gMoveDescription_SkyUppercut[] = _("Oppehak mod himlen\nmed kraft.");
const u8 gMoveDescription_SandTomb[] = _("Fjenden fanges i\nsandstorm 2-5 ture.");
const u8 gMoveDescription_SheerCold[] = _("Ultimativ kulde.\nBesvimer ved traef.");
const u8 gMoveDescription_MuddyWater[] = _("Mudderet vand.\nKan saenke praecision.");
const u8 gMoveDescription_BulletSeed[] = _("Skyd 2-5 fro mod\nfjenden.");
const u8 gMoveDescription_AerialAce[] = _("Ekstrem hurtigt angreb.\nKan ikke undgaas.");
const u8 gMoveDescription_IcicleSpear[] = _("Skarpe ispigger\n2-5 gange.");
const u8 gMoveDescription_IronDefense[] = _("Haerd overflade.\nOeger FORSVAR skarpt.");
const u8 gMoveDescription_Block[] = _("Blokerer fjendens vej\nsaa den ikke kan flygte.");
const u8 gMoveDescription_Howl[] = _("Brugeren hyler og\noeger ANGREB.");
const u8 gMoveDescription_DragonClaw[] = _("Skarpe dragekloer\nmed stor kraft.");
const u8 gMoveDescription_FrenzyPlant[] = _("Kaempe gren. Brugeren\nkan ikke bevaege sig naeste tur.");
const u8 gMoveDescription_BulkUp[] = _("Brugeren bygger\nmuskler. Oeger ANGREB og FORSVAR.");
const u8 gMoveDescription_Bounce[] = _("Springer paa fjenden\n2. tur. Kan lamme.");
const u8 gMoveDescription_MudShot[] = _("Mudder kastes.\nSaenker HASTIGHED.");
const u8 gMoveDescription_PoisonTail[] = _("Hoej kritisk. Kan forgifte.");
const u8 gMoveDescription_Covet[] = _("Soedt angreb der\nstjaeler fjendens genstand.");
const u8 gMoveDescription_VoltTackle[] = _("Elektrisk angreb.\nSkader brugeren lidt.");
const u8 gMoveDescription_MagicalLeaf[] = _("Magisk blad der\nikke kan undgaas.");
const u8 gMoveDescription_WaterSport[] = _("Svaekker ILD-angreb\nmens brugeren er i kamp.");
const u8 gMoveDescription_CalmMind[] = _("Fokus oeger SP. ANGREB\nog SP. FORSVAR.");
const u8 gMoveDescription_LeafBlade[] = _("Skaerende blad. Hoej\nkritisk-treffer.");
const u8 gMoveDescription_DragonDance[] = _("Mystisk dans oeger\nANGREB og HASTIGHED.");
const u8 gMoveDescription_RockBlast[] = _("Kaster 2-5 haarde\nsten mod fjenden.");
const u8 gMoveDescription_ShockWave[] = _("Hurtig stroem. Kan\nikke undgaas.");
const u8 gMoveDescription_WaterPulse[] = _("Vandpuls. Kan forvirre.");
const u8 gMoveDescription_DoomDesire[] = _("Angriber fjenden med\nlys to ture senere.");
const u8 gMoveDescription_PsychoBoost[] = _("Intenst angreb der\nsaenker SP. ANGREB.");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_DOUBLE_SLAP   - 1] = gMoveDescription_DoubleSlap,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_VICE_GRIP     - 1] = gMoveDescription_ViceGrip,
    [MOVE_GUILLOTINE    - 1] = gMoveDescription_Guillotine,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_SLAM          - 1] = gMoveDescription_Slam,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_HORN_ATTACK   - 1] = gMoveDescription_HornAttack,
    [MOVE_FURY_ATTACK   - 1] = gMoveDescription_FuryAttack,
    [MOVE_HORN_DRILL    - 1] = gMoveDescription_HornDrill,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_TWINEEDLE     - 1] = gMoveDescription_Twineedle,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_SUPERSONIC    - 1] = gMoveDescription_Supersonic,
    [MOVE_SONIC_BOOM    - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_ACID          - 1] = gMoveDescription_Acid,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_ICE_BEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_BLIZZARD      - 1] = gMoveDescription_Blizzard,
    [MOVE_PSYBEAM       - 1] = gMoveDescription_Psybeam,
    [MOVE_BUBBLE_BEAM   - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_LOW_KICK      - 1] = gMoveDescription_LowKick,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLAR_BEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_DANCE   - 1] = gMoveDescription_PetalDance,
    [MOVE_STRING_SHOT   - 1] = gMoveDescription_StringShot,
    [MOVE_DRAGON_RAGE   - 1] = gMoveDescription_DragonRage,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_THROW    - 1] = gMoveDescription_RockThrow,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_CONFUSION     - 1] = gMoveDescription_Confusion,
    [MOVE_PSYCHIC       - 1] = gMoveDescription_Psychic,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_MEDITATE      - 1] = gMoveDescription_Meditate,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_BIDE          - 1] = gMoveDescription_Bide,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_MIRROR_MOVE   - 1] = gMoveDescription_MirrorMove,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_EGG_BOMB      - 1] = gMoveDescription_EggBomb,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_SLUDGE        - 1] = gMoveDescription_Sludge,
    [MOVE_BONE_CLUB     - 1] = gMoveDescription_BoneClub,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_CLAMP         - 1] = gMoveDescription_Clamp,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_SPIKE_CANNON  - 1] = gMoveDescription_SpikeCannon,
    [MOVE_CONSTRICT     - 1] = gMoveDescription_Constrict,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_KINESIS       - 1] = gMoveDescription_Kinesis,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_GLARE         - 1] = gMoveDescription_Glare,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_POISON_GAS    - 1] = gMoveDescription_PoisonGas,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS   - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_SPORE         - 1] = gMoveDescription_Spore,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_ACID_ARMOR    - 1] = gMoveDescription_AcidArmor,
    [MOVE_CRABHAMMER    - 1] = gMoveDescription_Crabhammer,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_BONEMERANG    - 1] = gMoveDescription_Bonemerang,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_HYPER_FANG    - 1] = gMoveDescription_HyperFang,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_SUPER_FANG    - 1] = gMoveDescription_SuperFang,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_TRIPLE_KICK   - 1] = gMoveDescription_TripleKick,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_MIND_READER   - 1] = gMoveDescription_MindReader,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_POWDER_SNOW   - 1] = gMoveDescription_PowderSnow,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_FAINT_ATTACK  - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_SLUDGE_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_OCTAZOOKA     - 1] = gMoveDescription_Octazooka,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_ZAP_CANNON    - 1] = gMoveDescription_ZapCannon,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_BONE_RUSH     - 1] = gMoveDescription_BoneRush,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_CHARM         - 1] = gMoveDescription_Charm,
    [MOVE_ROLLOUT       - 1] = gMoveDescription_Rollout,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_MILK_DRINK    - 1] = gMoveDescription_MilkDrink,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_MEAN_LOOK     - 1] = gMoveDescription_MeanLook,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_RETURN        - 1] = gMoveDescription_Return,
    [MOVE_PRESENT       - 1] = gMoveDescription_Present,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_MEGAHORN      - 1] = gMoveDescription_Megahorn,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_SWEET_SCENT   - 1] = gMoveDescription_SweetScent,
    [MOVE_IRON_TAIL     - 1] = gMoveDescription_IronTail,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_MORNING_SUN   - 1] = gMoveDescription_MorningSun,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_MOONLIGHT     - 1] = gMoveDescription_Moonlight,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_TWISTER       - 1] = gMoveDescription_Twister,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_FUTURE_SIGHT  - 1] = gMoveDescription_FutureSight,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_BEAT_UP       - 1] = gMoveDescription_BeatUp,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_UPROAR        - 1] = gMoveDescription_Uproar,
    [MOVE_STOCKPILE     - 1] = gMoveDescription_Stockpile,
    [MOVE_SPIT_UP       - 1] = gMoveDescription_SpitUp,
    [MOVE_SWALLOW       - 1] = gMoveDescription_Swallow,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_FLATTER       - 1] = gMoveDescription_Flatter,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_FOLLOW_ME     - 1] = gMoveDescription_FollowMe,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_ROLE_PLAY     - 1] = gMoveDescription_RolePlay,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_GRUDGE        - 1] = gMoveDescription_Grudge,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_DIVE          - 1] = gMoveDescription_Dive,
    [MOVE_ARM_THRUST    - 1] = gMoveDescription_ArmThrust,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_TAIL_GLOW     - 1] = gMoveDescription_TailGlow,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_MUD_SPORT     - 1] = gMoveDescription_MudSport,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_POISON_FANG   - 1] = gMoveDescription_PoisonFang,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_BLAST_BURN    - 1] = gMoveDescription_BlastBurn,
    [MOVE_HYDRO_CANNON  - 1] = gMoveDescription_HydroCannon,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_CUTTER    - 1] = gMoveDescription_AirCutter,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_ODOR_SLEUTH   - 1] = gMoveDescription_OdorSleuth,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_METAL_SOUND   - 1] = gMoveDescription_MetalSound,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_COSMIC_POWER  - 1] = gMoveDescription_CosmicPower,
    [MOVE_WATER_SPOUT   - 1] = gMoveDescription_WaterSpout,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_SKY_UPPERCUT  - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_SHEER_COLD    - 1] = gMoveDescription_SheerCold,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_AERIAL_ACE    - 1] = gMoveDescription_AerialAce,
    [MOVE_ICICLE_SPEAR  - 1] = gMoveDescription_IcicleSpear,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_DRAGON_CLAW   - 1] = gMoveDescription_DragonClaw,
    [MOVE_FRENZY_PLANT  - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_TAIL   - 1] = gMoveDescription_PoisonTail,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_WATER_SPORT   - 1] = gMoveDescription_WaterSport,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_DRAGON_DANCE  - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_DOOM_DESIRE   - 1] = gMoveDescription_DoomDesire,
    [MOVE_PSYCHO_BOOST  - 1] = gMoveDescription_PsychoBoost,
};
