CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "Hej!\n"
    .string "Velkommen til CELADON DEPT. STORE.\p"
    .string "Tavlen til höjre beskriver\n"
    .string "butikkens layout.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "1F: SERVICE COUNTER\p"
    .string "2F: TRAINER'S MARKET\p"
    .string "3F: TV GAME SHOP\p"
    .string "4F: WISE MAN GIFTS\p"
    .string "5F: DRUGSTORE\p"
    .string "ROOFTOP SQUARE: VENDING MACHINES$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "1F: SERVICE COUNTER$"
