@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords::
    .string "とびらを　あけるには\n"
    .string "パスワードが　2つ　いるようだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded::
    .string "{PLAYER} indtastede en adgangskode.\p"
    .string "GOLDEEN need log.\p"
    .string "… …  … …  … …\p"
    .string "En adgangskode mere behøves for at\n"
    .string "âbne døren…$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened::
    .string "{PLAYER} indtastede to adgangskoder.\p"
    .string "GOLDEEN need log.\n"
    .string "Yes, nah, CHANSEY.\p"
    .string "… …  … …  … …\p"
    .string "LAGERETS dør gik op!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen::
    .string "LAGERETS dør er allerede âben.$"

FiveIsland_Meadow_Text_Rocket1Intro::
    .string "Dette omrâde er strengt forbudt!\n"
    .string "Ud, ud!$"

FiveIsland_Meadow_Text_Rocket1Defeat::
    .string "Er det for alvor?$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
    .string "Du har ingen forretning her!\n"
    .string "Gâ hjem!$"

FiveIsland_Meadow_Text_Rocket2Intro::
    .string "Der er intet herfra undtagen\n"
    .string "vores LAGER.\p"
    .string "Sâ hvad bringer dig her?$"

FiveIsland_Meadow_Text_Rocket2Defeat::
    .string "Det skulle ikke ske…$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
    .string "Vil du vide hvad der er inde i\n"
    .string "dette LAGER?\p"
    .string "Det er bedre du ikke ved det.\n"
    .string "For din egen skyld.$"

FiveIsland_Meadow_Text_Rocket3Intro::
    .string "Du spilder tid selv hvis du\n"
    .string "kommer forbi mig.$"

FiveIsland_Meadow_Text_Rocket3Defeat::
    .string "Øh, det gør mig rasende!$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
    .string "Du kommer ikke ind uden\n"
    .string "adgangskoderne alligevel.$"

