CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "Fangede POKéMON registreres\n"
    .string "med et ID No. og OT.\p"
    .string "OT stâer for Original TRAINER -\n"
    .string "TRAINERen der fangede den först.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "Okay!\p"
    .string "Min kammerat bytter sin\n"
    .string "KANGASKHAN for min HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "Kom nu, HAUNTER!\p"
    .string "Jeg elsker HAUNTER!\n"
    .string "Jeg samler pâ dem!\p"
    .string "Hva?\p"
    .string "HAUNTER blev til en anden\n"
    .string "POKéMON under byttehandlen!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "Du kan genkende POKéMON du fâr\n"
    .string "ved bytte pâ deres ID-numre.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "Det er en Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "Et RPG!\n"
    .string "Der er ikke tid til det!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "Et sportsspil!\n"
    .string "Far vil kunne lide det!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "Et puslespil!\n"
    .string "Ser vanedannende ud!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "Et kämpespil!\n"
    .string "Ser hârdt ud!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "3F: TV GAME SHOP$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "Röd og Grön!\n"
    .string "Begge er POKéMON!$"

Text_CounterTeach::
    .string "Aah, hej!\n"
    .string "Jeg er endelig färdig med POKéMON.\p"
    .string "Ikke färdig endnu? Skal jeg läre dig\n"
    .string "et godt trick?\p"
    .string "Tricket jeg tänker pâ er\n"
    .string "COUNTER.\p"
    .string "Ikke som den jeg läner mig op ad,\n"
    .string "bemärk!$"

Text_CounterDeclined::
    .string "Du er ikke interesseret? Kom til mig\n"
    .string "hvis du ombestemmer dig.$"

Text_CounterWhichMon::
    .string "Hvilken POKéMON skal jeg läre\n"
    .string "COUNTER?$"

Text_CounterTaught::
    .string "Bruger du det COUNTER-trick\n"
    .string "jeg lärte din POKéMON?$"
