CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "Fangede POKeMON registreres\n"
    .string "med et ID No. og OT.\p"
    .string "OT staaer for Original TRAINER -\n"
    .string "TRAINERen der fangede den foerst.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "Okay!\p"
    .string "Min kammerat bytter sin\n"
    .string "KANGASKHAN for min HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "Kom nu, HAUNTER!\p"
    .string "Jeg elsker HAUNTER!\n"
    .string "Jeg samler paa dem!\p"
    .string "Hva?\p"
    .string "HAUNTER blev til en anden\n"
    .string "POKeMON under byttehandlen!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "Du kan genkende POKeMON du faar\n"
    .string "ved bytte paa deres ID-numre.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "Det er en Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "Et RPG!\n"
    .string "Der er ikke tid til det!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "Et sportsspil!\n"
    .string "Far vil kunne lide det!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "Et puslespil!\n"
    .string "Ser vanedannende ud!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "Et kaempespil!\n"
    .string "Ser haardt ud!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "3F: TV GAME SHOP$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "Roed og Groen!\n"
    .string "Begge er POKeMON!$"

Text_CounterTeach::
    .string "Aah, hej!\n"
    .string "Jeg er endelig faerdig med POKeMON.\p"
    .string "Ikke faerdig endnu? Skal jeg laere dig\n"
    .string "et godt trick?\p"
    .string "Tricket jeg taenker paa er\n"
    .string "COUNTER.\p"
    .string "Ikke som den jeg laener mig op ad,\n"
    .string "bemaerk!$"

Text_CounterDeclined::
    .string "Du er ikke interesseret? Kom til mig\n"
    .string "hvis du ombestemmer dig.$"

Text_CounterWhichMon::
    .string "Hvilken POKeMON skal jeg laere\n"
    .string "COUNTER?$"

Text_CounterTaught::
    .string "Bruger du det COUNTER-trick\n"
    .string "jeg laerte din POKeMON?$"
