Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "Hej! Husker du mig?\n"
    .string "Jeg er en af PROF. OAKs ASSISTENTER.\p"
    .string "Hvis din POKéDEX har fulde data\n"
    .string "pâ {STR_VAR_1} arter, skal jeg give dig\l"
    .string "en belønning.\p"
    .string "PROF. OAK betrøde mig\n"
    .string "{STR_VAR_2} til dig.\p"
    .string "Sâ, {PLAYER}, lad mig spørge.\p"
    .string "Har du samlet data pâ mindst\n"
    .string "{STR_VAR_1} slags POKéMON?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "Stort! Du har fanget eller ejet\n"
    .string "{STR_VAR_3} slags POKéMON!\p"
    .string "Tillykke!\n"
    .string "Værsgo!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER} modtog {STR_VAR_2}\n"
    .string "fra ASSISTENTEN.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "Der er ting pâ jorden der mâske\n"
    .string "er skjult for synet.\p"
    .string "Brug ITEMFINDER til at opdage\n"
    .string "skjulte ting i nærheden.\p"
    .string "Maskinen er lidt begrænset.\n"
    .string "Den kan ikke pege præcist pâ ting.\p"
    .string "Den viser retningen hvor\n"
    .string "tingen er.\p"
    .string "Brug den til at orientere dig, og\n"
    .string "søg sâ det mistænkte omrâde manuelt.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Lad os se hvad kikkerten viser…\p"
    .string "Et stort POKéMON sover pâ en vej!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "Lad os se hvad kikkerten viser…\p"
    .string "Sikke en betagende udsigt!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "Lad os se hvad kikkerten viser…\p"
    .string "For at nâ LAVENDER TOWN fra\n"
    .string "CERULEAN CITY…\p"
    .string "ROCK TUNNEL ser ud til at være\n"
    .string "en god rute at tage.$"
