Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "Hej! Husker du mig?\n"
    .string "Jeg er en af PROF. OAKs ASSISTENTER.\p"
    .string "Hvis din POKeDEX har fulde data\n"
    .string "paa {STR_VAR_1} arter, skal jeg give dig\l"
    .string "en beloenning.\p"
    .string "PROF. OAK betroede mig\n"
    .string "{STR_VAR_2} til dig.\p"
    .string "Saa, {PLAYER}, lad mig spoerge.\p"
    .string "Har du samlet data paa mindst\n"
    .string "{STR_VAR_1} slags POKeMON?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "Stort! Du har fanget eller ejet\n"
    .string "{STR_VAR_3} slags POKeMON!\p"
    .string "Tillykke!\n"
    .string "Vaersgo!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER} modtog {STR_VAR_2}\n"
    .string "fra ASSISTENTEN.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "Der er ting paa jorden der maaske\n"
    .string "er skjult for synet.\p"
    .string "Brug ITEMFINDER til at opdage\n"
    .string "skjulte ting i naerheden.\p"
    .string "Maskinen er lidt begraenset.\n"
    .string "Den kan ikke pege praecist paa ting.\p"
    .string "Den viser retningen hvor\n"
    .string "tingen er.\p"
    .string "Brug den til at orientere dig, og\n"
    .string "soeg saa det mistaenkte omraade manuelt.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Lad os se hvad kikkerten viser…\p"
    .string "Et stort POKeMON sover paa en vej!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "Lad os se hvad kikkerten viser…\p"
    .string "Sikke en betagende udsigt!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "Lad os se hvad kikkerten viser…\p"
    .string "For at naa LAVENDER TOWN fra\n"
    .string "CERULEAN CITY…\p"
    .string "ROCK TUNNEL ser ud til at vaere\n"
    .string "en god rute at tage.$"
