PewterCity_House1_Text_Nidoran::
    .string "NIDORAN♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "NIDORAN, sid!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Vores POKeMON er en udenforstaaende,\n"
    .string "saa den er kraeven og svaer at haandtere.\p"
    .string "En udenforstaaende er en POKeMON du\n"
    .string "faar ved bytte.\p"
    .string "Den vokser hurtigt, men den kan ignorere\n"
    .string "en uerfaren TRAeNER i kamp.\p"
    .string "Hvis vi bare havde nogle BADGES…$"
