PewterCity_House1_Text_Nidoran::
    .string "NIDORAN♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "NIDORAN, sid!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Vores POKeMON er en udenforstâende,\n"
    .string "sâ den er kräven og svär at hândtere.\p"
    .string "En udenforstâende er en POKeMON du\n"
    .string "fâr ved bytte.\p"
    .string "Den vokser hurtigt, men den kan ignorere\n"
    .string "en uerfaren TRAeNER i kamp.\p"
    .string "Hvis vi bare havde nogle BADGES…$"
