PewterCity_House1_Text_Nidoran::
    .string "NIDORAN♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "NIDORAN, sid!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Vores POKéMON er en udenforstående,\n"
    .string "så den er kræven og svær at håndtere.\p"
    .string "En udenforstående er en POKéMON du\n"
    .string "får ved bytte.\p"
    .string "Den vokser hurtigt, men den kan ignorere\n"
    .string "en uerfaren TRÆNER i kamp.\p"
    .string "Hvis vi bare havde nogle BADGES…$"
