Route13_Text_SebastianIntro::
    .string "Mine fugle-POKéMON vil kæmpe\n"
    .string "mod dig!$"

Route13_Text_SebastianDefeat::
    .string "Mit PIDGEY og PIDGEOTTO combo\n"
    .string "tabte?$"

Route13_Text_SebastianPostBattle::
    .string "Mine POKéMON ser glade ud selv om\n"
    .string "de tabte.$"

Route13_Text_SusieIntro::
    .string "Jeg har fâet at vide at jeg er god\n"
    .string "til et barn.$"

Route13_Text_SusieDefeat::
    .string "Aah!\n"
    .string "Jeg tabte!$"

Route13_Text_SusiePostBattle::
    .string "Jeg vil blive en god TRAINER.\n"
    .string "Jeg træner hârdt, bare se.$"

Route13_Text_ValerieIntro::
    .string "Wow!\n"
    .string "Dine BADGES er for seje!$"

Route13_Text_ValerieDefeat::
    .string "Ikke nok!$"

Route13_Text_ValeriePostBattle::
    .string "Du fik de BADGES fra GYM\n"
    .string "LEADERS. Det ved jeg!$"

Route13_Text_GwenIntro::
    .string "Mine søde POKéMON vil gerne lære\n"
    .string "dig at kende.$"

Route13_Text_GwenDefeat::
    .string "Godt gâet!\n"
    .string "Du vandt totalt!$"

Route13_Text_GwenPostBattle::
    .string "Man skal lade POKéMON kæmpe for\n"
    .string "at stærke dem.$"

Route13_Text_AlmaIntro::
    .string "Jeg fandt CARBOS i en grotte engang\n"
    .string "da jeg udforskede huler.$"

Route13_Text_AlmaDefeat::
    .string "Aa, for dârligt!\n"
    .string "Jeg rodede det bare til!$"

Route13_Text_AlmaPostBattle::
    .string "CARBOS bøde HASTIGHEDEN af mine\n"
    .string "POKéMON.$"

Route13_Text_PerryIntro::
    .string "Jeg tænker ikke at tabe.\n"
    .string "Ikke nâr vinden blæser min vej!$"

Route13_Text_PerryDefeat::
    .string "Vinden vendte!$"

Route13_Text_PerryPostBattle::
    .string "Jeg er slâet.\n"
    .string "Jeg flyver hjem, tror jeg.$"

Route13_Text_LolaIntro::
    .string "Selvfølgelig leger jeg med dig,\n"
    .string "skat.$"

Route13_Text_LolaDefeat::
    .string "Aa!\n"
    .string "Dit lille uhyre!$"

Route13_Text_LolaPostBattle::
    .string "Jeg spekulerer pâ hvem der er\n"
    .string "stærkest, han eller hun POKéMON?$"

Route13_Text_SheilaIntro::
    .string "Vil du kæmpe med nogle\n"
    .string "POKéMON mod mig?$"

Route13_Text_SheilaDefeat::
    .string "Er det allerede slut?$"

Route13_Text_SheilaPostBattle::
    .string "Jeg ved faktisk ikke noget om\n"
    .string "POKéMON.\p"
    .string "Dem jeg bruger... jeg valgte dem\n"
    .string "for deres udseende!$"

Route13_Text_JaredIntro::
    .string "Hvad glor du pâ?$"

Route13_Text_JaredDefeat::
    .string "Pokker!\n"
    .string "Gâr i stâ!$"

Route13_Text_JaredPostBattle::
    .string "Forsvind!$"

Route13_Text_RobertIntro::
    .string "Jeg bruger altid fugle-POKéMON.\n"
    .string "Jeg har viet mig til dem.$"

Route13_Text_RobertDefeat::
    .string "Strømmen er slukket!$"

Route13_Text_RobertPostBattle::
    .string "Jeg ville ønske jeg kunne flyve som\n"
    .string "PIDGEY og PIDGEOTTO...$"

Route13_Text_LookToLeftOfThatPost::
    .string "TRAINER TIPS\p"
    .string "Se, se!\n"
    .string "Kig til venstre for det stolpe!$"

Route13_Text_SelectToSwitchItems::
    .string "TRAINER TIPS\p"
    .string "Brug SELECT til at skifte genstande\n"
    .string "i GENSTANDE-vinduet.$"

Route13_Text_RouteSign::
    .string "ROUTE 13\n"
    .string "Nord til SILENCE BRIDGE$"
