Route13_Text_SebastianIntro::
    .string "Mine fugle-POKeMON vil kaempe\n"
    .string "mod dig!$"

Route13_Text_SebastianDefeat::
    .string "Mit PIDGEY og PIDGEOTTO combo\n"
    .string "tabte?$"

Route13_Text_SebastianPostBattle::
    .string "Mine POKeMON ser glade ud selv om\n"
    .string "de tabte.$"

Route13_Text_SusieIntro::
    .string "Jeg har faaet at vide at jeg er god\n"
    .string "til et barn.$"

Route13_Text_SusieDefeat::
    .string "Aah!\n"
    .string "Jeg tabte!$"

Route13_Text_SusiePostBattle::
    .string "Jeg vil blive en god TRAINER.\n"
    .string "Jeg traener haardt, bare se.$"

Route13_Text_ValerieIntro::
    .string "Wow!\n"
    .string "Dine BADGES er for seje!$"

Route13_Text_ValerieDefeat::
    .string "Ikke nok!$"

Route13_Text_ValeriePostBattle::
    .string "Du fik de BADGES fra GYM\n"
    .string "LEADERS. Det ved jeg!$"

Route13_Text_GwenIntro::
    .string "Mine soede POKeMON vil gerne laere\n"
    .string "dig at kende.$"

Route13_Text_GwenDefeat::
    .string "Godt gaaet!\n"
    .string "Du vandt totalt!$"

Route13_Text_GwenPostBattle::
    .string "Man skal lade POKeMON kaempe for\n"
    .string "at staerke dem.$"

Route13_Text_AlmaIntro::
    .string "Jeg fandt CARBOS i en grotte engang\n"
    .string "da jeg udforskede huler.$"

Route13_Text_AlmaDefeat::
    .string "Aa, for daarligt!\n"
    .string "Jeg rodede det bare til!$"

Route13_Text_AlmaPostBattle::
    .string "CARBOS boede HASTIGHEDEN af mine\n"
    .string "POKeMON.$"

Route13_Text_PerryIntro::
    .string "Jeg taenker ikke at tabe.\n"
    .string "Ikke naar vinden blaeser min vej!$"

Route13_Text_PerryDefeat::
    .string "Vinden vendte!$"

Route13_Text_PerryPostBattle::
    .string "Jeg er slaaet.\n"
    .string "Jeg flyver hjem, tror jeg.$"

Route13_Text_LolaIntro::
    .string "Selvfoelgelig leger jeg med dig,\n"
    .string "skat.$"

Route13_Text_LolaDefeat::
    .string "Aa!\n"
    .string "Dit lille uhyre!$"

Route13_Text_LolaPostBattle::
    .string "Jeg spekulerer paa hvem der er\n"
    .string "staerkest, han eller hun POKeMON?$"

Route13_Text_SheilaIntro::
    .string "Vil du kaempe med nogle\n"
    .string "POKeMON mod mig?$"

Route13_Text_SheilaDefeat::
    .string "Er det allerede slut?$"

Route13_Text_SheilaPostBattle::
    .string "Jeg ved faktisk ikke noget om\n"
    .string "POKeMON.\p"
    .string "Dem jeg bruger... jeg valgte dem\n"
    .string "for deres udseende!$"

Route13_Text_JaredIntro::
    .string "Hvad glor du paa?$"

Route13_Text_JaredDefeat::
    .string "Pokker!\n"
    .string "Gaar i staa!$"

Route13_Text_JaredPostBattle::
    .string "Forsvind!$"

Route13_Text_RobertIntro::
    .string "Jeg bruger altid fugle-POKeMON.\n"
    .string "Jeg har viet mig til dem.$"

Route13_Text_RobertDefeat::
    .string "Stroemmen er slukket!$"

Route13_Text_RobertPostBattle::
    .string "Jeg ville oenske jeg kunne flyve som\n"
    .string "PIDGEY og PIDGEOTTO...$"

Route13_Text_LookToLeftOfThatPost::
    .string "TRAINER TIPS\p"
    .string "Se, se!\n"
    .string "Kig til venstre for det stolpe!$"

Route13_Text_SelectToSwitchItems::
    .string "TRAINER TIPS\p"
    .string "Brug SELECT til at skifte genstande\n"
    .string "i GENSTANDE-vinduet.$"

Route13_Text_RouteSign::
    .string "ROUTE 13\n"
    .string "Nord til SILENCE BRIDGE$"
