VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .string "Selv pâ samme niveau kan\n"
    .string "POKéMON have meget forskellige\l"
    .string "statistikker og evner.\p"
    .string "En POKéMON opfostret af en TRÆNER er\n"
    .string "stärkere end en i naturen.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .string "Min POKéMON blev forgiftet!\n"
    .string "Den besvimede mens vi gik!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .string "Det er sandt at en POKéMON pâ höjere\n"
    .string "niveau vil väre kraftigere…\p"
    .string "Men alle POKéMON har svagheder\n"
    .string "mod bestemte typer.\p"
    .string "Sâ der ser ikke ud til at väre nogen\n"
    .string "universelt stärk POKéMON.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .string "Trangen til at kämpe med en du\n"
    .string "har mödt för…\p"
    .string "Har du nogensinde haft den trang?\n"
    .string "Det er jeg sikker pâ du har.\p"
    .string "Jeg ville ogsâ kämpe mod visse\n"
    .string "mennesker igen og igen.\p"
    .string "Sâ jeg har givet disse väk.\n"
    .string "Tag venligst en!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .string "Brug den enhed og du finder\n"
    .string "TRÆNERE der leder efter en revanche.\p"
    .string "Du skal lade dens batteri op for at\n"
    .string "bruge den, dog.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .string "Hvordan bruger du VS SEEKER?\n"
    .string "Det er ikke svärt.\p"
    .string "Brug den bip-bip-bip, og\n"
    .string "TRÆNERE omkring dig vil lägge märke til det.\p"
    .string "Hvis en TRÆNER vil have revanche,\n"
    .string "giver den dig besked med det samme.\p"
    .string "Lad batteriet op og brug den\n"
    .string "nâr du er pâ vej.$"
