ViridianCity_Text_CanCarryMonsAnywhere::
    .string "De POKe BALLS ved din talje!\n"
    .string "Du har POKéMON, ikke?\p"
    .string "Det er fedt at du kan bäre og\n"
    .string "bruge POKéMON nâr som helst, overalt.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Dette POKéMON GYM er altid lukket.\p"
    .string "Jeg spekulerer pâ hvem LEDEREN er?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VIRIDIAN GYMs LEDER er vendt tilbage!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "Vil du vide om de to slags\n"
    .string "larve-POKéMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Aah, okay sâ!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE har ikke gift,\n"
    .string "men WEEDLE har.\p"
    .string "Pas pâ at dine POKéMON ikke bliver\n"
    .string "stukket af WEEDLEs POISON STING.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Aah, Bedstefar!\n"
    .string "Vär ikke sâ led!\p"
    .string "Undskyld.\n"
    .string "Han har ikke haft sin kaffe endnu.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "Jeg handler i PEWTER CITY\n"
    .string "nu og da.\p"
    .string "Jeg skal gennem den snöde sti i\n"
    .string "VIRIDIAN FOREST nâr jeg gör det.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "Jeg forbyder dig bestemt at\n"
    .string "gâ igennem her!\p"
    .string "Dette er privat ejendom!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Nâ, nu har jeg haft min kaffe, og\n"
    .string "det er hvad jeg skal bruge for at komme i gang!\p"
    .string "Hm?\n"
    .string "Hvad er den röde boks du har?\p"
    .string "Ah, sâ du arbejder pâ din\n"
    .string "POKéDEX.\p"
    .string "Sâ lad mig give dig et râd.\p"
    .string "Nâr du fanger en POKéMON,\n"
    .string "opdaterer POKéDEX automatisk\l"
    .string "sine data.\p"
    .string "…Du ved ikke hvordan man fanger\n"
    .string "en POKéMON?\p"
    .string "Sâ mâ jeg vel vise dig det!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "Sâ! Sig mig, det var lärerigt,\n"
    .string "var det ikke?\p"
    .string "Og her, tag ogsâ dette.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "Hvis der er noget du ikke\n"
    .string "forstâr, se det der.\p"
    .string "Det lärer dig grundläggende om\n"
    .string "at väre en POKéMON TRÆNER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Nâ, nu har jeg haft min kaffe, og\n"
    .string "det er hvad jeg skal bruge for at komme i gang!\p"
    .string "Men jeg lavede den for stärk.\n"
    .string "Den gav mig hovedpine…\p"
    .string "For resten, fylder du din\n"
    .string "POKéDEX?\p"
    .string "Fokuser först pâ at sväkke\n"
    .string "POKéMON för du pröver at fange den.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Nâ, nu har jeg haft min kaffe, og\n"
    .string "det er hvad jeg skal bruge for at komme i gang!\p"
    .string "Men jeg lavede den for stärk.\n"
    .string "Den gav mig hovedpine…\p"
    .string "For resten, hjälper mit gamle TEACHY TV\n"
    .string "dig?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "Det er min barnebarn i showet!\p"
    .string "Nâr han er den der underviser,\n"
    .string "er du bundet til at läre.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… Du er for optaget til ikke engang\n"
    .string "at have tid til TEACHY TV…\p"
    .string "Tid er penge, og ingen af delene bör\n"
    .string "spildes…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY \n"
    .string "Det evigt grönne paradis$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TRÆNER TIPS\p"
    .string "Fang POKéMON og udvid din\n"
    .string "samling.\p"
    .string "Jo flere du har, jo lettere er det\n"
    .string "at kämpe.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TRÆNER TIPS\p"
    .string "Kampbevägelserne af POKéMON er\n"
    .string "begränsede af deres POWER POINTS, PP.\p"
    .string "For at genopfriske PP, lad dine trätte\n"
    .string "POKéMON hvile pâ et POKéMON CENTER.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN GYMs döre er lâst…$"

