ViridianCity_Text_CanCarryMonsAnywhere::
    .string "De POKe BALLS ved din talje!\n"
    .string "Du har POKeMON, ikke?\p"
    .string "Det er fedt at du kan baere og\n"
    .string "bruge POKeMON naar som helst, overalt.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Dette POKeMON GYM er altid lukket.\p"
    .string "Jeg spekulerer paa hvem LEDEREN er?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VIRIDIAN GYMs LEDER er vendt tilbage!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "Vil du vide om de to slags\n"
    .string "larve-POKeMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Aah, okay saa!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE har ikke gift,\n"
    .string "men WEEDLE har.\p"
    .string "Pas paa at dine POKeMON ikke bliver\n"
    .string "stukket af WEEDLEs POISON STING.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Aah, Bedstefar!\n"
    .string "Vaer ikke saa led!\p"
    .string "Undskyld.\n"
    .string "Han har ikke haft sin kaffe endnu.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "Jeg handler i PEWTER CITY\n"
    .string "nu og da.\p"
    .string "Jeg skal gennem den snoede sti i\n"
    .string "VIRIDIAN FOREST naar jeg goer det.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "Jeg forbyder dig bestemt at\n"
    .string "gaa igennem her!\p"
    .string "Dette er privat ejendom!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Naa, nu har jeg haft min kaffe, og\n"
    .string "det er hvad jeg skal bruge for at komme i gang!\p"
    .string "Hm?\n"
    .string "Hvad er den roede boks du har?\p"
    .string "Ah, saa du arbejder paa din\n"
    .string "POKeDEX.\p"
    .string "Saa lad mig give dig et raad.\p"
    .string "Naar du fanger en POKeMON,\n"
    .string "opdaterer POKeDEX automatisk\l"
    .string "sine data.\p"
    .string "…Du ved ikke hvordan man fanger\n"
    .string "en POKeMON?\p"
    .string "Saa maa jeg vel vise dig det!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "Saa! Sig mig, det var laererigt,\n"
    .string "var det ikke?\p"
    .string "Og her, tag ogsaa dette.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "Hvis der er noget du ikke\n"
    .string "forstaar, se det der.\p"
    .string "Det laerer dig grundlaeggende om\n"
    .string "at vaere en POKeMON TRAeNER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Naa, nu har jeg haft min kaffe, og\n"
    .string "det er hvad jeg skal bruge for at komme i gang!\p"
    .string "Men jeg lavede den for staerk.\n"
    .string "Den gav mig hovedpine…\p"
    .string "For resten, fylder du din\n"
    .string "POKeDEX?\p"
    .string "Fokuser foerst paa at svaekke\n"
    .string "POKeMON foer du proever at fange den.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Naa, nu har jeg haft min kaffe, og\n"
    .string "det er hvad jeg skal bruge for at komme i gang!\p"
    .string "Men jeg lavede den for staerk.\n"
    .string "Den gav mig hovedpine…\p"
    .string "For resten, hjaelper mit gamle TEACHY TV\n"
    .string "dig?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "Det er min barnebarn i showet!\p"
    .string "Naar han er den der underviser,\n"
    .string "er du bundet til at laere.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… Du er for optaget til ikke engang\n"
    .string "at have tid til TEACHY TV…\p"
    .string "Tid er penge, og ingen af delene boer\n"
    .string "spildes…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY \n"
    .string "Det evigt groenne paradis$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TRAeNER TIPS\p"
    .string "Fang POKeMON og udvid din\n"
    .string "samling.\p"
    .string "Jo flere du har, jo lettere er det\n"
    .string "at kaempe.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TRAeNER TIPS\p"
    .string "Kampbevaegelserne af POKeMON er\n"
    .string "begraensede af deres POWER POINTS, PP.\p"
    .string "For at genopfriske PP, lad dine traette\n"
    .string "POKeMON hvile paa et POKeMON CENTER.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN CITY POKeMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN GYMs doere er laast…$"

