@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach::
    .string "Klar?\n"
    .string "Boing!\p"
    .string "Vi har en BODY SLAM-kamp for at\n"
    .string "se hvem der giver op först.\p"
    .string "Hvis du deltog, ville du blive\n"
    .string "mast som en bille…\p"
    .string "Hvad med at jeg lärer BODY SLAM\n"
    .string "til en af dine POKéMON i stedet?$"

Text_BodySlamDeclined::
    .string "Kom igen!\n"
    .string "Boing!$"

Text_BodySlamWhichMon::
    .string "Hvilken POKéMON vil läre at\n"
    .string "bruge BODY SLAM?$"

Text_BodySlamTaught::
    .string "Boioing!$"

FourIsland_House1_Text_FatMan::
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "Der er en själden slags IS-\n"
    .string "POKéMON der lever i hulen.\p"
    .string "Vi fâr mange besögende der\n"
    .string "hâber at se den POKéMON.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "Øh? Et POKéMON-ÆG?\n"
    .string "…Jeg har ingen anelse.\p"
    .string "…Øh, vent. DAY-CARE-folkene i\n"
    .string "byen sagde noget.\p"
    .string "De sagde at de havde fundet ÆG\n"
    .string "för pâ deres grund.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .string "Hvad er det her?\p"
    .string "Det nye POKéMON JOURNAL er ikke\n"
    .string "ankommet til denne ö?$"

