@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach::
    .string "Klar?\n"
    .string "Boing!\p"
    .string "Vi har en BODY SLAM-kamp for at\n"
    .string "se hvem der giver op foerst.\p"
    .string "Hvis du deltog, ville du blive\n"
    .string "mast som en bille…\p"
    .string "Hvad med at jeg laerer BODY SLAM\n"
    .string "til en af dine POKeMON i stedet?$"

Text_BodySlamDeclined::
    .string "Kom igen!\n"
    .string "Boing!$"

Text_BodySlamWhichMon::
    .string "Hvilken POKeMON vil laere at\n"
    .string "bruge BODY SLAM?$"

Text_BodySlamTaught::
    .string "Boioing!$"

FourIsland_House1_Text_FatMan::
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "Der er en sjaelden slags IS-\n"
    .string "POKeMON der lever i hulen.\p"
    .string "Vi faar mange besoegende der\n"
    .string "haaber at se den POKeMON.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "Oeh? Et POKeMON-AeG?\n"
    .string "…Jeg har ingen anelse.\p"
    .string "…Oeh, vent. DAY-CARE-folkene i\n"
    .string "byen sagde noget.\p"
    .string "De sagde at de havde fundet AeG\n"
    .string "foer paa deres grund.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .string "Hvad er det her?\p"
    .string "Det nye POKeMON JOURNAL er ikke\n"
    .string "ankommet til denne oe?$"

