CeruleanCity_House4_Text_NothingEntertaining::
    .string "Suk…\n"
    .string "For meget tid, for lidt at göre…\p"
    .string "Sker der ikke noget underholdende\n"
    .string "nogen steder?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
    .string "Ah!\n"
    .string "En ny nyhedsrapport!\p"
    .string "Hmm…\p"
    .string "Jeg forstâr!\n"
    .string "Det var ret informativt!\p"
    .string "Jeg roser dig for at vise interesse\n"
    .string "for nyheder i din unge alder.\p"
    .string "Som tak for at dele nyhederne\n"
    .string "med mig, vil jeg give dig dette.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
    .string "Oh, oh!\n"
    .string "D-denne nyhedsrapport!\p"
    .string "Hmm…\p"
    .string "Fantastisk!\n"
    .string "Hvilken utrolig nyhed!\p"
    .string "Jeg har ikke set en nyhedshistorie sâ\n"
    .string "utrolig i for lang tid!\p"
    .string "Tak for at dele denne fantastiske\n"
    .string "nyhed. Her er en masse BERRIES!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
    .string "Det virker sâ sörgeligt at ikke dele\n"
    .string "denne nyhed med andre…\p"
    .string "Jeg ville önske jeg kunne fortälle nogen…\n"
    .string "Lad andre vide nyheden…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
    .string "Ah, du har spredt nyheden for mig?\p"
    .string "Gode nyheder bliver värdifulde nâr\n"
    .string "alle slags mennesker deler dem.\p"
    .string "Som tak for at du spredte\n"
    .string "nyheden, tag dette!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
    .string "Du har spredt nyheden mere?\n"
    .string "Storslâet!\p"
    .string "Den nyhed mâ väre glad for\n"
    .string "at blive delt sâ meget.\p"
    .string "Ja, sandelig!\p"
    .string "Betragt dette som et tegn pâ\n"
    .string "pâskönnelse fra mig og nyheden.\p"
    .string "Jeg giver dig flere BERRIES end\n"
    .string "jeg normalt gör.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
    .string "Jeg nyder mig selv med alle\n"
    .string "slags nyheder.\p"
    .string "Ja, jeg er tilfreds!\n"
    .string "Jeg keder mig ikke lige forelöbigt.$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
    .string "Hm? Din BERRY POUCH er fuld.\n"
    .string "Min gave forbliver ugiven, sâ.$"
