VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Hej!\n"
	.string "Har du en {STR_VAR_1}?\p"
	.string "Vil du bytte den til min\n"
	.string "{STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "Det var ærgerligt.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "…Det her er ikke en {STR_VAR_1}.\p"
	.string "Hvis du fâr en, sâ byt den venligst\n"
	.string "til mig!$"

VermilionCity_House2_Text_ThankYou::
	.string "Tak!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "Hvordan har min gamle {STR_VAR_2} det?\p"
	.string "Min {STR_VAR_1} har det fantastisk!$"
