CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "Jeg fik min KOFFING i CINNABAR.\p"
    .string "Den er som regel venlig, men den aander\n"
    .string "gift naar den er vred.$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "Heheh! Denne GYM er fantastisk!\n"
    .string "Den er fuld af kvinder!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "CELADON er stolt af sine bestraebelser\n"
    .string "paa at holde byen smuk.\p"
    .string "Derfor er den nye GAME CORNER\n"
    .string "daarlig for vores byens image.$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Stoen…\n"
    .string "Jeg tabte det hele ved spilleautomaterne!\p"
    .string "Jeg vidste jeg skulle have indloest mine\n"
    .string "COINS for praemier!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "Dette er min pal, POLIWRATH.\p"
    .string "Den udviklede sig fra en POLIWHIRL da\n"
    .string "jeg brugte en WATER STONE.$"

CeladonCity_Text_Poliwrath::
    .string "POLIWRATH: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "Hvad glor du paa?\n"
    .string "Forsvind, ellers slaaer jeg dig.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "Hold dig ude af TEAM ROCKETs vej!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "TRAINER TIPS\p"
    .string "X ACCURACY oeger praecisionen af\n"
    .string "teknikker.\p"
    .string "DIRE HIT oeger sandsynligheden for\n"
    .string "kritiske traef.\p"
    .string "Koeb dine ting i CELADON\n"
    .string "DEPT. STORE!$"

CeladonCity_Text_CitySign::
    .string "CELADON CITY\n"
    .string "Regnbuens Drommes By$"

CeladonCity_Text_GymSign::
    .string "CELADON CITY POKeMON GYM\n"
    .string "LEADER: ERIKA\l"
    .string "Den Naturkaerlige Prinsesse!$"

CeladonCity_Text_MansionSign::
    .string "CELADON MANSION$"

CeladonCity_Text_DeptStoreSign::
    .string "Find hvad du har brug for i\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "TRAINER TIPS\p"
    .string "GUARD SPEC. beskytter POKeMON\n"
    .string "mod status-reduktions-trin under\l"
    .string "kamp.\p"
    .string "Koeb dine ting i\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "COINS indloeses for praemier!\n"
    .string "PRAEMIE UDSTYNNING$"

CeladonCity_Text_GameCornerSign::
    .string "ROCKET GAME CORNER\n"
    .string "Legepladsen for voksne!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Aaaagh, av…\n"
    .string "Jeg braendte min tunge!\p"
    .string "Den rare gamle dame i MANSION\n"
    .string "gav mig noget TEA.\p"
    .string "Men det var kogende varmt!\n"
    .string "Skal afkoele det for at drikke det.$"

Text_SoftboiledTeach::
    .string "Hej der!\p"
    .string "Jeg har set dig, men jeg fik aldrig\n"
    .string "en chance for at snakke.\p"
    .string "Det maa vaere held der bragte\n"
    .string "os sammen endelig.\p"
    .string "Jeg vil fejre det ved at laere dig\n"
    .string "tricket SOFTBOILED.$"

Text_SoftboiledDeclined::
    .string "Jeg vil altid holde oje med dig.\p"
    .string "Jeg haaber vi kan snakke igen.$"

Text_SoftboiledWhichMon::
    .string "Sa hvem er den POKeMON der faar\n"
    .string "chancen for at laere SOFTBOILED?$"

Text_SoftboiledTaught::
    .string "Jeg oensker dig al mulig held!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Aah, hvad skal jeg goere…\p"
    .string "Nogen stjal vores SILPH SCOPE.\p"
    .string "Tyven kom lobende denne vej,\n"
    .string "det er jeg sikker paa.\p"
    .string "Men jeg mistede ham af syne!\n"
    .string "Hvor gik han hen?$"
