CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "Jeg fik min KOFFING i CINNABAR.\p"
    .string "Den er som regel venlig, men den ânder\n"
    .string "gift nâr den er vred.$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "Heheh! Denne GYM er fantastisk!\n"
    .string "Den er fuld af kvinder!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "CELADON er stolt af sine besträbelser\n"
    .string "pâ at holde byen smuk.\p"
    .string "Derfor er den nye GAME CORNER\n"
    .string "dârlig for vores byens image.$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Stön…\n"
    .string "Jeg tabte det hele ved spilleautomaterne!\p"
    .string "Jeg vidste jeg skulle have indlöst mine\n"
    .string "COINS for prämier!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "Dette er min pal, POLIWRATH.\p"
    .string "Den udviklede sig fra en POLIWHIRL da\n"
    .string "jeg brugte en WATER STONE.$"

CeladonCity_Text_Poliwrath::
    .string "POLIWRATH: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "Hvad glor du pâ?\n"
    .string "Forsvind, ellers slâer jeg dig.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "Hold dig ude af TEAM ROCKETs vej!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "TRAINER TIPS\p"
    .string "X ACCURACY öger präcisionen af\n"
    .string "teknikker.\p"
    .string "DIRE HIT öger sandsynligheden for\n"
    .string "kritiske träf.\p"
    .string "Köb dine ting i CELADON\n"
    .string "DEPT. STORE!$"

CeladonCity_Text_CitySign::
    .string "CELADON CITY\n"
    .string "Regnbuens Drommes By$"

CeladonCity_Text_GymSign::
    .string "CELADON CITY POKéMON GYM\n"
    .string "LEADER: ERIKA\l"
    .string "Den Naturkärlige Prinsesse!$"

CeladonCity_Text_MansionSign::
    .string "CELADON MANSION$"

CeladonCity_Text_DeptStoreSign::
    .string "Find hvad du har brug for i\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "TRAINER TIPS\p"
    .string "GUARD SPEC. beskytter POKéMON\n"
    .string "mod status-reduktions-trin under\l"
    .string "kamp.\p"
    .string "Köb dine ting i\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "COINS indlöses for prämier!\n"
    .string "PRÄMIE UDSTYNNING$"

CeladonCity_Text_GameCornerSign::
    .string "ROCKET GAME CORNER\n"
    .string "Legepladsen for voksne!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Aâagh, av…\n"
    .string "Jeg brändte min tunge!\p"
    .string "Den rare gamle dame i MANSION\n"
    .string "gav mig noget TEA.\p"
    .string "Men det var kogende varmt!\n"
    .string "Skal afköle det for at drikke det.$"

Text_SoftboiledTeach::
    .string "Hej der!\p"
    .string "Jeg har set dig, men jeg fik aldrig\n"
    .string "en chance for at snakke.\p"
    .string "Det mâ väre held der bragte\n"
    .string "os sammen endelig.\p"
    .string "Jeg vil fejre det ved at läre dig\n"
    .string "tricket SOFTBOILED.$"

Text_SoftboiledDeclined::
    .string "Jeg vil altid holde oje med dig.\p"
    .string "Jeg hâber vi kan snakke igen.$"

Text_SoftboiledWhichMon::
    .string "Sa hvem er den POKéMON der fâr\n"
    .string "chancen for at läre SOFTBOILED?$"

Text_SoftboiledTaught::
    .string "Jeg önsker dig al mulig held!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Aah, hvad skal jeg göre…\p"
    .string "Nogen stjal vores SILPH SCOPE.\p"
    .string "Tyven kom lobende denne vej,\n"
    .string "det er jeg sikker pâ.\p"
    .string "Men jeg mistede ham af syne!\n"
    .string "Hvor gik han hen?$"
