ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hej!\n"
    .string "Du kom fra PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "Du kender PROF. OAK, ikke?\p"
    .string "Hans ordre kom ind.\n"
    .string "Kan du bringe den til ham?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} modtog OAKS PAKKEN\n"
    .string "fra POKeMON MART ekspeditricen.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay, tak! Sig hej til\n"
    .string "PROF. OAK fra mig, ogsâ.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "Denne butik sälger godt i\n"
    .string "ANTIDOTES, har jeg hört.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "Jeg skal köbe nogle POTIONS.\p"
    .string "Man ved aldrig hvornâr dine POKeMON\n"
    .string "fâr brug for hurtig helbredelse.$"

