ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hej!\n"
    .string "Du kom fra PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "Du kender PROF. OAK, ikke?\p"
    .string "Hans ordre kom ind.\n"
    .string "Kan du bringe den til ham?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} modtog OAKS PAKKEN\n"
    .string "fra POKeMON MART ekspeditricen.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay, tak! Sig hej til\n"
    .string "PROF. OAK fra mig, ogsaa.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "Denne butik saelger godt i\n"
    .string "ANTIDOTES, har jeg hoert.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "Jeg skal koebe nogle POTIONS.\p"
    .string "Man ved aldrig hvornaar dine POKeMON\n"
    .string "faar brug for hurtig helbredelse.$"

