VermilionCity_Gym_Text_LtSurgeIntro::
    .string "Hey, unge! Hvad tror du du laver\n"
    .string "her?\p"
    .string "Du overlever ikke laenge i kamp!\n"
    .string "Ikke med din svage styrke!\p"
    .string "Jeg siger dig, unge, elektriske POKeMON\n"
    .string "reddede mig under krigen!\p"
    .string "De chokkede mine fjender til\n"
    .string "lammelse!\p"
    .string "Det samme goer jeg ved dig!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "Et lille ord af raad, unge!\p"
    .string "Elektricitet er virkelig kraftfuld!\p"
    .string "Men den er nytteloes mod JORD-\n"
    .string "type POKeMON!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "THUNDERBADGE oeger din\n"
    .string "POKeMONs HASTIGHED!\p"
    .string "Den lader ogsaa din POKeMON FLYVE\n"
    .string "lynhurtigt naar som helst, unge!\p"
    .string "Du er speciel, unge!\n"
    .string "Tag dette!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} modtog TM34\n"
    .string "fra LT. SURGE.$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "TM34 indeholder SHOCK WAVE!\p"
    .string "Laer det til en ELEKTRISK POKeMON!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Yo, unge, goer plads i din TASKE!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Det var en choker!\p"
    .string "Du er den rigtige vare, unge!\p"
    .string "Okay, saa tag THUNDERBADGE!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "Da jeg var i haeren, var LT. SURGE\n"
    .string "min strenge befalingsmand.\p"
    .string "Han var en haard taskmaster.$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Stop!\n"
    .string "Du er meget dygtig!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "Det er ikke nemt at aabne den doer.\p"
    .string "LT. SURGE var altid beroemt for\n"
    .string "sin forsigtige natur i haeren.$"

VermilionCity_Gym_Text_BailyIntro::
    .string "Jeg er letvaegts, men jeg er god\n"
    .string "med elektricitet!\p"
    .string "Derfor sluttede jeg mig til dette GYM.$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Stegt!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Okay, jeg snakker!\p"
    .string "LT. SURGE sagde han gemte doer-\n"
    .string "kontakter inde i noget.$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "Dette er ikke et sted for boern!\n"
    .string "Ikke engang hvis du er god!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Wow!\n"
    .string "Overraskede mig!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "LT. SURGE installerede faeldrene i\n"
    .string "GYM selv.\p"
    .string "Han satte dobbelte laase overalt.\n"
    .string "Lad mig give dig et tip.\p"
    .string "Naar du aabner den foerste laas, er\n"
    .string "den anden laas lige ved siden af.$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champion i gaere!\p"
    .string "LT. SURGE har et oegenavn.\p"
    .string "Folk kalder ham\n"
    .string "den amerikanske lynkaster!\p"
    .string "Han er ekspert i elektriske\n"
    .string "POKeMON.\p"
    .string "FUGL/VAND-type POKeMON matcher\n"
    .string "daarligt mod ELEKTRISK type.\p"
    .string "Pas ogsaa paa lammelse.\p"
    .string "LT. SURGE er meget forsigtig.\p"
    .string "Han har laast sig selv inde, saa det bliver\n"
    .string "ikke nemt at komme til ham.$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "Puha!\n"
    .string "Den kamp var elektrisk!$"

VermilionCity_Gym_Text_GymStatue::
    .string "VERMILION POKeMON GYM\n"
    .string "LEDER: LT. SURGE\p"
    .string "VINDENDE TRAeNERE:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "VERMILION POKeMON GYM\n"
    .string "LEDER: LT. SURGE\p"
    .string "VINDENDE TRAeNERE:\n"
    .string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "Nix!\n"
    .string "Der er kun affald her.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Hey! Der er en kontakt under\n"
    .string "affaldet! Taend den!\p"
    .string "Den foerste elektriske laas aabnede!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "Hey! Der er endnu en kontakt i\n"
    .string "affaldet! Tryk paa den!\p"
    .string "… Klik!$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "Den anden elektriske laas aabnede!\n"
    .string "Motordoeren aabnede!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Nix!\n"
    .string "Der er kun affald her.\p"
    .string "Hey!\n"
    .string "De elektriske laase blev nulstillet!$"

