FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "Velkommen til SAFARI ZONE!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "For kun ¥500 kan du spille\n"
    .string "SAFARI GAME.\p"
    .string "Du kan vandre i det vidtstrakte\n"
    .string "safari og fange hvad du vil.\p"
    .string "Vil du spille?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "Det bliver ¥500!\p"
    .string "Vi bruger kun en særlig slags\n"
    .string "POKe BALLS her.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "{PLAYER} modtog 30 SAFARI BALLS\n"
    .string "fra betjenten.$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "Vi kalder dig pâ højtaleren nâr du\n"
    .string "løber tør for tid eller SAFARI BALLS.\p"
    .string "Jeg ønsker dig held og lykke!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "Okay.\n"
    .string "Kom igen!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "Ups!\n"
    .string "Ikke nok penge!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "Vil du forlade SAFARI ZONE\n"
    .string "tidligt?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "Returner venligst eventuelle\n"
    .string "SAFARI BALLS du har til overs.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "Held og lykke!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "Fangede du din andel?\n"
    .string "Kom igen!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "Hej! Er det din første gang her i\n"
    .string "SAFARI ZONE?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "SAFARI ZONE har faktisk fire\n"
    .string "zoner.\p"
    .string "Hver zone har forskellige POKéMON,\n"
    .string "ogsâ nogle sjælde.\p"
    .string "Brug de udleverede SAFARI BALLS\n"
    .string "til at fange dem.\p"
    .string "Du kan ogsâ kaste BAIT eller\n"
    .string "STEN udover SAFARI BALLS.\p"
    .string "Kaster du BAIT, bliver POKéMON\n"
    .string "mindre tilbøjelig til at flygte, men\l"
    .string "sværere at fange.\p"
    .string "Kaster du STEN, bliver POKéMON\n"
    .string "mere tilbøjelig til at flygte, men\l"
    .string "lettere at fange.\p"
    .string "Nâr du løber tør for tid eller\n"
    .string "SAFARI BALLS, er spillet slut!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "Beklager, du er stamgæst her!$"

