SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .string "Hva?\n"
    .string "Du…$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .string "Er du maaske…\n"
    .string "… …\p"
    .string "Det er dig!\n"
    .string "Du er {PLAYER}!\p"
    .string "Vi talte lige om dig!\p"
    .string "Vi talte om at en utroligt god\n"
    .string "TRAINER var dukket op.\p"
    .string "Og den person er dig!\n"
    .string "Du er saa sej!\p"
    .string "Saa vi besluttede at vi bliver\n"
    .string "din FAN CLUB!\p"
    .string "Vi haaber alle at du bliver ved med at\n"
    .string "kaempe og vise os hvor sej du er.\p"
    .string "Saadan vil andre maaske blive\n"
    .string "fans ligesom mig.$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .string "Jeg hepper altid paa dig!\p"
    .string "Kom saa, {PLAYER}, kom saa!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .string "Jeg tror altid paa dig,\n"
    .string "{PLAYER}.\p"
    .string "Vis de andre venligst hvad du er\n"
    .string "for en naar du kaemper alvorligt.$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .string "Undskyld.\n"
    .string "Jeg var din fan foer.\p"
    .string "Men nu ser du ud til at have mistet\n"
    .string "drivet du havde foer.\p"
    .string "Paa det sidste synes jeg {STR_VAR_1} har\n"
    .string "vaeret meget sejere.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .string "Oh!\n"
    .string "{PLAYER}!\p"
    .string "Alle har vaeret begejstrede for\n"
    .string "dig for nylig.\p"
    .string "Jeg kan forstaa hvorfor.\n"
    .string "Jeg ved at du er staerk.\p"
    .string "Men ved du hvad?\p"
    .string "Da jeg blev {STR_VAR_1}s fan,\n"
    .string "kan jeg ikke bare holde op med det.$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .string "Jeg synes TRAINERE er saa seje naar\n"
    .string "de kaemper.\p"
    .string "Synes du ikke ogsaa?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .string "Oh! Det er {PLAYER}!\n"
    .string "For sejt!\p"
    .string "Oh!\n"
    .string "Oh, ja!\p"
    .string "Kan du skrive under paa noget?\n"
    .string "Hvad med mine shorts?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .string "Uanset hvor varmt det har vaeret…\p"
    .string "Og uanset hvor koldt det bliver…\p"
    .string "Jeg har altid troet paa shorts og\n"
    .string "baaret dem!\p"
    .string "Jeg regner med at du bliver ved med\n"
    .string "at vinde!\p"
    .string "Jeg tror lige saa meget paa dig som\n"
    .string "jeg tror paa shorts!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .string "BROCK er min helt!\n"
    .string "Han er en mand mellem maend!\p"
    .string "Heheh, jeg fik min mor til at goere\n"
    .string "noget for mig.\p"
    .string "Jeg fik hende til at brodere BROCK\n"
    .string "paa mine shorts!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .string "…  …\p"
    .string "…  …\n"
    .string "Jeg er BROCKs fan!\p"
    .string "Selv om jeg var hans eneste fan,\n"
    .string "svaerger jeg paa min stenhaarde vilje,\l"
    .string "og paa mine shorts!\p"
    .string "Jeg vil vaere hans fan til den bitre ende!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .string "BROCK er det sidste ord i sejhed,\n"
    .string "punktum!\p"
    .string "Det er en fyr jeg vil ligne!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .string "{PLAYER}, jeg har haft formoejelsen af\n"
    .string "at se dig kaempe.\p"
    .string "Det vaekker soede erindringer om\n"
    .string "min egen laengst forsvundne ungdom.\p"
    .string "Maa du blive ved med at finde succes.\n"
    .string "Du har en fan i mig!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .string "Jeg har rejst langt og bredt\n"
    .string "gennem landene.\p"
    .string "Men aldrig har jeg set en TRAINER\n"
    .string "af din storhed.\p"
    .string "Tag mod af dine evner og bliv ved\n"
    .string "med at kaempe!\p"
    .string "Giv mig dit loefte om det,\n"
    .string "mit unge idol!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .string "Hmm…\n"
    .string "Og du er?\p"
    .string "Haaabede du paa at tilmelde dig\n"
    .string "et medlemskab i vores FAN CLUB?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .string "Ah, saa du er den meget-\n"
    .string "omtalte {PLAYER}.\p"
    .string "Du har bestemt udseendet af\n"
    .string "en vinder.\p"
    .string "Men for at jeg accepterer dig som\n"
    .string "en aegte POKeMON-storhed…\p"
    .string "… …\p"
    .string "Har du stadig vej at ga!$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .string "Alle os samlet her er fans\n"
    .string "af POKeMON TRAINERE.\p"
    .string "Saadan ser de ud i kamp…\n"
    .string "De er billedet paa coolhed.\p"
    .string "Maaske bliver du ogsaa omtalt\n"
    .string "her, hvis du bliver ved med at vinde.$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .string "Det er {PLAYER}!\n"
    .string "Det er {PLAYER}!\p"
    .string "Jeg vil gerne ligne {PLAYER} en dag!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .string "Alle holdt op med at vaere {PLAYER}s\n"
    .string "fan…\p"
    .string "Men det betyder at jeg kan have {PLAYER}\n"
    .string "helt for mig selv!\p"
    .string "Yay! Go for it!\n"
    .string "Min eneste {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .string "Ved du hvad?\n"
    .string "Jeg vil gerne ligne SABRINA!\p"
    .string "Jeg vil vaere en psykisk pige\n"
    .string "ligesom hende!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .string "Selv om jeg er den eneste, holder jeg\n"
    .string "ikke op med at vaere SABRINAs fan.\p"
    .string "Min drom er at ligne SABRINA,\n"
    .string "soed men cool.\p"
    .string "Jeg vil vaere en psykisk pige\n"
    .string "ligesom hende!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .string "Mon jeg kan blive en sej\n"
    .string "TRAINER en dag?$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .string "Oh man, oh man!\n"
    .string "Sejt! For sejt!\p"
    .string "…Hva?\n"
    .string "Nej, ikke dig.\p"
    .string "Bare maaden du kaemper paa.\n"
    .string "Det er sejt.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .string "Yo, {PLAYER}!\p"
    .string "Ser ud til at jeg er den eneste\n"
    .string "tilbage af dine fans.\p"
    .string "Men du ved hvad, jeg kan lide at\n"
    .string "vaere ene-fan… Mindre stress.\p"
    .string "Bliv ved!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .string "{STR_VAR_1} er sej, hva?\n"
    .string "Jeg elsker maaden han taler paa.\p"
    .string "Jeg ville virkelig vaerdsatte en chance\n"
    .string "for at moede ham personligt engang.$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .string "Hva, kan du tro det?\n"
    .string "Alle blev dine fans.\p"
    .string "Saa efter alt hvad vi har gennemgaaet\n"
    .string "er jeg den eneste {STR_VAR_1}-fan?\p"
    .string "Eh, at vaere den eneste\n"
    .string "{STR_VAR_1}-fan er min stil alligevel.$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .string "Oh du gode!\n"
    .string "Er det virkelig dig, {PLAYER}?\p"
    .string "Jeg maa sige, jeg beundrer\n"
    .string "maaden du kaemper paa.\p"
    .string "Jeg haaber du bliver ved.\n"
    .string "Jeg vil vaere din nummer et fan!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .string "Oh du gode!\n"
    .string "Om det ikke er {PLAYER}!\p"
    .string "Det er saa skuffende… Jeg indsa\n"
    .string "at jeg er din nummer-et-og-eneste fan!\p"
    .string "Naa, det kan ikke vaere anderledes!\n"
    .string "Lad mig i det mindste heppe paa dig!\p"
    .string "Hurra, hurra, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .string "For nylig har {STR_VAR_1} vaeret\n"
    .string "i flammer.\p"
    .string "Maaden han kaemper paa… Det er\n"
    .string "praecis som jeg kan lide det!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .string "Oh, hej!\n"
    .string "Om det ikke er {PLAYER}!\p"
    .string "Paa det sidste taler alle bare\n"
    .string "om dig.\p"
    .string "Jeg foeler mig ensom fordi jeg\n"
    .string "foretraekker {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .string "Fantastisk!\n"
    .string "{PLAYER}, du er virkelig fantastisk!\p"
    .string "I stedet for bare at se paa, maaske\n"
    .string "skal jeg ogsaa blive TRAINER.$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .string "Jeg er din eneste fan…\n"
    .string "Suk… Det her er ensomt…\p"
    .string "Kan du ikke praeve hardere og faa\n"
    .string "de andre til at lagge maerke til dig?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .string "Mester {STR_VAR_1} er saa vaerdig…\n"
    .string "Han er saa min type.\p"
    .string "Hvorfor kan de andre ikke se den\n"
    .string "vaerdighed han bare udstraaler?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .string "Jeg tror paa Mester {STR_VAR_1}\n"
    .string "af hele mit hjerte.\p"
    .string "Selv om jeg er den eneste der\n"
    .string "tror paa ham.\p"
    .string "Jeg foeler mig aldrig ensom, dog.\p"
    .string "Ikke hvis jeg bliver ved med at taenke\n"
    .string "paa Mester {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .string "Hiyah!\p"
    .string "Din kampstil er meget\n"
    .string "laererig.\p"
    .string "Jeg haaber du bliver ved med at\n"
    .string "arbejde hen imod succes, hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .string "I stedet for bare at se andre\n"
    .string "kaempe, kaemp selv!\p"
    .string "…Min DOJOs MESTER skaeldte mig ud\n"
    .string "saadan…\p"
    .string "Men det faar mig ikke til at holde op\n"
    .string "med at vaere din fan!\p"
    .string "Jeg kan ikke holde op med at vaere din fan!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .string "Hiyah! Der er kun eet TRAINER\n"
    .string "der har min respekt.\p"
    .string "Og det er ingen andre end min\n"
    .string "MESTER i FIGHTING DOJO.\p"
    .string "Du boer blive fan af min\n"
    .string "MESTER ligesom mig! Hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .string "Hiyah! Jeg respekterer min MESTER\n"
    .string "i FIGHTING DOJO.\p"
    .string "Jeg bliver aldrig fan af\n"
    .string "nogen andre end min MESTER!\p"
    .string "Jeg vil endda snige mig ud af DOJO\n"
    .string "for at sprede ord om hans storhed.\p"
    .string "Hiyah!$"

