SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .string "Hva?\n"
    .string "Du…$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .string "Er du mâske…\n"
    .string "… …\p"
    .string "Det er dig!\n"
    .string "Du er {PLAYER}!\p"
    .string "Vi talte lige om dig!\p"
    .string "Vi talte om at en utroligt god\n"
    .string "TRAINER var dukket op.\p"
    .string "Og den person er dig!\n"
    .string "Du er sâ sej!\p"
    .string "Sâ vi besluttede at vi bliver\n"
    .string "din FAN CLUB!\p"
    .string "Vi hâber alle at du bliver ved med at\n"
    .string "kæmpe og vise os hvor sej du er.\p"
    .string "Sâdan vil andre mâske blive\n"
    .string "fans ligesom mig.$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .string "Jeg hepper altid pâ dig!\p"
    .string "Kom sâ, {PLAYER}, kom sâ!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .string "Jeg tror altid pâ dig,\n"
    .string "{PLAYER}.\p"
    .string "Vis de andre venligst hvad du er\n"
    .string "for en nâr du kæmper alvorligt.$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .string "Undskyld.\n"
    .string "Jeg var din fan før.\p"
    .string "Men nu ser du ud til at have mistet\n"
    .string "drivet du havde før.\p"
    .string "Pâ det sidste synes jeg {STR_VAR_1} har\n"
    .string "været meget sejere.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .string "Oh!\n"
    .string "{PLAYER}!\p"
    .string "Alle har været begejstrede for\n"
    .string "dig for nylig.\p"
    .string "Jeg kan forstâ hvorfor.\n"
    .string "Jeg ved at du er stærk.\p"
    .string "Men ved du hvad?\p"
    .string "Da jeg blev {STR_VAR_1}s fan,\n"
    .string "kan jeg ikke bare holde op med det.$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .string "Jeg synes TRAINERE er sâ seje nâr\n"
    .string "de kæmper.\p"
    .string "Synes du ikke ogsâ?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .string "Oh! Det er {PLAYER}!\n"
    .string "For sejt!\p"
    .string "Oh!\n"
    .string "Oh, ja!\p"
    .string "Kan du skrive under pâ noget?\n"
    .string "Hvad med mine shorts?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .string "Uanset hvor varmt det har været…\p"
    .string "Og uanset hvor koldt det bliver…\p"
    .string "Jeg har altid trøt pâ shorts og\n"
    .string "bâret dem!\p"
    .string "Jeg regner med at du bliver ved med\n"
    .string "at vinde!\p"
    .string "Jeg tror lige sâ meget pâ dig som\n"
    .string "jeg tror pâ shorts!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .string "BROCK er min helt!\n"
    .string "Han er en mand mellem mænd!\p"
    .string "Heheh, jeg fik min mor til at gøre\n"
    .string "noget for mig.\p"
    .string "Jeg fik hende til at brodere BROCK\n"
    .string "pâ mine shorts!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .string "…  …\p"
    .string "…  …\n"
    .string "Jeg er BROCKs fan!\p"
    .string "Selv om jeg var hans eneste fan,\n"
    .string "sværger jeg pâ min stenhârde vilje,\l"
    .string "og pâ mine shorts!\p"
    .string "Jeg vil være hans fan til den bitre ende!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .string "BROCK er det sidste ord i sejhed,\n"
    .string "punktum!\p"
    .string "Det er en fyr jeg vil ligne!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .string "{PLAYER}, jeg har haft formøjelsen af\n"
    .string "at se dig kæmpe.\p"
    .string "Det vækker søde erindringer om\n"
    .string "min egen længst forsvundne ungdom.\p"
    .string "Mâ du blive ved med at finde succes.\n"
    .string "Du har en fan i mig!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .string "Jeg har rejst langt og bredt\n"
    .string "gennem landene.\p"
    .string "Men aldrig har jeg set en TRAINER\n"
    .string "af din storhed.\p"
    .string "Tag mod af dine evner og bliv ved\n"
    .string "med at kæmpe!\p"
    .string "Giv mig dit løfte om det,\n"
    .string "mit unge idol!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .string "Hmm…\n"
    .string "Og du er?\p"
    .string "Hâabede du pâ at tilmelde dig\n"
    .string "et medlemskab i vores FAN CLUB?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .string "Ah, sâ du er den meget-\n"
    .string "omtalte {PLAYER}.\p"
    .string "Du har bestemt udseendet af\n"
    .string "en vinder.\p"
    .string "Men for at jeg accepterer dig som\n"
    .string "en ægte POKéMON-storhed…\p"
    .string "… …\p"
    .string "Har du stadig vej at ga!$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .string "Alle os samlet her er fans\n"
    .string "af POKéMON TRAINERE.\p"
    .string "Sâdan ser de ud i kamp…\n"
    .string "De er billedet pâ coolhed.\p"
    .string "Mâske bliver du ogsâ omtalt\n"
    .string "her, hvis du bliver ved med at vinde.$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .string "Det er {PLAYER}!\n"
    .string "Det er {PLAYER}!\p"
    .string "Jeg vil gerne ligne {PLAYER} en dag!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .string "Alle holdt op med at være {PLAYER}s\n"
    .string "fan…\p"
    .string "Men det betyder at jeg kan have {PLAYER}\n"
    .string "helt for mig selv!\p"
    .string "Yay! Go for it!\n"
    .string "Min eneste {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .string "Ved du hvad?\n"
    .string "Jeg vil gerne ligne SABRINA!\p"
    .string "Jeg vil være en psykisk pige\n"
    .string "ligesom hende!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .string "Selv om jeg er den eneste, holder jeg\n"
    .string "ikke op med at være SABRINAs fan.\p"
    .string "Min drom er at ligne SABRINA,\n"
    .string "sød men cool.\p"
    .string "Jeg vil være en psykisk pige\n"
    .string "ligesom hende!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .string "Mon jeg kan blive en sej\n"
    .string "TRAINER en dag?$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .string "Oh man, oh man!\n"
    .string "Sejt! For sejt!\p"
    .string "…Hva?\n"
    .string "Nej, ikke dig.\p"
    .string "Bare mâden du kæmper pâ.\n"
    .string "Det er sejt.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .string "Yo, {PLAYER}!\p"
    .string "Ser ud til at jeg er den eneste\n"
    .string "tilbage af dine fans.\p"
    .string "Men du ved hvad, jeg kan lide at\n"
    .string "være ene-fan… Mindre stress.\p"
    .string "Bliv ved!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .string "{STR_VAR_1} er sej, hva?\n"
    .string "Jeg elsker mâden han taler pâ.\p"
    .string "Jeg ville virkelig værdsatte en chance\n"
    .string "for at møde ham personligt engang.$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .string "Hva, kan du tro det?\n"
    .string "Alle blev dine fans.\p"
    .string "Sâ efter alt hvad vi har gennemgâet\n"
    .string "er jeg den eneste {STR_VAR_1}-fan?\p"
    .string "Eh, at være den eneste\n"
    .string "{STR_VAR_1}-fan er min stil alligevel.$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .string "Oh du gode!\n"
    .string "Er det virkelig dig, {PLAYER}?\p"
    .string "Jeg mâ sige, jeg beundrer\n"
    .string "mâden du kæmper pâ.\p"
    .string "Jeg hâber du bliver ved.\n"
    .string "Jeg vil være din nummer et fan!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .string "Oh du gode!\n"
    .string "Om det ikke er {PLAYER}!\p"
    .string "Det er sâ skuffende… Jeg indsa\n"
    .string "at jeg er din nummer-et-og-eneste fan!\p"
    .string "Nâ, det kan ikke være anderledes!\n"
    .string "Lad mig i det mindste heppe pâ dig!\p"
    .string "Hurra, hurra, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .string "For nylig har {STR_VAR_1} været\n"
    .string "i flammer.\p"
    .string "Mâden han kæmper pâ… Det er\n"
    .string "præcis som jeg kan lide det!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .string "Oh, hej!\n"
    .string "Om det ikke er {PLAYER}!\p"
    .string "Pâ det sidste taler alle bare\n"
    .string "om dig.\p"
    .string "Jeg føler mig ensom fordi jeg\n"
    .string "foretrækker {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .string "Fantastisk!\n"
    .string "{PLAYER}, du er virkelig fantastisk!\p"
    .string "I stedet for bare at se pâ, mâske\n"
    .string "skal jeg ogsâ blive TRAINER.$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .string "Jeg er din eneste fan…\n"
    .string "Suk… Det her er ensomt…\p"
    .string "Kan du ikke præve hardere og fâ\n"
    .string "de andre til at lagge mærke til dig?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .string "Mester {STR_VAR_1} er sâ værdig…\n"
    .string "Han er sâ min type.\p"
    .string "Hvorfor kan de andre ikke se den\n"
    .string "værdighed han bare udstrâler?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .string "Jeg tror pâ Mester {STR_VAR_1}\n"
    .string "af hele mit hjerte.\p"
    .string "Selv om jeg er den eneste der\n"
    .string "tror pâ ham.\p"
    .string "Jeg føler mig aldrig ensom, dog.\p"
    .string "Ikke hvis jeg bliver ved med at tænke\n"
    .string "pâ Mester {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .string "Hiyah!\p"
    .string "Din kampstil er meget\n"
    .string "lærerig.\p"
    .string "Jeg hâber du bliver ved med at\n"
    .string "arbejde hen imod succes, hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .string "I stedet for bare at se andre\n"
    .string "kæmpe, kæmp selv!\p"
    .string "…Min DOJOs MESTER skældte mig ud\n"
    .string "sâdan…\p"
    .string "Men det fâr mig ikke til at holde op\n"
    .string "med at være din fan!\p"
    .string "Jeg kan ikke holde op med at være din fan!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .string "Hiyah! Der er kun eet TRAINER\n"
    .string "der har min respekt.\p"
    .string "Og det er ingen andre end min\n"
    .string "MESTER i FIGHTING DOJO.\p"
    .string "Du bør blive fan af min\n"
    .string "MESTER ligesom mig! Hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .string "Hiyah! Jeg respekterer min MESTER\n"
    .string "i FIGHTING DOJO.\p"
    .string "Jeg bliver aldrig fan af\n"
    .string "nogen andre end min MESTER!\p"
    .string "Jeg vil endda snige mig ud af DOJO\n"
    .string "for at sprede ord om hans storhed.\p"
    .string "Hiyah!$"

