SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .string "Hva?\n"
    .string "Du…$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .string "Er du måske…\n"
    .string "… …\p"
    .string "Det er dig!\n"
    .string "Du er {PLAYER}!\p"
    .string "Vi talte lige om dig!\p"
    .string "Vi talte om at en utroligt god\n"
    .string "TRAINER var dukket op.\p"
    .string "Og den person er dig!\n"
    .string "Du er så sej!\p"
    .string "Så vi besluttede at vi bliver\n"
    .string "din FAN CLUB!\p"
    .string "Vi håber alle at du bliver ved med at\n"
    .string "kæmpe og vise os hvor sej du er.\p"
    .string "Sådan vil andre måske blive\n"
    .string "fans ligesom mig.$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .string "Jeg hepper altid på dig!\p"
    .string "Kom så, {PLAYER}, kom så!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .string "Jeg tror altid på dig,\n"
    .string "{PLAYER}.\p"
    .string "Vis de andre venligst hvad du er\n"
    .string "for en når du kæmper alvorligt.$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .string "Undskyld.\n"
    .string "Jeg var din fan før.\p"
    .string "Men nu ser du ud til at have mistet\n"
    .string "drivet du havde før.\p"
    .string "På det sidste synes jeg {STR_VAR_1} har\n"
    .string "været meget sejere.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .string "Oh!\n"
    .string "{PLAYER}!\p"
    .string "Alle har været begejstrede for\n"
    .string "dig for nylig.\p"
    .string "Jeg kan forstå hvorfor.\n"
    .string "Jeg ved at du er stærk.\p"
    .string "Men ved du hvad?\p"
    .string "Da jeg blev {STR_VAR_1}s fan,\n"
    .string "kan jeg ikke bare holde op med det.$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .string "Jeg synes TRAINERE er så seje når\n"
    .string "de kæmper.\p"
    .string "Synes du ikke også?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .string "Oh! Det er {PLAYER}!\n"
    .string "For sejt!\p"
    .string "Oh!\n"
    .string "Oh, ja!\p"
    .string "Kan du skrive under på noget?\n"
    .string "Hvad med mine shorts?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .string "Uanset hvor varmt det har været…\p"
    .string "Og uanset hvor koldt det bliver…\p"
    .string "Jeg har altid trøt på shorts og\n"
    .string "båret dem!\p"
    .string "Jeg regner med at du bliver ved med\n"
    .string "at vinde!\p"
    .string "Jeg tror lige så meget på dig som\n"
    .string "jeg tror på shorts!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .string "BROCK er min helt!\n"
    .string "Han er en mand mellem mænd!\p"
    .string "Heheh, jeg fik min mor til at gøre\n"
    .string "noget for mig.\p"
    .string "Jeg fik hende til at brodere BROCK\n"
    .string "på mine shorts!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .string "…  …\p"
    .string "…  …\n"
    .string "Jeg er BROCKs fan!\p"
    .string "Selv om jeg var hans eneste fan,\n"
    .string "sværger jeg på min stenhårde vilje,\l"
    .string "og på mine shorts!\p"
    .string "Jeg vil være hans fan til den bitre ende!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .string "BROCK er det sidste ord i sejhed,\n"
    .string "punktum!\p"
    .string "Det er en fyr jeg vil ligne!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .string "{PLAYER}, jeg har haft formøjelsen af\n"
    .string "at se dig kæmpe.\p"
    .string "Det vækker søde erindringer om\n"
    .string "min egen længst forsvundne ungdom.\p"
    .string "Må du blive ved med at finde succes.\n"
    .string "Du har en fan i mig!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .string "Jeg har rejst langt og bredt\n"
    .string "gennem landene.\p"
    .string "Men aldrig har jeg set en TRAINER\n"
    .string "af din storhed.\p"
    .string "Tag mod af dine evner og bliv ved\n"
    .string "med at kæmpe!\p"
    .string "Giv mig dit løfte om det,\n"
    .string "mit unge idol!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .string "Hmm…\n"
    .string "Og du er?\p"
    .string "Håabede du på at tilmelde dig\n"
    .string "et medlemskab i vores FAN CLUB?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .string "Ah, så du er den meget-\n"
    .string "omtalte {PLAYER}.\p"
    .string "Du har bestemt udseendet af\n"
    .string "en vinder.\p"
    .string "Men for at jeg accepterer dig som\n"
    .string "en ægte POKéMON-storhed…\p"
    .string "… …\p"
    .string "Har du stadig vej at ga!$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .string "Alle os samlet her er fans\n"
    .string "af POKéMON TRAINERE.\p"
    .string "Sådan ser de ud i kamp…\n"
    .string "De er billedet på coolhed.\p"
    .string "Måske bliver du også omtalt\n"
    .string "her, hvis du bliver ved med at vinde.$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .string "Det er {PLAYER}!\n"
    .string "Det er {PLAYER}!\p"
    .string "Jeg vil gerne ligne {PLAYER} en dag!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .string "Alle holdt op med at være {PLAYER}s\n"
    .string "fan…\p"
    .string "Men det betyder at jeg kan have {PLAYER}\n"
    .string "helt for mig selv!\p"
    .string "Yay! Go for it!\n"
    .string "Min eneste {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .string "Ved du hvad?\n"
    .string "Jeg vil gerne ligne SABRINA!\p"
    .string "Jeg vil være en psykisk pige\n"
    .string "ligesom hende!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .string "Selv om jeg er den eneste, holder jeg\n"
    .string "ikke op med at være SABRINAs fan.\p"
    .string "Min drom er at ligne SABRINA,\n"
    .string "sød men cool.\p"
    .string "Jeg vil være en psykisk pige\n"
    .string "ligesom hende!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .string "Mon jeg kan blive en sej\n"
    .string "TRAINER en dag?$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .string "Oh man, oh man!\n"
    .string "Sejt! For sejt!\p"
    .string "…Hva?\n"
    .string "Nej, ikke dig.\p"
    .string "Bare måden du kæmper på.\n"
    .string "Det er sejt.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .string "Yo, {PLAYER}!\p"
    .string "Ser ud til at jeg er den eneste\n"
    .string "tilbage af dine fans.\p"
    .string "Men du ved hvad, jeg kan lide at\n"
    .string "være ene-fan… Mindre stress.\p"
    .string "Bliv ved!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .string "{STR_VAR_1} er sej, hva?\n"
    .string "Jeg elsker måden han taler på.\p"
    .string "Jeg ville virkelig værdsatte en chance\n"
    .string "for at møde ham personligt engang.$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .string "Hva, kan du tro det?\n"
    .string "Alle blev dine fans.\p"
    .string "Så efter alt hvad vi har gennemgået\n"
    .string "er jeg den eneste {STR_VAR_1}-fan?\p"
    .string "Eh, at være den eneste\n"
    .string "{STR_VAR_1}-fan er min stil alligevel.$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .string "Oh du gode!\n"
    .string "Er det virkelig dig, {PLAYER}?\p"
    .string "Jeg må sige, jeg beundrer\n"
    .string "måden du kæmper på.\p"
    .string "Jeg håber du bliver ved.\n"
    .string "Jeg vil være din nummer et fan!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .string "Oh du gode!\n"
    .string "Om det ikke er {PLAYER}!\p"
    .string "Det er så skuffende… Jeg indsa\n"
    .string "at jeg er din nummer-et-og-eneste fan!\p"
    .string "Nå, det kan ikke være anderledes!\n"
    .string "Lad mig i det mindste heppe på dig!\p"
    .string "Hurra, hurra, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .string "For nylig har {STR_VAR_1} været\n"
    .string "i flammer.\p"
    .string "Måden han kæmper på… Det er\n"
    .string "præcis som jeg kan lide det!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .string "Oh, hej!\n"
    .string "Om det ikke er {PLAYER}!\p"
    .string "På det sidste taler alle bare\n"
    .string "om dig.\p"
    .string "Jeg føler mig ensom fordi jeg\n"
    .string "foretrækker {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .string "Fantastisk!\n"
    .string "{PLAYER}, du er virkelig fantastisk!\p"
    .string "I stedet for bare at se på, måske\n"
    .string "skal jeg også blive TRAINER.$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .string "Jeg er din eneste fan…\n"
    .string "Suk… Det her er ensomt…\p"
    .string "Kan du ikke præve hardere og få\n"
    .string "de andre til at lagge mærke til dig?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .string "Mester {STR_VAR_1} er så værdig…\n"
    .string "Han er så min type.\p"
    .string "Hvorfor kan de andre ikke se den\n"
    .string "værdighed han bare udstråler?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .string "Jeg tror på Mester {STR_VAR_1}\n"
    .string "af hele mit hjerte.\p"
    .string "Selv om jeg er den eneste der\n"
    .string "tror på ham.\p"
    .string "Jeg føler mig aldrig ensom, dog.\p"
    .string "Ikke hvis jeg bliver ved med at tænke\n"
    .string "på Mester {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .string "Hiyah!\p"
    .string "Din kampstil er meget\n"
    .string "lærerig.\p"
    .string "Jeg håber du bliver ved med at\n"
    .string "arbejde hen imod succes, hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .string "I stedet for bare at se andre\n"
    .string "kæmpe, kæmp selv!\p"
    .string "…Min DOJOs MESTER skældte mig ud\n"
    .string "sådan…\p"
    .string "Men det får mig ikke til at holde op\n"
    .string "med at være din fan!\p"
    .string "Jeg kan ikke holde op med at være din fan!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .string "Hiyah! Der er kun eet TRAINER\n"
    .string "der har min respekt.\p"
    .string "Og det er ingen andre end min\n"
    .string "MESTER i FIGHTING DOJO.\p"
    .string "Du bør blive fan af min\n"
    .string "MESTER ligesom mig! Hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .string "Hiyah! Jeg respekterer min MESTER\n"
    .string "i FIGHTING DOJO.\p"
    .string "Jeg bliver aldrig fan af\n"
    .string "nogen andre end min MESTER!\p"
    .string "Jeg vil endda snige mig ud af DOJO\n"
    .string "for at sprede ord om hans storhed.\p"
    .string "Hiyah!$"

