Route8_Text_AidanIntro::
    .string "Du ser god ud til POKeMON, men hvad\n"
    .string "er dit keminiveau?$"

Route8_Text_AidanDefeat::
    .string "Av!\n"
    .string "Smeltning!$"

Route8_Text_AidanPostBattle::
    .string "Jeg er bedre til skole end det her!$"

Route8_Text_StanIntro::
    .string "Okay!\n"
    .string "Lad os spille et spil!$"

Route8_Text_StanDefeat::
    .string "Pokkers!\n"
    .string "Kom for kort!$"

Route8_Text_StanPostBattle::
    .string "Det gik ikke i dag.$"

Route8_Text_GlennIntro::
    .string "Du boer vide at du har brug for\n"
    .string "strategi for at vinde!$"

Route8_Text_GlennDefeat::
    .string "Det er ikke logisk!$"

Route8_Text_GlennPostBattle::
    .string "Start med GRIMER foerst…og…\n"
    .string "…og…saa…$"

Route8_Text_PaigeIntro::
    .string "Jeg kan lide NIDORAN, saa jeg\n"
    .string "samler dem!$"

Route8_Text_PaigeDefeat::
    .string "Hvorfor?\n"
    .string "Hvorfor??$"

Route8_Text_PaigePostBattle::
    .string "Naar POKeMON bliver voksne, bliver\n"
    .string "de grimme! De boer ikke udvikle sig.$"

Route8_Text_LeslieIntro::
    .string "Skole er sjovt, men det er\n"
    .string "POKeMON ogsaa.$"

Route8_Text_LeslieDefeat::
    .string "Du viste mig tydeligt at jeg boer\n"
    .string "holde mig til skolen.$"

Route8_Text_LesliePostBattle::
    .string "Jeg havde taenkt at faa frisk luft\n"
    .string "for en gangs skyld, men…\p"
    .string "Vi er fanget her pga. portene\n"
    .string "ved SAFFRON.$"

Route8_Text_AndreaIntro::
    .string "MEOWTH er saa nuttet, mjav, mjav,\n"
    .string "mjav!$"

Route8_Text_AndreaDefeat::
    .string "Miiijav!$"

Route8_Text_AndreaPostBattle::
    .string "Jeg synes ogsaa PIDGEY og RATTATA\n"
    .string "er nuttede!$"

Route8_Text_MeganIntro::
    .string "Vi maa se tossede ud saadan her\n"
    .string "staende.$"

Route8_Text_MeganDefeat::
    .string "Se hvad du gjorde ved mine stakkels,\n"
    .string "nuttede POKeMON!$"

Route8_Text_MeganPostBattle::
    .string "SAFFRONs portvagt lukker ikke os\n"
    .string "igennem.\p"
    .string "Jeg ved han goer sit job, men jeg\n"
    .string "synes han er ond.$"

Route8_Text_RichIntro::
    .string "Jeg er en vandrende spilfyr!$"

Route8_Text_RichDefeat::
    .string "Missede chancen!$"

Route8_Text_RichPostBattle::
    .string "At spille spil og POKeMON er som\n"
    .string "at spise jordnoedder! Kan ikke stoppe!$"

Route8_Text_JuliaIntro::
    .string "Hvad er et nuttet, rundt og fluffy\n"
    .string "POKeMON?$"

Route8_Text_JuliaDefeat::
    .string "Stop!\p"
    .string "Vaer ikke saa ond mod min CLEFAIRY!$"

Route8_Text_JuliaPostBattle::
    .string "Jeg laeste at CLEFAIRY udvikler sig\n"
    .string "naar den udsaettes for en MOON STONE.\p"
    .string "Jeg laeste det i et POKeMON JOURNAL.\n"
    .string "Tror du det er sandt?$"

Route8_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CELADON CITY - LAVENDER TOWN$"

Route8_Text_EliIntro::
    .string "ELI: Tvillingekraft er fantastisk.\n"
    .string "Vidste du det?$"

Route8_Text_EliDefeat::
    .string "ELI: Men…\n"
    .string "Vi brugte vores tvillingekraft…$"

Route8_Text_EliPostBattle::
    .string "ELI: Jeg fangede mine POKeMON\n"
    .string "sammen med ANNE!$"

Route8_Text_EliNotEnoughMons::
    .string "ELI: Vi kan ikke kaempe hvis du ikke\n"
    .string "har to POKeMON.$"

Route8_Text_AnneIntro::
    .string "ANNE: Vi chokerer dig med vores\n"
    .string "tvillingekraft!$"

Route8_Text_AnneDefeat::
    .string "ANNE: Vores tvillingekraft…$"

Route8_Text_AnnePostBattle::
    .string "ANNE: Jeg opdrager POKeMON sammen\n"
    .string "med ELI.$"

Route8_Text_AnneNotEnoughMons::
    .string "ANNE: Hej, hej! Lad os kaempe!\n"
    .string "Men tag to POKeMON med.$"

Route8_Text_RicardoIntro::
    .string "Min cykel virker ikke, mand.$"

Route8_Text_RicardoDefeat::
    .string "Av, mand.\n"
    .string "Jeg er ikke til det her.$"

Route8_Text_RicardoPostBattle::
    .string "Jeg fik graes i mine eger, mand.$"

Route8_Text_JarenIntro::
    .string "Goer plads, ellers koerer jeg dig\n"
    .string "ned!$"

Route8_Text_JarenDefeat::
    .string "Er du serioes, unge?$"

Route8_Text_JarenPostBattle::
    .string "Tro ikke du er noget saerligt\n"
    .string "bare fordi.$"
