Route8_Text_AidanIntro::
    .string "Du ser god ud til POKéMON, men hvad\n"
    .string "er dit keminiveau?$"

Route8_Text_AidanDefeat::
    .string "Av!\n"
    .string "Smeltning!$"

Route8_Text_AidanPostBattle::
    .string "Jeg er bedre til skole end det her!$"

Route8_Text_StanIntro::
    .string "Okay!\n"
    .string "Lad os spille et spil!$"

Route8_Text_StanDefeat::
    .string "Pokkers!\n"
    .string "Kom for kort!$"

Route8_Text_StanPostBattle::
    .string "Det gik ikke i dag.$"

Route8_Text_GlennIntro::
    .string "Du bør vide at du har brug for\n"
    .string "strategi for at vinde!$"

Route8_Text_GlennDefeat::
    .string "Det er ikke logisk!$"

Route8_Text_GlennPostBattle::
    .string "Start med GRIMER først…og…\n"
    .string "…og…sâ…$"

Route8_Text_PaigeIntro::
    .string "Jeg kan lide NIDORAN, sâ jeg\n"
    .string "samler dem!$"

Route8_Text_PaigeDefeat::
    .string "Hvorfor?\n"
    .string "Hvorfor??$"

Route8_Text_PaigePostBattle::
    .string "Nâr POKéMON bliver voksne, bliver\n"
    .string "de grimme! De bør ikke udvikle sig.$"

Route8_Text_LeslieIntro::
    .string "Skole er sjovt, men det er\n"
    .string "POKéMON ogsâ.$"

Route8_Text_LeslieDefeat::
    .string "Du viste mig tydeligt at jeg bør\n"
    .string "holde mig til skolen.$"

Route8_Text_LesliePostBattle::
    .string "Jeg havde tænkt at fâ frisk luft\n"
    .string "for en gangs skyld, men…\p"
    .string "Vi er fanget her pga. portene\n"
    .string "ved SAFFRON.$"

Route8_Text_AndreaIntro::
    .string "MEOWTH er sâ nuttet, mjav, mjav,\n"
    .string "mjav!$"

Route8_Text_AndreaDefeat::
    .string "Miiijav!$"

Route8_Text_AndreaPostBattle::
    .string "Jeg synes ogsâ PIDGEY og RATTATA\n"
    .string "er nuttede!$"

Route8_Text_MeganIntro::
    .string "Vi mâ se tossede ud sâdan her\n"
    .string "stænde.$"

Route8_Text_MeganDefeat::
    .string "Se hvad du gjorde ved mine stakkels,\n"
    .string "nuttede POKéMON!$"

Route8_Text_MeganPostBattle::
    .string "SAFFRONs portvagt lukker ikke os\n"
    .string "igennem.\p"
    .string "Jeg ved han gør sit job, men jeg\n"
    .string "synes han er ond.$"

Route8_Text_RichIntro::
    .string "Jeg er en vandrende spilfyr!$"

Route8_Text_RichDefeat::
    .string "Missede chancen!$"

Route8_Text_RichPostBattle::
    .string "At spille spil og POKéMON er som\n"
    .string "at spise jordnødder! Kan ikke stoppe!$"

Route8_Text_JuliaIntro::
    .string "Hvad er et nuttet, rundt og fluffy\n"
    .string "POKéMON?$"

Route8_Text_JuliaDefeat::
    .string "Stop!\p"
    .string "Vær ikke sâ ond mod min CLEFAIRY!$"

Route8_Text_JuliaPostBattle::
    .string "Jeg læste at CLEFAIRY udvikler sig\n"
    .string "nâr den udsættes for en MOON STONE.\p"
    .string "Jeg læste det i et POKéMON JOURNAL.\n"
    .string "Tror du det er sandt?$"

Route8_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CELADON CITY - LAVENDER TOWN$"

Route8_Text_EliIntro::
    .string "ELI: Tvillingekraft er fantastisk.\n"
    .string "Vidste du det?$"

Route8_Text_EliDefeat::
    .string "ELI: Men…\n"
    .string "Vi brugte vores tvillingekraft…$"

Route8_Text_EliPostBattle::
    .string "ELI: Jeg fangede mine POKéMON\n"
    .string "sammen med ANNE!$"

Route8_Text_EliNotEnoughMons::
    .string "ELI: Vi kan ikke kæmpe hvis du ikke\n"
    .string "har to POKéMON.$"

Route8_Text_AnneIntro::
    .string "ANNE: Vi chokerer dig med vores\n"
    .string "tvillingekraft!$"

Route8_Text_AnneDefeat::
    .string "ANNE: Vores tvillingekraft…$"

Route8_Text_AnnePostBattle::
    .string "ANNE: Jeg opdrager POKéMON sammen\n"
    .string "med ELI.$"

Route8_Text_AnneNotEnoughMons::
    .string "ANNE: Hej, hej! Lad os kæmpe!\n"
    .string "Men tag to POKéMON med.$"

Route8_Text_RicardoIntro::
    .string "Min cykel virker ikke, mand.$"

Route8_Text_RicardoDefeat::
    .string "Av, mand.\n"
    .string "Jeg er ikke til det her.$"

Route8_Text_RicardoPostBattle::
    .string "Jeg fik græs i mine eger, mand.$"

Route8_Text_JarenIntro::
    .string "Gør plads, ellers kører jeg dig\n"
    .string "ned!$"

Route8_Text_JarenDefeat::
    .string "Er du seriøs, unge?$"

Route8_Text_JarenPostBattle::
    .string "Tro ikke du er noget særligt\n"
    .string "bare fordi.$"
