FiveIsland_LostCave_Room10_Text_SelphyIntro::
    .string "H-hvad agter du at goere ved\n"
    .string "mig?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
    .string "Oeh… Jeg var bange for at du\n"
    .string "ville goere mig fortraed.$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
    .string "Jeg er saa glad for at du kom\n"
    .string "forbi.\p"
    .string "Jeg blev ret kede af at gaa,\n"
    .string "og jeg foeler mig traet.\p"
    .string "Maa jeg bede dig tage mig hjem\n"
    .string "herfra?$"

