FiveIsland_LostCave_Room10_Text_SelphyIntro::
    .string "H-hvad agter du at göre ved\n"
    .string "mig?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
    .string "Oeh… Jeg var bange for at du\n"
    .string "ville göre mig forträd.$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
    .string "Jeg er sâ glad for at du kom\n"
    .string "forbi.\p"
    .string "Jeg blev ret kede af at gâ,\n"
    .string "og jeg föler mig trät.\p"
    .string "Mâ jeg bede dig tage mig hjem\n"
    .string "herfra?$"

