CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "Jeg koeber en gave til min\n"
    .string "kaereste.\p"
    .string "Jeg taenker en POKe DOLL bliver det.\n"
    .string "Det er det populaere.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "Jeg hoerte noget nyttigt.\p"
    .string "Hvis en vild POKeMON dukker op, kan du\n"
    .string "distrahere den med en POKe DOLL.\p"
    .string "Du kan loebe vaek mens den vilde\n"
    .string "POKeMON er distraheret.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Udtryk dig med gaver!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution tilbud!\n"
    .string "Element STONES til salg nu!$"
