CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "Jeg køber en gave til min\n"
    .string "kæreste.\p"
    .string "Jeg tænker en POKe DOLL bliver det.\n"
    .string "Det er det populære.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "Jeg hørte noget nyttigt.\p"
    .string "Hvis en vild POKéMON dukker op, kan du\n"
    .string "distrahere den med en POKe DOLL.\p"
    .string "Du kan løbe væk mens den vilde\n"
    .string "POKéMON er distraheret.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Udtryk dig med gaver!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution tilbud!\n"
    .string "Element STONES til salg nu!$"
