CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "Jeg köber en gave til min\n"
    .string "käreste.\p"
    .string "Jeg tänker en POKe DOLL bliver det.\n"
    .string "Det er det populäre.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "Jeg hörte noget nyttigt.\p"
    .string "Hvis en vild POKeMON dukker op, kan du\n"
    .string "distrahere den med en POKe DOLL.\p"
    .string "Du kan löbe väk mens den vilde\n"
    .string "POKeMON er distraheret.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Udtryk dig med gaver!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution tilbud!\n"
    .string "Element STONES til salg nu!$"
