ViridianCity_House_Text_NicknamingIsFun::
    .string "At finde paa kaldenavne er sjovt,\n"
    .string "men det er ikke saa nemt at goere.\p"
    .string "Smart navne er rare, men enkle\n"
    .string "navne er lettere at huske.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "Min far elsker ogsaa POKeMON.$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Navn: SPEARY$"

