ViridianCity_House_Text_NicknamingIsFun::
    .string "At finde pâ kaldenavne er sjovt,\n"
    .string "men det er ikke sâ nemt at göre.\p"
    .string "Smart navne er rare, men enkle\n"
    .string "navne er lettere at huske.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "Min far elsker ogsâ POKéMON.$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Navn: SPEARY$"

