ViridianCity_House_Text_NicknamingIsFun::
    .string "At finde på kaldenavne er sjovt,\n"
    .string "men det er ikke så nemt at gøre.\p"
    .string "Smart navne er rare, men enkle\n"
    .string "navne er lettere at huske.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "Min far elsker også POKéMON.$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Navn: SPEARY$"

