SilphCo_3F_Text_WhatAmIToDo::
    .string "Jeg arbejder for SILPH CO.\n"
    .string "Hvad skal jeg goere?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}!\n"
    .string "Du og dine POKeMON reddede os!$"

SilphCo_3F_Text_GruntIntro::
    .string "Hold op med at rode med os, unge!$"

SilphCo_3F_Text_GruntDefeat::
    .string "Jeg giver op!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "Et hint? Du kan aabne doere med\n"
    .string "en CARD KEY!$"

SilphCo_3F_Text_JoseIntro::
    .string "Jeg stoetter TEAM ROCKET mere end\n"
    .string "jeg stoetter SILPH CO.!$"

SilphCo_3F_Text_JoseDefeat::
    .string "Du fik mig virkelig!$"

SilphCo_3F_Text_JosePostBattle::
    .string "Humph…\p"
    .string "TEAM ROCKET sagde at hvis jeg hjalp\n"
    .string "dem, ville de lade mig studere POKeMON.$"

SilphCo_3F_Text_FloorSign::
    .string "SILPH CO. HOVEDKONTOR\n"
    .string "3. SAL$"

