PalletTown_Text_OakDontGoOut::
    .string "OAK: Hej! Vent!\n"
    .string "Gâ ikke ud!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: Det er farligt!\n"
    .string "Vilde POKeMON lever i höjt gräs!\p"
    .string "Du har brug for din egen POKeMON\n"
    .string "til beskyttelse.\p"
    .string "Jeg ved det!\n"
    .string "Kom med mig!$"

PalletTown_Text_RaisingMonsToo::
    .string "Jeg opdrager ogsâ POKeMON.\p"
    .string "Nâr de bliver stärke, kan de\n"
    .string "beskytte mig.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Teknologi er utrolig!\p"
    .string "Du kan nu gemme og hente ting og\n"
    .string "POKeMON som data via PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "OAK POKeMON FORSKNINGSLAB$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}s hus$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}s hus$"

PalletTown_Text_TownSign::
    .string "PALLET TOWN\n"
    .string "Dine rejsens skygger venter!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "Du er tilbage?\p"
    .string "Hvor meget har du udfyldt i din\n"
    .string "POKeDEX?\p"
    .string "Mâ jeg se den?\p"
    .string "Lad mig se…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "Du har fanget {STR_VAR_2}…\p"
    .string "Hm, det ser ud til at du gör et\n"
    .string "ärligt forsög.\p"
    .string "Nâr du fâr udfyldt mere, kom og\n"
    .string "vis mig det.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "Du har fanget… {STR_VAR_2}!?\n"
    .string "Det er imponerende!\p"
    .string "Der er noget jeg vil spörge dig om,\n"
    .string "{PLAYER}.\p"
    .string "Kom.\n"
    .string "Fölg mig.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "Du synes at nyde at rejse.\p"
    .string "Med dig, {PLAYER}, kan jeg nemt\n"
    .string "forestille mig at du drager til endnu\l"
    .string "mere exotiske steder.\p"
    .string "Godt for dig, godt for dig.\n"
    .string "Hohoho.$"

