ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "LOSTELLE: Hulk… Snus…\n"
    .string "Aah! Venligst hjaelp!\p"
    .string "En skraemmende POKeMON dukkede op der\n"
    .string "for et stykke tid siden.\p"
    .string "Den blev ved med at skraemme.\n"
    .string "Den skraemte LOSTELLE.\p"
    .string "Jeg er for bange til at bevaege mig!\n"
    .string "Men jeg vil hjem…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "Aah! Der kommer den igen!\n"
    .string "Nej! Gaa vaek! Den skraemmer mig!\p"
    .string "Waaaaaaah!\n"
    .string "Jeg vil have min far!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "Aaaah! Det var saa skraemmende!\n"
    .string "Tak!\p"
    .string "LOSTELLE kom for at plukke nogle\n"
    .string "BAeR.\p"
    .string "Du maa faa dette!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "Hvad hedder du?\p"
    .string "LOSTELLE er bange, saa maa jeg gaa\n"
    .string "med dig til min fars hus?\p"
    .string "Okay!\n"
    .string "Lad os tage hjem!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "Din BERRY POUCH er fuld.\n"
    .string "Jeg gaetter paa at du ikke vil have dette.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Velkommen til BERRY FOREST\p"
    .string "Vaer venlig og del BAeR med\n"
    .string "andre og POKeMON.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Pas paa vilde, BAeR-elske\n"
    .string "POKeMON!$"

