ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "LOSTELLE: Hulk… Snus…\n"
    .string "Aah! Venligst hjælp!\p"
    .string "En skræmmende POKéMON dukkede op der\n"
    .string "for et stykke tid siden.\p"
    .string "Den blev ved med at skræmme.\n"
    .string "Den skræmte LOSTELLE.\p"
    .string "Jeg er for bange til at bevæge mig!\n"
    .string "Men jeg vil hjem…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "Aah! Der kommer den igen!\n"
    .string "Nej! Gå væk! Den skræmmer mig!\p"
    .string "Wåååah!\n"
    .string "Jeg vil have min far!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "Aåah! Det var så skræmmende!\n"
    .string "Tak!\p"
    .string "LOSTELLE kom for at plukke nogle\n"
    .string "BÆR.\p"
    .string "Du må få dette!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "Hvad hedder du?\p"
    .string "LOSTELLE er bange, så må jeg gå\n"
    .string "med dig til min fars hus?\p"
    .string "Okay!\n"
    .string "Lad os tage hjem!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "Din BERRY POUCH er fuld.\n"
    .string "Jeg gætter på at du ikke vil have dette.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Velkommen til BERRY FOREST\p"
    .string "Vær venlig og del BÆR med\n"
    .string "andre og POKéMON.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Pas på vilde, BÆR-elske\n"
    .string "POKéMON!$"

