ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "LOSTELLE: Hulk… Snus…\n"
    .string "Aah! Venligst hjälp!\p"
    .string "En skrämmende POKeMON dukkede op der\n"
    .string "for et stykke tid siden.\p"
    .string "Den blev ved med at skrämme.\n"
    .string "Den skrämte LOSTELLE.\p"
    .string "Jeg er for bange til at beväge mig!\n"
    .string "Men jeg vil hjem…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "Aah! Der kommer den igen!\n"
    .string "Nej! Gâ väk! Den skrämmer mig!\p"
    .string "Wâââah!\n"
    .string "Jeg vil have min far!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "Aâah! Det var sâ skrämmende!\n"
    .string "Tak!\p"
    .string "LOSTELLE kom for at plukke nogle\n"
    .string "BAeR.\p"
    .string "Du mâ fâ dette!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "Hvad hedder du?\p"
    .string "LOSTELLE er bange, sâ mâ jeg gâ\n"
    .string "med dig til min fars hus?\p"
    .string "Okay!\n"
    .string "Lad os tage hjem!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "Din BERRY POUCH er fuld.\n"
    .string "Jeg gätter pâ at du ikke vil have dette.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Velkommen til BERRY FOREST\p"
    .string "Vär venlig og del BAeR med\n"
    .string "andre og POKeMON.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Pas pâ vilde, BAeR-elske\n"
    .string "POKeMON!$"

