CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .string "POKéMON?\n"
    .string "Nej, dette er et hotel for mennesker.\p"
    .string "Vi er desvärre fuldt booket.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "Jeg er pâ ferie med min bror og\n"
    .string "käreste.\p"
    .string "CELADON er sâ flot en by!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "Hvorfor?\n"
    .string "Hvorfor tog hun sin bror med?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "Yippee! Jeg er pâ ferie!\n"
    .string "Min söster tog mig med! Fedt!$"
