CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .string "POKeMON?\n"
    .string "Nej, dette er et hotel for mennesker.\p"
    .string "Vi er desvaerre fuldt booket.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "Jeg er paa ferie med min bror og\n"
    .string "kaereste.\p"
    .string "CELADON er saa flot en by!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "Hvorfor?\n"
    .string "Hvorfor tog hun sin bror med?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "Yippee! Jeg er paa ferie!\n"
    .string "Min soester tog mig med! Fedt!$"
