FourIsland_Text_IslandSign::
    .string "FIRE Ö\n"
    .string "Den varme, blâ flodö$"

FourIsland_Text_LoreleiHasReturned::
    .string "LORELEI er vendt tilbage.\p"
    .string "Mon hun fandt bylivet for\n"
    .string "stressende?$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "LORELEI er rejst tilbage.\p"
    .string "Den LAPRAS hun har, forestiller jeg\n"
    .string "mig det er den hun mödte som barn.\p"
    .string "Jeg tror det var i ICEFALL CAVE\n"
    .string "at hun fangede den.\p"
    .string "Mâske har den POKéMON väret hos\n"
    .string "hende lige siden.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "{RIVAL}: Hej!\n"
    .string "{PLAYER}!\p"
    .string "Hvad laver du her pâ SEVII\n"
    .string "ISLANDS?\p"
    .string "Du burde holde op med at kopiere\n"
    .string "mig, ved du?\p"
    .string "Anyway, jeg har allerede fâet mit\n"
    .string "POKéMON-ÆG, sâ jeg er färdig her.\p"
    .string "Ha, du ved sikkert ikke engang\n"
    .string "om POKéMON-ÆG.\p"
    .string "Sâdan fylder du aldrig din\n"
    .string "NATIONAL POKéDEX.\p"
    .string "For resten sâ jeg en vi begge\n"
    .string "kender pâ denne ö.\p"
    .string "Hvorfor ikke kigge rundt hvis du\n"
    .string "er nysgerrig?\p"
    .string "Jeg har ikke tid at spilde.\p"
    .string "Vi ses!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .string "Øh, du fandt mig!\n"
    .string "Sig det ikke til LORELEI.\p"
    .string "Vidste du at LORELEI har masser\n"
    .string "af stuffetdukker?\p"
    .string "Hver gang hun kommer tilbage til\n"
    .string "FIRE Ö vokser samlingen!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "Øh, koldt!\p"
    .string "Jeg lavede en slush ved at skrabe\n"
    .string "is inde i ICEFALL CAVE.\p"
    .string "Den er kold og läkker!$"

FourIsland_Text_LoreleisHouse::
    .string "LORELEIS HUS$"

