FourIsland_Text_IslandSign::
    .string "FIRE Ø\n"
    .string "Den varme, blå flodø$"

FourIsland_Text_LoreleiHasReturned::
    .string "LORELEI er vendt tilbage.\p"
    .string "Mon hun fandt bylivet for\n"
    .string "stressende?$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "LORELEI er rejst tilbage.\p"
    .string "Den LAPRAS hun har, forestiller jeg\n"
    .string "mig det er den hun mødte som barn.\p"
    .string "Jeg tror det var i ICEFALL CAVE\n"
    .string "at hun fangede den.\p"
    .string "Måske har den POKéMON været hos\n"
    .string "hende lige siden.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "{RIVAL}: Hej!\n"
    .string "{PLAYER}!\p"
    .string "Hvad laver du her på SEVII\n"
    .string "ISLANDS?\p"
    .string "Du burde holde op med at kopiere\n"
    .string "mig, ved du?\p"
    .string "Anyway, jeg har allerede fået mit\n"
    .string "POKéMON-ÆG, så jeg er færdig her.\p"
    .string "Ha, du ved sikkert ikke engang\n"
    .string "om POKéMON-ÆG.\p"
    .string "Sådan fylder du aldrig din\n"
    .string "NATIONAL POKéDEX.\p"
    .string "For resten så jeg en vi begge\n"
    .string "kender på denne ø.\p"
    .string "Hvorfor ikke kigge rundt hvis du\n"
    .string "er nysgerrig?\p"
    .string "Jeg har ikke tid at spilde.\p"
    .string "Vi ses!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .string "Øh, du fandt mig!\n"
    .string "Sig det ikke til LORELEI.\p"
    .string "Vidste du at LORELEI har masser\n"
    .string "af stuffetdukker?\p"
    .string "Hver gang hun kommer tilbage til\n"
    .string "FIRE Ø vokser samlingen!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "Øh, koldt!\p"
    .string "Jeg lavede en slush ved at skrabe\n"
    .string "is inde i ICEFALL CAVE.\p"
    .string "Den er kold og lækker!$"

FourIsland_Text_LoreleisHouse::
    .string "LORELEIS HUS$"

